import type { AudioFileRemark, AuthorizationPeriod, ComplianceCheck, SubstituteSong, User } from '../types';

export const mockUsers: User[] = [
  { id: 'user_1', name: '阿梅', role: 'tour_coordinator' },
  { id: 'user_2', name: '小李', role: 'ticket_staff' },
  { id: 'user_3', name: '王老师', role: 'reviewer' },
];

export const currentUser: User = mockUsers[0];

const now = new Date();

export const mockAudioRemarks: AudioFileRemark[] = [
  {
    id: 'audio_001',
    fileName: '01_晴天.mp3',
    songName: '晴天',
    artist: '周杰伦',
    duration: 269,
    fileHash: 'hash_001_abc123',
    remark: '演唱会开场曲，音乐版权已确认',
    tags: ['开场', '经典'],
    createdAt: new Date(now.getTime() - 86400000 * 7).toISOString(),
    updatedAt: new Date(now.getTime() - 86400000 * 2).toISOString(),
    createdBy: 'user_1',
    updatedBy: 'user_1',
    version: 2,
    isActive: true,
  },
  {
    id: 'audio_002',
    fileName: '02_稻香.mp3',
    songName: '稻香',
    artist: '周杰伦',
    duration: 223,
    fileHash: 'hash_002_def456',
    remark: '中场曲目，需要确认最新授权期限',
    tags: ['中场', '励志'],
    createdAt: new Date(now.getTime() - 86400000 * 7).toISOString(),
    updatedAt: new Date(now.getTime() - 86400000 * 5).toISOString(),
    createdBy: 'user_1',
    updatedBy: 'user_1',
    version: 1,
    isActive: true,
  },
  {
    id: 'audio_003',
    fileName: '03_七里香.mp3',
    songName: '七里香',
    artist: '周杰伦',
    duration: 299,
    fileHash: 'hash_003_ghi789',
    remark: '安可曲备选',
    tags: ['安可', '情歌'],
    createdAt: new Date(now.getTime() - 86400000 * 5).toISOString(),
    updatedAt: new Date(now.getTime() - 86400000 * 3).toISOString(),
    createdBy: 'user_1',
    updatedBy: 'user_1',
    version: 1,
    isActive: true,
  },
  {
    id: 'audio_004',
    fileName: '04_夜曲.mp3',
    songName: '夜曲',
    artist: '周杰伦',
    duration: 235,
    fileHash: 'hash_004_jkl012',
    remark: '新增曲目，正在等待授权确认',
    tags: ['新增', '经典'],
    createdAt: new Date(now.getTime() - 86400000 * 2).toISOString(),
    updatedAt: new Date(now.getTime() - 86400000 * 1).toISOString(),
    createdBy: 'user_1',
    updatedBy: 'user_1',
    version: 1,
    isActive: true,
  },
  {
    id: 'audio_005',
    fileName: '05_青花瓷.mp3',
    songName: '青花瓷',
    artist: '周杰伦',
    duration: 239,
    fileHash: 'hash_005_mno345',
    remark: '中国风曲目，已确认授权',
    tags: ['中国风', '经典'],
    createdAt: new Date(now.getTime() - 86400000 * 10).toISOString(),
    updatedAt: new Date(now.getTime() - 86400000 * 1).toISOString(),
    createdBy: 'user_1',
    updatedBy: 'user_1',
    version: 1,
    isActive: true,
  },
];

export const mockAuthorizationPeriods: AuthorizationPeriod[] = [
  {
    id: 'auth_001',
    audioFileId: 'audio_001',
    songName: '晴天',
    authorizedPlatform: ['全国电台', '网络流媒体'],
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    authorizedRegion: ['中国大陆'],
    status: 'valid',
    licenseNumber: 'LIC-2026-0001',
    remarks: '年度授权，覆盖所有巡演城市',
    createdAt: new Date(now.getTime() - 86400000 * 30).toISOString(),
    updatedAt: new Date(now.getTime() - 86400000 * 7).toISOString(),
    updatedBy: 'user_1',
    history: [],
  },
  {
    id: 'auth_002',
    audioFileId: 'audio_002',
    songName: '稻香',
    authorizedPlatform: ['全国电台'],
    startDate: '2026-01-01',
    endDate: '2026-06-30',
    authorizedRegion: ['中国大陆'],
    status: 'expiring',
    licenseNumber: 'LIC-2026-0002',
    remarks: '即将到期，需要续签',
    createdAt: new Date(now.getTime() - 86400000 * 30).toISOString(),
    updatedAt: new Date(now.getTime() - 86400000 * 3).toISOString(),
    updatedBy: 'user_1',
    history: [],
  },
  {
    id: 'auth_003',
    audioFileId: 'audio_003',
    songName: '七里香',
    authorizedPlatform: ['全国电台', '网络流媒体'],
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    authorizedRegion: ['中国大陆'],
    status: 'expired',
    licenseNumber: 'LIC-2025-0003',
    remarks: '授权已过期，紧急处理中',
    createdAt: new Date(now.getTime() - 86400000 * 60).toISOString(),
    updatedAt: new Date(now.getTime() - 86400000 * 10).toISOString(),
    updatedBy: 'user_1',
    history: [],
  },
  {
    id: 'auth_005',
    audioFileId: 'audio_005',
    songName: '青花瓷',
    authorizedPlatform: ['全国电台', '网络流媒体', '电视台'],
    startDate: '2026-03-01',
    endDate: '2027-02-28',
    authorizedRegion: ['中国大陆', '中国台湾'],
    status: 'valid',
    licenseNumber: 'LIC-2026-0005',
    remarks: '跨地区授权，覆盖港澳台',
    createdAt: new Date(now.getTime() - 86400000 * 20).toISOString(),
    updatedAt: new Date(now.getTime() - 86400000 * 5).toISOString(),
    updatedBy: 'user_1',
    history: [],
  },
];

export const mockComplianceChecks: ComplianceCheck[] = [
  {
    id: 'check_001',
    audioFileId: 'audio_001',
    songName: '晴天',
    artist: '周杰伦',
    checkDate: new Date(now.getTime() - 86400000 * 1).toISOString(),
    status: 'compliant',
    issues: [],
    checkedBy: 'user_1',
    remarks: '所有材料齐全，合规通过',
    keptReason: '开场必备曲目，听众喜爱度高，授权完整有效',
    missingMaterials: [],
    nextStep: '无需处理，正常进入歌单',
    nextStepOwner: 'tour_coordinator',
    isSubstitute: false,
    substituteVerified: true,
    createdAt: new Date(now.getTime() - 86400000 * 1).toISOString(),
    updatedAt: new Date(now.getTime() - 86400000 * 1).toISOString(),
    history: [
      {
        id: 'hist_001',
        timestamp: new Date(now.getTime() - 86400000 * 1).toISOString(),
        userId: 'user_1',
        userName: '阿梅',
        action: 'create',
        remark: '首次合规检查通过',
      },
    ],
  },
  {
    id: 'check_002',
    audioFileId: 'audio_002',
    songName: '稻香',
    artist: '周杰伦',
    checkDate: new Date(now.getTime() - 86400000 * 1).toISOString(),
    status: 'needs_review',
    issues: [
      {
        id: 'issue_001',
        type: 'expired_auth',
        severity: 'medium',
        description: '授权即将在2026-06-30到期，需要确认续签进度',
      },
    ],
    checkedBy: 'user_1',
    remarks: '授权即将到期，正在与版权方沟通续签',
    keptReason: '中场核心曲目，正能量主题符合巡演定位，正在续签授权',
    missingMaterials: ['续签授权书扫描件'],
    nextStep: '阿梅联系版权方确认续签时间，拿到新授权书后更新系统',
    nextStepOwner: 'tour_coordinator',
    isSubstitute: false,
    substituteVerified: true,
    createdAt: new Date(now.getTime() - 86400000 * 1).toISOString(),
    updatedAt: new Date(now.getTime() - 86400000 * 1).toISOString(),
    history: [
      {
        id: 'hist_002',
        timestamp: new Date(now.getTime() - 86400000 * 1).toISOString(),
        userId: 'user_1',
        userName: '阿梅',
        action: 'create',
        remark: '发现授权即将到期，标记为需要复核',
      },
    ],
  },
  {
    id: 'check_003',
    audioFileId: 'audio_003',
    songName: '七里香',
    artist: '周杰伦',
    checkDate: new Date(now.getTime() - 86400000 * 1).toISOString(),
    status: 'non_compliant',
    issues: [
      {
        id: 'issue_002',
        type: 'expired_auth',
        severity: 'high',
        description: '授权已于2025-12-31过期，目前无有效授权',
      },
    ],
    checkedBy: 'user_1',
    remarks: '授权已过期，暂不能使用',
    keptReason: '',
    missingMaterials: ['有效授权书'],
    nextStep: '版权过期，需要法务同事重新谈判授权',
    nextStepOwner: 'legal',
    isSubstitute: false,
    substituteVerified: true,
    createdAt: new Date(now.getTime() - 86400000 * 1).toISOString(),
    updatedAt: new Date(now.getTime() - 86400000 * 1).toISOString(),
    history: [
      {
        id: 'hist_003',
        timestamp: new Date(now.getTime() - 86400000 * 1).toISOString(),
        userId: 'user_1',
        userName: '阿梅',
        action: 'create',
        remark: '授权已过期，标记为不合规',
      },
    ],
  },
  {
    id: 'check_004',
    audioFileId: 'audio_004',
    songName: '夜曲',
    artist: '周杰伦',
    checkDate: new Date(now.getTime() - 43200000).toISOString(),
    status: 'pending',
    issues: [
      {
        id: 'issue_003',
        type: 'missing_auth',
        severity: 'high',
        description: '缺少授权文件，需要补充',
      },
    ],
    checkedBy: 'user_1',
    remarks: '新增曲目，等待授权材料',
    keptReason: '歌单需要更多元化，夜曲是经典代表作',
    missingMaterials: ['授权书', '版权确认函'],
    nextStep: '阿梅联系经纪人索取授权材料',
    nextStepOwner: 'tour_coordinator',
    isSubstitute: false,
    substituteVerified: true,
    createdAt: new Date(now.getTime() - 43200000).toISOString(),
    updatedAt: new Date(now.getTime() - 43200000).toISOString(),
    history: [
      {
        id: 'hist_004',
        timestamp: new Date(now.getTime() - 43200000).toISOString(),
        userId: 'user_1',
        userName: '阿梅',
        action: 'create',
        remark: '新增曲目，待补充材料',
      },
    ],
  },
  {
    id: 'check_005',
    audioFileId: 'audio_005',
    songName: '青花瓷',
    artist: '周杰伦',
    checkDate: new Date(now.getTime() - 3600000).toISOString(),
    status: 'needs_review',
    issues: [
      {
        id: 'issue_004',
        type: 'substitute_unverified',
        severity: 'medium',
        description: '临时替补歌曲，来源仅为微信群消息，需要票务同事复核确认',
      },
    ],
    checkedBy: 'user_1',
    remarks: '群里说临时换成这首，先记录，需要票务确认',
    keptReason: '曲目本身合规，但替换来源需要确认',
    missingMaterials: ['官方替换通知', '确认邮件'],
    nextStep: '请票务同事小李确认这个替换是否有正式通知',
    nextStepOwner: 'ticket_staff',
    isSubstitute: true,
    substituteSource: 'wechat_group',
    substituteVerified: false,
    createdAt: new Date(now.getTime() - 3600000).toISOString(),
    updatedAt: new Date(now.getTime() - 3600000).toISOString(),
    history: [
      {
        id: 'hist_005',
        timestamp: new Date(now.getTime() - 3600000).toISOString(),
        userId: 'user_1',
        userName: '阿梅',
        action: 'create',
        remark: '微信群消息说临时替换，先记录，待票务复核',
      },
    ],
  },
];

export const mockSubstituteSongs: SubstituteSong[] = [
  {
    id: 'sub_001',
    originalSongId: 'audio_003',
    originalSongName: '七里香',
    substituteSongName: '青花瓷',
    substituteArtist: '周杰伦',
    sourceType: 'wechat_group',
    sourceDetail: '2026-06-06 巡演工作群 @阿梅 说：明天七里香换成青花瓷',
    status: 'pending_review',
    notifiedBy: 'user_1',
    createdAt: new Date(now.getTime() - 3600000).toISOString(),
  },
];
