spring:
  datasource:
    url: jdbc:tc:mysql:8.0:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379

rollback:
  system:
    canary-stages: [10, 30, 50, 100]
    stage-wait-seconds: 1
    lock-timeout-seconds: 5
    idempotent-ttl-seconds: 60
    cache-ttl-seconds: 60
