const EQUIPMENT_CRITICALITY = {
  CRITICAL: 'CRITICAL',
  IMPORTANT: 'IMPORTANT',
  NORMAL: 'NORMAL'
};

const EQUIPMENT_CRITICALITY_WEIGHT = {
  CRITICAL: 3,
  IMPORTANT: 2,
  NORMAL: 1
};

const REPLACEMENT_STATUS = {
  COMPATIBLE: 'COMPATIBLE',
  LIMITED: 'LIMITED',
  INCOMPATIBLE: 'INCOMPATIBLE'
};

const RECEPTION_STATUS = {
  PENDING: 'PENDING',
  APPROVING: 'APPROVING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  FAILED: 'FAILED',
  NEED_ALTERNATIVE: 'NEED_ALTERNATIVE'
};

const STOCK_ALERT_LEVEL = {
  NORMAL: 'NORMAL',
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL'
};

module.exports = {
  EQUIPMENT_CRITICALITY,
  EQUIPMENT_CRITICALITY_WEIGHT,
  REPLACEMENT_STATUS,
  RECEPTION_STATUS,
  STOCK_ALERT_LEVEL
};
