const { getDatabase } = require('../database/init');
const { generateId } = require('../utils/idGenerator');
const { ORDER_STATUS, MODULES, DAMAGE_DEGREE, ADJUSTMENT_TYPE } = require('../utils/constants');
const { logAudit } = require('../utils/auditLogger');
const { getOrderById } = require('./orderService');
const { getChecklistItemById, getChecklistsByOrderId } = require('./checklistService');

const DAMAGE_CHARGE_RULES = {
  [DAMAGE_DEGREE.NONE]: 0,
  [DAMAGE_DEGREE.MINOR]: 0.1,
  [DAMAGE_DEGREE.MODERATE]: 0.3,
  [DAMAGE_DEGREE.SEVERE]: 0.7,
  [DAMAGE_DEGREE.TOTAL_LOSS]: 1.0
};

function validateDamageChargeData(data) {
  const errors = [];
  if (!data.order_id) errors.push('order_id不能为空');
  if (!data.item_name) errors.push('item_name不能为空');
  if (data.charge_amount === undefined || data.charge_amount < 0) {
    errors.push('charge_amount不能为空且不能为负数');
  }
  return errors;
}

function calculateDamageCharge(unitPrice, damageDegree, quantity = 1) {
  if (!unitPrice || !damageDegree) return 0;
  
  const ratio = DAMAGE_CHARGE_RULES[damageDegree] || 0;
  return parseFloat((unitPrice * ratio * quantity).toFixed(2));
}

function autoGenerateDamageCharges(orderId, operator) {
  const db = getDatabase();
  const order = getOrderById(orderId);

  if (!order) {
    throw new Error('订单不存在');
  }

  if (order.status !== ORDER_STATUS.CHECKING) {
    throw new Error('只有验收中状态的订单才能自动生成损坏扣费');
  }

  const checklists = getChecklistsByOrderId(orderId);
  const existingCharges = getDamageChargesByOrderId(orderId);
  const existingItemIds = new Set(existingCharges.map(c => c.checklist_item_id));

  const newCharges = [];

  for (const item of checklists) {
    if (item.is_damaged && item.unit_price && !existingItemIds.has(item.id)) {
      const chargeAmount = calculateDamageCharge(
        item.unit_price,
        item.damage_degree,
        item.actual_quantity || 1
      );

      if (chargeAmount > 0) {
        const charge = createDamageCharge({
          order_id: orderId,
          checklist_item_id: item.id,
          item_name: item.item_name,
          damage_degree: item.damage_degree,
          charge_amount: chargeAmount,
          charge_reason: `自动生成: ${item.damage_degree}损坏`
        }, operator, false);
        
        newCharges.push(charge);
      }
    }
  }

  return newCharges;
}

function createDamageCharge(data, operator, checkOrderStatus = true) {
  const db = getDatabase();
  const errors = validateDamageChargeData(data);

  if (errors.length > 0) {
    throw new Error('损坏扣费数据校验失败: ' + errors.join(', '));
  }

  if (checkOrderStatus) {
    const order = getOrderById(data.order_id);
    if (!order) {
      throw new Error('订单不存在');
    }
    if (order.status === ORDER_STATUS.COMPLETED) {
      throw new Error('订单已完成，不允许添加损坏扣费');
    }
  }

  const chargeId = generateId();
  const now = new Date().toISOString();

  const stmt = db.prepare(`
    INSERT INTO damage_charges (
      id, order_id, checklist_item_id, item_name, damage_degree,
      charge_amount, charge_reason, created_by, created_at,
      is_manual_adjustment, adjustment_reason
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  stmt.run(
    chargeId,
    data.order_id,
    data.checklist_item_id || null,
    data.item_name,
    data.damage_degree || null,
    data.charge_amount,
    data.charge_reason || null,
    operator,
    now,
    data.is_manual_adjustment ? 1 : 0,
    data.adjustment_reason || null
  );

  logAudit('CREATE', MODULES.DAMAGE, operator, {
    targetId: chargeId,
    targetType: 'damage_charge',
    newValues: data
  });

  return getDamageChargeById(chargeId);
}

function getDamageChargeById(chargeId) {
  const db = getDatabase();
  return db.prepare(`
    SELECT * FROM damage_charges WHERE id = ?
  `).get(chargeId);
}

function getDamageChargesByOrderId(orderId) {
  const db = getDatabase();
  return db.prepare(`
    SELECT * FROM damage_charges 
    WHERE order_id = ? 
    ORDER BY created_at ASC
  `).all(orderId);
}

function updateDamageCharge(chargeId, data, operator) {
  const db = getDatabase();
  const charge = getDamageChargeById(chargeId);

  if (!charge) {
    throw new Error('损坏扣费记录不存在');
  }

  const order = getOrderById(charge.order_id);
  if (order && order.status === ORDER_STATUS.COMPLETED) {
    throw new Error('订单已完成，不允许修改损坏扣费');
  }

  const allowedUpdates = [
    'item_name', 'damage_degree', 'charge_amount', 'charge_reason'
  ];

  const updateFields = [];
  const updateValues = [];
  const oldValues = {};
  const newValues = {};

  for (const key of allowedUpdates) {
    if (data[key] !== undefined) {
      updateFields.push(`${key} = ?`);
      updateValues.push(data[key]);
      oldValues[key] = charge[key];
      newValues[key] = data[key];
    }
  }

  if (updateFields.length === 0) {
    return charge;
  }

  updateValues.push(chargeId);

  db.prepare(`
    UPDATE damage_charges 
    SET ${updateFields.join(', ')}
    WHERE id = ?
  `).run(...updateValues);

  logAudit('UPDATE', MODULES.DAMAGE, operator, {
    targetId: chargeId,
    targetType: 'damage_charge',
    oldValues,
    newValues
  });

  return getDamageChargeById(chargeId);
}

function deleteDamageCharge(chargeId, operator) {
  const db = getDatabase();
  const charge = getDamageChargeById(chargeId);

  if (!charge) {
    throw new Error('损坏扣费记录不存在');
  }

  const order = getOrderById(charge.order_id);
  if (order && order.status === ORDER_STATUS.COMPLETED) {
    throw new Error('订单已完成，不允许删除损坏扣费');
  }

  db.prepare(`DELETE FROM damage_charges WHERE id = ?`).run(chargeId);

  logAudit('DELETE', MODULES.DAMAGE, operator, {
    targetId: chargeId,
    targetType: 'damage_charge',
    oldValues: charge
  });

  return true;
}

function getDamageTotal(orderId) {
  const db = getDatabase();
  const result = db.prepare(`
    SELECT COALESCE(SUM(charge_amount), 0) as total
    FROM damage_charges 
    WHERE order_id = ?
  `).get(orderId);

  return parseFloat(result.total);
}

function manuallyAdjustDamage(chargeId, newAmount, reason, operator) {
  if (!reason) {
    throw new Error('人工调整必须提供原因');
  }

  const charge = getDamageChargeById(chargeId);
  if (!charge) {
    throw new Error('损坏扣费记录不存在');
  }

  const db = getDatabase();
  const oldAmount = charge.charge_amount;
  const adjustmentAmount = newAmount - oldAmount;

  const transaction = db.transaction(() => {
    updateDamageCharge(chargeId, {
      charge_amount: newAmount,
      charge_reason: (charge.charge_reason || '') + ` [人工调整: ${reason}]`
    }, operator);

    const adjustmentId = generateId();
    db.prepare(`
      INSERT INTO manual_adjustments (
        id, order_id, adjustment_type, old_value, new_value,
        adjustment_amount, reason, adjusted_by, adjusted_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    `).run(
      adjustmentId,
      charge.order_id,
      ADJUSTMENT_TYPE.DAMAGE,
      oldAmount,
      newAmount,
      adjustmentAmount,
      reason,
      operator,
      new Date().toISOString()
    );
  });

  transaction();

  logAudit('MANUAL_ADJUST', MODULES.DAMAGE, operator, {
    targetId: chargeId,
    targetType: 'damage_charge',
    oldValues: { charge_amount: oldAmount },
    newValues: { charge_amount: newAmount },
    remark: reason
  });

  return getDamageChargeById(chargeId);
}

module.exports = {
  validateDamageChargeData,
  calculateDamageCharge,
  autoGenerateDamageCharges,
  createDamageCharge,
  getDamageChargeById,
  getDamageChargesByOrderId,
  updateDamageCharge,
  deleteDamageCharge,
  getDamageTotal,
  manuallyAdjustDamage,
  DAMAGE_CHARGE_RULES
};
