export enum BatchType {
  REGISTRATION_CSV = 'REGISTRATION_CSV',
  WAITLIST_JSON = 'WAITLIST_JSON',
  ATTENDANCE_CSV = 'ATTENDANCE_CSV',
  BLACKLIST_CSV = 'BLACKLIST_CSV',
}

export enum BatchStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  PROCESSED = 'PROCESSED',
  REJECTED = 'REJECTED',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
}

export enum RegistrationSource {
  DIRECT = 'DIRECT',
  WAITLIST_PROMOTED = 'WAITLIST_PROMOTED',
  MANUAL = 'MANUAL',
}

export enum RegistrationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  WAITLISTED = 'WAITLISTED',
  PROMOTED = 'PROMOTED',
  CANCELLED = 'CANCELLED',
  NEEDS_MATERIALS = 'NEEDS_MATERIALS',
}

export enum AttendanceStatus {
  NOT_SIGNED = 'NOT_SIGNED',
  SIGNED_IN = 'SIGNED_IN',
  SIGNED_OUT = 'SIGNED_OUT',
  ABSENT = 'ABSENT',
}

export enum ProcessingAction {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  PROMOTE = 'PROMOTE',
  CANCEL = 'CANCEL',
  REQUEST_MATERIALS = 'REQUEST_MATERIALS',
  MARK_DUPLICATE = 'MARK_DUPLICATE',
  MARK_BLACKLISTED = 'MARK_BLACKLISTED',
  REVIEW = 'REVIEW',
}
