const PresetStatus = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  FROZEN: 'FROZEN',
  ACTIVE: 'ACTIVE'
};

const SceneStatus = {
  UNLOCKED: 'UNLOCKED',
  LOCKED: 'LOCKED'
};

const ApprovalStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

const ErrorCode = {
  SCENE_LOCKED: 'SCENE_LOCKED',
  SCENE_NOT_FOUND: 'SCENE_NOT_FOUND',
  PRESET_NOT_FOUND: 'PRESET_NOT_FOUND',
  PRESET_ALREADY_EXISTS: 'PRESET_ALREADY_EXISTS',
  INVALID_PRESET_STATUS: 'INVALID_PRESET_STATUS',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  APPROVAL_NOT_FOUND: 'APPROVAL_NOT_FOUND',
  MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
  INVALID_LIGHT_POSITION: 'INVALID_LIGHT_POSITION',
  DUPLICATE_VERSION: 'DUPLICATE_VERSION',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  FROZEN_PRESET_CANNOT_MODIFY: 'FROZEN_PRESET_CANNOT_MODIFY',
  ACTIVE_PRESET_CANNOT_ROLLBACK: 'ACTIVE_PRESET_CANNOT_ROLLBACK',
  INVALID_REQUEST: 'INVALID_REQUEST'
};

module.exports = {
  PresetStatus,
  SceneStatus,
  ApprovalStatus,
  ErrorCode
};
