SAMPLES = [
    {
        "id": "S001",
        "content": "请将以下英文翻译为中文：The quick brown fox jumps over the lazy dog.",
        "domain": "翻译",
        "reference_result": "那只敏捷的棕色狐狸跳过了那只懒狗。",
        "model_output": "那只敏捷的棕色狐狸跳过了那只懒狗。",
        "model_confidence": 0.95,
        "human_label": None,
        "source": "翻译评测集v2",
        "import_batch": "batch_2026_01",
    },
    {
        "id": "S002",
        "content": "请将以下英文翻译为中文：The quick brown fox jumps over the lazy dog.",
        "domain": "翻译",
        "reference_result": "那只敏捷的棕色狐狸跳过了那只懒狗。",
        "model_output": "那只敏捷的棕狐跳过了懒狗。",
        "model_confidence": 0.88,
        "human_label": None,
        "source": "翻译评测集v2",
        "import_batch": "batch_2026_01",
    },
    {
        "id": "S003",
        "content": "以下哪个选项是正确的？A.地球是平的 B.地球是圆的 C.地球是三角形的",
        "domain": "常识问答",
        "reference_result": "B",
        "model_output": "B",
        "model_confidence": 0.99,
        "human_label": None,
        "source": "常识问答集v1",
        "import_batch": "batch_2026_01",
    },
    {
        "id": "S004",
        "content": "请判断以下文章的情感倾向：今天天气真好，心情特别愉快！",
        "domain": "情感分析",
        "reference_result": "正面",
        "model_output": "负面",
        "model_confidence": 0.35,
        "human_label": "正面",
        "source": "情感评测集v3",
        "import_batch": "batch_2026_01",
    },
    {
        "id": "S005",
        "content": "请总结以下段落的要点：人工智能技术在医疗领域的应用日益广泛...",
        "domain": "摘要生成",
        "reference_result": None,
        "model_output": "AI在医疗领域应用广泛，包括诊断辅助和药物研发。",
        "model_confidence": 0.72,
        "human_label": None,
        "source": "摘要评测集v1",
        "import_batch": "batch_2026_01",
    },
    {
        "id": "S006",
        "content": "以下代码的输出是什么？print(2**3)",
        "domain": "代码生成",
        "reference_result": "8",
        "model_output": "6",
        "model_confidence": 0.45,
        "human_label": "8",
        "source": "代码评测集v2",
        "import_batch": "batch_2026_01",
    },
    {
        "id": "S007",
        "content": "请将以下句子改写为更正式的表达：这个东西挺好的。",
        "domain": "文本改写",
        "reference_result": "此产品品质优良。",
        "model_output": "这个物品相当不错。",
        "model_confidence": 0.60,
        "human_label": None,
        "source": "改写评测集v1",
        "import_batch": "batch_2026_01",
    },
    {
        "id": "S008",
        "content": "以下哪个数是质数？A.4 B.9 C.7 D.15",
        "domain": "数学推理",
        "reference_result": "C",
        "model_output": None,
        "model_confidence": None,
        "human_label": None,
        "source": "数学评测集v1",
        "import_batch": "batch_2026_01",
    },
    {
        "id": "S009",
        "content": "请判断以下文章的情感倾向：这部电影一般般，不太好看也不太难看。",
        "domain": "情感分析",
        "reference_result": "中性",
        "model_output": "负面",
        "model_confidence": 0.52,
        "human_label": "中性",
        "source": "情感评测集v3",
        "import_batch": "batch_2026_01",
    },
    {
        "id": "S010",
        "content": "请将以下句子翻译成英文：今天天气怎么样？",
        "domain": "翻译",
        "reference_result": None,
        "model_output": None,
        "model_confidence": None,
        "human_label": None,
        "source": "翻译评测集v2",
        "import_batch": "batch_2026_01",
    },
    {
        "id": "S011",
        "content": "请回答：水的化学式是什么？",
        "domain": "常识问答",
        "reference_result": "H2O",
        "model_output": "H2O",
        "model_confidence": 0.97,
        "human_label": None,
        "source": "常识问答集v1",
        "import_batch": "batch_2026_01",
    },
    {
        "id": "S012",
        "content": "以下代码有什么bug？def add(a, b): return a - b",
        "domain": "代码生成",
        "reference_result": "应该用+而不是-",
        "model_output": "运算符错误，应该使用加法",
        "model_confidence": 0.85,
        "human_label": "运算符错误，应使用+号",
        "source": "代码评测集v2",
        "import_batch": "batch_2026_01",
    },
    {
        "id": "S013",
        "content": "请回答：1+1等于几？",
        "domain": "数学推理",
        "reference_result": "2",
        "model_output": "2",
        "model_confidence": 0.99,
        "human_label": None,
        "source": "边界样本集",
        "import_batch": "batch_2026_01",
    },
    {
        "id": "S014",
        "content": "请回答：",
        "domain": None,
        "reference_result": None,
        "model_output": None,
        "model_confidence": None,
        "human_label": None,
        "source": "边界样本集",
        "import_batch": "batch_2026_01",
        "notes": "边界记录：内容为空",
    },
]


EXTRA_SAMPLES = [
    {
        "id": "S015",
        "content": "请将以下英文翻译为中文：Artificial intelligence is transforming the world.",
        "domain": "翻译",
        "reference_result": "人工智能正在改变世界。",
        "model_output": "人工智能正在改变世界。",
        "model_confidence": 0.91,
        "human_label": None,
        "source": "翻译评测集v2",
        "import_batch": "batch_2026_02",
    },
    {
        "id": "S016",
        "content": "请判断以下文章的情感倾向：服务态度极差，再也不会来了。",
        "domain": "情感分析",
        "reference_result": "负面",
        "model_output": "正面",
        "model_confidence": 0.28,
        "human_label": None,
        "source": "情感评测集v3",
        "import_batch": "batch_2026_02",
    },
    {
        "id": "S017",
        "content": "以下哪个选项是正确的？A.地球是平的 B.地球是圆的 C.地球是三角形的",
        "domain": "常识问答",
        "reference_result": "B",
        "model_output": "B",
        "model_confidence": 0.98,
        "human_label": None,
        "source": "常识问答集v2",
        "import_batch": "batch_2026_02",
        "notes": "跨库去重测试：内容与S003相同，ID不同",
    },
]
