[PHP]
display_errors = On
error_reporting = E_ALL
log_errors = Off

[Session]
session.use_only_cookies = Off

[MySQL]
mysql.default_password = "mypassword"

[Mail]
sendmail_from = admin@example.com
smtp_password = "emailpassword"
