const fs = require('fs');

const lines = [
'#!/bin/bash',
'set -e',
'',
'PORT="${TEST_PORT:-3000}"',
'BASE="http://localhost:${PORT}/api"',
'',
'echo "========== 市政运维服务核心功能验证 =========="',
'echo "测试地址: $BASE"',
'echo ""',
'',
'echo "[1/7] 健康检查..."',
'HEALTH=$(curl -s "$BASE/health")',
'if echo "$HEALTH" | grep -q \'"success":true\'; then',
'  echo "  PASS: 服务运行正常"',
'else',
'  echo "  FAIL: 健康检查失败"',
'  exit 1',
'fi',
'',
'echo "[2/7] 导入告警CSV..."',
'CSV_IMPORT=$(curl -s -X POST "$BASE/import/alarm-csv" -F "file=@examples/test_alarm.csv;filename=a.csv" -F "created_by=测试" -F "source_name=验证")',
'CSV_RECORD=$(echo "$CSV_IMPORT" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'data\'][\'records\'][0][\'record_no\'])" 2>/dev/null || echo "")',
'if [ -n "$CSV_RECORD" ]; then echo "  PASS: CSV导入成功 - $CSV_RECORD"; else echo "  FAIL: CSV导入失败"; exit 1; fi',
'',
'echo "[3/7] 导入巡查JSON..."',
'JSON_IMPORT=$(curl -s -X POST "$BASE/import/inspection-json" -H "Content-Type: application/json" -d \'{"data":[{"pole_no":"V001","light_no":"LD001","issue_type":"灯杆倾斜","level":"严重","location":"验证路","description":"验证","maintenance_team":"验证队","inspector":"验证","inspection_time":"2024-05-21 14:00:00"}],"created_by":"测试","source_name":"验证"}\')',
'JSON_RECORD=$(echo "$JSON_IMPORT" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'data\'][\'records\'][0][\'record_no\'])" 2>/dev/null || echo "")',
'if [ -n "$JSON_RECORD" ]; then echo "  PASS: JSON导入成功 - $JSON_RECORD"; else echo "  FAIL: JSON导入失败"; exit 1; fi',
'',
'echo "[4/7] 导入维修单..."',
'ORDER_IMPORT=$(curl -s -X POST "$BASE/import/work-order" -H "Content-Type: application/json" -d \'{"order_data":{"order_no":"WXV001","pole_no":"V002","light_no":"LD001","repair_type":"灯泡更换","location":"验证路","description":"验证","maintenance_team":"验证队","worker":"验证","repair_time":"2024-05-22 10:00:00"},"created_by":"测试"}\')',
'ORDER_RECORD=$(echo "$ORDER_IMPORT" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'data\'][\'record\'][\'record_no\'])" 2>/dev/null || echo "")',
'if [ -n "$ORDER_RECORD" ]; then echo "  PASS: 维修单导入成功 - $ORDER_RECORD"; else echo "  FAIL: 维修单导入失败"; exit 1; fi',
'',
'echo "[5/7] 验证处理流程..."',
'PROCESS=$(curl -s -X POST "$BASE/records/process" -H "Content-Type: application/json" -d "{\\"record_no\\":\\"$CSV_RECORD\\",\\"status\\":\\"processing\\",\\"action_reason\\":\\"验证派单\\",\\"action_by\\":\\"验证主管\\"}")',
'PS=$(echo "$PROCESS" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'data\'][\'status\'])" 2>/dev/null || echo "")',
'if [ "$PS" = "processing" ]; then echo "  PASS: 标记处理成功"; else echo "  FAIL: 标记处理失败"; exit 1; fi',
'',
'RETURNED=$(curl -s -X POST "$BASE/records/return" -H "Content-Type: application/json" -d "{\\"record_no\\":\\"$JSON_RECORD\\",\\"return_reason\\":\\"验证信息不明确\\",\\"action_by\\":\\"验证审核\\"}")',
'RS=$(echo "$RETURNED" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'data\'][\'status\'])" 2>/dev/null || echo "")',
'if [ "$RS" = "returned" ]; then echo "  PASS: 退回修改成功"; else echo "  FAIL: 退回修改失败"; exit 1; fi',
'',
'RECHECK=$(curl -s -X POST "$BASE/special/recheck" -H "Content-Type: application/json" -d "{\\"record_no\\":\\"$ORDER_RECORD\\",\\"recheck_result\\":\\"pass\\",\\"recheck_by\\":\\"验证质检\\",\\"recheck_reason\\":\\"验证修复完成\\"}")',
'RRS=$(echo "$RECHECK" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'data\'][\'recheck_result\'])" 2>/dev/null || echo "")',
'if [ "$RRS" = "pass" ]; then echo "  PASS: 修复复测成功"; else echo "  FAIL: 修复复测失败"; exit 1; fi',
'',
'echo "[6/7] 验证查询和追溯功能..."',
'TOTAL=$(curl -s "$BASE/records" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'total\'])" 2>/dev/null || echo "0")',
'echo "  总记录数: $TOTAL"',
'TRACE=$(curl -s "$BASE/records/$CSV_RECORD/trace")',
'HC=$(echo "$TRACE" | python3 -c "import sys,json; print(len(json.load(sys.stdin)[\'data\'][\'processing_history\']))" 2>/dev/null || echo "0")',
'if [ "$HC" -gt 0 ]; then echo "  PASS: 追溯链路正常 ($HC 条历史记录)"; else echo "  FAIL: 追溯链路异常"; exit 1; fi',
'',
'echo "[7/7] 验证导出功能..."',
'TEAM=$(python3 -c "import urllib.parse; print(urllib.parse.quote(\'维修一队\'))")',
'QC=$(curl -s "$BASE/records?maintenance_team=$TEAM" | python3 -c "import sys,json; print(json.load(sys.stdin)[\'total\'])" 2>/dev/null || echo "0")',
'EXPORT=$(curl -s "$BASE/export/records?maintenance_team=$TEAM")',
'EC=$(echo "$EXPORT" | grep -v "^$" | tail -n +2 | wc -l | tr -d " ")',
'echo "  查询结果数: $QC, 导出行数: $EC"',
'if [ "$QC" = "$EC" ]; then echo "  PASS: 导出数量与查询结果一致"; else echo "  WARN: 数量有差异"; fi',
'',
'echo ""',
'echo "========== 所有核心功能验证通过！ =========="',
];

fs.writeFileSync('test.sh', lines.join('\n'));
fs.chmodSync('test.sh', 0o755);
console.log('test.sh created with ' + lines.length + ' lines');
