#!/usr/bin/env python3

cli_code = [
    '#!/usr/bin/env node',
    '',
    'const fs = require("fs");',
    'const { Command } = require("commander");',
    '',
    'function ipToBigint(ip) {',
    '  const parts = ip.split(".").map(Number);',
    '  if (parts.length !== 4 || parts.some(p => isNaN(p) || p < 0 || p > 255)) {',
    '    throw new Error("Invalid IP: " + ip);',
    '  }',
    '  return (BigInt(parts[0]) << 24n) | (BigInt(parts[1]) << 16n) | (BigInt(parts[2]) << 8n) | BigInt(parts[3]);',
    '}',
    '',
    'function bigintToIp(n) {',
    '  return [',
    '    Number((n >> 24n) & 0xffn),',
    '    Number((n >> 16n) & 0xffn),',
    '    Number((n >> 8n) & 0xffn),',
    '    Number(n & 0xffn)',
    '  ].join(".");',
    '}',
    '',
    'function parseCidr(cidr) {',
    '  const [ip, prefixStr] = cidr.split("/");',
    '  const prefix = parseInt(prefixStr || "32", 10);',
    '  if (isNaN(prefix) || prefix < 0 || prefix > 32) {',
    '    throw new Error("Invalid CIDR prefix: " + prefixStr);',
    '  }',
    '  const ipNum = ipToBigint(ip);',
    '  const mask = prefix === 0 ? 0n : (0xffffffffn << BigInt(32 - prefix));',
    '  const start = ipNum & mask;',
    '  const end = start | (~mask & 0xffffffffn);',
    '  return { start, end };',
    '}',
    '',
    'function bigintToCidr(start, end) {',
    '  if (start === end) return bigintToIp(start) + "/32";',
    '  let prefix = 32;',
    '  while (prefix > 0) {',
    '    const mask = prefix === 0 ? 0n : (0xffffffffn << BigInt(32 - prefix));',
    '    if ((start & mask) === start && (start | (~mask & 0xffffffffn)) >= end) break;',
    '    prefix--;',
    '  }',
    '  return bigintToIp(start) + "/" + prefix;',
    '}',
    '',
    'function parseLine(line, lineNumber) {',
    '  const trimmed = line.trim();',
    '  if (!trimmed || trimmed.startsWith("#")) return null;',
    '  const parts = trimmed.split(/[,\\t]/).map(p => p.trim());',
    '  if (parts.length < 4) {',
    '    return { lineNumber, rawContent: line, reason: "Not enough fields: need 4, got " + parts.length };',
    '  }',
    '  const [cidr, team, purpose, environment] = parts;',
    '  if (!cidr) {',
    '    return { lineNumber, rawContent: line, reason: "CIDR cannot be empty" };',
    '  }',
    '  try {',
    '    const { start, end } = parseCidr(cidr);',
    '    return { lineNumber, cidr, team: team || "Unspecified", purpose: purpose || "Unspecified", environment: environment || "Unspecified", startIp: start, endIp: end };',
    '  } catch (e) {',
    '    return { lineNumber, rawContent: line, reason: "CIDR parse failed: " + e.message };',
    '  }',
    '}',
    '',
    'function parseInput(content) {',
    '  const lines = content.split("\\n");',
    '  const valid = [], bad = [];',
    '  lines.forEach((line, index) => {',
    '    const result = parseLine(line, index + 1);',
    '    if (result && "cidr" in result) valid.push(result);',
    '    else if (result && "reason" in result) bad.push(result);',
    '  });',
    '  return { valid, bad };',
    '}',
    '',
    'function detectOverlaps(entries) {',
    '  const sorted = [...entries].sort((a, b) => {',
    '    if (a.startIp < b.startIp) return -1;',
    '    if (a.startIp > b.startIp) return 1;',
    '    return 0;',
    '  });',
    '  const pairs = [];',
    '  for (let i = 0; i < sorted.length; i++) {',
    '    for (let j = i + 1; j < sorted.length; j++) {',
    '      const e1 = sorted[i], e2 = sorted[j];',
    '      if (e2.startIp > e1.endIp) break;',
    '      const overlapStart = e1.startIp > e2.startIp ? e1.startIp : e2.startIp;',
    '      const overlapEnd = e1.endIp < e2.endIp ? e1.endIp : e2.endIp;',
    '      if (overlapStart <= overlapEnd) {',
    '        pairs.push({ entry1: e1, entry2: e2, overlapStart, overlapEnd, overlapCidr: bigintToCidr(overlapStart, overlapEnd) });',
    '      }',
    '    }',
    '  }',
    '  return pairs;',
    '}',
    '',
    'function generateTeamSummaries(entries, overlaps) {',
    '  const teamMap = new Map();',
    '  entries.forEach(e => {',
    '    if (!teamMap.has(e.team)) teamMap.set(e.team, { entries: [], overlappingCount: 0 });',
    '    teamMap.get(e.team).entries.push(e);',
    '  });',
    '  overlaps.forEach(p => {',
    '    const t1 = teamMap.get(p.entry1.team), t2 = teamMap.get(p.entry2.team);',
    '    t1.overlappingCount++;',
    '    if (p.entry1.team !== p.entry2.team) t2.overlappingCount++;',
    '  });',
    '  return Array.from(teamMap.entries()).map(([team, data]) => ({',
    '    team, totalRanges: data.entries.length,',
    '    environments: [...new Set(data.entries.map(e => e.environment))],',
    '    purposes: [...new Set(data.entries.map(e => e.purpose))],',
    '    overlappingCount: data.overlappingCount',
    '  })).sort((a, b) => b.overlappingCount - a.overlappingCount);',
    '}',
    '',
    'function printTerminalSummary(result) {',
    '  console.log("");',
    '  console.log("=== IP Overlap Analysis Summary ===");',
    '  console.log("");',
    '  console.log("Total entries: " + result.totalEntries);',
    '  console.log("Valid entries: " + result.validEntries);',
    '  console.log("Bad entries: " + result.badEntries.length + "");',
    '  console.log("");',
    '  if (result.overlappingPairs.length > 0) {',
    '    console.log("WARNING: Found " + result.overlappingPairs.length + " overlaps!");',
    '    console.log("");',
    '    result.overlappingPairs.forEach((p, idx) => {',
    '      console.log("Overlap #" + (idx + 1) + ":");',
    '      console.log("  Range: " + p.overlapCidr);',
    '      console.log("  Entry 1 [line " + p.entry1.lineNumber + "]: " + p.entry1.cidr + " | " + p.entry1.team + " | " + p.entry1.purpose + " | " + p.entry1.environment);',
    '      console.log("  Entry 2 [line " + p.entry2.lineNumber + "]: " + p.entry2.cidr + " | " + p.entry2.team + " | " + p.entry2.purpose + " | " + p.entry2.environment);',
    '      console.log("");',
    '    });',
    '  } else {',
    '    console.log("OK: No IP overlaps detected");',
    '    console.log("");',
    '  }',
    '  if (result.badEntries.length > 0) {',
    '    console.log("ERROR: Bad entries (" + result.badEntries.length + "):");',
    '    result.badEntries.forEach(b => console.log("  [line " + b.lineNumber + "] " + b.reason + ": " + b.rawContent.trim()));',
    '    console.log("");',
    '  }',
    '  console.log("=== Team Statistics ===");',
    '  result.teamSummaries.forEach(ts => {',
    '    const status = ts.overlappingCount > 0 ? "WARNING" : "OK";',
    '    console.log(status + " " + ts.team + ": " + ts.totalRanges + " ranges, " + ts.overlappingCount + " overlaps");',
    '    console.log("  Environments: " + ts.environments.join(", "));',
    '    console.log("  Purposes: " + ts.purposes.join(", "));',
    '  });',
    '  console.log("");',
    '}',
    '',
    'function writeJsonOutput(result, filePath) {',
    '  const jsonData = {',
    '    generatedAt: new Date().toISOString(),',
    '    summary: { totalEntries: result.totalEntries, validEntries: result.validEntries, badEntriesCount: result.badEntries.length, overlappingPairsCount: result.overlappingPairs.length },',
    '    overlappingPairs: result.overlappingPairs.map(p => ({',
    '      overlapCidr: p.overlapCidr, overlapStartIp: bigintToIp(p.overlapStart), overlapEndIp: bigintToIp(p.overlapEnd),',
    '      entry1: { line: p.entry1.lineNumber, cidr: p.entry1.cidr, team: p.entry1.team, purpose: p.entry1.purpose, environment: p.entry1.environment },',
    '      entry2: { line: p.entry2.lineNumber, cidr: p.entry2.cidr, team: p.entry2.team, purpose: p.entry2.purpose, environment: p.entry2.environment }',
    '    })),',
    '    badEntries: result.badEntries,',
    '    teamSummaries: result.teamSummaries',
    '  };',
    '  fs.writeFileSync(filePath, JSON.stringify(jsonData, null, 2), "utf8");',
    '  console.log("JSON output written to: " + filePath);',
    '}',
    '',
    'function writeMarkdownReport(result, filePath) {',
    '  const hasOverlaps = result.overlappingPairs.length > 0;',
    '  const hasBadEntries = result.badEntries.length > 0;',
    '  let md = "# IP Overlap Analysis Report\\n\\n";',
    '  md += "Generated at: " + new Date().toLocaleString("en-US") + "\\n\\n";',
    '  md += "## Summary\\n\\n| Metric | Value |\\n|--------|-------|\\n";',
    '  md += "| Total entries | " + result.totalEntries + " |\\n";',
    '  md += "| Valid entries | " + result.validEntries + " |\\n";',
    '  md += "| Bad entries | " + result.badEntries.length + " |\\n";',
    '  md += "| Overlapping pairs | " + result.overlappingPairs.length + " |\\n\\n";',
    '  md += "**Conclusion**: " + (hasOverlaps ? "**WARNING: Found IP overlaps requiring attention**" : "**OK: No IP overlaps detected**") + "\\n\\n";',
    '  if (hasOverlaps) {',
    '    md += "## Overlap Details\\n\\n| # | Overlap Range | Entry 1 | Entry 2 |\\n|---|---------------|---------|---------|\\n";',
    '    result.overlappingPairs.forEach((p, idx) => {',
    '      md += "| " + (idx + 1) + " | " + p.overlapCidr + " | Line " + p.entry1.lineNumber + ": " + p.entry1.cidr + "<br>Team: " + p.entry1.team + "<br>Purpose: " + p.entry1.purpose + "<br>Env: " + p.entry1.environment + " | Line " + p.entry2.lineNumber + ": " + p.entry2.cidr + "<br>Team: " + p.entry2.team + "<br>Purpose: " + p.entry2.purpose + "<br>Env: " + p.entry2.environment + " |\\n";',
    '    });',
    '    md += "\\n";',
    '  }',
    '  md += "## Team Statistics\\n\\n| Team | Ranges | Environments | Purposes | Overlaps | Status |\\n|------|--------|--------------|----------|----------|--------|\\n";',
    '  result.teamSummaries.forEach(ts => {',
    '    const status = ts.overlappingCount > 0 ? "WARNING" : "OK";',
    '    md += "| " + ts.team + " | " + ts.totalRanges + " | " + ts.environments.join(", ") + " | " + ts.purposes.join(", ") + " | " + ts.overlappingCount + " | " + status + " |\\n";',
    '  });',
    '  if (hasBadEntries) {',
    '    md += "\\n## Bad Entries\\n\\n| Line | Reason | Content |\\n|------|--------|---------|\\n";',
    '    result.badEntries.forEach(b => md += "| " + b.lineNumber + " | " + b.reason + " | " + b.rawContent.trim() + " |\\n"));',
    '  }',
    '  md += "\\n---\\n*Generated by ip-overlap-cli*\\n";',
    '  fs.writeFileSync(filePath, md, "utf8");',
    '  console.log("Markdown report written to: " + filePath);',
    '}',
    '',
    'const program = new Command();',
    'program.name("ip-overlap").description("IP overlap detection CLI tool").version("1.0.0");',
    'program.requiredOption("-i, --input <path>", "Input CSV file path");',
    'program.option("-j, --json <path>", "Output JSON result file path");',
    'program.option("-m, --markdown <path>", "Output Markdown report path");',
    'program.parse(process.argv);',
    'const options = program.opts();',
    '',
    'function main() {',
    '  if (!fs.existsSync(options.input)) {',
    '    console.error("ERROR: Input file does not exist: " + options.input);',
    '    return 1;',
    '  }',
    '  const content = fs.readFileSync(options.input, "utf8");',
    '  const { valid, bad } = parseInput(content);',
    '  const overlappingPairs = detectOverlaps(valid);',
    '  const teamSummaries = generateTeamSummaries(valid, overlappingPairs);',
    '  const result = { totalEntries: valid.length + bad.length, validEntries: valid.length, badEntries: bad, overlappingPairs, teamSummaries };',
    '  printTerminalSummary(result);',
    '  if (options.json) writeJsonOutput(result, options.json);',
    '  if (options.markdown) writeMarkdownReport(result, options.markdown);',
    '  return overlappingPairs.length > 0 || bad.length > 0 ? 2 : 0;',
    '}',
    '',
    'try { process.exit(main()); }',
    'catch (e) { console.error("ERROR: Execution failed:", e.message); process.exit(1); }',
    ''
]

with open('index.js', 'w') as f:
    f.write('\n'.join(cli_code))

print(f"Created index.js with {len(cli_code)} lines")
