import { LevelConfig } from '@/types/game';

export const levels: LevelConfig[] = [
  {
    id: 1,
    name: '新手夜市',
    description: '3个摊位，容量宽松，熟悉基本操作',
    maxRounds: 5,
    roundDuration: 30,
    maxElectricity: 200,
    maxComplaints: 10,
    maxSmoke: 80,
    targetMoney: 500,
    idealElectricity: 150,
    stallConfigs: [
      {
        name: '老王烧烤',
        type: 'food',
        position: { x: 150, y: 200 },
        maxPower: 100,
        smokeCoefficient: 0.8,
        color: '#FF6B35',
        emoji: '🍢',
      },
      {
        name: '阿婆糖水',
        type: 'drink',
        position: { x: 400, y: 200 },
        maxPower: 60,
        smokeCoefficient: 0.2,
        color: '#2EC4B6',
        emoji: '🥤',
      },
      {
        name: '小李手工',
        type: 'craft',
        position: { x: 650, y: 200 },
        maxPower: 40,
        smokeCoefficient: 0.1,
        color: '#9B5DE5',
        emoji: '🎨',
      },
    ],
    randomEvents: [
      {
        id: 'power_surge',
        name: '用电高峰',
        description: '夜市用电高峰，容量临时下降',
        probability: 0.25,
        effect: {
          electricityDelta: 30,
          message: '⚠️ 用电高峰！总容量压力增加',
        },
      },
      {
        id: 'inspector',
        name: '城管巡查',
        description: '城管来巡查，油烟检查更严格',
        probability: 0.2,
        effect: {
          complaintDelta: 3,
          message: '🚨 城管巡查！油烟管控更严格',
        },
      },
      {
        id: 'festival',
        name: '节日客流',
        description: '节日期间客流增多，收益翻倍',
        probability: 0.2,
        effect: {
          moneyDelta: 100,
          message: '🎉 节日客流！收益增加',
        },
      },
    ],
  },
  {
    id: 2,
    name: '美食一条街',
    description: '5个摊位，油烟冲突严重，考验平衡能力',
    maxRounds: 8,
    roundDuration: 25,
    maxElectricity: 300,
    maxComplaints: 8,
    maxSmoke: 100,
    targetMoney: 1000,
    idealElectricity: 240,
    stallConfigs: [
      {
        name: '老王烧烤',
        type: 'food',
        position: { x: 100, y: 180 },
        maxPower: 100,
        smokeCoefficient: 0.9,
        color: '#FF6B35',
        emoji: '🍢',
      },
      {
        name: '张记烤鱼',
        type: 'food',
        position: { x: 250, y: 350 },
        maxPower: 90,
        smokeCoefficient: 0.85,
        color: '#F4A261',
        emoji: '🐟',
      },
      {
        name: '阿婆糖水',
        type: 'drink',
        position: { x: 400, y: 180 },
        maxPower: 50,
        smokeCoefficient: 0.15,
        color: '#2EC4B6',
        emoji: '🥤',
      },
      {
        name: '潮汕粥铺',
        type: 'food',
        position: { x: 550, y: 350 },
        maxPower: 70,
        smokeCoefficient: 0.5,
        color: '#E76F51',
        emoji: '🍲',
      },
      {
        name: '小李手工',
        type: 'craft',
        position: { x: 700, y: 180 },
        maxPower: 40,
        smokeCoefficient: 0.1,
        color: '#9B5DE5',
        emoji: '🎨',
      },
    ],
    randomEvents: [
      {
        id: 'power_surge',
        name: '用电高峰',
        description: '夜市用电高峰，容量临时下降',
        probability: 0.3,
        effect: {
          electricityDelta: 40,
          message: '⚠️ 用电高峰！总容量压力增加',
        },
      },
      {
        id: 'inspector',
        name: '城管巡查',
        description: '城管来巡查，油烟检查更严格',
        probability: 0.3,
        effect: {
          complaintDelta: 4,
          message: '🚨 城管巡查！油烟管控更严格',
        },
      },
      {
        id: 'festival',
        name: '节日客流',
        description: '节日期间客流增多，收益翻倍',
        probability: 0.25,
        effect: {
          moneyDelta: 150,
          message: '🎉 节日客流！收益增加',
        },
      },
      {
        id: 'rain',
        name: '突然下雨',
        description: '突然下雨，客流减少',
        probability: 0.2,
        effect: {
          moneyDelta: -50,
          message: '🌧️ 突然下雨！客流减少',
        },
      },
    ],
  },
  {
    id: 3,
    name: '旺角夜市',
    description: '7个摊位，容量紧张，投诉阈值低，高难度挑战',
    maxRounds: 10,
    roundDuration: 20,
    maxElectricity: 350,
    maxComplaints: 6,
    maxSmoke: 120,
    targetMoney: 2000,
    idealElectricity: 280,
    stallConfigs: [
      {
        name: '老王烧烤',
        type: 'food',
        position: { x: 80, y: 160 },
        maxPower: 100,
        smokeCoefficient: 0.9,
        color: '#FF6B35',
        emoji: '🍢',
      },
      {
        name: '张记烤鱼',
        type: 'food',
        position: { x: 80, y: 380 },
        maxPower: 90,
        smokeCoefficient: 0.85,
        color: '#F4A261',
        emoji: '🐟',
      },
      {
        name: '潮汕粥铺',
        type: 'food',
        position: { x: 280, y: 160 },
        maxPower: 70,
        smokeCoefficient: 0.5,
        color: '#E76F51',
        emoji: '🍲',
      },
      {
        name: '阿婆糖水',
        type: 'drink',
        position: { x: 280, y: 380 },
        maxPower: 50,
        smokeCoefficient: 0.15,
        color: '#2EC4B6',
        emoji: '🥤',
      },
      {
        name: '麻辣香锅',
        type: 'food',
        position: { x: 480, y: 160 },
        maxPower: 85,
        smokeCoefficient: 0.75,
        color: '#D62828',
        emoji: '🌶️',
      },
      {
        name: '小李手工',
        type: 'craft',
        position: { x: 480, y: 380 },
        maxPower: 40,
        smokeCoefficient: 0.1,
        color: '#9B5DE5',
        emoji: '🎨',
      },
      {
        name: '夜市酒吧',
        type: 'drink',
        position: { x: 680, y: 270 },
        maxPower: 60,
        smokeCoefficient: 0.3,
        color: '#00B4D8',
        emoji: '🍺',
      },
    ],
    randomEvents: [
      {
        id: 'power_surge',
        name: '用电高峰',
        description: '夜市用电高峰，容量临时下降',
        probability: 0.35,
        effect: {
          electricityDelta: 50,
          message: '⚠️ 用电高峰！总容量压力剧增',
        },
      },
      {
        id: 'inspector',
        name: '城管严管',
        description: '城管严管，油烟检查非常严格',
        probability: 0.35,
        effect: {
          complaintDelta: 5,
          message: '🚨 城管严管！油烟管控极严',
        },
      },
      {
        id: 'festival',
        name: '节日客流',
        description: '节日期间客流增多，收益翻倍',
        probability: 0.3,
        effect: {
          moneyDelta: 200,
          message: '🎉 节日客流！收益大增',
        },
      },
      {
        id: 'rain',
        name: '暴雨来袭',
        description: '暴雨来袭，客流大幅减少',
        probability: 0.25,
        effect: {
          moneyDelta: -100,
          message: '🌧️ 暴雨来袭！客流大幅减少',
        },
      },
      {
        id: 'neighbor_conflict',
        name: '邻摊纠纷',
        description: '邻摊因油烟问题产生纠纷',
        probability: 0.3,
        effect: {
          complaintDelta: 3,
          message: '😤 邻摊纠纷！油烟问题引发投诉',
        },
      },
    ],
  },
];

export const getLevelById = (id: number): LevelConfig | undefined => {
  return levels.find((l) => l.id === id);
};