
import os, ast

L = []
def a(s=""):
    L.append(s)

a("from datetime import datetime")
a("from typing import List, Dict, Any, Optional")
a("from collections import defaultdict")
a("from .models import (FeatureRecord, SelfCheckResult, RecordStatus, CheckSession, ConflictEvidence)")
a("from .result_store import UnifiedResultStore")
a("")
T = chr(92) + "u"
a("C = lambda *x: ''.join(chr(int(x[i:i+4],16)) for i in range(0,len(x),4))")
a("")
a("def check_duplicate_imports(records):")
a("    seen = set()")
a("    duplicates = []")
a("    for rec in records:")
a("        key = (rec.feature_id, rec.bucket_id, rec.sample_id)")
a("        if key in seen:")
a("            duplicates.append(C('72795f81') + str(rec.feature_id) + '-' + C('6876') + str(rec.bucket_id) + '-' + C('6837672c') + str(rec.sample_id))")
a("        seen.add(key)")
a("    if duplicates:")
a("        return SelfCheckResult(check_type=C('91cd590d5bfc516568c067e567e559d768c067e5'), passed=False, details=C('53d173b0') + str(len(duplicates)) + C('6761') + C('91cd590d8bb05f55') + ': ' + ', '.join(duplicates[:5]) + ('...' if len(duplicates) > 5 else ''), found_issues=len(duplicates))")
a("    return SelfCheckResult(check_type=C('91cd590d5bfc516568c067e567e559d768c067e5'), passed=True, details=C('65e091cd590d8bb05f55'), found_issues=0)")
a("")
a("def check_feature_missing_default(records):")
a("    missing = [r for r in records if r.status == RecordStatus.FEATURE_MISSING_DEFAULT]")
a("    if missing:")
a("        sids = [r.sample_id for r in missing]")
a("        return SelfCheckResult(check_type=C('72795f817f3a59319ed88ba4520668c067e5'), passed=False, details=C('53d173b0') + str(len(missing)) + C('6761') + C('8bb05f5572795f817f3a4f7f75289ed8586b5145586b5045855f55785230621656c05f554eba590d590d68388d1f6838'), found_issues=len(missing))")
a("    return SelfCheckResult(check_type=C('72795f817f3a59319ed88ba4520668c067e5'), passed=True, details=C('65e072795f817f3a8bb05f55'), found_issues=0)")
a("")
path = os.path.join("app", "self_check.py")
with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(L) + "\n")
with open(path, encoding="utf-8") as f:
    c = f.read()
ast.parse(c)
print("OK part1 lines:", c.count("\n"))
DET_3WAY_OK = "\u9875\u9762\u3001\u63a5\u53e3\u3001\u660e\u7ec6\u6570\u636e\u5b8c\u5168\u4e00\u81f4"
CT_PEND = "\u8865\u5f55\u540e\u91cd\u7b97\u6b63\u786e\u6027\u81ea\u68c0"
DET_PEND_SKIP = "\u65e0\u8865\u5f55\u5feb\u7167(\u975e\u8865\u5f55\u89e6\u53d1)\uff0c\u8df3\u8fc7\u68c0\u67e5"
FEATURE = "\u7279\u5f81"
DET_PEND_STILL_MISSING = "\u539f\u59cb\u503c\u5df2\u8865\u5168\u4f46\u4ecd\u4e3aFEATURE_MISSING_DEFAULT/pending\u72b6\u6001"
DET_PEND_WRONG_REMOVE = "\u4ecd\u7f3a\u5931\u4f46pending\u72b6\u6001\u88ab\u8bef\u53d6\u6d88"
DET_PEND_OK = "\u8865\u5f55\u540e\u6240\u6709\u7279\u5f81pending\u72b6\u6001\u5747\u6b63\u786e"
DET_3WAY_EXCEPTION = "\u81ea\u68c0\u6267\u884c\u5f02\u5e38: "
PAGE_RECORDS = "\u9875\u9762\u8bb0\u5f55\u6570"
API_RECORDS = "API\u8bb0\u5f55\u6570"
EXPORT_RECORDS = "\u5bfc\u51fa\u8bb0\u5f55\u6570"
SID = "\u6837\u672cID"
FID = "\u7279\u5f81ID"
SAMPLE_KEY_DIFF = "\u9875\u9762\u4e0eAPI\u6837\u672c-\u7279\u5f81\u952e\u96c6\u5408\u4e0d\u4e00\u81f4"
RECORD = "\u8bb0\u5f55"
PAGE_STATUS = "\u9875\u9762\u72b6\u6001="
API_STATUS = " vs API\u72b6\u6001="
DET_3WAY_DIFF = "\u5904\u4e09\u7aef\u4e0d\u4e00\u81f4: "
DET_3WAY_PASS = "\u9875\u9762/API/\u5bfc\u51fa\u4e09\u7aef\u6570\u636e\u5b8c\u5168\u4e00\u81f4"
TIAO = "\u6761"
CHU = "\u5904"
XIANG = "\u9879"
BUCKET = "\u6876"
NEG_BUCKET = "\u8d1f\u6837\u672c"
TE = "\u7279\u5f81"
w("# === check_duplicate_imports ===")
w("def check_duplicate_imports(records: List[FeatureRecord]) -> SelfCheckResult:")
w("    seen = set()")
w("    duplicates = []")
w("    for rec in records:")
w("        key = (rec.feature_id, rec.bucket_id, rec.sample_id)")
w("        if key in seen:")
w('            duplicates.append("' + TE + '" + str(rec.feature_id) + "-' + BUCKET + '" + str(rec.bucket_id) + "-' + SAMPLE + '" + str(rec.sample_id))')
w("        seen.add(key)")
w("    if duplicates:")
w("        return SelfCheckResult(")
w('            check_type="' + CT_DUP + '",')
w("            passed=False,")
w('            details="' + DET_DUP_FOUND + '" + str(len(duplicates)) + "' + TIAO + '" + ", ".join(duplicates[:5]) + ("..." if len(duplicates) > 5 else ""),')
w("            found_issues=len(duplicates),")
w("        )")
w("    return SelfCheckResult(")
w('        check_type="' + CT_DUP + '", passed=True, details="' + DET_DUP_OK + '", found_issues=0')
w("    )")
w()
w()
w("# === check_feature_missing_default ===")
w("def check_feature_missing_default(records: List[FeatureRecord]) -> SelfCheckResult:")
w("    missing_records = [r for r in records if r.status == RecordStatus.FEATURE_MISSING_DEFAULT]")
w("    if missing_records:")
w("        sample_ids = [r.sample_id for r in missing_records]")
w("        return SelfCheckResult(")
w('            check_type="' + CT_MISS + '", passed=False,')
w('            details=("' + DET_DUP_FOUND + '" + str(len(missing_records)) + "' + DET_MISS_DESC + ': "')
w('                     + ", ".join(sample_ids[:5]) + ("..." if len(sample_ids) > 5 else "")')
w('                     + ".' + DET_MISS_TAIL + '"),')
w("            found_issues=len(missing_records),")
w("        )")
w("    return SelfCheckResult(")
w('        check_type="' + CT_MISS + '", passed=True, details="' + DET_MISS_OK + '", found_issues=0')
w("    )")
w()
w()
w("# === check_resupplement_recalculation ===")
w("def check_resupplement_recalculation(original_records, resupplemented_records):")
w("    omap = {(r.feature_id, r.sample_id): r for r in original_records}")
w("    issues = []")
w("    for nr in resupplemented_records:")
w("        k = (nr.feature_id, nr.sample_id)")
w("        if k in omap:")
w("            orr = omap[k]")
w("            if orr.status == RecordStatus.FEATURE_MISSING_DEFAULT and nr.status == RecordStatus.FEATURE_MISSING_DEFAULT:")
w("                if orr.feature_value == nr.feature_value:")
w('                    issues.append("' + SAMPLE + '" + nr.sample_id + "' + DET_RESUP_STILL + '")')
w("    if issues:")
w("        return SelfCheckResult(")
w('            check_type="' + CT_RESUP + '", passed=False,')
w('            details="' + DET_DUP_FOUND + '" + str(len(issues)) + "' + DET_RESUP_NOT + ': " + ", ".join(issues[:5]),')
w("            found_issues=len(issues),")
w("        )")
w("    return SelfCheckResult(")
w('        check_type="' + CT_RESUP + '", passed=True, details="' + DET_RESUP_OK + '", found_issues=0')
w("    )")
w()
w()
w("# === check_export_internal_consistency ===")
w("def check_export_internal_consistency(bucket_records, negative_records, conflicts) -> SelfCheckResult:")
w("    issues = []")
w("    br_map = {(r.sample_id, r.feature_id): r for r in bucket_records}")
w("    nr_map = {(r.sample_id, r.feature_id): r for r in negative_records}")
w("    for c in conflicts:")
w("        k = (c.sample_id, c.feature_id)")
w("        if k not in br_map and k not in nr_map:")
w('            issues.append("' + CONFLICT + '" + c.record_id + "' + DET_EXPORT_NOTFOUND + '")')
w("    if issues:")
w("        return SelfCheckResult(")
w('            check_type="' + CT_EXPORT + '", passed=False,')
w('            details="' + DET_DUP_FOUND + '" + str(len(issues)) + "' + CHU + '\u4e0d\u4e00\u81f4: " + ", ".join(issues[:5]),')
w("            found_issues=len(issues),")
w("        )")
w("    return SelfCheckResult(")
w('        check_type="' + CT_EXPORT + '", passed=True, details="' + DET_EXPORT_OK + '", found_issues=0')
w("    )")
w()
w()
w("# === check_page_api_export_consistency ===")
w("def check_page_api_export_consistency(page_data, api_data, detail_data) -> SelfCheckResult:")
w("    issues = []")
w("    if len(page_data) != len(api_data) or len(page_data) != len(detail_data):")
w("        issues.append(")
w('            "' + LEN_MISMATCH + '" + str(len(page_data)) + "' + TIAO + ', \u63a5\u53e3" + str(len(api_data)) + "' + TIAO + ', \u660e\u7ec6" + str(len(detail_data)) + "' + TIAO + '"')
w("        )")
w("    page_keys = {str(sorted(d.items())) for d in page_data}")
w("    api_keys = {str(sorted(d.items())) for d in api_data}")
w("    detail_keys = {str(sorted(d.items())) for d in detail_data}")
w("    if page_keys != api_keys:")
w('        issues.append("' + PAGE_API_DIFF + '")')
w("    if page_keys != detail_keys:")
w('        issues.append("' + PAGE_DET_DIFF + '")')
w("    if issues:")
w("        return SelfCheckResult(")
w('            check_type="' + CT_3WAY + '",')
w("            passed=False,")
w('            details="; ".join(issues),')
w("            found_issues=len(issues),")
w("        )")
w("    return SelfCheckResult(")
w('        check_type="' + CT_3WAY + '",')
w("        passed=True,")
w('        details="' + DET_3WAY_OK + '",')
w("        found_issues=0,")
w("    )")
w()
w()
w("# === check_resupplement_pending_status ===")
w("def check_resupplement_pending_status(pre_snapshot, current_records) -> SelfCheckResult:")
w("    issues = []")
w("    if pre_snapshot is None:")
w("        return SelfCheckResult(")
w('            check_type="' + CT_PEND + '", passed=True,')
w('            details="' + DET_PEND_SKIP + '", found_issues=0')
w("        )")
w("    pre_map = {(r.sample_id, r.feature_id): r for r in pre_snapshot}")
w("    curr_map = {(r.sample_id, r.feature_id): r for r in current_records}")
w("    for k, pre_rec in pre_map.items():")
w("        if pre_rec.status != RecordStatus.FEATURE_MISSING_DEFAULT:")
w("            continue")
w("        if k not in curr_map:")
w("            continue")
w("        curr_rec = curr_map[k]")
w('        pre_missing = (pre_rec.feature_value is None or str(pre_rec.feature_value) == "nan" or str(pre_rec.feature_value) == "")')
w('        curr_missing = (curr_rec.feature_value is None or str(curr_rec.feature_value) == "nan" or str(curr_rec.feature_value) == "")')
w("        if not pre_missing:")
w("            continue")
w("        if not curr_missing and curr_rec.status == RecordStatus.FEATURE_MISSING_DEFAULT:")
w('            issues.append("' + SAMPLE + '" + curr_rec.sample_id + FEATURE + '" + curr_rec.feature_id + "' + DET_PEND_STILL_MISSING + '")')
w("        elif curr_missing and curr_rec.status != RecordStatus.FEATURE_MISSING_DEFAULT:")
w('            issues.append("' + SAMPLE + '" + curr_rec.sample_id + FEATURE + '" + curr_rec.feature_id + "' + DET_PEND_WRONG_REMOVE + '")')
w("    if issues:")
w("        return SelfCheckResult(")
w('            check_type="' + CT_PEND + '", passed=False,')
w('            details="' + DET_DUP_FOUND + '" + str(len(issues)) + "' + XIANG + 'pending\u72b6\u6001\u9519\u8bef: " + "; ".join(issues[:3]),')
w("            found_issues=len(issues),")
w("        )")
w("    return SelfCheckResult(")
w('        check_type="' + CT_PEND + '", passed=True,')
w('        details="' + DET_PEND_OK + '", found_issues=0')
w("    )")
w()
w()
w("# === check_three_way_consistency ===")
w("def check_three_way_consistency(session: CheckSession) -> SelfCheckResult:")
w("    store = UnifiedResultStore(session)")
w("    issues = []")
w("    try:")
w("        pr = store.get_all_records_for_page()")
w("        ar = store.get_all_records_for_api()")
w("        er = store.get_all_records_for_export()")
w("        if len(pr) != len(ar):")
w('            issues.append("' + PAGE_RECORDS + '" + str(len(pr)) + " != ' + API_RECORDS + '" + str(len(ar)))')
w("        if len(ar) != len(er):")
w('            issues.append("' + API_RECORDS + '" + str(len(ar)) + " != ' + EXPORT_RECORDS + '" + str(len(er)))')
w('        page_keys = {(r["' + SID + '"], r["' + FID + '"]) for r in pr}')
w('        api_keys = {(r["' + SID + '"], r["' + FID + '"]) for r in ar}')
w("        if page_keys != api_keys:")
w('            issues.append("' + SAMPLE_KEY_DIFF + '")')
w("        if not issues:")
w("            for r in pr:")
w('                k = (r["' + SID + '"], r["' + FID + '"])')
w('                page_val = r.get("\u6700\u7ec8\u72b6\u6001(\u82f1\u6587)")')
w('                api_rec = next((x for x in ar if (x["' + SID + '"], x["' + FID + '"]) == k), None)')
w('                if api_rec and api_rec.get("\u6700\u7ec8\u72b6\u6001(\u82f1\u6587)") != page_val:')
w('                    issues.append("' + RECORD + '" + str(k) + "' + PAGE_STATUS + '" + str(page_val) + "' + API_STATUS + '" + str(api_rec.get("status")))')
w("                    if len(issues) >= 3:")
w("                        break")
w("    except Exception as e:")
w("        return SelfCheckResult(")
w('            check_type="' + CT_3WAY + '", passed=False,')
w('            details="' + DET_3WAY_EXCEPTION + '" + str(e), found_issues=1')
w("        )")
w("    if issues:")
w("        return SelfCheckResult(")
w('            check_type="' + CT_3WAY + '", passed=False,')
w('            details="' + DET_DUP_FOUND + '" + str(len(issues)) + "' + DET_3WAY_DIFF + '" + "; ".join(issues[:5]),')
w("            found_issues=len(issues),")
w("        )")
w("    return SelfCheckResult(")
w('        check_type="' + CT_3WAY + '", passed=True,')
w('        details="' + DET_3WAY_PASS + '", found_issues=0')
w("    )")
w()
w()
w("# === run_all_self_checks ===")
w("def run_all_self_checks(bucket_records, negative_records, conflicts, session: Optional[CheckSession] = None, pre_resupplement_snapshot=None) -> List[SelfCheckResult]:")
w("    results = []")
w("    all_records = list(bucket_records) + list(negative_records)")
w("    results.append(check_duplicate_imports(all_records))")
w("    results.append(check_feature_missing_default(bucket_records))")
w("    if pre_resupplement_snapshot is not None:")
w("        results.append(check_resupplement_recalculation(pre_resupplement_snapshot, bucket_records))")
w("        results.append(check_resupplement_pending_status(pre_resupplement_snapshot, bucket_records))")
w("    results.append(check_export_internal_consistency(bucket_records, negative_records, conflicts))")
w("    if session is not None:")
w("        results.append(check_three_way_consistency(session))")
w("    return results")

f.close()

with open(path, encoding="utf-8") as f:
    content = f.read()
ast.parse(content)
print("self_check.py OK, lines:", content.count("\n"), "size:", len(content))
