const RESERVATION_STATUS = {
  AVAILABLE: 10,
  RESERVED: 20,
  RELEASED: 30,
  EXCHANGED: 40,
  PENDING_MANUAL: 50
};

const RESERVATION_STATUS_DESC = {
  10: '可兑换',
  20: '预占中',
  30: '已释放',
  40: '已兑换',
  50: '待人工处理'
};

const OPERATION_TYPE = {
  CREATE: 'CREATE',
  RESERVE: 'RESERVE',
  RELEASE: 'RELEASE',
  EXCHANGE: 'EXCHANGE',
  MANUAL: 'MANUAL',
  EXPIRE: 'EXPIRE'
};

const PAY_STATUS = {
  PENDING: 10,
  PROCESSING: 20,
  SUCCESS: 30,
  FAILED: 40
};

const ORDER_STATUS = {
  PENDING: 10,
  PROCESSING: 20,
  COMPLETED: 30,
  CANCELLED: 40
};

const ERROR_CODES = {
  SUCCESS: 0,
  PARAM_ERROR: 400,
  STOCK_INSUFFICIENT: 1001,
  PRODUCT_NOT_FOUND: 1002,
  MEMBER_NOT_FOUND: 1003,
  RESERVATION_NOT_FOUND: 1004,
  RESERVATION_STATUS_ERROR: 1005,
  POINTS_INSUFFICIENT: 1006,
  PAY_FAILED: 1007,
  PAY_TIMEOUT: 1008,
  DUPLICATE_RESERVATION: 1009,
  NEED_MANUAL_PROCESS: 1010,
  SYSTEM_ERROR: 500
};

const ERROR_MESSAGES = {
  400: '参数错误',
  1001: '库存不足',
  1002: '商品不存在',
  1003: '会员不存在',
  1004: '预占单不存在',
  1005: '预占单状态异常',
  1006: '积分不足',
  1007: '支付失败',
  1008: '支付超时',
  1009: '检测到重复预占',
  1010: '需要人工处理',
  500: '系统错误'
};

module.exports = {
  RESERVATION_STATUS,
  RESERVATION_STATUS_DESC,
  OPERATION_TYPE,
  PAY_STATUS,
  ORDER_STATUS,
  ERROR_CODES,
  ERROR_MESSAGES
};
