const fs = require("fs");
const path = require("path");
const { db, initSchema } = require("./src/db");
initSchema();
const dataParser = require("./src/dataParser");
const batchService = require("./src/batchService");
const uploadsDir = path.join(__dirname, "uploads");
const cardPath = path.join(uploadsDir, "sample_cards.csv");
db.prepare("DELETE FROM card_records").run();
db.prepare("DELETE FROM batches").run();
const batchId = batchService.createBatch("TEST-001", "2026-05", "测试员", "测试");
console.log("批次ID:", batchId);
const rawCards = dataParser.parseCardCSV(cardPath);
console.log("解析到的记录数:", rawCards.length);
const normCards = rawCards.map(dataParser.normalizeCardRecord);
console.log("规范化后记录数:", normCards.length);
console.log("第1条:", JSON.stringify(normCards[0]));
console.log("第2条:", JSON.stringify(normCards[1]));
const result = batchService.importCardRecords(batchId, normCards, "测试员");
console.log("导入结果:", JSON.stringify(result, null, 2));
