from models import ThresholdConfig, AlertLevel


PV_THRESHOLDS = {
    "直流输入电压": [
        ThresholdConfig(
            metric_name="直流输入电压",
            level=AlertLevel.NORMAL,
            min_value=450.0,
            max_value=850.0,
            unit="V",
            description="逆变器直流输入正常工作电压范围"
        ),
        ThresholdConfig(
            metric_name="直流输入电压",
            level=AlertLevel.NOTICE,
            min_value=400.0,
            max_value=450.0,
            unit="V",
            description="直流输入电压偏低，需要关注"
        ),
        ThresholdConfig(
            metric_name="直流输入电压",
            level=AlertLevel.WARNING,
            min_value=350.0,
            max_value=400.0,
            unit="V",
            description="直流输入电压过低，可能影响发电效率"
        ),
        ThresholdConfig(
            metric_name="直流输入电压",
            level=AlertLevel.ALARM,
            min_value=0.0,
            max_value=350.0,
            unit="V",
            description="直流输入电压严重过低，需立即检查"
        ),
        ThresholdConfig(
            metric_name="直流输入电压",
            level=AlertLevel.ALARM,
            min_value=850.0,
            max_value=1000.0,
            unit="V",
            description="直流输入电压过高，存在设备损坏风险"
        ),
        ThresholdConfig(
            metric_name="直流输入电压",
            level=AlertLevel.CRITICAL,
            min_value=1000.0,
            max_value=99999.0,
            unit="V",
            description="直流输入电压严重过高，立即停机检查"
        ),
    ],
    "交流输出功率": [
        ThresholdConfig(
            metric_name="交流输出功率",
            level=AlertLevel.NORMAL,
            min_value=10.0,
            max_value=100.0,
            unit="kW",
            description="逆变器正常输出功率范围"
        ),
        ThresholdConfig(
            metric_name="交流输出功率",
            level=AlertLevel.NOTICE,
            min_value=5.0,
            max_value=10.0,
            unit="kW",
            description="输出功率偏低，可能存在阴影遮挡"
        ),
        ThresholdConfig(
            metric_name="交流输出功率",
            level=AlertLevel.WARNING,
            min_value=1.0,
            max_value=5.0,
            unit="kW",
            description="输出功率明显偏低，需检查组件状态"
        ),
        ThresholdConfig(
            metric_name="交流输出功率",
            level=AlertLevel.ALARM,
            min_value=0.0,
            max_value=1.0,
            unit="kW",
            description="输出功率接近零，逆变器可能停机"
        ),
    ],
    "逆变器温度": [
        ThresholdConfig(
            metric_name="逆变器温度",
            level=AlertLevel.NORMAL,
            min_value=-10.0,
            max_value=55.0,
            unit="℃",
            description="逆变器正常工作温度范围"
        ),
        ThresholdConfig(
            metric_name="逆变器温度",
            level=AlertLevel.NOTICE,
            min_value=55.0,
            max_value=65.0,
            unit="℃",
            description="逆变器温度偏高，注意通风散热"
        ),
        ThresholdConfig(
            metric_name="逆变器温度",
            level=AlertLevel.WARNING,
            min_value=65.0,
            max_value=75.0,
            unit="℃",
            description="逆变器温度过高，可能降额运行"
        ),
        ThresholdConfig(
            metric_name="逆变器温度",
            level=AlertLevel.ALARM,
            min_value=75.0,
            max_value=85.0,
            unit="℃",
            description="逆变器温度严重过高，需立即检查冷却系统"
        ),
        ThresholdConfig(
            metric_name="逆变器温度",
            level=AlertLevel.CRITICAL,
            min_value=85.0,
            max_value=999.0,
            unit="℃",
            description="逆变器温度极高，立即停机检查"
        ),
    ],
    "发电效率": [
        ThresholdConfig(
            metric_name="发电效率",
            level=AlertLevel.NORMAL,
            min_value=95.0,
            max_value=99.0,
            unit="%",
            description="逆变器正常发电效率范围"
        ),
        ThresholdConfig(
            metric_name="发电效率",
            level=AlertLevel.NOTICE,
            min_value=92.0,
            max_value=95.0,
            unit="%",
            description="发电效率略低，可能受温度影响"
        ),
        ThresholdConfig(
            metric_name="发电效率",
            level=AlertLevel.WARNING,
            min_value=88.0,
            max_value=92.0,
            unit="%",
            description="发电效率偏低，需检查设备状态"
        ),
        ThresholdConfig(
            metric_name="发电效率",
            level=AlertLevel.ALARM,
            min_value=0.0,
            max_value=88.0,
            unit="%",
            description="发电效率严重偏低，存在故障隐患"
        ),
    ],
    "电网频率": [
        ThresholdConfig(
            metric_name="电网频率",
            level=AlertLevel.NORMAL,
            min_value=49.5,
            max_value=50.5,
            unit="Hz",
            description="电网频率正常范围"
        ),
        ThresholdConfig(
            metric_name="电网频率",
            level=AlertLevel.WARNING,
            min_value=48.0,
            max_value=49.5,
            unit="Hz",
            description="电网频率偏低，可能影响并网"
        ),
        ThresholdConfig(
            metric_name="电网频率",
            level=AlertLevel.WARNING,
            min_value=50.5,
            max_value=52.0,
            unit="Hz",
            description="电网频率偏高，可能影响并网"
        ),
        ThresholdConfig(
            metric_name="电网频率",
            level=AlertLevel.ALARM,
            min_value=0.0,
            max_value=48.0,
            unit="Hz",
            description="电网频率严重过低，可能脱网"
        ),
        ThresholdConfig(
            metric_name="电网频率",
            level=AlertLevel.ALARM,
            min_value=52.0,
            max_value=999.0,
            unit="Hz",
            description="电网频率严重过高，可能脱网"
        ),
    ],
}


LATE_ARRIVAL_THRESHOLD_HOURS = 24
FLUCTUATION_THRESHOLD_PERCENT = 30.0
SEQUENCE_CHECK_WINDOW_MINUTES = 60
