const APPLICATION_STATES = {
  PENDING: 'PENDING',
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REVISED: 'REVISED'
};

const RECORD_STATES = {
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const CRANE_STATES = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  MAINTENANCE: 'MAINTENANCE'
};

const STATE_TRANSITIONS = {
  [APPLICATION_STATES.PENDING]: [
    APPLICATION_STATES.SCHEDULED,
    APPLICATION_STATES.CANCELLED,
    APPLICATION_STATES.REVISED
  ],
  [APPLICATION_STATES.SCHEDULED]: [
    APPLICATION_STATES.IN_PROGRESS,
    APPLICATION_STATES.CANCELLED,
    APPLICATION_STATES.REVISED
  ],
  [APPLICATION_STATES.IN_PROGRESS]: [
    APPLICATION_STATES.COMPLETED,
    APPLICATION_STATES.CANCELLED
  ],
  [APPLICATION_STATES.COMPLETED]: [],
  [APPLICATION_STATES.CANCELLED]: [],
  [APPLICATION_STATES.REVISED]: [
    APPLICATION_STATES.SCHEDULED,
    APPLICATION_STATES.CANCELLED
  ]
};

function canTransition(from, to) {
  const allowed = STATE_TRANSITIONS[from] || [];
  return allowed.includes(to);
}

function isFinalState(state) {
  return [APPLICATION_STATES.COMPLETED, APPLICATION_STATES.CANCELLED].includes(state);
}

function isModifiableState(state) {
  return [
    APPLICATION_STATES.PENDING,
    APPLICATION_STATES.SCHEDULED,
    APPLICATION_STATES.REVISED
  ].includes(state);
}

module.exports = {
  APPLICATION_STATES,
  RECORD_STATES,
  CRANE_STATES,
  STATE_TRANSITIONS,
  canTransition,
  isFinalState,
  isModifiableState
};
