const ECN_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  IMPACT_ANALYZED: 'IMPACT_ANALYZED',
  APPROVED: 'APPROVED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
};

const URGENCY_LEVEL = {
  NORMAL: 'NORMAL',
  URGENT: 'URGENT',
  CRITICAL: 'CRITICAL'
};

const ITEM_STATUS = {
  PENDING: 'PENDING',
  NOTIFIED: 'NOTIFIED',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED',
  TRACE_ONLY: 'TRACE_ONLY'
};

const SHIPMENT_STATUS = {
  NOT_SHIPPED: 'NOT_SHIPPED',
  PARTIALLY_SHIPPED: 'PARTIALLY_SHIPPED',
  FULLY_SHIPPED: 'FULLY_SHIPPED'
};

const PURCHASE_CONFIRM_STATUS = {
  NOT_CONFIRMED: 'NOT_CONFIRMED',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED'
};

const PRODUCTION_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  FROZEN: 'FROZEN',
  COMPLETED: 'COMPLETED'
};

module.exports = {
  ECN_STATUS,
  URGENCY_LEVEL,
  ITEM_STATUS,
  SHIPMENT_STATUS,
  PURCHASE_CONFIRM_STATUS,
  PRODUCTION_STATUS
};
