"""Exporter module for generating batch_report.md, bad_channels.csv and HTML curve page."""

import csv
import json
from datetime import datetime
from pathlib import Path
from typing import Any

from formation_qc.rule_engine import Issue
from formation_qc.statistics import CapacityStats


class MarkdownExporter:
    def export(self, report: dict[str, Any], output_path: str) -> None:
        lines = ["# Formation Batch QC Report\n"]
        lines.append(f"**Generated:** {report.get('generated_at', datetime.now().strftime('%Y-%m-%d %H:%M:%S'))}\n")
        lines.append(f"**Total Channels:** {report.get('total_channels', 0)}\n")
        lines.append(f"**Problem Channels:** {report.get('problem_channels', 0)}\n\n")

        exec_summary = report.get("executive_summary", {})
        lines.append("## Executive Summary\n")
        lines.append(f"- Offline channels: {exec_summary.get('offline_count', 0)}\n")
        lines.append(f"- Reverse connection: {exec_summary.get('reverse_count', 0)}\n")
        lines.append(f"- Temperature issues: {exec_summary.get('temp_issue_count', 0)}\n")
        lines.append(f"- Missing samples: {exec_summary.get('missing_sample_count', 0)}\n")
        lines.append(f"- Capacity outliers: {exec_summary.get('capacity_outlier_count', 0)}\n\n")

        issues = report.get("all_issues", [])
        if issues:
            lines.append("## Issue Details\n")
            lines.append("| Channel | Type | Step | Timestamp | Value | Threshold | Message |\n")
            lines.append("|---------|------|------|-----------|-------|-----------|--------|\n")
            for iss in issues:
                ts = iss.timestamp.strftime("%Y-%m-%d %H:%M:%S") if iss.timestamp else "N/A"
                val = f"{iss.value:.2f}" if iss.value is not None else "N/A"
                thr = f"{iss.threshold:.2f}" if iss.threshold is not None else "N/A"
                step = str(iss.step) if iss.step is not None else "N/A"
                lines.append(f"| {iss.channel} | {iss.issue_type.value} | {step} | {ts} | {val} | {thr} | {iss.message} |\n")

        cap_outliers = report.get("capacity_outliers", [])
        if cap_outliers:
            lines.append("\n## Capacity Outliers\n")
            lines.append("| Channel | Capacity | Z-Score | Type |\n")
            lines.append("|---------|----------|---------|------|\n")
            for cs in cap_outliers:
                lines.append(f"| {cs.channel} | {cs.capacity:.4f} | {cs.z_score:.2f} | {cs.outlier_type or 'N/A'} |\n")

        segs = report.get("step_summary", [])
        if segs:
            lines.append("\n## Step Summary\n")
            lines.append("| Step | Name | Channels | Avg Voltage | Avg Temp | Avg Capacity |\n")
            lines.append("|------|------|----------|-------------|----------|-------------|\n")
            for seg in segs:
                lines.append(f"| {seg['step_index']} | {seg['step_name']} | {seg['channel_count']} | {seg.get('avg_voltage', 0):.3f} | {seg.get('avg_temperature', 0):.1f} | {seg.get('avg_capacity', 0):.4f} |\n")

        lines.append("\n---\n*Report generated by Formation QC CLI*\n")
        Path(output_path).write_text("".join(lines), encoding="utf-8")


class CsvExporter:
    def export(self, issues: list[Issue], capacity_outliers: list[CapacityStats], output_path: str) -> None:
        with open(output_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(["channel", "issue_type", "step", "timestamp", "value", "threshold", "message"])
            for iss in issues:
                ts = iss.timestamp.strftime("%Y-%m-%d %H:%M:%S") if iss.timestamp else ""
                val = f"{iss.value:.4f}" if iss.value is not None else ""
                thr = f"{iss.threshold:.4f}" if iss.threshold is not None else ""
                step = str(iss.step) if iss.step is not None else ""
                writer.writerow([iss.channel, iss.issue_type.value, step, ts, val, thr, iss.message])
            for cs in capacity_outliers:
                if cs.is_outlier:
                    writer.writerow([cs.channel, "capacity_outlier", "N/A", "N/A", f"{cs.capacity:.4f}", f"z={cs.z_score:.2f}", f"type={cs.outlier_type}"])


class HtmlExporter:
    def export(self, data: dict[str, Any], output_path: str) -> None:
        channels_data = data.get("channels", [])
        segments = data.get("segments", [])

        html = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Formation QC - Battery Curves</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
<style>
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
h1 { color: #333; }
.controls { margin-bottom: 20px; }
select, button { padding: 8px 16px; margin-right: 10px; }
.chart-container { background: white; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
canvas { max-height: 400px; }
.channel-info { background: white; border-radius: 8px; padding: 15px; margin-bottom: 20px; }
table { border-collapse: collapse; width: 100%; }
th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
th { background-color: #4CAF50; color: white; }
tr:nth-child(even) { background-color: #f2f2f2; }
.issue { color: #e53935; font-weight: bold; }
.ok { color: #43a047; }
</style>
</head>
<body>
<h1>Formation QC - Battery Curves</h1>
<div class="controls">
<label>Channel: <select id="channelSelect"></select></label>
<label>Metric: <select id="metricSelect">
<option value="voltage">Voltage</option>
<option value="current">Current</option>
<option value="temperature">Temperature</option>
<option value="capacity">Capacity</option>
</select></label>
<button onclick="drawChart()">Draw</button>
</div>
<div class="channel-info" id="channelInfo"></div>
<div class="chart-container"><canvas id="curveChart"></canvas></div>
<script>
"""
        channels_json = json.dumps(channels_data, default=str)
        segments_json = json.dumps(segments, default=str)
        html += f"const channelsData = {channels_json};\n"
        html += f"const segmentsData = {segments_json};\n"

        html += """
const chSelect = document.getElementById('channelSelect');
const infoDiv = document.getElementById('channelInfo');
let chart = null;

channelsData.forEach((ch, i) => {
    const opt = document.createElement('option');
    opt.value = i;
    opt.textContent = 'Channel ' + ch.channel + (ch.hasIssues ? ' [ISSUE]' : '');
    chSelect.appendChild(opt);
});

function drawChart() {
    const idx = parseInt(chSelect.value);
    const metric = document.getElementById('metricSelect').value;
    const ch = channelsData[idx];

    const labels = ch.data.map(p => p.timestamp);
    const values = ch.data.map(p => p[metric]);
    const stepBoundaries = [];
    if (segmentsData.length > 0) {
        const segs = segmentsData.filter(s => s.channel === ch.channel);
        segs.forEach(s => stepBoundaries.push({idx: s.start_idx, name: s.step_name}));
    }

    if (chart) chart.destroy();
    const ctx = document.getElementById('curveChart').getContext('2d');
    chart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: labels,
            datasets: [{
                label: metric.charAt(0).toUpperCase() + metric.slice(1) + ' - Ch ' + ch.channel,
                data: values,
                borderColor: 'blue',
                tension: 0.1,
                pointRadius: 1,
            }]
        },
        options: {
            responsive: true,
            scales: { x: { type: 'linear', ticks: { maxTicksLimit: 10 } } }
        }
    });

    const issues = ch.issues || [];
    if (issues.length > 0) {
        infoDiv.innerHTML = '<h3>Issues:</h3><ul>' + issues.map(i =>
            '<li class="issue">' + i.issue_type + ': ' + i.message + '</li>').join('') + '</ul>';
    } else {
        infoDiv.innerHTML = '<p class="ok">No issues detected for this channel.</p>';
    }
}

drawChart();
</script>
</body>
</html>"""
        Path(output_path).write_text(html, encoding="utf-8")
