lines = []
lines.append('import os, sys, json')
lines.append("DATA_DIR = '/Users/lzy/pro/solo/workspaces/zy72460/data'")
lines.append("db_path = os.path.join(DATA_DIR, 'rain_garden.db')")
lines.append('if os.path.exists(db_path): os.remove(db_path)')
lines.append('from database import init_db, engine, Base')
lines.append('Base.metadata.drop_all(bind=engine)')
lines.append('init_db()')
lines.append('from fastapi.testclient import TestClient')
lines.append('from api import app')
lines.append('client = TestClient(app)')
lines.append("print('1. 创建会话...')")
lines.append("r = client.post('/api/sessions', json={'session_id': 'AUTO-VERIFY-001'})")
lines.append('assert r.status_code == 200, r.text')
lines.append('d = r.json()')
lines.append("assert d['session_id'] == 'AUTO-VERIFY-001'")
lines.append("print('  ✓ ok')")
lines.append("print('2. 导入点位...')")
lines.append("POINTS = [{'point_id': 'P005', 'name': '徐家汇公园雨水花园', 'location': {'lat': 31.1987, 'lng': 121.4382, 'street': '徐家汇街道', 'is_boundary': False}}, {'point_id': 'P006', 'name': '衡山路雨水花园', 'location': {'lat': 31.2078, 'lng': 121.4375, 'street': '天平路街道', 'is_boundary': True, 'adjacent_streets': ['湖南路街道']}}]")
lines.append("r = client.post('/api/sessions/AUTO-VERIFY-001/points', json=POINTS)")
lines.append('assert r.status_code == 200, r.text')
lines.append('d = r.json()')
lines.append("assert d['imported'] == 2")
lines.append("print('  ✓ ok')")
lines.append("print('3. 第一次导入 R005/R006...')")
lines.append("RAMP = [{'record_id': 'R005', 'point_id': 'P005', 'inspector': '孙工', 'inspect_time': '2026-06-04T10:00:00', 'has_waterlogging': False, 'ramp_accessible': True, 'ramp_note': '正常'}, {'record_id': 'R006', 'point_id': 'P006', 'inspector': '孙工', 'inspect_time': '2026-06-04T11:00:00', 'has_waterlogging': False, 'ramp_accessible': True, 'ramp_note': '正常'}]")
lines.append("r = client.post('/api/sessions/AUTO-VERIFY-001/records?source=RAMP_SURVEY', json=RAMP, params={'actor': '小付'})")
lines.append('assert r.status_code == 200, r.text')
lines.append('d = r.json()')
lines.append("assert d['imported'] == 2")
lines.append("assert d['reused'] == 0")
lines.append("batch_id_1 = d['batch_id']")
lines.append("r005_detail = next(x for x in d['details'] if x['record_id'] == 'R005')")
lines.append("assert r005_detail['status'] == '真新增'")
lines.append("print('  ✓ ok, batch_id:', batch_id_1)")

content = '\n'.join(lines) + '\n'

with open('/Users/lzy/pro/solo/workspaces/zy72460/t1.py', 'w', encoding='utf-8') as f:
    f.write(content)

print(f'Written {len(lines)} lines, {len(content)} bytes')
