import type { LevelConfig } from "@/types/game";

export const LEVELS: LevelConfig[] = [
  {
    id: "level1",
    name: "基础吊运",
    description: "单钢卷无障碍，熟悉吊具升降与重心",
    difficulty: 1,
    maxTiltDegrees: 12,
    maxMoves: 5,
    timeLimit: 120,
    boundary: { minX: -12, maxX: 12, minZ: -8, maxZ: 8 },
    coils: [
      {
        id: "coil-1",
        position: { x: -5, y: 0.6, z: 0 },
        radius: 1.1,
        length: 2.4,
        weight: 12.5,
        centerOffset: { x: 0, y: 0 },
        targetZoneId: "zone-drop-1",
      },
    ],
    zones: [
      {
        id: "zone-pick-1",
        position: { x: -5, y: 0, z: 0 },
        size: { x: 3.5, y: 0.1, z: 3.5 },
        type: "pickup",
        label: "取卷区 A",
      },
      {
        id: "zone-drop-1",
        position: { x: 5, y: 0, z: 0 },
        size: { x: 3.5, y: 0.1, z: 3.5 },
        type: "dropoff",
        label: "放卷区 B",
      },
    ],
    rails: [
      { id: "rail-1", axis: "x", start: -12, end: 12, fixed: 0, y: 8 },
    ],
    cranes: [
      {
        id: "crane-1",
        railId: "rail-1",
        axis: "x",
        start: -12,
        end: 12,
        fixed: 0,
        y: 8,
        speed: 5,
        hoistSpeed: 2,
        width: 3,
      },
    ],
  },
  {
    id: "level2",
    name: "偏移警觉",
    description: "钢卷偏心装载，必须调整吊点以控制倾斜",
    difficulty: 2,
    maxTiltDegrees: 10,
    maxMoves: 6,
    timeLimit: 150,
    boundary: { minX: -12, maxX: 12, minZ: -8, maxZ: 8 },
    coils: [
      {
        id: "coil-1",
        position: { x: -5, y: 0.6, z: 0 },
        radius: 1.1,
        length: 2.4,
        weight: 14.2,
        centerOffset: { x: 0.55, y: 0.15 },
        targetZoneId: "zone-drop-1",
      },
      {
        id: "coil-2",
        position: { x: -5, y: 0.6, z: 4 },
        radius: 1.1,
        length: 2.4,
        weight: 11.8,
        centerOffset: { x: -0.4, y: -0.3 },
        targetZoneId: "zone-drop-2",
      },
    ],
    zones: [
      {
        id: "zone-pick-1",
        position: { x: -5, y: 0, z: 0 },
        size: { x: 3.5, y: 0.1, z: 3.5 },
        type: "pickup",
        label: "取卷区 A",
      },
      {
        id: "zone-pick-2",
        position: { x: -5, y: 0, z: 4 },
        size: { x: 3.5, y: 0.1, z: 3.5 },
        type: "pickup",
        label: "取卷区 B",
      },
      {
        id: "zone-drop-1",
        position: { x: 5, y: 0, z: 0 },
        size: { x: 3.5, y: 0.1, z: 3.5 },
        type: "dropoff",
        label: "放卷区 C",
      },
      {
        id: "zone-drop-2",
        position: { x: 5, y: 0, z: 4 },
        size: { x: 3.5, y: 0.1, z: 3.5 },
        type: "dropoff",
        label: "放卷区 D",
      },
    ],
    rails: [
      { id: "rail-1", axis: "x", start: -12, end: 12, fixed: 0, y: 8 },
    ],
    cranes: [
      {
        id: "crane-1",
        railId: "rail-1",
        axis: "x",
        start: -12,
        end: 12,
        fixed: 0,
        y: 8,
        speed: 5,
        hoistSpeed: 2,
        width: 3,
      },
    ],
  },
  {
    id: "level3",
    name: "双线轨道",
    description: "两条并行行车轨道，规划避让防碰撞",
    difficulty: 2,
    maxTiltDegrees: 12,
    maxMoves: 6,
    timeLimit: 180,
    boundary: { minX: -12, maxX: 12, minZ: -8, maxZ: 8 },
    coils: [
      {
        id: "coil-1",
        position: { x: -5, y: 0.6, z: -2 },
        radius: 1.1,
        length: 2.4,
        weight: 12,
        centerOffset: { x: 0.1, y: 0 },
        targetZoneId: "zone-drop-1",
      },
      {
        id: "coil-2",
        position: { x: -5, y: 0.6, z: 2 },
        radius: 1.1,
        length: 2.4,
        weight: 12,
        centerOffset: { x: 0, y: 0.1 },
        targetZoneId: "zone-drop-2",
      },
    ],
    zones: [
      {
        id: "zone-pick-1",
        position: { x: -5, y: 0, z: -2 },
        size: { x: 3.5, y: 0.1, z: 3 },
        type: "pickup",
        label: "取卷区 A",
      },
      {
        id: "zone-pick-2",
        position: { x: -5, y: 0, z: 2 },
        size: { x: 3.5, y: 0.1, z: 3 },
        type: "pickup",
        label: "取卷区 B",
      },
      {
        id: "zone-drop-1",
        position: { x: 5, y: 0, z: -2 },
        size: { x: 3.5, y: 0.1, z: 3 },
        type: "dropoff",
        label: "放卷区 C",
      },
      {
        id: "zone-drop-2",
        position: { x: 5, y: 0, z: 2 },
        size: { x: 3.5, y: 0.1, z: 3 },
        type: "dropoff",
        label: "放卷区 D",
      },
    ],
    rails: [
      { id: "rail-1", axis: "x", start: -12, end: 12, fixed: -4, y: 8 },
      { id: "rail-2", axis: "x", start: -12, end: 12, fixed: 4, y: 8 },
    ],
    cranes: [
      {
        id: "crane-1",
        railId: "rail-1",
        axis: "x",
        start: -12,
        end: 12,
        fixed: -4,
        y: 8,
        speed: 5,
        hoistSpeed: 2,
        width: 3,
      },
      {
        id: "crane-2",
        railId: "rail-2",
        axis: "x",
        start: -12,
        end: 12,
        fixed: 4,
        y: 8,
        speed: 5,
        hoistSpeed: 2,
        width: 3,
      },
    ],
  },
  {
    id: "level4",
    name: "人员穿越",
    description: "下方有人行通道，吊运路线禁止穿越",
    difficulty: 3,
    maxTiltDegrees: 10,
    maxMoves: 5,
    timeLimit: 150,
    boundary: { minX: -12, maxX: 12, minZ: -8, maxZ: 8 },
    coils: [
      {
        id: "coil-1",
        position: { x: -5, y: 0.6, z: -4 },
        radius: 1.1,
        length: 2.4,
        weight: 13.1,
        centerOffset: { x: 0.3, y: 0 },
        targetZoneId: "zone-drop-1",
      },
      {
        id: "coil-2",
        position: { x: -5, y: 0.6, z: 4 },
        radius: 1.1,
        length: 2.4,
        weight: 13.1,
        centerOffset: { x: -0.3, y: 0 },
        targetZoneId: "zone-drop-2",
      },
    ],
    zones: [
      {
        id: "zone-pick-1",
        position: { x: -5, y: 0, z: -4 },
        size: { x: 3.5, y: 0.1, z: 3 },
        type: "pickup",
        label: "取卷区 A",
      },
      {
        id: "zone-pick-2",
        position: { x: -5, y: 0, z: 4 },
        size: { x: 3.5, y: 0.1, z: 3 },
        type: "pickup",
        label: "取卷区 B",
      },
      {
        id: "zone-drop-1",
        position: { x: 5, y: 0, z: -4 },
        size: { x: 3.5, y: 0.1, z: 3 },
        type: "dropoff",
        label: "放卷区 C",
      },
      {
        id: "zone-drop-2",
        position: { x: 5, y: 0, z: 4 },
        size: { x: 3.5, y: 0.1, z: 3 },
        type: "dropoff",
        label: "放卷区 D",
      },
      {
        id: "zone-personnel-1",
        position: { x: 0, y: 0, z: 0 },
        size: { x: 12, y: 0.1, z: 2 },
        type: "personnel",
        label: "人行通道（禁止穿越）",
      },
    ],
    rails: [
      { id: "rail-1", axis: "x", start: -12, end: 12, fixed: 0, y: 8 },
    ],
    cranes: [
      {
        id: "crane-1",
        railId: "rail-1",
        axis: "x",
        start: -12,
        end: 12,
        fixed: 0,
        y: 8,
        speed: 5,
        hoistSpeed: 2,
        width: 3,
      },
    ],
  },
  {
    id: "level5",
    name: "综合作业",
    description: "多钢卷多作业区多障碍综合考验",
    difficulty: 4,
    maxTiltDegrees: 10,
    maxMoves: 8,
    timeLimit: 240,
    boundary: { minX: -14, maxX: 14, minZ: -10, maxZ: 10 },
    coils: [
      {
        id: "coil-1",
        position: { x: -7, y: 0.6, z: -5 },
        radius: 1.1,
        length: 2.4,
        weight: 14,
        centerOffset: { x: 0.4, y: 0.2 },
        targetZoneId: "zone-drop-1",
      },
      {
        id: "coil-2",
        position: { x: -7, y: 0.6, z: 0 },
        radius: 1.1,
        length: 2.4,
        weight: 12.2,
        centerOffset: { x: -0.3, y: 0.1 },
        targetZoneId: "zone-drop-2",
      },
      {
        id: "coil-3",
        position: { x: -7, y: 0.6, z: 5 },
        radius: 1.1,
        length: 2.4,
        weight: 13.8,
        centerOffset: { x: 0.2, y: -0.4 },
        targetZoneId: "zone-drop-3",
      },
    ],
    zones: [
      {
        id: "zone-pick-1",
        position: { x: -7, y: 0, z: -5 },
        size: { x: 3.5, y: 0.1, z: 3 },
        type: "pickup",
        label: "取卷 A",
      },
      {
        id: "zone-pick-2",
        position: { x: -7, y: 0, z: 0 },
        size: { x: 3.5, y: 0.1, z: 3 },
        type: "pickup",
        label: "取卷 B",
      },
      {
        id: "zone-pick-3",
        position: { x: -7, y: 0, z: 5 },
        size: { x: 3.5, y: 0.1, z: 3 },
        type: "pickup",
        label: "取卷 C",
      },
      {
        id: "zone-drop-1",
        position: { x: 7, y: 0, z: -5 },
        size: { x: 3.5, y: 0.1, z: 3 },
        type: "dropoff",
        label: "放卷 D",
      },
      {
        id: "zone-drop-2",
        position: { x: 7, y: 0, z: 0 },
        size: { x: 3.5, y: 0.1, z: 3 },
        type: "dropoff",
        label: "放卷 E",
      },
      {
        id: "zone-drop-3",
        position: { x: 7, y: 0, z: 5 },
        size: { x: 3.5, y: 0.1, z: 3 },
        type: "dropoff",
        label: "放卷 F",
      },
      {
        id: "zone-personnel-1",
        position: { x: 0, y: 0, z: 3 },
        size: { x: 12, y: 0.1, z: 1.8 },
        type: "personnel",
        label: "人行通道",
      },
      {
        id: "zone-restricted-1",
        position: { x: 0, y: 0, z: -3 },
        size: { x: 4, y: 0.1, z: 2.5 },
        type: "restricted",
        label: "禁入区",
      },
    ],
    rails: [
      { id: "rail-1", axis: "x", start: -14, end: 14, fixed: 0, y: 9 },
    ],
    cranes: [
      {
        id: "crane-1",
        railId: "rail-1",
        axis: "x",
        start: -14,
        end: 14,
        fixed: 0,
        y: 9,
        speed: 5,
        hoistSpeed: 2,
        width: 3,
      },
    ],
  },
];

export function getLevel(id: string): LevelConfig | undefined {
  return LEVELS.find((l) => l.id === id);
}
