import { BuildingModel, SunshineRecord, StatusHistory } from '@/types';

export const mockBuildings: BuildingModel[] = [
  {
    id: 'b1',
    name: '1号楼',
    position: { x: 0, y: 0, z: 0 },
    dimensions: { height: 30, width: 20, depth: 15 },
    color: '#64748b',
  },
  {
    id: 'b2',
    name: '2号楼',
    position: { x: 35, y: 0, z: 0 },
    dimensions: { height: 40, width: 25, depth: 18 },
    color: '#475569',
  },
  {
    id: 'b3',
    name: '3号楼',
    position: { x: 17, y: 0, z: 30 },
    dimensions: { height: 25, width: 18, depth: 12 },
    color: '#334155',
  },
  {
    id: 'b4',
    name: '4号楼',
    position: { x: -30, y: 0, z: 0 },
    dimensions: { height: 35, width: 22, depth: 16 },
    color: '#1e293b',
  },
];

const now = new Date().toISOString();

export const mockRecords: SunshineRecord[] = [
  {
    id: 'r1',
    buildingId: 'b1',
    buildingName: '1号楼',
    floor: 5,
    roomNumber: '501',
    source: '2024春季班-第3组',
    sourceType: 'import',
    importTime: now,
    importer: '张老师',
    status: 'confirmed',
    currentHandler: '张老师',
    isManualModified: false,
    lastModified: now,
    lastModifier: '张老师',
  },
  {
    id: 'r2',
    buildingId: 'b1',
    buildingName: '1号楼',
    floor: 8,
    roomNumber: '802',
    source: '2024春季班-第1组',
    sourceType: 'import',
    importTime: now,
    importer: '张老师',
    status: 'to_supplement',
    currentHandler: '李老师',
    pendingReason: '日照时间不足，需要补充实测数据',
    isManualModified: true,
    lastModified: now,
    lastModifier: '李老师',
  },
  {
    id: 'r3',
    buildingId: 'b2',
    buildingName: '2号楼',
    floor: 12,
    roomNumber: '1203',
    source: '2024春季班-第5组',
    sourceType: 'import',
    importTime: now,
    importer: '张老师',
    status: 'modified',
    currentHandler: '王老师',
    isManualModified: true,
    lastModified: now,
    lastModifier: '王老师',
    remark: '修正了楼层高度参数',
  },
  {
    id: 'r4',
    buildingId: 'b2',
    buildingName: '2号楼',
    floor: 6,
    roomNumber: '601',
    source: '2024春季班-第2组',
    sourceType: 'import',
    importTime: now,
    importer: '张老师',
    status: 'pending',
    currentHandler: '张老师',
    isManualModified: false,
    lastModified: now,
    lastModifier: '张老师',
  },
  {
    id: 'r5',
    buildingId: 'b3',
    buildingName: '3号楼',
    floor: 3,
    roomNumber: '302',
    source: '2024春季班-第4组',
    sourceType: 'import',
    importTime: now,
    importer: '张老师',
    status: 'confirmed',
    currentHandler: '张老师',
    isManualModified: false,
    lastModified: now,
    lastModifier: '张老师',
  },
  {
    id: 'r6',
    buildingId: 'b4',
    buildingName: '4号楼',
    floor: 10,
    roomNumber: '1001',
    source: '2024春季班-第6组',
    sourceType: 'import',
    importTime: now,
    importer: '张老师',
    status: 'to_supplement',
    currentHandler: '刘老师',
    pendingReason: '建筑阴影计算有误，待复核',
    isManualModified: true,
    lastModified: now,
    lastModifier: '刘老师',
  },
  {
    id: 'r7',
    buildingId: 'b4',
    buildingName: '4号楼',
    floor: 7,
    roomNumber: '703',
    source: '2024春季班-第7组',
    sourceType: 'manual',
    importTime: now,
    importer: '张老师',
    status: 'pending',
    currentHandler: '张老师',
    isManualModified: false,
    lastModified: now,
    lastModifier: '张老师',
  },
];

export const mockHistories: StatusHistory[] = [
  {
    id: 'h1',
    recordId: 'r2',
    fromStatus: 'pending',
    toStatus: 'to_supplement',
    reason: '日照时间不足，需要补充实测数据',
    operator: '李老师',
    operateTime: now,
  },
  {
    id: 'h2',
    recordId: 'r3',
    fromStatus: 'pending',
    toStatus: 'modified',
    reason: '修正了楼层高度参数',
    operator: '王老师',
    operateTime: now,
  },
  {
    id: 'h3',
    recordId: 'r1',
    fromStatus: 'pending',
    toStatus: 'confirmed',
    reason: '数据复核无误',
    operator: '张老师',
    operateTime: now,
  },
  {
    id: 'h4',
    recordId: 'r5',
    fromStatus: 'pending',
    toStatus: 'confirmed',
    reason: '数据复核无误',
    operator: '张老师',
    operateTime: now,
  },
  {
    id: 'h5',
    recordId: 'r6',
    fromStatus: 'pending',
    toStatus: 'to_supplement',
    reason: '建筑阴影计算有误，待复核',
    operator: '刘老师',
    operateTime: now,
  },
];
