L = []
a = L.append
a('#!/usr/bin/env python3')
a('import subprocess')
a('import json')
a('import os')
a('import sys')
a('import glob')
a('import re')
a('')
a('')
a('WORKDIR = os.path.dirname(os.path.abspath(__file__))')
a('SESSION_ID = "TEST-REPLAY"')
a('SESSIONS_DIR = os.path.join(WORKDIR, "sessions")')
a('OUTPUT_DIR = os.path.join(WORKDIR, "output")')
a('SESSION_FILE = os.path.join(SESSIONS_DIR, SESSION_ID + ".json")')
a('')
a('')
a('def print_step(msg):')
a('    print()')
a('    print("=" * 60)')
a('    print("  " + msg)')
a('    print("=" * 60)')
a('')
a('')
a('def print_check(msg):')
a('    print()')
a('    print("[检查点] " + msg)')
a('')
a('')
a('def assert_true(condition, msg):')
a('    if not condition:')
a('        print()')
a('        print("FAIL: " + msg)')
a('        sys.exit(1)')
a('')
a('')
a('def run_cmd(args):')
a('    print()')
a('    print("  执行: " + " ".join(args))')
a('    result = subprocess.run(args, cwd=WORKDIR, capture_output=True, text=True)')
a('    if result.stdout:')
a('        print(result.stdout)')
a('    if result.stderr:')
a('        sys.stderr.write(result.stderr)')
a('    if result.returncode != 0:')
a('        print("FAIL: 命令执行失败，返回码=" + str(result.returncode))')
a('        sys.exit(1)')
a('    return result')
a('')
a('')
a('def cleanup():')
a('    print_step("清理 TEST-REPLAY 相关会话和产物")')
a('    path = os.path.join(SESSIONS_DIR, SESSION_ID + ".json")')
a('    if os.path.exists(path):')
a('        print("  删除: " + path)')
a('        os.remove(path)')
a('    matched = glob.glob(os.path.join(OUTPUT_DIR, "*" + SESSION_ID + "*"))')
a('    for path in matched:')
a('        if os.path.exists(path):')
a('            print("  删除: " + path)')
a('            os.remove(path)')
a('    print("  清理完成")')
a('')
a('')
a('def load_session():')
a('    assert_true(os.path.exists(SESSION_FILE), "会话文件不存在: " + SESSION_FILE)')
a('    with open(SESSION_FILE, "r", encoding="utf-8") as f:')
a('        return json.load(f)')

