const app = require('./app');
const PORT = process.env.PORT || 3000;

app.listen(PORT, () => {
  console.log(`\n========================================`);
  console.log(`  WASM 规则插件验收台`);
  console.log(`  WASM Rule Plugin Validator`);
  console.log(`========================================`);
  console.log(`\n  服务地址: http://localhost:${PORT}`);
  console.log(`  健康检查: http://localhost:${PORT}/api/health`);
  console.log(`\n  API 端点:`);
  console.log(`    - 插件管理:`);
  console.log(`      GET    /api/plugins              - 获取插件列表`);
  console.log(`      GET    /api/plugins/:id          - 获取插件详情`);
  console.log(`      POST   /api/plugins              - 导入插件 (multipart/form-data)`);
  console.log(`      POST   /api/plugins/validate     - 验证插件 (不导入)`);
  console.log(`      DELETE /api/plugins/:id          - 删除插件`);
  console.log(`    `);
  console.log(`    - 批次管理:`);
  console.log(`      GET    /api/batches              - 获取批次列表`);
  console.log(`      GET    /api/batches/:id          - 获取批次详情`);
  console.log(`      POST   /api/batches              - 创建批次`);
  console.log(`      PUT    /api/batches/:id          - 更新批次`);
  console.log(`      DELETE /api/batches/:id          - 删除批次`);
  console.log(`    `);
  console.log(`    - 样本管理:`);
  console.log(`      GET    /api/batches/:id/samples  - 获取批次样本`);
  console.log(`      POST   /api/batches/:id/samples  - 添加单个样本`);
  console.log(`      POST   /api/batches/:id/samples/batch  - 批量添加样本`);
  console.log(`    `);
  console.log(`    - 执行控制:`);
  console.log(`      POST   /api/batches/:id/run      - 启动批次执行`);
  console.log(`      POST   /api/batches/:id/cancel   - 取消批次执行`);
  console.log(`      GET    /api/batches/:id/progress - 获取执行进度`);
  console.log(`      GET    /api/batches/:id/stats    - 获取执行统计`);
  console.log(`      GET    /api/batches/:id/runs     - 获取运行记录`);
  console.log(`      GET    /api/runs/:id              - 获取单个运行记录`);
  console.log(`    `);
  console.log(`    - 复核管理:`);
  console.log(`      POST   /api/runs/:id/review       - 人工复核`);
  console.log(`    `);
  console.log(`    - 导出功能:`);
  console.log(`      GET    /api/export/:batchId/markdown  - 导出 Markdown 报告`);
  console.log(`      GET    /api/export/:batchId/audit     - 导出 JSON 审计包`);
  console.log(`    `);
  console.log(`    - 系统监控:`);
  console.log(`      GET    /api/running              - 获取正在运行的任务`);
  console.log(`\n========================================\n`);
});
