const f = "/Users/lzy/pro/solo/workspaces/zy72488/src/pages/Workflow.tsx";
const fs = require("fs");
let s = "";
s += "import { useState, useMemo } from 'react';\n";
s += "import { Bus, FileText, CheckCircle, AlertTriangle, Database, FileCheck,\n";
s += "  Layers, Hash, MapPin, User, Clock, ChevronRight, CheckSquare,\n";
s += "  ArrowRight, Search } from 'lucide-react';\n";
s += "import { useStore } from '@/store/useStore';\n";
s += "import StatusBadge from '@/components/StatusBadge';\n";
s += "import { cn } from '@/lib/utils';\n";
s += "import type { Workflow as WorkflowType, Point } from '@/types';\n\n";
s += "const statusLabels = {\n";
s += "  normal: '正常', pending: '待处理', conflict: '有冲突',\n";
s += "  'pending-review': '待复核', 'not-needed': '无需复核',\n";
s += "  approved: '已通过', rejected: '已驳回'\n};\n\n";
s += "export default function Workflow() {\n";
s += "  const { workflows, points, checkDuplicateImport, completeStep1,\n";
s += "    completeStep2, completeStep3 } = useStore();\n\n";
s += "  const [selectedWorkflowId, setSelectedWorkflowId] = useState(workflows[0]?.id || null);\n";
s += "  const [searchTerm, setSearchTerm] = useState('');\n";
s += "  const [busCardTime, setBusCardTime] = useState('');\n";
s += "  const [importSource, setImportSource] = useState('手工录入');\n";
s += "  const [batchId, setBatchId] = useState('');\n";
s += "  const [redLineNote, setRedLineNote] = useState('');\n";
s += "  const [dupCheckResult, setDupCheckResult] = useState(null);\n";
s += "  const [step2ConflictResult, setStep2ConflictResult] = useState(null);\n\n";
s += "  const selectedWorkflow = useMemo(() => workflows.find(w => w.id === selectedWorkflowId) || null, [workflows, selectedWorkflowId]);\n";
s += "  const selectedPoint = useMemo(() => points.find(p => p.id === selectedWorkflow?.pointId), [points, selectedWorkflow]);\n";
s += "  const filteredWorkflows = workflows.filter(w => w.pointName.toLowerCase().includes(searchTerm.toLowerCase()) || (points.find(p => p.id === w.pointId)?.location || '').toLowerCase().includes(searchTerm.toLowerCase()));\n\n";
s += "  const initializeFormFromWorkflow = (wf) => {\n";
s += "    setBusCardTime(wf.stepData.step1?.busCardTime || '');\n";
s += "    setImportSource(wf.stepData.step1?.importSource || '手工录入');\n";
s += "    setBatchId(''); setRedLineNote(wf.stepData.step2?.redLineNote || '');\n";
s += "    setDupCheckResult(null); setStep2ConflictResult(null);\n";
s += "  };\n\n";
s += "  const handleSelectWorkflow = (id) => {\n";
s += "    setSelectedWorkflowId(id);\n";
s += "    const wf = workflows.find(w => w.id === id);\n";
s += "    if (wf) initializeFormFromWorkflow(wf);\n";
s += "  };\n\n";
s += "  const handleCheckDuplicate = () => {\n";
s += "    if (selectedPoint == null || busCardTime.trim() === '') return;\n";
s += "    const r = checkDuplicateImport(selectedPoint.id, busCardTime, batchId.trim() || undefined);\n";
s += "    setDupCheckResult({ checked: true, isDuplicate: r.isDuplicate, isSameBatch: r.isSameBatch,\n";
s += "      sameBatchCount: r.sameBatchCount, batchId: r.batchId, count: r.count, lastSource: r.lastSource });\n";
s += "  };\n\n";
s += "  const handleCompleteStep1 = () => {\n";
s += "    if (selectedWorkflow == null || busCardTime.trim() === '') return;\n";
s += "    const r = completeStep1(selectedWorkflow.id, busCardTime, importSource, batchId.trim() || undefined);\n";
s += "    setDupCheckResult({ checked: true, isDuplicate: r.isDuplicate, isSameBatch: r.isSameBatch,\n";
s += "      sameBatchCount: r.sameBatchCount, batchId: r.batchId, count: r.duplicateCount });\n";
s += "    setBatchId(r.batchId);\n";
s += "  };\n\n";
s += "  const handleCompleteStep2 = () => {\n";
s += "    if (selectedWorkflow == null) return;\n";
s += "    const r = completeStep2(selectedWorkflow.id, redLineNote);\n";
s += "    setStep2ConflictResult({ hasConflict: r.hasConflict, conflictDescription: r.conflictDescription });\n";
s += "  };\n\n";
s += "  const handleCompleteStep3 = () => {\n";
s += "    if (selectedWorkflow == null) return;\n";
s += "    completeStep3(selectedWorkflow.id);\n";
s += "  };\n\n";
s += "  const getStatusBadge = (st) => {\n";
s += "    const m = { normal: 'success', pending: 'warning', conflict: 'error',\n";
s += "      'pending-review': 'warning', 'not-needed': 'info',\n";
s += "      approved: 'success', rejected: 'error' };\n";
s += "    return m[st] || 'info';\n";
s += "  };\n\n";
s += "  const report = selectedWorkflow?.finalReport;\n";
s += "  const overallStatusColor = report?.overallConclusion?.includes('驳回') ? 'bg-red-50 border-red-200' : report?.overallConclusion?.includes('警告') ? 'bg-amber-50 border-amber-200' : 'bg-emerald-50 border-emerald-200';\n";
