const fs = require('fs');
const lines = [];

lines.push("import { create } from 'zustand';");
lines.push("import type { Point, Conflict, HistoryRecord, SelfCheckResult, Workflow } from '@/types';");
lines.push("import { mockPoints, mockConflicts, mockHistoryRecords, mockSelfCheckResults, mockWorkflows } from '@/data/mockData';");
lines.push("");
lines.push("type StoreState = {");
lines.push("  points: Point[];");
lines.push("  conflicts: Conflict[];");
lines.push("  historyRecords: HistoryRecord[];");
lines.push("  selfCheckResults: SelfCheckResult[];");
lines.push("  workflows: Workflow[];");
lines.push("  approveReview: (pointId: string, operator?: string) => void;");
lines.push("  rejectReview: (pointId: string, operator?: string, reason?: string) => void;");
lines.push("  runSelfCheck: () => SelfCheckResult;");
lines.push("  resolveConflict: (conflictId: string, resolution: 'confirmed' | 'rejected' | 'resolved', handler?: string) => void;");
lines.push("  checkDuplicateImport: (pointId: string, busCardTime: string, batchId?: string) => any;");
lines.push("  completeStep1: (workflowId: string, busCardTime: string, importSource?: string, batchId?: string) => any;");
lines.push("  completeStep2: (workflowId: string, redLineNote: string, changeReason?: string) => any;");
lines.push("  completeStep3: (workflowId: string) => any;");
lines.push("};");
lines.push("");
lines.push("const now = () => new Date().toISOString();");
lines.push("const uid = () => Math.random().toString(36).slice(2, 10);");
lines.push("");
lines.push("const genBatchId = () => 'batch-' + new Date().toISOString().slice(0, 7).replace(/-/g, '') + '-' + uid().slice(0, 4).toUpperCase();");
lines.push("");
lines.push("export const useStore = create<StoreState>((set, get) => ({");
lines.push("  points: mockPoints,");
lines.push("  conflicts: mockConflicts,");
lines.push("  historyRecords: mockHistoryRecords,");
lines.push("  selfCheckResults: mockSelfCheckResults,");
lines.push("  workflows: mockWorkflows,");
lines.push("");
lines.push("  approveReview: (pointId, operator = '系统管理员') => {");
lines.push("    set((s) => {");
lines.push("      const pts = s.points.map((p) => (p.id === pointId ? { ...p, reviewStatus: 'approved' as const, status: 'normal' as const, updatedAt: now() } : p));");
lines.push("      const hr = [...s.historyRecords, { id: 'hr-' + uid(), pointId, pointName: s.points.find((p) => p.id === pointId)?.name || '', action: 'review' as const, operator, beforeData: { reviewStatus: 'pending' }, afterData: { reviewStatus: 'approved', status: 'normal' }, fieldChanges: [{ field: 'reviewStatus', fieldLabel: '复核状态', beforeValue: '待复核', afterValue: '已通过' }, { field: 'status', fieldLabel: '点位状态', beforeValue: '待复核', afterValue: '正常' }], changeReason: '居民代表复核通过', remark: '', createdAt: now() }];");
lines.push("      return { points: pts, historyRecords: hr };");
lines.push("    });");
lines.push("  },");
lines.push("");
lines.push("  rejectReview: (pointId, operator = '系统管理员', reason = '存在疑问') => {");
lines.push("    set((s) => {");
lines.push("      const pts = s.points.map((p) => (p.id === pointId ? { ...p, reviewStatus: 'rejected' as const, status: 'conflict' as const, updatedAt: now() } : p));");
lines.push("      const hr = [...s.historyRecords, { id: 'hr-' + uid(), pointId, pointName: s.points.find((p) => p.id === pointId)?.name || '', action: 'review' as const, operator, beforeData: { reviewStatus: 'pending' }, afterData: { reviewStatus: 'rejected', status: 'conflict' }, fieldChanges: [{ field: 'reviewStatus', fieldLabel: '复核状态', beforeValue: '待复核', afterValue: '已驳回' }, { field: 'status', fieldLabel: '点位状态', beforeValue: '待复核', afterValue: '有冲突' }], changeReason: '居民代表复核驳回', remark: reason, createdAt: now() }];");
lines.push("      return { points: pts, historyRecords: hr };");
lines.push("    });");
lines.push("  },");
lines.push("");
lines.push("  runSelfCheck: () => {");
lines.push("    const { points } = get();");
lines.push("    const issues1: string[] = [], issues2: string[] = [], issues3: string[] = [];");
lines.push("    points.forEach((p) => {");
lines.push("      if (p.busCardTime && p.redLineNote) {");
lines.push("        const hasMorning = p.busCardTime.includes('7:') || p.busCardTime.includes('8:');");
lines.push("        const redBan = p.redLineNote.includes('禁止');");
lines.push("        if (hasMorning && redBan) issues1.push(p.name + ' 早高峰时段与红线禁止设摊冲突');");
lines.push("      }");
lines.push("      if (p.hasConstructionDetour && !p.mapSynced) issues2.push(p.name + ' 施工改道未同步地图');");
lines.push("      if (p.importCount > 1 && p.importBatches.some((b) => b.isDuplicate)) issues3.push(p.name + ' 存在重复导入记录');");
lines.push("    });");
lines.push("    const st1: any = issues1.length ? 'error' : 'pass';");
lines.push("    const st2: any = issues2.length ? 'warning' : 'pass';");
lines.push("    const st3: any = issues3.length ? 'warning' : 'pass';");
lines.push("    const overall = st1 === 'error' || st2 === 'error' ? 'error' : st1 === 'warning' || st2 === 'warning' || st3 === 'warning' ? 'warning' : 'pass';");
lines.push("    const r: SelfCheckResult = { id: 'sc-' + uid(), reportName: '点位数据自动自检报告-' + new Date().toLocaleDateString(), overallStatus: overall as any, summary: `共检测 ${points.length} 个点位，发现 ${issues1.length + issues2.length + issues3.length} 个问题`, items: [{ type: 'bus-vs-redline', typeName: '公交时段 vs 红线', source: '内置规则', status: st1, issues: issues1, conclusion: issues1.length ? `发现${issues1.length}个时段与红线冲突` : '无冲突' }, { type: 'detour-sync', typeName: '施工改道同步', source: 'GIS地图对比', status: st2, issues: issues2, conclusion: issues2.length ? `${issues2.length}个点位改道未同步` : '已全部同步' }, { type: 'data-integrity', typeName: '导入完整性', source: '批次校验', status: st3, issues: issues3, conclusion: issues3.length ? `${issues3.length}个点位存在重复导入` : '导入数据完整' }], checkedAt: now(), operator: '系统自动检测' };");
lines.push("    set({ selfCheckResults: [...get().selfCheckResults, r] });");
lines.push("    return r;");
lines.push("  },");
lines.push("");
lines.push("  resolveConflict: (conflictId, resolution, handler = '管理员') => {");
lines.push("    set((s) => ({ conflicts: s.conflicts.map((c) => (c.id === conflictId ? { ...c, status: resolution, handler, handledAt: now() } : c)) }));");
lines.push("  },");
lines.push("");
lines.push("  checkDuplicateImport: (pointId, busCardTime, batchId) => {");
lines.push("    const pt = get().points.find((p) => p.id === pointId);");
lines.push("    if (!pt) return { isDuplicate: false, count: 0, lastSource: '', batchId: batchId || genBatchId(), sameBatchCount: 0, isSameBatch: false, duplicateBatches: [] };");
lines.push("    const trimmed = busCardTime.trim();");
lines.push("    const sameTimeBatches = pt.importBatches.filter((b) => b.busCardTime === trimmed);");
lines.push("    const isDuplicate = sameTimeBatches.length > 0;");
lines.push("    let isSameBatch = false, sameBatchCount = 0;");
lines.push("    if (batchId) {");
lines.push("      const same = sameTimeBatches.filter((b) => b.batchId === batchId);");
lines.push("      isSameBatch = same.length > 0;");
lines.push("      sameBatchCount = same.length + 1;");
lines.push("    }");
lines.push("    const last = pt.importBatches[pt.importBatches.length - 1];");
lines.push("    return { isDuplicate, count: sameTimeBatches.length, lastSource: last?.source || pt.lastImportSource || '', batchId: batchId || last?.batchId || genBatchId(), sameBatchCount: sameBatchCount || (isDuplicate ? sameTimeBatches.length + 1 : 0), isSameBatch, duplicateBatches: sameTimeBatches.map((b) => b.batchId) };");
lines.push("  },");
lines.push("");
lines.push("  completeStep1: (workflowId, busCardTime, importSource = '公交公司', batchId) => {");
lines.push("    const { points, workflows } = get();");
lines.push("    const wf = workflows.find((w) => w.id === workflowId);");
lines.push("    if (!wf) return {};");
lines.push("    const pt = points.find((p) => p.id === wf.pointId);");
lines.push("    if (!pt) return {};");
lines.push("    const check = get().checkDuplicateImport(pt.id, busCardTime, batchId);");
lines.push("    const finalBatchId = batchId || check.batchId || genBatchId();");
lines.push("    const newOrder = pt.importBatches.length + 1;");
lines.push("    const isDup = check.isDuplicate;");
lines.push("    const newBatches = [...pt.importBatches, { batchId: finalBatchId, source: importSource, importedAt: now(), busCardTime: busCardTime.trim(), isDuplicate: isDup, importOrder: newOrder }];");
lines.push("    const newPoints = points.map((p) => (p.id === pt.id ? { ...p, busCardTime: busCardTime.trim(), importCount: p.importCount + 1, lastImportSource: importSource, lastImportBatchId: finalBatchId, importBatches: newBatches, updatedAt: now() } : p));");
lines.push("    const newWfs = workflows.map((w) => (w.id === workflowId ? { ...w, currentStep: 2 as const, stepData: { ...w.stepData, step1: { busCardTime: busCardTime.trim(), importedAt: now(), importSource, isDuplicate: isDup, duplicateDetected: isDup } } } : w));");
lines.push("    set({ points: newPoints, workflows: newWfs });");
lines.push("    return { isDuplicate: isDup, duplicateCount: check.count, batchId: finalBatchId, sameBatchCount: check.sameBatchCount, isSameBatch: check.isSameBatch };");
lines.push("  },");
lines.push("");
lines.push("  completeStep2: (workflowId, redLineNote, changeReason) => {");
lines.push("    const { points, workflows } = get();");
lines.push("    const wf = workflows.find((w) => w.id === workflowId);");
lines.push("    if (!wf) return {};");
lines.push("    const pt = points.find((p) => p.id === wf.pointId);");
lines.push("    if (!pt) return {};");
lines.push("    let hasConflict = false, conflictDescription = '';");
lines.push("    const bus = (wf.stepData.step1?.busCardTime || pt.busCardTime).toLowerCase();");
lines.push("    const red = redLineNote.toLowerCase();");
lines.push("    const morning = bus.includes('7:') || bus.includes('8:');");
lines.push("    const banned = red.includes('禁止');");
lines.push("    if (morning && banned) { hasConflict = true; conflictDescription = '早高峰时段与红线图禁止设摊存在冲突'; }");
lines.push("    const newPoints = points.map((p) => (p.id === pt.id ? { ...p, redLineNote, updatedAt: now() } : p));");
lines.push("    const newStatus = hasConflict ? 'conflict' : 'pending';");
lines.push("    const newWfs = workflows.map((w) => (w.id === workflowId ? { ...w, currentStep: 3 as const, status: 'in-progress' as const, stepData: { ...w.stepData, step2: { redLineNote, reviewedAt: now(), reviewer: '管理员', hasConflict, conflictDescription } } } : w));");
lines.push("    const hrs = [...get().historyRecords, { id: 'hr-' + uid(), pointId: pt.id, pointName: pt.name, action: 'supplement' as const, operator: '管理员', beforeData: { redLineNote: pt.redLineNote }, afterData: { redLineNote }, fieldChanges: [{ field: 'redLineNote', fieldLabel: '红线图备注', beforeValue: pt.redLineNote || '空', afterValue: redLineNote }], changeReason: changeReason || '补录红线备注', remark: hasConflict ? '检测到冲突' : '', createdAt: now() }];");
lines.push("    set({ points: newPoints, workflows: newWfs, historyRecords: hrs });");
lines.push("    return { hasConflict, conflictDescription };");
lines.push("  },");
lines.push("");
lines.push("  completeStep3: (workflowId) => {");
lines.push("    const { points, workflows, historyRecords } = get();");
lines.push("    const wf = workflows.find((w) => w.id === workflowId);");
lines.push("    if (!wf) return {};");
lines.push("    const pt = points.find((p) => p.id === wf.pointId);");
lines.push("    if (!pt) return {};");
lines.push("    const s1 = wf.stepData.step1; const s2 = wf.stepData.step2;");
lines.push("    const hasDup = s1?.isDuplicate || pt.importCount > 1;");
lines.push("    const detourWarn = pt.hasConstructionDetour && !pt.mapSynced;");
lines.push("    const needsReview = detourWarn;");
lines.push("    const pointStatus = detourWarn ? 'pending-review' : (s2?.hasConflict ? 'conflict' : 'normal');");
lines.push("    const reviewStatus = detourWarn ? 'pending' : (pt.hasConstructionDetour ? 'approved' : 'not-needed');");
lines.push("    const wfStatus: any = needsReview ? 'pending-review' : 'completed';");
lines.push("    const totalImports = pt.importBatches.length;");
lines.push("    const lastBatch = pt.importBatches[pt.importBatches.length - 1];");
lines.push("    const dupBatches = pt.importBatches.filter((x) => x.isDuplicate).length;");
lines.push("    const overallStatus: any = detourWarn ? 'warning' : (s2?.hasConflict ? 'error' : 'pass');");
lines.push("    const overallConclusion = detourWarn ? '待居民代表复核' : (s2?.hasConflict ? '存在时段与红线冲突，需人工介入' : '全部检查通过，点位已更新为正常');");
lines.push("    const fr = { duplicateCheck: { passed: !hasDup, detail: hasDup ? `存在${dupBatches}条重复导入记录，已自动去重，数据未翻倍` : '无重复导入', batchInfo: { totalBatches: new Set(pt.importBatches.map((b) => b.batchId)).size, totalImports, duplicateBatches: dupBatches, lastBatchId: lastBatch?.batchId || '', lastBatchSource: lastBatch?.source || s1?.importSource || '', lastBatchDuplicateCount: pt.importBatches.filter((x) => x.batchId === lastBatch?.batchId).length, isDeduplicated: hasDup } }, detourSync: { passed: !detourWarn, detail: detourWarn ? '存在施工改道且地图未同步，待居民代表现场复核' : '施工改道已同步或无改道', detourInfo: { hasDetour: pt.hasConstructionDetour, mapSynced: pt.mapSynced, detourDescription: detourWarn ? '施工改道信息待现场核实' : '无异常', reportSource: pt.hasConstructionDetour ? (pt.mapSynced ? 'GIS地图系统' : '施工队上报') : '无' } }, supplementRecalc: { passed: true, detail: s2?.hasConflict ? '补录完成，但检测到与公交时段冲突' : '补录完成，统计数据已重算', supplementInfo: { hasSupplement: !!s2?.redLineNote, redLineNote: s2?.redLineNote || '', hasConflict: !!s2?.hasConflict, conflictDescription: s2?.conflictDescription || '', statsRecalculated: true } }, exportConsistent: { passed: true, detail: '导出字段完整，包含批次、次数、状态、复核、改道信息', exportInfo: { fields: ['批次ID', '导入次数', '点位状态', '复核状态', '改道信息'], isConsistent: true } }, overallConclusion, overallStatus, finalPointStatus: pointStatus, finalReviewStatus: reviewStatus };");
lines.push("    const newPoints = points.map((p) => (p.id === pt.id ? { ...p, status: pointStatus as any, reviewStatus: reviewStatus as any, updatedAt: now() } : p));");
lines.push("    const newWfs = workflows.map((w) => (w.id === workflowId ? { ...w, currentStep: 3 as const, status: wfStatus, stepData: { ...w.stepData, step3: { updatedAt: now(), operator: '管理员', pointStatus, reviewStatus } }, finalReport: fr } : w));");
lines.push("    const hrs = [...historyRecords, { id: 'hr-' + uid(), pointId: pt.id, pointName: pt.name, action: 'update' as const, operator: '管理员', beforeData: { status: pt.status, reviewStatus: pt.reviewStatus }, afterData: { status: pointStatus, reviewStatus }, fieldChanges: [{ field: 'status', fieldLabel: '点位状态', beforeValue: pt.status, afterValue: pointStatus }, { field: 'reviewStatus', fieldLabel: '复核状态', beforeValue: pt.reviewStatus, afterValue: reviewStatus }], changeReason: '三步流程完成，系统自动判定', remark: '', createdAt: now() }];");
lines.push("    set({ points: newPoints, workflows: newWfs, historyRecords: hrs });");
lines.push("    return { pointStatus, reviewStatus, needsReview };");
lines.push("  },");
lines.push("}));");

const content = lines.join('\n') + '\n';
fs.writeFileSync('src/store/useStore.ts', content);
console.log('useStore.ts written:', content.length, 'bytes,', lines.length, 'lines');
