const express = require('express');
const router = express.Router();
const damageService = require('../services/damageService');
const responseHandler = require('../utils/responseHandler');

function getOperator(req) {
  return req.headers['x-operator'] || 'system';
}

router.post('/', (req, res) => {
  try {
    const charge = damageService.createDamageCharge(req.body, getOperator(req));
    res.status(201).json(responseHandler.success(charge, '损坏扣费创建成功'));
  } catch (error) {
    res.status(400).json(responseHandler.error(error.message, 400));
  }
});

router.get('/order/:orderId', (req, res) => {
  try {
    const charges = damageService.getDamageChargesByOrderId(req.params.orderId);
    const total = damageService.getDamageTotal(req.params.orderId);
    res.json(responseHandler.success({
      charges,
      total
    }));
  } catch (error) {
    res.status(500).json(responseHandler.error(error.message));
  }
});

router.post('/auto-generate/:orderId', (req, res) => {
  try {
    const newCharges = damageService.autoGenerateDamageCharges(req.params.orderId, getOperator(req));
    res.json(responseHandler.success(newCharges, `成功生成 ${newCharges.length} 条损坏扣费`));
  } catch (error) {
    res.status(400).json(responseHandler.error(error.message, 400));
  }
});

router.put('/:chargeId', (req, res) => {
  try {
    const charge = damageService.updateDamageCharge(req.params.chargeId, req.body, getOperator(req));
    res.json(responseHandler.success(charge, '损坏扣费更新成功'));
  } catch (error) {
    res.status(400).json(responseHandler.error(error.message, 400));
  }
});

router.post('/:chargeId/adjust', (req, res) => {
  try {
    const { new_amount, reason } = req.body;
    if (!reason) {
      return res.status(400).json(responseHandler.error('人工调整必须提供原因', 400));
    }
    if (new_amount === undefined || new_amount < 0) {
      return res.status(400).json(responseHandler.error('新金额不能为空且不能为负数', 400));
    }
    
    const charge = damageService.manuallyAdjustDamage(
      req.params.chargeId,
      parseFloat(new_amount),
      reason,
      getOperator(req)
    );
    res.json(responseHandler.success(charge, '人工调整成功'));
  } catch (error) {
    res.status(400).json(responseHandler.error(error.message, 400));
  }
});

router.delete('/:chargeId', (req, res) => {
  try {
    damageService.deleteDamageCharge(req.params.chargeId, getOperator(req));
    res.json(responseHandler.success(null, '损坏扣费删除成功'));
  } catch (error) {
    res.status(400).json(responseHandler.error(error.message, 400));
  }
});

module.exports = router;
