def build_main():
    lines = []
    
    lines.append("from fastapi import FastAPI, Depends, HTTPException, UploadFile, File, Form")
    lines.append("from fastapi.middleware.cors import CORSMiddleware")
    lines.append("from fastapi.responses import FileResponse")
    lines.append("from typing import List, Optional")
    lines.append("from datetime import date")
    lines.append("import os")
    lines.append("import tempfile")
    lines.append("from app.services import (")
    lines.append("    DataStore, DataImporter, ComparisonEngine, ")
    lines.append("    ReviewService, RecalculationService, ReportGenerator, ExplanationGenerator")
    lines.append(")")
    lines.append("from app.models import ReviewStatus")
    lines.append("")
    lines.append("")
    lines.append("def create_app() -> FastAPI:")
    lines.append("    app = FastAPI(")
    lines.append('        title="Flight Delay Reconciliation API",')
    lines.append('        description="Data import, auto comparison, review, report generation",')
    lines.append('        version="1.0.0"')
    lines.append("    )")
    lines.append("")
    lines.append("    app.add_middleware(")
    lines.append("        CORSMiddleware,")
    lines.append('        allow_origins=["*"],')
    lines.append("        allow_credentials=True,")
    lines.append('        allow_methods=["*"],')
    lines.append('        allow_headers=["*"],')
    lines.append("    )")
    lines.append("")
    lines.append("    def get_data_store() -> DataStore:")
    lines.append("        return DataStore()")
    lines.append("")
    lines.append("    def get_data_importer(store: DataStore = Depends(get_data_store)) -> DataImporter:")
    lines.append("        return DataImporter(store)")
    lines.append("")
    lines.append("    def get_comparison_engine(store: DataStore = Depends(get_data_store)) -> ComparisonEngine:")
    lines.append("        return ComparisonEngine(store)")
    lines.append("")
    lines.append("    def get_review_service(store: DataStore = Depends(get_data_store)) -> ReviewService:")
    lines.append("        return ReviewService(store)")
    lines.append("")
    lines.append("    def get_recalculation_service(")
    lines.append("        store: DataStore = Depends(get_data_store),")
    lines.append("        engine: ComparisonEngine = Depends(get_comparison_engine)")
    lines.append("    ) -> RecalculationService:")
    lines.append("        return RecalculationService(store, engine)")
    lines.append("")
    lines.append("    def get_explanation_generator() -> ExplanationGenerator:")
    lines.append("        return ExplanationGenerator()")
    lines.append("")
    lines.append("    def get_report_generator(")
    lines.append("        store: DataStore = Depends(get_data_store),")
    lines.append("        explainer: ExplanationGenerator = Depends(get_explanation_generator)")
    lines.append("    ) -> ReportGenerator:")
    lines.append("        return ReportGenerator(store, explainer)")
    lines.append("")
    lines.append('    @app.get("/", tags=["System"], summary="Health check")')
    lines.append("    async def root():")
    lines.append('        return {"status": "ok", "message": "API is running"}')
    
    lines.append("")
    lines.append('    @app.post("/api/import/claims/csv", tags=["Data Import"])')
    lines.append("    async def import_claims_csv(")
    lines.append("        file: UploadFile = File(...),")
    lines.append("        importer: DataImporter = Depends(get_data_importer)")
    lines.append("    ):")
    lines.append('        if not file.filename.endswith(".csv"):')
    lines.append('            raise HTTPException(status_code=400, detail="CSV file required")')
    lines.append("        content = await file.read()")
    lines.append('        result = importer.import_claims_csv(content.decode("utf-8"))')
    lines.append('        if not result.get("success"):')
    lines.append('            raise HTTPException(status_code=400, detail=result.get("error"))')
    lines.append("        return result")
    
    lines.append("")
    lines.append('    @app.post("/api/import/claims/json", tags=["Data Import"])')
    lines.append("    async def import_claims_json(")
    lines.append("        file: UploadFile = File(...),")
    lines.append("        importer: DataImporter = Depends(get_data_importer)")
    lines.append("    ):")
    lines.append('        if not file.filename.endswith(".json"):')
    lines.append('            raise HTTPException(status_code=400, detail="JSON file required")')
    lines.append("        content = await file.read()")
    lines.append('        result = importer.import_claims_json(content.decode("utf-8"))')
    lines.append('        if not result.get("success"):')
    lines.append('            raise HTTPException(status_code=400, detail=result.get("error"))')
    lines.append("        return result")

    lines.append("")
    lines.append('    @app.post("/api/import/flights/csv", tags=["Data Import"])')
    lines.append("    async def import_flights_csv(")
    lines.append("        file: UploadFile = File(...),")
    lines.append("        importer: DataImporter = Depends(get_data_importer)")
    lines.append("    ):")
    lines.append('        if not file.filename.endswith(".csv"):')
    lines.append('            raise HTTPException(status_code=400, detail="CSV file required")')
    lines.append("        content = await file.read()")
    lines.append('        result = importer.import_flights_csv(content.decode("utf-8"))')
    lines.append('        if not result.get("success"):')
    lines.append('            raise HTTPException(status_code=400, detail=result.get("error"))')
    lines.append("        return result")

    lines.append("")
    lines.append('    @app.post("/api/import/flights/json", tags=["Data Import"])')
    lines.append("    async def import_flights_json(")
    lines.append("        file: UploadFile = File(...),")
    lines.append("        importer: DataImporter = Depends(get_data_importer)")
    lines.append("    ):")
    lines.append('        if not file.filename.endswith(".json"):')
    lines.append('            raise HTTPException(status_code=400, detail="JSON file required")')
    lines.append("        content = await file.read()")
    lines.append('        result = importer.import_flights_json(content.decode("utf-8"))')
    lines.append('        if not result.get("success"):')
    lines.append('            raise HTTPException(status_code=400, detail=result.get("error"))')
    lines.append("        return result")

    lines.append("")
    lines.append('    @app.post("/api/import/photos", tags=["Data Import"])')
    lines.append("    async def import_photos(")
    lines.append("        file: UploadFile = File(...),")
    lines.append("        importer: DataImporter = Depends(get_data_importer)")
    lines.append("    ):")
    lines.append('        if not file.filename.endswith(".json"):')
    lines.append('            raise HTTPException(status_code=400, detail="JSON file required")')
    lines.append("        content = await file.read()")
    lines.append('        result = importer.import_photos_index(content.decode("utf-8"))')
    lines.append('        if not result.get("success"):')
    lines.append('            raise HTTPException(status_code=400, detail=result.get("error"))')
    lines.append("        return result")

    lines.append("")
    lines.append('    @app.post("/api/import/rules", tags=["Data Import"])')
    lines.append("    async def import_rules(")
    lines.append("        file: UploadFile = File(...),")
    lines.append("        importer: DataImporter = Depends(get_data_importer)")
    lines.append("    ):")
    lines.append('        if not file.filename.endswith(".json"):')
    lines.append('            raise HTTPException(status_code=400, detail="JSON file required")')
    lines.append("        content = await file.read()")
    lines.append('        result = importer.import_rules_json(content.decode("utf-8"))')
    lines.append('        if not result.get("success"):')
    lines.append('            raise HTTPException(status_code=400, detail=result.get("error"))')
    lines.append("        return result")

    lines.append("")
    lines.append('    @app.post("/api/compare/all", tags=["Auto Comparison"])')
    lines.append("    async def compare_all(")
    lines.append("        engine: ComparisonEngine = Depends(get_comparison_engine)")
    lines.append("    ):")
    lines.append("        results = engine.compare_all()")
    lines.append('        return {"success": True, "total": len(results), "results": [r.model_dump() for r in results]}')

    lines.append("")
    lines.append('    @app.post("/api/compare/{claim_id}", tags=["Auto Comparison"])')
    lines.append("    async def compare_single(")
    lines.append("        claim_id: str,")
    lines.append("        engine: ComparisonEngine = Depends(get_comparison_engine),")
    lines.append("        store: DataStore = Depends(get_data_store)")
    lines.append("    ):")
    lines.append("        claim = store.get_claim(claim_id)")
    lines.append("        if not claim:")
    lines.append('            raise HTTPException(status_code=404, detail="Claim not found")')
    lines.append("        result = engine.compare_claim(claim)")
    lines.append("        store.add_comparison_result(result)")
    lines.append('        return {"success": True, "result": result.model_dump()}')

    lines.append("")
    lines.append('    @app.get("/api/comparisons", tags=["Auto Comparison"])')
    lines.append("    async def get_all_comparisons(store: DataStore = Depends(get_data_store)):")
    lines.append("        results = store.get_all_comparison_results()")
    lines.append('        return {"success": True, "count": len(results), "results": [r.model_dump() for r in results]}')

    lines.append("")
    lines.append('    @app.get("/api/comparisons/{claim_id}", tags=["Auto Comparison"])')
    lines.append("    async def get_comparison(claim_id: str, store: DataStore = Depends(get_data_store)):")
    lines.append("        result = store.get_comparison_result(claim_id)")
    lines.append("        if not result:")
    lines.append('            raise HTTPException(status_code=404, detail="Result not found")')
    lines.append('        return {"success": True, "result": result.model_dump()}')

    lines.append("")
    lines.append('    @app.post("/api/review/{claim_id}", tags=["Manual Review"])')
    lines.append("    async def review_claim(")
    lines.append("        claim_id: str,")
    lines.append("        reviewer: str = Form(...),")
    lines.append("        status: ReviewStatus = Form(...),")
    lines.append("        reviewed_amount: float = Form(...),")
    lines.append("        review_notes: str = Form(...),")
    lines.append("        adjustment_reason: Optional[str] = Form(None),")
    lines.append("        review_service: ReviewService = Depends(get_review_service)")
    lines.append("    ):")
    lines.append("        result = review_service.review_claim(")
    lines.append("            claim_id=claim_id, reviewer=reviewer, status=status,")
    lines.append("            reviewed_amount=reviewed_amount, review_notes=review_notes,")
    lines.append("            adjustment_reason=adjustment_reason")
    lines.append("        )")
    lines.append('        if not result.get("success"):')
    lines.append('            raise HTTPException(status_code=400, detail=result.get("error"))')
    lines.append("        return result")

    lines.append("")
    lines.append('    @app.get("/api/review/pending", tags=["Manual Review"])')
    lines.append("    async def get_pending_reviews(review_service: ReviewService = Depends(get_review_service)):")
    lines.append("        results = review_service.get_pending_reviews()")
    lines.append('        return {"success": True, "count": len(results), "results": [r.model_dump() for r in results]}')

    lines.append("")
    lines.append('    @app.post("/api/recalculate/{claim_id}", tags=["Recalculation"])')
    lines.append("    async def recalculate_claim(")
    lines.append("        claim_id: str,")
    lines.append('        reason: str = Form("Recalculated"),')
    lines.append("        recalc_service: RecalculationService = Depends(get_recalculation_service)")
    lines.append("    ):")
    lines.append("        result = recalc_service.recalculate_claim(claim_id, reason)")
    lines.append('        if not result.get("success"):')
    lines.append('            raise HTTPException(status_code=400, detail=result.get("error"))')
    lines.append("        return result")

    lines.append("")
    lines.append('    @app.post("/api/recalculate/all", tags=["Recalculation"])')
    lines.append("    async def recalculate_all(")
    lines.append('        reason: str = Form("Batch recalculation"),')
    lines.append("        recalc_service: RecalculationService = Depends(get_recalculation_service)")
    lines.append("    ):")
    lines.append("        results = recalc_service.recalculate_all(reason)")
    lines.append('        return {"success": True, "total": len(results), "results": results}')

    lines.append("")
    lines.append('    @app.get("/api/report/{claim_id}", tags=["Report"])')
    lines.append("    async def get_detail_report(")
    lines.append("        claim_id: str,")
    lines.append("        report_generator: ReportGenerator = Depends(get_report_generator)")
    lines.append("    ):")
    lines.append("        report = report_generator.generate_detail_report(claim_id)")
    lines.append('        if not report.get("success"):')
    lines.append('            raise HTTPException(status_code=404, detail=report.get("error"))')
    lines.append("        return report")

    lines.append("")
    lines.append('    @app.get("/api/export/csv", tags=["Export"])')
    lines.append("    async def export_csv(report_generator: ReportGenerator = Depends(get_report_generator)):")
    lines.append('        with tempfile.NamedTemporaryFile(mode="w", suffix=".csv", delete=False, encoding="utf-8-sig") as f:')
    lines.append("            temp_path = f.name")
    lines.append("        result = report_generator.export_to_csv(temp_path)")
    lines.append('        if not result.get("success"):')
    lines.append("            os.unlink(temp_path)")
    lines.append('            raise HTTPException(status_code=400, detail=result.get("error"))')
    lines.append('        return FileResponse(temp_path, media_type="text/csv", filename=f"report_{date.today()}.csv")')

    lines.append("")
    lines.append('    @app.get("/api/export/excel", tags=["Export"])')
    lines.append("    async def export_excel(report_generator: ReportGenerator = Depends(get_report_generator)):")
    lines.append("        with tempfile.NamedTemporaryFile(suffix=".xlsx", delete=False) as f:")
    lines.append("            temp_path = f.name")
    lines.append("        result = report_generator.export_to_excel(temp_path)")
    lines.append('        if not result.get("success"):')
    lines.append("            os.unlink(temp_path)")
    lines.append('            raise HTTPException(status_code=400, detail=result.get("error"))')
    lines.append('        return FileResponse(temp_path, media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", filename=f"report_{date.today()}.xlsx")')

    lines.append("")
    lines.append('    @app.get("/api/statistics/summary", tags=["Statistics"])')
    lines.append("    async def get_summary(report_generator: ReportGenerator = Depends(get_report_generator)):")
    lines.append("        summary = report_generator.generate_summary()")
    lines.append('        return {"success": True, "summary": summary.model_dump()}')

    lines.append("")
    lines.append('    @app.get("/api/statistics/claims", tags=["Statistics"])')
    lines.append("    async def get_claims_stats(store: DataStore = Depends(get_data_store)):")
    lines.append("        claims = store.get_all_claims()")
    lines.append("        total = sum(c.claim_amount for c in claims)")
    lines.append('        return {"success": True, "total_claims": len(claims), "total_amount": total, "claims": [c.model_dump() for c in claims]}')

    lines.append("")
    lines.append('    @app.get("/api/statistics/flights", tags=["Statistics"])')
    lines.append("    async def get_flights_stats(store: DataStore = Depends(get_data_store)):")
    lines.append("        flights = store.get_all_flights()")
    lines.append("        delayed = [f for f in flights if f.delay_minutes > 0]")
    lines.append("        avg_delay = sum(f.delay_minutes for f in delayed) / len(delayed) if delayed else 0")
    lines.append('        return {"success": True, "total_flights": len(flights), "delayed_flights": len(delayed), "average_delay_minutes": round(avg_delay, 2)}')

    lines.append("")
    lines.append("    return app")
    lines.append("")
    lines.append("")
    lines.append("app = create_app()")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    import uvicorn")
    lines.append('    uvicorn.run(app, host="0.0.0.0", port=8000)')
    lines.append("")
    
    with open('main.py', 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    
    print(f"Built main.py with {len(lines)} lines")

if __name__ == "__main__":
    build_main()
