#!/usr/bin/env python3
output = 'app/services.py'
with open(output, 'a') as f:
    f.write('\n')
    f.write('    def add_photo(self, photo: PhotoIndex):\n')
    f.write('        self.photos[photo.photo_id] = photo\n')
    f.write('\n')
print(f"Lines: {sum(1 for _ in open(output))}")
    f.write('    def get_photos_for_claim(self, claim_id: str) -> List[PhotoIndex]:\n')
    f.write('        return [p for p in self.photos.values() if p.claim_id == claim_id]\n')
    f.write('\n')
    f.write('    def add_rule(self, rule: CompensationRule):\n')
    f.write('        self.rules[rule.rule_id] = rule\n')
    f.write('\n')
    f.write('    def get_all_rules(self) -> List[CompensationRule]:\n')
    f.write('        return list(self.rules.values())\n')
    f.write('\n')
    f.write('    def add_comparison_result(self, result: ComparisonResult):\n')
    f.write('        self.comparison_results[result.claim_id] = result\n')
    f.write('\n')
    f.write('    def get_comparison_result(self, claim_id: str) -> Optional[ComparisonResult]:\n')
    f.write('        return self.comparison_results.get(claim_id)\n')
    f.write('\n')
    f.write('    def get_all_comparison_results(self) -> List[ComparisonResult]:\n')
    f.write('        return list(self.comparison_results.values())\n')
    f.write('\n')
    f.write('    def add_review(self, claim_id: str, review: ReviewRecord):\n')
    f.write('        result = self.comparison_results.get(claim_id)\n')
    f.write('        if result:\n')
    f.write('            result.review_record = review\n')
    f.write('            if review.reviewed_amount > 0:\n')
    f.write('                result.final_amount = review.reviewed_amount\n')
    f.write('\n')
    f.write('    def clear_all(self):\n')
    f.write('        self.claims.clear()\n')
    f.write('        self.flights.clear()\n')
    f.write('        self.photos.clear()\n')
    f.write('        self.rules.clear()\n')
    f.write('        self.comparison_results.clear()\n')

print(f"Lines: {sum(1 for _ in open(output))}")
