lines = [
  "from typing import Dict, List, Optional",
  "from datetime import datetime, date, timedelta",
  "import uuid",
  "import pandas as pd",
  "import json",
  "from io import StringIO",
  "from app.models import (",
  "    ClaimRecord, FlightInfo, PhotoIndex, CompensationRule,",
  "    ComparisonResult, ReviewRecord, ReconciliationSummary,",
  "    ReviewStatus, DiscrepancyType, DiscrepancyItem",
  ")",
  "",
  "",
  "class DataStore:",
