with open('app/services.py', 'w') as f:
    f.write('from typing import Dict, List, Optional\n')
    f.write('from datetime import datetime, date\n')
    f.write('import uuid\n')
    f.write('import pandas as pd\n')
    f.write('import json\n')
    f.write('from io import StringIO\n')
    f.write('from app.models import (\n')
    f.write('    ClaimRecord, FlightInfo, PhotoIndex, CompensationRule,\n')
    f.write('    ComparisonResult, ReviewRecord, ReconciliationSummary,\n')
    f.write('    ReviewStatus, DiscrepancyType, DiscrepancyItem\n')
    f.write(')\n')
    f.write('\n\n')
print('Step 1 done')
