import type { Entity, EquityLink } from '../types'

const SOURCE_FILE = '材料包A-股权数据.xlsx'
const IMPORT_TIME = '2026-05-28T09:15:00.000Z'
const PROCESS_TIME = '2026-05-28T09:15:12.347Z'

export const mockEntities: Entity[] = [
  {
    id: 'e001',
    name: '华融金控集团',
    alias: ['华融金控'],
    coordinateSystem: 'WGS84',
    x: 1200,
    y: 800,
    floor: 1,
    photoUrl: 'https://example.com/photos/huarong-jk.jpg',
    shareRatio: 100,
    sourceFile: SOURCE_FILE,
    importTime: IMPORT_TIME,
    processTime: PROCESS_TIME,
    notes: '集团母公司，核心控股平台',
  },
  {
    id: 'e002',
    name: '华融资产管理',
    alias: ['华融资产'],
    coordinateSystem: 'WGS84',
    x: 1180,
    y: 850,
    floor: 1,
    photoUrl: 'https://example.com/photos/huarong-amc.jpg',
    shareRatio: 65,
    sourceFile: SOURCE_FILE,
    importTime: IMPORT_TIME,
    processTime: PROCESS_TIME,
    notes: '不良资产处置平台',
  },
  {
    id: 'e003',
    name: '华融资产管理有限公司',
    alias: ['华融资管'],
    coordinateSystem: 'WGS84',
    x: 1220,
    y: 860,
    floor: 1,
    photoUrl: 'https://example.com/photos/huarong-amc-full.jpg',
    shareRatio: 65,
    sourceFile: SOURCE_FILE,
    importTime: IMPORT_TIME,
    processTime: PROCESS_TIME,
    notes: '与华融资产管理疑似同一实体，全称与简称并存',
  },
  {
    id: 'e004',
    name: '华融证券',
    alias: ['华融证券股份'],
    coordinateSystem: 'WGS84',
    x: 1150,
    y: 900,
    floor: 2,
    photoUrl: 'https://example.com/photos/huarong-sec.jpg',
    shareRatio: 51,
    sourceFile: SOURCE_FILE,
    importTime: IMPORT_TIME,
    processTime: PROCESS_TIME,
    notes: '证券业务板块',
  },
  {
    id: 'e005',
    name: '华融信托',
    alias: ['华融国际信托'],
    coordinateSystem: 'CGCS2000',
    x: 3100,
    y: 2200,
    floor: 3,
    photoUrl: 'https://example.com/photos/huarong-trust.jpg',
    shareRatio: 70,
    sourceFile: SOURCE_FILE,
    importTime: IMPORT_TIME,
    processTime: PROCESS_TIME,
    notes: '信托业务板块',
  },
  {
    id: 'e006',
    name: '华融信托',
    alias: ['华融国际信托'],
    coordinateSystem: 'CGCS2000',
    x: 3120,
    y: 2180,
    floor: 5,
    photoUrl: 'https://example.com/photos/huarong-trust-2.jpg',
    shareRatio: 70,
    sourceFile: SOURCE_FILE,
    importTime: IMPORT_TIME,
    processTime: PROCESS_TIME,
    notes: '同一信托公司在不同楼层的记录，疑似重复',
  },
  {
    id: 'e007',
    name: '华融基金',
    alias: ['华融基金管理'],
    coordinateSystem: 'WGS84',
    x: 1250,
    y: 920,
    floor: 2,
    photoUrl: null,
    shareRatio: 45,
    sourceFile: SOURCE_FILE,
    importTime: IMPORT_TIME,
    processTime: PROCESS_TIME,
    notes: '基金管理业务，照片缺失',
  },
  {
    id: 'e008',
    name: '华融期货',
    alias: ['华融期货有限公司'],
    coordinateSystem: 'CGCS2000',
    x: 3050,
    y: 2280,
    floor: 3,
    photoUrl: 'https://example.com/photos/huarong-futures.jpg',
    shareRatio: 55,
    sourceFile: SOURCE_FILE,
    importTime: IMPORT_TIME,
    processTime: PROCESS_TIME,
    notes: '期货业务板块',
  },
  {
    id: 'e009',
    name: '华融租赁',
    alias: ['华融金融租赁'],
    coordinateSystem: 'CGCS2000',
    x: 5200,
    y: 4100,
    floor: 4,
    photoUrl: 'https://example.com/photos/huarong-lease.jpg',
    shareRatio: 60,
    sourceFile: SOURCE_FILE,
    importTime: IMPORT_TIME,
    processTime: PROCESS_TIME,
    notes: '金融租赁业务，坐标偏离严重',
  },
  {
    id: 'e010',
    name: '华融消费金融',
    alias: ['华融消金'],
    coordinateSystem: 'WGS84',
    x: 1190,
    y: 950,
    floor: 2,
    photoUrl: 'https://example.com/photos/huarong-cf.jpg',
    shareRatio: 40,
    sourceFile: SOURCE_FILE,
    importTime: IMPORT_TIME,
    processTime: PROCESS_TIME,
    notes: '消费金融业务',
  },
  {
    id: 'e011',
    name: '华融国际',
    alias: ['华融国际控股'],
    coordinateSystem: 'WGS84',
    x: 1210,
    y: 870,
    floor: 1,
    photoUrl: 'https://example.com/photos/huarong-intl.jpg',
    shareRatio: 80,
    sourceFile: SOURCE_FILE,
    importTime: IMPORT_TIME,
    processTime: PROCESS_TIME,
    notes: '海外业务控股平台',
  },
  {
    id: 'e012',
    name: '华融投资',
    alias: ['华融投资管理'],
    coordinateSystem: 'WGS84',
    x: 1230,
    y: 910,
    floor: 2,
    photoUrl: 'https://example.com/photos/huarong-inv.jpg',
    shareRatio: 35,
    sourceFile: SOURCE_FILE,
    importTime: IMPORT_TIME,
    processTime: PROCESS_TIME,
    notes: '投资管理业务',
  },
]

export const mockEquityLinks: EquityLink[] = [
  {
    id: 'l001',
    sourceId: 'e001',
    targetId: 'e002',
    ratio: 65,
    label: '持股65%',
  },
  {
    id: 'l002',
    sourceId: 'e001',
    targetId: 'e003',
    ratio: 65,
    label: '持股65%',
  },
  {
    id: 'l003',
    sourceId: 'e001',
    targetId: 'e004',
    ratio: 51,
    label: '持股51%',
  },
  {
    id: 'l004',
    sourceId: 'e001',
    targetId: 'e005',
    ratio: 70,
    label: '持股70%',
  },
  {
    id: 'l005',
    sourceId: 'e001',
    targetId: 'e007',
    ratio: 45,
    label: '持股45%',
  },
  {
    id: 'l006',
    sourceId: 'e001',
    targetId: 'e008',
    ratio: 55,
    label: '持股55%',
  },
  {
    id: 'l007',
    sourceId: 'e001',
    targetId: 'e009',
    ratio: 60,
    label: '持股60%',
  },
  {
    id: 'l008',
    sourceId: 'e011',
    targetId: 'e010',
    ratio: 40,
    label: '持股40%',
  },
  {
    id: 'l009',
    sourceId: 'e001',
    targetId: 'e011',
    ratio: 80,
    label: '持股80%',
  },
  {
    id: 'l010',
    sourceId: 'e001',
    targetId: 'e012',
    ratio: 35,
    label: '持股35%',
  },
]
