const fs = require('fs');
const lines = [];
lines.push("import { workflowDao } from '../dao/workflowDao';");
lines.push("import { redLineDao } from '../dao/redLineDao';");
lines.push("import { inspectorDao } from '../dao/inspectorDao';");
lines.push("import { shelterDao } from '../dao/shelterDao';");
lines.push("import { changeHistoryDao } from '../dao/changeHistoryDao';");
lines.push("import { capacityCheckDao } from '../dao/capacityCheckDao';");
lines.push("import { capacityCheckService } from './capacityCheckService';");
lines.push("import { WorkflowRecord, WorkflowStep, RedLineMap, GridInspectorReport, CapacityCheckResult } from '../types';");
lines.push("import { generateBatchNo, generateReportNo } from '../utils/common';");
lines.push('');
lines.push('const STEP_FLOW: Record<WorkflowStep, { previous: WorkflowStep | null; next: WorkflowStep | null }> = {');
lines.push("  redline_import: { previous: null, next: 'inspector_review' },");
lines.push("  inspector_review: { previous: 'redline_import', next: 'point_update' },");
lines.push("  point_update: { previous: 'inspector_review', next: null }");
lines.push('};');
lines.push('');
lines.push('const STEP_NAMES: Record<WorkflowStep, string> = {');
lines.push("  redline_import: '红线图导入',");
lines.push("  inspector_review: '网格员巡查表复核',");
lines.push("  point_update: '点位清单更新'");
lines.push('};');
lines.push('');
lines.push('const recordChange = (');
lines.push("  entityType: 'redline' | 'inspector_report' | 'capacity_check' | 'shelter' | 'conflict',");
lines.push('  entityId: string,');
lines.push('  shelterId: string,');
lines.push('  shelterName: string,');
lines.push("  changeType: 'create' | 'update' | 'reimport' | 'review' | 'recalc',");
lines.push('  fieldName: string,');
lines.push('  oldValue: string,');
lines.push('  newValue: string,');
lines.push('  operator: string,');
lines.push('  remark: string,');
lines.push('  affectedResultIds: string[] = []');
lines.push('): void => {');
lines.push('  changeHistoryDao.create({');
lines.push('    entityType,');
lines.push('    entityId,');
lines.push('    shelterId,');
lines.push('    shelterName,');
lines.push('    changeType,');
lines.push('    fieldName,');
lines.push('    oldValue,');
lines.push('    newValue,');
lines.push('    operator,');
lines.push('    remark,');
lines.push('    affectedResultIds');
lines.push('  });');
lines.push('};');
lines.push('');
lines.push('export const workflowService = {');
lines.push('  startWorkflow: (shelterId: string, operator: string): WorkflowRecord => {');
lines.push('    const existing = workflowDao.findLatestByShelterId(shelterId);');
lines.push("    if (existing && existing.stepStatus !== 'completed') {");
lines.push('      return existing;');
lines.push('    }');
lines.push('    return workflowDao.create({');
lines.push('      shelterId,');
lines.push("      currentStep: 'redline_import',");
lines.push("      stepStatus: 'pending',");
lines.push('      redLineMapId: null,');
lines.push('      inspectorReportId: null,');
lines.push('      previousStep: null,');
lines.push("      nextStep: 'inspector_review',");
lines.push('      operator,');
lines.push("      remark: ''");
lines.push('    });');
lines.push('  },');
lines.push('');
lines.push('  step1_importRedLine: (');
lines.push('    workflowId: string,');
lines.push('    shelterId: string,');
lines.push('    version: string,');
lines.push('    remarks: string,');
lines.push('    areaRange: string,');
lines.push('    effectiveDate: string,');
lines.push('    importOperator: string,');
lines.push('    options?: { isReimport?: boolean; reimportNote?: string; importBatchNo?: string }');
lines.push('  ): { workflow: WorkflowRecord; redLine: RedLineMap } => {');
lines.push('    const shelter = shelterDao.findById(shelterId);');
lines.push('    if (!shelter) {');
lines.push("      throw new Error('Shelter not found');");
lines.push('    }');
lines.push('    const existingLatest = redLineDao.findLatestByShelterId(shelterId);');
lines.push('    const isReimport = options?.isReimport || (existingLatest !== null);');
lines.push('    const importBatchNo = options?.importBatchNo || generateBatchNo();');
lines.push('    redLineDao.setOldToNotLatest(shelterId);');
lines.push('    const redLine = redLineDao.create({');
lines.push('      version,');
lines.push('      importBatchNo,');
lines.push('      shelterId,');
lines.push('      remarks,');
lines.push('      areaRange,');
lines.push('      effectiveDate,');
lines.push('      importOperator,');
lines.push('      isLatest: true,');
lines.push('      isReimport,');
lines.push("      reimportNote: options?.reimportNote || null,");
lines.push('      prevVersionId: existingLatest?.id || null');
lines.push('    });');
lines.push('    recordChange(');
lines.push("      'redline',");
lines.push('      redLine.id,');
lines.push('      shelterId,');
lines.push('      shelter.name,');
lines.push("      isReimport ? 'reimport' : 'create',");
lines.push("      '红线图',");
lines.push('      existingLatest ? `v${existingLatest.version}` : \'\',');
lines.push('      `v${version}`,'  );
lines.push('      importOperator,');
lines.push("      isReimport ? '重新导入红线图' : '首次导入红线图'");
lines.push('    );');
