const fs = require('fs');
const lines = [];
lines.push("import { workflowDao } from '../dao/workflowDao';");
lines.push("import { redLineDao } from '../dao/redLineDao';");
lines.push("import { inspectorDao } from '../dao/inspectorDao';");
lines.push("import { shelterDao } from '../dao/shelterDao';");
lines.push("import { changeHistoryDao } from '../dao/changeHistoryDao';");
lines.push("import { capacityCheckDao } from '../dao/capacityCheckDao';");
lines.push("import { capacityCheckService } from './capacityCheckService';");
lines.push("import { WorkflowRecord, WorkflowStep, RedLineMap, GridInspectorReport, CapacityCheckResult } from '../types';");
lines.push("import { generateBatchNo, generateReportNo } from '../utils/common';");
lines.push("");
lines.push("const STEP_FLOW: Record<WorkflowStep, { previous: WorkflowStep | null; next: WorkflowStep | null }> = {");
lines.push("  redline_import: { previous: null, next: 'inspector_review' },");
lines.push("  inspector_review: { previous: 'redline_import', next: 'point_update' },");
lines.push("  point_update: { previous: 'inspector_review', next: null }");
lines.push("};");
lines.push("");
lines.push("const STEP_NAMES: Record<WorkflowStep, string> = {");
lines.push("  redline_import: '红线图导入',");
lines.push("  inspector_review: '网格员巡查表复核',");
lines.push("  point_update: '点位清单更新'");
lines.push("};");
lines.push("");
lines.push("const recordChange = (");
lines.push("  entityType: 'redline' | 'inspector_report' | 'capacity_check' | 'shelter' | 'conflict',");
lines.push("  entityId: string,");
lines.push("  shelterId: string,");
lines.push("  shelterName: string,");
lines.push("  changeType: 'create' | 'update' | 'reimport' | 'review' | 'recalc',");
lines.push("  fieldName: string,");
lines.push("  oldValue: string,");
lines.push("  newValue: string,");
lines.push("  operator: string,");
lines.push("  remark: string,");
lines.push("  affectedResultIds: string[] = []");
lines.push("): void => {");
lines.push("  changeHistoryDao.create({");
lines.push("    entityType,");
lines.push("    entityId,");
lines.push("    shelterId,");
lines.push("    shelterName,");
lines.push("    changeType,");
lines.push("    fieldName,");
lines.push("    oldValue,");
lines.push("    newValue,");
lines.push("    operator,");
lines.push("    remark,");
lines.push("    affectedResultIds");
lines.push("  });");
lines.push("};");
lines.push("");
lines.push("export const workflowService = {");
lines.push("  startWorkflow: (shelterId: string, operator: string): WorkflowRecord => {");
lines.push("    const existing = workflowDao.findLatestByShelterId(shelterId);");
lines.push("    if (existing && existing.stepStatus !== 'completed') {");
lines.push("      return existing;");
lines.push("    }");
lines.push("    return workflowDao.create({");
lines.push("      shelterId,");
lines.push("      currentStep: 'redline_import',");
lines.push("      stepStatus: 'pending',");
lines.push("      redLineMapId: null,");
lines.push("      inspectorReportId: null,");
lines.push("      previousStep: null,");
lines.push("      nextStep: 'inspector_review',");
lines.push("      operator,");
lines.push("      remark: ''");
lines.push("    });");
lines.push("  },");
lines.push("");
lines.push("  step1_importRedLine: (");
lines.push("    workflowId: string,");
lines.push("    shelterId: string,");
lines.push("    version: string,");
lines.push("    remarks: string,");
lines.push("    areaRange: string,");
lines.push("    effectiveDate: string,");
lines.push("    importOperator: string,");
lines.push("    options?: { isReimport?: boolean; reimportNote?: string; importBatchNo?: string }");
lines.push("  ): { workflow: WorkflowRecord; redLine: RedLineMap } => {");
lines.push("    const shelter = shelterDao.findById(shelterId);");
lines.push("    if (!shelter) {");
lines.push("      throw new Error('Shelter not found');");
lines.push("    }");
lines.push("    const existingLatest = redLineDao.findLatestByShelterId(shelterId);");
lines.push("    const isReimport = options?.isReimport || (existingLatest !== null);");
lines.push("    const importBatchNo = options?.importBatchNo || generateBatchNo();");
lines.push("    redLineDao.setOldToNotLatest(shelterId);");
lines.push("    const redLine = redLineDao.create({");
lines.push("      version,");
lines.push("      importBatchNo,");
lines.push("      shelterId,");
lines.push("      remarks,");
lines.push("      areaRange,");
lines.push("      effectiveDate,");
lines.push("      importOperator,");
lines.push("      isLatest: true,");
lines.push("      isReimport,");
lines.push("      reimportNote: options?.reimportNote || null,");
lines.push("      prevVersionId: existingLatest?.id || null");
lines.push("    });");
lines.push("    recordChange(");
lines.push("      'redline',");
lines.push("      redLine.id,");
lines.push("      shelterId,");
lines.push("      shelter.name,");
lines.push("      isReimport ? 'reimport' : 'create',");
lines.push("      '红线图',");
lines.push("      existingLatest ? `v${existingLatest.version}` : '',");
lines.push("      `v${version}`,");
lines.push("      importOperator,");
lines.push("      isReimport ? '重新导入红线图' : '首次导入红线图'");
lines.push("    );");
lines.push("    const workflow = workflowDao.findById(workflowId);");
lines.push("    if (workflow) {");
lines.push("      workflowDao.updateStep(workflowId, {");
lines.push("        currentStep: 'redline_import',");
lines.push("        stepStatus: 'completed',");
lines.push("        previousStep: null,");
lines.push("        nextStep: 'inspector_review',");
lines.push("        redLineMapId: redLine.id,");
lines.push("        operator: importOperator,");
lines.push("        remark: '红线图导入完成'");
lines.push("      });");
lines.push("    }");
lines.push("    const updatedWorkflow = workflowDao.findById(workflowId) || workflow;");
lines.push("    return { workflow: updatedWorkflow!, redLine };");
lines.push("  },");
lines.push("");
lines.push("  reviewRedLine: (redLineId: string, reviewStatus: RedLineMap['reviewStatus'], reviewNote: string, reviewedBy: string): void => {");
lines.push("    const redLine = redLineDao.findById(redLineId);");
lines.push("    if (!redLine) {");
lines.push("      throw new Error('RedLine not found');");
lines.push("    }");
lines.push("    const shelter = shelterDao.findById(redLine.shelterId);");
lines.push("    const oldStatus = redLine.reviewStatus;");
lines.push("    redLineDao.updateReview(redLineId, reviewStatus, reviewNote, reviewedBy);");
lines.push("    if (shelter) {");
lines.push("      recordChange(");
lines.push("        'redline',");
lines.push("        redLineId,");
lines.push("        redLine.shelterId,");
lines.push("        shelter.name,");
lines.push("        'review',");
lines.push("        '审核状态',");
lines.push("        oldStatus,");
lines.push("        reviewStatus,");
lines.push("        reviewedBy,");
lines.push("        reviewNote");
lines.push("      );");
lines.push("    }");
lines.push("  },");
lines.push("");
lines.push("  updateRedLineRemarks: (redLineId: string, remarks: string, operator: string): void => {");
lines.push("    const redLine = redLineDao.findById(redLineId);");
lines.push("    if (!redLine) {");
lines.push("      throw new Error('RedLine not found');");
lines.push("    }");
lines.push("    const shelter = shelterDao.findById(redLine.shelterId);");
lines.push("    const oldRemarks = redLine.remarks;");
lines.push("    redLineDao.updateRemarks(redLineId, remarks, operator);");
lines.push("    if (shelter) {");
lines.push("      recordChange(");
lines.push("        'redline',");
lines.push("        redLineId,");
lines.push("        redLine.shelterId,");
lines.push("        shelter.name,");
lines.push("        'update',");
lines.push("        '红线图备注',");
lines.push("        oldRemarks,");
lines.push("        remarks,");
lines.push("        operator,");
lines.push("        '更新红线图备注'");
lines.push("      );");
lines.push("    }");
lines.push("  },");
lines.push("");
lines.push("  step2_reviewInspectorReport: (");
lines.push("    workflowId: string,");
lines.push("    shelterId: string,");
lines.push("    inspectorName: string,");
lines.push("    inspectionDate: string,");
lines.push("    actualCapacity: number,");
lines.push("    foundIssues: string,");
lines.push("    isTemporaryDetour: boolean,");
lines.push("    detourDescription: string,");
lines.push("    roadCondition: 'normal' | 'blocked' | 'detour',");
lines.push("    operator: string");
lines.push("  ): { workflow: WorkflowRecord; report: GridInspectorReport } => {");
lines.push("    const shelter = shelterDao.findById(shelterId);");
lines.push("    if (!shelter) {");
lines.push("      throw new Error('Shelter not found');");
lines.push("    }");
lines.push("    const reportNo = generateReportNo();");
lines.push("    const report = inspectorDao.create({");
lines.push("      reportNo,");
lines.push("      shelterId,");
lines.push("      inspectorName,");
lines.push("      inspectionDate,");
lines.push("      actualCapacity,");
lines.push("      foundIssues,");
lines.push("      isTemporaryDetour,");
lines.push("      detourDescription,");
lines.push("      roadCondition");
lines.push("    });");
lines.push("    recordChange(");
lines.push("      'inspector_report',");
lines.push("      report.id,");
lines.push("      shelterId,");
lines.push("      shelter.name,");
lines.push("      'create',");
lines.push("      '巡查表',");
lines.push("      '',");
lines.push("      reportNo,");
lines.push("      operator,");
lines.push("      '提交网格员巡查表'");
lines.push("    );");
lines.push("    const workflow = workflowDao.findById(workflowId);");
lines.push("    if (workflow) {");
lines.push("      if (isTemporaryDetour && shelter.status === 'pending_review') {");
lines.push("        workflowDao.updateStep(workflowId, {");
lines.push("          currentStep: 'inspector_review',");
lines.push("          stepStatus: 'suspended',");
lines.push("          previousStep: 'redline_import',");
lines.push("          nextStep: 'point_update',");
lines.push("          inspectorReportId: report.id,");
lines.push("          operator,");
lines.push("          remark: '存在临时改道，需居民审核确认'");
lines.push("        });");
lines.push("      } else {");
lines.push("        workflowDao.updateStep(workflowId, {");
lines.push("          currentStep: 'inspector_review',");
lines.push("          stepStatus: 'completed',");
lines.push("          previousStep: 'redline_import',");
lines.push("          nextStep: 'point_update',");
lines.push("          inspectorReportId: report.id,");
lines.push("          operator,");
lines.push("          remark: '巡查表复核完成'");
lines.push("        });");
lines.push("      }");
lines.push("    }");
lines.push("    const updatedWorkflow = workflowDao.findById(workflowId) || workflow;");
lines.push("    return { workflow: updatedWorkflow!, report };");
lines.push("  },");
lines.push("");
lines.push("  resumeAfterResidentReview: (workflowId: string, shelterId: string, operator: string): WorkflowRecord => {");
lines.push("    const workflow = workflowDao.findById(workflowId);");
lines.push("    if (!workflow) {");
lines.push("      throw new Error('Workflow not found');");
lines.push("    }");
lines.push("    workflowDao.updateStep(workflowId, {");
lines.push("      currentStep: 'inspector_review',");
lines.push("      stepStatus: 'completed',");
lines.push("      previousStep: 'redline_import',");
lines.push("      nextStep: 'point_update',");
lines.push("      operator,");
lines.push("      remark: '居民审核通过，继续流程'");
lines.push("    });");
lines.push("    const shelter = shelterDao.findById(shelterId);");
lines.push("    if (shelter) {");
lines.push("      recordChange(");
lines.push("        'shelter',");
lines.push("        shelterId,");
lines.push("        shelterId,");
lines.push("        shelter.name,");
lines.push("        'update',");
lines.push("        '流程状态',");
lines.push("        'suspended',");
lines.push("        'completed',");
lines.push("        operator,");
lines.push("        '居民审核通过，恢复流程'");
lines.push("      );");
lines.push("    }");
lines.push("    const updated = workflowDao.findById(workflowId);");
lines.push("    return updated!;");
lines.push("  },");
lines.push("");
lines.push("  step3_updatePointList: (workflowId: string, shelterId: string, operator: string): { workflow: WorkflowRecord; checkResult: CapacityCheckResult | null } => {");
lines.push("    const checkResult = capacityCheckService.recalculateAfterSupplement(shelterId, operator);");
lines.push("    const workflow = workflowDao.findById(workflowId);");
lines.push("    if (workflow) {");
lines.push("      workflowDao.updateStep(workflowId, {");
lines.push("        currentStep: 'point_update',");
lines.push("        stepStatus: 'completed',");
lines.push("        previousStep: 'inspector_review',");
lines.push("        nextStep: null,");
lines.push("        operator,");
lines.push("        remark: '点位清单更新完成，容量已重新核算'");
lines.push("      });");
lines.push("    }");
lines.push("    const shelter = shelterDao.findById(shelterId);");
lines.push("    if (shelter && checkResult) {");
lines.push("      recordChange(");
lines.push("        'capacity_check',");
lines.push("        checkResult.id,");
lines.push("        shelterId,");
lines.push("        shelter.name,");
lines.push("        'recalc',");
lines.push("        '核算容量',");
lines.push("        shelter.designedCapacity.toString(),");
lines.push("        checkResult.checkedCapacity.toString(),");
lines.push("        operator,");
lines.push("        '补充资料后重新核算容量',");
lines.push("        [checkResult.id]");
lines.push("      );");
lines.push("    }");
lines.push("    const updatedWorkflow = workflowDao.findById(workflowId) || workflow;");
lines.push("    return { workflow: updatedWorkflow!, checkResult };");
lines.push("  },");
lines.push("");
lines.push("  getWorkflowForShelter: (shelterId: string): WorkflowRecord | null => {");
lines.push("    return workflowDao.findLatestByShelterId(shelterId);");
lines.push("  },");
lines.push("");
lines.push("  getAllWorkflowsForShelter: (shelterId: string): WorkflowRecord[] => {");
lines.push("    return workflowDao.findByShelterId(shelterId);");
lines.push("  },");
lines.push("");
lines.push("  getAllWorkflows: (): WorkflowRecord[] => {");
lines.push("    return workflowDao.findAll();");
lines.push("  },");
lines.push("");
lines.push("  getWorkflowsByStep: (step: WorkflowStep): WorkflowRecord[] => {");
lines.push("    return workflowDao.findByStep(step);");
lines.push("  },");
lines.push("");
lines.push("  getStepName: (step: WorkflowStep): string => {");
lines.push("    return STEP_NAMES[step];");
lines.push("  },");
lines.push("");
lines.push("  getStepNames: (): Record<WorkflowStep, string> => {");
lines.push("    return { ...STEP_NAMES };");
lines.push("  }");
lines.push("};");
fs.writeFileSync('/Users/lzy/pro/solo/workspaces/zy72477/src/services/workflowService.ts', lines.join('\n'), 'utf-8');
console.log('Done, lines:', lines.length);
