/** @type {import('tailwindcss').Config} */

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
      padding: '1.5rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          50: '#f0f4ff',
          100: '#d9e2ff',
          200: '#b8c7ff',
          300: '#8aa2ff',
          400: '#5b78ff',
          500: '#0A2463',
          600: '#081d4f',
          700: '#06163b',
          800: '#041027',
          900: '#020a13',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
          50: '#fdf8f3',
          100: '#f9edd9',
          200: '#f2d9b3',
          300: '#e8c085',
          400: '#D4A574',
          500: '#c48d56',
          600: '#b07644',
          700: '#925d39',
          800: '#764c33',
          900: '#61402d',
        },
        success: {
          DEFAULT: '#2D6A4F',
          foreground: '#ffffff',
          50: '#f0f7f4',
          100: '#d9ece2',
          200: '#b5d9c6',
          300: '#84bea2',
          400: '#529d7c',
          500: '#2D6A4F',
          600: '#255a41',
          700: '#1f4936',
          800: '#1a3b2c',
          900: '#153124',
        },
        warning: {
          DEFAULT: '#E07A5F',
          foreground: '#ffffff',
          50: '#fdf4f1',
          100: '#fce4dc',
          200: '#f9c9b9',
          300: '#f4a68d',
          400: '#E07A5F',
          500: '#d65f3f',
          600: '#c04a2c',
          700: '#9f3c25',
          800: '#833424',
          900: '#6c2e22',
        },
        accent: {
          DEFAULT: '#9F86C0',
          foreground: '#ffffff',
          50: '#f7f4fb',
          100: '#eee7f6',
          200: '#ddd0ed',
          300: '#c5b0df',
          400: '#9F86C0',
          500: '#8a6cb0',
          600: '#77569c',
          700: '#624480',
          800: '#523a6a',
          900: '#453257',
        },
        error: {
          DEFAULT: '#DC2626',
          foreground: '#ffffff',
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#DC2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      fontFamily: {
        serif: ['"Noto Serif SC"', 'serif'],
        sans: ['"Noto Sans SC"', 'sans-serif'],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in': {
          from: { opacity: '0', transform: 'translateX(-10px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'bounce-in': {
          '0%': { opacity: '0', transform: 'translateY(-10px) scale(0.95)' },
          '50%': { transform: 'translateY(2px) scale(1.02)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 0.4s ease-out forwards',
        'slide-in': 'slide-in 0.3s ease-out forwards',
        'bounce-in': 'bounce-in 0.4s ease-out forwards',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
      },
      transitionTimingFunction: {
        'elegant': 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
};
