#!/usr/bin/env python3
import os

BASE = os.path.dirname(os.path.abspath(__file__))

def build():
    lines = []
    
    # Imports
    lines.append("import hashlib")
    lines.append("import os")
    lines.append("import uuid")
    lines.append("from datetime import datetime")
    lines.append("from enum import Enum")
    lines.append("from typing import Optional, List, Dict, Any")
    lines.append("from io import BytesIO")
    lines.append("")
    lines.append("from fastapi import FastAPI, Depends, HTTPException, Query, UploadFile, File")
    lines.append("from fastapi.middleware.cors import CORSMiddleware")
    lines.append("from fastapi.responses import StreamingResponse")
    lines.append("from pydantic import BaseModel, Field")
    lines.append("from sqlalchemy import create_engine, Column, Integer, String, DateTime, Text, ForeignKey")
    lines.append("from sqlalchemy.ext.declarative import declarative_base")
    lines.append("from sqlalchemy.orm import sessionmaker, Session, relationship")
    lines.append("from sqlalchemy.sql import func")
    lines.append("import pandas as pd")
    lines.append("")
    
    # Config
    lines.append("UPLOAD_DIR = \"uploads\"")
    lines.append("EXPORT_DIR = \"exports\"")
    lines.append("os.makedirs(UPLOAD_DIR, exist_ok=True)")
    lines.append("os.makedirs(EXPORT_DIR, exist_ok=True)")
    lines.append("")
    lines.append("SQLALCHEMY_DATABASE_URL = \"sqlite:///./tree_hazards.db\"")
    lines.append("engine = create_engine(SQLALCHEMY_DATABASE_URL, connect_args={\"check_same_thread\": False})")
    lines.append("SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)")
    lines.append("Base = declarative_base()")
    lines.append("")
    
    # Enums
    lines.append("class HazardLevel(str, Enum):")
    lines.append("    GENERAL = \"general\"")
    lines.append("    SERIOUS = \"serious\"")
    lines.append("    SEVERE = \"severe\"")
    lines.append("    EMERGENCY = \"emergency\"")
    lines.append("")
    lines.append("class HazardStatus(str, Enum):")
    lines.append("    PENDING_REVIEW = \"pending_review\"")
    lines.append("    BLOCKED = \"blocked\"")
    lines.append("    APPROVED = \"approved\"")
    lines.append("    IN_PROGRESS = \"in_progress\"")
    lines.append("    PENDING_RECHECK = \"pending_recheck\"")
    lines.append("    COMPLETED = \"completed\"")
    lines.append("    CLOSED = \"closed\"")
    lines.append("")
    lines.append("class OperationType(str, Enum):")
    lines.append("    REGISTER = \"register\"")
    lines.append("    BLOCK = \"block\"")
    lines.append("    APPROVE = \"approve\"")
    lines.append("    ASSIGN = \"assign\"")
    lines.append("    RECHECK_SUBMIT = \"recheck_submit\"")
    lines.append("    COMPLETE = \"complete\"")
    lines.append("    CLOSE = \"close\"")
    lines.append("    MODIFY = \"modify\"")
    lines.append("    WITHDRAW = \"withdraw\"")
    lines.append("    RESUBMIT = \"resubmit\"")
    lines.append("")
    
    # DB Models
    lines.append("class HazardDB(Base):")
    lines.append("    __tablename__ = \"hazards\"")
    lines.append("    id = Column(Integer, primary_key=True, index=True)")
    lines.append("    tree_number = Column(String(50), index=True, nullable=False)")
    lines.append("    road_location = Column(String(200), nullable=False)")
    lines.append("    location_hash = Column(String(64), index=True)")
    lines.append("    photo_path = Column(Text)")
    lines.append("    hazard_level = Column(String(20), nullable=False)")
    lines.append("    disposal_team = Column(String(100))")
    lines.append("    status = Column(String(30), default=HazardStatus.PENDING_REVIEW.value)")
    lines.append("    recheck_conclusion = Column(Text)")
    lines.append("    batch_id = Column(String(64), index=True)")
    lines.append("    description = Column(Text)")
    lines.append("    created_at = Column(DateTime(timezone=True), server_default=func.now())")
    lines.append("    updated_at = Column(DateTime(timezone=True), onupdate=func.now())")
    lines.append("    is_duplicate = Column(Integer, default=0)")
    lines.append("    original_hazard_id = Column(Integer, ForeignKey(\"hazards.id\"))")
    lines.append("    level_modified_count = Column(Integer, default=0)")
    lines.append("    operations = relationship(\"OperationLogDB\", back_populates=\"hazard\")")
    lines.append("    original = relationship(\"HazardDB\", remote_side=[id])")
    lines.append("")
    lines.append("class OperationLogDB(Base):")
    lines.append("    __tablename__ = \"operation_logs\"")
    lines.append("    id = Column(Integer, primary_key=True, index=True)")
    lines.append("    hazard_id = Column(Integer, ForeignKey(\"hazards.id\"))")
    lines.append("    operation_type = Column(String(30), nullable=False)")
    lines.append("    operator = Column(String(100))")
    lines.append("    remark = Column(Text)")
    lines.append("    old_status = Column(String(30))")
    lines.append("    new_status = Column(String(30))")
    lines.append("    old_level = Column(String(20))")
    lines.append("    new_level = Column(String(20))")
    lines.append("    created_at = Column(DateTime(timezone=True), server_default=func.now())")
    lines.append("    hazard = relationship(\"HazardDB\", back_populates=\"operations\")")
    lines.append("")
    lines.append("Base.metadata.create_all(bind=engine)")
    lines.append("")
    
    # Utility functions
    lines.append("def get_db():")
    lines.append("    db = SessionLocal()")
    lines.append("    try:")
    lines.append("        yield db")
    lines.append("    finally:")
    lines.append("        db.close()")
    lines.append("")
    lines.append("def calc_location_hash(tree_no, road_loc):")
    lines.append("    return hashlib.md5(f\"{tree_no}|{road_loc}\".encode()).hexdigest()")
    lines.append("")
    lines.append("def log_operation(db, h_id, op_type, operator=None, remark=None, old_status=None, new_status=None, old_level=None, new_level=None):")
    lines.append("    log = OperationLogDB(hazard_id=h_id, operation_type=op_type.value if hasattr(op_type, 'value') else op_type, operator=operator, remark=remark, old_status=old_status, new_status=new_status, old_level=old_level, new_level=new_level)")
    lines.append("    db.add(log)")
    lines.append("    db.commit()")
    lines.append("")
    
    # Status transitions
    lines.append("STATUS_TRANSITIONS = {")
    lines.append("    HazardStatus.PENDING_REVIEW.value: [HazardStatus.BLOCKED.value, HazardStatus.APPROVED.value, HazardStatus.CLOSED.value],")
    lines.append("    HazardStatus.BLOCKED.value: [HazardStatus.PENDING_REVIEW.value, HazardStatus.CLOSED.value],")
    lines.append("    HazardStatus.APPROVED.value: [HazardStatus.IN_PROGRESS.value, HazardStatus.PENDING_REVIEW.value, HazardStatus.CLOSED.value],")
    lines.append("    HazardStatus.IN_PROGRESS.value: [HazardStatus.PENDING_RECHECK.value, HazardStatus.PENDING_REVIEW.value, HazardStatus.COMPLETED.value, HazardStatus.CLOSED.value],")
    lines.append("    HazardStatus.PENDING_RECHECK.value: [HazardStatus.COMPLETED.value, HazardStatus.IN_PROGRESS.value, HazardStatus.CLOSED.value],")
    lines.append("    HazardStatus.COMPLETED.value: [HazardStatus.PENDING_REVIEW.value, HazardStatus.CLOSED.value],")
    lines.append("    HazardStatus.CLOSED.value: [HazardStatus.PENDING_REVIEW.value],")
    lines.append("}")
    lines.append("")
    lines.append("def validate_status_transition(old, new):")
    lines.append("    return new in STATUS_TRANSITIONS.get(old, [])")
    lines.append("")
    lines.append("def can_close(hazard):")
    lines.append("    if hazard.hazard_level == HazardLevel.EMERGENCY.value:")
    lines.append("        if not hazard.recheck_conclusion:")
    lines.append("            return False, \"封路等级隐患必须有复查结论才能关闭\"")
    lines.append("    if hazard.status in [HazardStatus.IN_PROGRESS.value, HazardStatus.PENDING_RECHECK.value]:")
    lines.append("        if not hazard.recheck_conclusion:")
    lines.append("            return False, \"处置中或待复查的隐患必须先提交复查结论\"")
    lines.append("    return True, \"\"")
    lines.append("")
    
    # Pydantic models
    lines.append("class HazardBase(BaseModel):")
    lines.append("    tree_number: str")
    lines.append("    road_location: str")
    lines.append("    photo_path: Optional[str] = None")
    lines.append("    hazard_level: HazardLevel")
    lines.append("    disposal_team: Optional[str] = None")
    lines.append("    batch_id: Optional[str] = None")
    lines.append("    description: Optional[str] = None")
    lines.append("")
    lines.append("class HazardCreate(HazardBase):")
    lines.append("    pass")
    lines.append("")
    lines.append("class HazardUpdate(BaseModel):")
    lines.append("    hazard_level: Optional[HazardLevel] = None")
    lines.append("    disposal_team: Optional[str] = None")
    lines.append("    description: Optional[str] = None")
    lines.append("    recheck_conclusion: Optional[str] = None")
    lines.append("")
    lines.append("class HazardResponse(HazardBase):")
    lines.append("    id: int")
    lines.append("    status: HazardStatus")
    lines.append("    recheck_conclusion: Optional[str] = None")
    lines.append("    location_hash: Optional[str] = None")
    lines.append("    created_at: datetime")
    lines.append("    updated_at: Optional[datetime] = None")
    lines.append("    is_duplicate: int")
    lines.append("    original_hazard_id: Optional[int] = None")
    lines.append("    level_modified_count: int")
    lines.append("    class Config:")
    lines.append("        from_attributes = True")
    lines.append("")
    lines.append("class OperationLogResponse(BaseModel):")
    lines.append("    id: int")
    lines.append("    hazard_id: int")
    lines.append("    operation_type: OperationType")
    lines.append("    operator: Optional[str] = None")
    lines.append("    remark: Optional[str] = None")
    lines.append("    old_status: Optional[HazardStatus] = None")
    lines.append("    new_status: Optional[HazardStatus] = None")
    lines.append("    old_level: Optional[HazardLevel] = None")
    lines.append("    new_level: Optional[HazardLevel] = None")
    lines.append("    created_at: datetime")
    lines.append("    class Config:")
    lines.append("        from_attributes = True")
    lines.append("")
    lines.append("class StatusChangeRequest(BaseModel):")
    lines.append("    operator: Optional[str] = None")
    lines.append("    remark: Optional[str] = None")
    lines.append("")
    lines.append("class RecheckRequest(BaseModel):")
    lines.append("    conclusion: str")
    lines.append("    operator: Optional[str] = None")
    lines.append("    passed: bool = True")
    lines.append("")
    
    # App init
    lines.append("app = FastAPI(title=\"城市树木隐患 API\", version=\"1.0.0\")")
    lines.append("app.add_middleware(CORSMiddleware, allow_origins=[\"*\"], allow_credentials=True, allow_methods=[\"*\"], allow_headers=[\"*\"])")
    lines.append("")
    
    # Write file
    path = os.path.join(BASE, 'main.py')
    with open(path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"Written {len(lines)} lines to main.py")

if __name__ == '__main__':
    build()
