import type { SamplePackage } from "@/types"

export const SAMPLE_PACKAGE: SamplePackage = {
  nodes: [
    { id: "u1", name: "张明", projectLabels: ["p-alpha", "p-beta"], sourceType: "raw" },
    { id: "u2", name: "李华", projectLabels: ["p-alpha"], sourceType: "raw" },
    { id: "u3", name: "王芳", projectLabels: ["p-alpha"], sourceType: "raw" },
    { id: "u4", name: "赵刚", projectLabels: ["p-beta"], sourceType: "raw" },
    { id: "u5", name: "陈静", projectLabels: ["p-beta"], sourceType: "raw" },
    { id: "u6", name: "刘洋", projectLabels: ["p-gamma"], sourceType: "raw" },
    { id: "u7", name: "孙丽", projectLabels: ["p-gamma"], sourceType: "raw" },
    { id: "u8", name: "周杰", projectLabels: ["p-gamma"], sourceType: "raw" },
    { id: "u9", name: "吴强", projectLabels: ["p-delta"], sourceType: "raw" },
    { id: "u10", name: "郑慧", projectLabels: ["p-delta"], sourceType: "raw" },
    { id: "u11", name: "黄磊", projectLabels: [], sourceType: "raw" },
    { id: "u12", name: "林娜", projectLabels: [], sourceType: "raw" },
    { id: "u13", name: "何伟", projectLabels: ["p-epsilon"], sourceType: "raw" },
    { id: "u14", name: "马琳", projectLabels: ["p-epsilon"], sourceType: "raw" },
    { id: "u15", name: "罗峰", projectLabels: ["p-epsilon"], sourceType: "raw" },
    { id: "u16", name: "谢芸", projectLabels: [], sourceType: "raw" },
    { id: "u17", name: "韩冰", projectLabels: ["p-zeta"], sourceType: "raw" },
    { id: "u18", name: "唐磊", projectLabels: ["p-zeta"], sourceType: "raw" },
    { id: "u19", name: "冯雪", projectLabels: ["p-zeta", "p-alpha"], sourceType: "raw" },
    { id: "u20", name: "曹宇", projectLabels: [], sourceType: "raw" },
  ],
  edges: [
    { id: "e1", source: "u1", target: "u2", weight: 0.9, sourceType: "raw" },
    { id: "e2", source: "u1", target: "u3", weight: 0.85, sourceType: "raw" },
    { id: "e3", source: "u2", target: "u3", weight: 0.8, sourceType: "raw" },
    { id: "e4", source: "u1", target: "u4", weight: 0.7, sourceType: "raw" },
    { id: "e5", source: "u4", target: "u5", weight: 0.75, sourceType: "raw" },
    { id: "e6", source: "u1", target: "u5", weight: 0.65, sourceType: "raw" },
    { id: "e7", source: "u6", target: "u7", weight: 0.9, sourceType: "raw" },
    { id: "e8", source: "u7", target: "u8", weight: 0.85, sourceType: "raw" },
    { id: "e9", source: "u6", target: "u8", weight: 0.8, sourceType: "raw" },
    { id: "e10", source: "u9", target: "u10", weight: 0.6, sourceType: "raw" },
    { id: "e11", source: "u11", target: "u12", weight: 0.5, sourceType: "raw" },
    { id: "e12", source: "u13", target: "u14", weight: 0.9, sourceType: "raw" },
    { id: "e13", source: "u14", target: "u15", weight: 0.85, sourceType: "raw" },
    { id: "e14", source: "u13", target: "u15", weight: 0.8, sourceType: "raw" },
    { id: "e15", source: "u17", target: "u18", weight: 0.7, sourceType: "raw" },
    { id: "e16", source: "u18", target: "u19", weight: 0.75, sourceType: "raw" },
    { id: "e17", source: "u17", target: "u19", weight: 0.8, sourceType: "raw" },
    { id: "e18", source: "u1", target: "u19", weight: 0.6, sourceType: "raw" },
    { id: "e19", source: "u9", target: "u6", weight: 0.4, sourceType: "raw" },
    { id: "e20", source: "u12", target: "u9", weight: 0.3, sourceType: "raw" },
  ],
  projectLabels: {
    "p-alpha": ["u1", "u2", "u3", "u19"],
    "p-beta": ["u1", "u4", "u5"],
    "p-gamma": ["u6", "u7", "u8"],
    "p-delta": ["u9", "u10"],
    "p-epsilon": ["u13", "u14", "u15"],
    "p-zeta": ["u17", "u18", "u19"],
  },
  blacklist: [
    { nodeA: "u11", nodeB: "u12", reason: "历史冲突记录" },
  ],
  capacityConfig: { minSize: 3, maxSize: 8 },
}
