const ORDER_STATES = {
  CREATED: 'CREATED',
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PAYMENT_SUCCEEDED: 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  INVENTORY_LOCKED: 'INVENTORY_LOCKED',
  INVENTORY_FAILED: 'INVENTORY_FAILED',
  SHIPPING_PENDING: 'SHIPPING_PENDING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCEL_PENDING: 'CANCEL_PENDING',
  CANCELLED: 'CANCELLED',
  CANCEL_REJECTED: 'CANCEL_REJECTED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
  REFUND_FAILED: 'REFUND_FAILED',
  COMPENSATION_IN_PROGRESS: 'COMPENSATION_IN_PROGRESS',
  COMPENSATED: 'COMPENSATED'
};

const EVENT_TYPES = {
  ORDER_CREATED: 'ORDER_CREATED',
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_SUCCEEDED: 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  INVENTORY_LOCKED: 'INVENTORY_LOCKED',
  INVENTORY_FAILED: 'INVENTORY_FAILED',
  SHIPPING_INITIATED: 'SHIPPING_INITIATED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCEL_REQUESTED: 'CANCEL_REQUESTED',
  CANCEL_APPROVED: 'CANCEL_APPROVED',
  CANCEL_REJECTED: 'CANCEL_REJECTED',
  REFUND_INITIATED: 'REFUND_INITIATED',
  REFUND_SUCCEEDED: 'REFUND_SUCCEEDED',
  REFUND_FAILED: 'REFUND_FAILED',
  COMPENSATION_INVENTORY_RELEASED: 'COMPENSATION_INVENTORY_RELEASED',
  COMPENSATION_PAYMENT_REFUNDED: 'COMPENSATION_PAYMENT_REFUNDED',
  COMPENSATION_EVENT: 'COMPENSATION_EVENT'
};

const STATE_TRANSITIONS = {
  [ORDER_STATES.CREATED]: {
    allowedEvents: [EVENT_TYPES.PAYMENT_INITIATED, EVENT_TYPES.CANCEL_REQUESTED],
    descriptions: {
      [EVENT_TYPES.PAYMENT_INITIATED]: '订单创建成功，等待用户支付',
      [EVENT_TYPES.CANCEL_REQUESTED]: '用户发起取消订单'
    }
  },
  [ORDER_STATES.PENDING_PAYMENT]: {
    allowedEvents: [EVENT_TYPES.PAYMENT_SUCCEEDED, EVENT_TYPES.PAYMENT_FAILED, EVENT_TYPES.CANCEL_REQUESTED],
    descriptions: {
      [EVENT_TYPES.PAYMENT_SUCCEEDED]: '支付成功，准备锁定库存',
      [EVENT_TYPES.PAYMENT_FAILED]: '支付失败，订单待处理',
      [EVENT_TYPES.CANCEL_REQUESTED]: '用户在支付过程中发起取消'
    }
  },
  [ORDER_STATES.PAYMENT_SUCCEEDED]: {
    allowedEvents: [EVENT_TYPES.INVENTORY_LOCKED, EVENT_TYPES.INVENTORY_FAILED, EVENT_TYPES.CANCEL_REQUESTED],
    descriptions: {
      [EVENT_TYPES.INVENTORY_LOCKED]: '库存锁定成功，准备发货',
      [EVENT_TYPES.INVENTORY_FAILED]: '库存锁定失败，需要补偿',
      [EVENT_TYPES.CANCEL_REQUESTED]: '用户在支付成功后发起取消'
    }
  },
  [ORDER_STATES.PAYMENT_FAILED]: {
    allowedEvents: [EVENT_TYPES.PAYMENT_INITIATED, EVENT_TYPES.CANCEL_REQUESTED],
    descriptions: {
      [EVENT_TYPES.PAYMENT_INITIATED]: '用户重新发起支付',
      [EVENT_TYPES.CANCEL_REQUESTED]: '用户取消订单'
    }
  },
  [ORDER_STATES.INVENTORY_LOCKED]: {
    allowedEvents: [EVENT_TYPES.SHIPPING_INITIATED, EVENT_TYPES.CANCEL_REQUESTED],
    descriptions: {
      [EVENT_TYPES.SHIPPING_INITIATED]: '开始发货流程',
      [EVENT_TYPES.CANCEL_REQUESTED]: '用户发起取消订单'
    }
  },
  [ORDER_STATES.INVENTORY_FAILED]: {
    allowedEvents: [EVENT_TYPES.COMPENSATION_PAYMENT_REFUNDED, EVENT_TYPES.CANCEL_REQUESTED],
    descriptions: {
      [EVENT_TYPES.COMPENSATION_PAYMENT_REFUNDED]: '库存锁定失败，补偿退款',
      [EVENT_TYPES.CANCEL_REQUESTED]: '用户发起取消'
    }
  },
  [ORDER_STATES.SHIPPING_PENDING]: {
    allowedEvents: [EVENT_TYPES.SHIPPED, EVENT_TYPES.CANCEL_REQUESTED],
    descriptions: {
      [EVENT_TYPES.SHIPPED]: '商品已发货',
      [EVENT_TYPES.CANCEL_REQUESTED]: '发货前用户发起取消'
    }
  },
  [ORDER_STATES.SHIPPED]: {
    allowedEvents: [EVENT_TYPES.DELIVERED, EVENT_TYPES.REFUND_INITIATED],
    descriptions: {
      [EVENT_TYPES.DELIVERED]: '商品已签收',
      [EVENT_TYPES.REFUND_INITIATED]: '发货后申请退款'
    }
  },
  [ORDER_STATES.DELIVERED]: {
    allowedEvents: [EVENT_TYPES.REFUND_INITIATED],
    descriptions: {
      [EVENT_TYPES.REFUND_INITIATED]: '签收后申请售后退款'
    }
  },
  [ORDER_STATES.CANCEL_PENDING]: {
    allowedEvents: [EVENT_TYPES.CANCEL_APPROVED, EVENT_TYPES.CANCEL_REJECTED],
    descriptions: {
      [EVENT_TYPES.CANCEL_APPROVED]: '取消申请已批准',
      [EVENT_TYPES.CANCEL_REJECTED]: '取消申请被拒绝'
    }
  },
  [ORDER_STATES.CANCELLED]: {
    allowedEvents: [],
    descriptions: {}
  },
  [ORDER_STATES.CANCEL_REJECTED]: {
    allowedEvents: [EVENT_TYPES.CANCEL_REQUESTED, EVENT_TYPES.SHIPPING_INITIATED],
    descriptions: {
      [EVENT_TYPES.CANCEL_REQUESTED]: '用户再次发起取消',
      [EVENT_TYPES.SHIPPING_INITIATED]: '继续发货流程'
    }
  },
  [ORDER_STATES.REFUND_PENDING]: {
    allowedEvents: [EVENT_TYPES.REFUND_SUCCEEDED, EVENT_TYPES.REFUND_FAILED],
    descriptions: {
      [EVENT_TYPES.REFUND_SUCCEEDED]: '退款成功',
      [EVENT_TYPES.REFUND_FAILED]: '退款失败'
    }
  },
  [ORDER_STATES.REFUNDED]: {
    allowedEvents: [],
    descriptions: {}
  },
  [ORDER_STATES.REFUND_FAILED]: {
    allowedEvents: [EVENT_TYPES.REFUND_INITIATED],
    descriptions: {
      [EVENT_TYPES.REFUND_INITIATED]: '重新发起退款'
    }
  },
  [ORDER_STATES.COMPENSATION_IN_PROGRESS]: {
    allowedEvents: [EVENT_TYPES.COMPENSATION_INVENTORY_RELEASED, EVENT_TYPES.COMPENSATION_PAYMENT_REFUNDED, EVENT_TYPES.COMPENSATION_EVENT],
    descriptions: {
      [EVENT_TYPES.COMPENSATION_INVENTORY_RELEASED]: '释放已锁定的库存',
      [EVENT_TYPES.COMPENSATION_PAYMENT_REFUNDED]: '退还已支付的款项',
      [EVENT_TYPES.COMPENSATION_EVENT]: '执行补偿操作'
    }
  },
  [ORDER_STATES.COMPENSATED]: {
    allowedEvents: [],
    descriptions: {}
  }
};

const EVENT_TO_STATE_MAPPING = {
  [EVENT_TYPES.ORDER_CREATED]: ORDER_STATES.CREATED,
  [EVENT_TYPES.PAYMENT_INITIATED]: ORDER_STATES.PENDING_PAYMENT,
  [EVENT_TYPES.PAYMENT_SUCCEEDED]: ORDER_STATES.PAYMENT_SUCCEEDED,
  [EVENT_TYPES.PAYMENT_FAILED]: ORDER_STATES.PAYMENT_FAILED,
  [EVENT_TYPES.INVENTORY_LOCKED]: ORDER_STATES.INVENTORY_LOCKED,
  [EVENT_TYPES.INVENTORY_FAILED]: ORDER_STATES.INVENTORY_FAILED,
  [EVENT_TYPES.SHIPPING_INITIATED]: ORDER_STATES.SHIPPING_PENDING,
  [EVENT_TYPES.SHIPPED]: ORDER_STATES.SHIPPED,
  [EVENT_TYPES.DELIVERED]: ORDER_STATES.DELIVERED,
  [EVENT_TYPES.CANCEL_REQUESTED]: ORDER_STATES.CANCEL_PENDING,
  [EVENT_TYPES.CANCEL_APPROVED]: ORDER_STATES.CANCELLED,
  [EVENT_TYPES.CANCEL_REJECTED]: ORDER_STATES.CANCEL_REJECTED,
  [EVENT_TYPES.REFUND_INITIATED]: ORDER_STATES.REFUND_PENDING,
  [EVENT_TYPES.REFUND_SUCCEEDED]: ORDER_STATES.REFUNDED,
  [EVENT_TYPES.REFUND_FAILED]: ORDER_STATES.REFUND_FAILED,
  [EVENT_TYPES.COMPENSATION_INVENTORY_RELEASED]: ORDER_STATES.COMPENSATED,
  [EVENT_TYPES.COMPENSATION_PAYMENT_REFUNDED]: ORDER_STATES.COMPENSATED,
  [EVENT_TYPES.COMPENSATION_EVENT]: ORDER_STATES.COMPENSATED
};

const EVENT_DESCRIPTIONS = {
  [EVENT_TYPES.ORDER_CREATED]: '订单创建',
  [EVENT_TYPES.PAYMENT_INITIATED]: '发起支付',
  [EVENT_TYPES.PAYMENT_SUCCEEDED]: '支付成功',
  [EVENT_TYPES.PAYMENT_FAILED]: '支付失败',
  [EVENT_TYPES.INVENTORY_LOCKED]: '库存锁定',
  [EVENT_TYPES.INVENTORY_FAILED]: '库存锁定失败',
  [EVENT_TYPES.SHIPPING_INITIATED]: '发起发货',
  [EVENT_TYPES.SHIPPED]: '已发货',
  [EVENT_TYPES.DELIVERED]: '已签收',
  [EVENT_TYPES.CANCEL_REQUESTED]: '申请取消',
  [EVENT_TYPES.CANCEL_APPROVED]: '取消通过',
  [EVENT_TYPES.CANCEL_REJECTED]: '取消被拒',
  [EVENT_TYPES.REFUND_INITIATED]: '发起退款',
  [EVENT_TYPES.REFUND_SUCCEEDED]: '退款成功',
  [EVENT_TYPES.REFUND_FAILED]: '退款失败',
  [EVENT_TYPES.COMPENSATION_INVENTORY_RELEASED]: '补偿：释放库存',
  [EVENT_TYPES.COMPENSATION_PAYMENT_REFUNDED]: '补偿：退款',
  [EVENT_TYPES.COMPENSATION_EVENT]: '补偿事件'
};

const STATE_DESCRIPTIONS = {
  [ORDER_STATES.CREATED]: '订单已创建',
  [ORDER_STATES.PENDING_PAYMENT]: '待支付',
  [ORDER_STATES.PAYMENT_SUCCEEDED]: '支付成功',
  [ORDER_STATES.PAYMENT_FAILED]: '支付失败',
  [ORDER_STATES.INVENTORY_LOCKED]: '库存已锁定',
  [ORDER_STATES.INVENTORY_FAILED]: '库存锁定失败',
  [ORDER_STATES.SHIPPING_PENDING]: '待发货',
  [ORDER_STATES.SHIPPED]: '已发货',
  [ORDER_STATES.DELIVERED]: '已签收',
  [ORDER_STATES.CANCEL_PENDING]: '取消待处理',
  [ORDER_STATES.CANCELLED]: '已取消',
  [ORDER_STATES.CANCEL_REJECTED]: '取消被拒',
  [ORDER_STATES.REFUND_PENDING]: '退款待处理',
  [ORDER_STATES.REFUNDED]: '已退款',
  [ORDER_STATES.REFUND_FAILED]: '退款失败',
  [ORDER_STATES.COMPENSATION_IN_PROGRESS]: '补偿处理中',
  [ORDER_STATES.COMPENSATED]: '已补偿'
};

class StateMachine {
  getNextState(currentState, eventType) {
    const transitions = STATE_TRANSITIONS[currentState];
    if (!transitions) {
      return null;
    }

    if (!transitions.allowedEvents.includes(eventType)) {
      return null;
    }

    return EVENT_TO_STATE_MAPPING[eventType] || null;
  }

  isValidTransition(currentState, eventType) {
    const transitions = STATE_TRANSITIONS[currentState];
    if (!transitions) {
      return false;
    }
    return transitions.allowedEvents.includes(eventType);
  }

  getTransitionDescription(currentState, eventType) {
    const transitions = STATE_TRANSITIONS[currentState];
    if (transitions && transitions.descriptions[eventType]) {
      return transitions.descriptions[eventType];
    }
    return EVENT_DESCRIPTIONS[eventType] || `执行事件: ${eventType}`;
  }

  getStateDescription(state) {
    return STATE_DESCRIPTIONS[state] || state;
  }

  getEventDescription(eventType) {
    return EVENT_DESCRIPTIONS[eventType] || eventType;
  }

  getAllowedEvents(currentState) {
    const transitions = STATE_TRANSITIONS[currentState];
    if (!transitions) {
      return [];
    }
    return transitions.allowedEvents;
  }

  canCancel(currentState) {
    const allowedEvents = this.getAllowedEvents(currentState);
    return allowedEvents.includes(EVENT_TYPES.CANCEL_REQUESTED);
  }

  canRefund(currentState) {
    const allowedEvents = this.getAllowedEvents(currentState);
    return allowedEvents.includes(EVENT_TYPES.REFUND_INITIATED);
  }
}

module.exports = {
  StateMachine,
  ORDER_STATES,
  EVENT_TYPES,
  STATE_TRANSITIONS,
  EVENT_TO_STATE_MAPPING,
  EVENT_DESCRIPTIONS,
  STATE_DESCRIPTIONS
};
