package com.grayscale.rollback.enums;

public enum OperationType {
    CREATE_RELEASE,
    UPDATE_RELEASE,
    START_PREPARING,
    ADVANCE_CANARY,
    COMPLETE_RELEASE,
    TRIGGER_ROLLBACK,
    EXECUTE_ROLLBACK,
    COMPLETE_ROLLBACK,
    FAIL_RELEASE,
    REPLAY_OPERATION,
    LOCK_ACQUIRE,
    LOCK_RELEASE,
    CACHE_UPDATE,
    CACHE_INVALIDATE
}
