#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
DATA_DIR="$PROJECT_DIR/data"
NORMAL_DATA_DIR="$SCRIPT_DIR/data/normal"
ERROR_DATA_DIR="$SCRIPT_DIR/data"
CLI="node $PROJECT_DIR/src/index.js"

echo ""
echo "========================================"
echo "  🧴 水站桶装水押金对账 CLI 演示"
echo "========================================"
echo ""

echo "========================================"
echo "  ❌ 第一部分: 异常检测功能演示"
echo "========================================"
echo ""

echo "📦 清理数据"
echo "----------------------------------------"
rm -rf "$DATA_DIR"
echo "已删除旧数据目录"
echo ""

echo "📥 导入包含异常的数据 (张三退押金但仍欠桶)"
echo "----------------------------------------"
echo ""
$CLI import history "$ERROR_DATA_DIR/history.csv"
echo ""
$CLI import delivery "$ERROR_DATA_DIR/delivery.csv"
echo ""
$CLI import return "$ERROR_DATA_DIR/return.csv"
echo ""
$CLI import refund "$ERROR_DATA_DIR/refund.csv"
echo ""

echo "🔍 运行异常检查"
echo "----------------------------------------"
$CLI check
echo ""

echo "💡 检查结果说明:"
echo "   ✅ 张三被正确检测：退了1桶押金但仍欠1桶"
echo "   ✅ 李四、王五、吴十不再被误报（他们还清了桶）"
echo "   ⚠️  配送员差异是警告，不阻止确认"
echo ""

echo "🔧 人工修正示例"
echo "----------------------------------------"
echo ""
echo "方案1: 删除张三的退款记录 (他还没还清桶)"
echo "   $CLI fix refund REF20260506001 --delete"
echo ""
echo "方案2: 让张三多还1桶 (回收从1桶改2桶)"
echo "   $CLI fix return R20260506001 bucketCount 2"
echo ""
echo "方案3: 让张三少退1桶押金"
echo "   $CLI fix refund REF20260506001 bucketCount 0"
echo "   $CLI fix refund REF20260506001 refundAmount 0"
echo ""

echo "🔄 测试重复导入防护"
echo "----------------------------------------"
echo ""
echo "再次导入相同配送单 (预期检测到重复)..."
$CLI import delivery "$ERROR_DATA_DIR/delivery.csv" || true
echo ""

echo "========================================"
echo "  ✅ 第二部分: 完整流程演示"
echo "========================================"
echo ""

echo "📦 清理数据"
echo "----------------------------------------"
rm -rf "$DATA_DIR"
echo "已删除旧数据目录"
echo ""

echo "📥 导入正常数据"
echo "----------------------------------------"
echo ""
$CLI import history "$NORMAL_DATA_DIR/history.csv"
echo ""
$CLI import delivery "$NORMAL_DATA_DIR/delivery.csv"
echo ""
$CLI import return "$NORMAL_DATA_DIR/return.csv"
echo ""
$CLI import refund "$NORMAL_DATA_DIR/refund.csv"
echo ""

echo "🔍 运行异常检查 (正常数据无错误)"
echo "----------------------------------------"
$CLI check
echo ""

echo "✅ 确认入账"
echo "----------------------------------------"
$CLI confirm
echo ""

echo "📊 生成对账报表"
echo "----------------------------------------"
$CLI report
echo ""

echo "========================================"
echo "  🎉 演示完成！"
echo "========================================"
echo ""
echo "核心修复内容:"
echo "  1. ✅ 修复了\"退押金但仍欠桶\"的判断逻辑"
echo "     - 之前: refunded > netBuckets (错误)"
echo "     - 现在: refunded > 0 && netOwed > 0 (正确)"
echo ""
echo "  2. ✅ 区分错误和警告"
echo "     - ❌ 错误: 数据校验、超量回收、退押金欠桶"
echo "     - ⚠️  警告: 配送员差异 (不阻止确认)"
echo ""
echo "常用命令汇总:"
echo "  water-deposit import <type> <file>   # 导入数据"
echo "  water-deposit check                  # 异常检查"
echo "  water-deposit fix ...                # 人工修正"
echo "  water-deposit confirm                # 确认入账"
echo "  water-deposit report                 # 生成报表"
echo ""
