import type { LevelDef } from '../engine/types';

export const LEVELS: LevelDef[] = [
  {
    id: 'L1',
    name: '常规运营',
    description: '单条主干线路，早晚高峰客流压力，无施工。重点体验基础调度：合理安排发车间隔，避免乘客等待过久导致投诉。',
    difficulty: 1,
    durationMin: 20,
    stations: [
      { id: 'S1', name: '火车站', x: 80, y: 220 },
      { id: 'S2', name: '市政府', x: 240, y: 220 },
      { id: 'S3', name: '中心广场', x: 420, y: 220 },
      { id: 'S4', name: '医院', x: 600, y: 220 },
      { id: 'S5', name: '大学', x: 780, y: 220 },
    ],
    routes: [
      {
        id: 'R1',
        name: '1 路（火车站—大学）',
        color: '#3AA0FF',
        stops: ['S1', 'S2', 'S3', 'S4', 'S5'],
        headwayMin: 4,
      },
    ],
    initialFleet: 4,
    maxComplaints: 10,
    maxDelayMin: 8,
    minCoverage: 0.8,
    closures: [],
    passengerEvents: [
      { minute: 2, stopId: 'S1', count: 8 },
      { minute: 4, stopId: 'S2', count: 5 },
      { minute: 6, stopId: 'S3', count: 10 },
      { minute: 9, stopId: 'S4', count: 6 },
      { minute: 12, stopId: 'S5', count: 7 },
      { minute: 15, stopId: 'S3', count: 8 },
    ],
  },
  {
    id: 'L2',
    name: '施工绕行',
    description: '主线路中段出现施工封路，必须临时切换备用路径；投诉阈值更低，重点考验改线与调度决策。',
    difficulty: 2,
    durationMin: 22,
    stations: [
      { id: 'S1', name: '火车站', x: 80, y: 180 },
      { id: 'S2', name: '市政府', x: 260, y: 180 },
      { id: 'S3', name: '中心广场', x: 460, y: 180 },
      { id: 'S4', name: '医院', x: 660, y: 180 },
      { id: 'S5', name: '大学', x: 860, y: 180 },
      { id: 'A1', name: '北街（绕）', x: 260, y: 60 },
      { id: 'A2', name: '体育馆（绕）', x: 460, y: 60 },
      { id: 'A3', name: '科技馆（绕）', x: 660, y: 60 },
    ],
    routes: [
      {
        id: 'R1',
        name: '1 路',
        color: '#3AA0FF',
        stops: ['S1', 'S2', 'S3', 'S4', 'S5'],
        altStops: ['S1', 'S2', 'A1', 'A2', 'A3', 'S4', 'S5'],
        headwayMin: 4,
      },
    ],
    initialFleet: 4,
    maxComplaints: 6,
    maxDelayMin: 6,
    minCoverage: 0.7,
    closures: [
      { id: 'C1', fromStop: 'S2', toStop: 'S3', startMinute: 5, endMinute: 16 },
    ],
    passengerEvents: [
      { minute: 2, stopId: 'S1', count: 6 },
      { minute: 5, stopId: 'S3', count: 12 },
      { minute: 8, stopId: 'S4', count: 8 },
      { minute: 11, stopId: 'A2', count: 5 },
      { minute: 14, stopId: 'S5', count: 9 },
      { minute: 17, stopId: 'S2', count: 6 },
    ],
  },
  {
    id: 'L3',
    name: '多线冲突',
    description: '两条线路共享主干道，车辆资源有限（减半）。重点在资源分配与间隔均衡，避免双线路同时延误。',
    difficulty: 3,
    durationMin: 24,
    stations: [
      { id: 'S1', name: '火车站', x: 80, y: 140 },
      { id: 'S2', name: '市政府', x: 300, y: 140 },
      { id: 'S3', name: '中心广场', x: 520, y: 140 },
      { id: 'S4', name: '医院', x: 740, y: 140 },
      { id: 'S5', name: '大学', x: 920, y: 140 },
      { id: 'T1', name: '南站', x: 80, y: 320 },
      { id: 'T2', name: '科技园', x: 300, y: 320 },
      { id: 'T3', name: '会展中心', x: 520, y: 320 },
      { id: 'T4', name: '体育馆', x: 740, y: 320 },
      { id: 'T5', name: '机场', x: 920, y: 320 },
    ],
    routes: [
      {
        id: 'R1',
        name: '1 路（东西干线）',
        color: '#3AA0FF',
        stops: ['S1', 'S2', 'S3', 'S4', 'S5'],
        headwayMin: 5,
      },
      {
        id: 'R2',
        name: '2 路（南北干线）',
        color: '#E2A93B',
        stops: ['T1', 'T2', 'T3', 'T4', 'T5'],
        headwayMin: 5,
      },
    ],
    initialFleet: 5,
    maxComplaints: 8,
    maxDelayMin: 7,
    minCoverage: 0.75,
    closures: [
      { id: 'C1', fromStop: 'S2', toStop: 'S3', startMinute: 8, endMinute: 15, routeId: 'R1' },
    ],
    passengerEvents: [
      { minute: 2, stopId: 'S1', count: 7 },
      { minute: 3, stopId: 'T1', count: 6 },
      { minute: 6, stopId: 'S3', count: 10 },
      { minute: 7, stopId: 'T3', count: 9 },
      { minute: 10, stopId: 'S4', count: 8 },
      { minute: 11, stopId: 'T4', count: 7 },
      { minute: 14, stopId: 'S5', count: 6 },
      { minute: 15, stopId: 'T5', count: 8 },
      { minute: 18, stopId: 'S2', count: 5 },
      { minute: 19, stopId: 'T2', count: 5 },
    ],
  },
];

export function getLevelById(id: string): LevelDef | undefined {
  return LEVELS.find((l) => l.id === id);
}
