import csv
from pathlib import Path

data = [
    {
        "sample_id": "S001", "student_id": "STU101", "question_id": "Q2023-045",
        "subject": "物理", "error_type": "读数误差", "error_source": "仪器精度",
        "expected_value": 9.80, "actual_value": 9.75, "propagated_error": 0.05,
        "error_magnitude": 0.0025, "original_answer": "9.75±0.05",
        "corrected_answer": "9.80±0.03", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": True, "confirm_before_note": "第一次看错了游标卡尺",
        "confirm_after_note": "重新对齐刻度后修正", "supplementary_remark": "",
        "supplementary_explanation": "",
        "created_at": "2026-06-15 09:30", "confirmed_at": "2026-06-15 10:12",
        "review_round": 1,
    },
    {
        "sample_id": "S002", "student_id": "STU102", "question_id": "Q2023-045",
        "subject": "物理", "error_type": "读数误差", "error_source": "仪器精度",
        "expected_value": 9.80, "actual_value": 9.78, "propagated_error": 0.02,
        "error_magnitude": 0.0004, "original_answer": "9.78±0.02",
        "corrected_answer": "9.80±0.03", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": True, "confirm_before_note": "小数点第二位估读偏大",
        "confirm_after_note": "已按标准操作重新估读", "supplementary_remark": "",
        "supplementary_explanation": "",
        "created_at": "2026-06-15 09:32", "confirmed_at": "2026-06-15 10:15",
        "review_round": 1,
    },
    {
        "sample_id": "S003", "student_id": "STU101", "question_id": "Q2023-045",
        "subject": "物理", "error_type": "读数误差", "error_source": "仪器精度",
        "expected_value": 9.80, "actual_value": 9.75, "propagated_error": 0.05,
        "error_magnitude": 0.0025, "original_answer": "9.75±0.05",
        "corrected_answer": "9.80±0.03", "is_duplicate": True, "duplicate_of": "S001",
        "manual_confirmed": False, "confirm_before_note": "",
        "confirm_after_note": "待确认：与S001是否为同一人重复提交？",
        "supplementary_remark": "后补备注：STU101提交了两次，第一次是草稿",
        "supplementary_explanation": "后补说明：该生在草稿纸上演算后忘记提交最终版本，系统记录了两次答案，需要人工判断以哪次为准",
        "created_at": "2026-06-15 09:31", "confirmed_at": "2026-06-15 11:00",
        "review_round": 1,
    },
    {
        "sample_id": "S004", "student_id": "STU103", "question_id": "Q2023-088",
        "subject": "化学", "error_type": "计算误差", "error_source": "有效数字保留",
        "expected_value": 2.35, "actual_value": 2.347, "propagated_error": 0.003,
        "error_magnitude": 0.000009, "original_answer": "2.347",
        "corrected_answer": "2.35", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": False, "confirm_before_note": "",
        "confirm_after_note": "有效数字保留位数错误，统一要求保留三位",
        "supplementary_remark": "", "supplementary_explanation": "",
        "created_at": "2026-06-15 10:05", "confirmed_at": "",
        "review_round": 1,
    },
    {
        "sample_id": "S005", "student_id": "STU104", "question_id": "Q2023-088",
        "subject": "化学", "error_type": "计算误差", "error_source": "公式误用",
        "expected_value": 2.35, "actual_value": 2.41, "propagated_error": 0.06,
        "error_magnitude": 0.0036, "original_answer": "2.41",
        "corrected_answer": "2.35", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": True, "confirm_before_note": "误差传播公式中平方项漏了系数2",
        "confirm_after_note": "已补正公式并复算", "supplementary_remark": "",
        "supplementary_explanation": "",
        "created_at": "2026-06-15 10:10", "confirmed_at": "2026-06-15 14:20",
        "review_round": 1,
    },
    {
        "sample_id": "S006", "student_id": "STU105", "question_id": "Q2023-012",
        "subject": "数学", "error_type": "舍入误差", "error_source": "中间步骤截断",
        "expected_value": 12.57, "actual_value": 12.50, "propagated_error": 0.07,
        "error_magnitude": 0.0049, "original_answer": "12.50",
        "corrected_answer": "12.57", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": False, "confirm_before_note": "",
        "confirm_after_note": "中间步骤π取3.14导致截断，应保留更多有效数字再最终舍入",
        "supplementary_remark": "", "supplementary_explanation": "",
        "created_at": "2026-06-15 11:00", "confirmed_at": "",
        "review_round": 1,
    },
    {
        "sample_id": "S007", "student_id": "STU102", "question_id": "Q2023-012",
        "subject": "数学", "error_type": "舍入误差", "error_source": "中间步骤截断",
        "expected_value": 12.57, "actual_value": 12.55, "propagated_error": 0.02,
        "error_magnitude": 0.0004, "original_answer": "12.55",
        "corrected_answer": "12.57", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": True, "confirm_before_note": "中间值舍入过早",
        "confirm_after_note": "最后一步再舍入", "supplementary_remark": "",
        "supplementary_explanation": "",
        "created_at": "2026-06-15 11:02", "confirmed_at": "2026-06-15 15:30",
        "review_round": 1,
    },
    {
        "sample_id": "S008", "student_id": "STU106", "question_id": "Q2023-156",
        "subject": "物理", "error_type": "系统误差", "error_source": "仪器校准偏差",
        "expected_value": 45.2, "actual_value": 44.8, "propagated_error": 0.4,
        "error_magnitude": 0.16, "original_answer": "44.8±0.2",
        "corrected_answer": "45.2±0.3", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": False, "confirm_before_note": "",
        "confirm_after_note": "天平未校准导致整体偏低，已用标准砝码校准仪器",
        "supplementary_remark": "", "supplementary_explanation": "",
        "created_at": "2026-06-15 13:45", "confirmed_at": "",
        "review_round": 1,
    },
    {
        "sample_id": "S009", "student_id": "STU107", "question_id": "Q2023-156",
        "subject": "物理", "error_type": "系统误差", "error_source": "仪器校准偏差",
        "expected_value": 45.2, "actual_value": 44.9, "propagated_error": 0.3,
        "error_magnitude": 0.09, "original_answer": "44.9±0.2",
        "corrected_answer": "45.2±0.3", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": True, "confirm_before_note": "同S008仪器问题",
        "confirm_after_note": "已统一处理该批次仪器",
        "supplementary_remark": "后补备注：该实验室所有天平当天均存在系统偏差，建议整批复核",
        "supplementary_explanation": "后补说明：经核查，6月15日上午该实验室3号天平未完成日常校准即投入使用，涉及STU106到STU110共5名学生，除本记录外其余样本已在复算中修正",
        "created_at": "2026-06-15 13:46", "confirmed_at": "2026-06-15 16:00",
        "review_round": 1,
    },
    {
        "sample_id": "S010", "student_id": "STU108", "question_id": "Q2023-156",
        "subject": "物理", "error_type": "系统误差", "error_source": "仪器校准偏差",
        "expected_value": 45.2, "actual_value": 44.85, "propagated_error": 0.35,
        "error_magnitude": 0.1225, "original_answer": "44.85±0.2",
        "corrected_answer": "45.2±0.3", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": False, "confirm_before_note": "",
        "confirm_after_note": "同实验室系统误差，已修正",
        "supplementary_remark": "", "supplementary_explanation": "",
        "created_at": "2026-06-15 13:47", "confirmed_at": "",
        "review_round": 1,
    },
    {
        "sample_id": "S011", "student_id": "STU101", "question_id": "Q2023-201",
        "subject": "数学", "error_type": "随机误差", "error_source": "测量波动",
        "expected_value": 3.1416, "actual_value": 3.14, "propagated_error": 0.0016,
        "error_magnitude": 0.00000256, "original_answer": "3.14",
        "corrected_answer": "3.1416", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": True, "confirm_before_note": "π近似值位数不够",
        "confirm_after_note": "需取至少四位小数", "supplementary_remark": "",
        "supplementary_explanation": "",
        "created_at": "2026-06-15 14:30", "confirmed_at": "2026-06-16 09:10",
        "review_round": 2,
    },
    {
        "sample_id": "S012", "student_id": "STU109", "question_id": "Q2023-077",
        "subject": "化学", "error_type": "读数误差", "error_source": "估读偏差",
        "expected_value": 0.125, "actual_value": 0.13, "propagated_error": 0.005,
        "error_magnitude": 0.000025, "original_answer": "0.13",
        "corrected_answer": "0.125", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": False, "confirm_before_note": "",
        "confirm_after_note": "滴定管读数仰视，读数时视线应与凹液面最低处平齐",
        "supplementary_remark": "", "supplementary_explanation": "",
        "created_at": "2026-06-15 15:00", "confirmed_at": "",
        "review_round": 1,
    },
    {
        "sample_id": "S013", "student_id": "STU110", "question_id": "Q2023-077",
        "subject": "化学", "error_type": "读数误差", "error_source": "估读偏差",
        "expected_value": 0.125, "actual_value": 0.12, "propagated_error": 0.005,
        "error_magnitude": 0.000025, "original_answer": "0.12",
        "corrected_answer": "0.125", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": True, "confirm_before_note": "滴定管读数俯视",
        "confirm_after_note": "读数方法同S012修正", "supplementary_remark": "",
        "supplementary_explanation": "",
        "created_at": "2026-06-15 15:02", "confirmed_at": "2026-06-15 17:20",
        "review_round": 1,
    },
    {
        "sample_id": "S014", "student_id": "STU103", "question_id": "Q2023-230",
        "subject": "物理", "error_type": "计算误差", "error_source": "误差传递公式错用",
        "expected_value": 5.68, "actual_value": 5.50, "propagated_error": 0.18,
        "error_magnitude": 0.0324, "original_answer": "5.50±0.10",
        "corrected_answer": "5.68±0.15", "is_duplicate": True, "duplicate_of": "S014",
        "manual_confirmed": True,
        "confirm_before_note": "该记录提交时有两个版本，初版5.50，修正版5.68",
        "confirm_after_note": "确认按修正版5.68归档，与S014为同一记录自我修正",
        "supplementary_remark": "后补备注：样本自身重复，系统允许学生在截止前修改答案，本记录保留两次提交的快照用于复盘",
        "supplementary_explanation": "后补说明：S014是学生STU103自己在截止前10分钟修改的答案，从5.50改到5.68，误差传播公式也一并修正了，用于展示同一人自我修正的重复类型",
        "created_at": "2026-06-15 15:30", "confirmed_at": "2026-06-15 15:45",
        "review_round": 1,
    },
    {
        "sample_id": "S015", "student_id": "STU104", "question_id": "Q2023-230",
        "subject": "物理", "error_type": "计算误差", "error_source": "误差传递公式错用",
        "expected_value": 5.68, "actual_value": 5.72, "propagated_error": 0.04,
        "error_magnitude": 0.0016, "original_answer": "5.72±0.10",
        "corrected_answer": "5.68±0.15", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": False, "confirm_before_note": "",
        "confirm_after_note": "系数错用为加法而非方和根，已按方和根公式复算",
        "supplementary_remark": "", "supplementary_explanation": "",
        "created_at": "2026-06-15 15:32", "confirmed_at": "",
        "review_round": 1,
    },
    {
        "sample_id": "S016", "student_id": "STU111", "question_id": "Q2023-310",
        "subject": "数学", "error_type": "舍入误差", "error_source": "四舍五入方向错误",
        "expected_value": 7.82, "actual_value": 7.81, "propagated_error": 0.01,
        "error_magnitude": 0.0001, "original_answer": "7.81",
        "corrected_answer": "7.82", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": False, "confirm_before_note": "",
        "confirm_after_note": "末位1按五入了，严格四舍五入",
        "supplementary_remark": "", "supplementary_explanation": "",
        "created_at": "2026-06-16 08:30", "confirmed_at": "",
        "review_round": 2,
    },
    {
        "sample_id": "S017", "student_id": "STU112", "question_id": "Q2023-310",
        "subject": "数学", "error_type": "舍入误差", "error_source": "四舍五入方向错误",
        "expected_value": 7.82, "actual_value": 7.83, "propagated_error": 0.01,
        "error_magnitude": 0.0001, "original_answer": "7.83",
        "corrected_answer": "7.82", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": False, "confirm_before_note": "",
        "confirm_after_note": "末位3按四舍了，严格四舍五入",
        "supplementary_remark": "", "supplementary_explanation": "",
        "created_at": "2026-06-16 08:32", "confirmed_at": "",
        "review_round": 2,
    },
    {
        "sample_id": "S018", "student_id": "STU105", "question_id": "Q2023-390",
        "subject": "化学", "error_type": "计算误差", "error_source": "单位换算遗漏",
        "expected_value": 0.00123, "actual_value": 1.23, "propagated_error": 1.22877,
        "error_magnitude": 1.50988, "original_answer": "1.23 mol/L",
        "corrected_answer": "1.23e-3 mol/L", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": False, "confirm_before_note": "",
        "confirm_after_note": "漏掉了mmol到mol的乘以10^-3换算，注意量纲",
        "supplementary_remark": "", "supplementary_explanation": "",
        "created_at": "2026-06-16 09:15", "confirmed_at": "",
        "review_round": 2,
    },
    {
        "sample_id": "S019", "student_id": "STU106", "question_id": "Q2023-390",
        "subject": "化学", "error_type": "计算误差", "error_source": "单位换算遗漏",
        "expected_value": 0.00123, "actual_value": 1.23, "propagated_error": 1.22877,
        "error_magnitude": 1.50988, "original_answer": "1.23 mol/L",
        "corrected_answer": "1.23e-3 mol/L", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": False, "confirm_before_note": "",
        "confirm_after_note": "同S018单位问题，已统一讲解单位换算注意事项",
        "supplementary_remark": "", "supplementary_explanation": "",
        "created_at": "2026-06-16 09:17", "confirmed_at": "",
        "review_round": 2,
    },
    {
        "sample_id": "S020", "student_id": "STU113", "question_id": "Q2023-445",
        "subject": "物理", "error_type": "随机误差", "error_source": "样本量不足",
        "expected_value": 2.50, "actual_value": 2.40, "propagated_error": 0.10,
        "error_magnitude": 0.01, "original_answer": "2.40±0.05",
        "corrected_answer": "2.50±0.10", "is_duplicate": False, "duplicate_of": "",
        "manual_confirmed": True,
        "confirm_before_note": "只测了3次就取平均，建议至少测6次",
        "confirm_after_note": "按边界样本处理，标记统计显著性偏弱",
        "supplementary_remark": "后补备注：边界样本，学生只做了3次重复测量，样本量偏少，统计显著性较弱",
        "supplementary_explanation": "后补说明：该题要求至少测量5次取平均以降低随机误差影响，该生时间不够只测了3次，属于边界情况，在误差传播分析中样本方差的自由度偏低，置信区间会更宽，归类时需要特别标注",
        "created_at": "2026-06-16 10:00", "confirmed_at": "2026-06-16 10:45",
        "review_round": 2,
    },
]

fieldnames = list(data[0].keys())
out_path = Path(__file__).parent / "data" / "error_samples.csv"
with open(out_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames, quoting=csv.QUOTE_MINIMAL)
    writer.writeheader()
    for row in data:
        writer.writerow(row)

print(f"已生成 {out_path}，共 {len(data)} 条记录")
