#!/bin/bash

BASE_URL="http://localhost:3000/api/tickets"

echo "=========================================="
echo "工单 SLA 暂停 API - Curl 示例命令"
echo "=========================================="
echo ""

echo "【基础信息查询】"
echo "------------------------------------------"
echo ""

echo "# 1. 查询所有优先级及其 SLA"
echo "curl -X GET $BASE_URL/priorities"
echo ""

echo "# 2. 查询所有暂停类型"
echo "curl -X GET $BASE_URL/pause-types"
echo ""

echo "=========================================="
echo "场景 1: 正常关闭的技术支持工单"
echo "=========================================="
echo ""

echo "# 步骤 1: 创建工单 (高优先级 - 8小时 SLA)"
echo "curl -X POST $BASE_URL/ \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"title\":\"无法登录系统\",\"type\":\"technical_support\",\"priority\":\"high\",\"customerId\":\"C001\",\"description\":\"用户无法登录后台\"}'"
echo ""

echo "# 步骤 2: 开始处理 (记录 SLA 开始时间)"
echo "curl -X POST $BASE_URL/T-000001/start \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"assignee\":\"张三\"}'"
echo ""

echo "# 步骤 3: 关闭工单 (计算 SLA 结果)"
echo "curl -X POST $BASE_URL/T-000001/close"
echo ""

echo "# 步骤 4: 查看详细时间线"
echo "curl -X GET $BASE_URL/T-000001/timeline"
echo ""

echo "=========================================="
echo "场景 2: 客户等待暂停 (不计入 SLA)"
echo "=========================================="
echo ""

echo "# 步骤 1: 创建投诉工单 (紧急优先级 - 2小时 SLA)"
echo "curl -X POST $BASE_URL/ \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"title\":\"订单未送达投诉\",\"type\":\"complaint\",\"priority\":\"critical\",\"customerId\":\"C002\"}'"
echo ""

echo "# 步骤 2: 开始处理"
echo "curl -X POST $BASE_URL/T-000002/start \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"assignee\":\"李四\"}'"
echo ""

echo "# 步骤 3: 暂停 - 等待客户提供订单号 (客户等待)"
echo "# 注意: 必须提供暂停原因，否则不能生效"
echo "curl -X POST $BASE_URL/T-000002/pause \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"pauseType\":\"customer_waiting\",\"reason\":\"需要客户提供订单号查询物流\"}'"
echo ""

echo "# 步骤 4: 恢复计时 (客户已提供信息)"
echo "curl -X POST $BASE_URL/T-000002/resume"
echo ""

echo "# 步骤 5: 关闭工单"
echo "curl -X POST $BASE_URL/T-000002/close"
echo ""

echo "# 步骤 6: 查看时间线 (会显示暂停和恢复事件)"
echo "curl -X GET $BASE_URL/T-000002/timeline"
echo ""

echo "=========================================="
echo "场景 3: 内部等待 (计入 SLA，内部责任)"
echo "=========================================="
echo ""

echo "# 步骤 1: 创建退款工单"
echo "curl -X POST $BASE_URL/ \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"title\":\"退款申请\",\"type\":\"refund\",\"priority\":\"medium\",\"customerId\":\"C003\"}'"
echo ""

echo "# 步骤 2: 开始处理"
echo "curl -X POST $BASE_URL/T-000003/start \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"assignee\":\"王五\"}'"
echo ""

echo "# 步骤 3: 内部等待 (需要财务审核，这部分计入 SLA)"
echo "curl -X POST $BASE_URL/T-000003/pause \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"pauseType\":\"internal_waiting\",\"reason\":\"等待财务部门审核退款\"}'"
echo ""

echo "# 步骤 4: 恢复并关闭"
echo "curl -X POST $BASE_URL/T-000003/resume"
echo "curl -X POST $BASE_URL/T-000003/close"
echo ""

echo "=========================================="
echo "场景 4: 节假日暂停"
echo "=========================================="
echo ""

echo "# 节假日暂停 (系统也会自动排除周末和法定假日)"
echo "curl -X POST $BASE_URL/T-000004/pause \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"pauseType\":\"holiday\",\"reason\":\"春节假期暂停处理\"}'"
echo ""

echo "=========================================="
echo "场景 5: 测试规则验证"
echo "=========================================="
echo ""

echo "# 测试 1: 暂停原因缺失 (应该返回 400 错误)"
echo "curl -X POST $BASE_URL/T-000001/pause \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"pauseType\":\"customer_waiting\"}'"
echo ""

echo "# 测试 2: 关闭后修改优先级 (应该返回 409 错误)"
echo "curl -X POST $BASE_URL/T-000001/assign-priority \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"priority\":\"critical\"}'"
echo ""

echo "# 测试 3: 关闭后暂停 (应该返回 409 错误)"
echo "curl -X POST $BASE_URL/T-000001/pause \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"pauseType\":\"customer_waiting\",\"reason\":\"测试\"}'"
echo ""

echo "=========================================="
echo "场景 6: 申诉后重算 SLA"
echo "=========================================="
echo ""

echo "# 步骤 1: 假设工单已关闭但标记为超时"
echo "# 先关闭一个工单用于测试"
echo "curl -X POST $BASE_URL/ \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"title\":\"超时测试工单\",\"type\":\"technical_support\",\"priority\":\"critical\",\"customerId\":\"C004\"}'"
echo "curl -X POST $BASE_URL/T-000005/start \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"assignee\":\"赵六\"}'"
echo "curl -X POST $BASE_URL/T-000005/close"
echo ""

echo "# 步骤 2: 创建申诉"
echo "curl -X POST $BASE_URL/T-000005/appeal \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"appealReason\":\"处理期间客户迟迟未回复\",
echo "    \"adjustPauseReason\":\"客户等待时间不应计入 SLA\"
echo "  }'"
echo ""

echo "# 步骤 3: 审批申诉 (确认为客户等待)"
echo "curl -X POST $BASE_URL/T-000005/approve-appeal \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"approvedPauseType\":\"customer_waiting\",
echo "    \"approvedReason\":\"经查证，客户确实延迟回复\"
echo "  }'"
echo ""

echo "# 步骤 4: 查看重算后的 SLA 和时间线"
echo "curl -X GET $BASE_URL/T-000005"
echo "curl -X GET $BASE_URL/T-000005/timeline"
echo ""

echo "=========================================="
echo "场景 7: 统计报表"
echo "=========================================="
echo ""

echo "# 查询所有统计数据"
echo "curl -X GET $BASE_URL/stats"
echo ""

echo "# 按时间段查询 (可选)"
echo "curl -X GET \"$BASE_URL/stats?startDate=2024-01-01&endDate=2024-12-31\""
echo ""

echo "=========================================="
echo "其他有用的查询"
echo "=========================================="
echo ""

echo "# 查询所有工单"
echo "curl -X GET $BASE_URL/"
echo ""

echo "# 查询单个工单详情"
echo "curl -X GET $BASE_URL/T-000001"
echo ""

echo "# 动态调整优先级"
echo "curl -X POST $BASE_URL/T-000001/assign-priority \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"priority\":\"critical\"}'"
echo ""

echo "=========================================="
echo "暂停类型说明"
echo "=========================================="
echo ""
echo "customer_waiting (客户等待)   - 不计入 SLA，客户责任"
echo "third_party_waiting (第三方)   - 不计入 SLA，第三方责任"
echo "internal_waiting (内部等待)    - 计入 SLA，内部责任"
echo "holiday (节假日)               - 不计入 SLA，无责任"
echo ""

echo "=========================================="
echo "优先级 SLA 说明"
echo "=========================================="
echo ""
echo "critical (紧急) - 2小时"
echo "high (高)       - 8小时"
echo "medium (中)     - 24小时"
echo "low (低)        - 3个工作日"
echo ""
