const APPLICATION_STATUSES = {
  SUBMITTED: 'SUBMITTED',
  PENDING_SURVEY: 'PENDING_SURVEY',
  SURVEY_COMPLETED: 'SURVEY_COMPLETED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVAL_IN_PROGRESS: 'APPROVAL_IN_PROGRESS',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PENDING_METER: 'PENDING_METER',
  METER_INSTALLED: 'METER_INSTALLED',
  PENDING_SUPPLEMENT: 'PENDING_SUPPLEMENT',
  SUPPLEMENT_SUBMITTED: 'SUPPLEMENT_SUBMITTED',
  GRID_CONNECTED: 'GRID_CONNECTED',
  CANCELLED: 'CANCELLED'
};

const SURVEY_STATUSES = {
  PENDING: 'PENDING',
  SCHEDULED: 'SCHEDULED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED'
};

const APPROVAL_NODE_TYPES = {
  INITIAL_REVIEW: 'INITIAL_REVIEW',
  TECHNICAL_REVIEW: 'TECHNICAL_REVIEW',
  FINAL_APPROVAL: 'FINAL_APPROVAL'
};

const APPROVAL_STATUSES = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  NEEDS_SUPPLEMENT: 'NEEDS_SUPPLEMENT'
};

const METER_TASK_STATUSES = {
  PENDING: 'PENDING',
  SCHEDULED: 'SCHEDULED',
  INSTALLED: 'INSTALLED',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED'
};

const SUPPLEMENT_STATUSES = {
  PENDING: 'PENDING',
  SUBMITTED: 'SUBMITTED',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED'
};

const REPORT_STATUSES = {
  PENDING: 'PENDING',
  GENERATED: 'GENERATED',
  APPROVED: 'APPROVED'
};

const OPERATION_TYPES = {
  APPLICATION_SUBMIT: 'APPLICATION_SUBMIT',
  SURVEY_SCHEDULE: 'SURVEY_SCHEDULE',
  SURVEY_COMPLETE: 'SURVEY_COMPLETE',
  APPROVAL_REVIEW: 'APPROVAL_REVIEW',
  METER_INSTALL: 'METER_INSTALL',
  SUPPLEMENT_REQUEST: 'SUPPLEMENT_REQUEST',
  SUPPLEMENT_SUBMIT: 'SUPPLEMENT_SUBMIT',
  REPORT_GENERATE: 'REPORT_GENERATE',
  STATUS_CHANGE: 'STATUS_CHANGE',
  MANUAL_CORRECTION: 'MANUAL_CORRECTION'
};

const ERROR_CODES = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_ERROR: 500,
  VALIDATION_ERROR: 422
};

const VALIDATION_MESSAGES = {
  MISSING_FIELD: (field) => `缺少必填字段: ${field}`,
  INVALID_FORMAT: (field) => `${field} 格式不正确`,
  INVALID_STATUS: (status) => `无效的状态: ${status}`,
  INVALID_TRANSITION: (from, to) => `无效的状态转换: ${from} -> ${to}`,
  ALREADY_EXISTS: '记录已存在',
  NOT_FOUND: '记录不存在',
  VERSION_CONFLICT: '版本冲突，数据已被其他人修改'
};

module.exports = {
  APPLICATION_STATUSES,
  SURVEY_STATUSES,
  APPROVAL_NODE_TYPES,
  APPROVAL_STATUSES,
  METER_TASK_STATUSES,
  SUPPLEMENT_STATUSES,
  REPORT_STATUSES,
  OPERATION_TYPES,
  ERROR_CODES,
  VALIDATION_MESSAGES
};
