const REAGENT_CATEGORIES = {
  GENERAL: 'general',
  HAZARDOUS: 'hazardous',
  BIOLOGICAL: 'biological',
  RADIOACTIVE: 'radioactive'
};

const HAZARD_LEVELS = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  EXTREME: 'extreme'
};

const APPROVAL_STATES = {
  DRAFT: 'draft',
  SUBMITTED: 'submitted',
  LAB_MANAGER_APPROVED: 'lab_manager_approved',
  SAFETY_REVIEWED: 'safety_reviewed',
  PENDING_SECOND_REVIEW: 'pending_second_review',
  AUDIT_INCONSISTENCY: 'audit_inconsistency',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled'
};

const APPROVAL_TRANSITIONS = {
  [APPROVAL_STATES.DRAFT]: [APPROVAL_STATES.SUBMITTED, APPROVAL_STATES.CANCELLED],
  [APPROVAL_STATES.SUBMITTED]: [APPROVAL_STATES.LAB_MANAGER_APPROVED, APPROVAL_STATES.REJECTED, APPROVAL_STATES.PENDING_SECOND_REVIEW],
  [APPROVAL_STATES.LAB_MANAGER_APPROVED]: [APPROVAL_STATES.SAFETY_REVIEWED, APPROVAL_STATES.REJECTED, APPROVAL_STATES.PENDING_SECOND_REVIEW],
  [APPROVAL_STATES.SAFETY_REVIEWED]: [APPROVAL_STATES.APPROVED, APPROVAL_STATES.REJECTED, APPROVAL_STATES.PENDING_SECOND_REVIEW, APPROVAL_STATES.AUDIT_INCONSISTENCY],
  [APPROVAL_STATES.PENDING_SECOND_REVIEW]: [APPROVAL_STATES.APPROVED, APPROVAL_STATES.REJECTED],
  [APPROVAL_STATES.AUDIT_INCONSISTENCY]: [APPROVAL_STATES.APPROVED, APPROVAL_STATES.REJECTED, APPROVAL_STATES.SUBMITTED],
  [APPROVAL_STATES.APPROVED]: [APPROVAL_STATES.COMPLETED, APPROVAL_STATES.CANCELLED],
  [APPROVAL_STATES.REJECTED]: [APPROVAL_STATES.SUBMITTED, APPROVAL_STATES.CANCELLED],
  [APPROVAL_STATES.COMPLETED]: [],
  [APPROVAL_STATES.CANCELLED]: []
};

const APPROVAL_ROLES = {
  APPLICANT: 'applicant',
  LAB_MANAGER: 'lab_manager',
  SAFETY_OFFICER: 'safety_officer',
  AUDITOR: 'auditor',
  ADMIN: 'admin'
};

const HAZARDOUS_QUOTA = {
  [HAZARD_LEVELS.LOW]: { singleLimit: 500, monthlyLimit: 2000, requiresSecondReview: false },
  [HAZARD_LEVELS.MEDIUM]: { singleLimit: 100, monthlyLimit: 500, requiresSecondReview: true },
  [HAZARD_LEVELS.HIGH]: { singleLimit: 50, monthlyLimit: 200, requiresSecondReview: true },
  [HAZARD_LEVELS.EXTREME]: { singleLimit: 10, monthlyLimit: 50, requiresSecondReview: true }
};

const STORAGE_CONDITIONS = {
  ROOM_TEMP: 'room_temperature',
  REFRIGERATED: 'refrigerated',
  FROZEN: 'frozen',
  DARK: 'dark_storage',
  INERT_GAS: 'inert_gas',
  EXPLOSION_PROOF: 'explosion_proof'
};

module.exports = {
  REAGENT_CATEGORIES,
  HAZARD_LEVELS,
  APPROVAL_STATES,
  APPROVAL_TRANSITIONS,
  APPROVAL_ROLES,
  HAZARDOUS_QUOTA,
  STORAGE_CONDITIONS
};
