export class BusinessError extends Error {
  code: string;
  details?: any;

  constructor(code: string, message: string, details?: any) {
    super(message);
    this.code = code;
    this.details = details;
    this.name = 'BusinessError';
  }
}

export const ErrorCodes = {
  CONTRACT_NOT_FOUND: 'CONTRACT_NOT_FOUND',
  CONTRACT_ALREADY_REFUNDED: 'CONTRACT_ALREADY_REFUNDED',
  REFUND_NOT_FOUND: 'REFUND_NOT_FOUND',
  REFUND_ALREADY_APPROVED: 'REFUND_ALREADY_APPROVED',
  REFUND_ALREADY_CANCELLED: 'REFUND_ALREADY_CANCELLED',
  DUPLICATE_APPLICATION: 'DUPLICATE_APPLICATION',
  INSTALLMENT_NOT_PAID: 'INSTALLMENT_NOT_PAID',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  MATERIAL_FEE_ALREADY_DEDUCTED: 'MATERIAL_FEE_ALREADY_DEDUCTED',
  GIFTED_LESSON_TREATED_AS_PAID: 'GIFTED_LESSON_TREATED_AS_PAID',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;
