import type { Material, FilterCriteria, TimelineEvent, ExportRecord, HandoverNote } from './types';

const now = Date.now();
const DAY = 86400000;

export const mockMaterials: Material[] = [
  {
    id: 'mat-001',
    currentName: '葡萄糖标准品 (高纯级)',
    nameHistory: [
      { id: 'nh-1', materialId: 'mat-001', name: '葡萄糖标准品', timestamp: now - 7 * DAY, operator: '学生草稿-小王', reason: '最初命名' },
      { id: 'nh-2', materialId: 'mat-001', name: '葡萄糖标准品 (高纯级)', timestamp: now - 2 * DAY, operator: '老叶', reason: '标注纯度级别，避免与分析纯混淆' },
    ],
    unit: 'mg',
    dataPoints: [
      { id: 'dp-1', x: 0.1, y: 0.082, label: 'C1', source: 'student', isBoundary: false },
      { id: 'dp-2', x: 0.2, y: 0.165, label: 'C2', source: 'student', isBoundary: false },
      { id: 'dp-3', x: 0.5, y: 0.412, label: 'C3', source: 'student', isBoundary: false },
      { id: 'dp-4', x: 1.0, y: 0.823, label: 'C4', source: 'student', isBoundary: false },
      { id: 'dp-5', x: 2.0, y: 1.648, label: 'C5', source: 'reference', isBoundary: true, note: '高浓度边界-参考数据补充' },
      { id: 'dp-6', x: 0.05, y: 0.041, label: 'C0', source: 'reference', isBoundary: true, note: '低浓度边界-参考数据补充' },
    ],
    status: 'reviewed',
    draftOriginalText: '学生小王：按浓度从低到高排 C0→C5，C0 和 C5 是边界点，我只测了中间四个点，边界是查文献找的。老师说边界点要标清楚。',
    sortNote: '排序依据：浓度升序。学生草稿中明确写了"C0→C5"。C0(0.05mg) 和 C5(2.0mg) 为边界。',
    createdAt: now - 7 * DAY,
    updatedAt: now - 2 * DAY,
  },
  {
    id: 'mat-002',
    currentName: '牛血清白蛋白 BSA',
    nameHistory: [
      { id: 'nh-3', materialId: 'mat-002', name: 'BSA蛋白', timestamp: now - 5 * DAY, operator: '学生草稿-小李' },
      { id: 'nh-4', materialId: 'mat-002', name: '牛血清白蛋白 BSA', timestamp: now - 4 * DAY, operator: '小李', reason: '补全中文名称' },
    ],
    unit: 'μg',
    dataPoints: [
      { id: 'dp-7', x: 5, y: 0.125, label: 'S1', source: 'student', isBoundary: false },
      { id: 'dp-8', x: 10, y: 0.251, label: 'S2', source: 'student', isBoundary: false },
      { id: 'dp-9', x: 20, y: 0.498, label: 'S3', source: 'student', isBoundary: false },
      { id: 'dp-10', x: 40, y: 0.987, label: 'S4', source: 'student', isBoundary: false },
      { id: 'dp-11', x: 80, y: 1.952, label: 'S5', source: 'reference', isBoundary: true },
      { id: 'dp-12', x: 2.5, y: 0.063, label: 'S0', source: 'reference', isBoundary: true },
    ],
    status: 'processed',
    draftOriginalText: '学生小李：S1到S4是我测的，S0和S5是问隔壁组借的数。S0好像是2.5μg？不太确定，再查查。',
    sortNote: '排序：浓度升序 S0(2.5)→S5(80)。学生不确定 S0 精确值，存疑。',
    createdAt: now - 5 * DAY,
    updatedAt: now - 4 * DAY,
  },
  {
    id: 'mat-003',
    currentName: '氯化钠-临时改名(交接用)',
    nameHistory: [
      { id: 'nh-5', materialId: 'mat-003', name: 'NaCl溶液', timestamp: now - 3 * DAY, operator: '学生草稿-小张', reason: '学生原始命名' },
      { id: 'nh-6', materialId: 'mat-003', name: '氯化钠标准溶液', timestamp: now - 1 * DAY, operator: '小张' },
      { id: 'nh-7', materialId: 'mat-003', name: '氯化钠-临时改名(交接用)', timestamp: now, operator: '系统-交接模拟', reason: '【真实交接场景】为试跑复核功能临时改名，模拟材料名称前后不一致的情况。接手同事需确认是否改回"氯化钠标准溶液"。' },
    ],
    unit: 'mg',
    dataPoints: [
      { id: 'dp-13', x: 1, y: 0.077, label: 'N1', source: 'student', isBoundary: false },
      { id: 'dp-14', x: 2, y: 0.156, label: 'N2', source: 'student', isBoundary: false },
      { id: 'dp-15', x: 5, y: 0.389, label: 'N3', source: 'student', isBoundary: false },
      { id: 'dp-16', x: 10, y: 0.778, label: 'N4', source: 'student', isBoundary: false },
      { id: 'dp-17', x: 0.5, y: 0.038, label: 'N0', source: 'student', isBoundary: true, note: '边界样本少·仅学生自测' },
      { id: 'dp-18', x: 15, y: 1.152, label: 'N5', source: 'student', isBoundary: true, note: '边界样本少·仅学生自测' },
    ],
    status: 'pending',
    draftOriginalText: '学生小张：N0是1mg？不对，是0.5。N5是15mg。我觉得边界点也够用了，但老叶之前说边界最好双份确认，我没做。还有N3好像算错了，等会再看一遍。',
    sortNote: '【排序不稳定警告】学生原草稿顺序：N1→N2→N3→N4→N0→N5。按浓度排序应为：N0(0.5)→N1→N2→N3→N4→N5(15)。学生把边界点放在了最后，未按浓度升序。原始说法见左侧草稿文本。',
    createdAt: now - 3 * DAY,
    updatedAt: now,
  },
  {
    id: 'mat-004',
    currentName: '硫酸铜标准液',
    nameHistory: [
      { id: 'nh-8', materialId: 'mat-004', name: '硫酸铜', timestamp: now - 6 * DAY, operator: '学生草稿-小陈' },
      { id: 'nh-9', materialId: 'mat-004', name: '硫酸铜五水合物', timestamp: now - 5 * DAY, operator: '小陈' },
      { id: 'nh-10', materialId: 'mat-004', name: '硫酸铜标准液', timestamp: now - 4 * DAY, operator: '老叶', reason: '统一命名规范' },
    ],
    unit: 'mg',
    dataPoints: [
      { id: 'dp-19', x: 0.5, y: 0.201, label: 'T1', source: 'student', isBoundary: false },
      { id: 'dp-20', x: 1.0, y: 0.403, label: 'T2', source: 'student', isBoundary: false },
      { id: 'dp-21', x: 2.0, y: 0.798, label: 'T3', source: 'student', isBoundary: false },
      { id: 'dp-22', x: 5.0, y: 1.965, label: 'T4', source: 'reference', isBoundary: true },
    ],
    status: 'missing',
    draftOriginalText: '学生小陈：高浓度那边我还没测，T4是参考数据。低浓度我还缺一个T0(0.2mg)，下周补。',
    sortNote: '排序：T1→T4 浓度升序。缺低浓度边界 T0，状态为缺材料。',
    createdAt: now - 6 * DAY,
    updatedAt: now - 4 * DAY,
  },
  {
    id: 'mat-005',
    currentName: '磷酸二氢钾',
    nameHistory: [
      { id: 'nh-11', materialId: 'mat-005', name: 'KH2PO4', timestamp: now - 8 * DAY, operator: '学生草稿-小周' },
      { id: 'nh-12', materialId: 'mat-005', name: '磷酸二氢钾', timestamp: now - 6 * DAY, operator: '小周', reason: '改中文' },
    ],
    unit: 'g',
    dataPoints: [
      { id: 'dp-23', x: 0.01, y: 0.108, label: 'P1', source: 'student', isBoundary: false },
      { id: 'dp-24', x: 0.02, y: 0.214, label: 'P2', source: 'student', isBoundary: false },
      { id: 'dp-25', x: 0.05, y: 0.532, label: 'P3', source: 'student', isBoundary: false },
      { id: 'dp-26', x: 0.1, y: 1.051, label: 'P4', source: 'student', isBoundary: false },
      { id: 'dp-27', x: 0.2, y: 2.087, label: 'P5', source: 'reference', isBoundary: true },
      { id: 'dp-28', x: 0.005, y: 0.055, label: 'P0', source: 'reference', isBoundary: true },
    ],
    status: 'processed',
    draftOriginalText: '学生小周：P0到P5全齐了，单位是克。之前有人写成mg了，是错的。',
    sortNote: '排序：P0(0.005g)→P5(0.2g) 浓度升序。⚠️单位历史：曾被误写为mg，实际为g。',
    createdAt: now - 8 * DAY,
    updatedAt: now - 6 * DAY,
  },
];

export const mockFilterCriterias: FilterCriteria[] = [
  {
    id: 'f-001',
    name: '默认筛选-全部材料',
    materialIds: ['mat-001', 'mat-002', 'mat-003', 'mat-004', 'mat-005'],
    boundaryThreshold: 0.05,
    boundarySampleMinCount: 2,
    fittingDegree: 1,
    excludeOutliers: false,
    createdAt: now - 7 * DAY,
    createdBy: '老叶',
  },
  {
    id: 'f-002',
    name: '已复核材料-仅线性拟合',
    materialIds: ['mat-001'],
    boundaryThreshold: 0.05,
    boundarySampleMinCount: 2,
    fittingDegree: 1,
    excludeOutliers: true,
    createdAt: now - 4 * DAY,
    createdBy: '老叶',
  },
  {
    id: 'f-003',
    name: '交接试跑-含待处理',
    materialIds: ['mat-001', 'mat-002', 'mat-003', 'mat-004', 'mat-005'],
    boundaryThreshold: 0.03,
    boundarySampleMinCount: 3,
    fittingDegree: 2,
    excludeOutliers: false,
    createdAt: now,
    createdBy: '系统-交接试跑',
  },
];

export const mockTimeline: TimelineEvent[] = [
  {
    id: 't-001',
    type: 'import',
    timestamp: now - 8 * DAY,
    operator: '小周',
    description: '导入材料"磷酸二氢钾"，含6个数据点',
    detail: { fileName: 'phosphate_draft.xlsx', pointCount: 6 },
  },
  {
    id: 't-002',
    type: 'import',
    timestamp: now - 7 * DAY,
    operator: '小王',
    description: '导入材料"葡萄糖标准品"，含4个学生测点',
    detail: { fileName: 'glucose_wang.xlsx', pointCount: 4 },
  },
  {
    id: 't-003',
    type: 'rename',
    timestamp: now - 7 * DAY + 3600000,
    operator: '小王',
    description: '将"葡萄糖"改名为"葡萄糖标准品"',
    detail: { oldName: '葡萄糖', newName: '葡萄糖标准品' },
  },
  {
    id: 't-004',
    type: 'filter',
    timestamp: now - 7 * DAY + 7200000,
    operator: '老叶',
    description: '创建筛选口径"默认筛选-全部材料"',
    filterSnapshot: mockFilterCriterias[0],
  },
  {
    id: 't-005',
    type: 'import',
    timestamp: now - 6 * DAY,
    operator: '小陈',
    description: '导入材料"硫酸铜"，标注缺低浓度边界',
    detail: { status: 'missing', missingNote: '缺T0(0.2mg)' },
  },
  {
    id: 't-006',
    type: 'status_change',
    timestamp: now - 5 * DAY + 3600000,
    operator: '老叶',
    description: '【处理完成】磷酸二氢钾拟合R²=0.9998，边界齐全',
    detail: { materialId: 'mat-005', rSquared: 0.9998 },
  },
  {
    id: 't-007',
    type: 'import',
    timestamp: now - 5 * DAY,
    operator: '小李',
    description: '导入材料"BSA蛋白"',
    detail: { fileName: 'bsa_li.xlsx' },
  },
  {
    id: 't-008',
    type: 'rename',
    timestamp: now - 4 * DAY,
    operator: '老叶',
    description: '统一命名：硫酸铜→硫酸铜五水合物→硫酸铜标准液',
    detail: { materialId: 'mat-004', chain: ['硫酸铜', '硫酸铜五水合物', '硫酸铜标准液'] },
  },
  {
    id: 't-009',
    type: 'review',
    timestamp: now - 3 * DAY,
    operator: '老叶',
    description: '【复核通过】葡萄糖标准品 - 补充边界点C0/C5',
    detail: { materialId: 'mat-001', addedBoundaryPoints: 2, oldR2: 0.9976, newR2: 0.9999 },
  },
  {
    id: 't-010',
    type: 'import',
    timestamp: now - 3 * DAY,
    operator: '小张',
    description: '导入材料"NaCl溶液"（后改名为氯化钠-临时改名）',
    detail: { fileName: 'nacl_zhang.xlsx', statusNote: '边界样本少，仅学生自测' },
  },
  {
    id: 't-011',
    type: 'fit',
    timestamp: now - 2 * DAY,
    operator: '老叶',
    description: '执行拟合 - 筛选"默认筛选-全部材料"',
    detail: { filterId: 'f-001', materialCount: 5, avgR2: 0.9954 },
  },
  {
    id: 't-012',
    type: 'export',
    timestamp: now - 2 * DAY + 3600000,
    operator: '老叶',
    description: '导出报告 - boundary_review_20260617.xlsx',
    detail: { hash: 'a1b2c3d4e5f6', pointCount: 28 },
  },
  {
    id: 't-013',
    type: 'status_change',
    timestamp: now - 1 * DAY,
    operator: '老叶',
    description: '【处理完成】BSA蛋白拟合通过',
    detail: { materialId: 'mat-002', rSquared: 0.9995 },
  },
  {
    id: 't-014',
    type: 'rename',
    timestamp: now,
    operator: '系统-交接模拟',
    description: '【临时改名】氯化钠标准溶液 → 氯化钠-临时改名(交接用) —— 模拟真实交接场景',
    detail: { materialId: 'mat-003', reason: '试跑复核，模拟名称前后不一致' },
  },
  {
    id: 't-015',
    type: 'filter',
    timestamp: now,
    operator: '系统-交接试跑',
    description: '创建筛选口径"交接试跑-含待处理"（边界最小样本数调整为3，拟合度改为二次）',
    filterSnapshot: mockFilterCriterias[2],
  },
  {
    id: 't-016',
    type: 'handover',
    timestamp: now,
    operator: '老叶 → 接手同事',
    description: '【交接】曲线拟合边界复核工作移交',
    detail: { pendingMaterials: ['mat-003', 'mat-004'], missingNote: 'mat-004缺T0，mat-003边界样本少' },
  },
];

export const mockExports: ExportRecord[] = [
  {
    id: 'exp-001',
    timestamp: now - 2 * DAY,
    operator: '老叶',
    filterCriteriaId: 'f-001',
    dataHash: 'a1b2c3d4e5f6',
    onScreenSnapshot: {
      materialCount: 5,
      totalPoints: 28,
      rSquaredValues: {
        'mat-001': 0.9999,
        'mat-002': 0.9995,
        'mat-003': 0.9968,
        'mat-004': 0.9942,
        'mat-005': 0.9998,
      },
      boundaryWarnings: ['mat-003: 边界样本不足(仅1份)', 'mat-004: 缺低浓度边界T0'],
    },
    fileName: 'boundary_review_20260617.xlsx',
  },
];

export const mockHandoverNote: HandoverNote = {
  materialLocation: '【材料存放位置】\n\n1. 原始学生草稿Excel: /shared/drafts/学生原始数据/\n   - glucose_wang.xlsx (小王)\n   - bsa_li.xlsx (小李)\n   - nacl_zhang.xlsx (小张) ⚠️ 含"氯化钠-临时改名"交接测试\n   - cuso4_chen.xlsx (小陈，缺T0)\n   - phosphate_zhou.xlsx (小周)\n\n2. 参考数据(边界补充): /shared/references/边界参考图谱/\n\n3. 老叶复核笔记(纸质扫描): /shared/reviews/老叶手写笔记_2026Q2.pdf',
  anomalyLocation: '【异常查看位置】\n\n1. 本系统左侧"异常与跳变分析"面板\n   - 红色标记：边界样本不足 / 缺材料\n   - 黄色标记：排序不稳定 / 单位存疑\n   - 紫色标记：材料名称变更历史\n\n2. 重点查看条目:\n   - mat-003 (氯化钠-临时改名): 名称前后不一致 + 边界样本少 + 排序不稳定\n   - mat-004 (硫酸铜): 缺T0低浓度边界点\n   - mat-002 (BSA): S0值存疑(学生草稿标注)\n   - mat-005 (磷酸二氢钾): 历史单位曾被误写为mg',
  reexportGuide: '【重新导出操作指引】\n\n步骤1：顶部筛选栏 → 选择筛选口径（建议使用"默认筛选-全部材料"）\n步骤2：确认当前屏幕数字 → 与下方"屏幕快照"面板对比一致\n步骤3：点击右上角"导出报告"按钮\n步骤4：弹窗中勾选"绑定屏幕快照哈希"（默认勾选，请勿取消）\n步骤5：导出完成后，可在"历史时间线→导出记录"中找到对应条目\n\n* 导出文件名将自动包含日期与哈希校验后缀\n* 可通过 Excel 第一页的"数据校验"Sheet 确认屏幕数字一致性',
  remarks: '【老叶留言】\n\n1. mat-003 那个改名是我让系统做的交接测试，你确认没问题就改回"氯化钠标准溶液"。\n2. mat-004 小陈说下周一补T0，你提醒他一下。\n3. 边界样本最少3份，之前默认设成2了，新筛选我改成3了，你看哪个合适。\n4. 排序不稳定一定要点"查看原始草稿"，别光看警告。\n5. 有问题微信找我，我休假一周但会看手机。',
};
