package report

import (
	"encoding/json"
	"io"
	"os"
	"strings"
	"text/template"

	"github.com/zy1214/pefa/pkg/evidence"
)

type Exporter struct {
	outputFormat OutputFormat
}

type OutputFormat string

const (
	FormatMarkdown OutputFormat = "markdown"
	FormatJSON     OutputFormat = "json"
)

func NewExporter(format OutputFormat) *Exporter {
	return &Exporter{
		outputFormat: format,
	}
}

func (e *Exporter) Export(result *evidence.AnalysisResult, w io.Writer) error {
	switch e.outputFormat {
	case FormatJSON:
		return e.exportJSON(result, w)
	case FormatMarkdown:
		return e.exportMarkdown(result, w)
	default:
		return e.exportMarkdown(result, w)
	}
}

func (e *Exporter) ExportAudit(result *evidence.AuditResult, w io.Writer) error {
	switch e.outputFormat {
	case FormatJSON:
		return e.exportAuditJSON(result, w)
	case FormatMarkdown:
		return e.exportAuditMarkdown(result, w)
	default:
		return e.exportAuditMarkdown(result, w)
	}
}

func (e *Exporter) ExportCompare(results []*evidence.AnalysisResult, w io.Writer) error {
	switch e.outputFormat {
	case FormatJSON:
		return e.exportCompareJSON(results, w)
	case FormatMarkdown:
		return e.exportCompareMarkdown(results, w)
	default:
		return e.exportCompareMarkdown(results, w)
	}
}

func (e *Exporter) exportJSON(result *evidence.AnalysisResult, w io.Writer) error {
	encoder := json.NewEncoder(w)
	encoder.SetIndent("", "  ")
	return encoder.Encode(result)
}

func (e *Exporter) exportAuditJSON(result *evidence.AuditResult, w io.Writer) error {
	encoder := json.NewEncoder(w)
	encoder.SetIndent("", "  ")
	return encoder.Encode(result)
}

func (e *Exporter) exportCompareJSON(results []*evidence.AnalysisResult, w io.Writer) error {
	type CompareOutput struct {
		SessionCount    int                        `json:"session_count"`
		AnalysisResults []*evidence.AnalysisResult `json:"analysis_results"`
	}

	output := CompareOutput{
		SessionCount:    len(results),
		AnalysisResults: results,
	}

	encoder := json.NewEncoder(w)
	encoder.SetIndent("", "  ")
	return encoder.Encode(output)
}

func (e *Exporter) exportMarkdown(result *evidence.AnalysisResult, w io.Writer) error {
	const mdTemplate = `# Performance Analysis Report

## Session Information

| Field | Value |
|-------|-------|
| Session ID | {{.SessionID}} |
| Analysis Time | {{.Timestamp.Format "2006-01-02 15:04:05"}} |
| Duration | {{.Alignment.TotalDuration}} |

## Timeline Alignment

{{if .Alignment.IsAligned}}
✓ All evidence timelines are properly aligned.
{{else}}
⚠ **Timeline alignment issues detected:**

{{range .Alignment.Gaps}}
- **{{.EvidenceType}}**: {{.Reason}} ({{.Duration}})
  Severity: {{.Severity}}
{{end}}
{{end}}

{{if .Alignment.SampleRateWarning}}
⚠ Sample rates vary significantly between evidence types.
{{end}}

## Bottlenecks Detected

{{if .Bottlenecks}}
### Summary

| Severity | Count |
|----------|-------|
| 🔴 Blocker | {{countSeverity .Bottlenecks "blocker"}} |
| 🟠 Major | {{countSeverity .Bottlenecks "major"}} |
| 🟡 Minor | {{countSeverity .Bottlenecks "minor"}} |
| 🔵 Info | {{countSeverity .Bottlenecks "info"}} |

### Detailed Findings

{{range .Bottlenecks}}
#### {{severityIcon .Severity}} [{{.Category}}] {{.Description}}

| Detail | Value |
|--------|-------|
| Severity | {{.Severity}} |
| Timestamp | {{if not .Timestamp.IsZero}}{{.Timestamp.Format "2006-01-02 15:04:05"}}{{else}}N/A{{end}} |
| Duration | {{if gt .Duration 0}}{{.Duration}}{{else}}N/A{{end}} |
| Evidence Sources | {{joinSources .EvidenceSources}} |

{{if .SupportingData}}
**Supporting Data:**
{{range $key, $value := .SupportingData}}
- {{$key}}: {{$value}}
{{end}}
{{end}}

---
{{end}}
{{else}}
No significant bottlenecks detected. The system appears to be operating within normal parameters.
{{end}}

## Recommendations

{{if .Recommendations}}
{{range .Recommendations}}
### {{priorityIcon .Priority}} {{.Title}}

{{.Description}}

**Action Steps:**
{{range .ActionSteps}}
- {{.}}
{{end}}

**Evidence Type:** {{.EvidenceType}}

---
{{end}}
{{else}}
No specific recommendations at this time.
{{end}}

## Executive Summary

{{.Summary}}

---
*Generated by PEFA - Linux Performance Evidence Analysis CLI*
`

	funcMap := template.FuncMap{
		"countSeverity": countSeverity,
		"severityIcon":  severityIcon,
		"priorityIcon":  priorityIcon,
		"joinSources":   joinSources,
	}

	tmpl, err := template.New("report").Funcs(funcMap).Parse(mdTemplate)
	if err != nil {
		return err
	}

	return tmpl.Execute(w, result)
}

func (e *Exporter) exportAuditMarkdown(result *evidence.AuditResult, w io.Writer) error {
	const auditTemplate = `# Evidence Quality Audit Report

## Audit Summary

| Field | Value |
|-------|-------|
| Session ID | {{.SessionID}} |
| Audit Time | {{.Timestamp.Format "2006-01-02 15:04:05"}} |
| **Quality Score** | {{printf "%.1f" .QualityScore}}/100 |

## Evidence Provided

{{if .EvidenceTypes}}
| Type | Status |
|------|--------|
{{range .EvidenceTypes}}| {{.}} | ✅ Provided |
{{end}}
{{else}}
No evidence provided.
{{end}}

## Missing Evidence Types

{{if .MissingTypes}}
| Type | Priority | Description |
|------|----------|-------------|
{{range .MissingTypes}}| {{.}} | {{getMissingPriority .}} | {{getMissingDescription .}} |
{{end}}
{{else}}
All evidence types provided.
{{end}}

## Issues Found

{{if .Issues}}
### Summary

| Severity | Count |
|----------|-------|
| 🔴 Critical | {{countIssueSeverity .Issues "critical"}} |
| 🟠 Warning | {{countIssueSeverity .Issues "warning"}} |
| 🔵 Info | {{countIssueSeverity .Issues "info"}} |

### Detailed Issues

{{range .Issues}}
#### {{issueSeverityIcon .Severity}} [{{.EvidenceType}}] {{.Message}}

**Suggested Fix:** {{.FixSuggestion}}

---
{{end}}
{{else}}
No issues found. Evidence quality is excellent.
{{end}}

## Collection Recommendations

{{if .Recommendations}}
{{range .Recommendations}}
### {{priorityIcon .Priority}} {{.Title}}

{{.Description}}

**Collection Commands:**
{{range .ActionSteps}}
- {{.}}
{{end}}

---
{{end}}
{{else}}
No additional collection needed.
{{end}}

## Quality Score Breakdown

The quality score is calculated based on:
- Evidence completeness (presence of all recommended types)
- Sample count adequacy
- Timestamp availability
- Data format correctness

**Score: {{printf "%.1f" .QualityScore}}/100**

{{if ge .QualityScore 80.0}}
✅ **Excellent**: Evidence is comprehensive and well-structured.
{{else if ge .QualityScore 60.0}}
🟡 **Good**: Evidence is adequate but could be improved.
{{else if ge .QualityScore 40.0}}
🟠 **Fair**: Evidence has significant gaps.
{{else}}
🔴 **Poor**: Evidence is insufficient for meaningful analysis.
{{end}}

---
*Generated by PEFA - Linux Performance Evidence Analysis CLI*
`

	funcMap := template.FuncMap{
		"countIssueSeverity":    countIssueSeverity,
		"issueSeverityIcon":     issueSeverityIcon,
		"priorityIcon":          priorityIcon,
		"getMissingPriority":    getMissingPriority,
		"getMissingDescription": getMissingDescription,
	}

	tmpl, err := template.New("audit").Funcs(funcMap).Parse(auditTemplate)
	if err != nil {
		return err
	}

	return tmpl.Execute(w, result)
}

func (e *Exporter) exportCompareMarkdown(results []*evidence.AnalysisResult, w io.Writer) error {
	const compareTemplate = `# Session Comparison Report

## Overview

| Session | Analysis Time | Duration | Bottlenecks | Recommendations |
|---------|---------------|----------|-------------|-----------------|
{{range .}}| {{.SessionID}} | {{.Timestamp.Format "2006-01-02 15:04"}} | {{.Alignment.TotalDuration}} | {{len .Bottlenecks}} | {{len .Recommendations}} |
{{end}}

## Bottleneck Comparison

### By Category

| Category | {{range $i, $r := .}}Session {{add $i 1}} | {{end}}
|----------|{{range $i, $r := .}}-----------------|{{end}}
| CPU | {{range .}}{{countCategory .Bottlenecks "cpu"}} | {{end}}
| Memory | {{range .}}{{countCategory .Bottlenecks "memory"}} | {{end}}
| I/O | {{range .}}{{countCategory .Bottlenecks "io"}} | {{end}}
| Network | {{range .}}{{countCategory .Bottlenecks "network"}} | {{end}}
| Syscall | {{range .}}{{countCategory .Bottlenecks "syscall"}} | {{end}}

### By Severity

| Severity | {{range $i, $r := .}}Session {{add $i 1}} | {{end}}
|----------|{{range $i, $r := .}}-----------------|{{end}}
| Blocker | {{range .}}{{countSeverity .Bottlenecks "blocker"}} | {{end}}
| Major | {{range .}}{{countSeverity .Bottlenecks "major"}} | {{end}}
| Minor | {{range .}}{{countSeverity .Bottlenecks "minor"}} | {{end}}

## Detailed Comparison

{{range $idx, $result := .}}
---

### Session {{add $idx 1}}: {{$result.SessionID}}

{{$result.Summary}}

{{end}}

## Recommendations Summary

{{if hasBlocking .}}
🔴 **Critical findings**: One or more sessions have blocker-level bottlenecks.

{{end}}
## Trend Analysis

{{if gt (len .) 1}}
Compare the sessions for patterns:
- Look for recurring bottlenecks across sessions
- Identify improvements or regressions
- Correlate with system changes or load patterns
{{else}}
Add more sessions to enable meaningful trend analysis.
{{end}}

---
*Generated by PEFA - Linux Performance Evidence Analysis CLI*
`

	funcMap := template.FuncMap{
		"add":           add,
		"countCategory": countCategory,
		"countSeverity": countSeverity,
		"hasBlocking":   hasBlocking,
		"priorityIcon":  priorityIcon,
	}

	tmpl, err := template.New("compare").Funcs(funcMap).Parse(compareTemplate)
	if err != nil {
		return err
	}

	return tmpl.Execute(w, results)
}

func countSeverity(bottlenecks []evidence.Bottleneck, severity string) int {
	count := 0
	for _, b := range bottlenecks {
		if string(b.Severity) == severity {
			count++
		}
	}
	return count
}

func countCategory(bottlenecks []evidence.Bottleneck, category string) int {
	count := 0
	for _, b := range bottlenecks {
		if string(b.Category) == category {
			count++
		}
	}
	return count
}

func countIssueSeverity(issues []evidence.AuditIssue, severity string) int {
	count := 0
	for _, i := range issues {
		if string(i.Severity) == severity {
			count++
		}
	}
	return count
}

func severityIcon(s evidence.BottleneckSeverity) string {
	switch s {
	case evidence.SeverityBlocker:
		return "🔴"
	case evidence.SeverityMajor:
		return "🟠"
	case evidence.SeverityMinor:
		return "🟡"
	case evidence.SeverityInfo:
		return "🔵"
	default:
		return "⚪"
	}
}

func issueSeverityIcon(s evidence.IssueSeverity) string {
	switch s {
	case evidence.IssueCritical:
		return "🔴"
	case evidence.IssueWarning:
		return "🟠"
	case evidence.IssueInfo:
		return "🔵"
	default:
		return "⚪"
	}
}

func priorityIcon(p evidence.RecommendationPriority) string {
	switch p {
	case evidence.PriorityImmediate:
		return "🔴"
	case evidence.PriorityHigh:
		return "🟠"
	case evidence.PriorityMedium:
		return "🟡"
	case evidence.PriorityLow:
		return "🔵"
	default:
		return "⚪"
	}
}

func joinSources(sources []evidence.EvidenceType) string {
	strs := make([]string, len(sources))
	for i, s := range sources {
		strs[i] = string(s)
	}
	return strings.Join(strs, ", ")
}

func add(a, b int) int {
	return a + b
}

func hasBlocking(results []*evidence.AnalysisResult) bool {
	for _, r := range results {
		for _, b := range r.Bottlenecks {
			if b.Severity == evidence.SeverityBlocker {
				return true
			}
		}
	}
	return false
}

func getMissingPriority(et evidence.EvidenceType) string {
	switch et {
	case evidence.TypeTop, evidence.TypeVmstat, evidence.TypeIostat:
		return "High"
	case evidence.TypeSs, evidence.TypeStrace:
		return "Medium"
	default:
		return "Low"
	}
}

func getMissingDescription(et evidence.EvidenceType) string {
	switch et {
	case evidence.TypeTop:
		return "Process-level CPU/memory usage"
	case evidence.TypeVmstat:
		return "System-wide CPU/memory/I/O trends"
	case evidence.TypeIostat:
		return "Device-level I/O statistics"
	case evidence.TypeSs:
		return "Network socket states"
	case evidence.TypeStrace:
		return "System call tracing"
	case evidence.TypePerfScript:
		return "CPU profiling call stacks"
	case evidence.TypeFoldedStack:
		return "Flamegraph input data"
	default:
		return "Additional evidence"
	}
}

func ExportToFile(result *evidence.AnalysisResult, filename string, format OutputFormat) error {
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	exporter := NewExporter(format)
	return exporter.Export(result, f)
}

func ExportAuditToFile(result *evidence.AuditResult, filename string, format OutputFormat) error {
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	exporter := NewExporter(format)
	return exporter.ExportAudit(result, f)
}

func ExportCompareToFile(results []*evidence.AnalysisResult, filename string, format OutputFormat) error {
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	exporter := NewExporter(format)
	return exporter.ExportCompare(results, f)
}
