from enum import Enum


class AccountStatus(str, Enum):
    ACTIVE = "ACTIVE"
    PAID_OFF = "PAID_OFF"
    EXTENDED = "EXTENDED"
    OVERDUE = "OVERDUE"
    FROZEN = "FROZEN"
    CLOSED = "CLOSED"


class ApplicationStatus(str, Enum):
    PENDING = "PENDING"
    FIRST_APPROVED = "FIRST_APPROVED"
    FINAL_APPROVED = "FINAL_APPROVED"
    EXECUTING = "EXECUTING"
    EXECUTED = "EXECUTED"
    EXECUTE_FAILED = "EXECUTE_FAILED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class RepaymentPlanStatus(str, Enum):
    ACTIVE = "ACTIVE"
    HISTORICAL = "HISTORICAL"
    REPLACED = "REPLACED"
    CANCELLED = "CANCELLED"


class InstallmentStatus(str, Enum):
    PENDING = "PENDING"
    PARTIAL = "PARTIAL"
    PAID = "PAID"
    OVERDUE = "OVERDUE"
    WRITTEN_OFF = "WRITTEN_OFF"


class ApprovalStage(str, Enum):
    FIRST_APPROVAL = "FIRST_APPROVAL"
    FINAL_APPROVAL = "FINAL_APPROVAL"
    REJECTION = "REJECTION"
    CANCELLATION = "CANCELLATION"
    EXECUTION = "EXECUTION"


class OperationType(str, Enum):
    SUBMIT = "SUBMIT"
    FIRST_APPROVE = "FIRST_APPROVE"
    FINAL_APPROVE = "FINAL_APPROVE"
    REJECT = "REJECT"
    CANCEL = "CANCEL"
    EXECUTE = "EXECUTE"
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    RECALCULATE = "RECALCULATE"
    SETTLE = "SETTLE"


class BusinessType(str, Enum):
    LOAN_ACCOUNT = "LOAN_ACCOUNT"
    REPAYMENT_PLAN = "REPAYMENT_PLAN"
    EXTENSION_APPLICATION = "EXTENSION_APPLICATION"
    PENALTY = "PENALTY"
    CREDIT_LIMIT = "CREDIT_LIMIT"
    APPROVAL = "APPROVAL"
    RECONCILIATION = "RECONCILIATION"
    TASK = "TASK"


class SourceType(str, Enum):
    ORIGINAL = "ORIGINAL"
    EXTENSION = "EXTENSION"
    MANUAL_ADJUST = "MANUAL_ADJUST"
    RECALCULATION = "RECALCULATION"


class TaskStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    RETRYING = "RETRYING"
    MAX_RETRY_EXCEEDED = "MAX_RETRY_EXCEEDED"
    CANCELLED = "CANCELLED"


class TaskType(str, Enum):
    EXECUTE_EXTENSION = "EXECUTE_EXTENSION"
    RECALCULATE_PLAN = "RECALCULATE_PLAN"
    RECALCULATE_PENALTY = "RECALCULATE_PENALTY"
    RELEASE_LIMIT = "RELEASE_LIMIT"
    RECONCILIATION_EXPORT = "RECONCILIATION_EXPORT"
    AUDIT_LOG_SYNC = "AUDIT_LOG_SYNC"


class OperationResult(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    PENDING = "PENDING"
