-- MQ Dead Letter Review System Schema
-- For MySQL 8.0+

CREATE TABLE IF NOT EXISTS message_trackings (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tracking_id VARCHAR(64) NOT NULL UNIQUE,
    message_id VARCHAR(64) NOT NULL,
    topic VARCHAR(128) NOT NULL,
    tag VARCHAR(64),
    `keys` VARCHAR(256),
    producer_group VARCHAR(128),
    consumer_group VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'PRODUCED',
    previous_status VARCHAR(32),
    retry_count INT DEFAULT 0,
    max_retry_count INT DEFAULT 3,
    body LONGTEXT,
    properties LONGTEXT,
    error_message TEXT,
    error_stack LONGTEXT,
    latest_error TEXT,
    latest_error_at DATETIME,
    produced_at DATETIME,
    sent_at DATETIME,
    consumed_at DATETIME,
    dead_letter_at DATETIME,
    replayed_at DATETIME,
    processed_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_message_id (message_id),
    INDEX idx_status (status),
    INDEX idx_topic (topic),
    INDEX idx_consumer_group (consumer_group),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dead_letter_messages (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tracking_id VARCHAR(64) NOT NULL UNIQUE,
    message_id VARCHAR(64) NOT NULL,
    topic VARCHAR(128) NOT NULL,
    tag VARCHAR(64),
    `keys` VARCHAR(256),
    consumer_group VARCHAR(128),
    body LONGTEXT,
    properties LONGTEXT,
    error_message TEXT,
    error_stack LONGTEXT,
    total_retry_count INT DEFAULT 0,
    replay_count INT DEFAULT 0,
    max_replay_count INT DEFAULT 5,
    origin_message_id VARCHAR(64),
    origin_topic VARCHAR(128),
    replay_status VARCHAR(32) DEFAULT 'DEAD_LETTER',
    last_replay_at DATETIME,
    dead_letter_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_message_id (message_id),
    INDEX idx_tracking_id (tracking_id),
    INDEX idx_topic (topic),
    INDEX idx_consumer_group (consumer_group),
    INDEX idx_replay_status (replay_status),
    INDEX idx_dead_letter_at (dead_letter_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS message_event_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tracking_id VARCHAR(64) NOT NULL,
    message_id VARCHAR(64),
    event_name VARCHAR(64) NOT NULL,
    from_status VARCHAR(32),
    to_status VARCHAR(32),
    operation VARCHAR(64),
    operator_id VARCHAR(64),
    description TEXT,
    request_body LONGTEXT,
    response_body LONGTEXT,
    error_info LONGTEXT,
    success BOOLEAN DEFAULT TRUE,
    execution_time BIGINT DEFAULT 0,
    ip_address VARCHAR(64),
    user_agent VARCHAR(512),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_tracking_id (tracking_id),
    INDEX idx_message_id (message_id),
    INDEX idx_event_name (event_name),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS replay_requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL UNIQUE,
    tracking_ids LONGTEXT,
    dead_letter_ids LONGTEXT,
    consumer_group VARCHAR(128),
    topic VARCHAR(128),
    tag VARCHAR(64),
    dry_run BOOLEAN DEFAULT FALSE,
    max_batch_size INT DEFAULT 100,
    concurrency INT DEFAULT 5,
    timeout INT DEFAULT 300,
    status VARCHAR(32) DEFAULT 'PENDING',
    success_count INT DEFAULT 0,
    failed_count INT DEFAULT 0,
    total_count INT DEFAULT 0,
    operator_id VARCHAR(64),
    reason TEXT,
    start_time DATETIME,
    end_time DATETIME,
    error_message TEXT,
    report_content LONGTEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_request_id (request_id),
    INDEX idx_status (status),
    INDEX idx_operator_id (operator_id),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS replay_tasks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL,
    tracking_id VARCHAR(64) NOT NULL,
    dead_letter_id BIGINT,
    message_id VARCHAR(64),
    sequence INT DEFAULT 0,
    status VARCHAR(32) DEFAULT 'PENDING',
    result TEXT,
    error_message TEXT,
    execution_time BIGINT DEFAULT 0,
    start_time DATETIME,
    end_time DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_request_id (request_id),
    INDEX idx_tracking_id (tracking_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
