with open('backend/services/selfCheck.js', 'w') as f:
    f.write('var dataStore = require("./dataStore");\n')
    f.write('var crypto = require("crypto");\n')
    f.write('\n')
    f.write('var STATUS = {\n')
    f.write('  PENDING: "pending",\n')
    f.write('  NORMAL: "normal",\n')
    f.write('  DUPLICATE_USER: "duplicate_user",\n')
    f.write('  NEEDS_REVIEW: "needs_review",\n')
    f.write('  MERGED: "merged",\n')
    f.write('  EXCLUDED: "excluded"\n')
    f.write('};\n')
    f.write('\n')
    f.write('var STATUS_LABELS = {};\n')
    f.write('STATUS_LABELS[STATUS.PENDING] = "待处理";\n')
    f.write('STATUS_LABELS[STATUS.NORMAL] = "正常";\n')
    f.write('STATUS_LABELS[STATUS.DUPLICATE_USER] = "同一用户重复反馈";\n')
    f.write('STATUS_LABELS[STATUS.NEEDS_REVIEW] = "待标注负责人复核";\n')
    f.write('STATUS_LABELS[STATUS.MERGED] = "已归并";\n')
    f.write('STATUS_LABELS[STATUS.EXCLUDED] = "已排除";\n')
    f.write('\n')
    f.write('var IMPORT_SOURCE_LABELS = {};\n')
    f.write('IMPORT_SOURCE_LABELS["initial"] = "首次导入";\n')
    f.write('IMPORT_SOURCE_LABELS["incremental"] = "增量导入";\n')
    f.write('IMPORT_SOURCE_LABELS["manual"] = "人工补录";\n')
print("Part 1 done")
