var fs = require('fs');
var path = require('path');

var content = [
  'var express = require(\'express\');',
  'var router = express.Router();',
  'var multer = require(\'multer\');',
  'var csv = require(\'csv-parser\');',
  'var fs = require(\'fs\');',
  'var json2csv = require(\'json2csv\');',
  'var Parser = json2csv.Parser;',
  '',
  'var dataStore = require(\'../services/dataStore\');',
  'var selfCheck = require(\'../services/selfCheck\');',
  '',
  'var readBatches = dataStore.readBatches;',
  'var writeBatches = dataStore.writeBatches;',
  'var readRecords = dataStore.readRecords;',
  'var writeRecords = dataStore.writeRecords;',
  'var generateId = dataStore.generateId;',
  '',
  'var STATUS = selfCheck.STATUS;',
  'var STATUS_LABELS = selfCheck.STATUS_LABELS;',
  'var IMPORT_SOURCE_LABELS = selfCheck.IMPORT_SOURCE_LABELS;',
  'var buildRecordFingerprint = selfCheck.buildRecordFingerprint;',
  'var calcIncrementalImportDiff = selfCheck.calcIncrementalImportDiff;',
  'var runFullCheck = selfCheck.runFullCheck;',
  'var applyAutoStatus = selfCheck.applyAutoStatus;',
  '',
  'var upload = multer({ dest: \'/tmp/\' });',
  '',
  'function parseCsvFile(filePath) {',
  '  return new Promise(function(resolve, reject) {',
  '    var rows = [];',
  '    fs.createReadStream(filePath)',
  '      .pipe(csv())',
  '      .on(\'data\', function(row) {',
  '        rows.push(row);',
  '      })',
  '      .on(\'end\', function() {',
  '        resolve(rows);',
  '      })',
  '      .on(\'error\', function(err) {',
  '        reject(err);',
  '      });',
  '  });',
  '}',
  '',
  'function normalizeRow(row) {',
  '  return {',
  '    question: row.question || row.问题 || row.questionText || \'\',',
  '    user_id: row.user_id || row.用户ID || row.userId || \'\',',
  '    user_name: row.user_name || row.用户名 || row.userName || \'\',',
  '    feedback_time: row.feedback_time || row.反馈时间 || row.feedbackTime || \'\'',
  '  };',
  '}',
  '',
  'function createRecordFromRow(row, batchId, importSource, importLineNumber, originalLineNumber) {',
  '  var normalized = normalizeRow(row);',
  '  var now = new Date().toISOString();',
  '  return {',
  '    id: generateId(),',
  '    batchId: batchId,',
  '    originalLineNumber: originalLineNumber,',
  '    importLineNumber: importLineNumber,',
  '    importSource: importSource,',
  '    importFingerprint: buildRecordFingerprint(normalized),',
  '    questionText: normalized.question,',
  '    userId: normalized.user_id,',
  '    userName: normalized.user_name,',
  '    feedbackTime: normalized.feedback_time,',
  '    originalData: row,',
  '    status: STATUS.PENDING,',
  '    statusUpdatedAt: now,',
  '    statusUpdatedBy: \'system_import\',',
  '    manualChanges: [],',
  '    mergedIntoId: null,',
  '    mergedFromIds: [],',
  '    annotatorComment: \'\',',
  '    reviewComment: \'\'',
  '  };',
  '}',
  '',
  'router.get(\'/\', function(req, res) {',
  '  try {',
  '    var batches = readBatches();',
  '    var records = readRecords();',
  '    var result = batches.map(function(batch) {',
  '      var batchRecords = records.filter(function(r) { return r.batchId === batch.id; });',
  '      return {',
  '        id: batch.id,',
  '        name: batch.name,',
  '        createdAt: batch.createdAt,',
  '        createdBy: batch.createdBy,',
  '        fileName: batch.fileName,',
  '        rowCount: batch.rowCount,',
  '        importNotes: batch.importNotes,',
  '        recordCount: batchRecords.length',
  '      };',
  '    });',
  '    res.json(result);',
  '  } catch (err) {',
  '    res.status(500).json({ error: err.message });',
  '  }',
  '});',
  '',
  'router.post(\'/\', upload.single(\'file\'), async function(req, res) {',
  '  try {',
  '    var name = (req.body.name || \'\').trim();',
  '    if (!name) {',
  '      return res.status(400).json({ error: \'批次名称不能为空\' });',
  '    }',
  '    if (!req.file) {',
  '      return res.status(400).json({ error: \'请上传CSV文件\' });',
  '    }',
  '',
  '    var rows = await parseCsvFile(req.file.path);',
  '    if (rows.length === 0) {',
  '      return res.status(400).json({ error: \'CSV文件为空或格式错误\' });',
  '    }',
  '',
  '    var batches = readBatches();',
  '    var records = readRecords();',
  '    var existingBatch = batches.find(function(b) { return b.name === name; });',
  '    var now = new Date().toISOString();',
  '',
  '    if (existingBatch) {',
  '      var incrementalDiff = calcIncrementalImportDiff(existingBatch.id, records, rows);',
  '      var reusedCount = incrementalDiff.reusedCount;',
  '      var newCount = incrementalDiff.newCount;',
  '      var newRecordsData = incrementalDiff.newRecords;',
  '',
  '      var newRecords = newRecordsData.map(function(item) {',
  '        return createRecordFromRow(',
  '          item.row,',
  '          existingBatch.id,',
  '          \'incremental\',',
  '          item.rowIndex + 2,',
  '          item.rowIndex + 2',
  '        );',
  '      });',
  '',
  '      var allRecords = records.concat(newRecords);',
  '      allRecords = applyAutoStatus(allRecords, existingBatch.id);',
  '      writeRecords(allRecords);',
  '',
  '      existingBatch.rowCount = (existingBatch.rowCount || 0) + newCount;',
  '      existingBatch.updatedAt = now;',
  '      writeBatches(batches);',
  '',
  '      var checkResult = runFullCheck(existingBatch.id);',
  '      var batchRecords = allRecords.filter(function(r) { return r.batchId === existingBatch.id; });',
  '',
  '      return res.json({',
  '        batch: existingBatch,',
  '        records: batchRecords,',
  '        recordCount: batchRecords.length,',
  '        incrementalDiff: {',
  '          reusedCount: reusedCount,',
  '          newCount: newCount',
  '        },',
  '        checkResult: checkResult',
  '      });',
  '    }',
  '',
  '    var batchId = generateId();',
  '    var batch = {',
  '      id: batchId,',
  '      name: name,',
  '      createdAt: now,',
  '      createdBy: req.body.createdBy || \'system\',',
  '      fileName: req.file.originalname,',
  '      rowCount: rows.length,',
  '      importNotes: req.body.importNotes || \'\'',
  '    };',
  '',
  '    var initialRecords = rows.map(function(row, idx) {',
  '      return createRecordFromRow(row, batchId, \'initial\', idx + 2, idx + 2);',
  '    });',
  '',
  '    var allRecordsNew = records.concat(initialRecords);',
  '    allRecordsNew = applyAutoStatus(allRecordsNew, batchId);',
  '    writeRecords(allRecordsNew);',
  '    batches.push(batch);',
  '    writeBatches(batches);',
  '',
  '    var checkResultNew = runFullCheck(batchId);',
  '',
  '    res.json({',
  '      batch: batch,',
  '      records: initialRecords,',
  '      recordCount: initialRecords.length,',
  '      incrementalDiff: {',
  '        reusedCount: 0,',
  '        newCount: initialRecords.length',
  '      },',
  '      checkResult: checkResultNew',
  '    });',
  '  } catch (err) {',
  '    res.status(500).json({ error: err.message });',
  '  }',
  '});',
  '',
  'router.get(\'/:batchId\', function(req, res) {',
  '  try {',
  '    var batchId = req.params.batchId;',
  '    var batches = readBatches();',
  '    var batch = batches.find(function(b) { return b.id === batchId; });',
  '    if (!batch) {',
  '      return res.status(404).json({ error: \'批次不存在\' });',
  '    }',
  '    var records = readRecords();',
  '    var batchRecords = records.filter(function(r) { return r.batchId === batchId; });',
  '    var checkResult = runFullCheck(batchId);',
  '',
  '    res.json({',
  '      id: batch.id,',
  '      name: batch.name,',
  '      createdAt: batch.createdAt,',
  '      createdBy: batch.createdBy,',
  '      fileName: batch.fileName,',
  '      rowCount: batch.rowCount,',
  '      importNotes: batch.importNotes,',
  '      records: batchRecords,',
  '      checkResult: checkResult',
  '    });',
  '  } catch (err) {',
  '    res.status(500).json({ error: err.message });',
  '  }',
  '});',
  '',
  'router.put(\'/:batchId/rename\', function(req, res) {',
  '  try {',
  '    var batchId = req.params.batchId;',
  '    var newName = (req.body.name || \'\').trim();',
  '    if (!newName) {',
  '      return res.status(400).json({ error: \'批次名称不能为空\' });',
  '    }',
  '',
  '    var batches = readBatches();',
  '    var batch = batches.find(function(b) { return b.id === batchId; });',
  '    if (!batch) {',
  '      return res.status(404).json({ error: \'批次不存在\' });',
  '    }',
  '',
  '    var duplicate = batches.find(function(b) {',
  '      return b.name === newName && b.id !== batchId;',
  '    });',
  '    if (duplicate) {',
  '      return res.status(400).json({ error: \'已存在同名批次\' });',
  '    }',
  '',
  '    batch.name = newName;',
  '    batch.updatedAt = new Date().toISOString();',
  '    writeBatches(batches);',
  '',
  '    res.json(batch);',
  '  } catch (err) {',
  '    res.status(500).json({ error: err.message });',
  '  }',
  '});',
  '',
  'router.post(\'/:batchId/notes\', function(req, res) {',
  '  try {',
  '    var batchId = req.params.batchId;',
  '    var importNotes = req.body.importNotes || \'\';',
  '',
  '    var batches = readBatches();',
  '    var batch = batches.find(function(b) { return b.id === batchId; });',
  '    if (!batch) {',
  '      return res.status(404).json({ error: \'批次不存在\' });',
  '    }',
  '',
  '    batch.importNotes = importNotes;',
  '    batch.updatedAt = new Date().toISOString();',
  '    writeBatches(batches);',
  '',
  '    res.json({ success: true });',
  '  } catch (err) {',
  '    res.status(500).json({ error: err.message });',
  '  }',
  '});',
  '',
  'router.get(\'/:batchId/check\', function(req, res) {',
  '  try {',
  '    var batchId = req.params.batchId;',
  '    var records = readRecords();',
  '    var updatedRecords = applyAutoStatus(records, batchId);',
  '    writeRecords(updatedRecords);',
  '',
  '    var result = runFullCheck(batchId);',
  '    res.json(result);',
  '  } catch (err) {',
  '    res.status(500).json({ error: err.message });',
  '  }',
  '});',
  '',
  'router.put(\'/:batchId/records/:recordId\', function(req, res) {',
  '  try {',
  '    var batchId = req.params.batchId;',
  '    var recordId = req.params.recordId;',
  '    var newStatus = req.body.status;',
  '    var operator = req.body.operator || \'unknown\';',
  '    var reason = req.body.reason || \'\';',
  '    var annotatorComment = req.body.annotatorComment;',
  '    var reviewComment = req.body.reviewComment;',
  '    var mergedIntoId = req.body.mergedIntoId;',
  '',
  '    var records = readRecords();',
  '    var recordIdx = records.findIndex(function(r) { return r.id === recordId && r.batchId === batchId; });',
  '    if (recordIdx === -1) {',
  '      return res.status(404).json({ error: \'记录不存在\' });',
  '    }',
  '',
  '    var record = records[recordIdx];',
  '    var now = new Date().toISOString();',
  '    var changes = [];',
  '',
  '    if (newStatus && newStatus !== record.status) {',
  '      changes.push({',
  '        field: \'status\',',
  '        oldValue: record.status,',
  '        newValue: newStatus,',
  '        changedAt: now,',
  '        changedBy: operator,',
  '        reason: reason',
  '      });',
  '      record.status = newStatus;',
  '      record.statusUpdatedAt = now;',
  '      record.statusUpdatedBy = operator;',
  '    }',
  '',
  '    if (annotatorComment !== undefined && annotatorComment !== record.annotatorComment) {',
  '      changes.push({',
  '        field: \'annotatorComment\',',
  '        oldValue: record.annotatorComment,',
  '        newValue: annotatorComment,',
  '        changedAt: now,',
  '        changedBy: operator,',
  '        reason: reason',
  '      });',
  '      record.annotatorComment = annotatorComment;',
  '    }',
  '',
  '    if (reviewComment !== undefined && reviewComment !== record.reviewComment) {',
  '      changes.push({',
  '        field: \'reviewComment\',',
  '        oldValue: record.reviewComment,',
  '        newValue: reviewComment,',
  '        changedAt: now,',
  '        changedBy: operator,',
  '        reason: reason',
  '      });',
  '      record.reviewComment = reviewComment;',
  '    }',
  '',
  '    if (mergedIntoId !== undefined && mergedIntoId !== record.mergedIntoId) {',
  '      changes.push({',
  '        field: \'mergedIntoId\',',
  '        oldValue: record.mergedIntoId,',
  '        newValue: mergedIntoId,',
  '        changedAt: now,',
  '        changedBy: operator,',
  '        reason: reason',
  '      });',
  '      record.mergedIntoId = mergedIntoId;',
  '    }',
  '',
  '    if (changes.length > 0) {',
  '      record.manualChanges = (record.manualChanges || []).concat(changes);',
  '    }',
  '',
  '    records[recordIdx] = record;',
  '    writeRecords(records);',
  '',
  '    res.json(record);',
  '  } catch (err) {',
  '    res.status(500).json({ error: err.message });',
  '  }',
  '});',
  '',
  'router.get(\'/:batchId/export\', function(req, res) {',
  '  try {',
  '    var batchId = req.params.batchId;',
  '    var format = req.query.format || \'csv\';',
  '',
  '    var batches = readBatches();',
  '    var batch = batches.find(function(b) { return b.id === batchId; });',
  '    if (!batch) {',
  '      return res.status(404).json({ error: \'批次不存在\' });',
  '    }',
  '',
  '    var records = readRecords();',
  '    var batchRecords = records.filter(function(r) { return r.batchId === batchId; });',
  '',
  '    var exportData = batchRecords.map(function(r) {',
  '      return {',
  '        \'原始行号\': r.originalLineNumber || \'\',',
  '        \'导入来源\': IMPORT_SOURCE_LABELS[r.importSource] || r.importSource || \'\',',
  '        \'本次导入行号\': r.importLineNumber || r.originalLineNumber || \'\',',
  '        \'用户ID\': r.userId || \'\',',
  '        \'用户名\': r.userName || \'\',',
  '        \'问题文本\': r.questionText || \'\',',
  '        \'反馈时间\': r.feedbackTime || \'\',',
  '        \'当前状态\': STATUS_LABELS[r.status] || r.status || \'\',',
  '        \'标注员留言\': r.annotatorComment || \'\',',
  '        \'复核意见\': r.reviewComment || \'\',',
  '        \'是否已归并\': r.status === STATUS.MERGED ? \'是\' : \'否\',',
  '        \'归并目标ID\': r.mergedIntoId || \'\',',
  '        \'状态更新时间\': r.statusUpdatedAt || \'\',',
  '        \'状态更新人\': r.statusUpdatedBy || \'\'',
  '      };',
  '    });',
  '',
  '    if (format === \'csv\') {',
  '      var fields = [',
  '        \'原始行号\', \'导入来源\', \'本次导入行号\', \'用户ID\', \'用户名\',',
  '        \'问题文本\', \'反馈时间\', \'当前状态\', \'标注员留言\', \'复核意见\',',
  '        \'是否已归并\', \'归并目标ID\', \'状态更新时间\', \'状态更新人\'',
  '      ];',
  '      var json2csvParser = new Parser({ fields: fields });',
  '      var csvContent = json2csvParser.parse(exportData);',
  '      var fileName = \'批次导出_\' + batch.name + \'_\' + new Date().toISOString().slice(0, 10) + \'.csv\';',
  '      var encodedFileName = encodeURIComponent(fileName);',
  '',
  '      res.setHeader(\'Content-Type\', \'text/csv; charset=utf-8\');',
  '      res.setHeader(\'Content-Disposition\', "attachment; filename*=UTF-8\'\'" + encodedFileName);',
  '      res.write(\'\\uFEFF\');',
  '      res.end(csvContent);',
  '    } else {',
  '      res.json(exportData);',
  '    }',
  '  } catch (err) {',
  '    res.status(500).json({ error: err.message });',
  '  }',
  '});',
  '',
  'module.exports = router;',
  ''
].join('\n');

var targetPath = path.join(__dirname, 'backend/routes/batches.js');
fs.writeFileSync(targetPath, content, 'utf8');
console.log('Written successfully to ' + targetPath);
console.log('Total lines: ' + content.split('\n').length);
