var fs = require('fs');
var path = require('path');

var baseDir = '/Users/lzy/pro/solo/workspaces/zy72517';

var selfCheckContent = [
'var dataStore = require(\'./dataStore\');',
'var readRecords = dataStore.readRecords;',
'var readBatches = dataStore.readBatches;',
'',
'var STATUS = {',
'  PENDING: \'pending\',',
'  NORMAL: \'normal\',',
'  DUPLICATE_USER: \'duplicate_user\',',
'  NEEDS_REVIEW: \'needs_review\',',
'  MERGED: \'merged\',',
'  EXCLUDED: \'excluded\'',
'};',
'',
'var STATUS_LABELS = {};',
'STATUS_LABELS[STATUS.PENDING] = \'待处理\';',
'STATUS_LABELS[STATUS.NORMAL] = \'正常\';',
'STATUS_LABELS[STATUS.DUPLICATE_USER] = \'同一用户重复反馈\';',
'STATUS_LABELS[STATUS.NEEDS_REVIEW] = \'待标注负责人复核\';',
'STATUS_LABELS[STATUS.MERGED] = \'已归并\';',
'STATUS_LABELS[STATUS.EXCLUDED] = \'已排除\';',
'',
'var IMPORT_SOURCE_LABELS = {',
'  initial: \'首次导入\',',
'  incremental: \'增量导入\',',
'  manual: \'人工补录\'',
'};',
'',
'function buildRecordFingerprint(row) {',
'  var question = (row.question || row.问题 || row.questionText || \'\').trim().toLowerCase();',
'  var userId = (row.user_id || row.用户ID || row.userId || \'\').trim();',
'  var feedbackTime = (row.feedback_time || row.反馈时间 || row.feedbackTime || \'\').trim();',
'  return userId + \'__\' + question + \'__\' + feedbackTime;',
'}',
'',
'function checkDuplicateImport(batchId, records, importedRows) {',
'  var batchRecords = records.filter(function(r) { return r.batchId === batchId; });',
'  var fingerprintMap = {};',
'',
'  batchRecords.forEach(function(record) {',
'    var fp = record.importFingerprint || buildRecordFingerprint(record);',
'    fingerprintMap[fp] = record;',
'  });',
'',
'  var issues = [];',
'  importedRows.forEach(function(row, idx) {',
'    var fingerprint = buildRecordFingerprint(row);',
'    var existing = fingerprintMap[fingerprint];',
'    if (existing) {',
'      issues.push({',
'        type: \'duplicate_import\',',
'        severity: \'warning\',',
'        originalLineNumber: idx + 2,',
'        questionText: row.question || row.问题,',
'        userId: row.user_id || row.用户ID,',
'        fingerprint: fingerprint,',
'        message: \'第\' + (idx + 2) + \'行与已有记录重复（用户+问题+反馈时间完全一致）\',',
'        existingRecordId: existing.id,',
'        existingOriginalLine: existing.originalLineNumber',
'      });',
'    }',
'  });',
'  return issues;',
'}',
'',
'function calcIncrementalImportDiff(batchId, existingRecords, newRows) {',
'  var batchRecords = existingRecords.filter(function(r) { return r.batchId === batchId; });',
'  var existingFingerprints = {};',
'',
'  batchRecords.forEach(function(record) {',
'    var fp = record.importFingerprint || buildRecordFingerprint(record);',
'    existingFingerprints[fp] = record;',
'  });',
'',
'  var reusedRecords = [];',
'  var newRecordsToAdd = [];',
'  var duplicateUserRecords = [];',
'',
'  newRows.forEach(function(row, idx) {',
'    var fingerprint = buildRecordFingerprint(row);',
'    if (existingFingerprints[fingerprint]) {',
'      reusedRecords.push({',
'        row: row,',
'        rowIndex: idx,',
'        existingRecord: existingFingerprints[fingerprint]',
'      });',
'    } else {',
'      newRecordsToAdd.push({',
'        row: row,',
'        rowIndex: idx,',
'        fingerprint: fingerprint',
'      });',
'    }',
'  });',
'',
'  return {',
'    reusedCount: reusedRecords.length,',
'    newCount: newRecordsToAdd.length,',
'    reusedRecords: reusedRecords,',
'    newRecords: newRecordsToAdd,',
'    duplicateUserRecords: duplicateUserRecords',
'  };',
'}',
'',
'function checkDuplicateUserFeedback(records, batchId) {',
'  var batchRecords = records.filter(function(r) { return r.batchId === batchId; });',
'  var userQuestionMap = {};',
'  batchRecords.forEach(function(record) {',
'    var key = record.userId + \'__\' + record.questionText.trim().toLowerCase();',
'    if (!userQuestionMap[key]) {',
'      userQuestionMap[key] = [];',
'    }',
'    userQuestionMap[key].push(record);',
'  });',
'',
'  var issues = [];',
'  Object.keys(userQuestionMap).forEach(function(key) {',
'    var recordsWithSame = userQuestionMap[key];',
'    if (recordsWithSame.length > 1) {',
'      recordsWithSame.slice(1).forEach(function(record) {',
'        if (record.status !== STATUS.MERGED && record.status !== STATUS.EXCLUDED) {',
'          issues.push({',
'            type: \'duplicate_user\',',
'            severity: \'warning\',',
'            recordId: record.id,',
'            questionText: record.questionText,',
'            userId: record.userId,',
'            message: \'用户 \' + record.userId + \' 同一问题重复反馈 \' + recordsWithSame.length + \' 条\',',
'            originalLineNumbers: recordsWithSame.map(function(r) { return r.originalLineNumber; })',
'          });',
'        }',
'      });',
'    }',
'  });',
'  return issues;',
'}',
'',
'function checkMergeConsistency(records, batchId) {',
'  var batchRecords = records.filter(function(r) { return r.batchId === batchId; });',
'  var recordIdMap = {};',
'  batchRecords.forEach(function(record) {',
'    recordIdMap[record.id] = record;',
'  });',
'',
'  var issues = [];',
'  batchRecords.forEach(function(record) {',
'    if (record.status === STATUS.MERGED && record.mergedIntoId) {',
'      var target = recordIdMap[record.mergedIntoId];',
'      if (!target) {',
'        issues.push({',
'          type: \'merge_target_missing\',',
'          severity: \'error\',',
'          recordId: record.id,',
'          questionText: record.questionText,',
'          message: \'记录已归并但目标记录不存在，归并目标ID：\' + record.mergedIntoId',
'        });',
'      } else if (target.status === STATUS.MERGED) {',
'        issues.push({',
'          type: \'merge_target_merged\',',
'          severity: \'warning\',',
'          recordId: record.id,',
'          questionText: record.questionText,',
'          message: \'归并目标本身也被归并了，目标ID：\' + record.mergedIntoId',
'        });',
'      }',
'    }',
'  });',
'  return issues;',
'}',
'',
'function checkExportConsistency(records, batchId) {',
'  var batchRecords = records.filter(function(r) { return r.batchId === batchId; });',
'  var displayCount = batchRecords.length;',
'',
'  var exportableRecords = batchRecords.filter(function(r) {',
'    return true;',
'  });',
'',
'  var exportCount = exportableRecords.length;',
'',
'  var hasWarning = displayCount !== exportCount;',
'  var warning = \'页面展示\' + displayCount + \'条记录，可导出\' + exportCount + \'条记录\';',
'  if (hasWarning) {',
'    warning = warning + \'（不一致：所有记录包括重复用户反馈和待复核都应导出）\';',
'  } else {',
'    warning = warning + \'，所有记录（含重复用户反馈、待复核）均可导出\';',
'  }',
'',
'  return {',
'    consistent: !hasWarning,',
'    warning: warning,',
'    displayCount: displayCount,',
'    exportableCount: exportCount,',
'    totalRecords: batchRecords.length,',
'    duplicateUserCount: batchRecords.filter(function(r) { return r.status === STATUS.DUPLICATE_USER; }).length,',
'    needsReviewCount: batchRecords.filter(function(r) { return r.status === STATUS.NEEDS_REVIEW; }).length',
'  };',
'}',
'',
'function runFullCheck(batchId) {',
'  var records = readRecords();',
'  var batches = readBatches();',
'  var batch = batches.find(function(b) { return b.id === batchId; });',
'',
'  if (!batch) {',
'    return {',
'      valid: false,',
'      error: \'批次不存在\'',
'    };',
'  }',
'',
'  var batchRecords = records.filter(function(r) { return r.batchId === batchId; });',
'',
'  var issues = [];',
'',
'  var duplicateUserIssues = checkDuplicateUserFeedback(records, batchId);',
'  issues = issues.concat(duplicateUserIssues);',
'',
'  var mergeIssues = checkMergeConsistency(records, batchId);',
'  issues = issues.concat(mergeIssues);',
'',
'  var importSources = {};',
'  batchRecords.forEach(function(record) {',
'    var source = record.importSource || \'unknown\';',
'    importSources[source] = (importSources[source] || 0) + 1;',
'  });',
'',
'  var statusCounts = {};',
'  Object.keys(STATUS).forEach(function(key) {',
'    statusCounts[STATUS[key]] = 0;',
'  });',
'  batchRecords.forEach(function(record) {',
'    statusCounts[record.status] = (statusCounts[record.status] || 0) + 1;',
'  });',
'',
'  var exportCheck = checkExportConsistency(records, batchId);',
'',
'  var stats = {',
'    total: batchRecords.length,',
'    normal: statusCounts[STATUS.NORMAL] || 0,',
'    duplicateUser: statusCounts[STATUS.DUPLICATE_USER] || 0,',
'    merged: statusCounts[STATUS.MERGED] || 0,',
'    excluded: statusCounts[STATUS.EXCLUDED] || 0,',
'    pending: statusCounts[STATUS.PENDING] || 0,',
'    needsReview: statusCounts[STATUS.NEEDS_REVIEW] || 0,',
'    importSources: importSources',
'  };',
'',
'  return {',
'    valid: true,',
'    batchId: batchId,',
'    batchName: batch.name,',
'    totalRecords: batchRecords.length,',
'    issues: issues,',
'    issueCount: issues.length,',
'    duplicateUserCount: duplicateUserIssues.length,',
'    stats: stats,',
'    statusCounts: statusCounts,',
'    importSources: importSources,',
'    exportCheck: exportCheck',
'  };',
'}',
'',
'function applyAutoStatus(records, batchId) {',
'  var batchRecords = records.filter(function(r) { return r.batchId === batchId; });',
'',
'  var userQuestionMap = {};',
'  batchRecords.forEach(function(record) {',
'    var key = record.userId + \'__\' + record.questionText.trim().toLowerCase();',
'    if (!userQuestionMap[key]) {',
'      userQuestionMap[key] = [];',
'    }',
'    userQuestionMap[key].push(record);',
'  });',
'',
'  var updatedRecords = records.map(function(record) {',
'    if (record.batchId !== batchId) {',
'      return record;',
'    }',
'',
'    var key = record.userId + \'__\' + record.questionText.trim().toLowerCase();',
'    var sameGroup = userQuestionMap[key] || [];',
'',
'    var newStatus = record.status;',
'    var reason = \'\';',
'',
'    if (record.status === STATUS.PENDING || record.status === STATUS.NORMAL || record.status === STATUS.DUPLICATE_USER) {',
'      if (sameGroup.length > 1) {',
'        var isFirst = sameGroup[0].id === record.id;',
'        if (!isFirst && record.status !== STATUS.MERGED && record.status !== STATUS.EXCLUDED) {',
'          newStatus = STATUS.DUPLICATE_USER;',
'          reason = \'同一用户+相同问题，自动标记为重复用户反馈，同组共\' + sameGroup.length + \'条\';',
'        } else if (isFirst && record.status === STATUS.DUPLICATE_USER) {',
'          newStatus = STATUS.NORMAL;',
'          reason = \'同组第一条记录，恢复为正常状态\';',
'        }',
'      } else if (record.status === STATUS.DUPLICATE_USER) {',
'        newStatus = STATUS.NORMAL;',
'        reason = \'不再有重复用户反馈，恢复为正常状态\';',
'      }',
'    }',
'',
'    if (newStatus !== record.status) {',
'      var changes = [',
'        {',
'          field: \'status\',',
'          oldValue: record.status,',
'          newValue: newStatus,',
'          changedAt: new Date().toISOString(),',
'          changedBy: \'system_auto_check\',',
'          reason: reason',
'        }',
'      ];',
'',
'      var newRecord = {};',
'      Object.keys(record).forEach(function(k) {',
'        newRecord[k] = record[k];',
'      });',
'      newRecord.status = newStatus;',
'      newRecord.statusUpdatedAt = new Date().toISOString();',
'      newRecord.statusUpdatedBy = \'system_auto_check\';',
'      newRecord.manualChanges = (record.manualChanges || []).concat(changes);',
'      return newRecord;',
'    }',
'',
'    return record;',
'  });',
'',
'  return updatedRecords;',
'}',
'',
'module.exports = {',
'  STATUS: STATUS,',
'  STATUS_LABELS: STATUS_LABELS,',
'  IMPORT_SOURCE_LABELS: IMPORT_SOURCE_LABELS,',
'  buildRecordFingerprint: buildRecordFingerprint,',
'  checkDuplicateImport: checkDuplicateImport,',
'  calcIncrementalImportDiff: calcIncrementalImportDiff,',
'  checkDuplicateUserFeedback: checkDuplicateUserFeedback,',
'  checkMergeConsistency: checkMergeConsistency,',
'  checkExportConsistency: checkExportConsistency,',
'  runFullCheck: runFullCheck,',
'  applyAutoStatus: applyAutoStatus',
'};',
''
].join('\n');

var batchesContent = [
'var express = require(\'express\');',
'var multer = require(\'multer\');',
'var csvParser = require(\'csv-parser\');',
'var Readable = require(\'stream\').Readable;',
'var Parser = require(\'json2csv\').Parser;',
'',
'var dataStore = require(\'../services/dataStore\');',
'var readBatches = dataStore.readBatches;',
'var writeBatches = dataStore.writeBatches;',
'var readRecords = dataStore.readRecords;',
'var writeRecords = dataStore.writeRecords;',
'var generateId = dataStore.generateId;',
'',
'var selfCheck = require(\'../services/selfCheck\');',
'var STATUS = selfCheck.STATUS;',
'var STATUS_LABELS = selfCheck.STATUS_LABELS;',
'var IMPORT_SOURCE_LABELS = selfCheck.IMPORT_SOURCE_LABELS;',
'var buildRecordFingerprint = selfCheck.buildRecordFingerprint;',
'var calcIncrementalImportDiff = selfCheck.calcIncrementalImportDiff;',
'var checkDuplicateImport = selfCheck.checkDuplicateImport;',
'var runFullCheck = selfCheck.runFullCheck;',
'var applyAutoStatus = selfCheck.applyAutoStatus;',
'',
'var router = express.Router();',
'var upload = multer({ storage: multer.memoryStorage() });',
'',
'router.get(\'/\', function(req, res) {',
'  var batches = readBatches();',
'  var records = readRecords();',
'',
'  var batchesWithStats = batches.map(function(batch) {',
'    var batchRecords = records.filter(function(r) { return r.batchId === batch.id; });',
'    var result = {};',
'    Object.keys(batch).forEach(function(k) { result[k] = batch[k]; });',
'    result.recordCount = batchRecords.length;',
'    result.issueCount = batchRecords.filter(function(r) {',
'      return r.status === STATUS.DUPLICATE_USER || r.status === STATUS.NEEDS_REVIEW;',
'    }).length;',
'    return result;',
'  });',
'',
'  res.json(batchesWithStats);',
'});',
'',
'router.post(\'/\', upload.single(\'file\'), function(req, res) {',
'  var promise = new Promise(function(resolve, reject) {',
'    try {',
'      var batchName = req.body.batchName;',
'      var operator = req.body.operator;',
'',
'      if (!batchName) {',
'        return res.status(400).json({ error: \'批次名称不能为空\' });',
'      }',
'',
'      if (!req.file) {',
'        return res.status(400).json({ error: \'请上传CSV文件\' });',
'      }',
'',
'      var rows = [];',
'      var fileContent = req.file.buffer.toString(\'utf8\');',
'',
'      Readable.from(fileContent)',
'        .pipe(csvParser())',
'        .on(\'data\', function(row) { rows.push(row); })',
'        .on(\'end\', function() {',
'          try {',
'            if (rows.length === 0) {',
'              return res.status(400).json({ error: \'CSV文件为空或格式错误\' });',
'            }',
'',
'            var existingBatches = readBatches();',
'            var existingRecords = readRecords();',
'            var existingBatch = existingBatches.find(function(b) { return b.name === batchName; });',
'',
'            var batchId;',
'            var isIncremental = false;',
'            var batch;',
'            var newRecords = [];',
'            var reusedCount = 0;',
'            var newCount = 0;',
'            var incrementalDiff = null;',
'',
'            if (existingBatch) {',
'              isIncremental = true;',
'              batchId = existingBatch.id;',
'',
'              var diffResult = calcIncrementalImportDiff(batchId, existingRecords, rows);',
'              reusedCount = diffResult.reusedCount;',
'              newCount = diffResult.newCount;',
'              incrementalDiff = {',
'                reusedCount: reusedCount,',
'                newCount: newCount,',
'                totalBefore: existingRecords.filter(function(r) { return r.batchId === batchId; }).length,',
'                totalAfter: existingRecords.filter(function(r) { return r.batchId === batchId; }).length + newCount',
'              };',
'',
'              var existingBatchRecords = existingRecords.filter(function(r) { return r.batchId === batchId; });',
'              var startLineNumber = existingBatchRecords.length + 2;',
'',
'              newRecords = diffResult.newRecords.map(function(item, idx) {',
'                var row = item.row;',
'                var fingerprint = item.fingerprint;',
'                var rec = {',
'                  id: generateId(),',
'                  batchId: batchId,',
'                  originalLineNumber: startLineNumber + idx,',
'                  importLineNumber: idx + 2,',
'                  questionText: row.question || row.问题 || \'\',',
'                  userId: row.user_id || row.用户ID || row.userId || \'\',',
'                  userName: row.user_name || row.用户名 || \'\',',
'                  feedbackTime: row.feedback_time || row.反馈时间 || \'\',',
'                  originalData: row,',
'                  status: STATUS.PENDING,',
'                  statusUpdatedAt: new Date().toISOString(),',
'                  statusUpdatedBy: \'system_import\',',
'                  manualChanges: [],',
'                  mergedIntoId: null,',
'                  mergedFromIds: [],',
'                  annotatorComment: \'\',',
'                  reviewComment: \'\',',
'                  importFingerprint: fingerprint,',
'                  importSource: \'incremental\'',
'                };',
'                return rec;',
'              });',
'',
'              var batchIdx = existingBatches.findIndex(function(b) { return b.id === batchId; });',
'              var updatedBatch = {};',
'              Object.keys(existingBatch).forEach(function(k) { updatedBatch[k] = existingBatch[k]; });',
'              updatedBatch.rowCount = (existingBatch.rowCount || 0) + newCount;',
'              updatedBatch.updatedAt = new Date().toISOString();',
'              updatedBatch.updatedBy = operator || \'system\';',
'              batch = updatedBatch;',
'              existingBatches[batchIdx] = batch;',
'            } else {',
'              batchId = generateId();',
'',
'              newRecords = rows.map(function(row, idx) {',
'                var fingerprint = buildRecordFingerprint(row);',
'                return {',
'                  id: generateId(),',
'                  batchId: batchId,',
'                  originalLineNumber: idx + 2,',
'                  importLineNumber: idx + 2,',
'                  questionText: row.question || row.问题 || \'\',',
'                  userId: row.user_id || row.用户ID || row.userId || \'\',',
'                  userName: row.user_name || row.用户名 || \'\',',
'                  feedbackTime: row.feedback_time || row.反馈时间 || \'\',',
'                  originalData: row,',
'                  status: STATUS.PENDING,',
'                  statusUpdatedAt: new Date().toISOString(),',
'                  statusUpdatedBy: \'system_import\',',
'                  manualChanges: [],',
'                  mergedIntoId: null,',
'                  mergedFromIds: [],',
'                  annotatorComment: \'\',',
'                  reviewComment: \'\',',
'                  importFingerprint: fingerprint,',
'                  importSource: \'initial\'',
'                };',
'              });',
'',
'              batch = {',
'                id: batchId,',
'                name: batchName,',
'                createdAt: new Date().toISOString(),',
'                createdBy: operator || \'system\',',
'                fileName: req.file.originalname,',
'                rowCount: rows.length,',
'                importNotes: \'\'',
'              };',
'',
'              existingBatches.push(batch);',
'              newCount = rows.length;',
'              incrementalDiff = {',
'                reusedCount: 0,',
'                newCount: newCount,',
'                totalBefore: 0,',
'                totalAfter: newCount',
'              };',
'            }',
'',
'            var allRecords = existingRecords.concat(newRecords);',
'            allRecords = applyAutoStatus(allRecords, batchId);',
'',
'            var duplicateIssues = checkDuplicateImport(batchId, existingRecords, rows);',
'',
'            writeBatches(existingBatches);',
'            writeRecords(allRecords);',
'',
'            var checkResult = runFullCheck(batchId);',
'',
'            res.json({',
'              success: true,',
'              batch: batch,',
'              isIncremental: isIncremental,',
'              importedCount: newCount,',
'              reusedCount: reusedCount,',
'              totalCount: allRecords.filter(function(r) { return r.batchId === batchId; }).length,',
'              duplicateIssues: duplicateIssues,',
'              incrementalDiff: incrementalDiff,',
'              checkResult: checkResult',
'            });',
'',
'            resolve();',
'          } catch (innerErr) {',
'            reject(innerErr);',
'          }',
'        })',
'        .on(\'error\', reject);',
'    } catch (error) {',
'      reject(error);',
'    }',
'  });',
'',
'  promise.catch(function(error) {',
'    console.error(\'导入失败:\', error);',
'    res.status(500).json({ error: \'导入失败: \' + error.message });',
'  });',
'});',
'',
'router.get(\'/:batchId\', function(req, res) {',
'  var batchId = req.params.batchId;',
'  var batches = readBatches();',
'  var batch = batches.find(function(b) { return b.id === batchId; });',
'',
'  if (!batch) {',
'    return res.status(404).json({ error: \'批次不存在\' });',
'  }',
'',
'  var records = readRecords().filter(function(r) { return r.batchId === batchId; });',
'  var checkResult = runFullCheck(batchId);',
'',
'  res.json({',
'    batch: batch,',
'    records: records,',
'    checkResult: checkResult',
'  });',
'});',
'',
'router.get(\'/:batchId/records\', function(req, res) {',
'  var batchId = req.params.batchId;',
'  var status = req.query.status;',
'  var userId = req.query.userId;',
'  var page = parseInt(req.query.page || 1);',
'  var pageSize = parseInt(req.query.pageSize || 50);',
'',
'  var records = readRecords().filter(function(r) { return r.batchId === batchId; });',
'',
'  if (status) {',
'    records = records.filter(function(r) { return r.status === status; });',
'  }',
'  if (userId) {',
'    records = records.filter(function(r) { return r.userId.indexOf(userId) !== -1; });',
'  }',
'',
'  var total = records.length;',
'  var start = (page - 1) * pageSize;',
'  var paginatedRecords = records.slice(start, start + pageSize);',
'',
'  res.json({',
'    total: total,',
'    page: page,',
'    pageSize: pageSize,',
'    records: paginatedRecords',
'  });',
'});',
'',
'router.put(\'/:batchId/records/:recordId\', function(req, res) {',
'  var batchId = req.params.batchId;',
'  var recordId = req.params.recordId;',
'  var status = req.body.status;',
'  var annotatorComment = req.body.annotatorComment;',
'  var reviewComment = req.body.reviewComment;',
'  var operator = req.body.operator;',
'  var reason = req.body.reason || \'\';',
'',
'  var records = readRecords();',
'  var recordIndex = records.findIndex(function(r) { return r.id === recordId && r.batchId === batchId; });',
'',
'  if (recordIndex === -1) {',
'    return res.status(404).json({ error: \'记录不存在\' });',
'  }',
'',
'  var oldRecord = records[recordIndex];',
'  var changes = [];',
'',
'  if (status && status !== oldRecord.status) {',
'    changes.push({',
'      field: \'status\',',
'      oldValue: oldRecord.status,',
'      newValue: status,',
'      changedAt: new Date().toISOString(),',
'      changedBy: operator || \'unknown\',',
'      reason: reason || \'手动更新状态\'',
'    });',
'  }',
'',
'  if (annotatorComment !== undefined && annotatorComment !== oldRecord.annotatorComment) {',
'    changes.push({',
'      field: \'annotatorComment\',',
'      oldValue: oldRecord.annotatorComment,',
'      newValue: annotatorComment,',
'      changedAt: new Date().toISOString(),',
'      changedBy: operator || \'unknown\',',
'      reason: reason || \'手动更新标注员留言\'',
'    });',
'  }',
'',
'  if (reviewComment !== undefined && reviewComment !== oldRecord.reviewComment) {',
'    changes.push({',
'      field: \'reviewComment\',',
'      oldValue: oldRecord.reviewComment,',
'      newValue: reviewComment,',
'      changedAt: new Date().toISOString(),',
'      changedBy: operator || \'unknown\',',
'      reason: reason || \'手动更新复核意见\'',
'    });',
'  }',
'',
'  var newRecord = {};',
'  Object.keys(oldRecord).forEach(function(k) { newRecord[k] = oldRecord[k]; });',
'  if (status) newRecord.status = status;',
'  if (annotatorComment !== undefined) newRecord.annotatorComment = annotatorComment;',
'  if (reviewComment !== undefined) newRecord.reviewComment = reviewComment;',
'  newRecord.statusUpdatedAt = new Date().toISOString();',
'  newRecord.statusUpdatedBy = operator || \'unknown\';',
'  newRecord.manualChanges = (oldRecord.manualChanges || []).concat(changes);',
'',
'  records[recordIndex] = newRecord;',
'',
'  writeRecords(records);',
'',
'  var checkResult = runFullCheck(batchId);',
'',
'  res.json({',
'    success: true,',
'    record: records[recordIndex],',
'    checkResult: checkResult',
'  });',
'});',
'',
'router.post(\'/:batchId/merge\', function(req, res) {',
'  var batchId = req.params.batchId;',
'  var sourceRecordIds = req.body.sourceRecordIds;',
'  var targetRecordId = req.body.targetRecordId;',
'  var operator = req.body.operator;',
'',
'  if (!targetRecordId || !sourceRecordIds || sourceRecordIds.length === 0) {',
'    return res.status(400).json({ error: \'归并参数不完整\' });',
'  }',
'',
'  var records = readRecords();',
'',
'  var targetRecord = records.find(function(r) { return r.id === targetRecordId && r.batchId === batchId; });',
'  if (!targetRecord) {',
'    return res.status(404).json({ error: \'目标记录不存在\' });',
'  }',
'',
'  var updatedRecords = records.slice();',
'',
'  sourceRecordIds.forEach(function(sourceId) {',
'    var sourceIdx = updatedRecords.findIndex(function(r) { return r.id === sourceId && r.batchId === batchId; });',
'    if (sourceIdx !== -1 && sourceId !== targetRecordId) {',
'      var sourceRecord = updatedRecords[sourceIdx];',
'      var newSourceRecord = {};',
'      Object.keys(sourceRecord).forEach(function(k) { newSourceRecord[k] = sourceRecord[k]; });',
'      newSourceRecord.status = STATUS.MERGED;',
'      newSourceRecord.mergedIntoId = targetRecordId;',
'      newSourceRecord.statusUpdatedAt = new Date().toISOString();',
'      newSourceRecord.statusUpdatedBy = operator || \'unknown\';',
'      newSourceRecord.manualChanges = (sourceRecord.manualChanges || []).concat([{',
'        field: \'mergedIntoId\',',
'        oldValue: null,',
'        newValue: targetRecordId,',
'        changedAt: new Date().toISOString(),',
'        changedBy: operator || \'unknown\',',
'        reason: \'手动归并到目标记录\'',
'      }]);',
'      updatedRecords[sourceIdx] = newSourceRecord;',
'',
'      var targetIdx = updatedRecords.findIndex(function(r) { return r.id === targetRecordId; });',
'      if (targetIdx !== -1) {',
'        var newTargetRecord = {};',
'        Object.keys(updatedRecords[targetIdx]).forEach(function(k) { newTargetRecord[k] = updatedRecords[targetIdx][k]; });',
'        newTargetRecord.mergedFromIds = (newTargetRecord.mergedFromIds || []).concat([sourceId]);',
'        updatedRecords[targetIdx] = newTargetRecord;',
'      }',
'    }',
'  });',
'',
'  writeRecords(updatedRecords);',
'',
'  var checkResult = runFullCheck(batchId);',
'',
'  res.json({',
'    success: true,',
'    checkResult: checkResult',
'  });',
'});',
'',
'router.get(\'/:batchId/export\', function(req, res) {',
'  var batchId = req.params.batchId;',
'  var format = req.query.format || \'csv\';',
'',
'  var batches = readBatches();',
'  var batch = batches.find(function(b) { return b.id === batchId; });',
'',
'  if (!batch) {',
'    return res.status(404).json({ error: \'批次不存在\' });',
'  }',
'',
'  var allRecords = readRecords();',
'  var batchRecords = allRecords.filter(function(r) { return r.batchId === batchId; });',
'',
'  var exportData = batchRecords.map(function(r) {',
'    return {',
'      \'原始行号\': r.originalLineNumber,',
'      \'导入来源\': IMPORT_SOURCE_LABELS[r.importSource] || r.importSource || \'\',',
'      \'本次导入行号\': r.importLineNumber || \'\',',
'      \'用户ID\': r.userId,',
'      \'用户名\': r.userName,',
'      \'问题文本\': r.questionText,',
'      \'反馈时间\': r.feedbackTime,',
'      \'当前状态\': STATUS_LABELS[r.status] || r.status,',
'      \'标注员留言\': r.annotatorComment,',
'      \'复核意见\': r.reviewComment,',
'      \'是否已归并\': r.status === STATUS.MERGED ? \'是\' : \'否\',',
'      \'归并目标ID\': r.mergedIntoId || \'\',',
'      \'状态更新时间\': r.statusUpdatedAt,',
'      \'状态更新人\': r.statusUpdatedBy',
'    };',
'  });',
'',
'  var safeFileName = encodeURIComponent(batch.name + \'_明细\');',
'',
'  if (format === \'json\') {',
'    res.setHeader(\'Content-Type\', \'application/json; charset=utf-8\');',
'    res.setHeader(\'Content-Disposition\', \'attachment; filename*=UTF-8\\'\\'\' + safeFileName + \'.json\');',
'    res.json(exportData);',
'  } else {',
'    var fields = exportData.length > 0 ? Object.keys(exportData[0]) : [];',
'    var parser = new Parser({ fields: fields });',
'    var csv = parser.parse(exportData);',
'',
'    res.setHeader(\'Content-Type\', \'text/csv; charset=utf-8\');',
'    res.setHeader(\'Content-Disposition\', \'attachment; filename*=UTF-8\\'\\'\' + safeFileName + \'.csv\');',
'    res.send(\'\\uFEFF\' + csv);',
'  }',
'});',
'',
'router.put(\'/:batchId/rename\', function(req, res) {',
'  var batchId = req.params.batchId;',
'  var name = req.body.name;',
'  var operator = req.body.operator;',
'',
'  if (!name) {',
'    return res.status(400).json({ error: \'批次名称不能为空\' });',
'  }',
'',
'  var batches = readBatches();',
'  var batchIdx = batches.findIndex(function(b) { return b.id === batchId; });',
'',
'  if (batchIdx === -1) {',
'    return res.status(404).json({ error: \'批次不存在\' });',
'  }',
'',
'  var duplicateBatch = batches.find(function(b) { return b.name === name && b.id !== batchId; });',
'  if (duplicateBatch) {',
'    return res.status(400).json({ error: \'批次名称已存在，请换个名称\' });',
'  }',
'',
'  var newBatch = {};',
'  Object.keys(batches[batchIdx]).forEach(function(k) { newBatch[k] = batches[batchIdx][k]; });',
'  newBatch.name = name;',
'  newBatch.updatedAt = new Date().toISOString();',
'  newBatch.updatedBy = operator || \'unknown\';',
'  batches[batchIdx] = newBatch;',
'',
'  writeBatches(batches);',
'',
'  var checkResult = runFullCheck(batchId);',
'',
'  res.json({',
'    success: true,',
'    batch: batches[batchIdx],',
'    checkResult: checkResult',
'  });',
'});',
'',
'router.get(\'/:batchId/check\', function(req, res) {',
'  var batchId = req.params.batchId;',
'  var result = runFullCheck(batchId);',
'  res.json(result);',
'});',
'',
'router.post(\'/:batchId/recheck\', function(req, res) {',
'  var batchId = req.params.batchId;',
'  var operator = req.body.operator;',
'',
'  var records = readRecords();',
'  records = applyAutoStatus(records, batchId);',
'  writeRecords(records);',
'',
'  var checkResult = runFullCheck(batchId);',
'',
'  res.json({',
'    success: true,',
'    message: \'补录后重算完成，已自动更新异常状态\',',
'    checkResult: checkResult',
'  });',
'});',
'',
'router.post(\'/:batchId/notes\', function(req, res) {',
'  var batchId = req.params.batchId;',
'  var importNotes = req.body.importNotes;',
'  var operator = req.body.operator;',
'',
'  var batches = readBatches();',
'  var batchIdx = batches.findIndex(function(b) { return b.id === batchId; });',
'',
'  if (batchIdx === -1) {',
'    return res.status(404).json({ error: \'批次不存在\' });',
'  }',
'',
'  var newBatch = {};',
'  Object.keys(batches[batchIdx]).forEach(function(k) { newBatch[k] = batches[batchIdx][k]; });',
'  newBatch.importNotes = importNotes;',
'  newBatch.notesUpdatedAt = new Date().toISOString();',
'  newBatch.notesUpdatedBy = operator || \'unknown\';',
'  batches[batchIdx] = newBatch;',
'',
'  writeBatches(batches);',
'',
'  res.json({',
'    success: true,',
'    batch: batches[batchIdx]',
'  });',
'});',
'',
'module.exports = router;',
''
].join('\n');

var indexHtmlContent = [
'<!DOCTYPE html>',
'<html lang="zh-CN">',
'<head>',
'  <meta charset="UTF-8">',
'  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
'  <title>产品问答相似问题归并</title>',
'  <link rel="stylesheet" href="styles.css">',
'</head>',
'<body>',
'  <div class="app">',
'    <header class="header">',
'      <h1>产品问答相似问题归并</h1>',
'      <div class="user-info">',
'        <span id="currentUser">算法运营-老唐</span>',
'      </div>',
'    </header>',
'',
'    <div class="main-container">',
'      <aside class="sidebar">',
'        <div class="sidebar-section">',
'          <h3>灰度批次</h3>',
'          <button id="createBatchBtn" class="btn btn-primary">+ 新建批次</button>',
'          <div id="batchList" class="batch-list"></div>',
'        </div>',
'        <div class="sidebar-section workflow-guide">',
'          <h3>操作指引</h3>',
'          <div class="step current">',
'            <span class="step-num">1</span>',
'            <span>导入灰度批次</span>',
'          </div>',
'          <div class="step">',
'            <span class="step-num">2</span>',
'            <span>补看标注员留言</span>',
'          </div>',
'          <div class="step">',
'            <span class="step-num">3</span>',
'            <span>证据回放更新</span>',
'          </div>',
'          <div class="step">',
'            <span class="step-num">4</span>',
'            <span>标注负责人复核</span>',
'          </div>',
'        </div>',
'      </aside>',
'',
'      <main class="content">',
'        <div id="emptyState" class="empty-state">',
'          <div class="empty-icon">📋</div>',
'          <h2>请选择或创建灰度批次</h2>',
'          <p>支持导入CSV，自动检测重复用户反馈，保留原始行号和改动痕迹</p>',
'        </div>',
'',
'        <div id="batchDetail" class="batch-detail" style="display: none;">',
'          <div class="batch-header">',
'            <div>',
'              <h2 id="batchName"></h2>',
'              <div class="batch-meta">',
'                <span id="batchFile"></span>',
'                <span>·</span>',
'                <span id="batchTime"></span>',
'              </div>',
'            </div>',
'            <div class="batch-actions">',
'              <button id="renameBatchBtn" class="btn btn-secondary">✏️ 重命名批次</button>',
'              <button id="recheckBtn" class="btn btn-secondary">🔄 补录后重算</button>',
'              <button id="exportBtn" class="btn btn-secondary">📥 导出明细</button>',
'              <button id="checkBtn" class="btn btn-primary">🔍 运行自检</button>',
'            </div>',
'          </div>',
'',
'          <div class="batch-notes">',
'            <label>标注员留言补录（老唐看群后补充）：</label>',
'            <textarea id="batchNotes" placeholder="这里记录标注员在群里补充的说明、特殊情况备注..."></textarea>',
'            <button id="saveNotesBtn" class="btn btn-small btn-secondary">保存备注</button>',
'          </div>',
'',
'          <div id="checkResult" class="check-result" style="display: none;">',
'            <h3>自检结果</h3>',
'            <div class="stats-grid">',
'              <div class="stat-card">',
'                <div class="stat-value" id="statTotal">0</div>',
'                <div class="stat-label">总记录数</div>',
'              </div>',
'              <div class="stat-card">',
'                <div class="stat-value" id="statNormal">0</div>',
'                <div class="stat-label">正常</div>',
'              </div>',
'              <div class="stat-card stat-warning">',
'                <div class="stat-value" id="statDuplicate">0</div>',
'                <div class="stat-label">同一用户重复反馈</div>',
'              </div>',
'              <div class="stat-card stat-info">',
'                <div class="stat-value" id="statMerged">0</div>',
'                <div class="stat-label">已归并</div>',
'              </div>',
'              <div class="stat-card stat-danger">',
'                <div class="stat-value" id="statExcluded">0</div>',
'                <div class="stat-label">已排除</div>',
'              </div>',
'              <div class="stat-card">',
'                <div class="stat-value" id="statPending">0</div>',
'                <div class="stat-label">待处理</div>',
'              </div>',
'              <div class="stat-card stat-info">',
'                <div class="stat-value" id="statInitial">0</div>',
'                <div class="stat-label">首次导入</div>',
'              </div>',
'              <div class="stat-card stat-success">',
'                <div class="stat-value" id="statIncremental">0</div>',
'                <div class="stat-label">增量导入</div>',
'              </div>',
'            </div>',
'            <div id="exportCheck" class="export-check"></div>',
'            <div id="issueList" class="issue-list"></div>',
'          </div>',
'',
'          <div class="filter-bar">',
'            <select id="statusFilter">',
'              <option value="">全部状态</option>',
'              <option value="pending">待处理</option>',
'              <option value="normal">正常</option>',
'              <option value="duplicate_user">同一用户重复反馈</option>',
'              <option value="needs_review">待标注负责人复核</option>',
'              <option value="merged">已归并</option>',
'              <option value="excluded">已排除</option>',
'            </select>',
'            <input type="text" id="userIdFilter" placeholder="搜索用户ID...">',
'            <span id="recordCount" class="record-count"></span>',
'          </div>',
'',
'          <div class="table-container">',
'            <table class="records-table">',
'              <thead>',
'                <tr>',
'                  <th width="40"><input type="checkbox" id="selectAll"></th>',
'                  <th width="80">原始行号</th>',
'                  <th width="90">导入来源</th>',
'                  <th width="100">用户ID</th>',
'                  <th>问题文本</th>',
'                  <th width="120">当前状态</th>',
'                  <th width="150">状态更新人</th>',
'                  <th width="100">操作</th>',
'                </tr>',
'              </thead>',
'              <tbody id="recordsTableBody"></tbody>',
'            </table>',
'          </div>',
'',
'          <div class="merge-bar" id="mergeBar" style="display: none;">',
'            <span>已选择 <span id="selectedCount">0</span> 条记录</span>',
'            <button id="cancelSelectBtn" class="btn btn-small btn-secondary">取消选择</button>',
'            <button id="mergeBtn" class="btn btn-small btn-primary">归并到主记录</button>',
'          </div>',
'        </div>',
'      </main>',
'    </div>',
'',
'    <div id="createBatchModal" class="modal" style="display: none;">',
'      <div class="modal-content">',
'        <div class="modal-header">',
'          <h3>新建灰度批次</h3>',
'          <button class="modal-close" onclick="closeModal(\'createBatchModal\')">×</button>',
'        </div>',
'        <div class="modal-body">',
'          <div class="form-group">',
'            <label>批次名称</label>',
'            <input type="text" id="newBatchName" placeholder="例如：2024Q4灰度批次-001">',
'          </div>',
'          <div class="form-group">',
'            <label>上传CSV文件</label>',
'            <input type="file" id="csvFile" accept=".csv">',
'            <small>需包含 question、user_id、user_name、feedback_time 列</small>',
'          </div>',
'          <div class="form-group">',
'            <label>操作人</label>',
'            <input type="text" id="operatorName" value="老唐">',
'          </div>',
'        </div>',
'        <div class="modal-footer">',
'          <button class="btn btn-secondary" onclick="closeModal(\'createBatchModal\')">取消</button>',
'          <button class="btn btn-primary" id="confirmCreateBatch">确认导入</button>',
'        </div>',
'      </div>',
'    </div>',
'',
'    <div id="renameBatchModal" class="modal" style="display: none;">',
'      <div class="modal-content">',
'        <div class="modal-header">',
'          <h3>重命名批次</h3>',
'          <button class="modal-close" onclick="closeModal(\'renameBatchModal\')">×</button>',
'        </div>',
'        <div class="modal-body">',
'          <div class="form-group">',
'            <label>当前批次名称</label>',
'            <input type="text" id="currentBatchName" disabled>',
'          </div>',
'          <div class="form-group">',
'            <label>新批次名称</label>',
'            <input type="text" id="newRenameBatchName" placeholder="请输入新的批次名称">',
'          </div>',
'          <div class="form-group">',
'            <label>操作人</label>',
'            <input type="text" id="renameOperatorName" value="老唐">',
'          </div>',
'        </div>',
'        <div class="modal-footer">',
'          <button class="btn btn-secondary" onclick="closeModal(\'renameBatchModal\')">取消</button>',
'          <button class="btn btn-primary" id="confirmRenameBatch">确认重命名</button>',
'        </div>',
'      </div>',
'    </div>',
'',
'    <div id="recordDetailModal" class="modal" style="display: none;">',
'      <div class="modal-content modal-large">',
'        <div class="modal-header">',
'          <h3>记录详情 - 证据回放</h3>',
'          <button class="modal-close" onclick="closeModal(\'recordDetailModal\')">×</button>',
'        </div>',
'        <div class="modal-body">',
'          <div class="detail-grid">',
'            <div class="detail-section">',
'              <h4>原始数据</h4>',
'              <div class="detail-item">',
'                <label>原始行号：</label>',
'                <span id="detailLineNumber"></span>',
'              </div>',
'              <div class="detail-item">',
'                <label>导入来源：</label>',
'                <span id="detailImportSource"></span>',
'              </div>',
'              <div class="detail-item">',
'                <label>用户ID：</label>',
'                <span id="detailUserId"></span>',
'              </div>',
'              <div class="detail-item">',
'                <label>用户名：</label>',
'                <span id="detailUserName"></span>',
'              </div>',
'              <div class="detail-item">',
'                <label>反馈时间：</label>',
'                <span id="detailFeedbackTime"></span>',
'              </div>',
'              <div class="detail-item">',
'                <label>问题文本：</label>',
'                <p id="detailQuestion" class="question-text"></p>',
'              </div>',
'            </div>',
'            <div class="detail-section">',
'              <h4>处理状态</h4>',
'              <div class="detail-item">',
'                <label>当前状态：</label>',
'                <select id="detailStatus">',
'                  <option value="pending">待处理</option>',
'                  <option value="normal">正常</option>',
'                  <option value="duplicate_user">同一用户重复反馈</option>',
'                  <option value="needs_review">待标注负责人复核</option>',
'                  <option value="merged">已归并</option>',
'                  <option value="excluded">已排除</option>',
'                </select>',
'              </div>',
'              <div class="detail-item">',
'                <label>状态更新人：</label>',
'                <span id="detailStatusUpdatedBy"></span>',
'              </div>',
'              <div class="detail-item">',
'                <label>状态更新时间：</label>',
'                <span id="detailStatusUpdatedAt"></span>',
'              </div>',
'              <div class="detail-item">',
'                <label>标注员留言：</label>',
'                <textarea id="detailAnnotatorComment" placeholder="标注员补充说明..."></textarea>',
'              </div>',
'              <div class="detail-item">',
'                <label>复核意见：</label>',
'                <textarea id="detailReviewComment" placeholder="标注负责人复核意见，同一用户重复反馈需在此说明处理方式..."></textarea>',
'              </div>',
'            </div>',
'          </div>',
'          <div class="detail-section">',
'            <h4>人工改动历史（证据链）</h4>',
'            <div id="detailChangeHistory" class="change-history"></div>',
'          </div>',
'          <div class="detail-section" id="mergeInfoSection" style="display: none;">',
'            <h4>归并信息</h4>',
'            <div id="mergeInfo"></div>',
'          </div>',
'        </div>',
'        <div class="modal-footer">',
'          <button class="btn btn-secondary" onclick="closeModal(\'recordDetailModal\')">关闭</button>',
'          <button class="btn btn-primary" id="saveRecordBtn">保存修改</button>',
'        </div>',
'      </div>',
'    </div>',
'',
'    <div id="mergeModal" class="modal" style="display: none;">',
'      <div class="modal-content">',
'        <div class="modal-header">',
'          <h3>选择归并目标主记录</h3>',
'          <button class="modal-close" onclick="closeModal(\'mergeModal\')">×</button>',
'        </div>',
'        <div class="modal-body">',
'          <p class="merge-tip">选择一条作为主记录，其他选中记录将归并到该记录下：</p>',
'          <div id="mergeTargetList" class="merge-target-list"></div>',
'        </div>',
'        <div class="modal-footer">',
'          <button class="btn btn-secondary" onclick="closeModal(\'mergeModal\')">取消</button>',
'          <button class="btn btn-primary" id="confirmMergeBtn">确认归并</button>',
'        </div>',
'      </div>',
'    </div>',
'',
'    <div id="toast" class="toast" style="display: none;"></div>',
'  </div>',
'',
'  <script src="app.js"></script>',
'</body>',
'</html>',
''
].join('\n');

var appJsContent = [
'var API_BASE = \'/api\';',
'',
'var STATUS_LABELS = {',
'  pending: \'待处理\',',
'  normal: \'正常\',',
'  duplicate_user: \'同一用户重复反馈\',',
'  needs_review: \'待标注负责人复核\',',
'  merged: \'已归并\',',
'  excluded: \'已排除\'',
'};',
'',
'var IMPORT_SOURCE_LABELS = {',
'  initial: \'首次导入\',',
'  incremental: \'增量导入\',',
'  manual: \'人工补录\'',
'};',
'',
'var state = {',
'  batches: [],',
'  currentBatchId: null,',
'  currentBatch: null,',
'  records: [],',
'  selectedRecordIds: [],',
'  currentRecord: null,',
'  mergeTargetId: null',
'};',
'',
'function showToast(message, type) {',
'  type = type || \'success\';',
'  var toast = document.getElementById(\'toast\');',
'  toast.textContent = message;',
'  toast.className = \'toast \' + type;',
'  toast.style.display = \'block\';',
'  setTimeout(function() {',
'    toast.style.display = \'none\';',
'  }, 3000);',
'}',
'',
'function closeModal(modalId) {',
'  document.getElementById(modalId).style.display = \'none\';',
'}',
'',
'function openModal(modalId) {',
'  document.getElementById(modalId).style.display = \'flex\';',
'}',
'',
'function formatDate(dateStr) {',
'  if (!dateStr) return \'-\';',
'  var date = new Date(dateStr);',
'  return date.toLocaleString(\'zh-CN\', {',
'    year: \'numeric\',',
'    month: \'2-digit\',',
'    day: \'2-digit\',',
'    hour: \'2-digit\',',
'    minute: \'2-digit\'',
'  });',
'}',
'',
'async function loadBatches() {',
'  try {',
'    var res = await fetch(API_BASE + \'/batches\');',
'    state.batches = await res.json();',
'    renderBatchList();',
'  } catch (e) {',
'    console.error(\'加载批次列表失败:\', e);',
'  }',
'}',
'',
'function renderBatchList() {',
'  var container = document.getElementById(\'batchList\');',
'',
'  if (state.batches.length === 0) {',
'    container.innerHTML = \'<p style="color: #999; font-size: 12px; text-align: center; padding: 20px 0;">暂无批次</p>\';',
'    return;',
'  }',
'',
'  container.innerHTML = state.batches.map(function(batch) {',
'    var html = \'<div class="batch-item \' + (batch.id === state.currentBatchId ? \'active\' : \'\') + \'" \';',
'    html += \'onclick="selectBatch(\\\'\' + batch.id + \'\\\')">\';',
'    html += \'<div class="batch-item-name">\' + batch.name + \'</div>\';',
'    html += \'<div class="batch-item-meta">\';',
'    html += \'<span>\' + batch.recordCount + \' 条记录</span>\';',
'    if (batch.issueCount > 0) {',
'      html += \'<span class="batch-item-issue">\' + batch.issueCount + \' 个问题</span>\';',
'    }',
'    html += \'</div>\';',
'    html += \'</div>\';',
'    return html;',
'  }).join(\'\');',
'}',
'',
'async function selectBatch(batchId) {',
'  state.currentBatchId = batchId;',
'  state.selectedRecordIds = [];',
'  renderBatchList();',
'',
'  try {',
'    var res = await fetch(API_BASE + \'/batches/\' + batchId);',
'    var data = await res.json();',
'    state.currentBatch = data.batch;',
'    state.records = data.records;',
'',
'    renderBatchDetail();',
'    renderRecords();',
'    renderCheckResult(data.checkResult);',
'',
'  } catch (e) {',
'    console.error(\'加载批次详情失败:\', e);',
'    showToast(\'加载批次详情失败\', \'error\');',
'  }',
'}',
'',
'function renderBatchDetail() {',
'  var batch = state.currentBatch;',
'',
'  document.getElementById(\'emptyState\').style.display = \'none\';',
'  document.getElementById(\'batchDetail\').style.display = \'block\';',
'',
'  document.getElementById(\'batchName\').textContent = batch.name;',
'  document.getElementById(\'batchFile\').textContent = batch.fileName;',
'  document.getElementById(\'batchTime\').textContent = formatDate(batch.createdAt);',
'  document.getElementById(\'batchNotes\').value = batch.importNotes || \'\';',
'}',
'',
'function renderRecords() {',
'  var statusFilter = document.getElementById(\'statusFilter\').value;',
'  var userIdFilter = document.getElementById(\'userIdFilter\').value.trim().toLowerCase();',
'',
'  var filtered = state.records;',
'',
'  if (statusFilter) {',
'    filtered = filtered.filter(function(r) { return r.status === statusFilter; });',
'  }',
'  if (userIdFilter) {',
'    filtered = filtered.filter(function(r) { return r.userId.toLowerCase().indexOf(userIdFilter) !== -1; });',
'  }',
'',
'  document.getElementById(\'recordCount\').textContent = \'共 \' + filtered.length + \' 条\';',
'',
'  var tbody = document.getElementById(\'recordsTableBody\');',
'  tbody.innerHTML = filtered.map(function(record) {',
'    var html = \'<tr class="\' + (record.status === \'duplicate_user\' ? \'duplicate\' : \'\') + \'">\';',
'    html += \'<td><input type="checkbox" class="record-checkbox" \';',
'    html += (state.selectedRecordIds.indexOf(record.id) !== -1 ? \'checked\' : \'\') + \' \';',
'    html += \'onchange="toggleRecordSelection(\\\'\' + record.id + \'\\\')"></td>\';',
'    html += \'<td><strong>L\' + record.originalLineNumber + \'</strong></td>\';',
'    html += \'<td>\' + (IMPORT_SOURCE_LABELS[record.importSource] || record.importSource || \'-\') + \'</td>\';',
'    html += \'<td>\' + record.userId + \'</td>\';',
'    var qText = record.questionText.length > 60 ? record.questionText.substr(0, 60) + \'...\' : record.questionText;',
'    html += \'<td>\' + qText + \'</td>\';',
'    html += \'<td><span class="status-tag status-\' + record.status + \'">\';',
'    html += STATUS_LABELS[record.status] + \'</span></td>\';',
'    html += \'<td>\' + (record.statusUpdatedBy || \'-\') + \'</td>\';',
'    html += \'<td>\';',
'    html += \'<button class="action-btn" onclick="viewRecordDetail(\\\'\' + record.id + \'\\\')">详情</button>\';',
'    html += \'</td>\';',
'    html += \'</tr>\';',
'    return html;',
'  }).join(\'\');',
'',
'  updateMergeBar();',
'}',
'',
'function toggleRecordSelection(recordId) {',
'  var idx = state.selectedRecordIds.indexOf(recordId);',
'  if (idx === -1) {',
'    state.selectedRecordIds.push(recordId);',
'  } else {',
'    state.selectedRecordIds.splice(idx, 1);',
'  }',
'',
'  var selectAll = document.getElementById