const ORDER_STATUS = {
  PENDING: 'PENDING',
  IN_USE: 'IN_USE',
  CHECKING: 'CHECKING',
  FEE_CALCULATED: 'FEE_CALCULATED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUND_PROCESSING: 'REFUND_PROCESSING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const ORDER_STATUS_FLOW = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.IN_USE, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.IN_USE]: [ORDER_STATUS.CHECKING],
  [ORDER_STATUS.CHECKING]: [ORDER_STATUS.FEE_CALCULATED, ORDER_STATUS.CHECKING],
  [ORDER_STATUS.FEE_CALCULATED]: [ORDER_STATUS.REFUND_PENDING, ORDER_STATUS.CHECKING],
  [ORDER_STATUS.REFUND_PENDING]: [ORDER_STATUS.REFUND_PROCESSING, ORDER_STATUS.CHECKING],
  [ORDER_STATUS.REFUND_PROCESSING]: [ORDER_STATUS.COMPLETED, ORDER_STATUS.REFUND_PENDING],
  [ORDER_STATUS.CANCELLED]: [],
  [ORDER_STATUS.COMPLETED]: []
};

const REFUND_QUEUE_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  MANUAL_REVIEW: 'MANUAL_REVIEW'
};

const REFUND_METHOD = {
  CASH: 'CASH',
  BANK_TRANSFER: 'BANK_TRANSFER',
  ORIGINAL_PAYMENT: 'ORIGINAL_PAYMENT'
};

const DAMAGE_DEGREE = {
  NONE: 'NONE',
  MINOR: 'MINOR',
  MODERATE: 'MODERATE',
  SEVERE: 'SEVERE',
  TOTAL_LOSS: 'TOTAL_LOSS'
};

const UTILITY_TYPE = {
  WATER: 'WATER',
  ELECTRICITY: 'ELECTRICITY'
};

const ADJUSTMENT_TYPE = {
  DAMAGE: 'DAMAGE',
  UTILITY: 'UTILITY',
  OTHER: 'OTHER',
  REFUND: 'REFUND'
};

const REPORT_TYPE = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY'
};

const MODULES = {
  ORDER: 'ORDER',
  CHECKLIST: 'CHECKLIST',
  DAMAGE: 'DAMAGE',
  UTILITY: 'UTILITY',
  FEE: 'FEE',
  REFUND: 'REFUND',
  REPORT: 'REPORT'
};

module.exports = {
  ORDER_STATUS,
  ORDER_STATUS_FLOW,
  REFUND_QUEUE_STATUS,
  REFUND_METHOD,
  DAMAGE_DEGREE,
  UTILITY_TYPE,
  ADJUSTMENT_TYPE,
  REPORT_TYPE,
  MODULES
};
