function showHelp() {
  console.log('');
  console.log('🚗 机场贵宾车动态调派 CLI (Airport VIP Dispatch CLI)');
  console.log('='.repeat(60));
  console.log('');
  console.log('基于航班延误、航站楼位置和车型偏好的智能调派系统');
  console.log('');
  console.log('【使用方法】');
  console.log('  node src/index.js <命令> [参数]');
  console.log('');
  console.log('【可用命令】');
  console.log('');
  console.log('  初始化与数据管理:');
  console.log('    init              初始化样例数据（航班、车辆、司机）');
  console.log('    import <文件>      从JSON文件导入数据');
  console.log('    status             显示系统当前状态');
  console.log('');
  console.log('  查看与列表:');
  console.log('    list flights       查看所有航班');
  console.log('    list vehicles      查看所有车辆');
  console.log('    list drivers       查看所有司机');
  console.log('    list dispatches    查看所有调派记录');
  console.log('    history [数量]     查看调派历史（默认最近10条）');
  console.log('');
  console.log('  核心业务:');
  console.log('    dispatch <航班ID>  为指定航班执行调派');
  console.log('    run               执行完整调派流程（所有航班）');
  console.log('    check             检查调派冲突');
  console.log('');
  console.log('  动态调整:');
  console.log('    delay <航班ID> <分钟> [原因]  更新航班延误并重算调派');
  console.log('');
  console.log('  报告导出:');
  console.log('    export [格式] [文件名]  导出报告 (json/text)');
  console.log('');
  console.log('  其他:');
  console.log('    --help, -h        显示帮助信息');
  console.log('    --version, -v     显示版本号');
  console.log('');
  console.log('【业务辨识度】');
  console.log('  ✅ 航班延误：根据延误程度调整优先级和接驾时间');
  console.log('  ✅ 航站楼位置：计算车辆基地到登机口的距离影响评分');
  console.log('  ✅ 车型偏好：优先匹配贵宾指定的车型，不匹配时扣分');
  console.log('');
  console.log('【快速开始】');
  console.log('  1. 初始化: node src/index.js init');
  console.log('  2. 查看航班: node src/index.js list flights');
  console.log('  3. 执行调派: node src/index.js dispatch FLIGHT-001');
  console.log('  4. 检查冲突: node src/index.js check');
  console.log('  5. 模拟延误: node src/index.js delay FLIGHT-002 60 天气原因');
  console.log('  6. 导出报告: node src/index.js export text');
  console.log('');
  console.log('【异常操作示例】');
  console.log('  1. 调派不存在的航班: node src/index.js dispatch INVALID_ID');
  console.log('  2. 导入不存在的文件: node src/index.js import /tmp/not-exist.json');
  console.log('  3. 延误参数错误: node src/index.js delay FLIGHT-001 abc');
  console.log('');
}

module.exports = { showHelp };
