from datetime import datetime
from typing import List

from models import RawRecord


def build_student_draft_records() -> List[RawRecord]:
    return [
        RawRecord(
            record_id="R001",
            category="运输成本",
            metric_name="运输距离",
            value=120.5,
            unit="km",
            dimension="距离",
            source="学生草稿-第1页",
            submitted_at=datetime(2026, 6, 15, 10, 30),
        ),
        RawRecord(
            record_id="R002",
            category="运输成本",
            metric_name="运输距离",
            value=5000.0,
            unit="m",
            dimension="距离",
            source="学生草稿-第1页",
            submitted_at=datetime(2026, 6, 15, 10, 32),
        ),
        RawRecord(
            record_id="R003",
            category="运输成本",
            metric_name="运输工时",
            value=8.5,
            unit="h",
            dimension="时间",
            source="学生草稿-第2页",
            submitted_at=datetime(2026, 6, 15, 11, 5),
        ),
        RawRecord(
            record_id="R004",
            category="运输成本",
            metric_name="运输工时",
            value=120.0,
            unit="min",
            dimension="时间",
            source="学生草稿-第2页",
            submitted_at=datetime(2026, 6, 15, 11, 7),
        ),
        RawRecord(
            record_id="R005",
            category="运输成本",
            metric_name="运输费用",
            value=3.2,
            unit="万元",
            dimension="金额",
            source="学生草稿-第3页",
            submitted_at=datetime(2026, 6, 15, 14, 20),
        ),
        RawRecord(
            record_id="R006",
            category="人力投入",
            metric_name="人工工时",
            value=160.0,
            unit="h",
            dimension="时间",
            source="学生草稿-第4页",
            submitted_at=datetime(2026, 6, 15, 14, 35),
        ),
        RawRecord(
            record_id="R007",
            category="人力投入",
            metric_name="人力成本",
            value=48000.0,
            unit="元",
            dimension="金额",
            source="学生草稿-第4页",
            submitted_at=datetime(2026, 6, 15, 14, 40),
        ),
        RawRecord(
            record_id="R008",
            category="物料消耗",
            metric_name="物料重量",
            value=2.5,
            unit="t",
            dimension="重量",
            source="学生草稿-第5页",
            submitted_at=datetime(2026, 6, 15, 15, 10),
        ),
        RawRecord(
            record_id="R009",
            category="物料消耗",
            metric_name="物料数量",
            value=120,
            unit="件",
            dimension="数量",
            source="学生草稿-第5页",
            submitted_at=datetime(2026, 6, 15, 15, 12),
        ),
        RawRecord(
            record_id="R010",
            category="设备折旧",
            metric_name="设备台数",
            value=5,
            unit="台",
            dimension="数量",
            source="学生草稿-第6页",
            submitted_at=datetime(2026, 6, 15, 16, 0),
        ),
        RawRecord(
            record_id="R011",
            category="运输成本",
            metric_name="运输距离",
            value=80.0,
            unit=None,
            dimension="距离",
            source="学生草稿-第1页（随手写，漏掉单位）",
            submitted_at=datetime(2026, 6, 15, 10, 45),
        ),
        RawRecord(
            record_id="R012",
            category="物料消耗",
            metric_name="物料重量",
            value=500.0,
            unit="km",
            dimension="重量",
            source="学生草稿-第5页（单位写错，应为kg）",
            submitted_at=datetime(2026, 6, 15, 15, 20),
        ),
        RawRecord(
            record_id="R013",
            category="人力投入",
            metric_name="加班工时",
            value=24,
            unit="h",
            dimension="时间",
            source="学生草稿-第4页（后补说明）",
            submitted_at=datetime(2026, 6, 16, 9, 0),
            supplementary_note="6月15日晚学生补记：周末加班24小时未计入初稿",
        ),
        RawRecord(
            record_id="R014",
            category="设备折旧",
            metric_name="折旧金额",
            value=12000,
            unit="元",
            dimension="金额",
            source="学生草稿-第6页（公式对但单位可能需要核对）",
            submitted_at=datetime(2026, 6, 15, 16, 15),
        ),
        RawRecord(
            record_id="R015",
            category="运输成本",
            metric_name="运输费用占比",
            value=35.5,
            unit="%",
            dimension="百分比",
            source="学生草稿-第3页",
            submitted_at=datetime(2026, 6, 15, 14, 25),
        ),
    ]


def build_late_attachment_record() -> RawRecord:
    return RawRecord(
        record_id="R016",
        category="运输成本",
        metric_name="运输距离（晚到附件）",
        value=45,
        unit="公里",
        dimension="距离",
        source="6月17日补交的扫描附件-路线B实测",
        submitted_at=datetime(2026, 6, 17, 8, 30),
        is_late=True,
    )


def build_supplementary_only_record() -> RawRecord:
    return RawRecord(
        record_id="R017",
        category="物料消耗",
        metric_name="紧急采购物料",
        value=50,
        unit="kg",
        dimension="重量",
        source="6月18日后补说明邮件",
        submitted_at=datetime(2026, 6, 18, 11, 0),
        supplementary_note="学生说明：R009物料数量120件中有50kg是临采，原草稿未区分重量",
    )
