import type { Building, SolarPanel, Inverter, Scheme } from "@/types"

const buildings: Building[] = [
  {
    id: "b1",
    name: "车间A栋",
    x: 0,
    y: 0,
    width: 30,
    depth: 15,
    height: 12,
    floor: "1",
    photoUrl: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=industrial%20factory%20building%20exterior%20modern%20solar%20park&image_size=landscape_4_3",
    status: "normal",
    anomalyNote: "",
  },
  {
    id: "b2",
    name: "车间B栋",
    x: 50,
    y: 0,
    width: 30,
    depth: 15,
    height: 10,
    floor: "1",
    photoUrl: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=warehouse%20building%20flat%20roof%20industrial%20park&image_size=landscape_4_3",
    status: "normal",
    anomalyNote: "",
  },
  {
    id: "b3",
    name: "综合楼",
    x: 25,
    y: 50,
    width: 20,
    depth: 20,
    height: 25,
    floor: "2-3",
    photoUrl: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=office%20building%20mixed%20use%20industrial%20complex&image_size=landscape_4_3",
    status: "boundary",
    anomalyNote: "floor字段为'2-3'，跨两个楼层，请确认实际层数",
  },
  {
    id: "b4",
    name: "配电房",
    x: 150,
    y: 20,
    width: 10,
    depth: 8,
    height: 5,
    floor: "1",
    photoUrl: "",
    status: "offset",
    anomalyNote: "坐标偏移约50米，疑似测量错误，与园区总平面图不一致",
  },
]

const panels: SolarPanel[] = [
  {
    id: "p1",
    name: "光伏板A-01",
    x: 5,
    y: 20,
    width: 2,
    height: 1,
    tiltAngle: 25,
    azimuth: 180,
    inverterId: "inv1",
    photoUrl: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=solar%20panel%20photovoltaic%20module%20rooftop&image_size=landscape_4_3",
    status: "normal",
    anomalyNote: "",
    shadowCoverage: 0.15,
  },
  {
    id: "p2",
    name: "光伏板A-02",
    x: 10,
    y: 20,
    width: 2,
    height: 1,
    tiltAngle: 25,
    azimuth: 180,
    inverterId: "inv1",
    photoUrl: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=solar%20panel%20photovoltaic%20module%20close%20up&image_size=landscape_4_3",
    status: "normal",
    anomalyNote: "",
    shadowCoverage: 0.35,
  },
  {
    id: "p3",
    name: "光伏板A-03",
    x: 15,
    y: 20,
    width: 2,
    height: 1,
    tiltAngle: 25,
    azimuth: 180,
    inverterId: "inv1",
    photoUrl: "",
    status: "missing_photo",
    anomalyNote: "缺少现场照片",
    shadowCoverage: 0.6,
  },
  {
    id: "p4",
    name: "光伏板B-01",
    x: 55,
    y: 20,
    width: 2,
    height: 1,
    tiltAngle: 20,
    azimuth: 180,
    inverterId: "inv2",
    photoUrl: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=solar%20panel%20array%20industrial%20rooftop&image_size=landscape_4_3",
    status: "normal",
    anomalyNote: "",
    shadowCoverage: 0.05,
  },
  {
    id: "p5",
    name: "光伏板B-02",
    x: 60,
    y: 20,
    width: 2,
    height: 1,
    tiltAngle: 20,
    azimuth: 180,
    inverterId: "inv2",
    photoUrl: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=photovoltaic%20module%20installation&image_size=landscape_4_3",
    status: "normal",
    anomalyNote: "",
    shadowCoverage: 0.1,
  },
  {
    id: "p6",
    name: "光伏板C-01",
    x: 30,
    y: 75,
    width: 2,
    height: 1,
    tiltAngle: 30,
    azimuth: 180,
    inverterId: "inv3",
    photoUrl: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=solar%20panel%20on%20building%20roof&image_size=landscape_4_3",
    status: "normal",
    anomalyNote: "",
    shadowCoverage: 0.8,
  },
]

const inverters: Inverter[] = [
  {
    id: "inv1",
    name: "逆变器A-01",
    aliasName: "逆变A01",
    x: 8,
    y: 18,
    floor: "1",
    buildingId: "b1",
    photoUrl: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=inverter%20device%20solar%20power%20system&image_size=landscape_4_3",
    status: "duplicate",
    anomalyNote: "名称'逆变器A-01'与'逆变A01'疑似同一设备，请确认",
  },
  {
    id: "inv2",
    name: "逆变器B-01",
    aliasName: "",
    x: 58,
    y: 18,
    floor: "1",
    buildingId: "b2",
    photoUrl: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=solar%20inverter%20equipment%20cabinet&image_size=landscape_4_3",
    status: "normal",
    anomalyNote: "",
  },
  {
    id: "inv3",
    name: "逆变器C-01",
    aliasName: "",
    x: 32,
    y: 73,
    floor: "1",
    buildingId: "",
    photoUrl: "https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=solar%20inverter%20wall%20mounted&image_size=landscape_4_3",
    status: "empty_value",
    anomalyNote: "buildingId为空，未关联建筑",
  },
]

export const sampleScheme: Scheme = {
  id: "sample-001",
  name: "示范园区-初始方案",
  latitude: 31.23,
  longitude: 121.47,
  date: "2025-06-15",
  time: "14:00",
  sunAltitude: 65,
  sunAzimuth: 210,
  buildings,
  panels,
  inverters,
  createdAt: "2025-06-01T10:00:00Z",
  updatedAt: "2025-06-01T10:00:00Z",
  note: "周会讨论用的初始方案，含已知异常",
}
