import { useEffect, useCallback } from 'react';
import {
  parseSurfaceEquation,
  generateSurfaceVertices,
  computeSurfaceNormals,
  generateBoundaryPoints,
  generateSamplePoints,
} from '../utils/math/surface';
import { generateGridIndices } from '../utils/math/geometry';
import { useSurfaceStore } from '../stores/useSurfaceStore';
import { useHistoryStore } from '../stores/useHistoryStore';
import { useViewStore } from '../stores/useViewStore';
import { DEMO_MATERIALS, DEMO_SURFACE_CONFIG, generateId } from '../data/demoData';
import type { DataMaterial, Point3D, Vector3D, UVPoint } from '../types/surface';
import { useFilterStore } from '../stores/useFilterStore';

interface InitOptions {
  loadDemo?: boolean;
  createSession?: boolean;
}

export function useSurfaceInit(options: InitOptions = {}) {
  const { loadDemo = true, createSession: autoCreateSession = true } = options;

  const {
    setSurfaceData,
    addMaterial,
    clearAll,
    materials,
    vertices,
    normals,
    uvs,
    indices,
    boundaryPoints,
    samplePoints,
    isLoaded,
  } = useSurfaceStore();

  const { createSession, addEntry, loadFromLocalStorage } = useHistoryStore();
  const { cameraPosition, cameraTarget, filterRange } = useViewStore();
  const { setLocked } = useFilterStore();

  const loadDemoData = useCallback(async () => {
    clearAll();

    DEMO_MATERIALS.forEach((material) => {
      addMaterial({ ...material, id: generateId(`mat_${material.type}`) });
    });

    await new Promise((resolve) => setTimeout(resolve, 100));

    const surfaceMaterial = DEMO_MATERIALS.find((m) => m.type === 'surface');
    if (!surfaceMaterial || !surfaceMaterial.equation) return;

    const surfaceFn = parseSurfaceEquation(
      surfaceMaterial.equation,
      surfaceMaterial.uvRange || { u: [-1, 1], v: [-1, 1] }
    );

    const resolution = surfaceMaterial.sampleDensity || 64;
    const { vertices: verts, uvs: uvCoords } = generateSurfaceVertices(surfaceFn, resolution);
    const norms = computeSurfaceNormals(verts, resolution);
    const inds = generateGridIndices(resolution, resolution);
    const bounds = generateBoundaryPoints(surfaceFn, 64);
    const samples = generateSamplePoints(surfaceFn, 30, 12345);

    const boundaryMat: DataMaterial = {
      id: generateId('mat_boundary'),
      name: '边界曲线（自动生成）',
      type: 'boundary',
      status: 'raw',
      source: 'generated',
      importedAt: Date.now(),
      points: bounds,
      sampleDensity: bounds.length,
      metadata: { autoGenerated: true, resolution: 64 },
    };

    const sampleMat: DataMaterial = {
      id: generateId('mat_sample'),
      name: '采样点集（自动生成）',
      type: 'sample',
      status: 'raw',
      source: 'generated',
      importedAt: Date.now(),
      points: samples,
      sampleDensity: samples.length,
      metadata: { autoGenerated: true, seed: 12345 },
    };

    addMaterial(boundaryMat);
    addMaterial(sampleMat);

    setSurfaceData({
      vertices: verts,
      normals: norms,
      uvs: uvCoords,
      indices: inds,
      boundaryPoints: bounds,
      samplePoints: samples,
    });

    if (autoCreateSession) {
      const sessionId = createSession('曲面积分演示 - 抛物面');
      addEntry({
        action: 'INIT',
        description: '加载演示数据：旋转抛物面 z = x² + y²',
        parameters: {
          equation: surfaceMaterial.equation,
          resolution,
          uvRange: surfaceMaterial.uvRange,
        },
        viewState: {
          cameraPosition,
          cameraTarget,
          filterRange,
        },
        materialsSnapshot: [...DEMO_MATERIALS, boundaryMat, sampleMat].map((m) => ({
          ...m,
          id: m.id || generateId(`mat_${m.type}`),
        })),
        issuesSnapshot: [],
        note: '初始加载演示数据，包含抛物面曲面、边界曲线和采样点集',
      });
    }
  }, [
    clearAll,
    addMaterial,
    setSurfaceData,
    createSession,
    addEntry,
    cameraPosition,
    cameraTarget,
    filterRange,
    autoCreateSession,
  ]);

  const loadFromMaterials = useCallback(
    (surfaceMat: DataMaterial) => {
      if (!surfaceMat.equation || !surfaceMat.uvRange) return;

      const surfaceFn = parseSurfaceEquation(surfaceMat.equation, surfaceMat.uvRange);
      const resolution = surfaceMat.sampleDensity || 64;
      const { vertices: verts, uvs: uvCoords } = generateSurfaceVertices(surfaceFn, resolution);
      const norms = computeSurfaceNormals(verts, resolution);
      const inds = generateGridIndices(resolution, resolution);

      let bounds: Point3D[] = [];
      const boundaryMat = materials.find((m) => m.type === 'boundary');
      if (boundaryMat?.points) {
        bounds = boundaryMat.points;
      } else {
        bounds = generateBoundaryPoints(surfaceFn, 64);
      }

      let samples: Point3D[] = [];
      const sampleMat = materials.find((m) => m.type === 'sample');
      if (sampleMat?.points) {
        samples = sampleMat.points;
      } else {
        samples = generateSamplePoints(surfaceFn, 30, Date.now());
      }

      setSurfaceData({
        vertices: verts,
        normals: norms,
        uvs: uvCoords,
        indices: inds,
        boundaryPoints: bounds,
        samplePoints: samples,
      });

      addEntry({
        action: 'UPDATE_SURFACE',
        description: `更新曲面: ${surfaceMat.name}`,
        parameters: {
          equation: surfaceMat.equation,
          resolution,
          materialId: surfaceMat.id,
        },
        viewState: {
          cameraPosition,
          cameraTarget,
          filterRange,
        },
        materialsSnapshot: materials,
        issuesSnapshot: [],
      });
    },
    [materials, setSurfaceData, addEntry, cameraPosition, cameraTarget, filterRange]
  );

  const flipNormals = useCallback(
    (indicesToFlip?: number[]) => {
      const newNormals: Vector3D[] = normals.map((n, i) => {
        if (!indicesToFlip || indicesToFlip.includes(i)) {
          return { x: -n.x, y: -n.y, z: -n.z };
        }
        return n;
      });

      setSurfaceData({ normals: newNormals });

      addEntry({
        action: 'FLIP_NORMALS',
        description: `翻转法向量 ${indicesToFlip ? `(${indicesToFlip.length}个顶点)` : '(全部)'}`,
        parameters: { flippedCount: indicesToFlip?.length || normals.length, indices: indicesToFlip },
        viewState: {
          cameraPosition,
          cameraTarget,
          filterRange,
        },
        materialsSnapshot: materials.map((m) => ({ ...m, status: 'processed' as const })),
        issuesSnapshot: [],
        note: '修正法向量方向',
      });

      const surfaceMat = materials.find((m) => m.type === 'surface');
      if (surfaceMat) {
        const { updateMaterial } = useSurfaceStore.getState();
        updateMaterial(surfaceMat.id, { status: 'processed' });
      }
    },
    [normals, setSurfaceData, addEntry, cameraPosition, cameraTarget, filterRange, materials]
  );

  const closeBoundary = useCallback(() => {
    if (boundaryPoints.length < 2) return;

    const first = boundaryPoints[0];
    const last = boundaryPoints[boundaryPoints.length - 1];
    const newPoints = [...boundaryPoints];

    const steps = Math.ceil(Math.max(Math.abs(first.x - last.x), Math.abs(first.y - last.y), Math.abs(first.z - last.z)) / 0.01);
    for (let i = 1; i < steps; i++) {
      const t = i / steps;
      newPoints.push({
        x: last.x + (first.x - last.x) * t,
        y: last.y + (first.y - last.y) * t,
        z: last.z + (first.z - last.z) * t,
      });
    }

    setSurfaceData({ boundaryPoints: newPoints });

    addEntry({
      action: 'CLOSE_BOUNDARY',
      description: `闭合边界曲线，补充 ${steps - 1} 个点`,
      parameters: { gapPoints: steps, originalCount: boundaryPoints.length, newCount: newPoints.length },
      viewState: {
        cameraPosition,
        cameraTarget,
        filterRange,
      },
      materialsSnapshot: materials.map((m) => (m.type === 'boundary' ? { ...m, status: 'processed' as const } : m)),
      issuesSnapshot: [],
      note: '插值补全边界缺口',
    });

    const boundaryMat = materials.find((m) => m.type === 'boundary');
    if (boundaryMat) {
      const { updateMaterial } = useSurfaceStore.getState();
      updateMaterial(boundaryMat.id, { status: 'processed', points: newPoints });
    }
  }, [boundaryPoints, setSurfaceData, addEntry, cameraPosition, cameraTarget, filterRange, materials]);

  const densifySamples = useCallback(
    (targetDensity: number = 50) => {
      const surfaceMat = materials.find((m) => m.type === 'surface');
      if (!surfaceMat?.equation || !surfaceMat.uvRange) return;

      const surfaceFn = parseSurfaceEquation(surfaceMat.equation, surfaceMat.uvRange);
      const currentCount = samplePoints.length;
      const additionalCount = Math.max(0, targetDensity - currentCount);
      const newSamples = generateSamplePoints(surfaceFn, additionalCount, Date.now());

      const combined = [...samplePoints, ...newSamples];
      setSurfaceData({ samplePoints: combined });

      addEntry({
        action: 'DENSIFY_SAMPLES',
        description: `加密采样点，新增 ${additionalCount} 个点`,
        parameters: {
          originalCount: currentCount,
          newCount: combined.length,
          targetDensity,
        },
        viewState: {
          cameraPosition,
          cameraTarget,
          filterRange,
        },
        materialsSnapshot: materials.map((m) => (m.type === 'sample' ? { ...m, status: 'processed' as const, points: combined } : m)),
        issuesSnapshot: [],
        note: '自动补充采样点以满足密度要求',
      });

      const sampleMat = materials.find((m) => m.type === 'sample');
      if (sampleMat) {
        const { updateMaterial } = useSurfaceStore.getState();
        updateMaterial(sampleMat.id, {
          status: 'processed',
          points: combined,
          sampleDensity: combined.length,
        });
      }
    },
    [materials, samplePoints, setSurfaceData, addEntry, cameraPosition, cameraTarget, filterRange]
  );

  useEffect(() => {
    if (loadDemo && !isLoaded) {
      loadDemoData();
    }
    loadFromLocalStorage();
  }, [loadDemo, isLoaded, loadDemoData, loadFromLocalStorage]);

  return {
    loadDemoData,
    loadFromMaterials,
    flipNormals,
    closeBoundary,
    densifySamples,
    isLoaded,
  };
}
