import type { LevelConfig } from '@/types/game';

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: '新手演练',
    description: '低楼层，少量电梯，适合熟悉操作。只有2部电梯，1支维保队，节奏较慢。',
    difficulty: 'easy',
    floorCount: 6,
    elevatorCount: 2,
    teamCount: 1,
    gameDuration: 180,
    faultInterval: [15, 25],
    maxConcurrentFaults: 1,
    passengerRange: [2, 5],
    conflictPenalty: 50,
    panicPenalty: 100,
    rescueBonus: 200,
    winCondition: 'all_rescued',
  },
  {
    id: 2,
    name: '日常值班',
    description: '中等规模写字楼，4部电梯，2支维保队，故障频率适中。',
    difficulty: 'easy',
    floorCount: 10,
    elevatorCount: 4,
    teamCount: 2,
    gameDuration: 240,
    faultInterval: [12, 20],
    maxConcurrentFaults: 2,
    passengerRange: [3, 8],
    conflictPenalty: 80,
    panicPenalty: 150,
    rescueBonus: 250,
    winCondition: 'all_rescued',
  },
  {
    id: 3,
    name: '早高峰挑战',
    description: '早高峰时段，电梯使用频繁，故障多发。6部电梯，3支维保队，需要高效调度。',
    difficulty: 'medium',
    floorCount: 15,
    elevatorCount: 6,
    teamCount: 3,
    gameDuration: 300,
    faultInterval: [8, 15],
    maxConcurrentFaults: 3,
    passengerRange: [5, 12],
    conflictPenalty: 100,
    panicPenalty: 200,
    rescueBonus: 300,
    winCondition: 'score_threshold',
    winScore: 2000,
  },
  {
    id: 4,
    name: '老旧楼宇危机',
    description: '设施老化的楼宇，电梯故障频发且类型复杂。误判率高，需要仔细判断故障类型。',
    difficulty: 'medium',
    floorCount: 12,
    elevatorCount: 5,
    teamCount: 2,
    gameDuration: 300,
    faultInterval: [6, 12],
    maxConcurrentFaults: 4,
    passengerRange: [4, 10],
    conflictPenalty: 120,
    panicPenalty: 250,
    rescueBonus: 350,
    winCondition: 'score_threshold',
    winScore: 2500,
  },
  {
    id: 5,
    name: '超高层应急',
    description: '30层超高层建筑，8部电梯，4支维保队，楼层高导致移动时间长，调度难度大。',
    difficulty: 'hard',
    floorCount: 30,
    elevatorCount: 8,
    teamCount: 4,
    gameDuration: 360,
    faultInterval: [5, 10],
    maxConcurrentFaults: 5,
    passengerRange: [8, 15],
    conflictPenalty: 150,
    panicPenalty: 300,
    rescueBonus: 400,
    winCondition: 'score_threshold',
    winScore: 4000,
  },
  {
    id: 6,
    name: '灾难级故障',
    description: '极端场景，多部电梯同时故障，维保队严重不足。考验玩家的优先级判断能力。',
    difficulty: 'hard',
    floorCount: 20,
    elevatorCount: 8,
    teamCount: 3,
    gameDuration: 300,
    faultInterval: [3, 8],
    maxConcurrentFaults: 6,
    passengerRange: [6, 18],
    conflictPenalty: 200,
    panicPenalty: 400,
    rescueBonus: 500,
    winCondition: 'score_threshold',
    winScore: 5000,
  },
];

export const FAULT_TYPE_NAMES: Record<string, string> = {
  door_jam: '门卡阻',
  power_out: '停电',
  overload: '超载',
  false_alarm: '误报',
  cable_issue: '缆绳异常',
};

export const FAULT_RESCUE_TIMES: Record<string, number> = {
  door_jam: 8,
  power_out: 15,
  overload: 5,
  false_alarm: 3,
  cable_issue: 20,
};

export const MOOD_NAMES: Record<string, string> = {
  calm: '平静',
  anxious: '焦虑',
  panic: '恐慌',
};

export const TEAM_STATUS_NAMES: Record<string, string> = {
  idle: '待命',
  moving: '前往中',
  working: '救援中',
  conflict: '冲突',
};

export const ELEVATOR_STATUS_NAMES: Record<string, string> = {
  normal: '正常',
  fault: '故障',
  rescuing: '救援中',
  rescued: '已救援',
};
