import type { InventoryRecord, OperationLog, PermissionChange } from '@/types';
import { generateId, formatDateTime } from './index';

const now = new Date();
const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);
const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000);

export const mockRecords: InventoryRecord[] = [
  {
    id: generateId(),
    source: 'api_doc',
    interfaceName: 'preOccupyStock',
    status: 'pending',
    stockCode: 'STK-2024-001',
    preOccupyQty: 100,
    releaseQty: 0,
    operator: '张三',
    pendingReason: '接口文档参数与实际调用不一致，需确认',
    idempotentKey: 'IDEMPOTENT-A1B2C3',
    idempotentValid: true,
    rawData: {
      orderNo: 'ORD-2024-001',
      skuId: 'SKU-001',
      qty: 100,
      warehouse: 'WH-01',
    },
    createdAt: formatDateTime(threeDaysAgo),
    updatedAt: formatDateTime(twoDaysAgo),
  },
  {
    id: generateId(),
    source: 'call_log',
    interfaceName: 'releaseStock',
    status: 'completed',
    stockCode: 'STK-2024-002',
    preOccupyQty: 50,
    releaseQty: 50,
    operator: '李四',
    idempotentKey: 'IDEMPOTENT-D4E5F6',
    idempotentValid: true,
    rawData: {
      orderNo: 'ORD-2024-002',
      skuId: 'SKU-002',
      qty: 50,
      warehouse: 'WH-02',
      releaseReason: '订单完成',
    },
    createdAt: formatDateTime(threeDaysAgo),
    updatedAt: formatDateTime(yesterday),
  },
  {
    id: generateId(),
    source: 'api_doc',
    interfaceName: 'preOccupyStock',
    status: 'error',
    stockCode: 'STK-2024-003',
    preOccupyQty: 200,
    releaseQty: 0,
    operator: '王五',
    pendingReason: '库存不足，预占失败',
    idempotentKey: 'IDEMPOTENT-G7H8I9',
    idempotentValid: false,
    idempotentInvalidReason: '重复调用超过3次',
    idempotentRetryCount: 3,
    rawData: {
      orderNo: 'ORD-2024-003',
      skuId: 'SKU-003',
      qty: 200,
      warehouse: 'WH-01',
      error: 'INSUFFICIENT_STOCK',
    },
    createdAt: formatDateTime(twoDaysAgo),
    updatedAt: formatDateTime(yesterday),
  },
  {
    id: generateId(),
    source: 'manual',
    interfaceName: 'manualAdjust',
    status: 'processing',
    stockCode: 'STK-2024-004',
    preOccupyQty: 75,
    releaseQty: 25,
    operator: '赵六',
    idempotentKey: 'IDEMPOTENT-J0K1L2',
    idempotentValid: true,
    rawData: {
      orderNo: 'ORD-2024-004',
      skuId: 'SKU-004',
      qty: 75,
      warehouse: 'WH-03',
      adjustReason: '客户部分退款',
    },
    createdAt: formatDateTime(twoDaysAgo),
    updatedAt: formatDateTime(now),
  },
  {
    id: generateId(),
    source: 'api_doc',
    interfaceName: 'preOccupyStock',
    status: 'pending',
    stockCode: 'STK-2024-005',
    preOccupyQty: 150,
    releaseQty: 0,
    operator: '张三',
    pendingReason: '等待技术负责人审批权限变更',
    idempotentKey: 'IDEMPOTENT-M3N4O5',
    idempotentValid: true,
    rawData: {
      orderNo: 'ORD-2024-005',
      skuId: 'SKU-005',
      qty: 150,
      warehouse: 'WH-01',
    },
    createdAt: formatDateTime(yesterday),
    updatedAt: formatDateTime(now),
  },
  {
    id: generateId(),
    source: 'call_log',
    interfaceName: 'releaseStock',
    status: 'completed',
    stockCode: 'STK-2024-006',
    preOccupyQty: 30,
    releaseQty: 30,
    operator: '李四',
    idempotentKey: 'IDEMPOTENT-P6Q7R8',
    idempotentValid: true,
    rawData: {
      orderNo: 'ORD-2024-006',
      skuId: 'SKU-006',
      qty: 30,
      warehouse: 'WH-02',
      releaseReason: '订单完成',
    },
    createdAt: formatDateTime(yesterday),
    updatedAt: formatDateTime(now),
  },
  {
    id: generateId(),
    source: 'api_doc',
    interfaceName: 'preOccupyStock',
    status: 'error',
    stockCode: 'STK-2024-007',
    preOccupyQty: 80,
    releaseQty: 0,
    operator: '王五',
    pendingReason: '接口超时，幂等键失效',
    idempotentKey: 'IDEMPOTENT-S9T0U1',
    idempotentValid: false,
    idempotentInvalidReason: '超时后重试，幂等键已过期',
    idempotentRetryCount: 5,
    rawData: {
      orderNo: 'ORD-2024-007',
      skuId: 'SKU-007',
      qty: 80,
      warehouse: 'WH-03',
      error: 'TIMEOUT',
    },
    createdAt: formatDateTime(yesterday),
    updatedAt: formatDateTime(now),
  },
  {
    id: generateId(),
    source: 'api_doc',
    interfaceName: 'batchPreOccupy',
    status: 'processing',
    stockCode: 'STK-2024-008',
    preOccupyQty: 500,
    releaseQty: 0,
    operator: '赵六',
    idempotentKey: 'IDEMPOTENT-V2W3X4',
    idempotentValid: true,
    rawData: {
      orderNo: 'ORD-2024-008',
      skuList: [
        { skuId: 'SKU-008', qty: 200 },
        { skuId: 'SKU-009', qty: 300 },
      ],
      warehouse: 'WH-01',
    },
    createdAt: formatDateTime(now),
    updatedAt: formatDateTime(now),
  },
  {
    id: generateId(),
    source: 'manual',
    interfaceName: 'manualRelease',
    status: 'pending',
    stockCode: 'STK-2024-009',
    preOccupyQty: 60,
    releaseQty: 0,
    operator: '张三',
    pendingReason: '手动释放需复核',
    idempotentKey: 'IDEMPOTENT-Y5Z6A7',
    idempotentValid: true,
    rawData: {
      orderNo: 'ORD-2024-009',
      skuId: 'SKU-010',
      qty: 60,
      warehouse: 'WH-02',
      releaseReason: '订单取消',
    },
    createdAt: formatDateTime(now),
    updatedAt: formatDateTime(now),
  },
  {
    id: generateId(),
    source: 'call_log',
    interfaceName: 'releaseStock',
    status: 'completed',
    stockCode: 'STK-2024-010',
    preOccupyQty: 25,
    releaseQty: 25,
    operator: '李四',
    idempotentKey: 'IDEMPOTENT-B8C9D0',
    idempotentValid: true,
    rawData: {
      orderNo: 'ORD-2024-010',
      skuId: 'SKU-011',
      qty: 25,
      warehouse: 'WH-03',
      releaseReason: '订单完成',
    },
    createdAt: formatDateTime(now),
    updatedAt: formatDateTime(now),
  },
];

export const mockOperationLogs: OperationLog[] = mockRecords.flatMap((record, idx) => {
  const logs: OperationLog[] = [
    {
      id: generateId(),
      recordId: record.id,
      action: 'import',
      operator: record.operator,
      reason: '从旧接口文档导入',
      afterData: { ...record },
      createdAt: record.createdAt,
    },
  ];

  if (record.status !== 'pending' || idx % 2 === 0) {
    logs.push({
      id: generateId(),
      recordId: record.id,
      action: 'review',
      operator: idx % 2 === 0 ? '技术负责人' : '李四',
      reason: record.status === 'error' ? '发现异常，标记处理' : '数据复核通过',
      afterData: { status: record.status },
      createdAt: record.updatedAt,
    });
  }

  if (idx === 2 || idx === 4) {
    logs.push({
      id: generateId(),
      recordId: record.id,
      action: 'modify',
      operator: '王五',
      reason: '修正预占数量',
      beforeData: { preOccupyQty: record.preOccupyQty - 10 },
      afterData: { preOccupyQty: record.preOccupyQty },
      createdAt: record.updatedAt,
    });
  }

  return logs;
});

export const mockPermissionChanges: PermissionChange[] = [
  {
    id: generateId(),
    recordId: mockRecords[4].id,
    operator: '技术负责人',
    beforePermission: {
      canPreOccupy: false,
      canRelease: true,
      warehouse: ['WH-02', 'WH-03'],
      maxQty: 100,
    },
    afterPermission: {
      canPreOccupy: true,
      canRelease: true,
      warehouse: ['WH-01', 'WH-02', 'WH-03'],
      maxQty: 200,
    },
    changeReason: '大促期间临时开放WH-01仓库预占权限',
    diffSnapshot: {
      canPreOccupy: { before: false, after: true },
      warehouse: { before: ['WH-02', 'WH-03'], after: ['WH-01', 'WH-02', 'WH-03'] },
      maxQty: { before: 100, after: 200 },
    },
    createdAt: formatDateTime(yesterday),
  },
  {
    id: generateId(),
    recordId: mockRecords[2].id,
    operator: '王五',
    beforePermission: {
      canPreOccupy: true,
      canRelease: true,
      warehouse: ['WH-01'],
      maxQty: 500,
    },
    afterPermission: {
      canPreOccupy: true,
      canRelease: true,
      warehouse: ['WH-01'],
      maxQty: 100,
    },
    changeReason: '调整最大预占数量，防止超卖',
    diffSnapshot: {
      maxQty: { before: 500, after: 100 },
    },
    createdAt: formatDateTime(twoDaysAgo),
  },
];
