const DonationStatus = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  REFUNDED: 'REFUNDED'
};

const InvoiceStatus = {
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  USED: 'USED',
  CANCELLED: 'CANCELLED'
};

const MergeRequestStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

const InvoiceType = {
  PERSONAL: 'PERSONAL',
  ENTERPRISE: 'ENTERPRISE'
};

const EntityType = {
  DONATION: 'DONATION',
  INVOICE: 'INVOICE',
  MERGE_REQUEST: 'MERGE_REQUEST',
  FUND_USAGE: 'FUND_USAGE'
};

const ERROR_CODES = {
  DUPLICATE_INVOICE: 'DUPLICATE_INVOICE',
  TAX_ID_MISSING: 'TAX_ID_MISSING',
  CROSS_PROJECT_MERGE: 'CROSS_PROJECT_MERGE',
  CANCELLED_INVOICE_DOWNLOAD: 'CANCELLED_INVOICE_DOWNLOAD',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR'
};

module.exports = {
  DonationStatus,
  InvoiceStatus,
  MergeRequestStatus,
  InvoiceType,
  EntityType,
  ERROR_CODES
};
