import { LevelConfig } from '../types';

const createEmptyInventory = () => ({ water: 0, medicine: 0, tent: 0 });

export const LEVELS: LevelConfig[] = [
  {
    id: 'level-1',
    name: '初级训练',
    difficulty: 'easy',
    description: '熟悉基本操作：将物资送到2个安置点',
    initialSupplies: { water: 20, medicine: 10, tent: 5 },
    maxTurns: 15,
    timeLimit: 600,
    eventProbability: 0.1,
    nodes: [
      { id: 'warehouse-1', type: 'warehouse', name: '物资仓库', x: 400, y: 300 },
      { id: 'shelter-1', type: 'shelter', name: '安置点A', x: 150, y: 150, demand: { water: 8, medicine: 4, tent: 2 }, received: createEmptyInventory() },
      { id: 'shelter-2', type: 'shelter', name: '安置点B', x: 650, y: 150, demand: { water: 6, medicine: 3, tent: 2 }, received: createEmptyInventory() },
      { id: 'junction-1', type: 'junction', name: '路口1', x: 400, y: 150 },
    ],
    roads: [
      { id: 'road-1', from: 'warehouse-1', to: 'junction-1', distance: 2, status: 'clear', baseTime: 2 },
      { id: 'road-2', from: 'junction-1', to: 'shelter-1', distance: 2, status: 'clear', baseTime: 2 },
      { id: 'road-3', from: 'junction-1', to: 'shelter-2', distance: 2, status: 'clear', baseTime: 2 },
    ],
    vehicles: [
      {
        id: 'vehicle-1',
        name: '运输车1号',
        maxCapacity: 20,
        currentLoad: createEmptyInventory(),
        currentWeight: 0,
        status: 'idle',
        currentNode: 'warehouse-1',
        targetNodes: [],
        progress: 0,
        speed: 1,
      },
    ],
  },
  {
    id: 'level-2',
    name: '中级挑战',
    difficulty: 'medium',
    description: '应对道路拥堵和天气变化，服务3个安置点',
    initialSupplies: { water: 30, medicine: 15, tent: 8 },
    maxTurns: 20,
    timeLimit: 900,
    eventProbability: 0.25,
    nodes: [
      { id: 'warehouse-1', type: 'warehouse', name: '物资仓库', x: 400, y: 350 },
      { id: 'shelter-1', type: 'shelter', name: '东区安置点', x: 100, y: 100, demand: { water: 10, medicine: 5, tent: 3 }, received: createEmptyInventory() },
      { id: 'shelter-2', type: 'shelter', name: '西区安置点', x: 700, y: 100, demand: { water: 8, medicine: 4, tent: 2 }, received: createEmptyInventory() },
      { id: 'shelter-3', type: 'shelter', name: '南区安置点', x: 400, y: 80, demand: { water: 6, medicine: 3, tent: 2 }, received: createEmptyInventory() },
      { id: 'junction-1', type: 'junction', name: '北路口', x: 400, y: 200 },
      { id: 'junction-2', type: 'junction', name: '东路口', x: 250, y: 150 },
      { id: 'junction-3', type: 'junction', name: '西路口', x: 550, y: 150 },
    ],
    roads: [
      { id: 'road-1', from: 'warehouse-1', to: 'junction-1', distance: 2, status: 'clear', baseTime: 2 },
      { id: 'road-2', from: 'junction-1', to: 'junction-2', distance: 2, status: 'clear', baseTime: 2 },
      { id: 'road-3', from: 'junction-1', to: 'junction-3', distance: 2, status: 'clear', baseTime: 2 },
      { id: 'road-4', from: 'junction-2', to: 'shelter-1', distance: 2, status: 'clear', baseTime: 2 },
      { id: 'road-5', from: 'junction-3', to: 'shelter-2', distance: 2, status: 'clear', baseTime: 2 },
      { id: 'road-6', from: 'junction-1', to: 'shelter-3', distance: 2, status: 'congested', baseTime: 3 },
    ],
    vehicles: [
      {
        id: 'vehicle-1',
        name: '运输车1号',
        maxCapacity: 25,
        currentLoad: createEmptyInventory(),
        currentWeight: 0,
        status: 'idle',
        currentNode: 'warehouse-1',
        targetNodes: [],
        progress: 0,
        speed: 1,
      },
      {
        id: 'vehicle-2',
        name: '运输车2号',
        maxCapacity: 20,
        currentLoad: createEmptyInventory(),
        currentWeight: 0,
        status: 'idle',
        currentNode: 'warehouse-1',
        targetNodes: [],
        progress: 0,
        speed: 1.2,
      },
    ],
  },
  {
    id: 'level-3',
    name: '高级演练',
    difficulty: 'hard',
    description: '多车辆协同，高频率随机事件，复杂路况',
    initialSupplies: { water: 50, medicine: 25, tent: 12 },
    maxTurns: 30,
    timeLimit: 1200,
    eventProbability: 0.4,
    nodes: [
      { id: 'warehouse-1', type: 'warehouse', name: '主仓库', x: 400, y: 400 },
      { id: 'shelter-1', type: 'shelter', name: '红星安置点', x: 100, y: 80, demand: { water: 12, medicine: 6, tent: 3 }, received: createEmptyInventory() },
      { id: 'shelter-2', type: 'shelter', name: '曙光安置点', x: 700, y: 80, demand: { water: 10, medicine: 5, tent: 3 }, received: createEmptyInventory() },
      { id: 'shelter-3', type: 'shelter', name: '希望安置点', x: 150, y: 250, demand: { water: 8, medicine: 4, tent: 2 }, received: createEmptyInventory() },
      { id: 'shelter-4', type: 'shelter', name: '朝阳安置点', x: 650, y: 250, demand: { water: 8, medicine: 4, tent: 2 }, received: createEmptyInventory() },
      { id: 'shelter-5', type: 'shelter', name: '中心安置点', x: 400, y: 150, demand: { water: 10, medicine: 5, tent: 2 }, received: createEmptyInventory() },
      { id: 'junction-1', type: 'junction', name: '中心路口', x: 400, y: 280 },
      { id: 'junction-2', type: 'junction', name: '东北路口', x: 550, y: 200 },
      { id: 'junction-3', type: 'junction', name: '西北路口', x: 250, y: 200 },
    ],
    roads: [
      { id: 'road-1', from: 'warehouse-1', to: 'junction-1', distance: 2, status: 'clear', baseTime: 2 },
      { id: 'road-2', from: 'junction-1', to: 'junction-3', distance: 2, status: 'clear', baseTime: 2 },
      { id: 'road-3', from: 'junction-1', to: 'junction-2', distance: 2, status: 'clear', baseTime: 2 },
      { id: 'road-4', from: 'junction-3', to: 'shelter-3', distance: 1, status: 'clear', baseTime: 1 },
      { id: 'road-5', from: 'junction-2', to: 'shelter-4', distance: 1, status: 'congested', baseTime: 2 },
      { id: 'road-6', from: 'junction-3', to: 'shelter-1', distance: 2, status: 'clear', baseTime: 2 },
      { id: 'road-7', from: 'junction-2', to: 'shelter-2', distance: 2, status: 'clear', baseTime: 2 },
      { id: 'road-8', from: 'junction-1', to: 'shelter-5', distance: 2, status: 'clear', baseTime: 2 },
    ],
    vehicles: [
      {
        id: 'vehicle-1',
        name: '重型卡车',
        maxCapacity: 35,
        currentLoad: createEmptyInventory(),
        currentWeight: 0,
        status: 'idle',
        currentNode: 'warehouse-1',
        targetNodes: [],
        progress: 0,
        speed: 0.8,
      },
      {
        id: 'vehicle-2',
        name: '轻型货车',
        maxCapacity: 18,
        currentLoad: createEmptyInventory(),
        currentWeight: 0,
        status: 'idle',
        currentNode: 'warehouse-1',
        targetNodes: [],
        progress: 0,
        speed: 1.3,
      },
      {
        id: 'vehicle-3',
        name: '快速配送车',
        maxCapacity: 12,
        currentLoad: createEmptyInventory(),
        currentWeight: 0,
        status: 'idle',
        currentNode: 'warehouse-1',
        targetNodes: [],
        progress: 0,
        speed: 1.6,
      },
    ],
  },
];

export const getLevelById = (id: string): LevelConfig | undefined => {
  return LEVELS.find((level) => level.id === id);
};
