const ERROR_CODES = {
  SUCCESS: 0,
  BAD_REQUEST: 400,
  INVALID_STATE_TRANSITION: 1001,
  IDEMPOTENCY_KEY_MISSING: 1002,
  INSUFFICIENT_INVENTORY: 1003,
  EXCHANGE_NOT_FOUND: 1004,
  INVALID_STATUS: 1005,
  PAYMENT_AMOUNT_MISMATCH: 1006,
  INVALID_REQUEST_DATA: 1007,
  INTERNAL_SERVER_ERROR: 500
};

const ERROR_MESSAGES = {
  [ERROR_CODES.BAD_REQUEST]: '请求参数错误',
  [ERROR_CODES.INVALID_STATE_TRANSITION]: '无效的状态转换',
  [ERROR_CODES.IDEMPOTENCY_KEY_MISSING]: '缺少幂等键 X-Idempotency-Key',
  [ERROR_CODES.INSUFFICIENT_INVENTORY]: '库存不足',
  [ERROR_CODES.EXCHANGE_NOT_FOUND]: '换货单不存在',
  [ERROR_CODES.INVALID_STATUS]: '无效的状态',
  [ERROR_CODES.PAYMENT_AMOUNT_MISMATCH]: '支付金额不匹配',
  [ERROR_CODES.INVALID_REQUEST_DATA]: '请求数据无效',
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: '服务器内部错误'
};

module.exports = {
  ERROR_CODES,
  ERROR_MESSAGES
};
