const ConferenceStatus = {
  PLANNED: 'planned',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled'
};

const ScheduleStatus = {
  DRAFT: 'draft',
  CONFIRMED: 'confirmed',
  IN_USE: 'in_use',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled'
};

const ErrorCodes = {
  CONFERENCE_NOT_FOUND: 'CONFERENCE_NOT_FOUND',
  INTERPRETER_NOT_FOUND: 'INTERPRETER_NOT_FOUND',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  CHANNEL_NOT_FOUND: 'CHANNEL_NOT_FOUND',
  SCHEDULE_NOT_FOUND: 'SCHEDULE_NOT_FOUND',
  STATE_CONFLICT: 'STATE_CONFLICT',
  DUPLICATE_SUBMISSION: 'DUPLICATE_SUBMISSION',
  SOURCE_RECORD_MISSING: 'SOURCE_RECORD_MISSING',
  INTERPRETER_CONFLICT: 'INTERPRETER_CONFLICT',
  DEVICE_CONFLICT: 'DEVICE_CONFLICT',
  CHANNEL_CONFLICT: 'CHANNEL_CONFLICT',
  TIME_SLOT_CONFLICT: 'TIME_SLOT_CONFLICT',
  LANGUAGE_MISMATCH: 'LANGUAGE_MISMATCH',
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  VALIDATION_ERROR: 'VALIDATION_ERROR'
};

module.exports = {
  ConferenceStatus,
  ScheduleStatus,
  ErrorCodes
};
