export interface SensorData {
  id: string;
  sensor_code: string;
  batch_id: string;
  material_type: string;
  rpm_min: number;
  rpm_max: number;
  coefficient: number;
  coefficient_manual: number;
  coefficient_reason: string | null;
  remark: string;
  created_at: string;
  updated_at: string;
  photos?: PhotoMeta[];
}

export interface PhotoMeta {
  id: string;
  sensor_id: string;
  filename: string;
  url: string;
  remark: string;
  uploaded_at: string;
}

export interface SafetyZone {
  id: string;
  sensor_id: string;
  rpm_min: number;
  rpm_max: number;
  coefficient: number;
  coefficient_source: 'auto' | 'manual';
  coefficient_reason: string | null;
  review_status: 'pending' | 'approved' | 'rollback';
  reviewer: string | null;
  review_comment: string | null;
  reviewed_at: string | null;
  version: number;
  created_at: string;
  updated_at: string;
  sensor_code?: string;
  material_type?: string;
  remark?: string;
  batch_id?: string;
  sensor?: SensorData;
}

export interface ChangeRecord {
  id: string;
  target_type: 'sensor' | 'safety-zone';
  target_id: string;
  field: string;
  old_value: string;
  new_value: string;
  operator: string;
  reason: string | null;
  created_at: string;
}

export interface Batch {
  id: string;
  filename: string;
  total_in_file: number;
  imported_count: number;
  duplicate_count: number;
  created_at: string;
}

export interface ImportResult {
  totalInFile: number;
  imported: number;
  duplicates: number;
  batchId: string;
}

export interface DashboardStats {
  totalZones: number;
  pendingReview: number;
  anomalyCount: number;
  lastImportTime: string | null;
}

export interface HistoryDiff {
  before: Record<string, unknown>;
  after: Record<string, unknown>;
}

export interface PagedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
}

export interface SafetyZoneStats {
  totalZones: number;
  pendingReview: number;
  approved: number;
  rollback: number;
  autoGenerated: number;
  manualModified: number;
}
