import * as fs from 'fs';
import * as path from 'path';
import { createObjectCsvWriter } from 'csv-writer';
import { format } from 'date-fns';
import {
  ReportData,
  MigrationPlan,
  Issue,
  Severity,
  IssueType
} from '../types';

export class ReportExporter {
  private outputDir: string;

  constructor(outputDir: string) {
    this.outputDir = outputDir;
    this.ensureOutputDir();
  }

  private ensureOutputDir(): void {
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }
  }

  async exportAll(data: ReportData): Promise<{
    planPath: string;
    issuesPath: string;
    reportPath: string;
    cachePath: string;
  }> {
    const planPath = await this.exportMigrationPlan(data.migrationPlan);
    const issuesPath = await this.exportIssuesCsv(data.issues);
    const reportPath = await this.exportReportMd(data);
    const cachePath = await this.exportDashboardCache(data);

    return { planPath, issuesPath, reportPath, cachePath };
  }

  async exportDashboardCache(data: ReportData): Promise<string> {
    const filePath = path.join(this.outputDir, 'dashboard_cache.json');
    const cache = {
      plan: data.migrationPlan,
      issues: data.issues,
      statistics: data.statistics,
      schemaDiff: data.schemaDiff,
      generatedAt: new Date().toISOString()
    };
    const content = JSON.stringify(cache, null, 2);
    await fs.promises.writeFile(filePath, content, 'utf-8');
    return filePath;
  }

  async exportMigrationPlan(plan: MigrationPlan): Promise<string> {
    const filePath = path.join(this.outputDir, 'migration_plan.json');
    const content = JSON.stringify(plan, null, 2);
    await fs.promises.writeFile(filePath, content, 'utf-8');
    return filePath;
  }

  async exportIssuesCsv(issues: Issue[]): Promise<string> {
    const filePath = path.join(this.outputDir, 'issues.csv');
    
    const csvWriter = createObjectCsvWriter({
      path: filePath,
      header: [
        { id: 'issueId', title: 'Issue ID' },
        { id: 'type', title: 'Type' },
        { id: 'severity', title: 'Severity' },
        { id: 'fieldId', title: 'Field ID' },
        { id: 'draftCount', title: 'Affected Drafts' },
        { id: 'description', title: 'Description' },
        { id: 'suggestion', title: 'Suggestion' },
        { id: 'affectedValues', title: 'Affected Values' }
      ]
    });

    const records = issues.map(issue => ({
      issueId: issue.issueId,
      type: issue.type,
      severity: issue.severity,
      fieldId: issue.fieldId,
      draftCount: issue.draftIds.length,
      description: issue.description,
      suggestion: issue.suggestion || '',
      affectedValues: JSON.stringify(issue.affectedValues.slice(0, 10))
    }));

    await csvWriter.writeRecords(records);
    return filePath;
  }

  async exportReportMd(data: ReportData): Promise<string> {
    const filePath = path.join(this.outputDir, 'report.md');
    const content = this.generateMarkdownReport(data);
    await fs.promises.writeFile(filePath, content, 'utf-8');
    return filePath;
  }

  private generateMarkdownReport(data: ReportData): string {
    const generatedAt = format(new Date(data.migrationPlan.generatedAt), 'yyyy-MM-dd HH:mm:ss');
    
    const lines: string[] = [
      '# Schema Migration Pre-Check Report',
      '',
      `> Generated at: ${generatedAt}`,
      '',
      `**Source Schema Version:** ${data.migrationPlan.sourceSchemaVersion}`,
      `**Target Schema Version:** ${data.migrationPlan.targetSchemaVersion}`,
      '',
      '---',
      '',
      '## 1. Summary',
      '',
      this.generateSummaryTable(data),
      '',
      '## 2. Schema Changes',
      '',
      this.generateSchemaDiffSection(data),
      '',
      '## 3. Issues Found',
      '',
      this.generateIssuesSection(data.issues),
      '',
      '## 4. Migration Plan',
      '',
      this.generateMigrationPlanSection(data.migrationPlan),
      '',
      '## 5. Recommendations',
      '',
      this.generateRecommendationsSection(data),
      '',
      '---',
      '',
      `*Report generated by schema-migration-checker*`
    ];

    return lines.join('\n');
  }

  private generateSummaryTable(data: ReportData): string {
    const stats = data.statistics;
    const critical = stats.issuesBySeverity['critical'] || 0;
    const high = stats.issuesBySeverity['high'] || 0;
    const medium = stats.issuesBySeverity['medium'] || 0;
    const low = stats.issuesBySeverity['low'] || 0;

    const lines: string[] = [
      '| Metric | Value |',
      '|--------|-------|',
      `| Total Drafts | ${stats.totalDrafts} |`,
      `| Affected Drafts | ${stats.affectedDrafts} |`,
      `| Fields Added | ${stats.fieldsAdded} |`,
      `| Fields Removed | ${stats.fieldsRemoved} |`,
      `| Fields Modified | ${stats.fieldsModified} |`,
      `| Attachments | ${stats.attachmentCount} |`,
      `| **Critical Issues** | **${critical}** |`,
      `| **High Issues** | **${high}** |`,
      `| **Medium Issues** | **${medium}** |`,
      `| **Low Issues** | **${low}** |`
    ];

    return lines.join('\n');
  }

  private generateSchemaDiffSection(data: ReportData): string {
    const diff = data.schemaDiff;
    const lines: string[] = [];

    if (diff.addedGroups.length > 0) {
      lines.push('### 2.1 Added Groups');
      lines.push('');
      for (const group of diff.addedGroups) {
        lines.push(`- **${group.groupName}** (\`${group.groupId}\`)`);
      }
      lines.push('');
    }

    if (diff.removedGroups.length > 0) {
      lines.push('### 2.2 Removed Groups');
      lines.push('');
      for (const group of diff.removedGroups) {
        lines.push(`- **${group.groupName}** (\`${group.groupId}\`)`);
      }
      lines.push('');
    }

    if (diff.addedFields.length > 0) {
      lines.push('### 2.3 Added Fields');
      lines.push('');
      lines.push('| Field ID | Group ID | Type | Required | Default |');
      lines.push('|----------|----------|------|----------|---------|');
      for (const field of diff.addedFields) {
        const fieldData = field.newValue as Record<string, unknown>;
        const requiredText = fieldData['required'] ? 'Yes' : 'No';
        const defaultText = fieldData['defaultValue'] !== undefined ? `\`${JSON.stringify(fieldData['defaultValue'])}\`` : '-';
        lines.push(`| \`${field.fieldId}\` | ${field.groupId} | ${fieldData['type']} | ${requiredText} | ${defaultText} |`);
      }
      lines.push('');
    }

    if (diff.removedFields.length > 0) {
      lines.push('### 2.4 Removed Fields');
      lines.push('');
      lines.push('| Field ID | Group ID | Type |');
      lines.push('|----------|----------|------|');
      for (const field of diff.removedFields) {
        const fieldData = field.oldValue as Record<string, unknown>;
        lines.push(`| \`${field.fieldId}\` | ${field.groupId} | ${fieldData['type']} |`);
      }
      lines.push('');
    }

    if (diff.modifiedFields.length > 0) {
      lines.push('### 2.5 Modified Fields');
      lines.push('');
      for (const field of diff.modifiedFields) {
        lines.push(`#### \`${field.fieldId}\``);
        lines.push('');
        if (field.changes && field.changes.length > 0) {
          lines.push('| Property | Old Value | New Value |');
          lines.push('|----------|-----------|-----------|');
          for (const change of field.changes) {
            lines.push(`| ${change.property} | \`${JSON.stringify(change.oldValue)}\` | \`${JSON.stringify(change.newValue)}\` |`);
          }
        }
        lines.push('');
      }
    }

    if (lines.length === 0) {
      lines.push('*No schema changes detected.*');
    }

    return lines.join('\n');
  }

  private generateIssuesSection(issues: Issue[]): string {
    if (issues.length === 0) {
      return '*No issues found. Migration should proceed safely.*';
    }

    const lines: string[] = [];
    const severityOrder: Severity[] = ['critical', 'high', 'medium', 'low'];

    for (const severity of severityOrder) {
      const severityIssues = issues.filter(i => i.severity === severity);
      if (severityIssues.length === 0) continue;

      const icon = severity === 'critical' ? '[CRITICAL]' : 
                   severity === 'high' ? '[HIGH]' : 
                   severity === 'medium' ? '[MEDIUM]' : '[LOW]';

      lines.push(`### 3.1 ${icon} ${severity.charAt(0).toUpperCase() + severity.slice(1)} Issues`);
      lines.push('');

      for (const issue of severityIssues) {
        lines.push(`#### ${issue.issueId}: ${this.getIssueTypeLabel(issue.type)}`);
        lines.push('');
        lines.push(`- **Field:** \`${issue.fieldId}\``);
        lines.push(`- **Affected Drafts:** ${issue.draftIds.length}`);
        lines.push(`- **Description:** ${issue.description}`);
        
        if (issue.suggestion) {
          lines.push(`- **Suggestion:** ${issue.suggestion}`);
        }

        if (issue.affectedValues.length > 0) {
          const sampleValues = issue.affectedValues.slice(0, 5);
          lines.push(`- **Sample Values:** ${sampleValues.map(v => `\`${JSON.stringify(v)}\``).join(', ')}`);
          if (issue.affectedValues.length > 5) {
            lines.push(`  (and ${issue.affectedValues.length - 5} more...)`);
          }
        }

        lines.push('');
      }
    }

    return lines.join('\n');
  }

  private getIssueTypeLabel(type: IssueType): string {
    const labels: Record<IssueType, string> = {
      'missing_field': 'Missing Field',
      'enum_value_mismatch': 'Enum Value Mismatch',
      'required_field_no_default': 'Required Field Without Default',
      'attachment_reference_lost': 'Attachment Reference Lost',
      'field_type_mismatch': 'Field Type Mismatch',
      'schema_version_lag': 'Schema Version Lag',
      'validation_failed': 'Validation Failed'
    };
    return labels[type] || type;
  }

  private generateMigrationPlanSection(plan: MigrationPlan): string {
    if (plan.steps.length === 0) {
      return '*No migration steps required.*';
    }

    const lines: string[] = [
      `| Step ID | Type | Description | Rules Applied |`,
      `|---------|------|-------------|---------------|`
    ];

    for (const step of plan.steps) {
      lines.push(`| ${step.stepId} | ${step.type} | ${step.description} | ${step.rulesApplied.join(', ')} |`);
    }

    return lines.join('\n');
  }

  private generateRecommendationsSection(data: ReportData): string {
    const issues = data.issues;
    const critical = issues.filter(i => i.severity === 'critical').length;
    const high = issues.filter(i => i.severity === 'high').length;

    const lines: string[] = [];

    if (critical > 0) {
      lines.push('### 5.1 Critical Actions Required');
      lines.push('');
      lines.push('**DO NOT PROCEED WITH MIGRATION** until the following critical issues are resolved:');
      lines.push('');
      
      const enumIssues = issues.filter(i => i.type === 'enum_value_mismatch');
      if (enumIssues.length > 0) {
        lines.push('- **Add enum mappings** for unmapped values');
      }

      const requiredIssues = issues.filter(i => i.type === 'required_field_no_default' && i.severity === 'critical');
      if (requiredIssues.length > 0) {
        lines.push('- **Add default values** for new required fields');
      }

      const attachmentIssues = issues.filter(i => i.type === 'attachment_reference_lost');
      if (attachmentIssues.length > 0) {
        lines.push('- **Map or remove** attachment references for removed fields');
      }

      lines.push('');
    }

    if (high > 0) {
      lines.push('### 5.2 Recommended Actions');
      lines.push('');
      lines.push('These issues are not blocking but should be addressed:');
      lines.push('');

      const missingFields = issues.filter(i => i.type === 'missing_field');
      if (missingFields.length > 0) {
        lines.push('- Create migration rules for removed fields that have data in drafts');
      }

      const typeMismatches = issues.filter(i => i.type === 'field_type_mismatch');
      if (typeMismatches.length > 0) {
        lines.push('- Add transform logic for fields with type changes');
      }

      lines.push('');
    }

    const draftsWithOldVersion = issues.filter(i => i.type === 'schema_version_lag');
    if (draftsWithOldVersion.length > 0) {
      lines.push('### 5.3 Version Considerations');
      lines.push('');
      lines.push('Some drafts are using older schema versions. Consider:');
      lines.push('');
      lines.push('- Verifying these drafts have all required fields');
      lines.push('- Running additional validation before migration');
      lines.push('');
    }

    if (lines.length === 0) {
      lines.push('**All checks passed!** Migration can proceed safely.');
      lines.push('');
      lines.push('Recommended steps:');
      lines.push('1. Review the generated migration plan');
      lines.push('2. Test migration with a small subset of drafts');
      lines.push('3. Backup all data before full migration');
      lines.push('4. Monitor migration progress');
    }

    return lines.join('\n');
  }
}
