import type { StageScene } from "@/types"

export const sampleScene: StageScene = {
  id: "scene-001",
  name: "话剧《暗夜之光》第一幕",
  version: 1,
  createdAt: "2026-05-20T10:00:00Z",
  updatedAt: "2026-05-28T14:30:00Z",
  source: "source://lighting-plan-v2/act1",
  stage: {
    width: 16,
    depth: 12,
    height: 0.3,
    gridUnit: 1,
  },
  lightBars: [
    {
      id: "lb-1",
      name: "1号灯杆",
      position: { x: -4, y: 8, z: -2 },
      length: 10,
      sourceRef: "source://rigging-plan/bar-1",
    },
    {
      id: "lb-2",
      name: "2号灯杆",
      position: { x: 0, y: 7.5, z: -5 },
      length: 10,
      sourceRef: "source://rigging-plan/bar-2",
    },
    {
      id: "lb-3",
      name: "3号灯杆",
      position: { x: 4, y: 8, z: -2 },
      length: 10,
      sourceRef: "source://rigging-plan/bar-3",
    },
    {
      id: "lb-4",
      name: "4号灯杆",
      position: { x: 0, y: 8.5, z: -8 },
      length: 12,
      sourceRef: "source://rigging-plan/bar-4",
    },
  ],
  hangingPoints: [
    {
      id: "hp-1",
      name: "1号吊点",
      position: { x: -3, y: 8, z: -1 },
      loadCapacity: 80,
      currentLoad: 35,
      sourceRef: "source://rigging-plan/hp-1",
    },
    {
      id: "hp-2",
      name: "2号吊点",
      position: { x: 3, y: 7.5, z: -1 },
      loadCapacity: 60,
      currentLoad: 25,
      sourceRef: "source://rigging-plan/hp-2",
    },
    {
      id: "hp-3",
      name: "3号吊点",
      position: { x: 0, y: 8, z: -5 },
      loadCapacity: 60,
      currentLoad: 85,
      sourceRef: "source://rigging-plan/hp-3",
    },
    {
      id: "hp-4",
      name: "4号吊点",
      position: { x: -5, y: 8.5, z: -8 },
      loadCapacity: 100,
      currentLoad: 40,
      sourceRef: "source://rigging-plan/hp-4",
    },
  ],
  fixtures: [
    {
      id: "fix-1",
      name: "1号聚光灯",
      type: "spotlight",
      position: { x: -4, y: 8, z: -2 },
      targetPosition: { x: -2, y: 0, z: 2 },
      beamAngle: 30,
      weight: 25,
      attachedTo: "lb-1",
      sourceRef: "source://fixture-schedule/fix-1",
    },
    {
      id: "fix-2",
      name: "2号聚光灯",
      type: "spotlight",
      position: { x: -2, y: 8, z: -2 },
      targetPosition: { x: 0, y: 0, z: 3 },
      beamAngle: 25,
      weight: 25,
      attachedTo: "lb-1",
      sourceRef: "source://fixture-schedule/fix-2",
    },
    {
      id: "fix-3",
      name: "3号追光灯",
      type: "moving_head",
      position: { x: 0, y: 7.5, z: -5 },
      targetPosition: { x: 0, y: 1.5, z: 0 },
      beamAngle: 20,
      weight: 30,
      attachedTo: "lb-2",
      sourceRef: "source://fixture-schedule/fix-3",
    },
    {
      id: "fix-4",
      name: "4号追光灯",
      type: "moving_head",
      position: { x: 2, y: 7.5, z: -5 },
      targetPosition: { x: 2, y: 1.5, z: 0 },
      beamAngle: 20,
      weight: 30,
      attachedTo: "lb-2",
      sourceRef: "source://fixture-schedule/fix-4",
    },
    {
      id: "fix-5",
      name: "5号柔光灯",
      type: "fresnel",
      position: { x: 4, y: 8, z: -2 },
      targetPosition: { x: 4, y: 0, z: 2 },
      beamAngle: 45,
      weight: 15,
      attachedTo: "lb-3",
      sourceRef: "source://fixture-schedule/fix-5",
    },
    {
      id: "fix-6",
      name: "6号LED帕灯",
      type: "led_par",
      position: { x: -5, y: 8, z: -2 },
      targetPosition: { x: -5, y: 0, z: 0 },
      beamAngle: 60,
      weight: 8,
      attachedTo: "lb-1",
      sourceRef: "source://fixture-schedule/fix-6",
    },
    {
      id: "fix-7",
      name: "7号聚光灯",
      type: "spotlight",
      position: { x: -1, y: 8.5, z: -8 },
      targetPosition: { x: -2, y: 0, z: 0 },
      beamAngle: 30,
      weight: 25,
      attachedTo: "lb-4",
      sourceRef: "source://fixture-schedule/fix-7",
    },
    {
      id: "fix-8",
      name: "8号聚光灯（穿帮灯）",
      type: "spotlight",
      position: { x: 1, y: 8.5, z: -8 },
      targetPosition: { x: 2, y: 0, z: 2 },
      beamAngle: 35,
      weight: 25,
      attachedTo: "lb-4",
      sourceRef: "source://fixture-schedule/fix-8",
    },
    {
      id: "fix-9",
      name: "9号柔光灯",
      type: "fresnel",
      position: { x: 0, y: 8, z: -5 },
      targetPosition: { x: 0, y: 0, z: -3 },
      beamAngle: 40,
      weight: 15,
      attachedTo: "lb-2",
      sourceRef: "source://fixture-schedule/fix-9",
    },
    {
      id: "fix-10",
      name: "10号追光灯",
      type: "moving_head",
      position: { x: -1, y: 8, z: -5 },
      targetPosition: { x: -3, y: 1.5, z: 1 },
      beamAngle: 22,
      weight: 30,
      attachedTo: "lb-2",
      sourceRef: "source://fixture-schedule/fix-10",
    },
    {
      id: "fix-11",
      name: "11号LED帕灯",
      type: "led_par",
      position: { x: 1, y: 8, z: -5 },
      targetPosition: { x: 3, y: 0, z: 1 },
      beamAngle: 55,
      weight: 8,
      attachedTo: "lb-2",
      sourceRef: "source://fixture-schedule/fix-11",
    },
  ],
  actorRoutes: [
    {
      id: "ar-1",
      name: "第一场 主角入场",
      scene: "第一场",
      waypoints: [
        { x: -6, y: 0, z: 4 },
        { x: -3, y: 0, z: 2 },
        { x: 0, y: 0, z: 0 },
      ],
      actorHeight: 1.8,
      sourceRef: "source://blocking-notes/act1-scene1",
    },
    {
      id: "ar-2",
      name: "第二场 群演穿越",
      scene: "第二场",
      waypoints: [
        { x: -5, y: 0, z: 5 },
        { x: -2, y: 0, z: 3 },
        { x: 2, y: 0, z: 0 },
        { x: 5, y: 0, z: -2 },
      ],
      actorHeight: 1.8,
      sourceRef: "source://blocking-notes/act1-scene2",
    },
    {
      id: "ar-3",
      name: "第二场 主角斜穿",
      scene: "第二场",
      waypoints: [
        { x: -5, y: 0, z: 3 },
        { x: -2, y: 0, z: 1 },
        { x: 1, y: 0, z: -1 },
        { x: 4, y: 0, z: -3 },
      ],
      actorHeight: 1.8,
      sourceRef: "source://blocking-notes/act1-scene2-hero",
    },
  ],
  collisions: [],
  auditLogs: [],
}
