server:
  port: 8080

spring:
  application:
    name: fee-calculation-api
  datasource:
    url: jdbc:h2:mem:fee_calc_db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.feiyong.feecalc: DEBUG
    org.hibernate.SQL: DEBUG
