import type { SamplePack } from '@/types';

export const samplePacks: SamplePack[] = [
  {
    id: 'basic-yaw',
    name: '基础偏航旋转',
    description: '卫星绕Z轴旋转90°的简单姿态，展示基本四元数-欧拉角对应关系',
    quaternion: { w: 0.7071, x: 0, y: 0, z: 0.7071, source: 'raw' },
    eulerAngles: { roll: 0, pitch: 0, yaw: Math.PI / 2, sequence: 'ZYX', source: 'computed' },
    interpolationSteps: 30,
    attitudeModel: 'simple-sat',
    targetAttitude: { w: 1, x: 0, y: 0, z: 0, source: 'raw' },
    report: '基础偏航旋转样例：展示Z轴90°旋转的四元数表示和球面映射',
    items: [
      { key: 'quaternion', label: '四元数', value: { w: 0.7071, x: 0, y: 0, z: 0.7071 }, tag: 'raw' },
      { key: 'euler', label: '欧拉角', value: { roll: 0, pitch: 0, yaw: 90 }, tag: 'computed' },
      { key: 'steps', label: '插值步长', value: 30, tag: 'raw' },
      { key: 'model', label: '姿态模型', value: 'simple-sat', tag: 'raw' },
      { key: 'target', label: '目标姿态', value: { w: 1, x: 0, y: 0, z: 0 }, tag: 'raw' },
      { key: 'report', label: '课堂报告', value: '基础偏航旋转样例', tag: 'raw' },
    ],
  },
  {
    id: 'gimbal-lock',
    name: '万向节锁演示',
    description: 'pitch = 90° 时万向节锁现象，欧拉角表示退化',
    quaternion: { w: 0.7071, x: 0, y: 0.7071, z: 0, source: 'raw' },
    eulerAngles: { roll: 0, pitch: Math.PI / 2, yaw: 0, sequence: 'ZYX', source: 'raw' },
    interpolationSteps: 40,
    attitudeModel: 'gimbal-sat',
    targetAttitude: { w: 1, x: 0, y: 0, z: 0, source: 'raw' },
    report: '万向节锁演示：pitch = 90° 时 roll 和 yaw 耦合，欧拉角表示失效',
    items: [
      { key: 'quaternion', label: '四元数', value: { w: 0.7071, x: 0, y: 0.7071, z: 0 }, tag: 'raw' },
      { key: 'euler', label: '欧拉角', value: { roll: 0, pitch: 90, yaw: 0 }, tag: 'raw' },
      { key: 'gimbal_status', label: '万向节锁状态', value: '已触发', tag: 'computed' },
      { key: 'steps', label: '插值步长', value: 40, tag: 'raw' },
      { key: 'model', label: '姿态模型', value: 'gimbal-sat', tag: 'raw' },
      { key: 'target', label: '目标姿态', value: { w: 1, x: 0, y: 0, z: 0 }, tag: 'raw' },
      { key: 'report', label: '课堂报告', value: '万向节锁演示', tag: 'raw' },
    ],
  },
  {
    id: 'unnormalized-quat',
    name: '未归一四元数',
    description: '输入未经归一化的四元数，触发归一化校验警告',
    quaternion: { w: 2, x: 0, y: 0, z: 0, source: 'raw' },
    eulerAngles: { roll: 0, pitch: 0, yaw: 0, sequence: 'ZYX', source: 'computed' },
    interpolationSteps: 20,
    attitudeModel: 'simple-sat',
    targetAttitude: { w: 1, x: 0, y: 0, z: 0, source: 'raw' },
    report: '未归一四元数样例：||q|| = 2.0，触发归一化校验',
    items: [
      { key: 'quaternion', label: '四元数', value: { w: 2, x: 0, y: 0, z: 0 }, tag: 'raw' },
      { key: 'norm', label: '四元数模', value: 2.0, tag: 'computed' },
      { key: 'normalized', label: '归一化结果', value: { w: 1, x: 0, y: 0, z: 0 }, tag: 'computed' },
      { key: 'euler', label: '欧拉角', value: { roll: 0, pitch: 0, yaw: 0 }, tag: 'computed' },
      { key: 'steps', label: '插值步长', value: 20, tag: 'raw' },
      { key: 'report', label: '课堂报告', value: '未归一四元数样例', tag: 'raw' },
    ],
  },
  {
    id: 'long-path',
    name: '插值绕远路径',
    description: '起止四元数点积为负，SLERP 走长弧，触发绕远警告',
    quaternion: { w: 1, x: 0, y: 0, z: 0, source: 'raw' },
    eulerAngles: { roll: 0, pitch: 0, yaw: 0, sequence: 'ZYX', source: 'raw' },
    interpolationSteps: 50,
    attitudeModel: 'simple-sat',
    targetAttitude: { w: -0.7071, x: 0, y: 0.7071, z: 0, source: 'raw' },
    report: '插值绕远样例：目标四元数 w<0，应取反后插值以获得短弧',
    items: [
      { key: 'quaternion', label: '起始四元数', value: { w: 1, x: 0, y: 0, z: 0 }, tag: 'raw' },
      { key: 'target', label: '目标四元数', value: { w: -0.7071, x: 0, y: 0.7071, z: 0 }, tag: 'raw' },
      { key: 'dot_product', label: '点积', value: -0.7071, tag: 'computed' },
      { key: 'suggestion', label: '建议', value: '取反目标四元数', tag: 'computed' },
      { key: 'steps', label: '插值步长', value: 50, tag: 'raw' },
      { key: 'report', label: '课堂报告', value: '插值绕远样例', tag: 'raw' },
    ],
  },
  {
    id: 'full-rotation',
    name: '三轴复合旋转',
    description: '卫星同时绕三轴旋转的复合姿态，展示四元数乘法的不可交换性',
    quaternion: { w: 0.5, x: 0.5, y: 0.5, z: 0.5, source: 'raw' },
    eulerAngles: { roll: Math.PI / 2, pitch: 0, yaw: Math.PI / 2, sequence: 'ZYX', source: 'computed' },
    interpolationSteps: 60,
    attitudeModel: 'complex-sat',
    targetAttitude: { w: 0.7071, x: 0, y: 0, z: 0.7071, source: 'raw' },
    report: '三轴复合旋转样例：展示四元数 (0.5,0.5,0.5,0.5) 的空间含义',
    items: [
      { key: 'quaternion', label: '四元数', value: { w: 0.5, x: 0.5, y: 0.5, z: 0.5 }, tag: 'raw' },
      { key: 'euler', label: '欧拉角(ZYX)', value: { roll: 90, pitch: 0, yaw: 90 }, tag: 'computed' },
      { key: 'steps', label: '插值步长', value: 60, tag: 'raw' },
      { key: 'model', label: '姿态模型', value: 'complex-sat', tag: 'raw' },
      { key: 'target', label: '目标姿态', value: { w: 0.7071, x: 0, y: 0, z: 0.7071 }, tag: 'raw' },
      { key: 'report', label: '课堂报告', value: '三轴复合旋转样例', tag: 'raw' },
    ],
  },
];
