const LicenseRiskAssessor = require('./src/core/LicenseRiskAssessor.js')
const assessor = new LicenseRiskAssessor()

console.log('=== 风险等级测试 ===')
console.log('MIT:', assessor.assessRisk('MIT').level)
console.log('Apache-2.0:', assessor.assessRisk('Apache-2.0').level)
console.log('BSD-3-Clause:', assessor.assessRisk('BSD-3-Clause').level)
console.log('LGPL-3.0:', assessor.assessRisk('LGPL-3.0').level)
console.log('GPL-3.0:', assessor.assessRisk('GPL-3.0').level)
console.log('GPL-2.0:', assessor.assessRisk('GPL-2.0').level)
console.log('AGPL-3.0:', assessor.assessRisk('AGPL-3.0').level)
console.log('MPL-2.0:', assessor.assessRisk('MPL-2.0').level)
console.log('CC0-1.0:', assessor.assessRisk('CC0-1.0').level)
console.log('Unlicense:', assessor.assessRisk('Unlicense').level)
console.log('Unknown:', assessor.assessRisk('Unknown').level)

console.log('')
console.log('=== Copyleft 测试 ===')
console.log('GPL-3.0 isCopyleft:', assessor.isCopyleft('GPL-3.0'))
console.log('LGPL-3.0 isCopyleft:', assessor.isCopyleft('LGPL-3.0'))
console.log('MIT isCopyleft:', assessor.isCopyleft('MIT'))

console.log('')
console.log('=== 网络服务风险测试 ===')
console.log('AGPL-3.0 isNetworkServiceRisk:', assessor.isNetworkServiceRisk('AGPL-3.0'))
console.log('GPL-3.0 isNetworkServiceRisk:', assessor.isNetworkServiceRisk('GPL-3.0'))

console.log('')
console.log('=== NOTICE 要求测试 ===')
console.log('Apache-2.0 requiresNotice:', assessor.requiresNotice('Apache-2.0'))
console.log('MIT requiresNotice:', assessor.requiresNotice('MIT'))

console.log('')
console.log('=== 许可证标准化测试 ===')
console.log('"apache" normalized:', assessor.normalizeLicense('apache'))
console.log('"gpl" normalized:', assessor.normalizeLicense('gpl'))
console.log('"bsd" normalized:', assessor.normalizeLicense('bsd'))
console.log('"lgpl" normalized:', assessor.normalizeLicense('lgpl'))
console.log('"agpl" normalized:', assessor.normalizeLicense('agpl'))
