package exporter

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/zy1225/chanalyzer/internal/models"
)

type Exporter struct {
	result   *models.AnalysisResult
	timeline *models.Timeline
}

func NewExporter(result *models.AnalysisResult, timeline *models.Timeline) *Exporter {
	return &Exporter{
		result:   result,
		timeline: timeline,
	}
}

func (e *Exporter) ExportMarkdown(outputPath string) error {
	var sb strings.Builder

	sb.WriteString("# Go Channel Analysis Report\n\n")
	sb.WriteString(fmt.Sprintf("Generated: %s\n\n", time.Now().Format("2006-01-02 15:04:05")))

	sb.WriteString("## Summary\n\n")
	sb.WriteString(fmt.Sprintf("- **Case**: %s\n", e.result.CaseName))
	sb.WriteString(fmt.Sprintf("- **Risk Level**: %s\n", e.getRiskLevelEmoji()))
	sb.WriteString(fmt.Sprintf("- **Deadlock Detected**: %t\n", e.result.Deadlock))
	if e.result.Deadlock {
		sb.WriteString(fmt.Sprintf("- **Deadlock Type**: %s\n", e.result.DeadlockType))
	}
	sb.WriteString("\n")

	sb.WriteString("## Statistics\n\n")
	sb.WriteString("| Metric | Value |\n")
	sb.WriteString("|--------|-------|\n")
	sb.WriteString(fmt.Sprintf("| Total Events | %d |\n", e.result.Stats.TotalEvents))
	sb.WriteString(fmt.Sprintf("| Total Channels | %d |\n", e.result.Stats.TotalChannels))
	sb.WriteString(fmt.Sprintf("| Total Goroutines | %d |\n", e.result.Stats.TotalGoroutines))
	sb.WriteString(fmt.Sprintf("| Blocked Goroutines | %d |\n", e.result.Stats.BlockedCount))
	sb.WriteString(fmt.Sprintf("| Closed Channels | %d |\n", e.result.Stats.ClosedChannels))
	sb.WriteString(fmt.Sprintf("| Nil Channels | %d |\n", e.result.Stats.NilChannels))
	sb.WriteString("\n")

	if e.result.Deadlock || e.result.Description != "" {
		sb.WriteString("## Issues Found\n\n")
		if e.result.Deadlock {
			sb.WriteString("### ⚠️ Deadlock Detected\n\n")
			sb.WriteString(fmt.Sprintf("**Type**: %s\n\n", e.result.DeadlockType))
			sb.WriteString(fmt.Sprintf("**Description**: %s\n\n", e.result.Description))
		}
	}

	if len(e.result.BlockedGoroutines) > 0 {
		sb.WriteString("## Blocked Goroutines\n\n")
		for i, g := range e.result.BlockedGoroutines {
			sb.WriteString(fmt.Sprintf("### %d. %s (%s)\n\n", i+1, g.Name, g.ID))
			sb.WriteString(fmt.Sprintf("- **State**: %s\n", g.State))
			sb.WriteString(fmt.Sprintf("- **Waiting On**: %s\n", g.WaitingOn))
			sb.WriteString(fmt.Sprintf("- **Blocked Since**: %s\n", g.Since.Format(time.RFC3339)))
			sb.WriteString("\n")
		}
	}

	if len(e.result.ChannelStates) > 0 {
		sb.WriteString("## Channel States\n\n")
		for id, ch := range e.result.ChannelStates {
			sb.WriteString(fmt.Sprintf("### Channel: %s\n\n", id))
			sb.WriteString(fmt.Sprintf("- **State**: %s\n", ch.State))
			sb.WriteString(fmt.Sprintf("- **Buffer**: %d/%d\n", ch.BufferLength, ch.BufferSize))
			if ch.BufferLength > 0 {
				sb.WriteString(fmt.Sprintf("- **Buffer Content**: %v\n", ch.Buffer))
			}
			sb.WriteString(fmt.Sprintf("- **Send Queue**: %d goroutines\n", ch.SendqLength))
			sb.WriteString(fmt.Sprintf("- **Receive Queue**: %d goroutines\n", ch.RecvqLength))
			sb.WriteString("\n")
		}
	}

	if e.timeline != nil && len(e.timeline.Events) > 0 {
		sb.WriteString("## Event Timeline\n\n")
		sb.WriteString("| # | Time | Type | Channel | Goroutine | Value | Block Reason |\n")
		sb.WriteString("|---|------|------|---------|-----------|-------|--------------|\n")
		for i, event := range e.timeline.Events {
			value := "-"
			if event.Value != nil {
				value = fmt.Sprintf("%v", event.Value)
			}
			blockReason := "-"
			if event.Metadata.BlockReason != "" {
				blockReason = event.Metadata.BlockReason
			}
			sb.WriteString(fmt.Sprintf("| %d | %s | %s | %s | %s | %s | %s |\n",
				i+1,
				event.Timestamp.Format("15:04:05"),
				event.Type,
				e.coalesce(event.ChannelID),
				e.coalesce(event.Goroutine),
				value,
				blockReason,
			))
		}
		sb.WriteString("\n")
	}

	if len(e.result.Suggestions) > 0 {
		sb.WriteString("## Suggestions & Fixes\n\n")
		for i, s := range e.result.Suggestions {
			sb.WriteString(fmt.Sprintf("### %d. [%s] %s\n\n", i+1, s.Priority, s.Category))
			sb.WriteString(fmt.Sprintf("%s\n\n", s.Description))
			if s.CodeExample != "" {
				sb.WriteString("```go\n")
				sb.WriteString(s.CodeExample)
				sb.WriteString("\n```\n\n")
			}
			if s.Reference != "" {
				sb.WriteString(fmt.Sprintf("**Reference**: %s\n\n", s.Reference))
			}
		}
	}

	sb.WriteString("---\n\n")
	sb.WriteString("*Generated by chanalyzer - Go Channel Deadlock & Throughput Analyzer*\n")

	dir := filepath.Dir(outputPath)
	if dir != "." && dir != "" {
		os.MkdirAll(dir, 0755)
	}

	if err := os.WriteFile(outputPath, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write markdown file: %w", err)
	}

	fmt.Printf("Markdown report exported to: %s\n", outputPath)
	return nil
}

func (e *Exporter) ExportJSON(outputPath string) error {
	report := map[string]interface{}{
		"generated_at": time.Now().Format(time.RFC3339),
		"result":       e.result,
	}

	if e.timeline != nil {
		report["timeline"] = map[string]interface{}{
			"start_at":   e.timeline.StartAt,
			"end_at":     e.timeline.EndAt,
			"events":     e.timeline.Events,
			"snapshots":  e.timeline.Snapshots,
			"duration":   e.timeline.Duration().String(),
		}
	}

	data, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal JSON: %w", err)
	}

	dir := filepath.Dir(outputPath)
	if dir != "." && dir != "" {
		os.MkdirAll(dir, 0755)
	}

	if err := os.WriteFile(outputPath, data, 0644); err != nil {
		return fmt.Errorf("failed to write JSON file: %w", err)
	}

	fmt.Printf("JSON report exported to: %s\n", outputPath)
	return nil
}

func (e *Exporter) getRiskLevelEmoji() string {
	switch e.result.RiskLevel {
	case "HIGH":
		return "🔴 HIGH"
	case "MEDIUM":
		return "🟡 MEDIUM"
	case "LOW":
		return "🟢 LOW"
	default:
		return e.result.RiskLevel
	}
}

func (e *Exporter) coalesce(s string) string {
	if s == "" {
		return "-"
	}
	return s
}

type ExportConfig struct {
	OutputPath string
	Format     string
	IncludeTimeline bool
}

func Export(result *models.AnalysisResult, timeline *models.Timeline, config *ExportConfig) error {
	exporter := NewExporter(result, timeline)

	switch config.Format {
	case "markdown", "md":
		return exporter.ExportMarkdown(config.OutputPath)
	case "json":
		return exporter.ExportJSON(config.OutputPath)
	case "all":
		basePath := config.OutputPath
		if ext := filepath.Ext(basePath); ext != "" {
			basePath = basePath[:len(basePath)-len(ext)]
		}
		if err := exporter.ExportMarkdown(basePath + ".md"); err != nil {
			return err
		}
		return exporter.ExportJSON(basePath + ".json")
	default:
		return fmt.Errorf("unsupported format: %s (supported: markdown, json, all)", config.Format)
	}
}
