const STATUS = {
  CREATED: 'CREATED',
  REASON_ANALYZING: 'REASON_ANALYZING',
  REASON_CONFIRMED: 'REASON_CONFIRMED',
  RESPONSIBILITY_ASSIGNED: 'RESPONSIBILITY_ASSIGNED',
  RECOVERY_IN_PROGRESS: 'RECOVERY_IN_PROGRESS',
  RECOVERED: 'RECOVERED',
  REVIEWING: 'REVIEWING',
  COMPLETED: 'COMPLETED'
};

const STATUS_TRANSITIONS = {
  [STATUS.CREATED]: [STATUS.REASON_ANALYZING],
  [STATUS.REASON_ANALYZING]: [STATUS.REASON_CONFIRMED, STATUS.CREATED],
  [STATUS.REASON_CONFIRMED]: [STATUS.RESPONSIBILITY_ASSIGNED, STATUS.REASON_ANALYZING],
  [STATUS.RESPONSIBILITY_ASSIGNED]: [STATUS.RECOVERY_IN_PROGRESS, STATUS.REASON_CONFIRMED],
  [STATUS.RECOVERY_IN_PROGRESS]: [STATUS.RECOVERED, STATUS.RESPONSIBILITY_ASSIGNED],
  [STATUS.RECOVERED]: [STATUS.REVIEWING, STATUS.RECOVERY_IN_PROGRESS],
  [STATUS.REVIEWING]: [STATUS.COMPLETED, STATUS.RECOVERED],
  [STATUS.COMPLETED]: []
};

const STATUS_DESCRIPTIONS = {
  [STATUS.CREATED]: '事件已创建，待分析原因',
  [STATUS.REASON_ANALYZING]: '原因分析中，收集各方面记录',
  [STATUS.REASON_CONFIRMED]: '原因已确认，待分配责任',
  [STATUS.RESPONSIBILITY_ASSIGNED]: '责任已确认，待复产',
  [STATUS.RECOVERY_IN_PROGRESS]: '复产进行中',
  [STATUS.RECOVERED]: '已复产，待复盘',
  [STATUS.REVIEWING]: '复盘中，起草报告',
  [STATUS.COMPLETED]: '已完成，事件归档'
};

const REASON_CATEGORIES = {
  EQUIPMENT: 'EQUIPMENT',
  MATERIAL: 'MATERIAL',
  PERSONNEL: 'PERSONNEL',
  OTHER: 'OTHER'
};

const REASON_CATEGORY_DESCRIPTIONS = {
  [REASON_CATEGORIES.EQUIPMENT]: '设备原因',
  [REASON_CATEGORIES.MATERIAL]: '物料原因',
  [REASON_CATEGORIES.PERSONNEL]: '人员原因',
  [REASON_CATEGORIES.OTHER]: '其他原因'
};

const REASON_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  REJECTED: 'REJECTED'
};

const RESPONSIBILITY_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  APPEALED: 'APPEALED',
  FINALIZED: 'FINALIZED'
};

const RECOVERY_STATUS = {
  STARTED: 'STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  VERIFYING: 'VERIFYING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

const REPORT_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

const SEVERITY = {
  MINOR: 'MINOR',
  MEDIUM: 'MEDIUM',
  MAJOR: 'MAJOR',
  CRITICAL: 'CRITICAL'
};

module.exports = {
  STATUS,
  STATUS_TRANSITIONS,
  STATUS_DESCRIPTIONS,
  REASON_CATEGORIES,
  REASON_CATEGORY_DESCRIPTIONS,
  REASON_STATUS,
  RESPONSIBILITY_STATUS,
  RECOVERY_STATUS,
  REPORT_STATUS,
  SEVERITY
};
