import {
  BeatRecord,
  Student,
  Section,
  ChangeLog,
  MismatchRecord,
  DataSource,
  RecordStatus,
  MismatchType,
  ChangeType,
} from '../types';

export const mockSections: Section[] = [
  { id: 's1', name: '第一小提琴', leaderId: 'l1', leaderName: '张部长' },
  { id: 's2', name: '第二小提琴', leaderId: 'l2', leaderName: '李部长' },
  { id: 's3', name: '中提琴', leaderId: 'l3', leaderName: '王部长' },
  { id: 's4', name: '大提琴', leaderId: 'l4', leaderName: '赵部长' },
  { id: 's5', name: '低音提琴', leaderId: 'l5', leaderName: '刘部长' },
  { id: 's6', name: '长笛', leaderId: 'l6', leaderName: '陈部长' },
  { id: 's7', name: '单簧管', leaderId: 'l7', leaderName: '周部长' },
  { id: 's8', name: '圆号', leaderId: 'l8', leaderName: '吴部长' },
];

export const mockStudents: Student[] = [
  { id: 'st1', name: '王小明', sectionId: 's1', instrument: '小提琴' },
  { id: 'st2', name: '李小红', sectionId: 's1', instrument: '小提琴' },
  { id: 'st3', name: '张小华', sectionId: 's2', instrument: '小提琴' },
  { id: 'st4', name: '刘小芳', sectionId: 's3', instrument: '中提琴' },
  { id: 'st5', name: '陈大伟', sectionId: 's4', instrument: '大提琴' },
  { id: 'st6', name: '杨美丽', sectionId: 's4', instrument: '大提琴' },
  { id: 'st7', name: '黄志强', sectionId: 's6', instrument: '长笛' },
  { id: 'st8', name: '周婷婷', sectionId: 's7', instrument: '单簧管' },
  { id: 'st9', name: '吴磊', sectionId: 's8', instrument: '圆号' },
  { id: 'st10', name: '郑浩', sectionId: 's1', instrument: '小提琴' },
];

const today = new Date();
const yesterday = new Date(today);
yesterday.setDate(yesterday.getDate() - 1);
const twoDaysAgo = new Date(today);
twoDaysAgo.setDate(twoDaysAgo.getDate() - 2);

function formatDate(d: Date): string {
  return d.toISOString().split('T')[0];
}

export const mockRecords: BeatRecord[] = [
  {
    id: 'r1',
    studentId: 'st1',
    studentName: '王小明',
    sectionId: 's1',
    sectionName: '第一小提琴',
    rehearsalDate: formatDate(today),
    measureStart: 1,
    measureEnd: 48,
    tempo: 88,
    source: DataSource.METRONOME,
    status: RecordStatus.CONFIRMED,
    remarks: '正常演奏',
    createdBy: '张部长',
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    isDuplicate: false,
  },
  {
    id: 'r2',
    studentId: 'st1',
    studentName: '王小明',
    sectionId: 's1',
    sectionName: '第一小提琴',
    rehearsalDate: formatDate(today),
    measureStart: 45,
    measureEnd: 80,
    tempo: 92,
    source: DataSource.MANUAL,
    status: RecordStatus.PENDING,
    remarks: '',
    createdBy: '王小明',
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    isDuplicate: true,
    duplicateOfId: 'r1',
  },
  {
    id: 'r3',
    studentId: 'st2',
    studentName: '李小红',
    sectionId: 's1',
    sectionName: '第一小提琴',
    rehearsalDate: formatDate(today),
    measureStart: 50,
    measureEnd: 30,
    tempo: 88,
    source: DataSource.MUSIC_SHEET,
    status: RecordStatus.TO_FILL,
    remarks: '小节号有问题，待核对',
    createdBy: '李小红',
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    isDuplicate: false,
  },
  {
    id: 'r4',
    studentId: 'st5',
    studentName: '陈大伟',
    sectionId: 's4',
    sectionName: '大提琴',
    rehearsalDate: formatDate(today),
    measureStart: 1,
    measureEnd: 30,
    tempo: 76,
    source: DataSource.METRONOME,
    status: RecordStatus.MANUAL_EDITED,
    remarks: '速度由80调整为76，指挥要求',
    createdBy: '赵部长',
    createdAt: yesterday.toISOString(),
    updatedAt: today.toISOString(),
    isDuplicate: false,
  },
  {
    id: 'r5',
    studentId: 'st6',
    studentName: '杨美丽',
    sectionId: 's4',
    sectionName: '大提琴',
    rehearsalDate: formatDate(today),
    measureStart: 45,
    measureEnd: 52,
    tempo: 76,
    source: DataSource.METRONOME,
    status: RecordStatus.TO_FILL,
    remarks: '中间不连续，待补',
    createdBy: '赵部长',
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    isDuplicate: false,
  },
  {
    id: 'r6',
    studentId: 'st7',
    studentName: '黄志强',
    sectionId: 's6',
    sectionName: '长笛',
    rehearsalDate: formatDate(today),
    measureStart: 25,
    measureEnd: 60,
    tempo: 250,
    source: DataSource.MANUAL,
    status: RecordStatus.PENDING,
    remarks: '',
    createdBy: '黄志强',
    createdAt: today.toISOString(),
    updatedAt: today.toISOString(),
    isDuplicate: false,
  },
  {
    id: 'r7',
    studentId: 'st3',
    studentName: '张小华',
    sectionId: 's2',
    sectionName: '第二小提琴',
    rehearsalDate: formatDate(yesterday),
    measureStart: 1,
    measureEnd: 100,
    tempo: 84,
    source: DataSource.MUSIC_SHEET,
    status: RecordStatus.CONFIRMED,
    remarks: '完整演奏',
    createdBy: '李部长',
    createdAt: yesterday.toISOString(),
    updatedAt: yesterday.toISOString(),
    isDuplicate: false,
  },
  {
    id: 'r8',
    studentId: 'st4',
    studentName: '刘小芳',
    sectionId: 's3',
    sectionName: '中提琴',
    rehearsalDate: formatDate(yesterday),
    measureStart: 10,
    measureEnd: 55,
    tempo: 84,
    source: DataSource.METRONOME,
    status: RecordStatus.CONFIRMED,
    remarks: '',
    createdBy: '王部长',
    createdAt: yesterday.toISOString(),
    updatedAt: yesterday.toISOString(),
    isDuplicate: false,
  },
  {
    id: 'r9',
    studentId: 'st8',
    studentName: '周婷婷',
    sectionId: 's7',
    sectionName: '单簧管',
    rehearsalDate: formatDate(twoDaysAgo),
    measureStart: 1,
    measureEnd: 120,
    tempo: 96,
    source: DataSource.METRONOME,
    status: RecordStatus.CONFIRMED,
    remarks: 'solo段落',
    createdBy: '周部长',
    createdAt: twoDaysAgo.toISOString(),
    updatedAt: twoDaysAgo.toISOString(),
    isDuplicate: false,
  },
  {
    id: 'r10',
    studentId: 'st9',
    studentName: '吴磊',
    sectionId: 's8',
    sectionName: '圆号',
    rehearsalDate: formatDate(twoDaysAgo),
    measureStart: 60,
    measureEnd: 90,
    tempo: 96,
    source: DataSource.MUSIC_SHEET,
    status: RecordStatus.MANUAL_EDITED,
    remarks: '起始小节由55调整为60，选曲表晚补',
    createdBy: '吴部长',
    createdAt: twoDaysAgo.toISOString(),
    updatedAt: yesterday.toISOString(),
    isDuplicate: false,
  },
];

export const mockChangeLogs: ChangeLog[] = [
  {
    id: 'cl1',
    recordId: 'r4',
    fieldName: 'tempo',
    oldValue: '80',
    newValue: '76',
    changedBy: '赵部长',
    changeType: ChangeType.MANUAL,
    changedAt: today.toISOString(),
    reason: '指挥要求放慢速度，更有表现力',
  },
  {
    id: 'cl2',
    recordId: 'r10',
    fieldName: 'measureStart',
    oldValue: '55',
    newValue: '60',
    changedBy: '吴部长',
    changeType: ChangeType.MANUAL,
    changedAt: yesterday.toISOString(),
    reason: '选曲表晚补，实际从第60小节开始',
  },
  {
    id: 'cl3',
    recordId: 'r2',
    fieldName: 'isDuplicate',
    oldValue: 'false',
    newValue: 'true',
    changedBy: '系统',
    changeType: ChangeType.SYSTEM,
    changedAt: today.toISOString(),
    reason: '自动检测到与记录r1重叠',
  },
  {
    id: 'cl4',
    recordId: 'r3',
    fieldName: 'status',
    oldValue: 'pending',
    newValue: 'toFill',
    changedBy: '系统',
    changeType: ChangeType.SYSTEM,
    changedAt: today.toISOString(),
    reason: '小节号颠倒，标记为待补',
  },
];

export const mockMismatchRecords: MismatchRecord[] = [
  {
    id: 'm1',
    recordId: 'r3',
    mismatchType: MismatchType.REVERSED,
    source: DataSource.MUSIC_SHEET,
    description: '小节号 50-30 写反了',
    suggestedHandler: '声部长',
    status: 'pending',
    detectedAt: today.toISOString(),
  },
  {
    id: 'm2',
    recordId: 'r2',
    mismatchType: MismatchType.OVERLAP,
    source: DataSource.MANUAL,
    description: '与王小明的另一条记录（小节1-48）重叠',
    suggestedHandler: '指挥',
    status: 'pending',
    detectedAt: today.toISOString(),
  },
  {
    id: 'm3',
    recordId: 'r5',
    mismatchType: MismatchType.DISCONTINUOUS,
    source: DataSource.METRONOME,
    description: '第30小节之后直接跳到45小节，中间缺少小节',
    suggestedHandler: '声部长',
    status: 'pending',
    detectedAt: today.toISOString(),
  },
  {
    id: 'm4',
    recordId: 'r6',
    mismatchType: MismatchType.OVERLAP,
    source: DataSource.MANUAL,
    description: '速度250异常，超出正常范围',
    suggestedHandler: '本人核对',
    status: 'pending',
    detectedAt: today.toISOString(),
  },
];

export function generateId(): string {
  return Math.random().toString(36).substring(2, 11);
}
