const DELETION_STATUS = {
  PENDING: 'PENDING',
  IN_GRACE_PERIOD: 'IN_GRACE_PERIOD',
  REVOCATION_REQUESTED: 'REVOCATION_REQUESTED',
  REVOKED: 'REVOKED',
  PURGE_SCHEDULED: 'PURGE_SCHEDULED',
  PURGE_IN_PROGRESS: 'PURGE_IN_PROGRESS',
  PURGED: 'PURGED',
  ERROR: 'ERROR',
  CANCELLED: 'CANCELLED'
};

const REVOCATION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

const PURGE_TASK_STATUS = {
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
};

const SUMMARY_TYPE = {
  DELETION_REQUEST: 'DELETION_REQUEST',
  REVOCATION: 'REVOCATION',
  PURGE_COMPLETION: 'PURGE_COMPLETION',
  FULL_AUDIT: 'FULL_AUDIT'
};

const VALID_STATUS_TRANSITIONS = {
  [DELETION_STATUS.PENDING]: [DELETION_STATUS.IN_GRACE_PERIOD, DELETION_STATUS.CANCELLED, DELETION_STATUS.ERROR],
  [DELETION_STATUS.IN_GRACE_PERIOD]: [DELETION_STATUS.REVOCATION_REQUESTED, DELETION_STATUS.PURGE_SCHEDULED, DELETION_STATUS.ERROR],
  [DELETION_STATUS.REVOCATION_REQUESTED]: [DELETION_STATUS.REVOKED, DELETION_STATUS.IN_GRACE_PERIOD, DELETION_STATUS.ERROR],
  [DELETION_STATUS.REVOKED]: [],
  [DELETION_STATUS.PURGE_SCHEDULED]: [DELETION_STATUS.PURGE_IN_PROGRESS, DELETION_STATUS.ERROR],
  [DELETION_STATUS.PURGE_IN_PROGRESS]: [DELETION_STATUS.PURGED, DELETION_STATUS.ERROR],
  [DELETION_STATUS.PURGED]: [],
  [DELETION_STATUS.ERROR]: [DELETION_STATUS.IN_GRACE_PERIOD, DELETION_STATUS.PURGE_SCHEDULED, DELETION_STATUS.CANCELLED],
  [DELETION_STATUS.CANCELLED]: []
};

module.exports = {
  DELETION_STATUS,
  REVOCATION_STATUS,
  PURGE_TASK_STATUS,
  SUMMARY_TYPE,
  VALID_STATUS_TRANSITIONS
};
