import { SubtitleCue, SceneMark, SyncRule } from '../parser/types';
import { DriftInfo, AlignmentResult } from '../alignment/aligner';
import { ValidationIssue } from '../validation/validator';

export interface ReportData {
  originalFile: string;
  transcriptFile: string;
  sceneMarksFile: string;
  rulesFile: string;
  totalCues: number;
  fixedCues: number;
  overlapsFixed: number;
  anchorPointsUsed: number;
  alignmentResult: AlignmentResult;
  validationIssues: ValidationIssue[];
  sceneMarks: SceneMark[];
}

export function generateDriftReport(data: ReportData): string {
  const { alignmentResult, validationIssues, sceneMarks, totalCues, fixedCues } = data;

  const driftStats = calculateDriftStats(alignmentResult.driftInfos);

  let md = `# Subtitle Timeline Drift Report\n\n`;
  md += `## Summary\n\n`;
  md += `- **Total Subtitles**: ${totalCues}\n`;
  md += `- **Processed Subtitles**: ${fixedCues}\n`;
  md += `- **Overlaps Fixed**: ${alignmentResult.overlapsFixed}\n`;
  md += `- **Anchor Points Used**: ${alignmentResult.anchorPointsUsed}\n\n`;

  md += `## Drift Statistics\n\n`;
  md += `- **Average Drift**: ${driftStats.avgDrift.toFixed(2)}ms\n`;
  md += `- **Max Drift**: ${driftStats.maxDrift.toFixed(2)}ms\n`;
  md += `- **Min Drift**: ${driftStats.minDrift.toFixed(2)}ms\n`;
  md += `- **Drift Std Dev**: ${driftStats.stdDev.toFixed(2)}ms\n`;
  md += `- **Average Drift Rate**: ${driftStats.avgDriftRate.toFixed(6)}\n\n`;

  if (alignmentResult.warnings.length > 0) {
    md += `## Alignment Warnings\n\n`;
    alignmentResult.warnings.forEach(w => {
      md += `- ${w}\n`;
    });
    md += `\n`;
  }

  if (validationIssues.length > 0) {
    md += `## Validation Issues\n\n`;
    const errors = validationIssues.filter(i => i.type === 'error');
    const warnings = validationIssues.filter(i => i.type === 'warning');

    if (errors.length > 0) {
      md += `### Errors\n\n`;
      errors.forEach(e => {
        md += `- **[${e.code}]** ${e.message}\n`;
        if (e.location) md += `  - Location: ${e.location}\n`;
      });
      md += `\n`;
    }

    if (warnings.length > 0) {
      md += `### Warnings\n\n`;
      warnings.forEach(w => {
        md += `- **[${w.code}]** ${w.message}\n`;
        if (w.location) md += `  - Location: ${w.location}\n`;
      });
      md += `\n`;
    }
  } else {
    md += `## Validation Issues\n\n`;
    md += `No validation issues detected.\n\n`;
  }

  if (sceneMarks.length > 0) {
    md += `## Scene Marks\n\n`;
    sceneMarks.forEach(sm => {
      md += `- [${sm.type}] ${sm.label}: ${formatTime(sm.timestamp)}\n`;
    });
    md += `\n`;
  }

  if (alignmentResult.driftInfos.length > 0) {
    md += `## Drift Timeline (Sample)\n\n`;
    md += `| Original Time | Adjusted Time | Drift | Drift Rate |\n`;
    md += `|---------------|---------------|-------|------------|\n`;

    const sampleSize = Math.min(10, alignmentResult.driftInfos.length);
    const step = Math.max(1, Math.floor(alignmentResult.driftInfos.length / sampleSize));

    for (let i = 0; i < alignmentResult.driftInfos.length; i += step) {
      const d = alignmentResult.driftInfos[i];
      md += `| ${formatTime(d.originalTime)} | ${formatTime(d.translatedTime)} | ${d.drift.toFixed(2)}ms | ${d.driftRate.toFixed(6)} |\n`;
    }
    md += `\n`;
  }

  md += `---\n\n`;
  md += `*Report generated by subtitle-sync-fix*\n`;

  return md;
}

function calculateDriftStats(driftInfos: DriftInfo[]): {
  avgDrift: number;
  maxDrift: number;
  minDrift: number;
  stdDev: number;
  avgDriftRate: number;
} {
  if (driftInfos.length === 0) {
    return { avgDrift: 0, maxDrift: 0, minDrift: 0, stdDev: 0, avgDriftRate: 1 };
  }

  const drifts = driftInfos.map(d => d.drift);
  const driftRates = driftInfos.map(d => d.driftRate);

  const avgDrift = drifts.reduce((a, b) => a + b, 0) / drifts.length;
  const maxDrift = Math.max(...drifts);
  const minDrift = Math.min(...drifts);
  const variance = drifts.reduce((sum, d) => sum + Math.pow(d - avgDrift, 2), 0) / drifts.length;
  const stdDev = Math.sqrt(variance);
  const avgDriftRate = driftRates.reduce((a, b) => a + b, 0) / driftRates.length;

  return { avgDrift, maxDrift, minDrift, stdDev, avgDriftRate };
}

function formatTime(ms: number): string {
  const hours = Math.floor(ms / 3600000);
  const minutes = Math.floor((ms % 3600000) / 60000);
  const seconds = Math.floor((ms % 60000) / 1000);
  const milliseconds = Math.floor(ms % 1000);

  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}.${milliseconds.toString().padStart(3, '0')}`;
  }
  return `${minutes}:${seconds.toString().padStart(2, '0')}.${milliseconds.toString().padStart(3, '0')}`;
}

export function generateTimelineHtml(
  cues: SubtitleCue[],
  sceneMarks: SceneMark[],
  driftInfos: DriftInfo[]
): string {
  const duration = Math.max(...cues.map(c => c.endTime), 0);
  const sceneMarkPositions = sceneMarks.map(sm => ({
    ...sm,
    position: (sm.timestamp / duration) * 100
  }));

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Subtitle Timeline Viewer</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #1a1a2e;
      color: #eee;
      min-height: 100vh;
      padding: 20px;
    }
    h1 {
      text-align: center;
      margin-bottom: 20px;
      color: #00d4ff;
    }
    .timeline-container {
      background: #16213e;
      border-radius: 8px;
      padding: 20px;
      margin-bottom: 20px;
    }
    .timeline {
      position: relative;
      height: 60px;
      background: #0f3460;
      border-radius: 4px;
      margin: 20px 0;
    }
    .cue {
      position: absolute;
      height: 30px;
      top: 15px;
      background: linear-gradient(90deg, #00d4ff, #0099cc);
      border-radius: 4px;
      min-width: 20px;
      cursor: pointer;
      transition: all 0.2s;
    }
    .cue:hover {
      background: linear-gradient(90deg, #00ffcc, #00cc99);
      transform: scaleY(1.2);
    }
    .scene-marker {
      position: absolute;
      top: 0;
      width: 2px;
      height: 60px;
      background: #ff6b6b;
    }
    .scene-marker::after {
      content: attr(data-label);
      position: absolute;
      top: -20px;
      left: 50%;
      transform: translateX(-50%);
      font-size: 10px;
      color: #ff6b6b;
      white-space: nowrap;
    }
    .time-ruler {
      display: flex;
      justify-content: space-between;
      font-size: 12px;
      color: #888;
      margin-top: 5px;
    }
    .legend {
      display: flex;
      gap: 20px;
      justify-content: center;
      margin-top: 10px;
      font-size: 14px;
    }
    .legend-item {
      display: flex;
      align-items: center;
      gap: 5px;
    }
    .legend-cue {
      width: 20px;
      height: 15px;
      background: linear-gradient(90deg, #00d4ff, #0099cc);
      border-radius: 2px;
    }
    .legend-marker {
      width: 2px;
      height: 15px;
      background: #ff6b6b;
    }
    .subtitle-list {
      background: #16213e;
      border-radius: 8px;
      padding: 20px;
      max-height: 400px;
      overflow-y: auto;
    }
    .subtitle-item {
      padding: 10px;
      margin: 5px 0;
      background: #0f3460;
      border-radius: 4px;
      border-left: 3px solid #00d4ff;
    }
    .subtitle-time {
      font-size: 12px;
      color: #00d4ff;
      margin-bottom: 5px;
    }
    .subtitle-text {
      font-size: 14px;
    }
    .drift-indicator {
      font-size: 11px;
      padding: 2px 6px;
      border-radius: 3px;
      margin-left: 10px;
    }
    .drift-positive { background: #ff6b6b; color: #fff; }
    .drift-negative { background: #4ecdc4; color: #fff; }
    .drift-zero { background: #95a5a6; color: #fff; }
  </style>
</head>
<body>
  <h1>Subtitle Timeline Viewer</h1>

  <div class="timeline-container">
    <div class="timeline" id="timeline">
      ${cues.map((cue, i) => {
        const left = (cue.startTime / duration) * 100;
        const width = Math.max(((cue.endTime - cue.startTime) / duration) * 100, 0.5);
        const drift = driftInfos[i] ? driftInfos[i].drift : 0;
        const driftClass = drift > 0 ? 'drift-positive' : drift < 0 ? 'drift-negative' : 'drift-zero';
        return `<div class="cue" style="left: ${left}%; width: ${width}%;" title="${cue.text.replace(/"/g, '&quot;')}" data-index="${i + 1}" data-drift="${drift.toFixed(2)}"></div>`;
      }).join('\n      ')}
      ${sceneMarkPositions.map(sm => `<div class="scene-marker" style="left: ${sm.position}%;" data-label="${sm.label}"></div>`).join('\n      ')}
    </div>
    <div class="time-ruler">
      ${generateTimeRuler(duration)}
    </div>
    <div class="legend">
      <div class="legend-item"><div class="legend-cue"></div> Subtitles</div>
      <div class="legend-item"><div class="legend-marker"></div> Scene Marks</div>
    </div>
  </div>

  <div class="subtitle-list" id="subtitleList">
    ${cues.map((cue, i) => {
      const drift = driftInfos[i] ? driftInfos[i].drift : 0;
      const driftClass = drift > 0 ? 'drift-positive' : drift < 0 ? 'drift-negative' : 'drift-zero';
      return `<div class="subtitle-item">
        <div class="subtitle-time">${formatHtmlTime(cue.startTime)} --> ${formatHtmlTime(cue.endTime)} <span class="drift-indicator ${driftClass}">${drift > 0 ? '+' : ''}${drift.toFixed(0)}ms</span></div>
        <div class="subtitle-text">${cue.text}</div>
      </div>`;
    }).join('\n    ')}
  </div>

  <script>
    const cues = document.querySelectorAll('.cue');
    const list = document.getElementById('subtitleList');

    cues.forEach(cue => {
      cue.addEventListener('click', () => {
        const index = parseInt(cue.dataset.index) - 1;
        const items = list.querySelectorAll('.subtitle-item');
        if (items[index]) {
          items[index].scrollIntoView({ behavior: 'smooth', block: 'center' });
          items[index].style.background = '#1f4068';
          setTimeout(() => { items[index].style.background = '#0f3460'; }, 1000);
        }
      });
    });
  </script>
</body>
</html>`;

  return html;
}

function generateTimeRuler(duration: number): string {
  const intervals = 10;
  let ruler = '';
  for (let i = 0; i <= intervals; i++) {
    const time = (duration * i) / intervals;
    ruler += `<span>${formatHtmlTime(time)}</span>`;
  }
  return ruler;
}

function formatHtmlTime(ms: number): string {
  const minutes = Math.floor(ms / 60000);
  const seconds = Math.floor((ms % 60000) / 1000);
  return `${minutes}:${seconds.toString().padStart(2, '0')}`;
}
