import os

def build():
    out = []
    out.append('#!/usr/bin/env python3')
    out.append('import os')
    out.append('import stat')
    out.append('import json')
    out.append('import sys')
    out.append('from datetime import datetime')
    out.append('from dataclasses import dataclass')
    out.append('from typing import List, Dict, Any')
    out.append('import click')
    out.append('')
    
    out.append('@dataclass')
    out.append('class PermissionEntry:')
    out.append('    path: str')
    out.append('    mode: str')
    out.append('    owner: str')
    out.append('    error: str = None')
    out.append('')
    
    out.append('@dataclass')
    out.append('class DiffResult:')
    out.append('    path: str')
    out.append('    field: str')
    out.append('    old: Any')
    out.append('    new: Any')
    out.append('')
    
    out.append('class Scanner:')
    out.append('    def __init__(self, path):')
    out.append('        self.path = os.path.abspath(path)')
    out.append('        self.entries = []')
    out.append('        self.errors = []')
    out.append('')
    out.append('    def scan(self):')
    out.append('        if not os.path.exists(self.path):')
    out.append('            self.errors.append({"path":self.path,"error":"Not found"})')
    out.append('            return self.entries, self.errors')
    out.append('        if os.path.isdir(self.path):')
    out.append('            for root, dirs, files in os.walk(self.path):')
    out.append('                for name in dirs + files:')
    out.append('                    full = os.path.join(root, name)')
    out.append('                    self._scan_one(full)')
    out.append('        else:')
    out.append('            self._scan_one(self.path)')
    out.append('        return self.entries, self.errors')
    out.append('')
    out.append('    def _scan_one(self, path):')
    out.append('        try:')
    out.append('            st = os.lstat(path)')
    out.append('            mode = oct(stat.S_IMODE(st.st_mode))[2:].zfill(3)')
    out.append('            try: owner = os.getpwuid(st.st_uid).pw_name')
    out.append('            except: owner = str(st.st_uid)')
    out.append('            self.entries.append(PermissionEntry(path, mode, owner))')
    out.append('        except Exception as e:')
    out.append('            err = str(e)')
    out.append('            self.errors.append({"path":path,"error":err})')
    out.append('            self.entries.append(PermissionEntry(path, "", "", error=err))')
    out.append('')
    
    out.append('class Manager:')
    out.append('    def __init__(self, sdir=".perm-snapshots"):')
    out.append('        self.sdir = sdir')
    out.append('        os.makedirs(sdir, exist_ok=True)')
    out.append('')
    out.append('    def save(self, name, entries, errors):')
    out.append('        ts = datetime.now().strftime("%Y%m%d_%H%M%S")')
    out.append('        fn = f"{name}_{ts}.json"')
    out.append('        fp = os.path.join(self.sdir, fn)')
    out.append('        data = {"name":name,"timestamp":ts,"entries":[e.__dict__ for e in entries],"errors":errors}')
    out.append('        with open(fp, "w") as f: json.dump(data, f, indent=2)')
    out.append('        return fp')
    out.append('')
    out.append('    def load(self, fp):')
    out.append('        with open(fp) as f: return json.load(f)')
    out.append('')
    out.append('    def list(self):')
    out.append('        if not os.path.exists(self.sdir): return []')
    out.append('        return sorted([f for f in os.listdir(self.sdir) if f.endswith(".json")])')
    out.append('')
    
    out.append('class Differ:')
    out.append('    def compare(self, base, curr):')
    out.append('        be = {e["path"]:e for e in base["entries"]}')
    out.append('        ce = {e["path"]:e for e in curr["entries"]}')
    out.append('        diffs = []')
    out.append('        added = []')
    out.append('        removed = []')
    out.append('        all_paths = set(be.keys()) | set(ce.keys())')
    out.append('        for p in all_paths:')
    out.append('            if p not in be: added.append(ce[p])')
    out.append('            elif p not in ce: removed.append(be[p])')
    out.append('            else:')
    out.append('                b = be[p]')
    out.append('                c = ce[p]')
    out.append('                for k in ["mode","owner"]:')
    out.append('                    if b.get(k) != c.get(k):')
    out.append('                        diffs.append(DiffResult(p, k, b.get(k), c.get(k)))')
    out.append('        return diffs, added, removed')
    out.append('')
    
    out.append('class Reporter:')
    out.append('    def summary(self, diffs, added, removed, errors):')
    out.append('        lines = ["="*60, "  Permission Snapshot Diff Summary", "="*60]')
    out.append('        lines.append(f"Modified: {len(diffs)}, Added: {len(added)}, Removed: {len(removed)}, Errors: {len(errors)}")')
    out.append('        if diffs:')
    out.append('            lines.append("-"*60)')
    out.append('            lines.append("Modifications:")')
    out.append('            for d in diffs[:10]: lines.append(f"  {d.path}: {d.old} -> {d.new}")')
    out.append('        if added:')
    out.append('            lines.append("-"*60)')
    out.append('            lines.append("Added:")')
    out.append('            for a in added[:5]: lines.append(f"  + {a[\'path\']}")')
    out.append('        if removed:')
    out.append('            lines.append("-"*60)')
    out.append('            lines.append("Removed:")')
    out.append('            for r in removed[:5]: lines.append(f"  - {r[\'path\']}")')
    out.append('        if errors:')
    out.append('            lines.append("-"*60)')
    out.append('            lines.append("Errors:")')
    out.append('            for e in errors: lines.append(f"  {e[\'path\']}: {e[\'error\']}")')
    out.append('        lines.append("="*60)')
    out.append('        return "\\n".join(lines)')
    out.append('')
    out.append('    def json_out(self, diffs, added, removed, errors, bname, cname):')
    out.append('        return json.dumps({"baseline":bname,"current":cname,"summary":')
    out.append('            {"modified":len(diffs),"added":len(added),"removed":len(removed),"errors":len(errors)},')
    out.append('            "modified":[{"path":d.path,"field":d.field,"old":d.old,"new":d.new} for d in diffs],')
    out.append('            "added":added,"removed":removed,"errors":errors}, indent=2)')
    out.append('')
    
    out.append('@click.group()')
    out.append('def cli(): pass')
    out.append('')
    
    out.append('@cli.command()')
    out.append('@click.argument("path")')
    out.append('@click.option("--name", "-n")')
    out.append('def scan(path, name):')
    out.append('    if not os.path.exists(path):')
    out.append('        click.echo(f"Error: {path} not found", err=True)')
    out.append('        sys.exit(1)')
    out.append('    if not name: name = os.path.basename(os.path.abspath(path))')
    out.append('    s = Scanner(path)')
    out.append('    entries, errors = s.scan()')
    out.append('    m = Manager()')
    out.append('    fp = m.save(name, entries, errors)')
    out.append('    click.echo(f"Snapshot saved: {fp} ({len(entries)} entries, {len(errors)} errors)")')
    out.append('    if errors: sys.exit(2)')
    out.append('')
    
    out.append('@cli.command("list")')
    out.append('def list_snaps():')
    out.append('    m = Manager()')
    out.append('    snaps = m.list()')
    out.append('    if not snaps: click.echo("No snapshots found")')
    out.append('    else:')
    out.append('        click.echo("Snapshots:")')
    out.append('        for i, s in enumerate(snaps, 1): click.echo(f"  {i}. {s}")')
    out.append('')
    
    out.append('@cli.command()')
    out.append('@click.argument("baseline")')
    out.append('@click.option("--path", "-p")')
    out.append('@click.option("--output-json")')
    out.append('def diff(baseline, path, output_json):')
    out.append('    m = Manager()')
    out.append('    if os.path.exists(baseline): bf = baseline')
    out.append('    else: bf = os.path.join(".perm-snapshots", baseline)')
    out.append('    if not os.path.exists(bf):')
    out.append('        click.echo(f"Error: baseline {bf} not found", err=True)')
    out.append('        sys.exit(1)')
    out.append('    bdata = m.load(bf)')
    out.append('    if path:')
    out.append('        s = Scanner(path)')
    out.append('        entries, errors = s.scan()')
    out.append('        cdata = {"name":"current_scan","entries":[e.__dict__ for e in entries],"errors":errors}')
    out.append('    else:')
    out.append('        click.echo("Error: specify --path", err=True)')
    out.append('        sys.exit(1)')
    out.append('    d = Differ()')
    out.append('    diffs, added, removed = d.compare(bdata, cdata)')
    out.append('    r = Reporter()')
    out.append('    click.echo(r.summary(diffs, added, removed, errors))')
    out.append('    if output_json:')
    out.append('        with open(output_json, "w") as f: f.write(r.json_out(diffs, added, removed, errors, bdata["name"], cdata["name"]))')
    out.append('        click.echo(f"JSON saved to {output_json}")')
    out.append('    if errors: sys.exit(2)')
    out.append('    elif diffs or added or removed: sys.exit(3)')
    out.append('')
    
    out.append('@cli.command()')
    out.append('@click.argument("snap")')
    out.append('def show(snap):')
    out.append('    m = Manager()')
    out.append('    if os.path.exists(snap): fp = snap')
    out.append('    else: fp = os.path.join(".perm-snapshots", snap)')
    out.append('    if not os.path.exists(fp):')
    out.append('        click.echo(f"Error: {fp} not found", err=True)')
    out.append('        sys.exit(1)')
    out.append('    data = m.load(fp)')
    out.append('    click.echo(f"Snapshot: {data[\'name\']}")')
    out.append('    click.echo(f"Entries: {len(data[\'entries\'])}, Errors: {len(data[\'errors\'])}")')
    out.append('    for e in data["entries"]:')
    out.append('        err = " [ERROR]" if e.get("error") else ""')
    out.append('        click.echo(f"  {e[\'mode\']} {e[\'owner\']} {e[\'path\']}{err}")')
    out.append('')
    
    out.append('if __name__ == "__main__":')
    out.append('    cli()')
    
    with open('perm_snapshot.py', 'w') as f:
        f.write('\n'.join(out))
    os.chmod('perm_snapshot.py', 0o755)
    print('Created perm_snapshot.py successfully!')

if __name__ == '__main__':
    build()
