export class BusinessError extends Error {
  public readonly code: string;
  public readonly details?: Record<string, unknown>;

  constructor(code: string, message: string, details?: Record<string, unknown>) {
    super(message);
    this.code = code;
    this.details = details;
    this.name = 'BusinessError';
  }
}

export const ErrorCodes = {
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  TEACHER_NOT_FOUND: 'TEACHER_NOT_FOUND',
  CLASS_NOT_FOUND: 'CLASS_NOT_FOUND',
  LESSON_NOT_FOUND: 'LESSON_NOT_FOUND',
  PACKAGE_NOT_FOUND: 'PACKAGE_NOT_FOUND',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  LEAVE_NOT_FOUND: 'LEAVE_NOT_FOUND',
  MAKEUP_TICKET_NOT_FOUND: 'MAKEUP_TICKET_NOT_FOUND',
  WAITLIST_NOT_FOUND: 'WAITLIST_NOT_FOUND',
  
  CLASS_CAPACITY_FULL: 'CLASS_CAPACITY_FULL',
  STUDENT_ALREADY_BOOKED: 'STUDENT_ALREADY_BOOKED',
  TIME_SLOT_CONFLICT: 'TIME_SLOT_CONFLICT',
  PACKAGE_EXPIRED: 'PACKAGE_EXPIRED',
  PACKAGE_FROZEN: 'PACKAGE_FROZEN',
  INSUFFICIENT_LESSONS: 'INSUFFICIENT_LESSONS',
  MAKEUP_TICKET_EXPIRED: 'MAKEUP_TICKET_EXPIRED',
  MAKEUP_TICKET_USED: 'MAKEUP_TICKET_USED',
  LESSON_ALREADY_STARTED: 'LESSON_ALREADY_STARTED',
  LESSON_COMPLETED: 'LESSON_COMPLETED',
  ALREADY_ON_WAITLIST: 'ALREADY_ON_WAITLIST',
  WAITLIST_EMPTY: 'WAITLIST_EMPTY',
  
  INVALID_INPUT: 'INVALID_INPUT',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
