import type { TimelineRecord, InspectionRecord, WeeklyReportItem } from "@/types"

export const timelineRecords: TimelineRecord[] = [
  {
    id: "tl-001",
    source: "grayscale",
    timestamp: "2026-05-30T14:20:00",
    title: "提示词 v3.2.1 灰度发布至 10% 流量",
    summary: "本次灰度将新的意图识别提示词推至 10% 流量池，核心变更：增加多轮上下文召回逻辑",
    status: "confirmed",
    modifier: "张伟",
    tags: ["意图识别", "灰度"],
  },
  {
    id: "tl-002",
    source: "quality_check",
    timestamp: "2026-05-30T13:45:00",
    title: "质检批次 QC-2026-0530 抽检完成",
    summary: "本轮抽检 120 条对话，合格率 94.2%，3 条涉及敏感词未脱敏",
    status: "pending",
    modifier: "李敏",
    pendingReason: "3 条敏感词漏脱敏待处理",
    tags: ["抽检", "敏感词"],
  },
  {
    id: "tl-003",
    source: "customer_service",
    timestamp: "2026-05-30T11:30:00",
    title: "用户 #U8821 投诉 AI 回复与咨询无关",
    summary: "用户询问退货流程，AI 回复了物流查询方式。疑似提示词 v3.2.0 上下文截断导致",
    status: "manual_corrected",
    modifier: "王芳",
    tags: ["投诉", "上下文截断"],
  },
  {
    id: "tl-004",
    source: "grayscale",
    timestamp: "2026-05-29T16:00:00",
    title: "提示词 v3.2.0 全量发布",
    summary: "意图识别提示词 v3.2.0 由灰度转全量，覆盖 100% 流量",
    status: "confirmed",
    modifier: "张伟",
    tags: ["意图识别", "全量"],
  },
  {
    id: "tl-005",
    source: "quality_check",
    timestamp: "2026-05-29T10:15:00",
    title: "质检批次 QC-2026-0529（晚到附件）",
    summary: "5月28日抽检数据因系统延迟，附件于29日到达。含 85 条对话，合格率 91.8%",
    status: "pending",
    modifier: "李敏",
    pendingReason: "晚到附件，数据完整性待确认",
    isLateAttachment: true,
    tags: ["抽检", "晚到"],
  },
  {
    id: "tl-006",
    source: "customer_service",
    timestamp: "2026-05-29T09:00:00",
    title: "用户 #U7743 咨询账单问题（重复记录）",
    summary: "该对话已在 5月28日录入，系统重复推送。内容一致，无新增信息",
    status: "confirmed",
    isDuplicate: true,
    tags: ["重复", "账单"],
  },
  {
    id: "tl-007",
    source: "grayscale",
    timestamp: "2026-05-28T15:30:00",
    title: "提示词 v3.1.9 灰度发布至 50% 流量",
    summary: "修复 v3.1.8 中情感分析误判问题，灰度范围扩大至 50%",
    status: "confirmed",
    modifier: "陈刚",
    tags: ["情感分析", "灰度"],
  },
  {
    id: "tl-008",
    source: "quality_check",
    timestamp: "2026-05-28T14:00:00",
    title: "质检批次 QC-2026-0528 人工更正",
    summary: "原自动评分将 4 条合格对话误标为不合格，已由质检员手动更正",
    status: "manual_corrected",
    modifier: "赵丽",
    tags: ["人工更正", "误标"],
  },
  {
    id: "tl-009",
    source: "customer_service",
    timestamp: "2026-05-28T10:45:00",
    title: "用户 #U6650 反馈 AI 语气生硬",
    summary: "用户认为 AI 回复缺乏同理心，情感分析提示词可能需要调整",
    status: "pending",
    modifier: "王芳",
    pendingReason: "待确认是否为提示词问题而非场景限制",
    tags: ["反馈", "情感"],
  },
  {
    id: "tl-010",
    source: "grayscale",
    timestamp: "2026-05-27T17:00:00",
    title: "提示词 v3.1.8 灰度发布至 5% 流量",
    summary: "新增情感分析模块，初步灰度至 5% 观察效果",
    status: "confirmed",
    modifier: "陈刚",
    tags: ["情感分析", "灰度"],
  },
  {
    id: "tl-011",
    source: "quality_check",
    timestamp: "2026-05-27T11:00:00",
    title: "质检批次 QC-2026-0527 抽检完成",
    summary: "本轮抽检 200 条对话，合格率 96.5%，1 条敏感词漏脱敏",
    status: "confirmed",
    modifier: "李敏",
    tags: ["抽检"],
  },
  {
    id: "tl-012",
    source: "customer_service",
    timestamp: "2026-05-27T08:30:00",
    title: "用户 #U5532 咨询退款流程",
    summary: "正常退款咨询，AI 回复准确，用户满意",
    status: "confirmed",
    tags: ["退款", "正常"],
  },
]

export const inspectionRecords: InspectionRecord[] = [
  {
    id: "insp-001",
    sourceSystem: "灰度发布平台",
    sourceIcon: "Rocket",
    promptVersion: "v3.2.1",
    currentStatus: "confirmed",
    modifier: "张伟",
    modifiedAt: "2026-05-30T14:20:00",
    changeHistory: [
      { timestamp: "2026-05-30T14:20:00", operator: "张伟", fromStatus: "pending", toStatus: "confirmed", remark: "灰度指标正常，确认发布" },
      { timestamp: "2026-05-30T10:00:00", operator: "系统", fromStatus: "pending", toStatus: "pending", remark: "自动创建灰度记录" },
    ],
  },
  {
    id: "insp-002",
    sourceSystem: "质检系统",
    sourceIcon: "ClipboardCheck",
    promptVersion: "v3.2.0",
    currentStatus: "pending",
    modifier: "李敏",
    modifiedAt: "2026-05-30T13:45:00",
    pendingReason: "3 条敏感词未脱敏，需运营确认处理方式",
    changeHistory: [
      { timestamp: "2026-05-30T13:45:00", operator: "李敏", fromStatus: "confirmed", toStatus: "pending", remark: "发现敏感词漏脱敏，回退至待处理" },
      { timestamp: "2026-05-30T09:00:00", operator: "系统", fromStatus: "pending", toStatus: "confirmed", remark: "自动评分合格" },
    ],
  },
  {
    id: "insp-003",
    sourceSystem: "客服工单系统",
    sourceIcon: "Headphones",
    promptVersion: "v3.2.0",
    currentStatus: "manual_corrected",
    modifier: "王芳",
    modifiedAt: "2026-05-30T11:30:00",
    isManualCorrection: true,
    changeHistory: [
      { timestamp: "2026-05-30T11:30:00", operator: "王芳", fromStatus: "pending", toStatus: "manual_corrected", remark: "人工更正：将上下文截断问题标记为提示词缺陷" },
      { timestamp: "2026-05-30T11:00:00", operator: "系统", fromStatus: "confirmed", toStatus: "pending", remark: "用户投诉触发自动待处理" },
    ],
  },
  {
    id: "insp-004",
    sourceSystem: "灰度发布平台",
    sourceIcon: "Rocket",
    promptVersion: "v3.2.0",
    currentStatus: "confirmed",
    modifier: "张伟",
    modifiedAt: "2026-05-29T16:00:00",
    changeHistory: [
      { timestamp: "2026-05-29T16:00:00", operator: "张伟", fromStatus: "pending", toStatus: "confirmed", remark: "灰度转全量确认" },
      { timestamp: "2026-05-28T15:30:00", operator: "陈刚", fromStatus: "pending", toStatus: "pending", remark: "扩大灰度范围至 50%" },
    ],
  },
  {
    id: "insp-005",
    sourceSystem: "质检系统",
    sourceIcon: "ClipboardCheck",
    promptVersion: "v3.2.0",
    currentStatus: "pending",
    modifier: "李敏",
    modifiedAt: "2026-05-29T10:15:00",
    pendingReason: "晚到附件，数据完整性待确认",
    isLateAttachment: true,
    changeHistory: [
      { timestamp: "2026-05-29T10:15:00", operator: "系统", fromStatus: "pending", toStatus: "pending", remark: "附件延迟到达，等待数据完整性校验" },
    ],
  },
  {
    id: "insp-006",
    sourceSystem: "客服工单系统",
    sourceIcon: "Headphones",
    promptVersion: "v3.1.9",
    currentStatus: "confirmed",
    modifier: "系统",
    modifiedAt: "2026-05-29T09:00:00",
    isDuplicate: true,
    changeHistory: [
      { timestamp: "2026-05-29T09:00:00", operator: "系统", fromStatus: "pending", toStatus: "confirmed", remark: "标记为重复记录，保留原始记录" },
    ],
  },
  {
    id: "insp-007",
    sourceSystem: "灰度发布平台",
    sourceIcon: "Rocket",
    promptVersion: "v3.1.9",
    currentStatus: "confirmed",
    modifier: "陈刚",
    modifiedAt: "2026-05-28T15:30:00",
    changeHistory: [
      { timestamp: "2026-05-28T15:30:00", operator: "陈刚", fromStatus: "pending", toStatus: "confirmed", remark: "灰度 50% 指标正常" },
      { timestamp: "2026-05-27T17:00:00", operator: "陈刚", fromStatus: "pending", toStatus: "pending", remark: "启动灰度 5%" },
    ],
  },
  {
    id: "insp-008",
    sourceSystem: "质检系统",
    sourceIcon: "ClipboardCheck",
    promptVersion: "v3.1.9",
    currentStatus: "manual_corrected",
    modifier: "赵丽",
    modifiedAt: "2026-05-28T14:00:00",
    isManualCorrection: true,
    changeHistory: [
      { timestamp: "2026-05-28T14:00:00", operator: "赵丽", fromStatus: "confirmed", toStatus: "manual_corrected", remark: "4 条对话被自动评分误判，人工更正为合格" },
      { timestamp: "2026-05-28T09:00:00", operator: "系统", fromStatus: "pending", toStatus: "confirmed", remark: "自动评分完成" },
    ],
  },
  {
    id: "insp-009",
    sourceSystem: "客服工单系统",
    sourceIcon: "Headphones",
    promptVersion: "v3.1.9",
    currentStatus: "pending",
    modifier: "王芳",
    modifiedAt: "2026-05-28T10:45:00",
    pendingReason: "待确认是否为提示词问题而非场景限制",
    changeHistory: [
      { timestamp: "2026-05-28T10:45:00", operator: "王芳", fromStatus: "confirmed", toStatus: "pending", remark: "用户反馈语气生硬，待根因分析" },
    ],
  },
  {
    id: "insp-010",
    sourceSystem: "灰度发布平台",
    sourceIcon: "Rocket",
    promptVersion: "v3.1.8",
    currentStatus: "confirmed",
    modifier: "陈刚",
    modifiedAt: "2026-05-27T17:00:00",
    changeHistory: [
      { timestamp: "2026-05-27T17:00:00", operator: "陈刚", fromStatus: "pending", toStatus: "confirmed", remark: "灰度 5% 启动确认" },
    ],
  },
]

export const weeklyReportItems: WeeklyReportItem[] = [
  {
    id: "wr-001",
    recordId: "insp-001",
    category: "confirmed",
    processingStance: "灰度指标达标，已确认 v3.2.1 进入灰度阶段",
    summary: "提示词 v3.2.1 灰度发布至 10% 流量",
    source: "grayscale",
    timestamp: "2026-05-30T14:20:00",
  },
  {
    id: "wr-002",
    recordId: "insp-004",
    category: "confirmed",
    processingStance: "灰度周期完整，指标合格，已转全量",
    summary: "提示词 v3.2.0 由灰度转全量发布",
    source: "grayscale",
    timestamp: "2026-05-29T16:00:00",
  },
  {
    id: "wr-003",
    recordId: "insp-006",
    category: "confirmed",
    processingStance: "确认为重复推送，原始记录已在上一周期处理",
    summary: "用户 #U7743 咨询重复记录",
    source: "customer_service",
    timestamp: "2026-05-29T09:00:00",
  },
  {
    id: "wr-004",
    recordId: "insp-007",
    category: "confirmed",
    processingStance: "灰度 50% 阶段指标正常，已确认继续推进",
    summary: "提示词 v3.1.9 灰度至 50%",
    source: "grayscale",
    timestamp: "2026-05-28T15:30:00",
  },
  {
    id: "wr-005",
    recordId: "insp-010",
    category: "confirmed",
    processingStance: "新功能灰度启动，5% 流量观察中",
    summary: "提示词 v3.1.8 情感分析灰度启动",
    source: "grayscale",
    timestamp: "2026-05-27T17:00:00",
  },
  {
    id: "wr-006",
    recordId: "insp-002",
    category: "pending",
    processingStance: "敏感词漏脱敏已标记，需运营确认是否需要回溯处理历史对话",
    summary: "质检批次 QC-2026-0530 发现 3 条敏感词未脱敏",
    source: "quality_check",
    timestamp: "2026-05-30T13:45:00",
  },
  {
    id: "wr-007",
    recordId: "insp-005",
    category: "pending",
    processingStance: "晚到附件已接收，待数据完整性校验后补录",
    summary: "质检批次 QC-2026-0529 晚到附件",
    source: "quality_check",
    timestamp: "2026-05-29T10:15:00",
  },
  {
    id: "wr-008",
    recordId: "insp-009",
    category: "pending",
    processingStance: "用户反馈语气生硬，待根因分析确认是否为提示词缺陷",
    summary: "用户 #U6650 反馈 AI 语气生硬",
    source: "customer_service",
    timestamp: "2026-05-28T10:45:00",
  },
  {
    id: "wr-009",
    recordId: "insp-003",
    category: "manual_corrected",
    processingStance: "上下文截断标记为提示词缺陷，已提交修复工单",
    summary: "用户 #U8821 投诉 AI 回复无关，人工更正为提示词缺陷",
    source: "customer_service",
    timestamp: "2026-05-30T11:30:00",
  },
  {
    id: "wr-010",
    recordId: "insp-008",
    category: "manual_corrected",
    processingStance: "自动评分误判 4 条合格对话，质检员已更正，评分模型待优化",
    summary: "质检批次 QC-2026-0528 人工更正自动评分误判",
    source: "quality_check",
    timestamp: "2026-05-28T14:00:00",
  },
]
