import os

TARGET = os.path.join(os.path.dirname(__file__), 'ensemble_vote_explainer.py')

lines = []
def L(s=""):
    lines.append(s)

L("from typing import List, Dict, Tuple, Optional")
L("from collections import defaultdict")
L("import uuid")
L("from datetime import datetime")
L("from models import (")
L("    Material, MaterialType, ThresholdNote, OnlineExperimentBucket,")
L("    VotingResult, WorkflowStep, ReviewStatus, SelfCheckResult, ConflictEvidence,")
L("    ThresholdChangeRecord, MaterialBatch")
L(")")
L("from errors import (")
L("    MinorityMaskedError, ThresholdConflictError, WorkflowStepError, FriendlyError")
L(")")
L("")
L("")
L("class ThresholdPlaybackValidator:")
L("    def __init__(self):")
L("        self._threshold_history: Dict[str, List[ThresholdChangeRecord]] = defaultdict(list)")
L("")
L("    def record_change(self, record: ThresholdChangeRecord):")
L("        self._threshold_history[record.model_name].append(record)")
L("")
L("    def validate_playback(self, model_name: str, expected_threshold: float,")
L("                          expected_minority: Optional[float] = None) -> Tuple[bool, str]:")
L("        if model_name not in self._threshold_history:")
L("            return False, \"no history\"")
L("        history = self._threshold_history[model_name]")
L("        last_record = history[-1]")
L("        threshold_match = abs(last_record.new_threshold - expected_threshold) < 1e-6")
L("        minority_match = True")
L("        if expected_minority is not None and last_record.new_minority_threshold is not None:")
L("            minority_match = abs(last_record.new_minority_threshold - expected_minority) < 1e-6")
L("        if threshold_match and minority_match:")
L("            return True, (\"ok from \" + last_record.change_source)")
L("        else:")
L("            return False, (\"mismatch history=\" + str(last_record.new_threshold))")
L("")
L("    def get_history(self, model_name: str) -> List[ThresholdChangeRecord]:")
L("        return list(self._threshold_history.get(model_name, []))")
L("")
L("    def get_detailed_history(self, model_name: str) -> List[Dict]:")
L("        history = self.get_history(model_name)")
L("        result = []")
L("        for i, record in enumerate(history, 1):")
L("            result.append({")
L("                \"idx\": i, \"change_id\": record.change_id, \"batch\": record.batch_number,")
L("                \"old_t\": record.old_threshold, \"new_t\": record.new_threshold,")
L("                \"old_mt\": record.old_minority_threshold, \"new_mt\": record.new_minority_threshold,")
L("                \"source\": record.change_source, \"reason\": record.change_reason,")
L("                \"op\": record.operator, \"at\": record.changed_at, \"affect\": record.affected_items")
L("            })")
L("        return result")
L("")
L("")
L("class ConflictDetector:")
L("    def detect_conflicts(self, notes, buckets):")
L("        conflicts = []")
L("        nt = {tn.model_name: tn.threshold for tn in notes}")
L("        bt = {eb.model_name: eb.threshold for eb in buckets}")
L("        for mn in set(nt.keys()) | set(bt.keys()):")
L("            if mn in nt and mn in bt and abs(nt[mn] - bt[mn]) > 1e-6:")
L("                note = next(tn for tn in notes if tn.model_name == mn)")
L("                bucket = next(eb for eb in buckets if eb.model_name == mn)")
L("                conflicts.append(ConflictEvidence(")
L("                    model_name=mn, threshold_note_value=nt[mn],")
L("                    experiment_bucket_value=bt[mn], threshold_note_id=note.note_id,")
L("                    experiment_bucket_id=bucket.bucket_id,")
L("                    description=(\"note[\" + note.note_id + \"]=\" + str(nt[mn]) +")
L("                                 \" bucket[\" + bucket.bucket_id + \"]=\" + str(bt[mn]))")
L("                ))")
L("        return conflicts")
L("")
L("")
L("class SelfChecker:")
L("    def __init__(self):")
L("        self._snapshots: List[Dict] = []")
L("")
L("    def run_all(self, material, all_materials, merged_notes, merged_buckets, cur=None):")
L("        return [")
L("            self._chk_dup(material, all_materials),")
L("            self._chk_mask(merged_buckets),")
L("            self._chk_sup(material, all_materials, merged_notes, merged_buckets),")
L("            self._chk_export(cur)")
L("        ]")
L("")
L("    def _chk_dup(self, material, all_materials):")
L("        same = [m for m in all_materials if m.material_id == material.material_id]")
L("        n = len(same)")
L("        if n > 1 and material.material_type != MaterialType.SUPPLEMENT:")
L("            return SelfCheckResult(\"重复导入检查\", False, \"dup count=\" + str(n), {\"count\": n})")
L("        return SelfCheckResult(\"重复导入检查\", True, \"batches=\" + str(n) + \" type=\" + material.material_type.value, {\"count\": n})")
L("")
L("    def _chk_mask(self, buckets):")
L("    bad = []")
L("    for b in buckets:")
L("        if b.minority_sample_count > 0 and b.sample_count > 0:")
L("            r = b.minority_sample_count / b.sample_count")
L("            gap = b.overall_metric - b.minority_metric")
L("            if r < 0.1 and gap > 0.2:")
L("                bad.append({\"m\": b.model_name, \"r\": r, \"gap\": gap})")
L("    if bad:")
L("        return SelfCheckResult(\"少数类样本被总指标盖住检查\", False, \"count=\" + str(len(bad)), {\"bad\": bad})")
L("    return SelfCheckResult(\"少数类样本被总指标盖住检查\", True, \"ok\", {\"n\": len(buckets)})")
L("")
L("    def _chk_sup(self, material, all_materials, mn, mb):")
L("    if material.material_type == MaterialType.SUPPLEMENT:")
L("        prev = [m for m in all_materials if m.model_name == material.model_name")
L("                and m.material_id == material.material_id and m is not material]")
L("        if not prev:")
L("            return SelfCheckResult(\"补录后重算检查\", False, \"no prev\", {})")
L("        if not mn and not mb:")
L("            return SelfCheckResult(\"补录后重算检查\", False, \"no data\", {})")
L("        return SelfCheckResult(\"补录后重算检查\", True,")
L("                              \"merged notes=\" + str(len(mn)) + \" buckets=\" + str(len(mb)), {})")
L("    return SelfCheckResult(\"补录后重算检查\", True, \"skip\", {})")
L("")
L("    def _chk_export(self, cur=None):")
L("    n = len(self._snapshots)")
L("    if n == 0:")
L("        return SelfCheckResult(\"导出一致性检查\", False, \"no export yet\", {\"n\": 0})")
L("    if n == 1:")
L("        s = self._snapshots[0]")
L("        issues = []")
L("        if not s.get(\"trace_id\"): issues.append(\"empty trace_id\")")
L("        if s.get(\"threshold\") is None: issues.append(\"no threshold\")")
L("        if cur:")
L("            if abs(s.get(\"threshold\", -1) - cur.final_threshold) > 1e-6:")
L("                issues.append(\"threshold mismatch\")")
L("            if s.get(\"batch\") != cur.current_batch:")
L("                issues.append(\"batch mismatch\")")
L("        if issues:")
L("            return SelfCheckResult(\"导出一致性检查\", False, \";\".join(issues), {\"n\": 1})")
L("        return SelfCheckResult(\"导出一致性检查\", True, \"verified trace/batch/threshold\", {\"n\": 1, \"tid\": s.get(\"trace_id\")})")
L("    issues = []")
L("    first = self._snapshots[0]")
L("    for i, s in enumerate(self._snapshots):")
L("        if not s.get(\"trace_id\"): issues.append(\"#\" + str(i + 1) + \" empty trace\")")
L("        if s.get(\"threshold\") is None: issues.append(\"#\" + str(i + 1) + \" no threshold\")")
L("        if i > 0:")
L("            if s.get(\"model_name\") != first.get(\"model_name\"): issues.append(\"model diff\")")
L("            if abs(s.get(\"threshold\", -1) - first.get(\"threshold\", -999)) > 1e-6: issues.append(\"t diff\")")
L("    if cur and abs(self._snapshots[-1].get(\"threshold\", -1) - cur.final_threshold) > 1e-6:")
L("        issues.append(\"latest vs cur mismatch\")")
L("    if issues:")
L("        return SelfCheckResult(\"导出一致性检查\", False, \";\".join(issues), {\"n\": n})")
L("    return SelfCheckResult(\"导出一致性检查\", True, \"all \" + str(n) + \" exports consistent\", {\"n\": n})")
L("")
L("    def record_export(self, snap): self._snapshots.append(snap)")
L("    def get_export_count(self): return len(self._snapshots)")
L("")
L("")
L("class EnsembleVoteExplainer:")
L("    def __init__(self):")
L("        self.playback_validator = ThresholdPlaybackValidator()")
L("        self.conflict_detector = ConflictDetector()")
L("        self.self_checker = SelfChecker()")
L("        self._res: Dict[str, VotingResult] = {}")
L("        self._all: List[Material] = []")
L("        self._bc: Dict[str, int] = defaultdict(int)")
L("")
L("    def _merge(self, mat):")
L("        same = [m for m in self._all if m.material_id == mat.material_id] + [mat]")
L("        n_map, b_map = {}, {}")
L("        for m in same:")
L("            for n in m.threshold_notes: n_map[n.note_id] = n")
L("            for b in m.experiment_buckets: b_map[b.bucket_id] = b")
L("        return list(n_map.values()), list(b_map.values())")
L("")
L("    def _mkrec(self, mn, ot, nt, om, nm, src, reason, op, batch, affect):")
L("        return ThresholdChangeRecord(")
L("            change_id=str(uuid.uuid4())[:8], model_name=mn, old_threshold=ot,")
L("            new_threshold=nt, old_minority_threshold=om, new_minority_threshold=nm,")
L("            change_source=src, change_reason=reason, operator=op, batch_number=batch, affected_items=affect)")
L("")
L("    def process_material(self, mat):")
L("        self._all.append(mat)")
L("        self._bc[mat.material_id] += 1")
L("        bn = self._bc[mat.material_id]")
L("        mn_notes, mn_buckets = self._merge(mat)")
L("        batch = MaterialBatch(material_id=mat.material_id, batch_number=bn,")
L("                              material_type=mat.material_type, imported_at=mat.imported_at,")
L("                              threshold_notes=list(mat.threshold_notes),")
L("                              experiment_buckets=list(mat.experiment_buckets))")
L("        exist = self._res.get(mat.model_name)")
L("        ot = exist.final_threshold if exist else None")
L("        omt = exist.final_minority_threshold if exist else None")
L("        conflicts = self.conflict_detector.detect_conflicts(mn_notes, mn_buckets)")
L("        masked = any(b.minority_sample_count > 0 and b.sample_count > 0")
L("                     and (b.minority_sample_count / b.sample_count) < 0.1")
L("                     and (b.overall_metric - b.minority_metric) > 0.2 for b in mn_buckets)")
L("        at = sum(([n.threshold for n in mn_notes] + [b.threshold for b in mn_buckets]) or [0]) / max(1, len(mn_notes) + len(mn_buckets))")
L("        amts = [n.minority_threshold for n in mn_notes if n.minority_threshold is not None] + \\\n               [b.minority_threshold for b in mn_buckets if b.minority_threshold is not None]")
L("        amt = (sum(amts) / len(amts)) if amts else None")
L("        sc = 0.8 - 0.1 * len(conflicts)")
L("        tot = sum(b.sample_count for b in mn_buckets)")
L("        sc -= 0.2 if tot < 100 else (0.1 if tot < 1000 else 0.0)")
L("        sc = max(0.0, min(1.0, sc))")
L("        rs = ReviewStatus.NEED_ALGORITHM_REVIEW if masked else (ReviewStatus.PENDING if conflicts else ReviewStatus.PENDING)")
L("        if exist:")
L("            r = exist")
L("            r.final_threshold = at; r.final_minority_threshold = amt; r.confidence = sc")
L("            r.is_minority_masked = masked; r.review_status = rs")
L("            r.conflict_evidences = conflicts; r.material_batches.append(batch); r.current_batch = bn")
L("        else:")
L("            r = VotingResult(model_name=mat.model_name, final_threshold=at,")
L("                             final_minority_threshold=amt, confidence=sc,")
L("                             is_minority_masked=masked, review_status=rs,")
L("                             conflict_evidences=conflicts, self_check_results=[],")
L("                             workflow_step=WorkflowStep.STEP1_THRESHOLD_IMPORT,")
L("                             material_batches=[batch], change_history=[], current_batch=bn)")
L("            self._res[mat.model_name] = r")
L("        r.self_check_results = self.self_checker.run_all(mat, self._all, mn_notes, mn_buckets, r)")
L("        rec = self._mkrec(mat.model_name, ot, at, omt, amt,")
L("                          \"import-\" + mat.material_type.value,")
L("                          \"batch#\" + str(bn) + \" recalc\", \"importer\", bn,")
L("                          [\"notes=\" + str(len(mn_notes)), \"buckets=\" + str(len(mn_buckets))])")
L("        r.change_history.append(rec)")
L("        self.playback_validator.record_change(rec)")
L("        return r")
L("")
L("    def tang_review_buckets(self, mn, confirm=None, reject=None):")
L("        r = self._res.get(mn)")
L("        if not r: raise FriendlyError(\"no result\", \"import first\")")
L("        if r.workflow_step != WorkflowStep.STEP1_THRESHOLD_IMPORT:")
L("            raise WorkflowStepError(r.workflow_step.value, WorkflowStep.STEP2_TANG_REVIEW.value)")
L("        ot, omt = r.final_threshold, r.final_minority_threshold")
L("        confirm, reject = confirm or [], reject or []")
L("        remain, affect = [], []")
L("        for c in r.conflict_evidences:")
L("            if c.threshold_note_id in reject:")
L("                r.final_threshold = c.experiment_bucket_value")
L("                affect.append(\"reject \" + c.threshold_note_id + \" use bucket=\" + str(c.experiment_bucket_value))")
L("            elif c.threshold_note_id in confirm:")
L("                affect.append(\"confirm \" + c.threshold_note_id)")
L("            else: remain.append(c)")
L("        r.conflict_evidences = remain")
L("        if not remain and not r.is_minority_masked:")
L("            r.workflow_step = WorkflowStep.STEP2_TANG_REVIEW; r.review_status = ReviewStatus.CONFIRMED")
L("        elif r.is_minority_masked:")
L("            r.review_status = ReviewStatus.NEED_ALGORITHM_REVIEW; r.workflow_step = WorkflowStep.STEP2_TANG_REVIEW")
L("        else: r.review_status = ReviewStatus.PENDING")
L("        rec = self._mkrec(mn, ot, r.final_threshold, omt, r.final_minority_threshold,")
L("                          \"tang-review\", \"confirm=\" + str(len(confirm)) + \" reject=\" + str(len(reject)),")
L("                          \"推荐策略老唐\", r.current_batch, affect or [\"no change\"])")
L("        r.change_history.append(rec); self.playback_validator.record_change(rec)")
L("        ec = self.self_checker._chk_export(r)")
L("        for i, x in enumerate(r.self_check_results):")
L("            if x.check_name == \"导出一致性检查\": r.self_check_results[i] = ec")
L("        return r")
L("")
L("    def update_threshold_playback(self, mn, nt, nmt=None, reason=\"\"):")
L("        r = self._res.get(mn)")
L("        if not r: raise FriendlyError(\"no result\", \"do step1+2 first\")")
L("        if r.workflow_step != WorkflowStep.STEP2_TANG_REVIEW:")
L("            raise WorkflowStepError(r.workflow_step.value, WorkflowStep.STEP3_THRESHOLD_UPDATE.value)")
L("        ot, omt = r.final_threshold, r.final_minority_threshold")
L("        self.playback_validator.validate_playback(mn, ot, omt)")
L("        r.final_threshold = nt; r.final_minority_threshold = nmt")
L("        r.workflow_step = WorkflowStep.COMPLETED; r.export_trace_id = str(uuid.uuid4())[:12]")
L("        rec = self._mkrec(mn, ot, nt, omt, nmt, \"playback-update\",")
L("                          reason or \"final calibration\", \"system\", r.current_batch,")
L("                          [\"threshold final\", \"trace=\" + r.export_trace_id])")
L("        r.change_history.append(rec); self.playback_validator.record_change(rec)")
L("        self.self_checker.record_export({\"model_name\": mn, \"threshold\": nt,")
L("                                         \"minority_threshold\": nmt, \"trace_id\": r.export_trace_id,")
L("                                         \"batch\": r.current_batch})")
L("        ec = self.self_checker._chk_export(r)")
L("        for i, x in enumerate(r.self_check_results):")
L("            if x.check_name == \"导出一致性检查\": r.self_check_results[i] = ec")
L("        return r")
L("")
L("    def refresh_checks(self, mn):")
L("        r = self._res.get(mn)")
L("        if not r: raise FriendlyError(\"no result\", \"import first\")")
L("        ec = self.self_checker._chk_export(r)")
L("        for i, x in enumerate(r.self_check_results):")
L("            if x.check_name == \"导出一致性检查\": r.self_check_results[i] = ec")
L("        return r")
L("")
L("    def get_voting_result(self, mn): return self._res.get(mn)")
L("")
L("    def export_report(self, mn):")
L("        r = self._res.get(mn)")
L("        if not r: raise FriendlyError(\"no result\", \"import first\")")
L("        if not r.export_trace_id:")
L("            r.export_trace_id = str(uuid.uuid4())[:12]")
L("            self.self_checker.record_export({\"model_name\": mn, \"threshold\": r.final_threshold,")
L("                                             \"minority_threshold\": r.final_minority_threshold,")
L("                                             \"trace_id\": r.export_trace_id, \"batch\": r.current_batch})")
L("        ec = self.self_checker._chk_export(r)")
L("        for i, x in enumerate(r.self_check_results):")
L("            if x.check_name == \"导出一致性检查\": r.self_check_results[i] = ec")
L("        return {")
L("            \"model\": r.model_name, \"threshold\": r.final_threshold,")
L("            \"minority_threshold\": r.final_minority_threshold, \"confidence\": r.confidence,")
L("            \"review\": r.review_status.value, \"workflow\": r.workflow_step.value,")
L("            \"masked\": r.is_minority_masked, \"batch\": r.current_batch,")
L("            \"trace_id\": r.export_trace_id,")
L("            \"lookup\": {\"trace_id\": r.export_trace_id,")
L("                        \"change_ids\": [c.change_id for c in r.change_history],")
L("                        \"batches\": [b.batch_number for b in r.material_batches],")
L("                        \"material_ids\": list({b.material_id for b in r.material_batches})},")
L("            \"batches\": [{\"mid\": b.material_id, \"bn\": b.batch_number,")
L("                         \"type\": b.material_type.value, \"note_ids\": [n.note_id for n in b.threshold_notes],")
L("                         \"bucket_ids\": [eb.bucket_id for eb in b.experiment_buckets]} for b in r.material_batches],")
L("            \"changes\": self.playback_validator.get_detailed_history(mn),")
L("            \"conflicts\": [{\"note_id\": c.threshold_note_id, \"bucket_id\": c.experiment_bucket_id,")
L("                           \"note_t\": c.threshold_note_value, \"bucket_t\": c.experiment_bucket_value,")
L("                           \"desc\": c.description} for c in r.conflict_evidences],")
L("            \"checks\": [{\"name\": x.check_name, \"ok\": x.passed, \"msg\": x.message} for x in r.self_check_results]")
L("        }")

with open(TARGET, 'w', encoding='utf-8') as f:
    f.write("\n".join(lines))
print("WROTE", TARGET, "LINES=", len(lines))
