const HAZARD_STATUS = {
  DISCOVERED: 'discovered',
  RECTIFYING: 'rectifying',
  PENDING_REVIEW: 'pending_review',
  REOPENED: 'reopened',
  CLOSED: 'closed'
};

const HAZARD_LEVEL = {
  MINOR: 'minor',
  GENERAL: 'general',
  MAJOR: 'major',
  CRITICAL: 'critical'
};

const REVIEW_RESULT = {
  PASSED: 'passed',
  FAILED: 'failed'
};

const STATUS_LABELS = {
  [HAZARD_STATUS.DISCOVERED]: '已发现',
  [HAZARD_STATUS.RECTIFYING]: '整改中',
  [HAZARD_STATUS.PENDING_REVIEW]: '待复查',
  [HAZARD_STATUS.REOPENED]: '需重新整改',
  [HAZARD_STATUS.CLOSED]: '已闭环'
};

const LEVEL_LABELS = {
  [HAZARD_LEVEL.MINOR]: '轻微',
  [HAZARD_LEVEL.GENERAL]: '一般',
  [HAZARD_LEVEL.MAJOR]: '重大',
  [HAZARD_LEVEL.CRITICAL]: '特大'
};

const REVIEW_RESULT_LABELS = {
  [REVIEW_RESULT.PASSED]: '复查通过',
  [REVIEW_RESULT.FAILED]: '复查不通过'
};

const RECTIFY_DEADLINE_DAYS = {
  [HAZARD_LEVEL.MINOR]: 1,
  [HAZARD_LEVEL.GENERAL]: 3,
  [HAZARD_LEVEL.MAJOR]: 5,
  [HAZARD_LEVEL.CRITICAL]: 10
};

const FINE_AMOUNTS = {
  [HAZARD_LEVEL.MINOR]: 200,
  [HAZARD_LEVEL.GENERAL]: 500,
  [HAZARD_LEVEL.MAJOR]: 2000,
  [HAZARD_LEVEL.CRITICAL]: 10000
};

const RECTIFY_DEADLINE_DAYS_REOPENED = {
  [HAZARD_LEVEL.MINOR]: 0.5,
  [HAZARD_LEVEL.GENERAL]: 1,
  [HAZARD_LEVEL.MAJOR]: 2,
  [HAZARD_LEVEL.CRITICAL]: 5
};

module.exports = {
  HAZARD_STATUS,
  HAZARD_LEVEL,
  REVIEW_RESULT,
  STATUS_LABELS,
  LEVEL_LABELS,
  REVIEW_RESULT_LABELS,
  RECTIFY_DEADLINE_DAYS,
  FINE_AMOUNTS,
  RECTIFY_DEADLINE_DAYS_REOPENED
};
