sample_routes = [
    {
        "name": "初学者入门线路 - 暖阳",
        "wall_section": "A区-左侧",
        "angle": 10,
        "holds": [
            {
                "id": "h1",
                "type": "jug",
                "position": {"x": 30, "y": 10},
                "size": 1.8,
                "difficulty_contribution": 0.8,
                "is_start": True,
                "is_end": False,
            },
            {
                "id": "h2",
                "type": "jug",
                "position": {"x": 50, "y": 25},
                "size": 1.6,
                "difficulty_contribution": 0.9,
                "is_start": False,
                "is_end": False,
            },
            {
                "id": "h3",
                "type": "pocket",
                "position": {"x": 40, "y": 40},
                "size": 1.2,
                "difficulty_contribution": 1.0,
                "is_start": False,
                "is_end": False,
            },
            {
                "id": "h4",
                "type": "jug",
                "position": {"x": 60, "y": 55},
                "size": 1.5,
                "difficulty_contribution": 0.9,
                "is_start": False,
                "is_end": False,
            },
            {
                "id": "h5",
                "type": "jug",
                "position": {"x": 45, "y": 75},
                "size": 1.7,
                "difficulty_contribution": 0.8,
                "is_start": False,
                "is_end": True,
            },
            {
                "id": "f1",
                "type": "foothold",
                "position": {"x": 25, "y": 5},
                "size": 0.8,
                "difficulty_contribution": 0.5,
                "is_start": False,
                "is_end": False,
            },
        ],
        "notes": "新换线后第一个简单线路，适合新手热身",
    },
    {
        "name": "进阶挑战 - 悬崖舞者",
        "wall_section": "B区-仰角",
        "angle": 35,
        "holds": [
            {
                "id": "h1",
                "type": "jug",
                "position": {"x": 35, "y": 8},
                "size": 1.4,
                "difficulty_contribution": 1.0,
                "is_start": True,
                "is_end": False,
            },
            {
                "id": "h2",
                "type": "crimp",
                "position": {"x": 55, "y": 22},
                "size": 0.6,
                "difficulty_contribution": 1.3,
                "is_start": False,
                "is_end": False,
            },
            {
                "id": "h3",
                "type": "sloper",
                "position": {"x": 45, "y": 38},
                "size": 1.0,
                "difficulty_contribution": 1.2,
                "is_start": False,
                "is_end": False,
            },
            {
                "id": "h4",
                "type": "pinch",
                "position": {"x": 65, "y": 52},
                "size": 0.8,
                "difficulty_contribution": 1.4,
                "is_start": False,
                "is_end": False,
            },
            {
                "id": "h5",
                "type": "crimp",
                "position": {"x": 50, "y": 68},
                "size": 0.5,
                "difficulty_contribution": 1.5,
                "is_start": False,
                "is_end": False,
            },
            {
                "id": "h6",
                "type": "jug",
                "position": {"x": 60, "y": 85},
                "size": 1.2,
                "difficulty_contribution": 1.1,
                "is_start": False,
                "is_end": True,
            },
            {
                "id": "f1",
                "type": "foothold",
                "position": {"x": 30, "y": 3},
                "size": 0.7,
                "difficulty_contribution": 0.6,
                "is_start": False,
                "is_end": False,
            },
            {
                "id": "f2",
                "type": "foothold",
                "position": {"x": 40, "y": 30},
                "size": 0.6,
                "difficulty_contribution": 0.7,
                "is_start": False,
                "is_end": False,
            },
        ],
        "notes": "仰角35度，有几个难点抓点，需要核心力量",
    },
]

sample_dirty_routes = [
    {
        "name": "",
        "wall_section": "C区",
        "angle": 75,
        "holds": [
            {
                "id": "",
                "type": "jug",
                "position": {"x": -10, "y": 150},
                "size": 3.0,
                "difficulty_contribution": 3.0,
                "is_start": False,
                "is_end": False,
            }
        ],
        "notes": "这是一个有问题的线路，用于测试脏数据处理",
    },
]

sample_feedbacks = [
    {
        "route_index": 0,
        "climber_name": "小明",
        "climber_experience_level": "beginner",
        "completed": True,
        "perceived_difficulty": "V1",
        "number_of_attempts": 1,
        "time_taken": 45.0,
        "comments": "比较简单，第一次就完成了",
    },
    {
        "route_index": 0,
        "climber_name": "小红",
        "climber_experience_level": "intermediate",
        "completed": True,
        "perceived_difficulty": "V0",
        "number_of_attempts": 1,
        "time_taken": 30.0,
        "comments": "确实很简单，热身刚刚好",
    },
    {
        "route_index": 1,
        "climber_name": "阿强",
        "climber_experience_level": "advanced",
        "completed": True,
        "perceived_difficulty": "V6",
        "number_of_attempts": 3,
        "time_taken": 90.0,
        "comments": "仰角部分很有挑战性，sloper抓点需要技巧",
    },
    {
        "route_index": 1,
        "climber_name": "小李",
        "climber_experience_level": "expert",
        "completed": True,
        "perceived_difficulty": "V5",
        "number_of_attempts": 1,
        "time_taken": 60.0,
        "comments": "线路流畅，难度标注合理",
    },
]

sample_dirty_feedbacks = [
    {
        "route_index": 0,
        "climber_name": "",
        "climber_experience_level": "superman",
        "completed": True,
        "perceived_difficulty": "V99",
        "number_of_attempts": 0,
    },
]


def get_expectations():
    return {
        "route_0_expectation": {
            "name": "暖阳",
            "expected_base_difficulty": "V0-V1",
            "reason": "多为jug抓点，角度平缓(10度)",
            "angle_multiplier": 1.0,
            "expected_after_feedback": "V0-V1",
        },
        "route_1_expectation": {
            "name": "悬崖舞者",
            "expected_base_difficulty": "V4-V6",
            "reason": "有crimp、sloper、pinch等难点抓点，仰角35度",
            "angle_multiplier": 1.45,
            "expected_after_feedback": "V5-V6",
        },
        "validation_rules": {
            "线路名称不能为空",
            "墙壁角度必须在 -30 到 60 度之间",
            "线路必须至少有一个起点抓点",
            "线路必须至少有一个终点抓点",
            "线路必须至少有 3 个手抓点",
            "抓点大小必须在 0-2 之间",
            "抓点难度贡献必须在 0.5-2.0 之间",
            "抓点坐标必须在 0-100 之间",
        },
        "difficulty_scaling": {
            "jug": "最容易，基础难度 0.2",
            "pocket": "中等，基础难度 0.5",
            "pinch": "中等偏难，基础难度 0.6",
            "crimp": "难，基础难度 0.8",
            "sloper": "最难，基础难度 0.9",
        },
        "feedback_weighting": {
            "beginner": 0.7,
            "intermediate": 1.0,
            "advanced": 1.3,
            "expert": 1.5,
        },
    }
