const fs = require('fs');

const lines = [];

lines.push("const express = require('express');");
lines.push("const bodyParser = require('body-parser');");
lines.push("const CryptoJS = require('crypto-js');");
lines.push("const app = express();");
lines.push("const PORT = process.env.PORT || 3000;");
lines.push("app.use(bodyParser.json({ limit: '10mb' }));");
lines.push("app.use(bodyParser.urlencoded({ extended: true }));");
lines.push("const data = { batches: [], materials: [], elderly: [], nurses: [], schedules: [], auditLogs: [], processTraces: [] };");
lines.push("const counters = { batch:1, material:1, elderly:1, nurse:1, schedule:1, audit:1, trace:1 };");
lines.push("function generateHash(d) { const str = typeof d === 'string' ? d : JSON.stringify(d); return CryptoJS.SHA256(str).toString(CryptoJS.enc.Hex); }");
lines.push("function generateBatchNo() { const d = new Date(); return 'BATCH-' + d.getFullYear() + String(d.getMonth()+1).padStart(2,'0') + String(d.getDate()).padStart(2,'0') + '-' + Date.now().toString(36).toUpperCase(); }");
lines.push("function now() { return new Date().toISOString(); }");
lines.push("app.post('/api/batches', (req, res) => {");
lines.push("  const { title, material_data, created_by } = req.body;");
lines.push("  if (!title || !material_data || !created_by) return res.status(400).json({ error: 'Missing fields' });");
lines.push("  const h = generateHash(material_data);");
lines.push("  const ex = data.batches.find(b => b.material_hash === h);");
lines.push("  if (ex) return res.json({ isDuplicate: true, batch: ex, message: 'Duplicate material' });");
lines.push("  const b = { id: counters.batch++, batch_no: generateBatchNo(), material_hash: h, title, status: 'pending', created_by, created_at: now(), updated_at: now() };");
lines.push("  data.batches.push(b);");
lines.push("  res.json({ isDuplicate: false, batch: b, message: 'Created' });");
lines.push("});");
lines.push("app.get('/api/batches', (req, res) => res.json(data.batches.sort((a,b) => new Date(b.created_at)-new Date(a.created_at))));");
lines.push("app.get('/api/batches/:id', (req, res) => { const b = data.batches.find(x => x.id == req.params.id); b ? res.json(b) : res.status(404).json({error:'Not found'}); });");
lines.push("app.get('/api/batches/:id/statistics', (req, res) => {");
lines.push("  const id = parseInt(req.params.id);");
lines.push("  const s = data.schedules.filter(x => x.batch_id === id);");
lines.push("  res.json({ totalSchedules: s.length, totalElderly: data.elderly.filter(x => x.batch_id === id).length, totalNurses: data.nurses.filter(x => x.batch_id === id).length, statusBreakdown: { scheduled: s.filter(x => x.status==='scheduled').length, cancelled: s.filter(x => x.status==='cancelled').length, completed: s.filter(x => x.status==='completed').length }});");
lines.push("});");
lines.push("app.post('/api/materials', (req, res) => {");
lines.push("  const { batch_id, source_type, raw_data, file_name, uploaded_by } = req.body;");
lines.push("  if (!batch_id || !source_type || !raw_data || !uploaded_by) return res.status(400).json({error:'Missing fields'});");
lines.push("  const h = generateHash(raw_data);");
lines.push("  const ex = data.materials.find(m => m.content_hash === h);");
lines.push("  if (ex) return res.json({isDuplicate:true, material:ex, message:'Duplicate'});");
lines.push("  const m = { id: counters.material++, batch_id: parseInt(batch_id), source_type, content_hash: h, raw_data: JSON.stringify(raw_data), file_name, uploaded_by, created_at: now() };");
lines.push("  data.materials.push(m);");
lines.push("  const d = typeof raw_data === 'string' ? JSON.parse(raw_data) : raw_data;");
lines.push("  if (d.elderly) for (const e of d.elderly) data.elderly.push({id: counters.elderly++, batch_id: parseInt(batch_id), name:e.name, phone:e.phone||'', address:e.address||'', care_level:e.care_level||'', care_items:e.care_items||[], created_at: now()});");
lines.push("  if (d.nurses) for (const n of d.nurses) data.nurses.push({id: counters.nurse++, batch_id: parseInt(batch_id), name:n.name, phone:n.phone||'', skills:n.skills||[], status:'active', created_at: now()});");
lines.push("  res.json({isDuplicate:false, material:m, message:'Registered'});");
lines.push("});");
lines.push("app.post('/api/schedules/recalculate/:batchId', (req, res) => {");
lines.push("  const id = parseInt(req.params.batchId);");
lines.push("  data.schedules = data.schedules.filter(s => s.batch_id !== id || s.status !== 'scheduled');");
lines.push("  const elder = data.elderly.filter(e => e.batch_id === id);");
lines.push("  const nurses = data.nurses.filter(n => n.batch_id === id);");
lines.push("  if (!elder.length || !nurses.length) return res.json({scheduled:0, message:'No data'});");
lines.push("  const slots = ['08:00-10:00','10:00-12:00','14:00-16:00','16:00-18:00'];");
lines.push("  let cnt = 0;");
lines.push("  for (let day=0; day<7; day++) {");
lines.push("    const dt = new Date(); dt.setDate(dt.getDate()+day);");
lines.push("    const ds = dt.toISOString().split('T')[0];");
lines.push("    let ni = 0;");
lines.push("    for (let i=0; i<elder.length; i++) {");
lines.push("      const nurse = nurses[ni % nurses.length]; ni++;");
lines.push("      const s = { id: counters.schedule++, batch_id: id, elderly_id: elder[i].id, nurse_id: nurse.id, schedule_date: ds, time_slot: slots[i%slots.length], care_items: elder[i].care_items||[], status:'scheduled', cancel_reason: null, cancel_type: null, last_handler: null, handled_at: null, created_at: now(), updated_at: now() };");
lines.push("      data.schedules.push(s);");
lines.push("      data.processTraces.push({id: counters.trace++, schedule_id: s.id, action:'schedule_created', operator:'system', detail:'Auto-scheduled', created_at: now()});");
lines.push("      cnt++;");
lines.push("    }");
lines.push("  }");
lines.push("  const b = data.batches.find(x => x.id === id);");
lines.push("  if (b) { b.status = 'completed'; b.updated_at = now(); }");
lines.push("  res.json({scheduled: cnt, message:'Done'});");
lines.push("});");
lines.push("app.get('/api/schedules/batch/:batchId', (req, res) => {");
lines.push("  const id = parseInt(req.params.batchId);");
lines.push("  res.json(data.schedules.filter(s => s.batch_id===id).map(s => ({...s, elderly_name: data.elderly.find(e=>e.id===s.elderly_id)?.name||'', nurse_name: data.nurses.find(n=>n.id===s.nurse_id)?.name||''})).sort((a,b) => a.schedule_date.localeCompare(b.schedule_date) || a.time_slot.localeCompare(b.time_slot)));");
lines.push("});");
lines.push("app.get('/api/schedules/:id', (req, res) => {");
lines.push("  const s = data.schedules.find(x => x.id == req.params.id);");
lines.push("  if (!s) return res.status(404).json({error:'Not found'});");
lines.push("  const e = data.elderly.find(x => x.id === s.elderly_id);");
lines.push("  const n = data.nurses.find(x => x.id === s.nurse_id);");
lines.push("  res.json({...s, elderly_name:e?.name||'', elderly_phone:e?.phone||'', elderly_address:e?.address||'', nurse_name:n?.name||'', nurse_phone:n?.phone||''});");
lines.push("});");
lines.push("app.get('/api/schedules/:id/traces', (req, res) => {");
lines.push("  res.json(data.processTraces.filter(t => t.schedule_id == req.params.id).sort((a,b) => new Date(a.created_at)-new Date(b.created_at)));");
lines.push("});");
lines.push("app.get('/api/schedules/:id/audit', (req, res) => {");
lines.push("  res.json(data.auditLogs.filter(l => l.schedule_id == req.params.id).sort((a,b) => new Date(a.created_at)-new Date(b.created_at)));");
lines.push("});");
lines.push("app.put('/api/schedules/:id', (req, res) => {");
lines.push("  const { updates, operator, reason } = req.body;");
lines.push("  if (!updates || !operator || !reason) return res.status(400).json({error:'Missing fields'});");
lines.push("  const s = data.schedules.find(x => x.id == req.params.id);");
lines.push("  if (!s) return res.status(404).json({error:'Not found'});");
lines.push("  for (const [k,v] of Object.entries(updates)) {");
lines.push("    if (s[k]!==undefined && String(s[k]||'')!==String(v||'')) {");
lines.push("      data.auditLogs.push({id: counters.audit++, schedule_id: s.id, field_name: k, old_value: String(s[k]||''), new_value: String(v||''), change_reason: reason, changed_by: operator, created_at: now()});");
lines.push("    }");
lines.push("  }");
lines.push("  Object.assign(s, updates); s.last_handler = operator; s.handled_at = now(); s.updated_at = now();");
lines.push("  data.processTraces.push({id: counters.trace++, schedule_id: s.id, action:'updated', operator, detail: reason, created_at: now()});");
lines.push("  const e = data.elderly.find(x => x.id === s.elderly_id);");
lines.push("  const n = data.nurses.find(x => x.id === s.nurse_id);");
lines.push("  res.json({...s, elderly_name:e?.name||'', nurse_name:n?.name||''});");
lines.push("});");
lines.push("app.post('/api/schedules/:id/cancel', (req, res) => {");
lines.push("  const { cancel_type, reason, operator } = req.body;");
lines.push("  if (!cancel_type || !reason || !operator) return res.status(400).json({error:'Missing fields'});");
lines.push("  req.body.updates = { status: 'cancelled', cancel_type, cancel_reason: reason };");
lines.push("  req.body.reason = reason; req.body.operator = operator;");
lines.push("  app._router.handle(req, res);");
lines.push("});");
lines.push("app.get('/api/schedules/export/:batchId', (req, res) => {");
lines.push("  const id = parseInt(req.params.batchId);");
lines.push("  res.json(data.schedules.filter(s => s.batch_id === id).map(s => {");
lines.push("    const e = data.elderly.find(x => x.id === s.elderly_id);");
lines.push("    const n = data.nurses.find(x => x.id === s.nurse_id);");
lines.push("    return { schedule_id: s.id, schedule_date: s.schedule_date, time_slot: s.time_slot, status: s.status, nurse_name: n?.name||'', nurse_phone: n?.phone||'', elderly_name: e?.name||'', elderly_phone: e?.phone||'', elderly_address: e?.address||'', care_level: e?.care_level||'', care_items: e?.care_items||[], cancel_type: s.cancel_type||'', cancel_reason: s.cancel_reason||'', last_handler: s.last_handler||'', handled_at: s.handled_at||'' };");
lines.push("  }).sort((a,b) => a.schedule_date.localeCompare(b.schedule_date) || a.time_slot.localeCompare(b.time_slot)));");
lines.push("});");
lines.push("app.get('/health', (req, res) => res.json({ status: 'ok', message: 'Home Care API running', stats: { batches: data.batches.length, schedules: data.schedules.length } }));");
lines.push("app.listen(PORT, () => { console.log('Server running on http://localhost:'+PORT); console.log('Health: GET /health'); });");
lines.push("module.exports = app;");

fs.writeFileSync('src/server.js', lines.join('\n'));
console.log('Generated ' + lines.length + ' lines');
