#!/usr/bin/env python3
import os

lines = []
a = lines.append

a('#!/usr/bin/env python3')
a('import os, sys, socket, json, csv')
a('from datetime import datetime')
a('from io import StringIO')
a('from flask import Flask, render_template_string, request, jsonify, send_file, redirect, url_for')
a('sys.path.insert(0, os.path.dirname(__file__))')
a('from drift_system import (')
a('    init_db, get_db, DataAccessor, ImportService, AdjustmentService,')
a('    SelfCheckService, ExportService, ReportService, STATUS_LABEL,')
a(')')
a('')
a('app = Flask(__name__)')
a('app.config["MAX_CONTENT_LENGTH"] = 16 * 1024 * 1024')
a('EXPORTS_DIR = os.path.join(os.path.dirname(__file__), "exports")')
a('os.makedirs(EXPORTS_DIR, exist_ok=True)')
a('')

# find_free_port
a('def find_free_port():')
a('    for p in range(5000, 5100):')
a('        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)')
a('        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)')
a('        try:')
a('            s.bind(("127.0.0.1", p))')
a('            s.close()')
a('            return p')
a('        except OSError:')
a('            s.close()')
a('            continue')
a('    return 5080')
a('')

# BASE_HTML
a('BASE_HTML = r"""<!DOCTYPE html>')
a('<html lang="zh-CN">')
a('<head>')
a('<meta charset="utf-8">')
a('<meta name="viewport" content="width=device-width, initial-scale=1">')
a('<title>门店评论情绪漂移</title>')
a('<style>')
a('*{margin:0;padding:0;box-sizing:border-box}')
a('body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#f5f7fa;color:#303133;line-height:1.6}')
a('.header{background:linear-gradient(135deg,#409eff,#337ecc);color:#fff;padding:16px 24px;display:flex;align-items:center;justify-content:space-between}')
a('.header h1{font-size:20px;font-weight:600}')
a('.header nav a{color:#fff;text-decoration:none;margin-left:20px;font-size:14px;opacity:.85}')
a('.header nav a:hover{opacity:1;text-decoration:underline}')
a('.container{max-width:1200px;margin:0 auto;padding:20px}')
a('.card{background:#fff;border-radius:8px;box-shadow:0 2px 12px rgba(0,0,0,.06);padding:20px;margin-bottom:16px}')
a('.card-title{font-size:16px;font-weight:600;margin-bottom:12px;padding-bottom:8px;border-bottom:1px solid #ebeef5}')
a('table{width:100%;border-collapse:collapse;font-size:13px}')
a('th{background:#f5f7fa;color:#909399;font-weight:600;text-align:left;padding:10px 12px;border-bottom:1px solid #ebeef5}')
a('td{padding:10px 12px;border-bottom:1px solid #ebeef5}')
a('tr:hover td{background:#f5f7fa}')
a('.tag{display:inline-block;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:500}')
a('.tag-primary{background:#ecf5ff;color:#409eff}')
a('.tag-warning{background:#fdf6ec;color:#e6a23c}')
a('.tag-danger{background:#fef0f0;color:#f56c6c}')
a('.tag-success{background:#f0f9eb;color:#67c23a}')
a('.tag-info{background:#f4f4f5;color:#909399}')
a('.btn{display:inline-block;padding:8px 16px;border-radius:4px;font-size:14px;cursor:pointer;border:1px solid #dcdfe6;background:#fff;color:#606266;text-decoration:none}')
a('.btn:hover{color:#409eff;border-color:#c6e2ff;background:#ecf5ff}')
a('.btn-primary{background:#409eff;color:#fff;border-color:#409eff}')
a('.btn-primary:hover{background:#66b1ff;border-color:#66b1ff}')
a('.btn-danger{background:#f56c6c;color:#fff;border-color:#f56c6c}')
a('.stat-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin-bottom:16px}')
a('.stat-item{background:#f5f7fa;border-radius:6px;padding:16px;text-align:center}')
a('.stat-num{font-size:28px;font-weight:700;color:#409eff}')
a('.stat-label{font-size:12px;color:#909399;margin-top:4px}')
a('.breakdown-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px;margin-bottom:16px}')
a('.breakdown-item{background:#f5f7fa;border-radius:6px;padding:14px;text-align:center}')
a('.b-label{font-size:12px;color:#909399;margin-bottom:6px}')
a('.b-num{font-size:24px;font-weight:700}')
a('.form-group{margin-bottom:14px}')
a('.form-group label{display:block;font-size:13px;color:#606266;margin-bottom:4px;font-weight:500}')
a('.form-group input,.form-group select,.form-group textarea{width:100%;padding:8px 12px;border:1px solid #dcdfe6;border-radius:4px;font-size:14px}')
a('.detail-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px}')
a('.detail-section h3{font-size:14px;color:#909399;margin-bottom:8px}')
a('.detail-section .val{font-size:14px;color:#303133}')
a('.alert{padding:12px 16px;border-radius:4px;margin-bottom:12px;font-size:13px}')
a('.alert-warning{background:#fdf6ec;color:#e6a23c;border:1px solid #faecd8}')
a('.alert-danger{background:#fef0f0;color:#f56c6c;border:1px solid #fde2e2}')
a('.alert-success{background:#f0f9eb;color:#67c23a;border:1px solid #e1f3d8}')
a('.empty{text-align:center;padding:40px;color:#909399}')
a('.overridden-badge{background:#f56c6c;color:#fff;padding:2px 6px;border-radius:3px;font-size:11px;font-weight:600}')
a('</style>')
a('</head>')
a('<body>')
a('<div class="header">')
a('<h1>门店评论情绪漂移</h1>')
a('<nav>')
a('<a href="/">报告</a> <a href="/records">明细</a> <a href="/import">导入</a> <a href="/export">导出</a> <a href="/self-check">自检</a> <a href="/batches">批次</a>')
a('</nav>')
a('</div>')
a('<div class="container">')
a('{{ PAGE_CONTENT }}')
a('</div>')
a('</body>')
a('</html>"""')
a('')

# render_page
a('def render_page(page_content, **context):')
a('    html = BASE_HTML.replace("{{ PAGE_CONTENT }}", page_content)')
a('    return render_template_string(html, **context)')
a('')

# _get_import_breakdown
a('def _get_import_breakdown(batch_id=None):')
a('    conn = get_db()')
a('    if batch_id:')
a('        batches = conn.execute("SELECT * FROM import_batches WHERE id = ? ORDER BY import_time DESC", (batch_id,)).fetchall()')
a('    else:')
a('        batches = conn.execute("SELECT * FROM import_batches ORDER BY import_time DESC LIMIT 10").fetchall()')
a('    total_new = total_history_dup = total_current_dup = total_file_dup = 0')
a('    batch_details = []')
a('    for b in batches:')
a('        bd = dict(b); bid = bd["id"]; btype = bd.get("batch_type","")')
a('        nc = hdc = cdc = fdc = 0')
a('        if btype == "annotator":')
a('            fh = bd.get("import_hash")')
a('            if fh:')
a('                hc = conn.execute("SELECT COUNT(*) as cnt FROM import_batches WHERE import_hash = ? AND id < ?", (fh, bid)).fetchone()["cnt"]')
a('                if hc > 0: fdc = bd.get("record_count", 0)')
a('            arecs = conn.execute("SELECT comment_id, original_line_no FROM annotator_comments WHERE batch_id = ?", (bid,)).fetchall()')
a('            seen = set()')
a('            for ar in arecs:')
a('                key = "{}#{}".format(ar["comment_id"], ar["original_line_no"])')
a('                if key in seen: cdc += 1')
a('                seen.add(key)')
a('                he = conn.execute("SELECT COUNT(*) as cnt FROM annotator_comments ac WHERE ac.comment_id = ? AND ac.original_line_no = ? AND ac.batch_id < ?", (ar["comment_id"], ar["original_line_no"], bid)).fetchone()["cnt"]')
a('                if he > 0: hdc += 1')
a('                else:')
a('                    de = conn.execute("SELECT COUNT(*) as cnt FROM sentiment_drift_records sdr WHERE sdr.comment_id = ? AND (SELECT MIN(batch_id) FROM annotator_comments WHERE comment_id = sdr.comment_id) = ?", (ar["comment_id"], bid)).fetchone()["cnt"]')
a('                    if de > 0: nc += 1')
a('        bdl = "标注员留言" if btype == "annotator" else "模型输出" if btype == "model" else btype')
a('        batch_details.append({**bd, "new_count": nc, "history_dup_count": hdc, "current_dup_count": cdc, "file_dup_count": fdc, "batch_type_label": bdl})')
a('        total_new += nc; total_history_dup += hdc; total_current_dup += cdc; total_file_dup += fdc')
a('    conn.close()')
a('    return {"total_new": total_new, "total_history_dup": total_history_dup, "total_current_dup": total_current_dup, "total_file_dup": total_file_dup, "batch_details": batch_details, "generated_at": datetime.now().isoformat()}')
a('')

# index route
a('@app.route("/")')
a('def index():')
a('    report = ReportService.generate_report()')
a('    s = report["summary"]')
a('    bd = _get_import_breakdown()')
a('    p = ""')
a('    p += \'<div class="card"><div class="card-title">核心指标</div><div class="stat-grid">\'')
a('    p += \'<div class="stat-item"><div class="stat-num">{}</div><div class="stat-label">总评论数</div></div>\'.format(s["total_records"])')
a('    p += \'<div class="stat-item"><div class="stat-num">{}</div><div class="stat-label">情绪漂移数({}%)</div></div>\'.format(s["drift_count"], s["drift_rate"])')
a('    p += \'<div class="stat-item"><div class="stat-num">{}</div><div class="stat-label">已人工改判</div></div>\'.format(s["manual_adjusted_count"])')
a('    p += \'<div class="stat-item"><div class="stat-num" style="color:#f56c6c">{}</div><div class="stat-label">待安全审核(被批跑覆盖)</div></div>\'.format(s["overridden_pending_count"])')
a('    p += \'<div class="stat-item"><div class="stat-num" style="color:#67c23a">{}</div><div class="stat-label">已安全复核</div></div>\'.format(s["reviewed_count"])')
a('    p += \'</div></div>\'')
a('    p += \'<div class="card"><div class="card-title">导入重复判断分类</div><div class="breakdown-grid">\'')
a('    p += \'<div class="breakdown-item"><div class="b-label">新记录(首次入库)</div><div class="b-num" style="color:#409eff">{}</div></div>\'.format(bd["total_new"])')
a('    p += \'<div class="breakdown-item"><div class="b-label">历史重复(已有批次存在)</div><div class="b-num" style="color:#e6a23c">{}</div></div>\'.format(bd["total_history_dup"])')
a('    p += \'<div class="breakdown-item"><div class="b-label">本批次重复(同文件内重复)</div><div class="b-num" style="color:#e6a23c">{}</div></div>\'.format(bd["total_current_dup"])')
a('    p += \'<div class="breakdown-item"><div class="b-label">同文件Hash重复(完全相同文件)</div><div class="b-num" style="color:#f56c6c">{}</div></div>\'.format(bd["total_file_dup"])')
a('    p += \'</div></div>\'')
a('    p += \'<div class="card"><div class="card-title">状态分布</div><table><tr><th>状态码</th><th>状态</th><th>数量</th></tr>\'')
a('    for code, info in report["status_distribution"].items():')
a('        tc = "tag-danger" if code == "adjustment_overridden" else "tag-primary"')
a('        p += \'<tr><td>{}</td><td><span class="tag {}">{}</span></td><td>{}</td></tr>\'.format(code, tc, info["label"], info["count"])')
a('    p += \'</table></div>\'')
a('    p += \'<div class="card"><div class="card-title">门店分布</div><table><tr><th>门店</th><th>评论数</th><th>漂移数</th><th>漂移率</th></tr>\'')
a('    for st in report["store_distribution"]:')
a('        p += \'<tr><td>{}</td><td>{}</td><td>{}</td><td>{}%</td></tr>\'.format(st["store_id"], st["cnt"], st["drift_cnt"] or 0, st["drift_rate"])')
a('    p += \'</table></div>\'')
a('    p += \'<div class="card"><div class="card-title">最近批次</div><table><tr><th>ID</th><th>类型</th><th>源文件</th><th>导入时间</th><th>记录数</th><th>重复数</th></tr>\'')
a('    for b in report.get("import_batches_recent", []):')
a('        p += \'<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>\'.format(b.get("id",""), b.get("batch_type",""), b.get("source_file",""), b.get("import_time",""), b.get("record_count",0), b.get("duplicate_count",0))')
a('    p += \'</table></div>\'')
a('    p += \'<p>报告生成时间：{}</p>\'.format(report["generated_at_label"])')
a('    return render_page(p, report=report, bd=bd)')
a('')

# records page
a('@app.route("/records")')
a('def records_page():')
a('    sf = request.args.get("status", "")')
a('    stf = request.args.get("store_id", "")')
a('    records = DataAccessor.list_records(status=sf if sf else None, store_id=stf if stf else None)')
a('    p = \'<div class="card"><div class="card-title">记录明细</div>\'')
a('    p += \'<form method="get" style="margin-bottom:12px;display:flex;gap:8px;align-items:end">\'')
a('    p += \'<div class="form-group" style="margin:0"><label>状态</label><select name="status"><option value="">全部</option>\'')
a('    for code, label in STATUS_LABEL.items():')
a('        sel = " selected" if code == sf else ""')
a('        p += \'<option value="{}"{}>{}</option>\'.format(code, sel, label)')
a('    p += \'</select></div>\'')
a('    p += \'<div class="form-group" style="margin:0"><label>门店</label><input name="store_id" value="{}" placeholder="门店ID"></div>\'.format(stf)')
a('    p += \'<button type="submit" class="btn btn-primary">筛选</button> <a href="/records" class="btn">重置</a></form>\'')
a('    if not records:')
a('        p += \'<div class="empty">暂无记录</div>\'')
a('    else:')
a('        p += \'<table><tr><th>评论ID</th><th>门店</th><th>标注情感</th><th>模型情感</th><th>漂移</th><th>状态</th><th>覆盖标记</th><th>行号</th><th>源文件</th><th>操作</th></tr>\'')
a('        for r in records:')
a('            dt = \'<span class="tag tag-danger">漂移</span>\' if r.get("drift_detected") else \'<span class="tag tag-success">一致</span>\'')
a('            sc = r.get("status",""); sl = r.get("status_label",sc)')
a('            tc = "tag-danger" if sc == "adjustment_overridden" else "tag-warning" if sc == "manually_adjusted" else "tag-primary" if sc == "annotator_imported" else "tag-success" if sc == "reviewed" else "tag-info"')
a('            of = r.get("adjust_overridden_flag", "")')
a('            oh = \'<span class="overridden-badge">被覆盖</span>\' if of == "是" else ""')
a('            p += \'<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td><span class="tag {}">{}</span>{}</td><td>{}</td><td>{}</td><td><a href="/record/{}" class="btn" style="padding:2px 8px;font-size:12px">详情</a></td></tr>\'.format(')
a('                r.get("comment_id",""), r.get("store_id",""), r.get("annotator_sentiment",""), r.get("model_sentiment",""),')
a('                dt, tc, sl, oh, r.get("original_line_no",""), r.get("annotator_source_file",""), r.get("comment_id",""))')
a('        p += \'</table>\'')
a('    p += \'</div>\'')
a('    p += \'<p>共 {} 条记录</p>\'.format(len(records))')
a('    return render_page(p, records=records)')
a('')

# record detail
a('@app.route("/record/<comment_id>")')
a('def record_detail(comment_id):')
a('    r = DataAccessor.get_record_by_comment_id(comment_id)')
a('    if not r:')
a('        return render_page(\'<div class="empty">未找到记录：{}</div>\'.format(comment_id)), 404')
a('    p = \'<div class="card"><div class="card-title">记录详情：{}</div><div class="detail-grid">\'.format(comment_id)')
a('    p += \'<div class="detail-section"><h3>基本信息</h3>\'')
a('    for k, v in [("评论ID","comment_id"),("门店","store_id"),("原始情感","original_sentiment"),("当前情感","current_sentiment")]:')
a('        p += \'<p class="val">{}：{}</p>\'.format(k, r.get(v,""))')
a('    p += \'<p class="val">漂移检测：{}</p>\'.format("是" if r.get("drift_detected") else "否")')
a('    p += \'<p class="val">状态：<span class="tag tag-primary">{}</span></p></div>\'.format(r.get("status_label",""))')
a('    p += \'<div class="detail-section"><h3>标注员留言(原始材料)</h3>\'')
a('    for k, v in [("原始行号","original_line_no"),("内容","annotator_content"),("标注情感","annotator_sentiment"),("批次ID","annotator_batch_id"),("源文件","annotator_source_file"),("导入时间","annotator_import_time")]:')
a('        p += \'<p class="val">{}：{}</p>\'.format(k, r.get(v,""))')
a('    p += \'</div>\'')
a('    p += \'<div class="detail-section"><h3>模型输出片段</h3>\'')
a('    for k, v in [("模型版本","model_version"),("片段文本","fragment_text"),("模型预测","model_sentiment"),("置信度","confidence"),("源文件","model_source_file"),("导入时间","model_import_time")]:')
a('        p += \'<p class="val">{}：{}</p>\'.format(k, r.get(v,""))')
a('    p += \'</div>\'')
a('    p += \'<div class="detail-section"><h3>人工改判与覆盖</h3>\'')
a('    adjs = r.get("adjustments", [])')
a('    if adjs:')
a('        for adj in adjs:')
a('            p += \'<div style="margin-bottom:8px;padding:8px;background:#f5f7fa;border-radius:4px">\'')
a('            p += \'<p class="val">{} -> {} (by {})</p>\'.format(adj.get("old_sentiment",""), adj.get("new_sentiment",""), adj.get("adjusted_by",""))')
a('            p += \'<p class="val">时间：{}</p>\'.format(adj.get("adjusted_at",""))')
a('            if adj.get("overridden"):')
a('                p += \'<p class="val"><span class="overridden-badge">被覆盖</span> by {} at {}</p>\'.format(adj.get("overridden_by",""), adj.get("overridden_at",""))')
a('            if adj.get("note"): p += \'<p class="val">备注：{}</p>\'.format(adj.get("note",""))')
a('            p += \'</div>\'')
a('    else:')
a('        p += \'<p class="val">无人工改判记录</p>\'')
a('    p += \'</div>\'')
a('    p += \'<div class="detail-section"><h3>状态变更历史</h3>\'')
a('    hist = r.get("history", [])')
a('    if hist:')
a('        for h in hist:')
a('            p += \'<p class="val">{} -> {} (by {}) {} {}</p>\'.format(h.get("old_status",""), h.get("new_status",""), h.get("changed_by",""), h.get("changed_at",""), "原因:"+h.get("reason","") if h.get("reason") else "")')
a('    else:')
a('        p += \'<p class="val">无状态变更记录</p>\'')
a('    p += \'</div></div></div>\'')
a('    p += \'<a href="/records" class="btn">返回列表</a>\'')
a('    return render_page(p, record=r)')
a('')

# import page
a('@app.route("/import", methods=["GET", "POST"])')
a('def import_page():')
a('    msg = ""; msg_type = "info"; result = None')
a('    if request.method == "POST":')
a('        try:')
a('            it = request.form.get("import_type", "annotator")')
a('            file = request.files.get("file")')
a('            if not file or not file.filename:')
a('                msg = "请选择文件"; msg_type = "danger"')
a('            else:')
a('                fn = file.filename; cb = file.read(); cs = cb.decode("utf-8-sig")')
a('                if it == "annotator":')
a('                    reader = csv.DictReader(StringIO(cs)); rows = [dict(r) for r in reader]')
a('                    result = ImportService.import_annotator_comments(rows, source_file=fn)')
a('                else:')
a('                    data = json.loads(cs)')
a('                    if isinstance(data, dict): data = data.get("records", [data])')
a('                    result = ImportService.import_model_outputs(data, source_file=fn)')
a('                if result.get("same_file_duplicate"):')
a('                    msg = "同文件Hash重复，已跳过。共{}条".format(result.get("total_count",0)); msg_type = "warning"')
a('                else:')
a('                    parts = []')
a('                    if result.get("new_count",0) > 0: parts.append("新记录{}条".format(result["new_count"]))')
a('                    if result.get("history_duplicate_count",0) > 0: parts.append("历史重复{}条".format(result["history_duplicate_count"]))')
a('                    if result.get("current_duplicate_count",0) > 0: parts.append("本批次重复{}条".format(result["current_duplicate_count"]))')
a('                    if not parts: parts.append("0条记录")')
a('                    msg = "导入完成：" + "，".join(parts); msg_type = "success"')
a('        except Exception as e:')
a('            msg = "导入失败：" + str(e); msg_type = "danger"')
a('    p = \'<div class="card"><div class="card-title">数据导入</div>\'')
a('    if msg: p += \'<div class="alert alert-{}">{}</div>\'.format(msg_type, msg)')
a('    p += \'<form method="post" enctype="multipart/form-data">\'')
a('    p += \'<div class="form-group"><label>导入类型</label><select name="import_type"><option value="annotator">标注员留言 CSV</option><option value="model">模型输出 JSON</option></select></div>\'')
a('    p += \'<div class="form-group"><label>文件</label><input type="file" name="file" accept=".csv,.json"></div>\'')
a('    p += \'<button type="submit" class="btn btn-primary">导入</button></form></div>\'')
a('    if result:')
a('        p += \'<div class="card"><div class="card-title">导入结果</div><div class="breakdown-grid">\'')
a('        p += \'<div class="breakdown-item"><div class="b-label">新记录</div><div class="b-num" style="color:#409eff">{}</div></div>\'.format(result.get("new_count",0))')
a('        p += \'<div class="breakdown-item"><div class="b-label">历史重复</div><div class="b-num" style="color:#e6a23c">{}</div></div>\'.format(result.get("history_duplicate_count",0))')
a('        p += \'<div class="breakdown-item"><div class="b-label">本批次重复</div><div class="b-num" style="color:#e6a23c">{}</div></div>\'.format(result.get("current_duplicate_count",0))')
a('        p += \'<div class="breakdown-item"><div class="b-label">同文件Hash重复</div><div class="b-num" style="color:#f56c6c">{}</div></div>\'.format(result.get("total_count",0) if result.get("same_file_duplicate") else 0)')
a('        p += \'</div>\'')
a('        bk = result.get("breakdown", {})')
a('        if bk.get("new"): p += "<p>新记录：" + ", ".join("{}(L{})".format(x["comment_id"], x["line_no"]) for x in bk["new"]) + "</p>"')
a('        if bk.get("history_duplicate"): p += "<p>历史重复：" + ", ".join("{}(L{})".format(x["comment_id"], x["line_no"]) for x in bk["history_duplicate"]) + "</p>"')
a('        if bk.get("current_duplicate"): p += "<p>本批次重复：" + ", ".join("{}(L{})".format(x["comment_id"], x["line_no"]) for x in bk["current_duplicate"]) + "</p>"')
a('        if bk.get("same_file_duplicate"): p += "<p>同文件重复：" + ", ".join(bk["same_file_duplicate"][:10]) + "</p>"')
a('        p += \'</div>\'')
a('    p += \'<div class="card"><div class="card-title">样例数据(快速导入)</div>\'')
a('    sd_dir = os.path.join(os.path.dirname(__file__), "sample_data")')
a('    if os.path.isdir(sd_dir):')
a('        p += \'<table><tr><th>文件</th><th>类型</th><th>操作</th></tr>\'')
a('        for fn in sorted(os.listdir(sd_dir)):')
a('            fp = os.path.join(sd_dir, fn)')
a('            if not os.path.isfile(fp): continue')
a('            itype = "annotator" if fn.endswith(".csv") else "model" if fn.endswith(".json") else ""')
a('            if not itype: continue')
a('            p += \'<tr><td>{}</td><td>{}</td><td><a href="/import-sample?file={}&type={}" class="btn" style="padding:2px 8px;font-size:12px">导入</a></td></tr>\'.format(fn, "标注员留言" if itype=="annotator" else "模型输出", fn, itype)')
a('        p += \'</table>\'')
a('    p += \'</div>\'')
a('    return render_page(p, result=result)')
a('')

# import sample
a('@app.route("/import-sample")')
a('def import_sample():')
a('    fn = request.args.get("file", "")')
a('    itype = request.args.get("type", "annotator")')
a('    sd_dir = os.path.join(os.path.dirname(__file__), "sample_data")')
a('    fp = os.path.join(sd_dir, fn)')
a('    if not os.path.isfile(fp) or not fn: return redirect("/import")')
a('    try:')
a('        if itype == "annotator":')
a('            with open(fp, "r", encoding="utf-8-sig") as f: rows = [dict(r) for r in csv.DictReader(f)]')
a('            ImportService.import_annotator_comments(rows, source_file=fn)')
a('        else:')
a('            with open(fp, "r", encoding="utf-8-sig") as f: data = json.load(f)')
a('            if isinstance(data, dict): data = data.get("records", [data])')
a('            ImportService.import_model_outputs(data, source_file=fn)')
a('    except Exception: pass')
a('    return redirect("/import")')
a('')

# export page
a('@app.route("/export")')
a('def export_page():')
a('    p = \'<div class="card"><div class="card-title">数据导出</div><div style="display:flex;gap:12px"><a href="/api/export/details" class="btn btn-primary">导出明细CSV</a> <a href="/api/export/overridden-trace" class="btn btn-danger">导出覆盖追溯CSV</a></div></div>\'')
a('    efs = sorted(os.listdir(EXPORTS_DIR), reverse=True) if os.path.isdir(EXPORTS_DIR) else []')
a('    if efs:')
a('        p += \'<div class="card"><div class="card-title">已导出文件</div><table><tr><th>文件名</th><th>大小</th><th>操作</th></tr>\'')
a('        for ef in efs[:20]:')
a('            efp = os.path.join(EXPORTS_DIR, ef); sz = os.path.getsize(efp)')
a('            ss = "{:.1f} KB".format(sz/1024) if sz > 1024 else "{} B".format(sz)')
a('            p += \'<tr><td>{}</td><td>{}</td><td><a href="/exports/{}" class="btn" style="padding:2px 8px;font-size:12px">下载</a> <a href="/exports/preview/{}" class="btn" style="padding:2px 8px;font-size:12px">预览</a></td></tr>\'.format(ef, ss, ef, ef)')
a('        p += \'</table></div>\'')
a('    return render_page(p)')
a('')

# download & preview
a('@app.route("/exports/<filename>")')
a('def download_export(filename):')
a('    fp = os.path.join(EXPORTS_DIR, filename)')
a('    if not os.path.isfile(fp): return "File not found", 404')
a('    return send_file(fp, as_attachment=True, download_name=filename)')
a('')
a('@app.route("/exports/preview/<filename>")')
a('def preview_export(filename):')
a('    fp = os.path.join(EXPORTS_DIR, filename)')
a('    if not os.path.isfile(fp): return "File not found", 404')
a('    with open(fp, "r", encoding="utf-8-sig") as f: ls = f.readlines()[:100]')
a('    p = \'<div class="card"><div class="card-title">预览：{}(前100行)</div>\'.format(filename)')
a('    p += "<pre>" + "".join(ls).replace("<","&lt;").replace(">","&gt;") + "</pre>"')
a('    p += \'<a href="/exports/{}" class="btn btn-primary">下载完整文件</a> <a href="/export" class="btn">返回导出页</a></div>\'.format(filename)')
a('    return render_page(p)')
a('')

# self-check page
a('@app.route("/self-check")')
a('def self_check_page():')
a('    results = SelfCheckService.run_all_checks()')
a('    p = \'<div class="card"><div class="card-title">自检结果</div>\'')
a('    for r in results:')
a('        sc = "alert-success" if r.get("status") == "pass" else "alert-danger"')
a('        p += \'<div class="alert {}"><strong>{}</strong>: {}</div>\'.format(sc, r.get("check_type",""), r.get("message",""))')
a('        if r.get("details"): p += "<pre>" + json.dumps(r["details"], ensure_ascii=False, indent=2, default=str) + "</pre>"')
a('    p += \'</div><a href="/api/self-check/run" class="btn btn-primary">重新执行自检</a>\'')
a('    return render_page(p, results=results)')
a('')

# batches page
a('@app.route("/batches")')
a('def batches_page():')
a('    batches = DataAccessor.list_batches()')
a('    p = \'<div class="card"><div class="card-title">批次列表</div>\'')
a('    if not batches:')
a('        p += \'<div class="empty">暂无批次</div>\'')
a('    else:')
a('        p += \'<table><tr><th>ID</th><th>类型</th><th>源文件</th><th>导入时间</th><th>记录数</th><th>重复数</th><th>状态</th></tr>\'')
a('        for b in batches:')
a('            p += \'<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>\'.format(b.get("id",""), b.get("batch_type",""), b.get("source_file",""), b.get("import_time",""), b.get("record_count",0), b.get("duplicate_count",0), b.get("status",""))')
a('        p += \'</table>\'')
a('    p += \'</div>\'')
a('    return render_page(p, batches=batches)')
a('')

# API routes
a('@app.route("/api/records")')
a('def api_records():')
a('    st = request.args.get("status"); sid = request.args.get("store_id")')
a('    records = DataAccessor.list_records(status=st if st else None, store_id=sid if sid else None)')
a('    return jsonify({"total": len(records), "records": [dict(r) for r in records], "ok": True})')
a('')
a('@app.route("/api/record/<comment_id>")')
a('def api_record(comment_id):')
a('    r = DataAccessor.get_record_by_comment_id(comment_id)')
a('    if not r: return jsonify({"ok": False, "error": "not found"}), 404')
a('    return jsonify({"ok": True, "record": r})')
a('')
a('@app.route("/api/report")')
a('def api_report():')
a('    return jsonify({"ok": True, "report": ReportService.generate_report()})')
a('')
a('@app.route("/api/self-check")')
a('def api_self_check():')
a('    return jsonify({"ok": True, "results": SelfCheckService.run_all_checks()})')
a('')
a('@app.route("/api/self-check/run")')
a('def api_self_check_run():')
a('    SelfCheckService.run_all_checks()')
a('    return redirect("/self-check")')
a('')

# API import routes
a('@app.route("/api/import/annotator", methods=["POST"])')
a('def api_import_annotator():')
a('    try:')
a('        file = request.files.get("file")')
a('        if not file:')
a('            data = request.get_json(force=True); rows = data if isinstance(data, list) else data.get("records", [])')
a('            result = ImportService.import_annotator_comments(rows, source_file=request.args.get("source_file"))')
a('        else:')
a('            cs = file.read().decode("utf-8-sig"); rows = [dict(r) for r in csv.DictReader(StringIO(cs))]')
a('            result = ImportService.import_annotator_comments(rows, source_file=file.filename)')
a('        return jsonify({"ok": True, "result": result})')
a('    except Exception as e:')
a('        return jsonify({"ok": False, "error": str(e)}), 500')
a('')
a('@app.route("/api/import/model", methods=["POST"])')
a('def api_import_model():')
a('    try:')
a('        file = request.files.get("file")')
a('        if not file:')
a('            data = request.get_json(force=True); rows = data if isinstance(data, list) else data.get("records", [])')
a('            result = ImportService.import_model_outputs(rows, source_file=request.args.get("source_file"))')
a('        else:')
a('            data = json.loads(file.read().decode("utf-8-sig"))')
a('            if isinstance(data, dict): data = data.get("records", [data])')
a('            result = ImportService.import_model_outputs(data, source_file=file.filename)')
a('        return jsonify({"ok": True, "result": result})')
a('    except Exception as e:')
a('        return jsonify({"ok": False, "error": str(e)}), 500')
a('')

# API adjust, batch-rerun, review
a('@app.route("/api/adjust", methods=["POST"])')
a('def api_adjust():')
a('    try:')
a('        d = request.get_json(force=True)')
a('        result = AdjustmentService.manual_adjust(record_id=d["record_id"], new_sentiment=d["new_sentiment"], adjusted_by=d.get("adjusted_by","web"), note=d.get("note"))')
a('        return jsonify({"ok": True, "result": result})')
a('    except Exception as e:')
a('        return jsonify({"ok": False, "error": str(e)}), 500')
a('')
a('@app.route("/api/batch-rerun", methods=["POST"])')
a('def api_batch_rerun():')
a('    try:')
a('        d = request.get_json(force=True)')
a('        result = AdjustmentService.batch_rerun(comment_ids=d["comment_ids"], new_sentiments=d["new_sentiments"], run_by=d.get("run_by","web"))')
a('        return jsonify({"ok": True, "result": result})')
a('    except Exception as e:')
a('        return jsonify({"ok": False, "error": str(e)}), 500')
a('')
a('@app.route("/api/review", methods=["POST"])')
a('def api_review():')
a('    try:')
a('        d = request.get_json(force=True)')
a('        result = AdjustmentService.review_overridden(record_id=d["record_id"], reviewed_by=d.get("reviewed_by","web"), final_sentiment=d["final_sentiment"], status=d.get("status","reviewed"))')
a('        return jsonify({"ok": True, "result": result})')
a('    except Exception as e:')
a('        return jsonify({"ok": False, "error": str(e)}), 500')
a('')

# API export routes
a('@app.route("/api/export/details")')
a('def api_export_details():')
a('    ts = datetime.now().strftime("%Y%m%d_%H%M%S"); fn = "情绪漂移明细_{}.csv".format(ts)')
a('    fp = os.path.join(EXPORTS_DIR, fn)')
a('    st = request.args.get("status"); sid = request.args.get("store_id")')
a('    result = ExportService.export_details(fp, status=st if st else None, store_id=sid if sid else None)')
a('    if result.get("success"): return send_file(fp, as_attachment=True, download_name=fn)')
a('    return jsonify(result), 500')
a('')
a('@app.route("/api/export/overridden-trace")')
a('def api_export_overridden_trace():')
a('    ts = datetime.now().strftime("%Y%m%d_%H%M%S"); fn = "覆盖追溯_{}.csv".format(ts)')
a('    fp = os.path.join(EXPORTS_DIR, fn)')
a('    result = ExportService.export_overridden_trace(fp)')
a('    if result.get("success"): return send_file(fp, as_attachment=True, download_name=fn)')
a('    return jsonify(result), 500')
a('')
a('@app.route("/api/import-breakdown")')
a('def api_import_breakdown():')
a('    bid = request.args.get("batch_id", type=int)')
a('    return jsonify({"ok": True, "result": _get_import_breakdown(batch_id=bid)})')
a('')
a('@app.route("/api/recompute", methods=["POST"])')
a('def api_recompute():')
a('    try:')
a('        report = ReportService.generate_report()')
a('        checks = SelfCheckService.run_all_checks()')
a('        return jsonify({"ok": True, "report": report, "self_check_count": len(checks)})')
a('    except Exception as e:')
a('        return jsonify({"ok": False, "error": str(e)}), 500')
a('')

# init_db & main
a('init_db()')
a('')
a('if __name__ == "__main__":')
a('    port = find_free_port()')
a('    print("=" * 50)')
a('    print("门店评论情绪漂移系统")')
a('    print("访问地址: http://127.0.0.1:{}".format(port))')
a('    print("=" * 50)')
a('    app.run(host="127.0.0.1", port=port, debug=False, use_reloader=False, threaded=True)')

content = "\n".join(lines) + "\n"
with open("app.py", "w", encoding="utf-8") as f:
    f.write(content)

print("app.py written: {} lines, {} bytes".format(len(lines), len(content)))

import ast
try:
    ast.parse(content)
    print("syntax OK")
except SyntaxError as e:
    print("SYNTAX ERROR:", e)
