import type { WorkOrder } from '../types';

export const mockWorkOrders: WorkOrder[] = [
  {
    id: 'wo-001',
    orderNo: 'GD20260601001',
    deviceNo: 'DT-SH-0001',
    deviceName: '上海中心大厦1号客梯',
    faultType: '门机故障',
    faultDescription: '电梯开关门异响，2楼无法正常开门',
    reportTime: '2026-06-01 08:15:00',
    reporter: '李工',
    status: 'completed',
    priority: 'high',
    manualRemark: '2楼门机皮带磨损约3mm，已更换原装皮带，试运行50次无异常。物业签字确认。',
    judgment: 'normal',
    judgmentBy: '王审核',
    judgmentAt: '2026-06-01 16:30:00',
    shift: 'morning',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-001-1',
        workOrderId: 'wo-001',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20door%20mechanism%20repair%20close%20up%20technical%20photo&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20door%20mechanism%20repair%20close%20up%20technical%20photo&image_size=square',
        description: '磨损的门机皮带特写',
        uploadTime: '2026-06-01 09:20:00',
        isLateArrival: false,
        hitsOldTerminology: false,
        exifInfo: { device: 'iPhone 14 Pro', gps: '31.2304°N,121.4737°E', originalTime: '2026-06-01 09:15:22' },
      },
      {
        id: 'p-001-2',
        workOrderId: 'wo-001',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=new%20elevator%20belt%20installed%20maintenance%20photo&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=new%20elevator%20belt%20installed%20maintenance%20photo&image_size=square',
        description: '新皮带安装完成',
        uploadTime: '2026-06-01 10:45:00',
        isLateArrival: false,
        hitsOldTerminology: false,
        exifInfo: { device: 'iPhone 14 Pro', gps: '31.2304°N,121.4737°E', originalTime: '2026-06-01 10:40:12' },
      },
      {
        id: 'p-001-3',
        workOrderId: 'wo-001',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20maintenance%20completion%20inspection%20report&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20maintenance%20completion%20inspection%20report&image_size=square',
        description: '物业签字确认单（补传）',
        uploadTime: '2026-06-02 14:22:00',
        isLateArrival: true,
        hitsOldTerminology: false,
        exifInfo: { device: 'iPhone 14 Pro', originalTime: '2026-06-02 14:20:00' },
      },
    ],
    attachments: [
      { id: 'a-001-1', filename: '门机皮带型号规格.pdf', uploadTime: '2026-06-01 11:00:00', isLateArrival: false },
      { id: 'a-001-2', filename: '物业确认函扫描件.pdf', uploadTime: '2026-06-02 15:00:00', isLateArrival: true },
    ],
    judgmentHistory: [
      { id: 'jh-001-1', workOrderId: 'wo-001', operator: '王审核', operatorRole: 'reviewer', oldJudgment: null, newJudgment: 'normal', reason: '维修流程规范，配件更换标准', changedAt: '2026-06-01 16:30:00', shift: 'afternoon' },
    ],
  },
  {
    id: 'wo-002',
    orderNo: 'GD20260601002',
    deviceNo: 'DT-SH-0002',
    deviceName: '上海中心大厦2号货梯',
    faultType: '称重异常',
    faultDescription: '3人即超载报警，称重传感器疑似偏移',
    reportTime: '2026-06-01 09:40:00',
    reporter: '张工',
    status: 'completed',
    priority: 'medium',
    manualRemark: '传感器底座松动导致偏移1.5度，重新校准后加载测试通过。使用了老标准"三点校准法"完成。',
    judgment: 'abnormal',
    judgmentBy: '阿敏',
    judgmentAt: '2026-06-01 20:10:00',
    shift: 'morning',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-002-1',
        workOrderId: 'wo-002',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20load%20cell%20sensor%20offset%20technical%20photo&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20load%20cell%20sensor%20offset%20technical%20photo&image_size=square',
        description: '传感器底座偏移照片',
        uploadTime: '2026-06-01 10:15:00',
        isLateArrival: false,
        hitsOldTerminology: true,
        exifInfo: { device: '华为 Mate 60', gps: '31.2304°N,121.4737°E' },
      },
      {
        id: 'p-002-2',
        workOrderId: 'wo-002',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=old%20three%20point%20calibration%20method%20elevator%20maintenance&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=old%20three%20point%20calibration%20method%20elevator%20maintenance&image_size=square',
        description: '按老规矩三点校准法作业中——旧说法',
        uploadTime: '2026-06-01 11:30:00',
        isLateArrival: false,
        hitsOldTerminology: true,
      },
      {
        id: 'p-002-3',
        workOrderId: 'wo-002',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20load%20test%20weights%20verification&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20load%20test%20weights%20verification&image_size=square',
        description: '加载测试现场（晚传）',
        uploadTime: '2026-06-02 08:05:00',
        isLateArrival: true,
        hitsOldTerminology: false,
      },
    ],
    attachments: [
      { id: 'a-002-1', filename: '称重校准记录表.xlsx', uploadTime: '2026-06-01 12:00:00', isLateArrival: false },
    ],
    judgmentHistory: [
      { id: 'jh-002-1', workOrderId: 'wo-002', operator: '王审核', operatorRole: 'reviewer', oldJudgment: null, newJudgment: 'normal', reason: '校准后测试通过，流程完整', changedAt: '2026-06-01 17:00:00', shift: 'afternoon' },
      { id: 'jh-002-2', workOrderId: 'wo-002', operator: '阿敏', operatorRole: 'supervisor', oldJudgment: 'normal', newJudgment: 'abnormal', reason: '使用了已废止的"三点校准法"旧标准，照片描述中出现旧说法，虽测试数据合格但作业规范不符，需返工按新标准执行', changedAt: '2026-06-01 20:10:00', shift: 'night' },
      { id: 'jh-002-3', workOrderId: 'wo-002', operator: '陈接班', operatorRole: 'reviewer', oldJudgment: 'abnormal', newJudgment: 'pending_review', reason: '夜班接到返工通知，已安排次日早班重做，待复核新标准记录', changedAt: '2026-06-01 23:45:00', shift: 'night' },
    ],
  },
  {
    id: 'wo-003',
    orderNo: 'GD20260601003',
    deviceNo: 'DT-SH-0003',
    deviceName: '环球金融中心A座观光梯',
    faultType: '平层不准',
    faultDescription: '101楼平层误差超 30mm，乘客绊倒风险',
    reportTime: '2026-06-01 14:20:00',
    reporter: '赵工',
    status: 'abnormal',
    priority: 'critical',
    manualRemark: '平层传感器表面有油污，清洁后误差降至18mm仍偏大，待进口配件到货后更换磁栅尺。临时限制电梯使用。',
    judgment: 'abnormal',
    judgmentBy: '阿敏',
    judgmentAt: '2026-06-01 22:00:00',
    shift: 'afternoon',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-003-1',
        workOrderId: 'wo-003',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20leveling%20sensor%20dirty%20oily%20surface%20closeup&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20leveling%20sensor%20dirty%20oily%20surface%20closeup&image_size=square',
        description: '平层传感器油污特写',
        uploadTime: '2026-06-01 15:00:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
      {
        id: 'p-003-2',
        workOrderId: 'wo-003',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20floor%20leveling%20gap%20measurement%20ruler&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20floor%20leveling%20gap%20measurement%20ruler&image_size=square',
        description: '平层误差测量 28mm',
        uploadTime: '2026-06-01 16:30:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
    ],
    attachments: [
      { id: 'a-003-1', filename: '平层误差逐次测量记录.pdf', uploadTime: '2026-06-01 17:30:00', isLateArrival: false },
    ],
    judgmentHistory: [
      { id: 'jh-003-1', workOrderId: 'wo-003', operator: '阿敏', operatorRole: 'supervisor', oldJudgment: null, newJudgment: 'abnormal', reason: '观光梯属高优先级设备，误差超标+配件待进口，必须标记异常并限制使用', changedAt: '2026-06-01 22:00:00', shift: 'night' },
    ],
  },
  {
    id: 'wo-004',
    orderNo: 'GD20260601004',
    deviceNo: 'DT-SH-0001',
    deviceName: '上海中心大厦1号客梯',
    faultType: '门机故障',
    faultDescription: '（重复导入测试）同DT-SH-0001另一条工单',
    reportTime: '2026-06-01 08:20:00',
    reporter: '李工',
    status: 'completed',
    priority: 'high',
    manualRemark: '此条为重复导入测试数据，设备编号与GD20260601001相同',
    judgment: 'pending_review',
    judgmentBy: null,
    judgmentAt: null,
    shift: 'morning',
    isDuplicateWarning: true,
    duplicateAction: 'skip',
    photos: [
      {
        id: 'p-004-1',
        workOrderId: 'wo-004',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=duplicate%20elevator%20repair%20ticket%20document%20warning&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=duplicate%20elevator%20repair%20ticket%20document%20warning&image_size=square',
        description: '重复工单照片',
        uploadTime: '2026-06-01 09:00:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
    ],
    attachments: [],
    judgmentHistory: [],
  },
  {
    id: 'wo-005',
    orderNo: 'GD20260602005',
    deviceNo: 'DT-BJ-0015',
    deviceName: '北京国贸三期B座客梯',
    faultType: '控制板报警',
    faultDescription: '主控板 E41 安全回路断开报警',
    reportTime: '2026-06-02 06:50:00',
    reporter: '孙工',
    status: 'completed',
    priority: 'high',
    manualRemark: '安全回路接线端子13号松动氧化，打磨后扭矩紧固至1.2N·m，连续运行2小时无报警。',
    judgment: 'normal',
    judgmentBy: '王审核',
    judgmentAt: '2026-06-02 11:30:00',
    shift: 'morning',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-005-1',
        workOrderId: 'wo-005',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20control%20board%20safety%20circuit%20terminal%20loose%20wire&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20control%20board%20safety%20circuit%20terminal%20loose%20wire&image_size=square',
        description: '13号端子氧化松动',
        uploadTime: '2026-06-02 07:30:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
      {
        id: 'p-005-2',
        workOrderId: 'wo-005',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=torque%20wrench%20tightening%20elevator%20terminal&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=torque%20wrench%20tightening%20elevator%20terminal&image_size=square',
        description: '扭矩扳手紧固作业',
        uploadTime: '2026-06-02 09:00:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
    ],
    attachments: [
      { id: 'a-005-1', filename: '主控板报警日志导出.csv', uploadTime: '2026-06-02 07:10:00', isLateArrival: false },
      { id: 'a-005-2', filename: '紧固后运行监控日志.csv', uploadTime: '2026-06-02 14:00:00', isLateArrival: true },
    ],
    judgmentHistory: [
      { id: 'jh-005-1', workOrderId: 'wo-005', operator: '王审核', operatorRole: 'reviewer', oldJudgment: null, newJudgment: 'normal', reason: '故障定位准确，处理符合工艺标准', changedAt: '2026-06-02 11:30:00', shift: 'morning' },
    ],
  },
  {
    id: 'wo-006',
    orderNo: 'GD20260602006',
    deviceNo: 'DT-GZ-0008',
    deviceName: '广州西塔IFC消防梯',
    faultType: '通讯故障',
    faultDescription: '轿厢与机房 CAN 通讯偶发中断',
    reportTime: '2026-06-02 11:10:00',
    reporter: '周工',
    status: 'processing',
    priority: 'medium',
    manualRemark: '通讯线屏蔽层接地疑似接触不良，初步处理后观察中。使用老经验"拍打法"确认是接触问题。',
    judgment: 'pending_review',
    judgmentBy: null,
    judgmentAt: null,
    shift: 'morning',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-006-1',
        workOrderId: 'wo-006',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20CAN%20bus%20communication%20cable%20shielding%20ground&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20CAN%20bus%20communication%20cable%20shielding%20ground&image_size=square',
        description: '屏蔽层接地端子',
        uploadTime: '2026-06-02 12:00:00',
        isLateArrival: false,
        hitsOldTerminology: true,
      },
    ],
    attachments: [],
    judgmentHistory: [],
  },
  {
    id: 'wo-007',
    orderNo: 'GD20260602007',
    deviceNo: 'DT-SZ-0022',
    deviceName: '深圳平安金融中心员工梯',
    faultType: '按钮失灵',
    faultDescription: 'B2层呼梯按钮无响应',
    reportTime: '2026-06-02 15:40:00',
    reporter: '吴工',
    status: 'completed',
    priority: 'low',
    manualRemark: '按钮触点积碳，酒精清洁后恢复，已建议物业后续更换新按钮。',
    judgment: 'normal',
    judgmentBy: '陈接班',
    judgmentAt: '2026-06-02 20:00:00',
    shift: 'afternoon',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-007-1',
        workOrderId: 'wo-007',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20call%20button%20disassembled%20carbon%20contacts%20dirty&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20call%20button%20disassembled%20carbon%20contacts%20dirty&image_size=square',
        description: '积碳触点拆解图',
        uploadTime: '2026-06-02 16:15:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
      {
        id: 'p-007-2',
        workOrderId: 'wo-007',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20button%20cleaned%20with%20alcohol%20swab&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20button%20cleaned%20with%20alcohol%20swab&image_size=square',
        description: '酒精清洁作业',
        uploadTime: '2026-06-02 17:00:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
    ],
    attachments: [],
    judgmentHistory: [
      { id: 'jh-007-1', workOrderId: 'wo-007', operator: '陈接班', operatorRole: 'reviewer', oldJudgment: null, newJudgment: 'normal', reason: '小故障处理到位，后续更换建议合理', changedAt: '2026-06-02 20:00:00', shift: 'night' },
    ],
  },
  {
    id: 'wo-008',
    orderNo: 'GD20260602008',
    deviceNo: 'DT-CD-0003',
    deviceName: '成都IFS 2号观光梯',
    faultType: '异响',
    faultDescription: '高速运行时轿厢顶部周期性异响',
    reportTime: '2026-06-02 22:30:00',
    reporter: '钱工',
    status: 'pending',
    priority: 'medium',
    manualRemark: '夜班抵达现场，异响疑似导靴间隙偏大，但需白天停运检查。暂列待处理。',
    judgment: 'pending_review',
    judgmentBy: null,
    judgmentAt: null,
    shift: 'night',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-008-1',
        workOrderId: 'wo-008',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20guide%20shoe%20gap%20measurement%20night%20shift&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20guide%20shoe%20gap%20measurement%20night%20shift&image_size=square',
        description: '夜班初查导靴区域',
        uploadTime: '2026-06-02 23:15:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
    ],
    attachments: [],
    judgmentHistory: [],
  },
  {
    id: 'wo-009',
    orderNo: 'GD20260603009',
    deviceNo: 'DT-HZ-0001',
    deviceName: '杭州来福士广场医用梯',
    faultType: '关门受阻',
    faultDescription: '光幕频繁误触发，影响担架进出',
    reportTime: '2026-06-03 07:05:00',
    reporter: '冯工',
    status: 'completed',
    priority: 'critical',
    manualRemark: '医用梯优先级最高，光幕透镜表面有消毒水结晶雾层，专用清洁布擦拭后恢复。连续测试担架通行20次无异常。',
    judgment: 'normal',
    judgmentBy: '阿敏',
    judgmentAt: '2026-06-03 12:00:00',
    shift: 'morning',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-009-1',
        workOrderId: 'wo-009',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20door%20light%20curtain%20lens%20foggy%20disinfectant%20residue&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20door%20light%20curtain%20lens%20foggy%20disinfectant%20residue&image_size=square',
        description: '光幕透镜雾层（消毒水结晶）',
        uploadTime: '2026-06-03 07:40:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
      {
        id: 'p-009-2',
        workOrderId: 'wo-009',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=hospital%20stretcher%20passing%20elevator%20door%20test&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=hospital%20stretcher%20passing%20elevator%20door%20test&image_size=square',
        description: '担架通行测试',
        uploadTime: '2026-06-03 09:30:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
      {
        id: 'p-009-3',
        workOrderId: 'wo-009',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=hospital%20elevator%20maintenance%20sign%20off%20form&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=hospital%20elevator%20maintenance%20sign%20off%20form&image_size=square',
        description: '院方后勤签字确认（补传）',
        uploadTime: '2026-06-04 10:00:00',
        isLateArrival: true,
        hitsOldTerminology: false,
      },
    ],
    attachments: [
      { id: 'a-009-1', filename: '医用梯担架通行测试录像.mp4', uploadTime: '2026-06-03 10:00:00', isLateArrival: false },
    ],
    judgmentHistory: [
      { id: 'jh-009-1', workOrderId: 'wo-009', operator: '王审核', operatorRole: 'reviewer', oldJudgment: null, newJudgment: 'normal', reason: '医用梯处理及时，测试完整', changedAt: '2026-06-03 11:00:00', shift: 'morning' },
      { id: 'jh-009-2', workOrderId: 'wo-009', operator: '阿敏', operatorRole: 'supervisor', oldJudgment: 'normal', newJudgment: 'normal', reason: '复核确认，医用梯类故障处理流程合规，担架测试录像留存完整，无需返工', changedAt: '2026-06-03 12:00:00', shift: 'morning' },
    ],
  },
  {
    id: 'wo-010',
    orderNo: 'GD20260603010',
    deviceNo: 'DT-NJ-0007',
    deviceName: '南京紫峰大厦办公梯',
    faultType: '运行抖动',
    faultDescription: '40-50层区间运行有明显顿挫感',
    reportTime: '2026-06-03 10:20:00',
    reporter: '郑工',
    status: 'processing',
    priority: 'medium',
    manualRemark: '曳引轮绳槽磨损不均，需安排周末钢丝绳跳槽重车。正在排期。',
    judgment: 'abnormal',
    judgmentBy: '阿敏',
    judgmentAt: '2026-06-03 18:00:00',
    shift: 'morning',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-010-1',
        workOrderId: 'wo-010',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20traction%20sheave%20rope%20groove%20uneven%20wear&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20traction%20sheave%20rope%20groove%20uneven%20wear&image_size=square',
        description: '绳槽磨损不均特写',
        uploadTime: '2026-06-03 11:00:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
    ],
    attachments: [
      { id: 'a-010-1', filename: '绳槽磨损深度测量表.xlsx', uploadTime: '2026-06-03 14:00:00', isLateArrival: false },
    ],
    judgmentHistory: [
      { id: 'jh-010-1', workOrderId: 'wo-010', operator: '阿敏', operatorRole: 'supervisor', oldJudgment: null, newJudgment: 'abnormal', reason: '曳引系统核心部件磨损，虽可暂运行但存在打滑风险，按异常处理督促排期', changedAt: '2026-06-03 18:00:00', shift: 'afternoon' },
    ],
  },
  {
    id: 'wo-011',
    orderNo: 'GD20260603011',
    deviceNo: 'DT-WH-0012',
    deviceName: '武汉绿地中心服务梯',
    faultType: '超载误报',
    faultDescription: '空轿厢偶发超载报警重启',
    reportTime: '2026-06-03 16:45:00',
    reporter: '韩工',
    status: 'pending',
    priority: 'high',
    manualRemark: '待深入排查，怀疑AD转换板漂移。按旧经验先用手压法模拟加载确认——旧说法备注。',
    judgment: 'pending_review',
    judgmentBy: null,
    judgmentAt: null,
    shift: 'afternoon',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-011-1',
        workOrderId: 'wo-011',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20AD%20converter%20board%20drift%20diagnostic%20multimeter&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20AD%20converter%20board%20drift%20diagnostic%20multimeter&image_size=square',
        description: 'AD板漂移检测中',
        uploadTime: '2026-06-03 17:30:00',
        isLateArrival: false,
        hitsOldTerminology: true,
      },
    ],
    attachments: [],
    judgmentHistory: [],
  },
  {
    id: 'wo-012',
    orderNo: 'GD20260604012',
    deviceNo: 'DT-XA-0005',
    deviceName: '西安绿地中心A座客梯',
    faultType: '显示屏异常',
    faultDescription: '轿厢内显示屏花屏闪跳',
    reportTime: '2026-06-04 09:00:00',
    reporter: '杨工',
    status: 'completed',
    priority: 'low',
    manualRemark: '排线接口氧化，重新插拔后恢复正常。已申请备用排线以便后续复发快速更换。',
    judgment: 'normal',
    judgmentBy: '陈接班',
    judgmentAt: '2026-06-04 15:00:00',
    shift: 'morning',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-012-1',
        workOrderId: 'wo-012',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20car%20display%20screen%20flickering%20colorful%20lines&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20car%20display%20screen%20flickering%20colorful%20lines&image_size=square',
        description: '花屏现场',
        uploadTime: '2026-06-04 09:30:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
      {
        id: 'p-012-2',
        workOrderId: 'wo-012',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20display%20ribbon%20cable%20reconnecting%20repair&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20display%20ribbon%20cable%20reconnecting%20repair&image_size=square',
        description: '重插排线作业',
        uploadTime: '2026-06-04 10:30:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
    ],
    attachments: [],
    judgmentHistory: [
      { id: 'jh-012-1', workOrderId: 'wo-012', operator: '陈接班', operatorRole: 'reviewer', oldJudgment: null, newJudgment: 'normal', reason: '常见小故障处理规范', changedAt: '2026-06-04 15:00:00', shift: 'afternoon' },
    ],
  },
  {
    id: 'wo-013',
    orderNo: 'GD20260604013',
    deviceNo: 'DT-CQ-0009',
    deviceName: '重庆来福士T3N客梯',
    faultType: '限速器动作',
    faultDescription: '下行12楼限速器意外动作安全钳抱死',
    reportTime: '2026-06-04 13:15:00',
    reporter: '朱工',
    status: 'abnormal',
    priority: 'critical',
    manualRemark: '限速器离心块弹簧疲劳断裂导致意外动作，已更换弹簧+恢复安全钳，正做限速器校验。属重大未遂事件。',
    judgment: 'abnormal',
    judgmentBy: '阿敏',
    judgmentAt: '2026-06-04 22:00:00',
    shift: 'afternoon',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-013-1',
        workOrderId: 'wo-013',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20overspeed%20governor%20broken%20spring%20centrifugal%20weight&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20overspeed%20governor%20broken%20spring%20centrifugal%20weight&image_size=square',
        description: '断裂的限速器弹簧',
        uploadTime: '2026-06-04 14:00:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
      {
        id: 'p-013-2',
        workOrderId: 'wo-013',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20safety%20gear%20wedge%20jammed%20release%20repair&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20safety%20gear%20wedge%20jammed%20release%20repair&image_size=square',
        description: '安全钳楔块恢复作业',
        uploadTime: '2026-06-04 17:00:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
      {
        id: 'p-013-3',
        workOrderId: 'wo-013',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20governor%20calibration%20test%20equipment%20certified&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20governor%20calibration%20test%20equipment%20certified&image_size=square',
        description: '限速器校验中（晚传）',
        uploadTime: '2026-06-05 09:30:00',
        isLateArrival: true,
        hitsOldTerminology: false,
      },
    ],
    attachments: [
      { id: 'a-013-1', filename: '限速器弹簧材质检测报告.pdf', uploadTime: '2026-06-04 18:00:00', isLateArrival: false },
      { id: 'a-013-2', filename: '重大未遂事件初报表.docx', uploadTime: '2026-06-04 21:00:00', isLateArrival: false },
      { id: 'a-013-3', filename: '限速器校验证书最终版.pdf', uploadTime: '2026-06-05 15:00:00', isLateArrival: true },
    ],
    judgmentHistory: [
      { id: 'jh-013-1', workOrderId: 'wo-013', operator: '王审核', operatorRole: 'reviewer', oldJudgment: null, newJudgment: 'abnormal', reason: '限速器意外动作属重大安全事件', changedAt: '2026-06-04 20:00:00', shift: 'night' },
      { id: 'jh-013-2', workOrderId: 'wo-013', operator: '阿敏', operatorRole: 'supervisor', oldJudgment: 'abnormal', newJudgment: 'abnormal', reason: '复核确认异常定级正确，已要求全区域同型号限速器排查弹簧疲劳，并留存校验证书待后续抽检', changedAt: '2026-06-04 22:00:00', shift: 'night' },
    ],
  },
  {
    id: 'wo-014',
    orderNo: 'GD20260604014',
    deviceNo: 'DT-TJ-0002',
    deviceName: '天津周大福金融中心货梯',
    faultType: '变频器过流',
    faultDescription: '重载上行时变频器 OC 报警停机',
    reportTime: '2026-06-04 19:20:00',
    reporter: '秦工',
    status: 'completed',
    priority: 'high',
    manualRemark: '电机绝缘老化导致相间泄漏电流偏大，已做绝缘浸漆处理，空载满载各测试30次通过。',
    judgment: 'normal',
    judgmentBy: '陈接班',
    judgmentAt: '2026-06-05 08:00:00',
    shift: 'night',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-014-1',
        workOrderId: 'wo-014',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20inverter%20overcurrent%20OC%20alarm%20display&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20inverter%20overcurrent%20OC%20alarm%20display&image_size=square',
        description: '变频器 OC 报警界面',
        uploadTime: '2026-06-04 19:45:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
      {
        id: 'p-014-2',
        workOrderId: 'wo-014',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20traction%20motor%20insulation%20varnish%20treatment&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20traction%20motor%20insulation%20varnish%20treatment&image_size=square',
        description: '电机绝缘浸漆处理',
        uploadTime: '2026-06-05 01:00:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
    ],
    attachments: [
      { id: 'a-014-1', filename: '电机绝缘电阻测试记录.xlsx', uploadTime: '2026-06-05 06:00:00', isLateArrival: false },
    ],
    judgmentHistory: [
      { id: 'jh-014-1', workOrderId: 'wo-014', operator: '陈接班', operatorRole: 'reviewer', oldJudgment: null, newJudgment: 'normal', reason: '处理彻底，测试数据齐全', changedAt: '2026-06-05 08:00:00', shift: 'morning' },
    ],
  },
  {
    id: 'wo-015',
    orderNo: 'GD20260605015',
    deviceNo: 'DT-BJ-0015',
    deviceName: '北京国贸三期B座客梯',
    faultType: '控制板报警',
    faultDescription: '（重复导入测试）与GD20260602005同设备编号',
    reportTime: '2026-06-05 10:00:00',
    reporter: '孙工',
    status: 'processing',
    priority: 'medium',
    manualRemark: '此条为第二组重复设备编号测试，设备编号DT-BJ-0015已存在于WO-005。',
    judgment: 'pending_review',
    judgmentBy: null,
    judgmentAt: null,
    shift: 'morning',
    isDuplicateWarning: true,
    photos: [
      {
        id: 'p-015-1',
        workOrderId: 'wo-015',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=duplicate%20elevator%20work%20order%20second%20instance%20testing&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=duplicate%20elevator%20work%20order%20second%20instance%20testing&image_size=square',
        description: '重复工单测试2',
        uploadTime: '2026-06-05 10:30:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
    ],
    attachments: [],
    judgmentHistory: [],
  },
  {
    id: 'wo-016',
    orderNo: 'GD20260605016',
    deviceNo: 'DT-QD-0006',
    deviceName: '青岛海天中心客梯',
    faultType: '对讲无声',
    faultDescription: '轿厢紧急对讲主机无声音输出',
    reportTime: '2026-06-05 11:30:00',
    reporter: '许工',
    status: 'completed',
    priority: 'medium',
    manualRemark: '5P线插针接触不良，压线钳重新压接后对讲恢复，5方通话全测通过。',
    judgment: 'normal',
    judgmentBy: '王审核',
    judgmentAt: '2026-06-05 16:00:00',
    shift: 'morning',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-016-1',
        workOrderId: 'wo-016',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20emergency%20intercom%205%20party%20cable%20connector%20loose&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20emergency%20intercom%205%20party%20cable%20connector%20loose&image_size=square',
        description: '5P线插针',
        uploadTime: '2026-06-05 12:00:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
    ],
    attachments: [],
    judgmentHistory: [
      { id: 'jh-016-1', workOrderId: 'wo-016', operator: '王审核', operatorRole: 'reviewer', oldJudgment: null, newJudgment: 'normal', reason: '紧急对讲属安全项，全测通过后合格', changedAt: '2026-06-05 16:00:00', shift: 'afternoon' },
    ],
  },
  {
    id: 'wo-017',
    orderNo: 'GD20260605017',
    deviceNo: 'DT-DL-0011',
    deviceName: '大连中心裕景公寓梯',
    faultType: '轿厢照明故障',
    faultDescription: 'LED照明一半不亮，应急灯正常',
    reportTime: '2026-06-05 14:40:00',
    reporter: '何工',
    status: 'completed',
    priority: 'low',
    manualRemark: 'LED驱动电源输出异常，更换同型号驱动后照明全亮。拆回旧件返厂分析。',
    judgment: 'normal',
    judgmentBy: '陈接班',
    judgmentAt: '2026-06-05 22:00:00',
    shift: 'afternoon',
    isDuplicateWarning: false,
    photos: [
      {
        id: 'p-017-1',
        workOrderId: 'wo-017',
        url: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20car%20LED%20light%20half%20out%20driver%20replacement&image_size=square_hd',
        thumbnail: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=elevator%20car%20LED%20light%20half%20out%20driver%20replacement&image_size=square',
        description: '更换LED驱动',
        uploadTime: '2026-06-05 15:30:00',
        isLateArrival: false,
        hitsOldTerminology: false,
      },
    ],
    attachments: [],
    judgmentHistory: [
      { id: 'jh-017-1', workOrderId: 'wo-017', operator: '陈接班', operatorRole: 'reviewer', oldJudgment: null, newJudgment: 'normal', reason: '照明类故障更换配件即完成', changedAt: '2026-06-05 22:00:00', shift: 'night' },
    ],
  },
];

export const SAMPLE_ORDER_ID = 'wo-002';
