import * as fs from 'fs';
import * as path from 'path';
import { createObjectCsvWriter } from 'csv-writer';
import { AnalysisReport, Issue, IssueType } from '../types';
import { logger } from '../utils/logger';

export class OutputGenerator {
  private outputDir: string;

  constructor(outputDir: string) {
    this.outputDir = outputDir;
    this.ensureDirectory();
  }

  private ensureDirectory(): void {
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
      logger.info(`Created output directory: ${this.outputDir}`);
    }
  }

  async generateAll(report: AnalysisReport): Promise<void> {
    logger.info('Generating output files...');
    
    await Promise.all([
      this.generateReportMd(report),
      this.generateIssuesCsv(report),
      this.generateHitMatrixHtml(report)
    ]);
    
    logger.success('All output files generated successfully');
  }

  private async generateReportMd(report: AnalysisReport): Promise<void> {
    const filePath = path.join(this.outputDir, 'report.md');
    logger.info(`Generating ${filePath}`);

    const issueCounts = this.countIssuesByType(report.issues);
    
    const content = `# Canary Replay Analysis Report

## Summary
Generated at: ${report.generatedAt}

### Request Statistics
| Metric | Value |
|--------|-------|
| Total Requests | ${report.summary.totalRequests} |
| Matched Routes | ${report.summary.matchedRoutes} |
| Canary Hits | ${report.summary.canaryHits} |
| Stable Hits | ${report.summary.stableHits} |

### Issue Summary
| Severity | Count |
|----------|-------|
| Critical | ${report.summary.criticalIssues} |
| High | ${report.summary.highIssues} |
| Medium | ${report.summary.mediumIssues} |
| Low | ${report.summary.lowIssues} |
| **Total** | **${report.summary.totalIssues}** |

### Issues by Type
${this.renderIssueTypeBreakdown(issueCounts)}

${report.routeOverlaps.length > 0 ? `
## Route Overlap Detection
The following route patterns overlap and may cause unexpected routing:

${report.routeOverlaps.map(overlap => `
### Overlap: \`${overlap.path1}\` and \`${overlap.path2}\`
- **Priority Conflict**: ${overlap.priorityConflict ? '⚠️ YES - Same priority, behavior is undefined' : 'No - priorities differ'}
`).join('')}

**Recommendation**: Review these routes and ensure proper priority ordering.
` : ''}

${report.missingHealthData.length > 0 ? `
## Missing Health Data
The following service versions have no health check data:

${report.missingHealthData.map(svc => `- ${svc}`).join('\n')}

**Recommendation**: Ensure health monitoring is configured for all canary versions.
` : ''}

## Weight Analysis
${report.weightAnalysis.length > 0 ? `
| Service | Version | Expected Weight | Actual Hits | Actual % | Status |
|---------|---------|-----------------|-------------|----------|--------|
${report.weightAnalysis.map(w => `
| ${w.service} | ${w.version} | ${w.expectedWeight}% | ${w.actualHits} | ${w.actualPercentage.toFixed(2)}% | ${w.isOverBudget ? '⚠️ OVER BUDGET' : '✓ OK'} |
`).join('')}
` : 'No canary weight rules were matched during replay.'}

## Detailed Issues
${report.issues.length > 0 ? this.renderDetailedIssues(report.issues) : 'No issues detected during replay.'}

---
*This report was generated by canary-replay-cli. For more details, see the accompanying issues.csv and hit_matrix.html files.*
`;

    fs.writeFileSync(filePath, content);
    logger.success(`Generated ${filePath}`);
  }

  private countIssuesByType(issues: Issue[]): Record<IssueType, number> {
    const counts: Record<IssueType, number> = {
      WRONG_SERVICE: 0,
      HEALTHY_SHOULD_HIT_CANARY: 0,
      UNHEALTHY_STILL_SHUNT: 0,
      WEIGHT_EXCEEDS_BUDGET: 0,
      MISSING_HEALTH_DATA: 0,
      ROUTE_OVERLAP: 0
    };

    for (const issue of issues) {
      counts[issue.type]++;
    }

    return counts;
  }

  private renderIssueTypeBreakdown(counts: Record<IssueType, number>): string {
    const typeNames: Record<IssueType, string> = {
      WRONG_SERVICE: 'Wrong Service Routing',
      HEALTHY_SHOULD_HIT_CANARY: 'Healthy Requests Missed Canary',
      UNHEALTHY_STILL_SHUNT: 'Unhealthy Service Would Receive Traffic',
      WEIGHT_EXCEEDS_BUDGET: 'Weight Exceeds Budget',
      MISSING_HEALTH_DATA: 'Missing Health Data',
      ROUTE_OVERLAP: 'Route Overlap'
    };

    const lines: string[] = [];
    for (const [type, count] of Object.entries(counts) as [IssueType, number][]) {
      if (count > 0) {
        const icon = count > 0 ? '⚠️' : '✓';
        lines.push(`- ${icon} **${typeNames[type]}**: ${count}`);
      }
    }

    return lines.length > 0 ? lines.join('\n') : '- No issues detected';
  }

  private renderDetailedIssues(issues: Issue[]): string {
    const severityOrder: ('critical' | 'high' | 'medium' | 'low')[] = ['critical', 'high', 'medium', 'low'];
    const severityEmoji: Record<string, string> = {
      critical: '🔴',
      high: '🟠',
      medium: '🟡',
      low: '⚪'
    };

    let content = '';

    for (const severity of severityOrder) {
      const severityIssues = issues.filter(i => i.severity === severity);
      if (severityIssues.length === 0) continue;

      content += `\n### ${severityEmoji[severity]} ${severity.toUpperCase()} Issues (${severityIssues.length})\n\n`;
      
      for (const issue of severityIssues) {
        content += `#### ${issue.type}\n`;
        content += `${issue.message}\n\n`;
        content += '```json\n';
        content += JSON.stringify(issue.details, null, 2);
        content += '\n```\n\n';
      }
    }

    return content;
  }

  private async generateIssuesCsv(report: AnalysisReport): Promise<void> {
    const filePath = path.join(this.outputDir, 'issues.csv');
    logger.info(`Generating ${filePath}`);

    if (report.issues.length === 0) {
      fs.writeFileSync(filePath, 'type,severity,message,details\n');
      logger.success(`Generated ${filePath} (empty)`);
      return;
    }

    const csvWriter = createObjectCsvWriter({
      path: filePath,
      header: [
        { id: 'type', title: 'type' },
        { id: 'severity', title: 'severity' },
        { id: 'message', title: 'message' },
        { id: 'details', title: 'details' }
      ]
    });

    const records = report.issues.map(issue => ({
      type: issue.type,
      severity: issue.severity,
      message: issue.message,
      details: JSON.stringify(issue.details)
    }));

    await csvWriter.writeRecords(records);
    logger.success(`Generated ${filePath}`);
  }

  private async generateHitMatrixHtml(report: AnalysisReport): Promise<void> {
    const filePath = path.join(this.outputDir, 'hit_matrix.html');
    logger.info(`Generating ${filePath}`);

    const content = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Canary Replay - Hit Matrix</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f7fa; padding: 20px; }
    .container { max-width: 1400px; margin: 0 auto; }
    h1 { color: #1a202c; margin-bottom: 20px; }
    .summary { background: white; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    .summary-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }
    .summary-item { background: #edf2f7; padding: 15px; border-radius: 6px; text-align: center; }
    .summary-item .value { font-size: 24px; font-weight: bold; color: #2d3748; }
    .summary-item .label { font-size: 12px; color: #718096; margin-top: 4px; }
    .severity-critical { background: #fed7d7; color: #c53030; }
    .severity-high { background: #feebc8; color: #c05621; }
    .severity-medium { background: #fefcbf; color: #975a16; }
    .severity-low { background: #e2e8f0; color: #4a5568; }
    .matrix-section { background: white; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
    .matrix-section h2 { color: #2d3748; margin-bottom: 15px; font-size: 18px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th, td { padding: 10px; text-align: left; border-bottom: 1px solid #e2e8f0; }
    th { background: #f7fafc; font-weight: 600; color: #4a5568; }
    tr:hover { background: #f7fafc; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 11px; font-weight: 500; }
    .badge-canary { background: #bee3f8; color: #2b6cb0; }
    .badge-stable { background: #c6f6d5; color: #276749; }
    .badge-healthy { background: #c6f6d5; color: #276749; }
    .badge-unhealthy { background: #fed7d7; color: #c53030; }
    .issue-indicator { display: inline-block; width: 8px; height: 8px; border-radius: 50%; margin-right: 4px; }
    .filters { display: flex; gap: 10px; margin-bottom: 15px; flex-wrap: wrap; }
    .filter-btn { padding: 6px 12px; border: 1px solid #e2e8f0; background: white; border-radius: 4px; cursor: pointer; font-size: 13px; }
    .filter-btn.active { background: #4299e1; color: white; border-color: #4299e1; }
    .empty-state { text-align: center; padding: 40px; color: #718096; }
    .toggle-details { background: none; border: none; cursor: pointer; color: #4299e1; font-size: 12px; }
    .details-row { display: none; }
    .details-row.show { display: table-row; }
    .details-content { background: #f7fafc; padding: 15px; border-radius: 4px; font-family: monospace; font-size: 12px; white-space: pre-wrap; }
  </style>
</head>
<body>
  <div class="container">
    <h1>🎯 Canary Replay - Hit Matrix</h1>
    
    <div class="summary">
      <div class="summary-grid">
        <div class="summary-item">
          <div class="value">${report.summary.totalRequests}</div>
          <div class="label">Total Requests</div>
        </div>
        <div class="summary-item">
          <div class="value">${report.summary.matchedRoutes}</div>
          <div class="label">Matched Routes</div>
        </div>
        <div class="summary-item">
          <div class="value">${report.summary.canaryHits}</div>
          <div class="label">Canary Hits</div>
        </div>
        <div class="summary-item">
          <div class="value">${report.summary.stableHits}</div>
          <div class="label">Stable Hits</div>
        </div>
        <div class="summary-item ${report.summary.criticalIssues > 0 ? 'severity-critical' : ''}">
          <div class="value">${report.summary.criticalIssues}</div>
          <div class="label">Critical Issues</div>
        </div>
        <div class="summary-item ${report.summary.highIssues > 0 ? 'severity-high' : ''}">
          <div class="value">${report.summary.highIssues}</div>
          <div class="label">High Issues</div>
        </div>
      </div>
    </div>

    ${report.weightAnalysis.length > 0 ? `
    <div class="matrix-section">
      <h2>📊 Weight Distribution</h2>
      <table>
        <thead>
          <tr>
            <th>Service</th>
            <th>Version</th>
            <th>Expected Weight</th>
            <th>Actual Hits</th>
            <th>Actual %</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          ${report.weightAnalysis.map(w => `
          <tr>
            <td><strong>${w.service}</strong></td>
            <td><span class="badge badge-canary">${w.version}</span></td>
            <td>${w.expectedWeight}%</td>
            <td>${w.actualHits}</td>
            <td>${w.actualPercentage.toFixed(2)}%</td>
            <td>${w.isOverBudget ? '<span class="badge severity-high">⚠️ OVER BUDGET</span>' : '<span class="badge badge-healthy">✓ OK</span>'}</td>
          </tr>
          `).join('')}
        </tbody>
      </table>
    </div>
    ` : ''}

    <div class="matrix-section">
      <h2>🔗 Hit Chain Details</h2>
      <div class="filters">
        <button class="filter-btn active" onclick="filterRows('all')">All</button>
        <button class="filter-btn" onclick="filterRows('canary')">Canary Only</button>
        <button class="filter-btn" onclick="filterRows('stable')">Stable Only</button>
        <button class="filter-btn" onclick="filterRows('issues')">With Issues</button>
      </div>
      ${report.hitChains.length > 0 ? `
      <table id="hitMatrix">
        <thead>
          <tr>
            <th>#</th>
            <th>Request ID</th>
            <th>Path</th>
            <th>Route</th>
            <th>Target</th>
            <th>Health</th>
            <th>Issues</th>
            <th>Details</th>
          </tr>
        </thead>
        <tbody>
          ${report.hitChains.map((chain, index) => {
            const hasIssues = chain.issues.length > 0;
            const isCanary = chain.canaryEvaluation.shouldHitCanary;
            const rowClass = hasIssues ? 'has-issues' : (isCanary ? 'canary-hit' : 'stable-hit');
            return `
          <tr class="data-row ${rowClass}">
            <td>${index + 1}</td>
            <td><code>${chain.requestId}</code></td>
            <td><code>${chain.path}</code></td>
            <td>${chain.routeMatch.matched ? `✓ <code>${chain.routeMatch.route.path}</code>` : '❌ No Match'}</td>
            <td>
              <span class="badge ${isCanary ? 'badge-canary' : 'badge-stable'}">${chain.actualService}:${chain.actualVersion}</span>
            </td>
            <td>
              ${chain.isHealthy ? '<span class="badge badge-healthy">✓ Healthy</span>' : '<span class="badge badge-unhealthy">✗ Unhealthy</span>'}
              ${!chain.healthInfo ? '<span class="badge severity-medium">⚠️ No Data</span>' : ''}
            </td>
            <td>
              ${hasIssues ? chain.issues.map(i => `<span class="issue-indicator" style="background: ${this.severityToColor(i.severity)}"></span>`).join('') : '—'}
            </td>
            <td><button class="toggle-details" onclick="toggleDetails(${index})">View</button></td>
          </tr>
          <tr class="details-row" id="details-${index}">
            <td colspan="8">
              <div class="details-content">
<strong>Request Info:</strong>
  Method: ${chain.method}
  Headers: ${JSON.stringify(chain.headers, null, 2)}
  User ID: ${chain.userId || 'N/A'}
  Bucket: ${chain.bucket || 'N/A'}

<strong>Route Match:</strong>
  Matched: ${chain.routeMatch.matched ? 'Yes' : 'No'}
  ${chain.routeMatch.matched ? `Route: ${chain.routeMatch.route.path}` : `Reason: ${chain.routeMatch.reason || 'N/A'}`}

<strong>Canary Evaluation:</strong>
  Should Hit Canary: ${chain.canaryEvaluation.shouldHitCanary ? 'Yes' : 'No'}
  Target Version: ${chain.canaryEvaluation.targetVersion}
  Weight: ${chain.canaryEvaluation.weight}%
  Matched Conditions: ${chain.canaryEvaluation.matchedConditions.length > 0 ? chain.canaryEvaluation.matchedConditions.join(', ') : 'None'}
  Reasoning: ${chain.canaryEvaluation.reasoning}

<strong>Health Status:</strong>
  Healthy: ${chain.isHealthy ? 'Yes' : 'No'}
  ${chain.healthInfo ? `Health Data:
    Error Rate: ${chain.healthInfo.errorRate}%
    P99 Latency: ${chain.healthInfo.latencyP99}ms
    Last Check: ${chain.healthInfo.lastCheck}` : 'No health data available'}

<strong>Issues (${chain.issues.length}):</strong>
${chain.issues.length > 0 ? chain.issues.map(i => `  [${i.severity.toUpperCase()}] ${i.type}: ${i.message}
    Details: ${JSON.stringify(i.details, null, 2)}`).join('\n\n') : '  None'}
              </div>
            </td>
          </tr>
          `;
          }).join('')}
        </tbody>
      </table>
      ` : '<div class="empty-state">No hit chains to display</div>'}
    </div>

    <div class="matrix-section">
      <h2>🗺️ Route Overlaps</h2>
      ${report.routeOverlaps.length > 0 ? `
      <table>
        <thead>
          <tr>
            <th>Route 1</th>
            <th>Route 2</th>
            <th>Priority Conflict</th>
          </tr>
        </thead>
        <tbody>
          ${report.routeOverlaps.map(overlap => `
          <tr>
            <td><code>${overlap.path1}</code></td>
            <td><code>${overlap.path2}</code></td>
            <td>${overlap.priorityConflict ? '<span class="badge severity-critical">⚠️ YES</span>' : '<span class="badge badge-healthy">No</span>'}</td>
          </tr>
          `).join('')}
        </tbody>
      </table>
      ` : '<div class="empty-state">No route overlaps detected ✓</div>'}
    </div>

    <div class="matrix-section">
      <h2>📋 Missing Health Data</h2>
      ${report.missingHealthData.length > 0 ? `
      <ul style="list-style: none; padding: 0;">
        ${report.missingHealthData.map(svc => `
        <li style="padding: 8px 0; border-bottom: 1px solid #e2e8f0;">
          <span class="badge severity-medium">⚠️</span>
          <code>${svc}</code>
        </li>
        `).join('')}
      </ul>
      ` : '<div class="empty-state">All services have health data ✓</div>'}
    </div>

    <div style="text-align: center; padding: 20px; color: #718096; font-size: 12px;">
      Generated at: ${report.generatedAt} | canary-replay-cli
    </div>
  </div>

  <script>
    function toggleDetails(index) {
      const row = document.getElementById('details-' + index);
      row.classList.toggle('show');
    }

    function filterRows(type) {
      document.querySelectorAll('.filter-btn').forEach(btn => btn.classList.remove('active'));
      event.target.classList.add('active');

      const rows = document.querySelectorAll('.data-row');
      rows.forEach(row => {
        const detailsRow = row.nextElementSibling;
        let show = false;

        switch(type) {
          case 'all':
            show = true;
            break;
          case 'canary':
            show = row.classList.contains('canary-hit');
            break;
          case 'stable':
            show = row.classList.contains('stable-hit');
            break;
          case 'issues':
            show = row.classList.contains('has-issues');
            break;
        }

        row.style.display = show ? '' : 'none';
        if (detailsRow && detailsRow.classList.contains('details-row')) {
          detailsRow.style.display = 'none';
        }
      });
    }
  </script>
</body>
</html>
`;

    fs.writeFileSync(filePath, content);
    logger.success(`Generated ${filePath}`);
  }

  private severityToColor(severity: string): string {
    const colors: Record<string, string> = {
      critical: '#ef4444',
      high: '#f97316',
      medium: '#eab308',
      low: '#9ca3af'
    };
    return colors[severity] || '#9ca3af';
  }
}
