"""Generate three_step_flow.py"""
import os

OUTPUT = os.path.join(os.path.dirname(__file__), "learning_path_recommender", "workflow", "three_step_flow.py")

lines = []
lines.append('from typing import List, Dict, Any')
lines.append('from datetime import datetime')
lines.append('from ..core import Importer, VersionManager, MaskingEngine')
lines.append('from ..audit import AuditLogger')
lines.append('from ..storage import JSONStorage')
lines.append('')
lines.append('')
lines.append('class ThreeStepWorkflow:')
lines.append('    def __init__(self, storage: JSONStorage):')
lines.append('        self.storage = storage')
lines.append('        self.audit = AuditLogger(storage)')
lines.append('        self.version_manager = VersionManager(storage, self.audit)')
lines.append('        self.importer = Importer(storage, self.audit, self.version_manager)')
lines.append('        self.masking_engine = MaskingEngine(storage, self.audit)')
lines.append('')
lines.append('    def step1_import_model_outputs(self, items, batch_id, imported_by="system", source_file=None):')
lines.append('        self.audit.log_workflow_step("three_step", "step1_import_model_outputs", "started", imported_by, {"batch_id": batch_id, "item_count": len(items)})')
lines.append('        import_record = self.importer.import_model_outputs(items=items, batch_id=batch_id, imported_by=imported_by, source_file=source_file)')
lines.append('        for rec_id in import_record.item_ids:')
lines.append('            self.masking_engine.process_recommendation(rec_id, imported_by, auto_fix=False)')
lines.append('        result = {"step": 1, "name": "import_model_outputs", "batch_id": batch_id, "import_record": import_record.to_dict(), "item_ids": import_record.item_ids}')
lines.append('        self.audit.log_workflow_step("three_step", "step1_import_model_outputs", "completed", imported_by, result)')
lines.append('        return result')
lines.append('')
lines.append('    def step2_apply_manual_reviews(self, reviews, batch_id, applied_by="xiaomeng"):')
lines.append('        self.audit.log_workflow_step("three_step", "step2_apply_manual_reviews", "started", applied_by, {"batch_id": batch_id, "review_count": len(reviews)})')
lines.append('        updated, not_found, unchanged = self.importer.apply_manual_review(reviews=reviews, batch_id=batch_id, applied_by=applied_by)')
lines.append('        recs = self.storage.list_recommendations(batch_id=batch_id)')
lines.append('        for rec in recs:')
lines.append('            if rec.review_status == "reviewed":')
lines.append('                self.masking_engine.process_recommendation(rec.id, applied_by, auto_fix=False)')
lines.append('        result = {"step": 2, "name": "apply_manual_reviews", "batch_id": batch_id, "updated": updated, "not_found": not_found, "unchanged": unchanged}')
lines.append('        self.audit.log_workflow_step("three_step", "step2_apply_manual_reviews", "completed", applied_by, result)')
lines.append('        return result')
lines.append('')
lines.append('    def step3_export_masked(self, batch_id, exported_by, include_unreviewed=False, escalate_phone_issues=True):')
lines.append('        self.audit.log_workflow_step("three_step", "step3_export_masked", "started", exported_by, {"batch_id": batch_id, "include_unreviewed": include_unreviewed})')
lines.append('        recs = self.storage.list_recommendations(batch_id=batch_id)')
lines.append('        rec_ids = [r.id for r in recs]')
lines.append('        phone_issues = []')
lines.append('        for rec in recs:')
lines.append('            if rec.has_unmasked_phone:')
lines.append('                if escalate_phone_issues:')
lines.append('                    self.masking_engine.mark_for_algorithm_review(rec.id, exported_by, "导出时发现手机号漏遮，留待算法同事复核")')
lines.append('                phone_issues.append(rec.id)')
lines.append('        exported, skipped = self.masking_engine.export_masked(rec_ids, exported_by, include_unreviewed=include_unreviewed)')
lines.append('        result = {"step": 3, "name": "export_masked", "batch_id": batch_id, "total": len(rec_ids), "exported_count": len(exported), "skipped_count": len(skipped), "phone_issue_count": len(phone_issues), "phone_issue_ids": phone_issues, "skipped_ids": skipped, "exported_data": exported}')
lines.append('        self.audit.log_workflow_step("three_step", "step3_export_masked", "completed", exported_by, {k: v for k, v in result.items() if k != "exported_data"})')
lines.append('        return result')
lines.append('')
lines.append('    def run_full_workflow(self, model_items, manual_reviews, batch_id, operator="xiaomeng"):')
lines.append('        step1 = self.step1_import_model_outputs(items=model_items, batch_id=batch_id, imported_by=operator)')
lines.append('        step2 = self.step2_apply_manual_reviews(reviews=manual_reviews, batch_id=batch_id, applied_by=operator)')
lines.append('        step3 = self.step3_export_masked(batch_id=batch_id, exported_by=operator, include_unreviewed=False, escalate_phone_issues=True)')
lines.append('        s1 = step1["import_record"]')
lines.append('        summary = {')
lines.append('            "imported": s1["new_count"],')
lines.append('            "updated_step1": s1["updated_count"],')
lines.append('            "duplicates": s1["duplicate_count"],')
lines.append('            "reviews_applied": step2["updated"],')
lines.append('            "exported": step3["exported_count"],')
lines.append('            "skipped": step3["skipped_count"],')
lines.append('            "phone_issues": step3["phone_issue_count"],')
lines.append('            "source_summary": s1.get("metadata", {}).get("source_summary", {}),')
lines.append('        }')
lines.append('        return {"batch_id": batch_id, "workflow": "three_step_complete", "steps": [step1, step2, step3], "summary": summary}')
lines.append('')
lines.append('    def get_workflow_summary(self, batch_id):')
lines.append('        recs = self.storage.list_recommendations(batch_id=batch_id)')
lines.append('        import_records = self.storage.list_import_records(batch_id=batch_id)')
lines.append('        with_phone = [r for r in recs if r.has_unmasked_phone]')
lines.append('        reviewed = [r for r in recs if r.review_status == "reviewed"]')
lines.append('        pending_alg = [r for r in recs if r.review_status == "pending_algorithm_review"]')
lines.append('        source_breakdown = {}')
lines.append('        for record in import_records:')
lines.append('            details = record.metadata.get("item_processing_details", [])')
lines.append('            for d in details:')
lines.append('                source_breakdown[d["recommendation_id"]] = {"source_type": d["source_type"], "source_batch": d["source_batch"], "import_batch_id": record.batch_id, "imported_at": record.imported_at.isoformat(), "imported_by": record.imported_by}')
lines.append('        return {"batch_id": batch_id, "total_recommendations": len(recs), "import_records": len(import_records), "with_unmasked_phone": len(with_phone), "reviewed": len(reviewed), "pending_algorithm_review": len(pending_alg), "recommendation_ids": [r.id for r in recs], "phone_issue_ids": [r.id for r in with_phone], "source_breakdown": source_breakdown}')
lines.append('')
lines.append('    def get_import_details(self, import_record_id):')
lines.append('        record = self.storage.get_import_record(import_record_id)')
lines.append('        if not record:')
lines.append('            return {"error": "Import record not found"}')
lines.append('        item_details = record.metadata.get("item_processing_details", [])')
lines.append('        source_summary = record.metadata.get("source_summary", {})')
lines.append('        detailed_items = []')
lines.append('        for d in item_details:')
lines.append('            rec = self.storage.get_recommendation(d["recommendation_id"])')
lines.append('            info = d.copy()')
lines.append('            if rec:')
lines.append('                info["content_preview"] = rec.content[:100] if rec.content else ""')
lines.append('                info["current_version"] = rec.version')
lines.append('                info["masking_status"] = rec.masking_status')
lines.append('                info["review_status"] = rec.review_status')
lines.append('            detailed_items.append(info)')
lines.append('        labels = {"new_material": "新增材料", "current_batch_duplicate": "本次重复导入", "historical_batch_duplicate": "历史批次重复", "content_updated": "内容有更新"}')
lines.append('        return {"import_record_id": record.id, "batch_id": record.batch_id, "imported_at": record.imported_at.isoformat(), "imported_by": record.imported_by, "source_file": record.source_file, "total_items": record.item_count, "new_count": record.new_count, "duplicate_count": record.duplicate_count, "updated_count": record.updated_count, "source_summary": source_summary, "source_summary_labels": {k: labels.get(k, k) for k in source_summary.keys()}, "items": detailed_items}')
lines.append('')

with open(OUTPUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"Written {len(lines)} lines to {OUTPUT}")
