const STATUS = {
  IMPORTED: 'IMPORTED',
  SCREENSHOT_REVIEWED: 'SCREENSHOT_REVIEWED',
  PENDING_MANAGER_REVIEW: 'PENDING_MANAGER_REVIEW',
  MANAGER_APPROVED: 'MANAGER_APPROVED',
  MANAGER_REJECTED: 'MANAGER_REJECTED',
  NORMAL: 'NORMAL',
  REVERTED: 'REVERTED'
};

const STATUS_LABEL = {
  [STATUS.IMPORTED]: '已导入',
  [STATUS.SCREENSHOT_REVIEWED]: '已补看截图',
  [STATUS.PENDING_MANAGER_REVIEW]: '待基金经理复核',
  [STATUS.MANAGER_APPROVED]: '基金经理复核通过',
  [STATUS.MANAGER_REJECTED]: '基金经理复核驳回',
  [STATUS.NORMAL]: '正常',
  [STATUS.REVERTED]: '已回滚'
};

const CHANGE_TYPE = {
  T1_TO_T2_MANUAL: 'T1_TO_T2_MANUAL',
  QUANTITY_ADJUSTMENT: 'QUANTITY_ADJUSTMENT',
  AMOUNT_ADJUSTMENT: 'AMOUNT_ADJUSTMENT',
  OTHER: 'OTHER'
};

const CHANGE_TYPE_LABEL = {
  [CHANGE_TYPE.T1_TO_T2_MANUAL]: 'T+1到账手工改为T+2',
  [CHANGE_TYPE.QUANTITY_ADJUSTMENT]: '数量调整',
  [CHANGE_TYPE.AMOUNT_ADJUSTMENT]: '金额调整',
  [CHANGE_TYPE.OTHER]: '其他调整'
};

const FIELDS = {
  SETTLEMENT_DATE: 'settlement_date',
  QUANTITY: 'quantity',
  AMOUNT: 'amount'
};

const FIELD_LABEL = {
  [FIELDS.SETTLEMENT_DATE]: '到账日',
  [FIELDS.QUANTITY]: '数量',
  [FIELDS.AMOUNT]: '金额'
};

const ALLOWED_TRANSITIONS = {
  [STATUS.IMPORTED]: [STATUS.SCREENSHOT_REVIEWED, STATUS.REVERTED],
  [STATUS.SCREENSHOT_REVIEWED]: [STATUS.PENDING_MANAGER_REVIEW, STATUS.NORMAL, STATUS.IMPORTED, STATUS.REVERTED],
  [STATUS.PENDING_MANAGER_REVIEW]: [STATUS.MANAGER_APPROVED, STATUS.MANAGER_REJECTED, STATUS.SCREENSHOT_REVIEWED, STATUS.REVERTED],
  [STATUS.MANAGER_APPROVED]: [STATUS.NORMAL, STATUS.PENDING_MANAGER_REVIEW, STATUS.REVERTED],
  [STATUS.MANAGER_REJECTED]: [STATUS.SCREENSHOT_REVIEWED, STATUS.PENDING_MANAGER_REVIEW, STATUS.REVERTED],
  [STATUS.NORMAL]: [STATUS.MANAGER_APPROVED, STATUS.REVERTED],
  [STATUS.REVERTED]: [STATUS.IMPORTED]
};

module.exports = {
  STATUS,
  STATUS_LABEL,
  CHANGE_TYPE,
  CHANGE_TYPE_LABEL,
  FIELDS,
  FIELD_LABEL,
  ALLOWED_TRANSITIONS
};
