const RECALL_SOURCE_STATES = {
  HEALTHY: 'HEALTHY',
  DEGRADED: 'DEGRADED',
  CIRCUIT_BREAKER_OPEN: 'CIRCUIT_BREAKER_OPEN',
  PROBING: 'PROBING'
};

const STATE_TRANSITIONS = {
  [RECALL_SOURCE_STATES.HEALTHY]: [
    RECALL_SOURCE_STATES.DEGRADED
  ],
  [RECALL_SOURCE_STATES.DEGRADED]: [
    RECALL_SOURCE_STATES.HEALTHY,
    RECALL_SOURCE_STATES.CIRCUIT_BREAKER_OPEN
  ],
  [RECALL_SOURCE_STATES.CIRCUIT_BREAKER_OPEN]: [
    RECALL_SOURCE_STATES.PROBING
  ],
  [RECALL_SOURCE_STATES.PROBING]: [
    RECALL_SOURCE_STATES.HEALTHY,
    RECALL_SOURCE_STATES.CIRCUIT_BREAKER_OPEN
  ]
};

const DEFAULT_CONFIG = {
  failureRateThreshold: 0.3,
  consecutiveFailuresThreshold: 5,
  circuitBreakerTimeoutMs: 60000,
  probeIntervalMs: 30000,
  windowSize: 100,
  healthCheckIntervalMs: 10000
};

const REQUEST_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  TIMEOUT: 'TIMEOUT',
  SKIPPED: 'SKIPPED'
};

module.exports = {
  RECALL_SOURCE_STATES,
  STATE_TRANSITIONS,
  DEFAULT_CONFIG,
  REQUEST_STATUS
};