import type { MaterialRecord, HistoryEntry, SupplementaryNote, OpinionItem } from './types';

const uid = (s: string) => s;

const h = (p: Partial<HistoryEntry>): HistoryEntry => ({
  id: Math.random().toString(36).slice(2, 9),
  timestamp: '2026-06-05T10:00:00.000Z',
  operator: '岑工',
  field: 'status',
  fieldLabel: '审核状态',
  oldValue: 'PENDING',
  newValue: 'CONFIRMED',
  reason: '—',
  ...p,
});

const note = (p: Partial<SupplementaryNote>): SupplementaryNote => ({
  id: Math.random().toString(36).slice(2, 9),
  content: '',
  handler: '岑工',
  handledAt: '2026-06-06T09:00:00.000Z',
  process: '',
  result: 'RESOLVED',
  resultText: '',
  ...p,
});

const op = (content: string, inDisclosure: boolean, isOld: boolean): OpinionItem => ({
  id: Math.random().toString(36).slice(2, 9),
  content,
  isInDisclosure: inDisclosure,
  isOld,
  isMissed: isOld && !inDisclosure,
});

export const MOCK_RECORDS: MaterialRecord[] = [
  {
    id: uid('r001'),
    code: 'XF-F1A-0023',
    name: 'GB 23864 有机封堵泥 A级',
    type: '防火封堵',
    fireZone: 'F1-防火分区A',
    submissionDate: '2026-05-28',
    layerName: 'A-FIRE-SEAL-PENETRATION',
    status: 'PENDING',
    submitter: '施工一组 · 王建国',
    reviewer: '岑工',
    opinions: [
      op('燃烧性能等级需提供 GB 8624-2012 A级 型式检验报告', true, true),
      op('电缆穿越处封堵厚度 ≥ 240mm，需附现场测厚记录', true, false),
      op('厂家需提供近三年同类项目消防验收通过证明', false, true),
      op('提供产品 RoHS 报告（如涉及出口项目）', false, false),
    ],
    supplementaryNotes: [
      note({
        content: '厂家补寄 A级报告，日期2026-03已过期，需重新出具',
        handler: '岑工',
        handledAt: '2026-06-02T11:20:00.000Z',
        process: '电话联系厂家李经理（138xxxx）→ 确认报告于3月到期→ 要求本周内寄新报告→ 厂家表示2026-06-08前寄出',
        result: 'IN_PROGRESS',
        resultText: '待厂家重新出具报告（预计6/8到件）',
      }),
    ],
    layerAbnormality: {
      hasAbnormality: true,
      reason:
        '图层命名混乱：该材料同时出现在 `A-FIRE-SEAL-PENETRATION`、`ARCH-SEAL-GENERAL`、`MEP-HVAC-PEN` 三个图层中，且均未按BIM标准使用 `FZ-` 前缀标识所属防火分区，无法自动归属到 F1-A 分区。',
      suggestion:
        '1. 清理冗余图层，统一归属至 `FZ-F1A-FIRE-SEAL-PENETRATION`；\n2. 图层命名严格遵循《项目BIM执行标准 V3.2》第6.4节；\n3. 补绘分区边界后重新导出明细表。',
      reviewed: false,
      affectedLayers: ['A-FIRE-SEAL-PENETRATION', 'ARCH-SEAL-GENERAL', 'MEP-HVAC-PEN'],
    },
    history: [
      h({
        timestamp: '2026-05-28T15:40:00.000Z',
        operator: '系统',
        field: 'create',
        fieldLabel: '记录创建',
        oldValue: '-',
        newValue: 'F1-A · XF-F1A-0023',
        reason: '施工一组送审登记',
      }),
      h({
        timestamp: '2026-05-30T09:12:00.000Z',
        operator: '岑工',
        field: 'status',
        fieldLabel: '审核状态',
        oldValue: '待补件',
        newValue: '退回',
        reason: '初审发现型式检验报告已过期 2 个月，不符合 GB 23864 第 5.2 条强制要求',
      }),
      h({
        timestamp: '2026-06-02T14:05:00.000Z',
        operator: '岑工',
        field: 'status',
        fieldLabel: '审核状态',
        oldValue: '退回',
        newValue: '待补件',
        reason: '厂家已承诺补发有效期内报告，先挂待补件等候到件复核',
      }),
    ],
  },

  {
    id: uid('r002'),
    code: 'XF-F1B-0018',
    name: '木质隔热防火门 FM-1021 甲级',
    type: '防火门',
    fireZone: 'F1-防火分区B',
    submissionDate: '2026-05-26',
    layerName: 'FZ-F1B-DOOR-FIRE-M1',
    status: 'CONFIRMED',
    submitter: '施工三组 · 刘芳',
    reviewer: '岑工',
    opinions: [
      op('甲、乙级防火门区分标识需在门扇正面粘贴', true, true),
      op('闭门器顺序器型号需符合 GB 12955 要求', true, true),
      op('提供 3C 认证证书及对应铭牌照片', true, false),
    ],
    supplementaryNotes: [],
    layerAbnormality: {
      hasAbnormality: false,
      reason: '',
      suggestion: '',
      reviewed: true,
      affectedLayers: [],
    },
    history: [
      h({
        timestamp: '2026-05-26T10:22:00.000Z',
        operator: '系统',
        field: 'create',
        fieldLabel: '记录创建',
        oldValue: '-',
        newValue: 'F1-B · XF-F1B-0018',
        reason: '施工三组送审登记',
      }),
      h({
        timestamp: '2026-05-29T16:30:00.000Z',
        operator: '岑工',
        field: 'status',
        fieldLabel: '审核状态',
        oldValue: '待补件',
        newValue: '已确认',
        reason: '3C证书、型式检验、现场标识照片齐全，符合GB 12955-2008要求',
      }),
    ],
  },

  {
    id: uid('r003'),
    code: 'XF-F2A-0005',
    name: '特级防火卷帘 FJL-4.2×3.0 双轨双帘',
    type: '防火卷帘',
    fireZone: 'F2-防火分区A',
    submissionDate: '2026-06-01',
    layerName: 'CURTAIN-WALL-FIRE-2F-A',
    status: 'REJECTED',
    submitter: '施工二组 · 赵磊',
    reviewer: '岑工',
    opinions: [
      op('卷帘耐火极限 ≥ 3.00h，提供 GB 14102 型式检验报告', true, false),
      op('启闭速度 2~7.5 m/min，附厂家出厂检测记录', true, true),
      op('与喷淋头联动信号需提供消防联动调试记录', false, true),
      op('导轨埋入深度 ≥ 60mm，现场隐蔽工程验收单缺失', false, true),
    ],
    supplementaryNotes: [
      note({
        content: '施工方坚称已做导轨隐蔽验收，但资料找不到',
        handler: '岑工',
        handledAt: '2026-06-04T15:10:00.000Z',
        process: '1. 调取监理日志，6月1日未记载该隐蔽验收；\n2. 现场开孔抽检3处导轨，埋深分别为 48/52/45mm，均未达到60mm；\n3. 发工作联系单至施工组要求整改并重新报验。',
        result: 'ESCALATED',
        resultText: '上报项目经理发整改单，整改后重新报',
      }),
    ],
    layerAbnormality: {
      hasAbnormality: true,
      reason:
        '图层 `CURTAIN-WALL-FIRE-2F-A` 与幕墙图层前缀相同，且防火分区信息仅在图层描述中而非命名中；同时卷帘构件与幕墙竖梃构件混放于同一图层。',
      suggestion:
        '1. 拆分到独立图层 `FZ-F2A-FIRE-CURTAIN-SHUTTER`；\n2. 幕墙竖梃移回 `ARCH-CURTAINWALL-MULLION` 层；\n3. 按防火分区批量重命名现有图层。',
      reviewed: false,
      affectedLayers: ['CURTAIN-WALL-FIRE-2F-A'],
    },
    history: [
      h({
        timestamp: '2026-06-01T11:50:00.000Z',
        operator: '系统',
        field: 'create',
        fieldLabel: '记录创建',
        oldValue: '-',
        newValue: 'F2-A · XF-F2A-0005',
        reason: '施工二组送审登记',
      }),
      h({
        timestamp: '2026-06-04T17:00:00.000Z',
        operator: '岑工',
        field: 'status',
        fieldLabel: '审核状态',
        oldValue: '待补件',
        newValue: '退回',
        reason: '导轨埋深抽检不合格（45~52mm vs 要求 ≥60mm）+ 旧意见联动调试记录缺失，必须整体整改后重新报',
      }),
    ],
  },

  {
    id: uid('r004'),
    code: 'XF-F2B-0011',
    name: 'C类单片防火玻璃 12mm 非隔热',
    type: '防火玻璃',
    fireZone: 'F2-防火分区B',
    submissionDate: '2026-05-30',
    layerName: 'FZ-F2B-GLAZING-FIRE-C',
    status: 'CONFIRMED',
    submitter: '施工一组 · 王建国',
    reviewer: '岑工',
    opinions: [
      op('C类防火玻璃需满足耐火完整性 1.00h', true, true),
      op('提供 GB 15763.1 检验报告原件扫描件', true, false),
    ],
    supplementaryNotes: [],
    layerAbnormality: {
      hasAbnormality: false,
      reason: '',
      suggestion: '',
      reviewed: true,
      affectedLayers: [],
    },
    history: [
      h({
        timestamp: '2026-05-30T14:30:00.000Z',
        operator: '系统',
        field: 'create',
        fieldLabel: '记录创建',
        oldValue: '-',
        newValue: 'F2-B · XF-F2B-0011',
        reason: '施工一组送审登记',
      }),
      h({
        timestamp: '2026-06-03T10:00:00.000Z',
        operator: '岑工',
        field: 'status',
        fieldLabel: '审核状态',
        oldValue: '待补件',
        newValue: '已确认',
        reason: '检验报告齐全，规格与图纸一致',
      }),
    ],
  },

  {
    id: uid('r005'),
    code: 'XF-F3A-0002',
    name: '镀锌钢管喷淋 DN150 沟槽连接',
    type: '喷淋管',
    fireZone: 'F3-防火分区A',
    submissionDate: '2026-06-05',
    layerName: 'MEP-SPRINKLER-MAIN-3F',
    status: 'PENDING',
    submitter: '机电组 · 孙浩',
    reviewer: '岑工',
    opinions: [
      op('管材壁厚 ≥ 4.5mm，提供材质单', true, false),
      op('沟槽管件需为同一品牌配套产品', true, true),
      op('分区阀门处需设水流指示器+信号阀', false, true),
    ],
    supplementaryNotes: [],
    layerAbnormality: {
      hasAbnormality: true,
      reason:
        '图层 `MEP-SPRINKLER-MAIN-3F` 横跨F3-A与F3-B两个防火分区，分区边界处未按标准切割图层实体，无法单独统计F3-A材料量。',
      suggestion:
        '1. 在分区防火墙处（x=42.350轴）打断管道实体；\n2. 分别放置于 `FZ-F3A-MEP-SPRINKLER` 与 `FZ-F3B-MEP-SPRINKLER`；\n3. 重新导出材料表。',
      reviewed: true,
      affectedLayers: ['MEP-SPRINKLER-MAIN-3F'],
    },
    history: [
      h({
        timestamp: '2026-06-05T09:40:00.000Z',
        operator: '系统',
        field: 'create',
        fieldLabel: '记录创建',
        oldValue: '-',
        newValue: 'F3-A · XF-F3A-0002',
        reason: '机电组送审登记',
      }),
    ],
  },

  {
    id: uid('r006'),
    code: 'XF-F1A-0031',
    name: '钢板排烟风管 1200×600 δ=1.2mm',
    type: '排烟风管',
    fireZone: 'F1-防火分区A',
    submissionDate: '2026-06-03',
    layerName: 'FZ-F1A-MEP-DUCT-SMOKE',
    status: 'CONFIRMED',
    submitter: '机电组 · 孙浩',
    reviewer: '岑工',
    opinions: [
      op('排烟风管耐火极限 ≥ 1.00h，附耐火测试报告', true, true),
      op('法兰连接螺栓间距 ≤ 150mm', true, false),
    ],
    supplementaryNotes: [
      note({
        content: '初测法兰螺栓间距为165mm，超标',
        handler: '岑工',
        handledAt: '2026-06-06T13:20:00.000Z',
        process: '通知机电班组立即加密，2小时后复查：风管L3段46处法兰全部补装螺栓，实测间距132~148mm',
        result: 'RESOLVED',
        resultText: '整改合格，通过确认',
      }),
    ],
    layerAbnormality: {
      hasAbnormality: false,
      reason: '',
      suggestion: '',
      reviewed: true,
      affectedLayers: [],
    },
    history: [
      h({
        timestamp: '2026-06-03T16:10:00.000Z',
        operator: '系统',
        field: 'create',
        fieldLabel: '记录创建',
        oldValue: '-',
        newValue: 'F1-A · XF-F1A-0031',
        reason: '机电组送审登记',
      }),
      h({
        timestamp: '2026-06-05T11:00:00.000Z',
        operator: '岑工',
        field: 'status',
        fieldLabel: '审核状态',
        oldValue: '待补件',
        newValue: '待补件',
        reason: '法兰螺栓间距不达标，发整改（见备注），但状态先保留待补件，待整改复查',
      }),
      h({
        timestamp: '2026-06-06T15:45:00.000Z',
        operator: '岑工',
        field: 'status',
        fieldLabel: '审核状态',
        oldValue: '待补件',
        newValue: '已确认',
        reason: '法兰螺栓加密整改已复查合格，且耐火报告齐全',
      }),
    ],
  },

  {
    id: uid('r007'),
    code: 'XF-F3A-0008',
    name: '耐火母线槽 CMC-1600A',
    type: '电缆桥架',
    fireZone: 'F3-防火分区A',
    submissionDate: '2026-06-07',
    layerName: 'ELEC-BUSWAY-MAIN',
    status: 'PENDING',
    submitter: '机电组 · 李敏',
    reviewer: '岑工',
    opinions: [
      op('母线槽耐火时间 ≥ 2h，型式检验报告', true, false),
      op('防火分区穿越处封堵需同等级防火封堵', true, true),
      op('提供 3C 证书及一致性说明', true, false),
      op('现场需做1.5倍额定电流温升测试记录', false, true),
    ],
    supplementaryNotes: [],
    layerAbnormality: {
      hasAbnormality: true,
      reason:
        '图层 `ELEC-BUSWAY-MAIN` 内混用三个防火分区的母线槽实体，且图层名称无任何分区标识；无法通过图层过滤自动归属到 F3-A。',
      suggestion:
        '1. 按分区拆分图层：`FZ-F1A-ELEC-BUSWAY`、`FZ-F2A-ELEC-BUSWAY`、`FZ-F3A-ELEC-BUSWAY`；\n2. 图层描述中注明对应分区与电压等级。',
      reviewed: false,
      affectedLayers: ['ELEC-BUSWAY-MAIN'],
    },
    history: [
      h({
        timestamp: '2026-06-07T10:00:00.000Z',
        operator: '系统',
        field: 'create',
        fieldLabel: '记录创建',
        oldValue: '-',
        newValue: 'F3-A · XF-F3A-0008',
        reason: '机电组送审登记',
      }),
    ],
  },
];
