import { Action, Resources } from '../types';

export const INITIAL_RESOURCES: Resources = {
  food: 30,
  water: 50,
  energy: 100,
  spirit: 70,
  toolDurability: 50,
  safety: 30,
};

export const ACTIONS: Action[] = [
  {
    id: 'search_wreckage',
    name: '搜索残骸',
    description: '在沉船残骸中寻找有用的物资',
    actionPoints: 2,
    energyCost: 15,
    location: 'beach',
    requirements: {
      toolDurability: 5,
    },
    effects: {
      resources: { toolDurability: -5, spirit: 5 },
      description: '在残骸中找到了一些物资！',
    },
  },
  {
    id: 'find_water',
    name: '寻找水源',
    description: '在海滩附近寻找淡水',
    actionPoints: 2,
    energyCost: 20,
    location: 'beach',
    requirements: {},
    effects: {
      resources: { water: 10, energy: -10 },
      description: '发现了一些淡水！',
    },
  },
  {
    id: 'build_shelter',
    name: '搭建庇护所',
    description: '开始建造或升级庇护所',
    actionPoints: 3,
    energyCost: 25,
    location: 'beach',
    requirements: {
      inventory: [{ itemId: 'wood', quantity: 5 }],
    },
    effects: {
      resources: { energy: -20, spirit: 10 },
      facilityProgress: { facilityId: 'shelter', progress: 35 },
      description: '在建造庇护所上取得了进展',
    },
  },
  {
    id: 'make_fire',
    name: '取火',
    description: '尝试钻木取火',
    actionPoints: 2,
    energyCost: 20,
    location: 'beach',
    requirements: {
      inventory: [{ itemId: 'wood', quantity: 3 }, { itemId: 'tinder', quantity: 1 }],
      toolDurability: 10,
    },
    effects: {
      resources: { toolDurability: -10, spirit: 20, safety: 10 },
      facilityProgress: { facilityId: 'fire', progress: 50 },
      description: '成功生起了火堆！',
    },
  },
  {
    id: 'explore_forest',
    name: '探索森林',
    description: '深入森林，可能发现新的地点或资源',
    actionPoints: 3,
    energyCost: 25,
    location: 'forest',
    requirements: {},
    effects: {
      resources: { energy: -15, spirit: 5 },
      locationProgress: { locationId: 'forest', progress: 25 },
      description: '在森林中探索',
    },
  },
  {
    id: 'collect_wood',
    name: '采集木材',
    description: '收集建造用的木材',
    actionPoints: 2,
    energyCost: 15,
    location: 'forest',
    requirements: {
      toolDurability: 5,
    },
    effects: {
      resources: { toolDurability: -5 },
      inventory: [{ itemId: 'wood', quantity: 4 }],
      description: '收集了一些木材',
    },
  },
  {
    id: 'find_food',
    name: '寻找食物',
    description: '在森林中寻找可食用的植物或小动物',
    actionPoints: 2,
    energyCost: 20,
    location: 'forest',
    requirements: {},
    effects: {
      resources: { food: 8, energy: -10 },
      description: '找到了一些食物！',
    },
  },
  {
    id: 'find_water_forest',
    name: '寻找溪流',
    description: '在森林中寻找水源',
    actionPoints: 3,
    energyCost: 25,
    location: 'forest',
    requirements: {},
    effects: {
      resources: { water: 5, energy: -15 },
      description: '似乎听到了水流声...',
    },
  },
  {
    id: 'explore_cave',
    name: '探索洞穴',
    description: '小心地探索黑暗的洞穴',
    actionPoints: 3,
    energyCost: 30,
    location: 'cave',
    requirements: {
      resources: { energy: 40 },
    },
    effects: {
      resources: { energy: -25, spirit: -10 },
      locationProgress: { locationId: 'cave', progress: 30 },
      description: '洞穴中很黑，让人感到不安...',
    },
  },
  {
    id: 'find_water_cave',
    name: '收集洞内水',
    description: '从洞穴中的水洼收集淡水',
    actionPoints: 2,
    energyCost: 15,
    location: 'cave',
    requirements: {},
    effects: {
      resources: { water: 15, spirit: -5 },
      description: '收集到了洞穴中的淡水',
    },
  },
  {
    id: 'explore_cliff',
    name: '攀爬悬崖',
    description: '小心翼翼地爬上悬崖',
    actionPoints: 3,
    energyCost: 30,
    location: 'cliff',
    requirements: {
      resources: { energy: 50 },
      toolDurability: 10,
    },
    effects: {
      resources: { energy: -25, toolDurability: -10, spirit: 15 },
      locationProgress: { locationId: 'cliff', progress: 50 },
      description: '站在高处可以看到更远的海面...',
    },
  },
  {
    id: 'send_signal',
    name: '发送救援信号',
    description: '在悬崖顶部点燃信号火',
    actionPoints: 2,
    energyCost: 15,
    location: 'cliff',
    requirements: {
      inventory: [{ itemId: 'wood', quantity: 10 }, { itemId: 'tinder', quantity: 2 }],
      facility: { facilityId: 'fire', minLevel: 1 },
    },
    effects: {
      resources: { spirit: 20 },
      description: '信号火熊熊燃烧，希望能被船只看到...',
    },
  },
  {
    id: 'collect_water',
    name: '收集溪水',
    description: '从溪流中收集干净的淡水',
    actionPoints: 1,
    energyCost: 10,
    location: 'stream',
    requirements: {},
    effects: {
      resources: { water: 20, spirit: 10 },
      description: '收集到了清澈的溪水！',
    },
  },
  {
    id: 'set_trap',
    name: '设置陷阱',
    description: '在溪流附近设置陷阱捕获小动物',
    actionPoints: 2,
    energyCost: 15,
    location: 'stream',
    requirements: {
      inventory: [{ itemId: 'wood', quantity: 3 }],
      toolDurability: 5,
    },
    effects: {
      resources: { toolDurability: -5, food: 12 },
      description: '陷阱捕获了一些小动物！',
    },
  },
  {
    id: 'fish',
    name: '钓鱼',
    description: '在溪流中钓鱼',
    actionPoints: 2,
    energyCost: 10,
    location: 'stream',
    requirements: {
      inventory: [{ itemId: 'fishing_rod', quantity: 1 }],
    },
    effects: {
      resources: { food: 15, spirit: 5 },
      description: '钓到了几条鱼！',
    },
  },
  {
    id: 'write_journal',
    name: '写航海日志',
    description: '记录今天的经历和感受',
    actionPoints: 1,
    energyCost: 5,
    requirements: {},
    effects: {
      resources: { spirit: 10 },
      description: '写下了今天的日志，心情平静了一些',
    },
  },
  {
    id: 'rest',
    name: '休息',
    description: '坐下来休息，恢复体力',
    actionPoints: 1,
    energyCost: 0,
    requirements: {},
    effects: {
      resources: { energy: 25, spirit: 5 },
      description: '休息了一会儿，体力有所恢复',
    },
  },
  {
    id: 'repair_tools',
    name: '修理工具',
    description: '修复损坏的工具',
    actionPoints: 2,
    energyCost: 10,
    requirements: {
      inventory: [{ itemId: 'metal', quantity: 2 }],
    },
    effects: {
      resources: { toolDurability: 30, spirit: 5 },
      description: '工具修复了！',
    },
  },
  {
    id: 'plant_crops',
    name: '种植作物',
    description: '在菜园中种植粮食作物',
    actionPoints: 2,
    energyCost: 20,
    requirements: {
      inventory: [{ itemId: 'seeds', quantity: 1 }],
      facility: { facilityId: 'garden', minLevel: 1 },
    },
    effects: {
      resources: { energy: -15, spirit: 10 },
      description: '种子已播种，等待收获...',
    },
  },
];
