const fs = require('fs');
const path = require('path');

const targetPath = path.join(__dirname, 'test_full_verify.js');

const lines = [];

function add(line) {
  lines.push(line);
}

// Header and requires
add("var clearAllData = require('./src/models').clearAllData;");
add("var importDesensitizationRule = require('./src/models').importDesensitizationRule;");
add("var updateDesensitizationRule = require('./src/models').updateDesensitizationRule;");
add("var addGrayBatch = require('./src/models').addGrayBatch;");
add("var updateGrayBatch = require('./src/models').updateGrayBatch;");
add("var getDesensitizationRules = require('./src/models').getDesensitizationRules;");
add("var getGrayBatches = require('./src/models').getGrayBatches;");
add("var getInspectionRecords = require('./src/models').getInspectionRecords;");
add("var getExportResults = require('./src/models').getExportResults;");
add("var getPhoneMaskIssues = require('./src/models').getPhoneMaskIssues;");
add("var getAuditLogs = require('./src/models').getAuditLogs;");
add("var updatePhoneMaskIssue = require('./src/models').updatePhoneMaskIssue;");
add("var traceBackByTraceId = require('./src/models').traceBackByTraceId;");
add("var traceBackByRagReference = require('./src/models').traceBackByRagReference;");
add("");
add("var runInspection = require('./src/inspectionEngine').runInspection;");
add("var rerunInspection = require('./src/inspectionEngine').rerunInspection;");
add("var findValidRagMatches = require('./src/inspectionEngine').findValidRagMatches;");
add("");
add("console.log('═══════════════════ 完整端到端验证 ═══════════════════');");
add("console.log('');");
add("");
add("var passCount = 0;");
add("var failCount = 0;");
add("");
add("function assert(cond, label) {");
add("  if (cond) {");
add("    passCount++;");
add("    console.log('  [PASS] ' + label);");
add("  } else {");
add("    failCount++;");
add("    console.log('  [FAIL] ' + label);");
add("  }");
add("}");
add("");
add("var ruleAId = null;");
add("var ruleBId = null;");
add("var batch001Id = null;");
add("var batch002Id = null;");
add("var firstInspectionId = null;");
add("var secondInspectionId = null;");
add("var thirdInspectionId = null;");
add("var phoneIssues1 = null;");
add("");

// Preparation
add("console.log('━━━━━━ 准备阶段：清空数据');");
add("clearAllData();");
add("console.log('  [PASS] 清空所有历史数据');");
add("console.log('');");
add("");

// Test 0
add("console.log('━━━━━━ 测试 0：RAG 引擎单元测试');");
add("var ra = findValidRagMatches('本规则缺少RAG引用');");
add("assert(ra.validMatches.length === 0, '样例A validMatches 为空');");
add("assert(ra.negatedMatches.length >= 1, '样例A negatedMatches 非空');");
add("assert(ra.negatedMatches[0].negationReason && ra.negatedMatches[0].negationReason.indexOf('前缀') >= 0, '样例A 否定原因包含前缀');");
add("");
add("var rb = findValidRagMatches('本规则RAG引用缺失，待补充');");
add("assert(rb.validMatches.length === 0, '样例B validMatches 为空');");
add("assert(rb.negatedMatches.length >= 1, '样例B negatedMatches 非空');");
add("");
add("var rc = findValidRagMatches('引用来源：知识库第3.2.1节');");
add("assert(rc.validMatches.length >= 1, '样例C validMatches 有');");
add("assert(rc.negatedMatches.length === 0, '样例C negatedMatches 空');");
add("");
add("var rd = findValidRagMatches('/引用 只是路径标记');");
add("assert(rd.validMatches.length === 0, '样例D validMatches 空');");
add("assert(rd.negatedMatches.length === 0, '样例D negatedMatches 空');");
add("");
add("var re = findValidRagMatches('RAG引用来源：知识库第1节 同时在content里也缺少RAG引用');");
add("assert(re.validMatches.length >= 1, '样例E validMatches 有');");
add("assert(re.negatedMatches.length >= 1, '样例E negatedMatches 有');");
add("console.log('');");
add("");

// Test 1
add("console.log('━━━━━━ 测试 1：导入两条脱敏规则');");
add("var ruleA = importDesensitizationRule({");
add("  name: '客户咨询记录脱敏规则',");
add("  remark: '主流程：客户进线 记录 脱敏 归档。注意：/引用 只是路径标记',");
add("  mainProcess: '1.客户进线\\n2.记录\\n3.脱敏\\n4./引用 只是路径标记不是标注RAG引用\\n5.存储',");
add("  content: '说明：本规则缺少RAG引用，待算法同事核查后补充来源。测试手机号1：13600136000（故意漏遮）。测试手机号2：在备注里的 13700137000（漏遮）'");
add("}, '算法运营实习生');");
add("ruleAId = ruleA.id;");
add("assert(ruleA.name === '客户咨询记录脱敏规则', '规则A 导入成功');");
add("assert(ruleA.versionHistory.length >= 1, '规则A 初始版本历史存在');");
add("");
add("var ruleB = importDesensitizationRule({");
add("  name: '订单查询脱敏规则',");
add("  remark: '主流程：查询订单 拉取数据 敏感字段遮蔽',");
add("  mainProcess: '1.请求校验 2.订单查询 3.脱敏遮蔽。RAG引用来源：知识库第2.1.4节订单脱敏规范',");
add("  content: '正常规则，手机号正确遮蔽：135****2222'");
add("}, '算法运营实习生');");
add("ruleBId = ruleB.id;");
add("assert(ruleB.name === '订单查询脱敏规则', '规则B 导入成功');");
add("console.log('');");
add("");

// Test 2
add("console.log('━━━━━━ 测试 2：第一次巡检（只有规则，还没批次）');");
add("var result1 = runInspection('系统管理员');");
add("firstInspectionId = result1.inspection.id;");
add("phoneIssues1 = result1.inspection.phoneIssues;");
add("");
add("var gaps1 = result1.inspection.gaps;");
add("var gapRuleA = gaps1.find(function(g){ return g.ruleId === ruleAId && g.type === 'no_rag_evidence'; });");
add("var gapRuleB = gaps1.find(function(g){ return g.ruleId === ruleBId && g.type === 'rag_reference_found'; });");
add("");
add("assert(gapRuleA !== undefined, '规则A 应判为 no_rag_evidence');");
add("if (gapRuleA && gapRuleA.rawMaterialSnapshot) {");
add("  assert(gapRuleA.rawMaterialSnapshot.negatedMatches && gapRuleA.rawMaterialSnapshot.negatedMatches.length >= 1, '规则A negatedMatches 至少1条');");
add("} else {");
add("  assert(false, '规则A rawMaterialSnapshot 缺失');");
add("}");
add("");
add("assert(gapRuleB !== undefined, '规则B 应判为 rag_reference_found');");
add("if (gapRuleB && gapRuleB.ragMatchDetails) {");
add("  var validTexts = gapRuleB.ragMatchDetails.map(function(m){ return m.matchedText; });");
add("  var hasKb = validTexts.some(function(t){ return t.indexOf('知识库第2.1.4节') >= 0; });");
add("  var hasRagRef = validTexts.some(function(t){ return t.indexOf('RAG引用来源') >= 0; });");
add("  assert(hasKb, '规则B validMatches 匹配到知识库第2.1.4节');");
add("  assert(hasRagRef, '规则B validMatches 匹配到RAG引用来源');");
add("} else {");
add("  assert(false, '规则B ragMatchDetails 缺失');");
add("}");
add("");
add("var p136 = phoneIssues1.find(function(p){ return p.phoneNumber === '13600136000'; });");
add("var p137 = phoneIssues1.find(function(p){ return p.phoneNumber === '13700137000'; });");
add("assert(p136 !== undefined, '手机号 13600136000 被检测到');");
add("assert(p137 !== undefined, '手机号 13700137000 被检测到');");
add("assert(p136 && p136.rawMaterialSnapshot && p136.rawMaterialSnapshot.fieldName, '136手机号有 fieldName');");
add("assert(p137 && p137.rawMaterialSnapshot && p137.rawMaterialSnapshot.fieldName, '137手机号有 fieldName');");
add("assert(p136 && p136.status === 'pending_review', '136手机号状态为 pending_review');");
add("assert(p137 && p137.status === 'pending_review', '137手机号状态为 pending_review');");
add("");
add("var report1 = result1.exportResult.content;");
add("assert(report1.indexOf('否定表达') >= 0, '导出报告中含否定表达字样');");
add("console.log('');");
add("");

// Test 3
add("console.log('━━━━━━ 测试 3：导入灰度批次 GRAY-2024-001 和 GRAY-2024-002');");
add("var batch001 = addGrayBatch({");
add("  batchNo: 'GRAY-2024-001',");
add("  relatedRuleId: ruleAId,");
add("  sceneStatement: '现场说法：客户进线投诉，坐席记录时正确遮蔽了手机号138****8888。',");
add("  content: '批次说明：共50条对话，2条异常。RAG引用来源：知识库第5.3节灰度批次现场记录'");
add("}, '算法运营老唐');");
add("batch001Id = batch001.id;");
add("assert(batch001.batchNo === 'GRAY-2024-001', 'GRAY-2024-001 导入成功');");
add("");
add("var batch002 = addGrayBatch({");
add("  batchNo: 'GRAY-2024-002',");
add("  relatedRuleId: ruleAId,");
add("  sceneStatement: '现场说法：2024-Q2第二批灰度测试，客户咨询退款进度，坐席手动记录的手机号 13900139000 未自动遮蔽。此批次的RAG引用待补充。',");
add("  content: '内容正文：该批次共80条测试记录，涉及4个业务场景。复核结论：content里也有 13911139111 （漏遮），需标记。'");
add("}, '算法运营老唐');");
add("batch002Id = batch002.id;");
add("assert(batch002.batchNo === 'GRAY-2024-002', 'GRAY-2024-002 导入成功');");
add("console.log('');");
add("");

// Test 4
add("console.log('━━━━━━ 测试 4：第二次巡检（现在有两个批次了）');");
add("var result2 = runInspection('算法运营老唐');");
add("secondInspectionId = result2.inspection.id;");
add("");
add("var gaps2 = result2.inspection.gaps;");
add("var gap001 = gaps2.find(function(g){ return g.batchId === batch001Id && g.type === 'batch_rag_reference_found'; });");
add("var gap002 = gaps2.find(function(g){ return g.batchId === batch002Id && g.type === 'batch_no_rag_evidence'; });");
add("");
add("assert(gap001 !== undefined, 'GRAY-2024-001：batch_rag_reference_found');");
add("assert(gap002 !== undefined, 'GRAY-2024-002：batch_no_rag_evidence');");
add("if (gap002 && gap002.rawMaterialSnapshot) {");
add("  assert(gap002.rawMaterialSnapshot.negatedMatches && gap002.rawMaterialSnapshot.negatedMatches.length >= 1, 'GRAY-002 negatedMatches 至少1条');");
add("} else {");
add("  assert(false, 'GRAY-002 rawMaterialSnapshot 缺失');");
add("}");
add("");
add("var phoneIssues2 = result2.inspection.phoneIssues;");
add("var p1390 = phoneIssues2.find(function(p){ return p.phoneNumber === '13900139000' && p.rawMaterialSnapshot && p.rawMaterialSnapshot.fieldName === 'sceneStatement'; });");
add("var p1391 = phoneIssues2.find(function(p){ return p.phoneNumber === '13911139111' && p.rawMaterialSnapshot && p.rawMaterialSnapshot.fieldName === 'content'; });");
add("assert(p1390 !== undefined, 'GRAY-002 sceneStatement 中 13900139000 必须出现');");
add("assert(p1391 !== undefined, 'GRAY-002 content 中 13911139111 必须出现');");
add("");
add("var pendingAll = phoneIssues2.every(function(p){ return p.status === 'pending_review'; });");
add("assert(pendingAll, '所有手机号状态为 pending_review');");
add("console.log('');");
add("");

// Test 5
add("console.log('━━━━━━ 测试 5：算法同事补充规则A的RAG引用');");
add("var updatedRuleA = updateDesensitizationRule(ruleAId, {");
add("  mainProcess: '1.客户进线\\n2.记录\\n3.脱敏\\n4./引用 只是路径标记\\n5.RAG引用来源：知识库第3.2.1节脱敏处理规范\\n6.存储',");
add("  content: '说明：RAG引用已由算法同事小王补录。原测试手机号已在修复：136****6000。备注里的137****7000也已遮蔽。'");
add("}, '算法同事小王', '补录RAG引用来源，修复主流程，补全遮蔽测试手机号');");
add("");
add("assert(updatedRuleA !== null, '规则A 更新成功');");
add("assert(updatedRuleA.versionHistory && updatedRuleA.versionHistory.length >= 2, '规则A versionHistory 至少 2 条');");
add("var latestVer = updatedRuleA.versionHistory[updatedRuleA.versionHistory.length - 1];");
add("var changedFields = latestVer.changes ? latestVer.changes.map(function(c){ return c.field; }) : [];");
add("var hasMainProcess = changedFields.indexOf('mainProcess') >= 0;");
add("var hasContent = changedFields.indexOf('content') >= 0;");
add("assert(hasMainProcess, 'changes 包含 mainProcess 字段');");
add("assert(hasContent, 'changes 包含 content 字段');");
add("console.log('');");
add("");

// Test 6
add("console.log('━━━━━━ 测试 6：算法运营老唐补录 GRAY-2024-002 的 RAG 引用');");
add("var oldScene002 = batch002.sceneStatement;");
add("var newScene002 = oldScene002 + ' RAG引用来源：知识库第5.7节灰度二期现场规范';");
add("var updatedBatch002 = updateGrayBatch(batch002Id, {");
add("  sceneStatement: newScene002");
add("}, '算法运营老唐', '补录批次RAG引用来源');");
add("");
add("assert(updatedBatch002 !== null, 'GRAY-2024-002 更新成功');");
add("assert(updatedBatch002.versionHistory && updatedBatch002.versionHistory.length >= 2, 'GRAY-002 versionHistory 至少 2 条');");
add("var latestBatchVer = updatedBatch002.versionHistory[updatedBatch002.versionHistory.length - 1];");
add("assert(latestBatchVer.changeReason && latestBatchVer.changeReason.indexOf('补录批次RAG引用来源') >= 0, '修改原因可见');");
add("console.log('');");
add("");

// Test 7
add("console.log('━━━━━━ 测试 7：重跑巡检（重算）');");
add("var result3 = rerunInspection('算法运营老唐', secondInspectionId);");
add("thirdInspectionId = result3.inspection.id;");
add("");
add("var gaps3 = result3.inspection.gaps;");
add("var gapRuleANew = gaps3.find(function(g){ return g.ruleId === ruleAId && g.type === 'rag_reference_found'; });");
add("var gap002New = gaps3.find(function(g){ return g.batchId === batch002Id && g.type === 'batch_rag_reference_found'; });");
add("");
add("assert(gapRuleANew !== undefined, '规则A 现在 rag_reference_found');");
add("if (gapRuleANew) {");
add("  var negCnt = (gapRuleANew.negatedMatches || []).length;");
add("  assert(negCnt === 0, '规则A negatedMatches 为空');");
add("}");
add("");
add("assert(gap002New !== undefined, 'GRAY-2024-002 现在 batch_rag_reference_found');");
add("");
add("var phoneIssues3 = result3.inspection.phoneIssues;");
add("var phoneCount3 = phoneIssues3.length;");
add("var phoneCount1Len = phoneIssues1.length;");
add("assert(phoneCount3 < phoneCount1Len, '手机号数量显著减少');");
add("");
add("var p1390Still = phoneIssues3.find(function(p){ return p.phoneNumber === '13900139000'; });");
add("var p1391Still = phoneIssues3.find(function(p){ return p.phoneNumber === '13911139111'; });");
add("assert(p1390Still !== undefined, 'GRAY-002 的 13900139000 继续存在');");
add("assert(p1391Still !== undefined, 'GRAY-002 的 13911139111 继续存在');");
add("console.log('');");
add("");

// Test 8
add("console.log('━━━━━━ 测试 8：算法同事复核手机号');");
add("var allPhoneIssues = getPhoneMaskIssues();");
add("var pendingList = allPhoneIssues.filter(function(p){ return p.status === 'pending_review'; });");
add("assert(pendingList.length >= 3, '至少有 3 个 pending_review 手机号问题');");
add("");
add("if (pendingList.length >= 3) {");
add("  var up1 = updatePhoneMaskIssue(pendingList[0].id, {");
add("    status: 'confirmed',");
add("    reviewedBy: '算法同事小王',");
add("    reviewNote: '确认漏遮，已提交修复单'");
add("  }, '算法同事小王');");
add("  assert(up1 && up1.status === 'confirmed', '第1个手机号改为 confirmed');");
add("");
add("  var up2 = updatePhoneMaskIssue(pendingList[1].id, {");
add("    status: 'confirmed',");
add("    reviewedBy: '算法同事小李',");
add("    reviewNote: '确认漏遮，历史共出现5次'");
add("  }, '算法同事小李');");
add("  assert(up2 && up2.status === 'confirmed', '第2个手机号改为 confirmed');");
add("");
add("  assert(pendingList[2].status === 'pending_review', '第3个保留 pending_review 不动');");
add("}");
add("console.log('');");
add("");

// Test 9
add("console.log('━━━━━━ 测试 9：Trace ID 反查');");
add("var pendingAfterUpdate = getPhoneMaskIssues();");
add("var anyPhone = pendingAfterUpdate.find(function(p){ return p.traceId; });");
add("if (anyPhone) {");
add("  var traceResult = traceBackByTraceId(anyPhone.traceId);");
add("  assert(traceResult.found === true, 'traceBackByTraceId found=true');");
add("  var hasPhoneIssue = traceResult.sources.some(function(s){ return s.type === 'phone_issue' || s.type === 'phone_mask_issue_record'; });");
add("  assert(hasPhoneIssue, 'sources 至少 1 个包含 phone_issue');");
add("  var hasSnapshot = traceResult.sources.some(function(s){ return s.rawMaterialSnapshot; });");
add("  assert(hasSnapshot, 'sources 至少 1 个含 rawMaterialSnapshot');");
add("  if (traceResult.relatedRule) {");
add("    assert(traceResult.relatedRule.versionHistory !== undefined, '追溯可见 rule versionHistory');");
add("  }");
add("} else {");
add("  assert(false, '没有找到带 traceId 的手机号');");
add("}");
add("console.log('');");
add("");

// Test 10
add("console.log('━━━━━━ 测试 10：RAG 引用关键词反查');");
add("var ragTrace = traceBackByRagReference('知识库第');");
add("assert(ragTrace.matches.length >= 3, 'matches.length >= 3');");
add("var hasGapDesc = ragTrace.matches.every(function(m){ return m.gapDescription; });");
add("assert(hasGapDesc, '每个 match 有 gapDescription');");
add("var hasRuleOrBatch = ragTrace.matches.some(function(m){ return m.ruleName || m.batchNo; });");
add("assert(hasRuleOrBatch, '能反查 ruleName/batchNo');");
add("console.log('');");
add("");

// Test 11
add("console.log('━━━━━━ 测试 11：导出报告和脱敏导出结构');");
add("var allExports = getExportResults();");
add("assert(allExports.length >= 3, '导出报告数 >= 3');");
add("var lastExport = allExports[allExports.length - 1];");
add("");
add("assert(lastExport.gapsSummary !== undefined, 'gapsSummary 存在');");
add("assert(typeof lastExport.gapsSummary.ragMissing === 'number', 'gapsSummary.ragMissing 是数字');");
add("assert(typeof lastExport.gapsSummary.ragFound === 'number', 'gapsSummary.ragFound 是数字');");
add("assert(typeof lastExport.gapsSummary.other === 'number', 'gapsSummary.other 是数字');");
add("assert(typeof lastExport.gapsSummary.total === 'number', 'gapsSummary.total 是数字');");
add("");
add("assert(lastExport.phoneIssuesSummary !== undefined, 'phoneIssuesSummary 存在');");
add("assert(lastExport.phoneIssuesSummary.pending >= 1, 'pending >= 1');");
add("assert(lastExport.phoneIssuesSummary.confirmed >= 2, 'confirmed >= 2');");
add("assert(lastExport.phoneIssuesSummary.items.length >= 3, 'items.length >= 3');");
add("");
add("var items = lastExport.phoneIssuesSummary.items;");
add("var allItemsValid = items.every(function(it){");
add("  return it.traceId && it.phoneNumber && it.fieldName && it.status && it.sourceName && it.context !== undefined;");
add("});");
add("assert(allItemsValid, 'items 每个含完整字段');");
add("");
add("var reportContent = lastExport.content;");
add("assert(reportContent.indexOf('RAG 引用缺失巡检报告') >= 0, '报告含标题');");
add("assert(reportContent.indexOf('Trace ID') >= 0, '报告含 Trace ID');");
add("assert(reportContent.indexOf('手机号漏遮') >= 0, '报告含手机号漏遮');");
add("assert(reportContent.indexOf('待算法同事复核') >= 0, '报告含待算法同事复核');");
add("");
add("var hasGRAY002Phone = reportContent.indexOf('13900139000') >= 0 || reportContent.indexOf('13911139111') >= 0 || reportContent.indexOf('GRAY-2024-002') >= 0;");
add("assert(hasGRAY002Phone, '报告里能看到 GRAY-2024-002 相关');");
add("console.log('');");
add("");

// Test 12
add("console.log('━━━━━━ 测试 12：完整数据汇总打印');");
add("var rules = getDesensitizationRules();");
add("var rulesWithVer = rules.filter(function(r){ return r.versionHistory && r.versionHistory.length >= 2; });");
add("var batches = getGrayBatches();");
add("var inspections = getInspectionRecords();");
add("var exportsList = getExportResults();");
add("var phones = getPhoneMaskIssues();");
add("var audits = getAuditLogs();");
add("");
add("var pendingCnt = phones.filter(function(p){ return p.status === 'pending_review'; }).length;");
add("var confirmedCnt = phones.filter(function(p){ return p.status === 'confirmed'; }).length;");
add("");
add("console.log('');");
add("console.log('┌─────────────────────────────────────────────────────┐');");
add("console.log('│              完整数据汇总表                         │');");
add("console.log('├─────────────────────────────────────────────────────┤');");
add("console.log('│ 规则条数                          │ ' + rules.length + ' 条');");
add("console.log('│ 含版本历史(>=2)的规则条数         │ ' + rulesWithVer.length + ' 条');");
add("console.log('│ 灰度批次数                        │ ' + batches.length + ' 条');");
add("console.log('│ 巡检次数                          │ ' + inspections.length + ' 次');");
add("assert(inspections.length >= 3, '巡检次数 >= 3');");
add("console.log('│ 导出报告数                        │ ' + exportsList.length + ' 份');");
add("assert(exportsList.length >= 3, '导出报告数 >= 3');");
add("console.log('│ 手机号问题总数                    │ ' + phones.length + ' 个');");
add("console.log('│   - pending_review 待复核         │ ' + pendingCnt + ' 个');");
add("console.log('│   - confirmed    已确认           │ ' + confirmedCnt + ' 个');");
add("console.log('│ 审计日志条数                      │ ' + audits.length + ' 条');");
add("assert(audits.length >= 10, '审计日志条数 >= 10');");
add("console.log('└─────────────────────────────────────────────────────┘');");
add("console.log('');");
add("");

// Summary - 9 core validations
add("console.log('━━━━━━ 9个 核心验证总结');");
add("console.log('');");
add("console.log('1. 缺少RAG引用字样不被判为有引用，而是作为缺失保留给算法同事');");
add("console.log('   -> 测试0/测试2验证：negatedMatches 机制正确识别否定前缀');");
add("console.log('');");
add("console.log('2. GRAY-2024-002 的 sceneStatement 手机号 13900139000 进入脱敏导出');");
add("console.log('   -> 测试4验证：fieldName=sceneStatement 的 13900139000 被正确检测');");
add("console.log('');");
add("console.log('3. GRAY-2024-002 的 content 手机号 13911139111 也进入脱敏导出');");
add("console.log('   -> 测试4验证：fieldName=content 的 13911139111 被正确检测');");
add("console.log('');");
add("console.log('4. 手机号漏遮保持 pending_review 留待算法同事复核，不急着归正常');");
add("console.log('   -> 测试4/测试8验证：默认状态pending_review，2个confirmed+1个保留pending');");
add("console.log('');");
add("console.log('5. Trace ID 能反查到：原始材料 + 改前/改后 + 修改人 + 修改原因');");
add("console.log('   -> 测试9验证：traceBackByTraceId 返回完整追溯信息');");
add("console.log('');");
add("console.log('6. RAG 引用关键词能反查：匹配内容 + 原始材料');");
add("console.log('   -> 测试10验证：traceBackByRagReference 返回多个match');");
add("console.log('');");
add("console.log('7. 负责人补看补录的历史：versionHistory 记录原话、修改人、修改原因');");
add("console.log('   -> 测试5/测试6验证：versionHistory>=2，含changes/modifiedBy/changeReason');");
add("console.log('');");
add("console.log('8. 导出/报告不停在总数，每个手机号有完整字段信息');");
add("console.log('   -> 测试11验证：phoneIssuesSummary.items 每个都有完整字段');");
add("console.log('');");
add("console.log('9. 不只用 138/GRAY-001：也用了 136/137/1390/1391 / GRAY-002 证明');");
add("console.log('   -> 全流程覆盖：规则A(136/137)、GRAY-001(138已遮蔽)、GRAY-002(1390/1391)');");
add("console.log('');");
add("");
add("console.log('═══════════════════════════════════════════════════════');");
add("console.log('  总统计: PASS=' + passCount + '  FAIL=' + failCount);");
add("console.log('═══════════════════════════════════════════════════════');");

const content = lines.join('\n');
fs.writeFileSync(targetPath, content, 'utf8');
console.log('OK: wrote ' + lines.length + ' lines, ' + content.length + ' chars to ' + targetPath);
