const fs = require('fs');

const lines = [];

lines.push("const {");
lines.push("  generateId,");
lines.push("  saveInspectionRecord,");
lines.push("  saveExportResult,");
lines.push("  savePhoneMaskIssue,");
lines.push("  addAuditLog,");
lines.push("  getDesensitizationRules,");
lines.push("  getGrayBatches");
lines.push("} = require('./models');");
lines.push("");
lines.push("");
lines.push("const PHONE_REGEX = /1[3-9]\\d{9}/g;");
lines.push("");
lines.push("const RAG_PATTERNS = [");
lines.push("  /RAG[ _-]*(引用|证据|来源|出处|reference|cite)/i,");
lines.push("  /(引用|证据|来源|出处)[ _-]*RAG/i,");
lines.push("  /知识库第[^\\s]+节/,");
lines.push("  /引用来源[：:]/,");
lines.push("  /RAG[ _-]*reference/i,");
lines.push("  /\\*RAG\\*/,");
lines.push("  /【RAG[ _-]*(引用|证据|来源|出处)】/,");
lines.push("  /「RAG[ _-]*(引用|证据|来源|出处)」/,");
lines.push("  /RAG[ _-]*引用[ _-]*来源/i,");
lines.push("  /(引用|证据|来源|出处)[ _-]*\\[RAG\\]/i");
lines.push("];");
lines.push("");
lines.push("const NEG_PREFIX = [");
lines.push("  '不是', '并非', '非', '缺少', '缺失',");
lines.push("  '未标注', '未添加', '未填写', '无', '没有',");
lines.push("  '待补充', '尚未', '暂未', '待补', '需补充',");
lines.push("  '未找到', '未附上', '未提供', '缺乏', '未包含',");
lines.push("  '未说明'");
lines.push("];");
lines.push("");
lines.push("const NEG_SUFFIX = [");
lines.push("  /缺失/,");
lines.push("  /待补充/,");
lines.push("  /未标注/,");
lines.push("  /未提供/,");
lines.push("  /待补/");
lines.push("];");
lines.push("");
lines.push("function isNegatedRagMatch(mt, ft, mi) {");
lines.push("  var pfx = ft.substring(Math.max(0, mi - 24), mi);");
lines.push("  for (var i = 0; i < NEG_PREFIX.length; i++) {");
lines.push("    if (pfx.indexOf(NEG_PREFIX[i]) >= 0) {");
lines.push("      return { negated: true, reason: '前缀含' + NEG_PREFIX[i] };");
lines.push("    }");
lines.push("  }");
lines.push("  var sfx = ft.substring(mt.length + mi, Math.min(ft.length, mi + mt.length + 24));");
lines.push("  for (var j = 0; j < NEG_SUFFIX.length; j++) {");
lines.push("    if (NEG_SUFFIX[j].test(sfx)) {");
lines.push("      return { negated: true, reason: '后缀匹配' };");
lines.push("    }");
lines.push("  }");
lines.push("  return { negated: false };");
lines.push("}");
lines.push("");
lines.push("function getMatchContext(text, matchIndex, matchLength, contextLen) {");
lines.push("  if (contextLen === undefined) contextLen = 30;");
lines.push("  if (!text || matchIndex === undefined) return null;");
lines.push("  var start = Math.max(0, matchIndex - contextLen);");
lines.push("  var end = Math.min(text.length, matchIndex + matchLength + contextLen);");
lines.push("  var prefix = text.substring(start, matchIndex);");
lines.push("  var suffix = text.substring(matchIndex + matchLength, end);");
lines.push("  if (start > 0) prefix = '...' + prefix;");
lines.push("  if (end < text.length) suffix = suffix + '...';");
lines.push("  return {");
lines.push("    prefix: prefix,");
lines.push("    matched: text.substring(matchIndex, matchIndex + matchLength),");
lines.push("    suffix: suffix,");
lines.push("    fullContext: prefix + text.substring(matchIndex, matchIndex + matchLength) + suffix");
lines.push("  };");
lines.push("}");
lines.push("");
lines.push("function findValidRagMatches(text) {");
lines.push("  var valid = [];");
lines.push("  var neg = [];");
lines.push("  if (!text) return { validMatches: valid, negatedMatches: neg };");
lines.push("  for (var pi = 0; pi < RAG_PATTERNS.length; pi++) {");
lines.push("    var pat = RAG_PATTERNS[pi];");
lines.push("    var rx = new RegExp(pat.source, pat.flags.indexOf('g') >= 0 ? pat.flags : pat.flags + 'g');");
lines.push("    var m;");
lines.push("    while ((m = rx.exec(text)) !== null) {");
lines.push("      var base = {");
lines.push("        patternIndex: pi,");
lines.push("        matchedText: m[0],");
lines.push("        matchIndex: m.index,");
lines.push("        context: getMatchContext(text, m.index, m[0].length)");
lines.push("      };");
lines.push("      var ck = isNegatedRagMatch(m[0], text, m.index);");
lines.push("      if (ck.negated) {");
lines.push("        base.negationReason = ck.reason;");
lines.push("        neg.push(base);");
lines.push("      } else {");
lines.push("        valid.push(base);");
lines.push("      }");
lines.push("      if (m.index === rx.lastIndex) rx.lastIndex++;");
lines.push("    }");
lines.push("  }");
lines.push("  return { validMatches: valid, negatedMatches: neg };");
lines.push("}");
lines.push("");
lines.push("function detectPhoneNumbers(text) {");
lines.push("  if (!text) return [];");
lines.push("  var matches = text.match(PHONE_REGEX);
lines.push("  return matches || [];");
lines.push("}");
lines.push("");
lines.push("function isPhoneMasked(phone) {");
lines.push("  return phone.includes('*') || phone.includes('x') || phone.includes('X');");
lines.push("}");
lines.push("");
lines.push("function analyzeCitationGaps(rule, batches) {");
lines.push("  var gaps = [];");
lines.push("  var checkedFields = ['remark', 'mainProcess', 'content'];");
lines.push("  var allTexts = [];");
lines.push("  checkedFields.forEach(function(field) {");
lines.push("    if (rule[field]) {");
lines.push("      allTexts.push({ field: field, text: rule[field] });");
lines.push("    }");
lines.push("  });");
lines.push("  var combinedText = allTexts.map(function(t) { return t.text; }).join('\\n');
lines.push("  var ragResult = findValidRagMatches(combinedText);
lines.push("  var traceId = generateId('trace');
lines.push("  if (ragResult.validMatches.length > 0) {");
lines.push("    gaps.push({");
lines.push("      id: generateId('gap'),");
lines.push("      traceId: traceId,");
lines.push("      type: 'rag_reference_found',");
lines.push("      ruleId: rule.id,");
lines.push("      ruleName: rule.name,");
lines.push("      description: '规则「' + rule.name + '」已找到 RAG 引用标注',");
lines.push("      ragMatchDetails: ragResult.validMatches,");
lines.push("      negatedMatches: ragResult.negatedMatches,");
lines.push("      rawMaterialSnapshot: {");
lines.push("        ruleId: rule.id,");
lines.push("        ruleName: rule.name,");
lines.push("        checkedFields: checkedFields,");
lines.push("        fieldTexts: allTexts.reduce(function(acc, t) { acc[t.field] = t.text; return acc; }, {}),");
lines.push("        negatedMatches: ragResult.negatedMatches");
lines.push("      }");
lines.push("    });");
lines.push("  } else {");
lines.push("    gaps.push({");
lines.push("      id: generateId('gap'),");
lines.push("      traceId: traceId,");
lines.push("      type: 'no_rag_evidence',");
lines.push("      ruleId: rule.id,");
lines.push("      ruleName: rule.name,");
lines.push("      description: '规则「' + rule.name + '」缺少 RAG 引用来源标注，待算法同事核查后补充',");
lines.push("      ragMatchDetails: [],");
lines.push("      negatedMatches: ragResult.negatedMatches,");
lines.push("      rawMaterialSnapshot: {");
lines.push("        ruleId: rule.id,");
lines.push("        ruleName: rule.name,");
lines.push("        checkedFields: checkedFields,");
lines.push("        fieldTexts: allTexts.reduce(function(acc, t) { acc[t.field] = t.text; return acc; }, {}),");
lines.push("        negatedMatches: ragResult.negatedMatches");
lines.push("      }");
lines.push("    });");
lines.push("  }");
lines.push("  if (batches && batches.length > 0) {");
lines.push("    batches.forEach(function(batch) {");
lines.push("      if (batch.relatedRuleId !== rule.id) return;");
lines.push("      var batchFields = ['sceneStatement', 'content'];");
lines.push("      var batchTexts = [];");
lines.push("      batchFields.forEach(function(field) {");
lines.push("        if (batch[field]) {");
lines.push("          batchTexts.push({ field: field, text: batch[field] });");
lines.push("        }");
lines.push("      });");
lines.push("      var batchCombined = batchTexts.map(function(t) { return t.text; }).join('\\n');
lines.push("      var batchRagResult = findValidRagMatches(batchCombined);
lines.push("      var batchTraceId = generateId('trace');
lines.push("      if (batchRagResult.validMatches.length > 0) {");
lines.push("        gaps.push({");
lines.push("          id: generateId('gap'),");
lines.push("          traceId: batchTraceId,");
lines.push("          type: 'batch_rag_reference_found',");
lines.push("          ruleId: rule.id,");
lines.push("          ruleName: rule.name,");
lines.push("          batchId: batch.id,");
lines.push("          batchNo: batch.batchNo,");
lines.push("          description: '灰度批次「' + batch.batchNo + '」已找到 RAG 引用标注',");
lines.push("          ragMatchDetails: batchRagResult.validMatches,");
lines.push("          negatedMatches: batchRagResult.negatedMatches,");
lines.push("          rawMaterialSnapshot: {");
lines.push("            batchId: batch.id,");
lines.push("            batchNo: batch.batchNo,");
lines.push("            relatedRuleId: rule.id,");
lines.push("            checkedFields: batchFields,");
lines.push("            fieldTexts: batchTexts.reduce(function(acc, t) { acc[t.field] = t.text; return acc; }, {}),");
lines.push("            negatedMatches: batchRagResult.negatedMatches");
lines.push("          }");
lines.push("        });");
lines.push("      } else {");
lines.push("        gaps.push({");
lines.push("          id: generateId('gap'),");
lines.push("          traceId: batchTraceId,");
lines.push("          type: 'batch_no_rag_evidence',");
lines.push("          ruleId: rule.id,");
lines.push("          ruleName: rule.name,");
lines.push("          batchId: batch.id,");
lines.push("          batchNo: batch.batchNo,");
lines.push("          description: '灰度批次「' + batch.batchNo + '」缺少 RAG 引用来源标注，待算法同事核查后补充',");
lines.push("          ragMatchDetails: [],");
lines.push("          negatedMatches: batchRagResult.negatedMatches,");
lines.push("          rawMaterialSnapshot: {");
lines.push("            batchId: batch.id,");
lines.push("            batchNo: batch.batchNo,");
lines.push("            relatedRuleId: rule.id,");
lines.push("            checkedFields: batchFields,");
lines.push("            fieldTexts: batchTexts.reduce(function(acc, t) { acc[t.field] = t.text; return acc; }, {}),");
lines.push("            negatedMatches: batchRagResult.negatedMatches");
lines.push("          }");
lines.push("        });");
lines.push("      }");
lines.push("    });");
lines.push("  }");
lines.push("  return gaps;");
lines.push("}");
lines.push("");
lines.push("function checkPhoneMasking(text, sourceType, sourceId, sourceName, extraMeta) {");
lines.push("  var issues = [];");
lines.push("  if (!text) return issues;");
lines.push("  var remainingText = text;");
lines.push("  var globalOffset = 0;");
lines.push("  while (true) {");
lines.push("    var matches = remainingText.match(PHONE_REGEX);
lines.push("    if (!matches || matches.length === 0) break;");
lines.push("    var phone = matches[0];");
lines.push("    var idxInRemaining = remainingText.indexOf(phone);");
lines.push("    var absoluteIndex = globalOffset + idxInRemaining;");
lines.push("    if (!isPhoneMasked(phone)) {");
lines.push("      var traceId = generateId('trace');
lines.push("      var ctx = getMatchContext(text, absoluteIndex, phone.length);
lines.push("      var fieldName = extraMeta && extraMeta.fieldName ? extraMeta.fieldName : 'unknown';
lines.push("      var issue = {");
lines.push("        id: generateId('phone'),");
lines.push("        traceId: traceId,");
lines.push("        phoneNumber: phone,");
lines.push("        sourceType: sourceType,");
lines.push("        sourceId: sourceId,");
lines.push("        sourceName: sourceName,");
lines.push("        status: 'pending_review',");
lines.push("        detectedAt: new Date().toISOString(),");
lines.push("        context: ctx,");
lines.push("        matchIndex: absoluteIndex,");
lines.push("        note: '检测到未脱敏手机号，待算法同事复核',");
lines.push("        rawMaterialSnapshot: {");
lines.push("          sourceType: sourceType,");
lines.push("          sourceId: sourceId,");
lines.push("          sourceName: sourceName,");
lines.push("          fieldName: fieldName,");
lines.push("          originalText: text,");
lines.push("          matchedPhone: phone,");
lines.push("          matchIndex: absoluteIndex,");
lines.push("          context: ctx");
lines.push("        }");
lines.push("      };");
lines.push("      issues.push(issue);");
lines.push("    }");
lines.push("    remainingText = remainingText.substring(idxInRemaining + phone.length);
lines.push("    globalOffset = absoluteIndex + phone.length;");
lines.push("  }");
lines.push("  return issues;");
lines.push("}");
lines.push("");
lines.push("function generateFriendlyReport(inspection) {");
lines.push("  var lines = [];");
lines.push("  lines.push('═══════════════════════════════════════════════════════');");
lines.push("  lines.push('  RAG 引用缺失巡检报告');");
lines.push("  lines.push('═══════════════════════════════════════════════════════');");
lines.push("  lines.push('');");
lines.push("  lines.push('巡检 ID: ' + inspection.id);");
lines.push("  lines.push('执行时间: ' + inspection.createdAt);");
lines.push("  lines.push('执行人: ' + inspection.operator);");
lines.push("  if (inspection.options && inspection.options.rerunFrom) {");
lines.push("    lines.push('重跑来源: ' + inspection.options.rerunFrom);");
lines.push("  }");
lines.push("  lines.push('');");
lines.push("  var ragMissing = inspection.gaps.filter(function(g) {");
lines.push("    return g.type === 'no_rag_evidence' || g.type === 'batch_no_rag_evidence';");
lines.push("  });");
lines.push("  var ragFound = inspection.gaps.filter(function(g) {");
lines.push("    return g.type === 'rag_reference_found' || g.type === 'batch_rag_reference_found';");
lines.push("  });");
lines.push("  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');");
lines.push("  lines.push('📊 巡检结果汇总');");
lines.push("  lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');");
lines.push("  lines.push('  🔴 RAG 引用缺失: ' + ragMissing.length + ' 个');");
lines.push("  lines.push('  🟢 RAG 引用已存在: ' + ragFound.length + ' 个');");
lines.push("  lines.push('  📱 手机号漏遮: ' + inspection.phoneIssues.length + ' 个');");
lines.push("  lines.push('');");
lines.push("  if (ragMissing.length > 0) {");
lines.push("    lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');");
lines.push("    lines.push('🔴 RAG 引用缺失明细');");
lines.push("    lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');");
lines.push("    ragMissing.forEach(function(gap, idx) {");
lines.push("      lines.push('');");
lines.push("      lines.push('  ' + (idx + 1) + '. ' + gap.description);");
lines.push("      lines.push('     Trace ID: ' + gap.traceId);");
lines.push("      if (gap.negatedMatches && gap.negatedMatches.length > 0) {");
lines.push("        lines.push('     ⚠️  检测到否定表达（以下匹配被排除）:');");
lines.push("        gap.negatedMatches.forEach(function(nm) {");
lines.push("          lines.push('        - \"' + nm.matchedText + '\" (' + nm.negationReason + ')');");
lines.push("          if (nm.context) {");
lines.push("            lines.push('          上下文: ' + nm.context.fullContext);");
lines.push("          }");
lines.push("        });");
lines.push("      }");
lines.push("      if (gap.rawMaterialSnapshot && gap.rawMaterialSnapshot.checkedFields) {");
lines.push("        lines.push('     已检查字段: ' + gap.rawMaterialSnapshot.checkedFields.join(', '));");
lines.push("      }");
lines.push("    });");
lines.push("    lines.push('');");
lines.push("  }");
lines.push("  if (ragFound.length > 0) {");
lines.push("    lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');");
lines.push("    lines.push('🟢 RAG 引用已存在明细');");
lines.push("    lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');");
lines.push("    ragFound.forEach(function(gap, idx) {");
lines.push("      lines.push('');");
lines.push("      lines.push('  ' + (idx + 1) + '. ' + gap.description);");
lines.push("      lines.push('     Trace ID: ' + gap.traceId);");
lines.push("      if (gap.ragMatchDetails && gap.ragMatchDetails.length > 0) {");
lines.push("        lines.push('     匹配到的引用:');");
lines.push("        gap.ragMatchDetails.forEach(function(m) {");
lines.push("          lines.push('        - \"' + m.matchedText + '\"');");
lines.push("          if (m.context) {");
lines.push("            lines.push('          上下文: ' + m.context.fullContext);");
lines.push("          }");
lines.push("        });");
lines.push("      }");
lines.push("    });");
lines.push("    lines.push('');");
lines.push("  }");
lines.push("  if (inspection.phoneIssues.length > 0) {");
lines.push("    lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');");
lines.push("    lines.push('📱 手机号漏遮明细（待算法同事复核）');");
lines.push("    lines.push('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');");
lines.push("    inspection.phoneIssues.forEach(function(issue, idx) {");
lines.push("      lines.push('');");
lines.push("      lines.push('  ' + (idx + 1) + '. 📱 ' + issue.phoneNumber);");
lines.push("      lines.push('     Trace ID: ' + issue.traceId);");
lines.push("      lines.push('     来源: ' + issue.sourceName);");
lines.push("      if (issue.rawMaterialSnapshot && issue.rawMaterialSnapshot.fieldName) {");
lines.push("        lines.push('     字段名: ' + issue.rawMaterialSnapshot.fieldName);");
lines.push("      }");
lines.push("      lines.push('     状态: ' + (issue.status === 'pending_review' ? '⏳ 待算法同事复核' : '✅ 已确认'));");
lines.push("      if (issue.context) {");
lines.push("        lines.push('     上下文: ' + issue.context.fullContext);");
lines.push("      }");
lines.push("    });");
lines.push("    lines.push('');");
lines.push("  }");
lines.push("  lines.push('═══════════════════════════════════════════════════════');");
lines.push("  lines.push('  报告结束');");
lines.push("  lines.push('═══════════════════════════════════════════════════════');");
lines.push("  return lines.join('\\n');");
lines.push("}");
lines.push("");
lines.push("function runInspection(operator, options) {");
lines.push("  if (!options) options = {};");
lines.push("  var rules = getDesensitizationRules();");
lines.push("  var batches = getGrayBatches();");
lines.push("  var allGaps = [];");
lines.push("  var allPhoneIssues = [];");
lines.push("  rules.forEach(function(rule) {");
lines.push("    var ruleGaps = analyzeCitationGaps(rule, batches);");
lines.push("    allGaps.push.apply(allGaps, ruleGaps);");
lines.push("    var ruleFields = [");
lines.push("      { field: 'remark', text: rule.remark },");
lines.push("      { field: 'mainProcess', text: rule.mainProcess },");
lines.push("      { field: 'content', text: rule.content }");
lines.push("    ];");
lines.push("    ruleFields.forEach(function(rf) {");
lines.push("      if (rf.text) {");
lines.push("        var issues = checkPhoneMasking(rf.text, 'rule', rule.id, rule.name, { fieldName: rf.field });");
lines.push("        allPhoneIssues.push.apply(allPhoneIssues, issues);");
lines.push("      }");
lines.push("    });");
lines.push("  });");
lines.push("  batches.forEach(function(batch) {");
lines.push("    var batchFields = [");
lines.push("      { field: 'sceneStatement', text: batch.sceneStatement },");
lines.push("      { field: 'content', text: batch.content }");
lines.push("    ];");
lines.push("    batchFields.forEach(function(bf) {");
lines.push("      if (bf.text) {");
lines.push("        var issues = checkPhoneMasking(bf.text, 'batch', batch.id, batch.batchNo, { fieldName: bf.field });");
lines.push("        allPhoneIssues.push.apply(allPhoneIssues, issues);");
lines.push("      }");
lines.push("    });");
lines.push("  });");
lines.push("  var inspectionId = generateId('inspection');");
lines.push("  var inspection = {");
lines.push("    id: inspectionId,");
lines.push("    operator: operator,");
lines.push("    createdAt: new Date().toISOString(),");
lines.push("    options: options,");
lines.push("    gaps: allGaps,");
lines.push("    phoneIssues: allPhoneIssues");
lines.push("  };");
lines.push("  saveInspectionRecord(inspection);");
lines.push("  allPhoneIssues.forEach(function(issue) {");
lines.push("    savePhoneMaskIssue(issue);");
lines.push("  });");
lines.push("  addAuditLog('run_inspection', operator, {");
lines.push("    inspectionId: inspectionId,");
lines.push("    gapCount: allGaps.length,");
lines.push("    phoneIssueCount: allPhoneIssues.length,");
lines.push("    options: options");
lines.push("  });");
lines.push("  var ragMissingCount = allGaps.filter(function(g) {");
lines.push("    return g.type === 'no_rag_evidence' || g.type === 'batch_no_rag_evidence';");
lines.push("  }).length;");
lines.push("  var ragFoundCount = allGaps.filter(function(g) {");
lines.push("    return g.type === 'rag_reference_found' || g.type === 'batch_rag_reference_found';");
lines.push("  }).length;");
lines.push("  var otherCount = allGaps.length - ragMissingCount - ragFoundCount;");
lines.push("  var pendingCount = allPhoneIssues.filter(function(p) { return p.status === 'pending_review'; }).length;");
lines.push("  var confirmedCount = allPhoneIssues.filter(function(p) { return p.status === 'confirmed'; }).length;");
lines.push("  var phoneItems = allPhoneIssues.map(function(p) {");
lines.push("    return {");
lines.push("      traceId: p.traceId,");
lines.push("      phoneNumber: p.phoneNumber,");
lines.push("      fieldName: p.rawMaterialSnapshot ? p.rawMaterialSnapshot.fieldName : 'unknown',");
lines.push("      status: p.status,");
lines.push("      sourceName: p.sourceName,");
lines.push("      context: p.context ? p.context.fullContext : ''");
lines.push("    };");
lines.push("  });");
lines.push("  var gapsSummary = {");
lines.push("    ragMissing: ragMissingCount,");
lines.push("    ragFound: ragFoundCount,");
lines.push("    other: otherCount,");
lines.push("    total: allGaps.length");
lines.push("  };");
lines.push("  var phoneIssuesSummary = {");
lines.push("    pending: pendingCount,");
lines.push("    confirmed: confirmedCount,");
lines.push("    total: allPhoneIssues.length,");
lines.push("    items: phoneItems");
lines.push("  };");
lines.push("  var friendlyReport = generateFriendlyReport(inspection);");
lines.push("  var exportResult = {");
lines.push("    id: generateId('export'),");
lines.push("    inspectionId: inspectionId,");
lines.push("    createdAt: new Date().toISOString(),");
lines.push("    operator: operator,");
lines.push("    content: friendlyReport,");
lines.push("    gapsSummary: gapsSummary,");
lines.push("    phoneIssuesSummary: phoneIssuesSummary");
lines.push("  };");
lines.push("  saveExportResult(exportResult);");
lines.push("  return {");
lines.push("    inspection: inspection,");
lines.push("    exportResult: exportResult,");
lines.push("    friendlyReport: friendlyReport");
lines.push("  };");
lines.push("}");
lines.push("");
lines.push("function rerunInspection(operator, previousInspectionId) {");
lines.push("  return runInspection(operator, { rerunFrom: previousInspectionId });");
lines.push("}");
lines.push("");
lines.push("module.exports = {");
lines.push("  runInspection: runInspection,");
lines.push("  rerunInspection: rerunInspection,");
lines.push("  detectPhoneNumbers: detectPhoneNumbers,");
lines.push("  isPhoneMasked: isPhoneMasked,");
lines.push("  generateFriendlyReport: generateFriendlyReport,");
lines.push("  checkPhoneMasking: checkPhoneMasking,");
lines.push("  findValidRagMatches: findValidRagMatches,");
lines.push("  isNegatedRagMatch: isNegatedRagMatch,");
lines.push("  RAG_PATTERNS: RAG_PATTERNS,");
lines.push("  NEG_PREFIX: NEG_PREFIX");
lines.push("};");

const content = lines.join('\n');
fs.writeFileSync('/Users/lzy/pro/solo/workspaces/zy72501/src/inspectionEngine.js', content, 'utf8');
console.log('SUCCESS: written', lines.length, 'lines');
