const PRICE_STATUS = {
  ACTIVE: 'active',
  EXPIRED_PENDING: 'expired_pending',
  EXPIRED: 'expired',
  RESTORE_REQUESTED: 'restore_requested'
};

const PRICE_STATUS_LABELS = {
  [PRICE_STATUS.ACTIVE]: '生效中',
  [PRICE_STATUS.EXPIRED_PENDING]: '失效待确认',
  [PRICE_STATUS.EXPIRED]: '已失效',
  [PRICE_STATUS.RESTORE_REQUESTED]: '恢复申请'
};

const EXPIRATION_REASONS = {
  TIME_EXPIRED: 'time_expired',
  PRICE_ADJUSTMENT: 'price_adjustment',
  CONTRACT_TERMINATED: 'contract_terminated',
  PRODUCT_DISCONTINUED: 'product_discontinued',
  CUSTOMER_LEVEL_CHANGED: 'customer_level_changed',
  MANUAL_INVALID: 'manual_invalid'
};

const EXPIRATION_REASON_LABELS = {
  [EXPIRATION_REASONS.TIME_EXPIRED]: '协议有效期到期',
  [EXPIRATION_REASONS.PRICE_ADJUSTMENT]: '价格策略调整',
  [EXPIRATION_REASONS.CONTRACT_TERMINATED]: '合作协议终止',
  [EXPIRATION_REASONS.PRODUCT_DISCONTINUED]: '产品停产下架',
  [EXPIRATION_REASONS.CUSTOMER_LEVEL_CHANGED]: '客户等级变更',
  [EXPIRATION_REASONS.MANUAL_INVALID]: '人工手动失效'
};

const REQUIRED_MATERIALS = {
  [EXPIRATION_REASONS.TIME_EXPIRED]: ['续约协议扫描件', '最新报价单盖章版'],
  [EXPIRATION_REASONS.PRICE_ADJUSTMENT]: ['价格调整审批表', '客户确认函'],
  [EXPIRATION_REASONS.CONTRACT_TERMINATED]: ['合同终止协议', '账款结清证明'],
  [EXPIRATION_REASONS.PRODUCT_DISCONTINUED]: ['产品替代方案', '库存清理确认'],
  [EXPIRATION_REASONS.CUSTOMER_LEVEL_CHANGED]: ['等级变更审批单', '新等级报价表'],
  [EXPIRATION_REASONS.MANUAL_INVALID]: ['失效申请单', '审批人签字确认']
};

const VALID_TRANSITIONS = {
  [PRICE_STATUS.ACTIVE]: [PRICE_STATUS.EXPIRED_PENDING],
  [PRICE_STATUS.EXPIRED_PENDING]: [PRICE_STATUS.EXPIRED, PRICE_STATUS.ACTIVE],
  [PRICE_STATUS.EXPIRED]: [PRICE_STATUS.RESTORE_REQUESTED],
  [PRICE_STATUS.RESTORE_REQUESTED]: [PRICE_STATUS.ACTIVE, PRICE_STATUS.EXPIRED]
};

module.exports = {
  PRICE_STATUS,
  PRICE_STATUS_LABELS,
  EXPIRATION_REASONS,
  EXPIRATION_REASON_LABELS,
  REQUIRED_MATERIALS,
  VALID_TRANSITIONS
};
