import { db } from './index';
import {
  Project,
  DeviceRemark,
  RemarkHistory,
  CADPoint,
  FlipRecord,
  MaterialBatch,
  SightRecord,
  TraceLink,
  InspectionItem,
} from '@/types';

function generateId(): string {
  return Math.random().toString(36).substring(2, 11);
}

const now = new Date();
const oneDayAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000);
const twoDaysAgo = new Date(now.getTime() - 48 * 60 * 60 * 1000);
const threeDaysAgo = new Date(now.getTime() - 72 * 60 * 60 * 1000);

export const seedProjects: Project[] = [
  {
    id: 'proj-001',
    name: '国家大剧院戏剧厅座席视线分析',
    status: 'active',
    createdAt: threeDaysAgo,
    updatedAt: oneDayAgo,
    lastModifier: '王经理',
  },
  {
    id: 'proj-002',
    name: '上海文化广场主剧场视线优化',
    status: 'active',
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
    lastModifier: '李项目经理',
  },
  {
    id: 'proj-003',
    name: '广州歌剧院实验剧场',
    status: 'completed',
    createdAt: threeDaysAgo,
    updatedAt: threeDaysAgo,
    lastModifier: '张主管',
  },
];

export const seedDeviceRemarks: DeviceRemark[] = [
  {
    id: 'dev-001',
    projectId: 'proj-001',
    deviceCode: 'DEV-A-001',
    deviceName: 'A区1排1号座椅',
    content: '视线高度1100mm，靠背角度105度',
    coordinate: { x: 1250, y: 8500, z: 1100 },
    area: 'A区',
    modifier: '张工',
    modifiedAt: twoDaysAgo,
    batchId: 'batch-001',
  },
  {
    id: 'dev-002',
    projectId: 'proj-001',
    deviceCode: 'DEV-A-002',
    deviceName: 'A区1排2号座椅',
    content: '视线高度1100mm，标准座位',
    coordinate: { x: 1750, y: 8500, z: 1100 },
    area: 'A区',
    modifier: '张工',
    modifiedAt: twoDaysAgo,
    batchId: 'batch-001',
  },
  {
    id: 'dev-003',
    projectId: 'proj-001',
    deviceCode: 'DEV-B-005',
    deviceName: 'B区5排3号座椅',
    content: '视线高度1200mm，考虑前方栏杆遮挡',
    coordinate: { x: 3250, y: -6500, z: 1200 },
    area: 'B区',
    modifier: '李工',
    modifiedAt: oneDayAgo,
    batchId: 'batch-001',
  },
  {
    id: 'dev-004',
    projectId: 'proj-001',
    deviceCode: 'DEV-C-012',
    deviceName: 'C区12排8号座椅',
    content: '视线高度1150mm，无障碍座位',
    coordinate: { x: -2800, y: 5200, z: 1150 },
    area: 'C区',
    modifier: '王工程师',
    modifiedAt: oneDayAgo,
    batchId: 'batch-002',
  },
  {
    id: 'dev-005',
    projectId: 'proj-002',
    deviceCode: 'DEV-M-008',
    deviceName: '主区8排15号座椅',
    content: 'VIP区域，视线高度1180mm',
    coordinate: { x: 4500, y: 3200, z: 1180 },
    area: '主区',
    modifier: '陈设计师',
    modifiedAt: twoDaysAgo,
    batchId: 'batch-003',
  },
];

export const seedRemarkHistories: RemarkHistory[] = [
  {
    id: 'hist-001',
    remarkId: 'dev-001',
    oldContent: '视线高度1050mm，标准座位',
    newContent: '视线高度1100mm，靠背角度105度',
    oldCoordinate: { x: 1250, y: 8500, z: 1050 },
    newCoordinate: { x: 1250, y: 8500, z: 1100 },
    modifier: '张工',
    modifiedAt: oneDayAgo,
    changeReason: '根据最新人体工学标准调整视线高度',
  },
  {
    id: 'hist-002',
    remarkId: 'dev-003',
    oldContent: '视线高度1150mm，标准座位',
    newContent: '视线高度1200mm，考虑前方栏杆遮挡',
    oldCoordinate: { x: 3250, y: -6500, z: 1150 },
    newCoordinate: { x: 3250, y: -6500, z: 1200 },
    modifier: '李工',
    modifiedAt: oneDayAgo,
    changeReason: '现场勘测发现前方栏杆遮挡，抬高视线高度50mm',
  },
];

export const seedCADPoints: CADPoint[] = [
  {
    id: 'cad-001',
    projectId: 'proj-001',
    pointCode: 'PT-A-001',
    pointName: 'A区1排视点',
    x: 1250,
    y: 8500,
    z: 1100,
    source: 'AutoCAD 2024',
    batchId: 'batch-001',
    importedAt: twoDaysAgo,
    importer: '李设计师',
  },
  {
    id: 'cad-002',
    projectId: 'proj-001',
    pointCode: 'PT-A-002',
    pointName: 'A区2排视点',
    x: 1750,
    y: 8500,
    z: 1100,
    source: 'AutoCAD 2024',
    batchId: 'batch-001',
    importedAt: twoDaysAgo,
    importer: '李设计师',
  },
  {
    id: 'cad-003',
    projectId: 'proj-001',
    pointCode: 'PT-B-005',
    pointName: 'B区5排视点',
    x: 3250,
    y: 6500,
    z: 1200,
    source: 'Revit 2024',
    batchId: 'batch-001',
    importedAt: oneDayAgo,
    importer: '王设计师',
    hasFlip: true,
    flipType: 'y-flip',
    flipSource: 'cad-point',
  },
  {
    id: 'cad-004',
    projectId: 'proj-001',
    pointCode: 'PT-C-012',
    pointName: 'C区12排视点',
    x: -2800,
    y: 5200,
    z: 1150,
    source: 'AutoCAD 2024',
    batchId: 'batch-002',
    importedAt: oneDayAgo,
    importer: '李设计师',
  },
  {
    id: 'cad-005',
    projectId: 'proj-002',
    pointCode: 'PT-M-008',
    pointName: '主区8排视点',
    x: 4500,
    y: 3200,
    z: 1180,
    source: 'AutoCAD 2024',
    batchId: 'batch-003',
    importedAt: twoDaysAgo,
    importer: '陈设计师',
  },
];

export const seedFlipRecords: FlipRecord[] = [
  {
    id: 'flip-001',
    cadPointId: 'cad-003',
    projectId: 'proj-001',
    flipType: 'y-flip',
    source: 'cad-point',
    assignee: '李设计师',
    assigneeRole: 'CAD设计师',
    status: 'pending',
    remark: 'Y轴坐标符号与设备备注相反，疑似导入时坐标轴翻转',
    createdAt: oneDayAgo,
  },
];

export const seedMaterialBatches: MaterialBatch[] = [
  {
    id: 'batch-001',
    projectId: 'proj-001',
    batchNo: 'BATCH-2026-0529-001',
    checksum: 'sha256:8a7f9d2c4e1b3c5f7a9d2c4e1b3c5f7a9d2c4e1b3c5f7a9d2c4e1b3c5f7a9d2c',
    importedAt: twoDaysAgo,
    importer: '王经理',
    recordCount: 6,
  },
  {
    id: 'batch-002',
    projectId: 'proj-001',
    batchNo: 'BATCH-2026-0530-001',
    checksum: 'sha256:1b3c5f7a9d2c4e8a7f9d2c4e1b3c5f7a9d2c4e1b3c5f7a9d2c4e1b3c5f7a9d2c',
    importedAt: oneDayAgo,
    importer: '王经理',
    recordCount: 2,
  },
  {
    id: 'batch-003',
    projectId: 'proj-002',
    batchNo: 'BATCH-2026-0528-001',
    checksum: 'sha256:4e1b3c5f7a9d2c8a7f9d2c4e1b3c5f7a9d2c4e1b3c5f7a9d2c4e1b3c5f7a9d2c',
    importedAt: threeDaysAgo,
    importer: '李项目经理',
    recordCount: 2,
  },
];

export const seedSightRecords: SightRecord[] = [
  {
    id: 'sight-001',
    projectId: 'proj-001',
    batchId: 'batch-001',
    deviceCode: 'DEV-A-001',
    pointCode: 'PT-A-001',
    deviceName: 'A区1排1号座椅',
    pointName: 'A区1排视点',
    conclusion: '视线良好，无遮挡，可视角度符合标准',
    sightValue: 95.5,
    status: 'confirmed',
    isManualModified: false,
    traceSource: 'device-remark',
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: 'sight-002',
    projectId: 'proj-001',
    batchId: 'batch-001',
    deviceCode: 'DEV-A-002',
    pointCode: 'PT-A-002',
    deviceName: 'A区1排2号座椅',
    pointName: 'A区2排视点',
    conclusion: '视线良好，无遮挡，可视角度符合标准',
    sightValue: 94.2,
    status: 'confirmed',
    isManualModified: false,
    traceSource: 'device-remark',
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
  {
    id: 'sight-003',
    projectId: 'proj-001',
    batchId: 'batch-001',
    deviceCode: 'DEV-B-005',
    pointCode: 'PT-B-005',
    deviceName: 'B区5排3号座椅',
    pointName: 'B区5排视点',
    conclusion: '检测到坐标轴翻转，需确认坐标正确性后重新分析',
    sightValue: 0,
    status: 'flip-detected',
    isManualModified: false,
    traceSource: 'cad-point',
    createdAt: oneDayAgo,
    updatedAt: oneDayAgo,
  },
  {
    id: 'sight-004',
    projectId: 'proj-001',
    batchId: 'batch-002',
    deviceCode: 'DEV-C-012',
    pointCode: 'PT-C-012',
    deviceName: 'C区12排8号座椅',
    pointName: 'C区12排视点',
    conclusion: '经人工复核，视线遮挡风险已排除，调整视线高度至1150mm',
    sightValue: 88.0,
    status: 'manual-modified',
    isManualModified: true,
    traceSource: 'manual-input',
    createdAt: oneDayAgo,
    updatedAt: oneDayAgo,
    manualModifier: '王工程师',
    manualModifiedAt: oneDayAgo,
    manualReason: '无障碍座位特殊处理，根据现场实际情况调整',
  },
  {
    id: 'sight-005',
    projectId: 'proj-001',
    batchId: 'batch-002',
    deviceCode: 'DEV-C-013',
    pointCode: 'PT-C-013',
    deviceName: 'C区13排5号座椅',
    pointName: 'C区13排视点',
    conclusion: '设备备注坐标缺失，待补充完整后分析',
    sightValue: 0,
    status: 'pending',
    isManualModified: false,
    traceSource: 'device-remark',
    createdAt: oneDayAgo,
    updatedAt: oneDayAgo,
  },
  {
    id: 'sight-006',
    projectId: 'proj-002',
    batchId: 'batch-003',
    deviceCode: 'DEV-M-008',
    pointCode: 'PT-M-008',
    deviceName: '主区8排15号座椅',
    pointName: '主区8排视点',
    conclusion: 'VIP区域视线极佳，符合设计要求',
    sightValue: 98.0,
    status: 'confirmed',
    isManualModified: false,
    traceSource: 'device-remark',
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
  },
];

export const seedTraceLinks: TraceLink[] = [
  {
    id: 'trace-001',
    recordId: 'sight-001',
    sourceType: 'device-remark',
    sourceId: 'dev-001',
    sourceSnapshot: {
      deviceCode: 'DEV-A-001',
      content: '视线高度1100mm，靠背角度105度',
      coordinate: { x: 1250, y: 8500, z: 1100 },
    },
    linkType: 'primary',
  },
  {
    id: 'trace-002',
    recordId: 'sight-001',
    sourceType: 'cad-point',
    sourceId: 'cad-001',
    sourceSnapshot: {
      pointCode: 'PT-A-001',
      x: 1250,
      y: 8500,
      z: 1100,
    },
    linkType: 'secondary',
  },
  {
    id: 'trace-003',
    recordId: 'sight-003',
    sourceType: 'cad-point',
    sourceId: 'cad-003',
    sourceSnapshot: {
      pointCode: 'PT-B-005',
      x: 3250,
      y: 6500,
      z: 1200,
      hasFlip: true,
      flipType: 'y-flip',
    },
    linkType: 'primary',
  },
  {
    id: 'trace-004',
    recordId: 'sight-004',
    sourceType: 'manual-input',
    sourceId: 'manual-001',
    sourceSnapshot: {
      modifier: '王工程师',
      reason: '无障碍座位特殊处理，根据现场实际情况调整',
      originalValue: 85.0,
      modifiedValue: 88.0,
    },
    linkType: 'manual',
  },
];

export const seedInspectionItems: InspectionItem[] = [
  {
    id: 'inspect-001',
    recordId: 'sight-001',
    projectId: 'proj-001',
    category: 'confirmed',
    handlingMethod: '数据校验通过，视线分析结果准确，可直接用于施工。',
    description: 'A区1排1号座椅视线分析结果：视线值95.5%，无遮挡，符合GB/T 35647-2017标准要求。',
    isConfirmed: true,
    confirmedBy: '王经理',
    confirmedAt: oneDayAgo,
    nextStep: '无，可进入下一阶段',
    contactPerson: '张工',
    contactRole: '设备工程师',
  },
  {
    id: 'inspect-002',
    recordId: 'sight-002',
    projectId: 'proj-001',
    category: 'confirmed',
    handlingMethod: '数据校验通过，视线分析结果准确，可直接用于施工。',
    description: 'A区1排2号座椅视线分析结果：视线值94.2%，无遮挡，符合标准要求。',
    isConfirmed: true,
    confirmedBy: '王经理',
    confirmedAt: oneDayAgo,
    nextStep: '无，可进入下一阶段',
    contactPerson: '张工',
    contactRole: '设备工程师',
  },
  {
    id: 'inspect-003',
    recordId: 'sight-003',
    projectId: 'proj-001',
    category: 'pending-supplement',
    handlingMethod: '数据存在缺失或异常，需补充完整后重新分析。请联系对应责任人补全数据。',
    description: 'B区5排3号座椅检测到Y轴坐标轴翻转，CAD点位Y坐标(6500)与设备备注Y坐标(-6500)符号相反。',
    isConfirmed: false,
    nextStep: '请CAD设计师核对并修正坐标后重新导入',
    contactPerson: '李设计师',
    contactRole: 'CAD设计师',
  },
  {
    id: 'inspect-004',
    recordId: 'sight-004',
    projectId: 'proj-001',
    category: 'manual-modified',
    handlingMethod: '数据经过人工调整，需再次核对原始材料。调整原因和依据已记录在案。',
    description: 'C区12排8号座椅视线值由85.0%人工调整为88.0%，调整原因：无障碍座位特殊处理，根据现场实际情况调整。',
    isConfirmed: true,
    confirmedBy: '王经理',
    confirmedAt: oneDayAgo,
    nextStep: '已确认，保留调整记录备查',
    contactPerson: '王工程师',
    contactRole: '设备工程师',
  },
  {
    id: 'inspect-005',
    recordId: 'sight-005',
    projectId: 'proj-001',
    category: 'pending-supplement',
    handlingMethod: '数据存在缺失或异常，需补充完整后重新分析。请联系对应责任人补全数据。',
    description: 'C区13排5号座椅设备备注坐标缺失，无法进行视线分析。',
    isConfirmed: false,
    nextStep: '请设备工程师补充该座位的坐标信息',
    contactPerson: '张工',
    contactRole: '设备工程师',
  },
];

export async function seedDatabase() {
  const existingProjects = await db.projects.count();
  if (existingProjects > 0) {
    return;
  }

  await db.transaction('rw', db.tables, async () => {
    await db.projects.bulkAdd(seedProjects);
    await db.deviceRemarks.bulkAdd(seedDeviceRemarks);
    await db.remarkHistories.bulkAdd(seedRemarkHistories);
    await db.cadPoints.bulkAdd(seedCADPoints);
    await db.flipRecords.bulkAdd(seedFlipRecords);
    await db.materialBatches.bulkAdd(seedMaterialBatches);
    await db.sightRecords.bulkAdd(seedSightRecords);
    await db.traceLinks.bulkAdd(seedTraceLinks);
    await db.inspectionItems.bulkAdd(seedInspectionItems);
  });
}

export { generateId };
