import { generateId } from './index';
import type {
  BankTransaction,
  Voucher,
  Invoice,
  Contract,
  DataSource,
} from '../types';

export const generateSampleData = (
  batchId: string
): {
  transactions: BankTransaction[];
  vouchers: Voucher[];
  invoices: Invoice[];
  contracts: Contract[];
  sources: DataSource[];
} => {
  const now = Date.now();
  const sourceId1 = generateId();
  const sourceId2 = generateId();
  const sourceId3 = generateId();
  const sourceId4 = generateId();

  const transactions: BankTransaction[] = [
    {
      id: generateId(),
      batchId,
      sourceId: sourceId1,
      transactionDate: '2024-05-01',
      transactionNo: 'TXN001',
      summary: '阿里巴巴服务费',
      debitAmount: 5000,
      creditAmount: 0,
      balance: 100000,
      counterparty: '阿里巴巴云计算有限公司',
      counterpartyAccount: '1234567890123456',
      remark: '5月份云服务费用',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId1,
      transactionDate: '2024-05-02',
      transactionNo: 'TXN002',
      summary: '腾讯科技-软件许可',
      debitAmount: 3500,
      creditAmount: 0,
      balance: 96500,
      counterparty: '腾讯科技(深圳)有限公司',
      counterpartyAccount: '9876543210987654',
      remark: '年度软件许可费',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId1,
      transactionDate: '2024-05-03',
      transactionNo: 'TXN003',
      summary: '办公用品采购',
      debitAmount: 1200,
      creditAmount: 0,
      balance: 95300,
      counterparty: '得力文具销售有限公司',
      counterpartyAccount: '1111222233334444',
      remark: '',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId1,
      transactionDate: '2024-05-04',
      transactionNo: 'TXN004',
      summary: '差旅费报销-张三',
      debitAmount: 2800,
      creditAmount: 0,
      balance: 92500,
      counterparty: '张三',
      counterpartyAccount: '6666888899990000',
      remark: '北京出差',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId1,
      transactionDate: '2024-05-05',
      transactionNo: 'TXN005',
      summary: '红冲-办公用品采购',
      debitAmount: 1200,
      creditAmount: 0,
      balance: 91300,
      counterparty: '得力文具销售有限公司',
      counterpartyAccount: '1111222233334444',
      remark: '退货红冲',
      isRedFlush: true,
      originalTransactionNo: 'TXN003',
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId1,
      transactionDate: '2024-05-06',
      transactionNo: 'TXN006',
      summary: '设备采购款',
      debitAmount: 15000,
      creditAmount: 0,
      balance: 76300,
      counterparty: '联想集团有限公司',
      counterpartyAccount: '5555666677778888',
      remark: '服务器采购',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId1,
      transactionDate: '2024-05-07',
      transactionNo: 'TXN007',
      summary: '阿里巴巴服务费',
      debitAmount: 5500,
      creditAmount: 0,
      balance: 71300,
      counterparty: '阿里巴巴云计算有限公司',
      counterpartyAccount: '1234567890123456',
      remark: '另一笔服务费（金额不同）',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId1,
      transactionDate: '2024-05-08',
      transactionNo: 'TXN008',
      summary: '咨询服务费',
      debitAmount: 8500,
      creditAmount: 0,
      balance: 62800,
      counterparty: '德勤咨询有限公司',
      counterpartyAccount: '2222333344445555',
      remark: '',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const vouchers: Voucher[] = [
    {
      id: generateId(),
      batchId,
      sourceId: sourceId2,
      voucherNo: 'V202405001',
      voucherDate: '2024-05-01',
      summary: '阿里云服务费',
      debitAmount: 5000,
      creditAmount: 0,
      accountCode: '660201',
      accountName: '管理费用-服务费',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId2,
      voucherNo: 'V202405002',
      voucherDate: '2024-05-02',
      summary: '软件许可费',
      debitAmount: 3500,
      creditAmount: 0,
      accountCode: '660202',
      accountName: '管理费用-软件费',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId2,
      voucherNo: 'V202405003',
      voucherDate: '2024-05-03',
      summary: '办公用品采购',
      debitAmount: 1200,
      creditAmount: 0,
      accountCode: '660203',
      accountName: '管理费用-办公费',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId2,
      voucherNo: 'V202405004',
      voucherDate: '2024-05-04',
      summary: '差旅费用',
      debitAmount: 2800,
      creditAmount: 0,
      accountCode: '660204',
      accountName: '管理费用-差旅费',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId2,
      voucherNo: 'V202405005',
      voucherDate: '2024-05-06',
      summary: '固定资产-服务器',
      debitAmount: 15000,
      creditAmount: 0,
      accountCode: '160101',
      accountName: '固定资产-电子设备',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId2,
      voucherNo: 'V202405006',
      voucherDate: '2024-05-07',
      summary: '阿里云服务费',
      debitAmount: 4900,
      creditAmount: 0,
      accountCode: '660201',
      accountName: '管理费用-服务费',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId2,
      voucherNo: 'V202405007',
      voucherDate: '2024-05-08',
      summary: '咨询服务',
      debitAmount: 8500,
      creditAmount: 0,
      accountCode: '660205',
      accountName: '管理费用-咨询费',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId2,
      voucherNo: 'V202405008',
      voucherDate: '2024-05-09',
      summary: '办公费用',
      debitAmount: 500,
      creditAmount: 0,
      accountCode: '660203',
      accountName: '管理费用-办公费',
      isRedFlush: false,
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId2,
      voucherNo: 'V202405009',
      voucherDate: '2024-05-05',
      summary: '红冲-办公用品采购',
      debitAmount: 1200,
      creditAmount: 0,
      accountCode: '660203',
      accountName: '管理费用-办公费',
      isRedFlush: true,
      originalVoucherNo: 'V202405003',
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const invoices: Invoice[] = [
    {
      id: generateId(),
      batchId,
      sourceId: sourceId3,
      invoiceNo: 'INV001',
      invoiceCode: '1100123456',
      invoiceDate: '2024-05-01',
      amount: 4716.98,
      taxAmount: 283.02,
      totalAmount: 5000,
      counterparty: '阿里巴巴云计算有限公司',
      counterpartyTaxNo: '91330100MA27WX4J6Q',
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      batchId,
      sourceId: sourceId3,
      invoiceNo: 'INV002',
      invoiceCode: '1100123457',
      invoiceDate: '2024-05-02',
      amount: 3301.89,
      taxAmount: 198.11,
      totalAmount: 3500,
      counterparty: '腾讯科技(深圳)有限公司',
      counterpartyTaxNo: '91440300MA5DRT7X8T',
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const contracts: Contract[] = [
    {
      id: generateId(),
      batchId,
      sourceId: sourceId4,
      contractNo: 'CT2024001',
      contractName: '云服务年度框架协议',
      contractAmount: 60000,
      counterparty: '阿里巴巴云计算有限公司',
      paymentTerms: '按月支付',
      matched: false,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const sources: DataSource[] = [
    {
      id: sourceId1,
      name: '银行流水样例.xlsx',
      type: 'bank',
      importTime: now,
      fileHash: 'sample_bank_hash',
      recordCount: transactions.length,
      batchId,
    },
    {
      id: sourceId2,
      name: '凭证数据样例.xlsx',
      type: 'voucher',
      importTime: now,
      fileHash: 'sample_voucher_hash',
      recordCount: vouchers.length,
      batchId,
    },
    {
      id: sourceId3,
      name: '发票台账样例.xlsx',
      type: 'invoice',
      importTime: now,
      fileHash: 'sample_invoice_hash',
      recordCount: invoices.length,
      batchId,
    },
    {
      id: sourceId4,
      name: '合同摘要样例.xlsx',
      type: 'contract',
      importTime: now,
      fileHash: 'sample_contract_hash',
      recordCount: contracts.length,
      batchId,
    },
  ];

  return { transactions, vouchers, invoices, contracts, sources };
};
