const STATUS = {
  PENDING_ASSIGN: 'pending_assign',
  ANNOTATING: 'annotating',
  REWORKING: 'reworking',
  ACCEPTED: 'accepted',
  PENDING_MANUAL: 'pending_manual'
};

const STATUS_LABELS = {
  [STATUS.PENDING_ASSIGN]: '待分配',
  [STATUS.ANNOTATING]: '标注中',
  [STATUS.REWORKING]: '返工中',
  [STATUS.ACCEPTED]: '已验收',
  [STATUS.PENDING_MANUAL]: '待人工处理'
};

const STATUS_TRANSITIONS = {
  [STATUS.PENDING_ASSIGN]: [STATUS.ANNOTATING, STATUS.PENDING_MANUAL],
  [STATUS.ANNOTATING]: [STATUS.REWORKING, STATUS.ACCEPTED],
  [STATUS.REWORKING]: [STATUS.ACCEPTED, STATUS.PENDING_MANUAL],
  [STATUS.ACCEPTED]: [],
  [STATUS.PENDING_MANUAL]: [STATUS.PENDING_ASSIGN, STATUS.ANNOTATING, STATUS.REWORKING, STATUS.ACCEPTED]
};

const REWORK_REASONS = {
  QUALITY_ISSUE: 'quality_issue',
  MISSING_DATA: 'missing_data',
  INCORRECT_LABEL: 'incorrect_label',
  INCOMPLETE: 'incomplete',
  OTHER: 'other'
};

const REWORK_REASON_LABELS = {
  [REWORK_REASONS.QUALITY_ISSUE]: '质量问题',
  [REWORK_REASONS.MISSING_DATA]: '数据缺失',
  [REWORK_REASONS.INCORRECT_LABEL]: '标注错误',
  [REWORK_REASONS.INCOMPLETE]: '标注不完整',
  [REWORK_REASONS.OTHER]: '其他'
};

module.exports = {
  STATUS,
  STATUS_LABELS,
  STATUS_TRANSITIONS,
  REWORK_REASONS,
  REWORK_REASON_LABELS
};
