from datetime import datetime
from extensions import db

class ImportLog(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    file_type = db.Column(db.String(50), nullable=False)
    file_name = db.Column(db.String(255), nullable=False)
    import_time = db.Column(db.DateTime, default=datetime.utcnow)
    record_count = db.Column(db.Integer, default=0)
    status = db.Column(db.String(20), default='success')

class TemperatureRecord(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    batch_number = db.Column(db.String(100), nullable=False, index=True)
    probe_id = db.Column(db.String(100), nullable=False)
    location = db.Column(db.String(200))
    temperature = db.Column(db.Float, nullable=False)
    record_time = db.Column(db.DateTime, nullable=False, index=True)
    import_log_id = db.Column(db.Integer, db.ForeignKey('import_log.id'))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    __table_args__ = (db.UniqueConstraint('batch_number', 'probe_id', 'record_time'),)

class SampleTransfer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    batch_number = db.Column(db.String(100), nullable=False, index=True)
    sample_id = db.Column(db.String(100), nullable=False, index=True)
    sample_name = db.Column(db.String(200))
    from_location = db.Column(db.String(200))
    to_location = db.Column(db.String(200))
    transfer_time = db.Column(db.DateTime, nullable=False, index=True)
    transfer_person = db.Column(db.String(100))
    temperature = db.Column(db.Float)
    status = db.Column(db.String(50))
    notes = db.Column(db.Text)
    import_log_id = db.Column(db.Integer, db.ForeignKey('import_log.id'))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class AlarmRecord(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    batch_number = db.Column(db.String(100), index=True)
    probe_id = db.Column(db.String(100), nullable=False)
    location = db.Column(db.String(200))
    alarm_type = db.Column(db.String(100))
    alarm_level = db.Column(db.String(50))
    temperature = db.Column(db.Float)
    start_time = db.Column(db.DateTime, nullable=False, index=True)
    end_time = db.Column(db.DateTime)
    duration_minutes = db.Column(db.Integer)
    ack_person = db.Column(db.String(100))
    ack_time = db.Column(db.DateTime)
    description = db.Column(db.Text)
    import_log_id = db.Column(db.Integer, db.ForeignKey('import_log.id'))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class ReviewNote(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    batch_number = db.Column(db.String(100), index=True)
    sample_id = db.Column(db.String(100))
    review_time = db.Column(db.DateTime, default=datetime.utcnow)
    reviewer = db.Column(db.String(100))
    temperature_check = db.Column(db.String(50))
    packaging_check = db.Column(db.String(50))
    documentation_check = db.Column(db.String(50))
    overall_status = db.Column(db.String(50))
    comments = db.Column(db.Text)
    import_log_id = db.Column(db.Integer, db.ForeignKey('import_log.id'))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class RiskAnalysis(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    batch_number = db.Column(db.String(100), nullable=False, index=True)
    risk_type = db.Column(db.String(100), nullable=False)
    risk_level = db.Column(db.String(20), default='medium')
    description = db.Column(db.Text)
    location = db.Column(db.String(200))
    start_time = db.Column(db.DateTime)
    end_time = db.Column(db.DateTime)
    duration_minutes = db.Column(db.Integer)
    temperature = db.Column(db.Float)
    sample_ids = db.Column(db.Text)
    status = db.Column(db.String(20), default='pending')
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class ReviewConclusion(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    risk_analysis_id = db.Column(db.Integer, db.ForeignKey('risk_analysis.id'), nullable=False)
    batch_number = db.Column(db.String(100), nullable=False, index=True)
    reviewer = db.Column(db.String(100))
    review_time = db.Column(db.DateTime, default=datetime.utcnow)
    conclusion_type = db.Column(db.String(50))
    root_cause = db.Column(db.Text)
    corrective_action = db.Column(db.Text)
    preventive_action = db.Column(db.Text)
    responsibility = db.Column(db.String(200))
    deadline = db.Column(db.DateTime)
    status = db.Column(db.String(20), default='pending')
    comments = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    risk_analysis = db.relationship('RiskAnalysis', backref=db.backref('conclusions', lazy=True))

class TodoItem(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    risk_analysis_id = db.Column(db.Integer, db.ForeignKey('risk_analysis.id'), nullable=False)
    batch_number = db.Column(db.String(100), index=True)
    title = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text)
    assignee = db.Column(db.String(100))
    due_date = db.Column(db.DateTime)
    priority = db.Column(db.String(20), default='medium')
    status = db.Column(db.String(20), default='pending')
    completed_at = db.Column(db.DateTime)
    completed_by = db.Column(db.String(100))
    notes = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    risk_analysis = db.relationship('RiskAnalysis', backref=db.backref('todos', lazy=True))
