import csv
import html
from pathlib import Path
from datetime import datetime
from typing import List, Dict
from .rules import Issue
from .coverage import CoverageGap, ScreenCoverage, ScheduleCoverageAnalyzer


def generate_kdm_audit_markdown(
    issues: List[Issue],
    coverage_summary: Dict,
    coverage_by_screen: Dict[str, ScreenCoverage],
    output_path: str
):
    lines = [
        "# KDM 预检报告 / KDM Pre-Check Audit Report",
        "",
        f"**生成时间 / Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## 执行摘要 / Executive Summary",
        "",
        f"- 总场次 / Total Showtimes: {coverage_summary.get('total_shows', 0)}",
        f"- KDM 覆盖场次 / Covered Showtimes: {coverage_summary.get('covered_shows', 0)}",
        f"- 整体覆盖率 / Overall Coverage: {coverage_summary.get('overall_coverage_percentage', 0):.1f}%",
        f"- 错误数 / Errors: {coverage_summary.get('error_count', 0)}",
        f"- 警告数 / Warnings: {coverage_summary.get('warning_count', 0)}",
        f"- 分析银幕数 / Screens Analyzed: {coverage_summary.get('screens_analyzed', 0)}",
        f"- KDM 数量 / KDM Count: {coverage_summary.get('kdm_count', 0)}",
        "",
        "## 问题汇总 / Issues Summary",
        "",
    ]

    error_issues = [i for i in issues if i.severity == 'ERROR']
    warning_issues = [i for i in issues if i.severity == 'WARNING']

    if error_issues:
        lines.append("### 错误 / Errors")
        lines.append("")
        lines.append("| 严重性 | 类别 | 银幕 | 标题 | 描述 | CPL ID | 推荐操作 |")
        lines.append("|--------|------|------|------|------|--------|----------|")
        for issue in error_issues:
            lines.append(f"| {issue.severity} | {issue.category} | {issue.screen_id} | "
                        f"{issue.title} | {issue.description} | {issue.cpl_id} | "
                        f"{issue.recommended_action} |")
        lines.append("")

    if warning_issues:
        lines.append("### 警告 / Warnings")
        lines.append("")
        lines.append("| 严重性 | 类别 | 银幕 | 标题 | 描述 | CPL ID | 推荐操作 |")
        lines.append("|--------|------|------|------|------|--------|----------|")
        for issue in warning_issues:
            lines.append(f"| {issue.severity} | {issue.category} | {issue.screen_id} | "
                        f"{issue.title} | {issue.description} | {issue.cpl_id} | "
                        f"{issue.recommended_action} |")
        lines.append("")

    lines.extend([
        "## 银幕覆盖率 / Screen Coverage",
        "",
        "| 银幕 ID | 银幕名称 | 总场次 | 覆盖场次 | 覆盖率 | 问题数 |",
        "|---------|----------|--------|----------|--------|--------|",
    ])

    for screen_id, sc in coverage_by_screen.items():
        lines.append(f"| {screen_id} | {sc.screen_name} | {sc.total_shows} | "
                    f"{sc.covered_shows} | {sc.coverage_percentage:.1f}% | {len(sc.gaps)} |")

    lines.extend(["", "## 详细问题列表 / Detailed Issue List", ""])

    if not issues:
        lines.append("*未发现问题 / No issues found.*")
    else:
        for idx, issue in enumerate(issues, 1):
            lines.extend([
                f"### {idx}. [{issue.severity}] {issue.category} - {issue.title}",
                "",
                f"- **银幕 / Screen**: {issue.screen_id}",
                f"- **CPL ID**: {issue.cpl_id}",
                f"- **CPL UUID**: {issue.cpl_uuid}",
                f"- **描述 / Description**: {issue.description}",
                f"- **推荐操作 / Recommended Action**: {issue.recommended_action}",
                "",
            ])

    lines.extend([
        "---",
        "*本报告由 DCP/KDM 预检器自动生成 / Generated by DCP/KDM Pre-checker*"
    ])

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))


def generate_issues_csv(issues: List[Issue], output_path: str):
    fieldnames = [
        'severity', 'category', 'screen_id', 'title', 'description',
        'cpl_id', 'cpl_uuid', 'recommended_action'
    ]

    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for issue in issues:
            writer.writerow({
                'severity': issue.severity,
                'category': issue.category,
                'screen_id': issue.screen_id,
                'title': issue.title,
                'description': issue.description,
                'cpl_id': issue.cpl_id,
                'cpl_uuid': issue.cpl_uuid,
                'recommended_action': issue.recommended_action
            })


def generate_timeline_html(timeline_data: List[Dict], output_path: str):
    status_colors = {
        'OK': '#28a745',
        'MISSING_KDM': '#dc3545',
        'KDM_INVALID': '#ffc107',
        'UNKNOWN': '#6c757d'
    }

    status_labels = {
        'OK': 'OK',
        'MISSING_KDM': 'Missing KDM',
        'KDM_INVALID': 'KDM Invalid',
        'UNKNOWN': 'Unknown'
    }

    rows = []
    for item in timeline_data:
        status = item.get('status', 'UNKNOWN')
        color = status_colors.get(status, status_colors['UNKNOWN'])
        label = status_labels.get(status, 'Unknown')

        rows.append(f"""
        <tr>
            <td>{html.escape(item.get('screen_name', ''))}</td>
            <td>{html.escape(item.get('title', ''))}</td>
            <td>{html.escape(item.get('show_datetime', ''))}</td>
            <td>{html.escape(item.get('cpl_id', ''))}</td>
            <td><span class="status-badge" style="background-color: {color}">{html.escape(label)}</span></td>
            <td>{html.escape(item.get('details', ''))}</td>
            <td>{html.escape(item.get('kdm_title', ''))}</td>
            <td>{html.escape(item.get('kdm_valid_start', '')[:19] if item.get('kdm_valid_start') else '')}</td>
            <td>{html.escape(item.get('kdm_valid_end', '')[:19] if item.get('kdm_valid_end') else '')}</td>
        </tr>
        """)

    html_content = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KDM 放映时间线 / KDM Playback Timeline</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background: #f5f5f5;
            padding: 20px;
        }}
        .container {{
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            overflow: hidden;
        }}
        header {{
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            color: white;
            padding: 30px;
        }}
        header h1 {{
            font-size: 1.8em;
            margin-bottom: 10px;
        }}
        header p {{
            opacity: 0.8;
            font-size: 0.9em;
        }}
        .summary {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 15px;
            padding: 20px;
            background: #f8f9fa;
            border-bottom: 1px solid #eee;
        }}
        .summary-card {{
            text-align: center;
            padding: 15px;
            background: white;
            border-radius: 6px;
        }}
        .summary-card .value {{
            font-size: 2em;
            font-weight: bold;
            color: #1a1a2e;
        }}
        .summary-card .label {{
            font-size: 0.85em;
            color: #666;
            margin-top: 5px;
        }}
        .ok-count {{ color: #28a745; }}
        .error-count {{ color: #dc3545; }}
        .warning-count {{ color: #ffc107; }}
        table {{
            width: 100%;
            border-collapse: collapse;
        }}
        th {{
            background: #f8f9fa;
            padding: 12px 15px;
            text-align: left;
            font-weight: 600;
            font-size: 0.85em;
            color: #333;
            border-bottom: 2px solid #dee2e6;
            position: sticky;
            top: 0;
        }}
        td {{
            padding: 12px 15px;
            border-bottom: 1px solid #eee;
            font-size: 0.9em;
        }}
        tr:hover {{
            background: #f8f9fa;
        }}
        .status-badge {{
            display: inline-block;
            padding: 4px 10px;
            border-radius: 12px;
            color: white;
            font-size: 0.8em;
            font-weight: 500;
        }}
        .table-wrapper {{
            max-height: 600px;
            overflow-y: auto;
        }}
        footer {{
            padding: 20px;
            text-align: center;
            color: #666;
            font-size: 0.85em;
            background: #f8f9fa;
            border-top: 1px solid #eee;
        }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🎬 KDM 放映时间线 / KDM Playback Timeline</h1>
            <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </header>

        <div class="summary">
            <div class="summary-card">
                <div class="value">{len(timeline_data)}</div>
                <div class="label">Total Shows</div>
            </div>
            <div class="summary-card">
                <div class="value ok-count">{len([t for t in timeline_data if t.get('status') == 'OK'])}</div>
                <div class="label">OK</div>
            </div>
            <div class="summary-card">
                <div class="value error-count">{len([t for t in timeline_data if t.get('status') in ('MISSING_KDM', 'KDM_INVALID')])}</div>
                <div class="label">Issues</div>
            </div>
            <div class="summary-card">
                <div class="value">{len(set(t.get('screen_id') for t in timeline_data))}</div>
                <div class="label">Screens</div>
            </div>
        </div>

        <div class="table-wrapper">
            <table>
                <thead>
                    <tr>
                        <th>Screen</th>
                        <th>Title</th>
                        <th>Show Time</th>
                        <th>CPL ID</th>
                        <th>Status</th>
                        <th>Details</th>
                        <th>KDM Title</th>
                        <th>KDM Valid From</th>
                        <th>KDM Valid Until</th>
                    </tr>
                </thead>
                <tbody>
                    {''.join(rows)}
                </tbody>
            </table>
        </div>

        <footer>
            Generated by DCP/KDM Pre-checker | 影院 DCP/KDM 放映包预检器
        </footer>
    </div>
</body>
</html>
"""

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html_content)
