version: '3.8'

services:
  web_b:
    image: httpd:latest
    ports:
      - "0.0.0.0:8443:8443"
      - target: 8080
        published: ${HTTP_PORT:-8080}
        protocol: tcp
        host_ip: 0.0.0.0
