server.port=8080
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

review.storage.dir=data
review.export.dir=output
spring.main.web-application-type=servlet
