import type { Conflict, RemarkHistory, Review, ModelParams, KnowledgeLink, TrendData } from '@/types';

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

export const mockConflicts: Conflict[] = [
  {
    id: 'c001',
    sampleNumber: 'IMG-2024-00123',
    modelVersion: 'v3.2.0',
    previousModelVersion: 'v3.1.5',
    labelA: '正常商品',
    labelB: '涉黄图片',
    confidenceA: 0.72,
    confidenceB: 0.68,
    status: 'pending',
    sourceUrl: 'https://wiki.example.com/knowledge/IMG-2024-00123',
    ticketUrl: 'https://ticket.example.com/T-2024-0567',
    currentRemark: '模型升级后标签置信度发生变化，需人工复核',
    isModelVersionChanged: true,
    importBatch: 'batch-2024-06-10',
    createdAt: daysAgo(2),
    updatedAt: daysAgo(1),
  },
  {
    id: 'c002',
    sampleNumber: 'IMG-2024-00145',
    modelVersion: 'v3.2.0',
    labelA: '暴力内容',
    labelB: '正常内容',
    confidenceA: 0.85,
    confidenceB: 0.55,
    status: 'reviewing',
    sourceUrl: 'https://wiki.example.com/knowledge/IMG-2024-00145',
    currentRemark: '标注负责人正在核对线上反馈工单',
    isModelVersionChanged: false,
    importBatch: 'batch-2024-06-10',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: 'c003',
    sampleNumber: 'IMG-2024-00178',
    modelVersion: 'v3.2.0',
    previousModelVersion: 'v3.1.5',
    labelA: '广告引流',
    labelB: '正常推广',
    confidenceA: 0.62,
    confidenceB: 0.71,
    status: 'pending',
    sourceUrl: 'https://wiki.example.com/knowledge/IMG-2024-00178',
    ticketUrl: 'https://ticket.example.com/T-2024-0589',
    currentRemark: 'v3.2.0对广告识别阈值下调，导致冲突',
    isModelVersionChanged: true,
    importBatch: 'batch-2024-06-10',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },
  {
    id: 'c004',
    sampleNumber: 'IMG-2024-00201',
    modelVersion: 'v3.2.0',
    labelA: '政治敏感',
    labelB: '正常时政',
    confidenceA: 0.58,
    confidenceB: 0.63,
    status: 'resolved',
    sourceUrl: 'https://wiki.example.com/knowledge/IMG-2024-00201',
    currentRemark: '运营复核人已确认：正常时政内容，标签B正确',
    isModelVersionChanged: false,
    importBatch: 'batch-2024-06-05',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
  },
  {
    id: 'c005',
    sampleNumber: 'IMG-2024-00234',
    modelVersion: 'v3.2.0',
    previousModelVersion: 'v3.1.0',
    labelA: '低俗内容',
    labelB: '正常着装',
    confidenceA: 0.75,
    confidenceB: 0.65,
    status: 'pending',
    sourceUrl: 'https://wiki.example.com/knowledge/IMG-2024-00234',
    isModelVersionChanged: true,
    importBatch: 'batch-2024-06-12',
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: 'c006',
    sampleNumber: 'IMG-2024-00256',
    modelVersion: 'v3.2.0',
    labelA: '侵权图片',
    labelB: '正常内容',
    confidenceA: 0.88,
    confidenceB: 0.42,
    status: 'reviewing',
    sourceUrl: 'https://wiki.example.com/knowledge/IMG-2024-00256',
    ticketUrl: 'https://ticket.example.com/T-2024-0601',
    currentRemark: '正在等待版权方确认材料',
    isModelVersionChanged: false,
    importBatch: 'batch-2024-06-08',
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
  },
];

export const mockRemarkHistories: RemarkHistory[] = [
  {
    id: 'rh001',
    conflictId: 'c001',
    oldRemark: '',
    newRemark: '模型升级后标签置信度发生变化',
    operator: '系统',
    operatorRole: 'product',
    createdAt: daysAgo(2),
  },
  {
    id: 'rh002',
    conflictId: 'c001',
    oldRemark: '模型升级后标签置信度发生变化',
    newRemark: '模型升级后标签置信度发生变化，需人工复核',
    operator: '周姐',
    operatorRole: 'annotator',
    createdAt: daysAgo(1),
  },
  {
    id: 'rh003',
    conflictId: 'c003',
    oldRemark: '',
    newRemark: 'v3.2.0对广告识别阈值下调，导致冲突',
    operator: '周姐',
    operatorRole: 'annotator',
    createdAt: daysAgo(0),
  },
  {
    id: 'rh004',
    conflictId: 'c004',
    oldRemark: '',
    newRemark: '初步判断为正常时政内容',
    operator: '周姐',
    operatorRole: 'annotator',
    createdAt: daysAgo(4),
  },
  {
    id: 'rh005',
    conflictId: 'c004',
    oldRemark: '初步判断为正常时政内容',
    newRemark: '运营复核人已确认：正常时政内容，标签B正确',
    operator: '李运营',
    operatorRole: 'operator',
    createdAt: daysAgo(2),
  },
];

export const mockReviews: Review[] = [
  {
    id: 'r001',
    conflictId: 'c001',
    reason: '模型版本从v3.1.5升级到v3.2.0，涉黄识别模型的特征权重发生调整，同一图片在不同版本下产生了标签差异。样本编号IMG-2024-00123对应的图片内容为边缘场景。',
    existingMaterials: ['知识库原始链接', 'v3.1.5模型预测日志', 'v3.2.0模型预测日志'],
    missingMaterials: ['标注负责人周姐的人工判断依据', '线上反馈工单的用户投诉记录'],
    nextStep: '标注负责人周姐补充线上反馈工单信息和人工标注意见后，交由运营复核人最终判定。',
    assignee: 'annotator',
    assigneeName: '周姐',
    dueDate: daysAgo(-1),
    status: 'in_progress',
  },
  {
    id: 'r004',
    conflictId: 'c004',
    reason: '模型对政治敏感内容的边界识别存在模糊区，正常时政新闻配图被误判。',
    existingMaterials: ['知识库原始链接', '模型预测日志', '运营复核人判定记录'],
    missingMaterials: [],
    nextStep: '已闭环，归档处理。',
    assignee: 'operator',
    assigneeName: '李运营',
    status: 'completed',
  },
];

export const mockModelParams: ModelParams[] = [
  {
    id: 'mp001',
    conflictId: 'c001',
    modelVersion: 'v3.2.0',
    parameters: {
      model_arch: 'ResNet-50',
      threshold_nsfw: 0.65,
      threshold_normal: 0.70,
      feature_extractor: 'CLIP-ViT-L/14',
      training_data_version: '2024-Q1',
      batch_size: 64,
      learning_rate: 0.0001,
    },
    decisionReason: 'v3.2.0将NSFW阈值从0.70下调至0.65，提升召回率的同时增加了误判风险。该图片皮肤暴露面积占比28%，处于边界区域。取舍：优先保证召回，误判由人工复核兜底。',
  },
  {
    id: 'mp003',
    conflictId: 'c003',
    modelVersion: 'v3.2.0',
    parameters: {
      model_arch: 'EfficientNet-B4',
      threshold_ad: 0.60,
      text_detection_weight: 0.4,
      image_pattern_weight: 0.6,
      contact_info_detection: true,
    },
    decisionReason: 'v3.2.0增加了水印和联系方式检测权重，该图片包含半透明微信号水印。取舍：宁可误判不漏判，广告类内容优先保证召回率。',
  },
];

export const mockKnowledgeLinks: KnowledgeLink[] = [
  {
    id: 'kl001',
    url: 'https://wiki.example.com/knowledge/IMG-2024-00123',
    sampleNumber: 'IMG-2024-00123',
    modelVersion: 'v3.1.5',
    importedAt: daysAgo(7),
    importBatch: 'batch-2024-05-01',
  },
  {
    id: 'kl002',
    url: 'https://wiki.example.com/knowledge/IMG-2024-00123',
    sampleNumber: 'IMG-2024-00123',
    modelVersion: 'v3.2.0',
    importedAt: daysAgo(2),
    importBatch: 'batch-2024-06-10',
  },
  {
    id: 'kl003',
    url: 'https://wiki.example.com/knowledge/IMG-2024-00145',
    sampleNumber: 'IMG-2024-00145',
    modelVersion: 'v3.2.0',
    importedAt: daysAgo(3),
    importBatch: 'batch-2024-06-10',
  },
];

export const mockTrendData: TrendData[] = [
  { date: '06-01', count: 12, modelChanged: 3 },
  { date: '06-02', count: 18, modelChanged: 5 },
  { date: '06-03', count: 15, modelChanged: 4 },
  { date: '06-04', count: 22, modelChanged: 8 },
  { date: '06-05', count: 19, modelChanged: 6 },
  { date: '06-06', count: 28, modelChanged: 12 },
  { date: '06-07', count: 6, modelChanged: 3 },
];
