import type {
  Product,
  InventoryItem,
  Order,
  ExchangeRate,
  Transaction,
  ExceptionItem,
  CorrectionRecord,
  RoundResult,
} from './types';

export const products: Product[] = [
  { id: 'p1', name: '智能电子配件', sku: 'ELEC-001', unitCost: 150, currency: 'USD' },
  { id: 'p2', name: '精密机械零件', sku: 'MECH-002', unitCost: 320, currency: 'EUR' },
  { id: 'p3', name: '纺织面料', sku: 'TEXT-003', unitCost: 85, currency: 'USD' },
  { id: 'p4', name: '化工原料', sku: 'CHEM-004', unitCost: 200, currency: 'GBP' },
];

export const initialInventory: InventoryItem[] = [
  {
    id: 'inv1',
    productId: 'p1',
    productName: '智能电子配件',
    quantity: 100,
    unitCost: 150,
    totalValue: 15000,
    currency: 'USD',
    purchaseRound: 0,
    overstockThreshold: 150,
    isOverstock: false,
  },
  {
    id: 'inv2',
    productId: 'p2',
    productName: '精密机械零件',
    quantity: 50,
    unitCost: 320,
    totalValue: 16000,
    currency: 'EUR',
    purchaseRound: 0,
    overstockThreshold: 80,
    isOverstock: false,
  },
  {
    id: 'inv3',
    productId: 'p3',
    productName: '纺织面料',
    quantity: 200,
    unitCost: 85,
    totalValue: 17000,
    currency: 'USD',
    purchaseRound: 0,
    overstockThreshold: 250,
    isOverstock: false,
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord1',
    orderNo: 'ORD-2024-001',
    customerName: '美国TechCorp公司',
    productId: 'p1',
    productName: '智能电子配件',
    quantity: 50,
    unitPrice: 220,
    totalAmount: 11000,
    currency: 'USD',
    status: 'shipped',
    createRound: 1,
    expectedDeliveryRound: 3,
    defaultRisk: 0.05,
    hasMissingFields: false,
    isLateSubmission: false,
    remarks: '长期合作客户，信用良好',
  },
  {
    id: 'ord2',
    orderNo: 'ORD-2024-002',
    customerName: '德国AutoParts GmbH',
    productId: 'p2',
    productName: '精密机械零件',
    quantity: 30,
    unitPrice: 450,
    totalAmount: 13500,
    currency: 'EUR',
    status: 'confirmed',
    createRound: 2,
    expectedDeliveryRound: 4,
    defaultRisk: 0.08,
    hasMissingFields: true,
    missingFields: ['contactPerson', 'shippingAddress'],
    isLateSubmission: true,
    lateReason: '客户临时修改订单条款，延迟提交',
    remarks: '备注：原单价420欧元，客户协商后提价至450',
    lastModified: new Date('2024-03-15'),
    modifiedBy: '张经理',
    modificationReason: '客户要求修改单价和数量',
  },
  {
    id: 'ord3',
    orderNo: 'ORD-2024-003',
    customerName: '日本Fashion Co.',
    productId: 'p3',
    productName: '纺织面料',
    quantity: 80,
    unitPrice: 130,
    totalAmount: 10400,
    currency: 'USD',
    status: 'pending',
    createRound: 3,
    expectedDeliveryRound: 5,
    defaultRisk: 0.15,
    hasMissingFields: true,
    missingFields: ['paymentTerms'],
    isLateSubmission: false,
    remarks: '新客户，需要核实信用资质',
  },
  {
    id: 'ord4',
    orderNo: 'ORD-2024-004',
    customerName: '英国ChemTrade Ltd',
    productId: 'p4',
    productName: '化工原料',
    quantity: 40,
    unitPrice: 280,
    totalAmount: 11200,
    currency: 'GBP',
    status: 'delivered',
    createRound: 1,
    expectedDeliveryRound: 3,
    actualDeliveryRound: 3,
    defaultRisk: 0.03,
    hasMissingFields: false,
    isLateSubmission: false,
    remarks: '已收款，交易完成',
  },
  {
    id: 'ord5',
    orderNo: 'ORD-2024-005',
    customerName: '意大利Machinery Srl',
    productId: 'p2',
    productName: '精密机械零件',
    quantity: 25,
    unitPrice: 480,
    totalAmount: 12000,
    currency: 'EUR',
    status: 'defaulted',
    createRound: 1,
    expectedDeliveryRound: 2,
    defaultRisk: 0.25,
    hasMissingFields: false,
    isLateSubmission: false,
    remarks: '客户资金链断裂，已拖欠货款3个月',
  },
];

export const exchangeRateCards: ExchangeRate[] = [
  {
    id: 'rate1',
    currency: 'USD',
    rate: 7.245,
    previousRate: 7.220,
    trend: 'up',
    round: 1,
    cardType: 'normal',
    description: '美联储加息预期升温，美元小幅走强',
  },
  {
    id: 'rate2',
    currency: 'USD',
    rate: 7.310,
    previousRate: 7.245,
    trend: 'up',
    round: 2,
    cardType: 'shock',
    description: '地缘政治风险加剧，美元大幅升值',
  },
  {
    id: 'rate3',
    currency: 'USD',
    rate: 7.185,
    previousRate: 7.310,
    trend: 'down',
    round: 3,
    cardType: 'recovery',
    description: '中美贸易谈判取得进展，人民币回升',
  },
  {
    id: 'rate4',
    currency: 'USD',
    rate: 7.220,
    previousRate: 7.185,
    trend: 'up',
    round: 4,
    cardType: 'normal',
    description: '市场情绪平稳，汇率窄幅波动',
  },
  {
    id: 'rate5',
    currency: 'USD',
    rate: 7.400,
    previousRate: 7.220,
    trend: 'up',
    round: 5,
    cardType: 'shock',
    description: '突发金融事件，美元大幅跳涨',
  },
];

export const initialTransactions: Transaction[] = [
  {
    id: 'txn1',
    transactionNo: 'TXN-2024-001',
    type: 'sale',
    amount: 11200,
    currency: 'GBP',
    cnyEquivalent: 95200,
    exchangeRateUsed: 8.5,
    description: '英国ChemTrade Ltd货款',
    relatedOrderId: 'ord4',
    status: 'normal',
    round: 3,
    createTime: new Date('2024-03-10'),
  },
  {
    id: 'txn2',
    transactionNo: 'TXN-2024-002',
    type: 'purchase',
    amount: 15000,
    currency: 'USD',
    cnyEquivalent: 108675,
    exchangeRateUsed: 7.245,
    description: '智能电子配件采购',
    relatedInventoryId: 'inv1',
    status: 'normal',
    round: 1,
    createTime: new Date('2024-03-01'),
  },
  {
    id: 'txn3',
    transactionNo: 'TXN-2024-003',
    type: 'purchase',
    amount: 16000,
    currency: 'EUR',
    cnyEquivalent: 124800,
    exchangeRateUsed: 7.8,
    description: '精密机械零件采购',
    relatedInventoryId: 'inv2',
    status: 'normal',
    round: 1,
    createTime: new Date('2024-03-01'),
  },
  {
    id: 'txn4',
    transactionNo: 'TXN-2024-004',
    type: 'forex_exchange',
    amount: 5000,
    currency: 'USD',
    cnyEquivalent: 36550,
    exchangeRateUsed: 7.31,
    description: '美元结汇，用于支付供应商货款',
    status: 'normal',
    round: 2,
    createTime: new Date('2024-03-08'),
    correctionHistory: [
      {
        id: 'corr1',
        transactionId: 'txn4',
        fieldName: 'exchangeRateUsed',
        oldValue: 7.28,
        newValue: 7.31,
        reason: '银行实际结汇汇率与预估汇率有差异',
        operator: '李会计',
        timestamp: new Date('2024-03-09'),
        round: 2,
      },
    ],
  },
  {
    id: 'txn5',
    transactionNo: 'TXN-2024-005',
    type: 'sale',
    amount: 8000,
    currency: 'USD',
    cnyEquivalent: 58480,
    exchangeRateUsed: 7.31,
    description: '客户补付前期欠款',
    relatedOrderId: 'ord1',
    status: 'supplement',
    round: 2,
    createTime: new Date('2024-03-12'),
    isSupplement: true,
    supplementReason: 'ROUND1订单尾款延迟到账',
    supplementRound: 1,
  },
  {
    id: 'txn6',
    transactionNo: 'TXN-2024-006',
    type: 'purchase',
    amount: 3000,
    currency: 'USD',
    cnyEquivalent: 21735,
    exchangeRateUsed: 7.245,
    description: '运费支出（误录入，已撤回）',
    status: 'reversed',
    round: 1,
    createTime: new Date('2024-03-02'),
    isReversed: true,
    reversalReason: '重复录入运费支出',
  },
  {
    id: 'txn7',
    transactionNo: 'TXN-2024-007',
    type: 'purchase',
    amount: 3000,
    currency: 'USD',
    cnyEquivalent: 21735,
    exchangeRateUsed: 7.245,
    description: '运费支出',
    status: 'normal',
    round: 1,
    createTime: new Date('2024-03-02'),
  },
  {
    id: 'txn8',
    transactionNo: 'TXN-2024-008',
    type: 'forex_exchange',
    amount: -12000,
    currency: 'EUR',
    cnyEquivalent: -93600,
    exchangeRateUsed: 7.8,
    description: '欧元汇兑亏损确认',
    status: 'pending_review',
    round: 3,
    createTime: new Date('2024-03-15'),
  },
];

export const initialExceptions: ExceptionItem[] = [
  {
    id: 'ex1',
    type: 'customer_default',
    status: 'pending',
    title: '意大利客户货款违约',
    description: '意大利Machinery Srl公司已拖欠货款12000欧元超过3个月，多次催收无果。建议计提坏账准备。',
    amount: 12000,
    currency: 'EUR',
    relatedOrderId: 'ord5',
    round: 3,
    discoveredRound: 3,
  },
  {
    id: 'ex2',
    type: 'forex_loss',
    status: 'confirmed',
    title: '欧元贬值汇兑损失',
    description: '由于欧元汇率从7.9跌至7.8，持有的16000欧元产生汇兑损失1600元人民币。',
    amount: 1600,
    currency: 'USD',
    relatedTransactionId: 'txn8',
    round: 3,
    discoveredRound: 3,
  },
  {
    id: 'ex3',
    type: 'missing_fields',
    status: 'pending',
    title: '订单缺少关键字段',
    description: '订单ORD-2024-002缺少联系人、收货地址字段；订单ORD-2024-003缺少付款条款。请补录后再进行发货操作。',
    relatedOrderId: 'ord2',
    round: 2,
    discoveredRound: 3,
  },
  {
    id: 'ex4',
    type: 'late_submission',
    status: 'waived',
    title: '订单延迟提交',
    description: '订单ORD-2024-002因客户临时修改条款延迟3天提交，考虑到是长期合作客户，已豁免处理。',
    relatedOrderId: 'ord2',
    round: 2,
    discoveredRound: 2,
    resolvedRound: 2,
    resolution: '业务经理审批通过，豁免延迟责任',
    operator: '王总监',
  },
  {
    id: 'ex5',
    type: 'inventory_overstock',
    status: 'pending',
    title: '纺织面料库存积压',
    description: '纺织面料当前库存200件，接近250件积压警戒线。近3个月销量仅为预期的60%，建议降价促销或减少采购。',
    amount: 17000,
    currency: 'USD',
    relatedInventoryId: 'inv3',
    round: 3,
    discoveredRound: 3,
  },
];

export const initialCorrectionRecords: CorrectionRecord[] = [
  {
    id: 'corr1',
    transactionId: 'txn4',
    fieldName: 'exchangeRateUsed',
    oldValue: 7.28,
    newValue: 7.31,
    reason: '银行实际结汇汇率与预估汇率有差异',
    operator: '李会计',
    timestamp: new Date('2024-03-09'),
    round: 2,
  },
  {
    id: 'corr2',
    transactionId: 'txn2',
    fieldName: 'amount',
    oldValue: 14500,
    newValue: 15000,
    reason: '供应商补发50件配件，调整采购金额',
    operator: '张经理',
    timestamp: new Date('2024-03-05'),
    round: 1,
  },
];

export const initialRoundHistory: RoundResult[] = [
  {
    round: 1,
    startCash: 1000000,
    endCash: 843590,
    cashChange: -156410,
    revenue: 0,
    costs: 233475,
    forexGainLoss: 0,
    inventoryValue: 229475,
    ordersCompleted: 0,
    ordersDefaulted: 0,
    exceptionsGenerated: [],
    decisions: [
      '采购智能电子配件100件，价值15000美元',
      '采购精密机械零件50件，价值16000欧元',
    ],
    resultAnalysis: '首轮运营主要为备货阶段，现金流出较大。库存价值健康，无异常情况。',
  },
  {
    round: 2,
    startCash: 843590,
    endCash: 890145,
    cashChange: 46555,
    revenue: 58480,
    costs: 11930,
    forexGainLoss: 0,
    inventoryValue: 229475,
    ordersCompleted: 0,
    ordersDefaulted: 0,
    exceptionsGenerated: ['ex4'],
    decisions: [
      '美元结汇5000美元，用于支付货款',
      '收回应收账款8000美元',
      '处理订单延迟提交豁免',
    ],
    resultAnalysis: '本期回收部分前期应收账款，现金流转正。发现订单延迟提交问题，已妥善处理。',
  },
  {
    round: 3,
    startCash: 890145,
    endCash: 985345,
    cashChange: 95200,
    revenue: 95200,
    costs: 0,
    forexGainLoss: -1600,
    inventoryValue: 227875,
    ordersCompleted: 1,
    ordersDefaulted: 1,
    exceptionsGenerated: ['ex1', 'ex2', 'ex3', 'ex5'],
    decisions: [
      '完成英国ChemTrade订单，收汇11200英镑',
      '确认欧元汇兑损失1600元',
      '发现意大利客户违约',
    ],
    resultAnalysis: '本期完成大额订单，现金大幅增长。但同时暴露多重风险：客户违约、汇兑损失、库存积压、订单信息不全，需重点关注风险管理。',
  },
];

export const getInitialState = () => ({
  currentRound: 3,
  totalRounds: 8,
  cash: 985345,
  initialCash: 1000000,
  targetCash: 1500000,
  exchangeRates: exchangeRateCards,
  currentRate: exchangeRateCards[2],
  inventory: initialInventory,
  orders: initialOrders,
  transactions: initialTransactions,
  exceptions: initialExceptions,
  correctionRecords: initialCorrectionRecords,
  roundHistory: initialRoundHistory,
  isGameOver: false,
  selectedTab: 'dashboard' as const,
});
