export const LEVELS = [
  {
    id: 0,
    name: '第一关 · 入门班',
    desc: '三件套：退货 / 破损 / 预订。只看书脊标签。',
    turns: 5,
    turnTime: 60,
    maxMistakes: 3,
    booksPerTurn: [6, 8],
    rules: [
      '书脊标签 = 退 → 拖到「退货区」',
      '书脊标签 = 损 → 拖到「破损登记」',
      '书脊标签 = 订 → 拖到「预订留位」',
      '正确率 100% 本回合额外 +20 分',
    ],
    slots: ['return', 'damaged', 'reserved'],
    shelves: [],
    matchReturnSlip: false,
    scorePerBook: 10,
  },
  {
    id: 1,
    name: '第二关 · 盘点周',
    desc: '新增「可售回架」：退回但品相完好的书按 ISBN 段回到 A/B/C/D 四个货架。',
    turns: 5,
    turnTime: 75,
    maxMistakes: 4,
    booksPerTurn: [8, 11],
    rules: [
      '退货 / 破损 / 预订 规则不变',
      '书脊标签 = 架 → 需要按 ISBN 首段放回货架',
      'ISBN 978-7-1 → 货架 A',
      'ISBN 978-7-2 → 货架 B',
      'ISBN 978-7-5 → 货架 C',
      'ISBN 978-7-8 → 货架 D',
    ],
    slots: ['return', 'damaged', 'reserved', 'shelf'],
    shelves: ['A', 'B', 'C', 'D'],
    shelfIsbnPrefixes: {
      A: '978-7-1',
      B: '978-7-2',
      C: '978-7-5',
      D: '978-7-8',
    },
    matchReturnSlip: false,
    scorePerBook: 12,
  },
  {
    id: 2,
    name: '第三关 · 月末对账',
    desc: '每张退货单必须与实物一一对应；保留破损登记、预订留位、可售回架。',
    turns: 6,
    turnTime: 90,
    maxMistakes: 5,
    booksPerTurn: [9, 13],
    rules: [
      '书脊标签 = 退 → 必须拖到「对应单号」的退货单格子',
      '书脊标签 = 损 → 破损登记（无退货单）',
      '书脊标签 = 订 → 预订留位（无退货单）',
      '书脊标签 = 架 → 按 ISBN 段回货架 A/B/C/D',
      '退货单匹配错误直接判失误',
    ],
    slots: ['return', 'damaged', 'reserved', 'shelf'],
    shelves: ['A', 'B', 'C', 'D'],
    shelfIsbnPrefixes: {
      A: '978-7-1',
      B: '978-7-2',
      C: '978-7-5',
      D: '978-7-8',
    },
    matchReturnSlip: true,
    returnSlipsPerTurn: [3, 5],
    scorePerBook: 15,
  },
];

export function getLevel(id) {
  return LEVELS.find(l => l.id === id) || LEVELS[0];
}

export const BOOK_KINDS = {
  return:   { tag: '退', color: '#f4c86a' },
  damaged:  { tag: '损', color: '#ff7b7b' },
  reserved: { tag: '订', color: '#8fd2ff' },
  shelf:    { tag: '架', color: '#7bd88f' },
};

export const BOOK_TITLES = [
  '夜晚的潜水艇',
  '秋园',
  '长安的荔枝',
  '置身事内',
  '人类简史',
  '万历十五年',
  '圆圈正义',
  '始于极限',
  '地下室手记',
  '局外人',
  '悉达多',
  '你想活出怎样的人生',
  '厌女',
  '被讨厌的勇气',
  '蛤蟆先生去看心理医生',
  '也许你该找个人聊聊',
  '理想国',
  '形而上学',
  '查拉图斯特拉如是说',
  '第二性',
  '存在与时间',
  '存在与虚无',
  '梦的解析',
  '动机与人格',
  '经济学原理',
  '国富论',
  '资本论',
  '君主论',
  '社会契约论',
  '论美国的民主',
  '历史的终结与最后的人',
  '文明的冲突',
  '枪炮、病菌与钢铁',
  '崩溃',
  '第三种黑猩猩',
  '自私的基因',
  '盲眼钟表匠',
  '时间简史',
  '果壳中的宇宙',
  '宇宙的琴弦',
];
