import os

OUT = os.path.join(os.path.dirname(__file__), '..', 'index.js')

lines = []
def w(s=''):
    lines.append(s)

w("const express = require('express');")
w("const cors = require('cors');")
w("const path = require('path');")
w("const fs = require('fs');")
w("const crypto = require('crypto');")
w("const { Parser } = require('json2csv');")
w("const dbModule = require('./db');")
w("const selfCheck = require('./selfCheck');")
w()
w("const app = express();")
w("const PORT = 3001;")
w()
w("app.use(cors());")
w("app.use(express.json());")
w("app.use(express.static(path.join(__dirname, '..', 'public')));")
w()
w("const dataDir = path.join(__dirname, '..', 'data');")
w("if (!fs.existsSync(dataDir)) {")
w("  fs.mkdirSync(dataDir, { recursive: true });")
w("}")
w()
w("const loadJSON = dbModule.loadDB;")
w("const saveDB = dbModule.saveDB;")
w("const insertRow = dbModule.insertRow;")
w("const updateRow = dbModule.updateRow;")
w("const now = dbModule.now;")
w()
w("function addAuditLog(sampleId, action, oldValue, newValue, operator, remark) {")
w("  const oper = operator || 'system';")
w("  const rmk = remark || '';")
w("  insertRow(")
w("    'sample_audit_logs',")
w("    ['sample_id', 'action', 'old_value', 'new_value', 'operator', 'remark'],")
w("    [sampleId, action, oldValue, newValue, oper, rmk]")
w("  );")
w("}")
w()
w("app.get('/api/reports', (req, res) => {")
w("  const data = loadJSON();")
w("  const reports = (data.weekly_reports || []).map(r => {")
w("    const sample_count = (data.negative_samples || []).filter(s => s.report_id == r.id).length;")
w("    const recall_count = (data.recall_candidates || []).filter(c => c.report_id == r.id).length;")
w("    return { ...r, sample_count, recall_count };")
w("  });")
w("  reports.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));")
w("  res.json(reports);")
w("});")
w()
w("app.post('/api/reports', (req, res) => {")
w("  const { week_number, title, created_by } = req.body;")
w("  try {")
w("    const existing = loadJSON().weekly_reports?.find(r => r.week_number === week_number);")
w("    if (existing) {")
w("      return res.status(400).json({ error: '该周次周报已存在' });")
w("    }")
w("    const result = insertRow(")
w("      'weekly_reports',")
w("      ['week_number', 'title', 'created_by', 'status'],")
w("      [week_number, title, created_by || 'system', 'draft']")
w("    );")
w("    res.json({ id: result.lastInsertRowid, week_number, title });")
w("  } catch (e) {")
w("    res.status(400).json({ error: e.message });")
w("  }")
w("});")
w()
w("app.get('/api/reports/:id', (req, res) => {")
w("  const data = loadJSON();")
w("  const report = (data.weekly_reports || []).find(r => r.id === parseInt(req.params.id));")
w("  if (!report) return res.status(404).json({ error: 'Report not found' });")
w("  res.json(report);")
w("});")
w()
w("app.get('/api/reports/:id/samples', (req, res) => {")
w("  const { status, anomaly_only } = req.query;")
w("  const reportId = parseInt(req.params.id);")
w("  const data = loadJSON();")
w("  let samples = (data.negative_samples || []).filter(s => s.report_id === reportId);")
w("  if (status) samples = samples.filter(s => s.processing_status === status);")
w("  if (anomaly_only === '1') samples = samples.filter(s => s.is_bucket_diff_anomaly === 1);")
w("  samples.sort((a, b) => a.original_line_no - b.original_line_no);")
w("  res.json(samples);")
w("});")
w()
w("app.post('/api/reports/:id/samples/import', (req, res) => {")
w("  const reportId = parseInt(req.params.id);")
w("  const { samples, operator } = req.body;")
w("  const data = loadJSON();")
w("  const report = (data.weekly_reports || []).find(r => r.id === reportId);")
w("  if (!report) return res.status(404).json({ error: 'Report not found' });")
w()
w("  samples.forEach((s, idx) => {")
w("    const bucketInfo = selfCheck.calculateBucketForSample(s);")
w("    const result = insertRow(")
w("      'negative_samples',")
w("      ['report_id', 'original_line_no', 'item_id', 'item_title', 'offline_score', 'online_score',")
w("       'offline_bucket', 'online_bucket', 'bucket_diff', 'is_bucket_diff_anomaly', 'raw_data', 'processing_status'],")
w("      [reportId,")
w("       s.original_line_no || (idx + 1),")
w("       s.item_id,")
w("       s.item_title || '',")
w("       s.offline_score,")
w("       s.online_score,")
w("       bucketInfo.offline_bucket,")
w("       bucketInfo.online_bucket,")
w("       bucketInfo.bucket_diff,")
w("       bucketInfo.is_bucket_diff_anomaly,")
w("       JSON.stringify(s),")
w("       'imported']")
w("    );")
w("    addAuditLog(result.lastInsertRowid, 'import', null, JSON.stringify(s), operator || 'system', '导入负样本');")
w("  });")
w()
w("  const after = loadJSON();")
w("  const count = (after.negative_samples || []).filter(s => s.report_id === reportId).length;")
w("  res.json({ imported: samples.length, total: count });")
w("});")
w()
w("app.patch('/api/samples/:id', (req, res) => {")
w("  const sampleId = parseInt(req.params.id);")
w("  const { manual_remark, processing_status, operator } = req.body;")
w("  const data = loadJSON();")
w("  const old = (data.negative_samples || []).find(s => s.id === sampleId);")
w("  if (!old) return res.status(404).json({ error: 'Sample not found' });")
w()
w("  const setFields = [];")
w("  const setValues = [];")
w()
w("  if (manual_remark !== undefined) {")
w("    setFields.push('manual_remark');")
w("    setValues.push(manual_remark);")
w("    addAuditLog(sampleId, 'update_manual_remark', old.manual_remark || null, manual_remark, operator || 'system', '人工备注更新');")
w("  }")
w("  if (processing_status !== undefined) {")
w("    setFields.push('processing_status');")
w("    setValues.push(processing_status);")
w("    addAuditLog(sampleId, 'update_status', old.processing_status || null, processing_status, operator || 'system', '处理状态更新');")
w("  }")
w()
w("  if (setFields.length === 0) return res.status(400).json({ error: 'No updates' });")
w()
w("  setFields.push('updated_at');")
w("  setValues.push(now());")
w("  updateRow('negative_samples', setFields, setValues, 'id', sampleId);")
w()
w("  const updated = loadJSON().negative_samples.find(s => s.id === sampleId);")
w("  res.json(updated);")
w("});")
w()
w("app.get('/api/samples/:id/audit', (req, res) => {")
w("  const data = loadJSON();")
w("  const logs = (data.sample_audit_logs || [])")
w("    .filter(a => a.sample_id === parseInt(req.params.id))")
w("    .sort((a, b) => new Date(b.created_at) - new Date(a.created_at));")
w("  res.json(logs);")
w("});")
w()
w("app.get('/api/reports/:id/recalls', (req, res) => {")
w("  const data = loadJSON();")
w("  const recalls = (data.recall_candidates || [])")
w("    .filter(r => r.report_id === parseInt(req.params.id))")
w("    .sort((a, b) => new Date(b.created_at) - new Date(a.created_at));")
w("  res.json(recalls);")
w("});")
w()
w("app.post('/api/reports/:id/recalls', (req, res) => {")
w("  const reportId = parseInt(req.params.id);")
w("  const { items, added_by } = req.body;")
w("  const oper = added_by || 'linjie';")
w()
w("  items.forEach(item => {")
w("    insertRow(")
w("      'recall_candidates',")
w("      ['report_id', 'sample_id', 'item_id', 'item_title', 'recall_source', 'recall_score', 'added_by'],")
w("      [reportId, item.sample_id || null, item.item_id, item.item_title || '',")
w("       item.recall_source || '', item.recall_score || null, oper]")
w("    );")
w("    if (item.sample_id) {")
w("      const d0 = loadJSON();")
w("      const sample = (d0.negative_samples || []).find(s => s.id === item.sample_id);")
w("      if (sample) {")
w("        updateRow('negative_samples', ['recall_candidate_added', 'updated_at'], [1, now()], 'id', item.sample_id);")
w("        addAuditLog(item.sample_id, 'link_recall', null, JSON.stringify(item), oper, '关联召回候选');")
w("      }")
w("    }")
w("  });")
w("  res.json({ added: items.length });")
w("});")
w()
w("app.post('/api/reports/:id/recalc', (req, res) => {")
w("  const reportId = parseInt(req.params.id);")
w("  const { operator } = req.body;")
w("  const oper = operator || 'system';")
w()
w("  const data = loadJSON();")
w("  const samples = (data.negative_samples || []).filter(s => s.report_id === reportId);")
w()
w("  samples.forEach(s => {")
w("    const bucketInfo = selfCheck.calculateBucketForSample(s);")
w("    const oldAnomaly = s.is_bucket_diff_anomaly;")
w("    updateRow(")
w("      'negative_samples',")
w("      ['offline_bucket', 'online_bucket', 'bucket_diff', 'is_bucket_diff_anomaly', 'updated_at'],")
w("      [bucketInfo.offline_bucket, bucketInfo.online_bucket, bucketInfo.bucket_diff, bucketInfo.is_bucket_diff_anomaly, now()],")
w("      'id',")
w("      s.id")
w("    );")
w("    if (oldAnomaly !== bucketInfo.is_bucket_diff_anomaly) {")
w("      addAuditLog(s.id, 'recalc_bucket', String(oldAnomaly), String(bucketInfo.is_bucket_diff_anomaly), oper, '补录后重算分桶');")
w("    }")
w("  });")
w()
w("  const newData = loadJSON();")
w("  const anomalyCount = (newData.negative_samples || []).filter(s =>")
w("    s.report_id === reportId && s.is_bucket_diff_anomaly === 1")
w("  ).length;")
w("  res.json({ recalculated: samples.length, anomaly_count: anomalyCount });")
w("});")
w()
w("app.post('/api/reports/:id/self-check', (req, res) => {")
w("  const reportId = parseInt(req.params.id);")
w("  const results = selfCheck.runAllChecks(reportId);")
w("  res.json(results);")
w("});")
w()
w("app.get('/api/reports/:id/self-check/latest', (req, res) => {")
w("  const reportId = parseInt(req.params.id);")
w("  const data = loadJSON();")
w("  const checks = (data.self_check_results || [])")
w("    .filter(r => r.report_id === reportId)")
w("    .sort((a, b) => new Date(b.checked_at) - new Date(a.checked_at));")
w("  const grouped = {};")
w("  checks.forEach(r => {")
w("    if (!grouped[r.check_type]) grouped[r.check_type] = r;")
w("  });")
w("  res.json(grouped);")
w("});")
w()
w("function getEvidenceChain(sampleId, data) {")
w("  const audits = (data.sample_audit_logs || []).filter(a => a.sample_id === sampleId);")
w("  const recalls = (data.recall_candidates || []).filter(r => r.sample_id === sampleId);")
w("  const statusHistory = [];")
w("  let lastStatus = null;")
w()
w("  audits.forEach(a => {")
w("    if (a.action === 'update_status') {")
w("      statusHistory.push({")
w("        from: a.old_value, to: a.new_value,")
w("        operator: a.operator, time: a.created_at, remark: a.remark")
w("      });")
w("      lastStatus = a.new_value;")
w("    } else if (a.action === 'import') {")
w("      statusHistory.push({")
w("        from: null, to: 'imported',")
w("        operator: a.operator, time: a.created_at, remark: a.remark || '首次导入'")
w("      });")
w("      lastStatus = 'imported';")
w("    }")
w("  });")
w()
w("  const manualRemarks = audits")
w("    .filter(a => a.action === 'update_manual_remark')")
w("    .map(a => ({ old: a.old_value, new: a.new_value, operator: a.operator, time: a.created_at, remark: a.remark }));")
w()
w("  const recallLinks = audits")
w("    .filter(a => a.action === 'link_recall')")
w("    .map(a => ({ data: a.new_value, operator: a.operator, time: a.created_at, remark: a.remark }));")
w()
w("  const recalcLogs = audits")
w("    .filter(a => a.action === 'recalc_bucket')")
w("    .map(a => ({ old_anomaly: a.old_value, new_anomaly: a.new_value, operator: a.operator, time: a.created_at, remark: a.remark }));")
w()
w("  return {")
w("    audit_count: audits.length,")
w("    status_history: statusHistory,")
w("    current_status: lastStatus,")
w("    manual_remark_history: manualRemarks,")
w("    recall_link_history: recallLinks,")
w("    recalc_history: recalcLogs,")
w("    recalls: recalls,")
w("    audits: audits.sort((a, b) => new Date(b.created_at) - new Date(a.created_at))")
w("  };")
w("}")
w()
w("app.get('/api/reports/:id/export', (req, res) => {")
w("  const reportId = parseInt(req.params.id);")
w("  const data = loadJSON();")
w("  const samples = (data.negative_samples || [])")
w("    .filter(s => s.report_id === reportId)")
w("    .sort((a, b) => a.original_line_no - b.original_line_no);")
w()
w("  const snapshot = samples.map(s => ({")
w("    ...s,")
w("    evidence_snapshot: getEvidenceChain(s.id, data)")
w("  }));")
w()
w("  const contentHash = crypto")
w("    .createHash('md5')")
w("    .update(JSON.stringify(samples))")
w("    .digest('hex');")
w()
w("  const exportedBy = req.query.exported_by || 'system';")
w()
w("  insertRow(")
w("    'export_records',")
w("    ['report_id', 'export_type', 'content_hash', 'exported_by', 'snapshot_data'],")
w("    [reportId, 'csv', contentHash, exportedBy, snapshot]")
w("  );")
w()
w("  const json2csvParser = new Parser({")
w("    fields: [")
w("      '原始行号', '物料ID', '物料标题', '离线分数', '线上分数',")
w("      '离线分桶', '线上分桶', '分桶差值', '分差一桶异常',")
w("      '人工备注', '处理状态', '已关联召回候选'")
w("    ]")
w("  });")
w()
w("  const csvData = samples.map(s => ({")
w("    '原始行号': s.original_line_no,")
w("    '物料ID': s.item_id,")
w("    '物料标题': s.item_title,")
w("    '离线分数': s.offline_score,")
w("    '线上分数': s.online_score,")
w("    '离线分桶': s.offline_bucket,")
w("    '线上分桶': s.online_bucket,")
w("    '分桶差值': s.bucket_diff,")
w("    '分差一桶异常': s.is_bucket_diff_anomaly ? '是' : '否',")
w("    '人工备注': s.manual_remark || '',")
w("    '处理状态': s.processing_status,")
w("    '已关联召回候选': s.recall_candidate_added ? '是' : '否'")
w("  }));")
w()
w("  const csv = json2csvParser.parse(csvData);")
w("  res.setHeader('Content-Type', 'text/csv; charset=utf-8');")
w("  res.setHeader('Content-Disposition', `attachment; filename=\"weekly_report_${reportId}.csv\"`);")
w("  res.send('\\uFEFF' + csv);")
w("});")
w()
w("app.patch('/api/reports/:id/status', (req, res) => {")
w("  const reportId = parseInt(req.params.id);")
w("  const { status } = req.body;")
w("  updateRow('weekly_reports', ['status', 'updated_at'], [status, now()], 'id', reportId);")
w("  res.json({ id: reportId, status });")
w("});")
w()
w("app.get('/api/reports/:id/summary', (req, res) => {")
w("  const reportId = parseInt(req.params.id);")
w("  const data = loadJSON();")
w("  const samples = (data.negative_samples || []).filter(s => s.report_id === reportId);")
w("  const total = samples.length;")
w("  const anomalies = samples.filter(s => s.is_bucket_diff_anomaly === 1).length;")
w("  const pending = samples.filter(s => ['pending', 'imported'].includes(s.processing_status)).length;")
w("  const reviewed = samples.filter(s => s.processing_status === 'reviewed').length;")
w("  const withRecall = samples.filter(s => s.recall_candidate_added === 1).length;")
w("  const recallCount = (data.recall_candidates || []).filter(r => r.report_id === reportId).length;")
w("  res.json({")
w("    total_samples: total,")
w("    bucket_anomalies: anomalies,")
w("    pending_review: pending,")
w("    reviewed: reviewed,")
w("    samples_with_recall: withRecall,")
w("    recall_candidates: recallCount")
w("  });")
w("});")
w()
w("app.get('/api/reports/:id/export-history', (req, res) => {")
w("  const reportId = parseInt(req.params.id);")
w("  const data = loadJSON();")
w("  const exports = (data.export_records || [])")
w("    .filter(e => e.report_id === reportId)")
w("    .sort((a, b) => new Date(b.created_at) - new Date(a.created_at));")
w()
w("  exports.forEach(e => {")
w("    if (e.snapshot_data) {")
w("      e.sample_count = e.snapshot_data.length;")
w("      e.anomaly_count = e.snapshot_data.filter(s => s.is_bucket_diff_anomaly === 1).length;")
w("    } else {")
w("      e.sample_count = 0;")
w("      e.anomaly_count = 0;")
w("    }")
w("  });")
w("  res.json(exports);")
w("});")
w()
w("app.get('/api/exports/:id', (req, res) => {")
w("  const exportId = parseInt(req.params.id);")
w("  const data = loadJSON();")
w("  const exp = (data.export_records || []).find(e => e.id === exportId);")
w("  if (!exp) return res.status(404).json({ error: 'Export not found' });")
w()
w("  const exports = (data.export_records || []).filter(e => e.report_id === exp.report_id);")
w("  const prevExport = exports")
w("    .filter(e => e.id < exportId)")
w("    .sort((a, b) => b.id - a.id)[0];")
w()
w("  const samples = exp.snapshot_data || [];")
w("  const report = (data.weekly_reports || []).find(r => r.id === exp.report_id);")
w()
w("  const samplesWithEvidence = samples.map(s => ({")
w("    ...s,")
w("    evidence: s.evidence_snapshot || getEvidenceChain(s.id, data)")
w("  }));")
w()
w("  let diff = null;")
w("  if (prevExport && prevExport.snapshot_data) {")
w("    const prevMap = new Map(prevExport.snapshot_data.map(s => [String(s.id), s]));")
w("    const currMap = new Map(samples.map(s => [String(s.id), s]));")
w("    const changes = [];")
w()
w("    samples.forEach(curr => {")
w("      const prev = prevMap.get(String(curr.id));")
w("      if (prev) {")
w("        const itemChanges = [];")
w("        ['processing_status', 'manual_remark', 'is_bucket_diff_anomaly',")
w("         'recall_candidate_added', 'offline_bucket', 'online_bucket'].forEach(field => {")
w("          if (JSON.stringify(prev[field]) !== JSON.stringify(curr[field])) {")
w("            itemChanges.push({ field, from: prev[field], to: curr[field] });")
w("          }")
w("        });")
w("        if (itemChanges.length > 0) {")
w("          changes.push({")
w("            id: curr.id, item_id: curr.item_id, item_title: curr.item_title,")
w("            original_line_no: curr.original_line_no, changes: itemChanges")
w("          });")
w("        }")
w("      }")
w("    });")
w()
w("    const added = samples.filter(s => !prevMap.has(String(s.id)));")
w("    const removed = prevExport.snapshot_data.filter(s => !currMap.has(String(s.id)));")
w("    diff = {")
w("      prev_export_id: prevExport.id,")
w("      prev_exported_at: prevExport.created_at,")
w("      changes, added, removed")
w("    };")
w("  }")
w()
w("  res.json({")
w("    export: {")
w("      id: exp.id,")
w("      report_id: exp.report_id,")
w("      export_type: exp.export_type,")
w("      content_hash: exp.content_hash,")
w("      exported_by: exp.exported_by,")
w("      created_at: exp.created_at,")
w("      sample_count: samples.length")
w("    },")
w("    report,")
w("    samples: samplesWithEvidence,")
w("    diff,")
w("    anomaly_summary: samples.filter(s => s.is_bucket_diff_anomaly === 1).map(s => ({")
w("      id: s.id, item_id: s.item_id, item_title: s.item_title,")
w("      original_line_no: s.original_line_no, offline_score: s.offline_score,")
w("      online_score: s.online_score, offline_bucket: s.offline_bucket,")
w("      online_bucket: s.online_bucket, processing_status: s.processing_status,")
w("      manual_remark: s.manual_remark")
w("    }))")
w("  });")
w("});")
w()
w("app.get('/api/samples/:id/evidence', (req, res) => {")
w("  const sampleId = parseInt(req.params.id);")
w("  const data = loadJSON();")
w("  const sample = (data.negative_samples || []).find(s => s.id === sampleId);")
w("  if (!sample) return res.status(404).json({ error: 'Sample not found' });")
w("  const evidence = getEvidenceChain(sampleId, data);")
w("  res.json({ sample, evidence });")
w("});")
w()
w("app.patch('/api/reports/:id/samples/status', (req, res) => {")
w("  const reportId = parseInt(req.params.id);")
w("  const { sample_ids, processing_status, operator, remark } = req.body;")
w("  if (!sample_ids || !processing_status) {")
w("    return res.status(400).json({ error: 'Missing parameters' });")
w("  }")
w()
w("  const data = loadJSON();")
w("  const oper = operator || 'system';")
w("  const rmk = remark || '批量更新状态';")
w("  let updatedCount = 0;")
w()
w("  sample_ids.forEach(sid => {")
w("    const sample = (data.negative_samples || []).find(s => s.id === sid && s.report_id === reportId);")
w("    if (sample) {")
w("      const oldStatus = sample.processing_status;")
w("      sample.processing_status = processing_status;")
w("      sample.updated_at = now();")
w("      updatedCount++;")
w("      insertRow(")
w("        'sample_audit_logs',")
w("        ['sample_id', 'action', 'old_value', 'new_value', 'operator', 'remark'],")
w("        [sid, 'update_status', oldStatus, processing_status, oper, rmk]")
w("      );")
w("    }")
w("  });")
w()
w("  saveDB(data);")
w("  res.json({ updated: updatedCount, status: processing_status });")
w("});")
w()
w("app.get('/api/exports/:id/csv', (req, res) => {")
w("  const exportId = parseInt(req.params.id);")
w("  const data = loadJSON();")
w("  const exp = (data.export_records || []).find(e => e.id === exportId);")
w("  if (!exp) return res.status(404).json({ error: 'Export not found' });")
w("  if (!exp.snapshot_data) return res.status(400).json({ error: 'No snapshot data' });")
w()
w("  const samples = exp.snapshot_data;")
w("  const json2csvParser = new Parser({")
w("    fields: [")
w("      '原始行号', '物料ID', '物料标题', '离线分数', '线上分数',")
w("      '离线分桶', '线上分桶', '分桶差值', '分差一桶异常',")
w("      '人工备注', '处理状态', '已关联召回候选'")
w("    ]")
w("  });")
w()
w("  const csvData = samples.map(s => ({")
w("    '原始行号': s.original_line_no,")
w("    '物料ID': s.item_id,")
w("    '物料标题': s.item_title,")
w("    '离线分数': s.offline_score,")
w("    '线上分数': s.online_score,")
w("    '离线分桶': s.offline_bucket,")
w("    '线上分桶': s.online_bucket,")
w("    '分桶差值': s.bucket_diff,")
w("    '分差一桶异常': s.is_bucket_diff_anomaly ? '是' : '否',")
w("    '人工备注': s.manual_remark || '',")
w("    '处理状态': s.processing_status,")
w("    '已关联召回候选': s.recall_candidate_added ? '是' : '否'")
w("  }));")
w()
w("  const csv = json2csvParser.parse(csvData);")
w("  res.setHeader('Content-Type', 'text/csv; charset=utf-8');")
w("  res.setHeader('Content-Disposition', `attachment; filename=\"weekly_report_export_${exportId}_snapshot.csv\"`);")
w("  res.send('\\uFEFF' + csv);")
w("});")
w()
w("app.get('/', (req, res) => {")
w("  res.sendFile(path.join(__dirname, '..', 'public', 'index.html'));")
w("});")
w()
w("app.listen(PORT, () => {")
w("  console.log('推荐探索率周报系统已启动: http://localhost:' + PORT);")
w("});")
w()

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')

import os.path
print(f'生成完成: {OUT}')
print(f'大小: {os.path.getsize(OUT)} bytes')
print(f'行数: {len(lines)}')
