openapi: 3.0.0
info:
  title: Dirty API (with outdated examples)
  version: 1.0.0
servers:
  - url: https://jsonplaceholder.typicode.com
paths:
  /users:
    get:
      summary: Get users (example name is outdated)
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              example:
                - id: 1
                  name: John Doe (Outdated)
  /posts:
    post:
      summary: Create a post (expected status code is wrong)
      requestBody:
        content:
          application/json:
            example:
              title: foo
              body: bar
              userId: 1
      responses:
        '400':
          description: Expected bad request but actual is 201
          content:
            application/json:
              example:
                error: "Bad Request"
