const { format, addDays } = require('date-fns');

const ACTIVITY_STATUS = {
  DRAFT: 'DRAFT',
  PLANNED: 'PLANNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

const SAMPLE_STATUS = {
  ARCHIVED: 'ARCHIVED',
  IN_INSPECTION: 'IN_INSPECTION',
  DESTROYED: 'DESTROYED',
  RETAINED_FOR_INVESTIGATION: 'RETAINED_FOR_INVESTIGATION'
};

const COMPLAINT_STATUS = {
  PENDING: 'PENDING',
  UNDER_INVESTIGATION: 'UNDER_INVESTIGATION',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};

const REPORT_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED'
};

const STATUS_TRANSITIONS = {
  activities: {
    [ACTIVITY_STATUS.DRAFT]: [ACTIVITY_STATUS.PLANNED],
    [ACTIVITY_STATUS.PLANNED]: [ACTIVITY_STATUS.IN_PROGRESS, ACTIVITY_STATUS.CANCELLED],
    [ACTIVITY_STATUS.IN_PROGRESS]: [ACTIVITY_STATUS.COMPLETED, ACTIVITY_STATUS.CANCELLED],
    [ACTIVITY_STATUS.COMPLETED]: [],
    [ACTIVITY_STATUS.CANCELLED]: []
  },
  samples: {
    [SAMPLE_STATUS.ARCHIVED]: [SAMPLE_STATUS.IN_INSPECTION, SAMPLE_STATUS.RETAINED_FOR_INVESTIGATION, SAMPLE_STATUS.DESTROYED],
    [SAMPLE_STATUS.IN_INSPECTION]: [SAMPLE_STATUS.DESTROYED, SAMPLE_STATUS.RETAINED_FOR_INVESTIGATION, SAMPLE_STATUS.ARCHIVED],
    [SAMPLE_STATUS.RETAINED_FOR_INVESTIGATION]: [SAMPLE_STATUS.DESTROYED],
    [SAMPLE_STATUS.DESTROYED]: []
  },
  complaints: {
    [COMPLAINT_STATUS.PENDING]: [COMPLAINT_STATUS.UNDER_INVESTIGATION],
    [COMPLAINT_STATUS.UNDER_INVESTIGATION]: [COMPLAINT_STATUS.RESOLVED, COMPLAINT_STATUS.CLOSED],
    [COMPLAINT_STATUS.RESOLVED]: [COMPLAINT_STATUS.CLOSED],
    [COMPLAINT_STATUS.CLOSED]: []
  },
  reports: {
    [REPORT_STATUS.PENDING]: [REPORT_STATUS.IN_PROGRESS],
    [REPORT_STATUS.IN_PROGRESS]: [REPORT_STATUS.COMPLETED],
    [REPORT_STATUS.COMPLETED]: []
  }
};

const isValidStatusTransition = (entityType, currentStatus, targetStatus) => {
  const transitions = STATUS_TRANSITIONS[entityType];
  if (!transitions) return false;
  const allowed = transitions[currentStatus] || [];
  return allowed.includes(targetStatus);
};

const calculateDestroyDeadline = (archiveDate, shelfLifeDays = 7) => {
  const date = new Date(archiveDate);
  return format(addDays(date, shelfLifeDays), 'yyyy-MM-dd');
};

const now = () => format(new Date(), 'yyyy-MM-dd HH:mm:ss');

module.exports = {
  ACTIVITY_STATUS,
  SAMPLE_STATUS,
  COMPLAINT_STATUS,
  REPORT_STATUS,
  STATUS_TRANSITIONS,
  isValidStatusTransition,
  calculateDestroyDeadline,
  now
};
