const STAGES = {
  INIT: 'init',
  DATA_PREPARE: 'data_prepare',
  INDEX_BUILDING: 'index_building',
  VERIFICATION: 'verification',
  GRAY_RELEASE: 'gray_release',
  FULL_SWITCH: 'full_switch',
  COMPLETED: 'completed',
  FAILED: 'failed',
  ROLLED_BACK: 'rolled_back'
};

const STATUSES = {
  PENDING: 'pending',
  RUNNING: 'running',
  PAUSED: 'paused',
  SUCCESS: 'success',
  FAILED: 'failed',
  BLOCKED: 'blocked'
};

const STAGE_TRANSITIONS = {
  [STAGES.INIT]: {
    allowedTo: [STAGES.DATA_PREPARE, STAGES.FAILED],
    allowedStatuses: [STATUSES.PENDING, STATUSES.RUNNING, STATUSES.FAILED]
  },
  [STAGES.DATA_PREPARE]: {
    allowedTo: [STAGES.INDEX_BUILDING, STAGES.PAUSED, STAGES.FAILED, STAGES.ROLLED_BACK],
    allowedStatuses: [STATUSES.RUNNING, STATUSES.PAUSED, STATUSES.SUCCESS, STATUSES.FAILED]
  },
  [STAGES.INDEX_BUILDING]: {
    allowedTo: [STAGES.VERIFICATION, STAGES.PAUSED, STAGES.FAILED, STAGES.ROLLED_BACK],
    allowedStatuses: [STATUSES.RUNNING, STATUSES.PAUSED, STATUSES.SUCCESS, STATUSES.FAILED]
  },
  [STAGES.VERIFICATION]: {
    allowedTo: [STAGES.GRAY_RELEASE, STAGES.PAUSED, STAGES.FAILED, STAGES.ROLLED_BACK],
    allowedStatuses: [STATUSES.RUNNING, STATUSES.PAUSED, STATUSES.SUCCESS, STATUSES.FAILED, STATUSES.BLOCKED]
  },
  [STAGES.GRAY_RELEASE]: {
    allowedTo: [STAGES.FULL_SWITCH, STAGES.PAUSED, STAGES.FAILED, STAGES.ROLLED_BACK],
    allowedStatuses: [STATUSES.RUNNING, STATUSES.PAUSED, STATUSES.SUCCESS, STATUSES.FAILED, STATUSES.BLOCKED]
  },
  [STAGES.FULL_SWITCH]: {
    allowedTo: [STAGES.COMPLETED, STAGES.FAILED, STAGES.ROLLED_BACK],
    allowedStatuses: [STATUSES.RUNNING, STATUSES.SUCCESS, STATUSES.FAILED]
  },
  [STAGES.COMPLETED]: {
    allowedTo: [],
    allowedStatuses: [STATUSES.SUCCESS]
  },
  [STAGES.FAILED]: {
    allowedTo: [STAGES.DATA_PREPARE, STAGES.INDEX_BUILDING, STAGES.VERIFICATION],
    allowedStatuses: [STATUSES.FAILED]
  },
  [STAGES.ROLLED_BACK]: {
    allowedTo: [],
    allowedStatuses: [STATUSES.SUCCESS]
  },
  [STAGES.PAUSED]: {
    allowedTo: [STAGES.DATA_PREPARE, STAGES.INDEX_BUILDING, STAGES.VERIFICATION, STAGES.GRAY_RELEASE],
    allowedStatuses: [STATUSES.PAUSED]
  }
};

const STAGE_NAMES = {
  [STAGES.INIT]: '初始化',
  [STAGES.DATA_PREPARE]: '数据准备',
  [STAGES.INDEX_BUILDING]: '索引构建',
  [STAGES.VERIFICATION]: '验证查询',
  [STAGES.GRAY_RELEASE]: '灰度发布',
  [STAGES.FULL_SWITCH]: '全量切换',
  [STAGES.COMPLETED]: '已完成',
  [STAGES.FAILED]: '失败',
  [STAGES.ROLLED_BACK]: '已回滚',
  [STAGES.PAUSED]: '已暂停'
};

const STATUS_NAMES = {
  [STATUSES.PENDING]: '待执行',
  [STATUSES.RUNNING]: '执行中',
  [STATUSES.PAUSED]: '已暂停',
  [STATUSES.SUCCESS]: '成功',
  [STATUSES.FAILED]: '失败',
  [STATUSES.BLOCKED]: '已拦截'
};

module.exports = {
  STAGES,
  STATUSES,
  STAGE_TRANSITIONS,
  STAGE_NAMES,
  STATUS_NAMES
};