export const ERROR_RULES = {
  PAYMENT_INVOICE_AMOUNT_MISMATCH: 'PAYMENT_INVOICE_AMOUNT_MISMATCH',
  INVOICE_SUMMARY_INCONSISTENCY: 'INVOICE_SUMMARY_INCONSISTENCY',
  DUPLICATE_INVOICE_NO: 'DUPLICATE_INVOICE_NO',
  SILENT_OVERWRITE_PROHIBITED: 'SILENT_OVERWRITE_PROHIBITED',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_DATE: 'INVALID_DATE',
  INVALID_STATUS: 'INVALID_STATUS'
};

export const ERROR_MESSAGES = {
  [ERROR_RULES.PAYMENT_INVOICE_AMOUNT_MISMATCH]: '付款金额与票据金额不一致',
  [ERROR_RULES.INVOICE_SUMMARY_INCONSISTENCY]: '票据汇总金额与明细金额不一致',
  [ERROR_RULES.DUPLICATE_INVOICE_NO]: '票据编号已存在，禁止静默覆盖',
  [ERROR_RULES.SILENT_OVERWRITE_PROHIBITED]: '禁止静默覆盖已有记录',
  [ERROR_RULES.REQUIRED_FIELD_MISSING]: '必填字段缺失',
  [ERROR_RULES.INVALID_AMOUNT]: '金额必须为正数',
  [ERROR_RULES.INVALID_DATE]: '日期格式无效',
  [ERROR_RULES.INVALID_STATUS]: '状态值无效，必须是 pending、approved 或 rejected'
};
