import pathlib
p = pathlib.Path('app/main.py')
L = p.read_text().splitlines()
L.append('')
L.append('def log_field(db, s, t, aid, reason, updates):')
L.append('    b, a = {}, {}')
L.append("    for f in ['student_name', 'student_id', 'class_name', 'meal_days', 'subsidy_amount']:")
L.append('        if f in updates:')
L.append('            b[f] = str(getattr(s, f))')
L.append('            a[f] = str(updates[f])')
L.append("    l = ChangeLog(task_id=t.id, submission_id=s.id, actor_id=aid, change_type='field', reason=reason, before_value=b, after_value=a)")
L.append('    db.add(l); db.flush()')
L.append('    for f in b:')
L.append('        fc = FieldChange(submission_id=s.id, change_log_id=l.id, field_name=f, before_value=b[f], after_value=a[f])')
L.append('        db.add(fc)')
L.append('    db.flush(); return l')
L.append('')
L.append('init_db()')
L.append('')
L.append("app = FastAPI(title='Subsidy API')")
L.append('')
p.write_text(chr(10).join(L))
