import pathlib
p = pathlib.Path('app/main.py')
L = p.read_text().splitlines()
L.append('')
L.append('@app.get("/")')
L.append('def root():')
L.append("    return {'service': '食堂留餐补贴处理服务', 'version': '1.0'}")
L.append('')
L.append('@app.post("/api/submissions", response_model=SubmissionResponse, status_code=201)')
L.append('def submit_submission(payload: SubsidySubmission, db: Session = Depends(get_db)):')
L.append('    existing = db.query(Submission).filter(Submission.batch_no == payload.batch_no).first()')
L.append('    if existing: raise HTTPException(status_code=400, detail="batch exists")')
L.append('    user = db.query(User).filter(User.username == "system").first()')
L.append('    if not user:')
L.append('        user = User(username="system", role="system")')
L.append('        db.add(user); db.commit(); db.refresh(user)')
L.append('    s = Submission(batch_no=payload.batch_no, submitted_by=user.id, student_name=payload.student_name, student_id=payload.student_id, class_name=payload.class_name, meal_days=payload.meal_days, subsidy_amount=payload.subsidy_amount, raw_payload=payload.model_dump())')
L.append('    db.add(s); db.flush()')
L.append('    t = Task(submission_id=s.id, state="processing")')
L.append('    db.add(t); db.flush()')
L.append('    try:')
L.append('        cat, reason, follow = classify_submission(db, s, t)')
L.append('        c = Classification(task_id=t.id, category=cat, reason=reason, follow_up_action=follow)')
L.append('        db.add(c)')
L.append('        t.state = "success" if cat == "normal" else "review_pending"')
L.append('    except Exception as e:')
L.append('        t.state = "failed"')
L.append('        t.error_message = str(e)')
L.append('    db.commit(); db.refresh(t)')
L.append('    return SubmissionResponse(submission_id=s.id, task_id=t.id, batch_no=payload.batch_no, state=t.state, message=f"classified: {cat}")')
L.append('')
p.write_text(chr(10).join(L))
