import pathlib
p = pathlib.Path('app/main.py')
L = p.read_text().splitlines()
L.append('')
L.append('@app.get("/api/tasks/{task_id}", response_model=TaskResponse)')
L.append('def get_task(task_id: int, db: Session = Depends(get_db)):')
L.append('    t = db.query(Task).filter(Task.id == task_id).first()')
L.append('    if not t: raise HTTPException(status_code=404, detail="not found")')
L.append('    r = TaskResponse(task_id=t.id, submission_id=t.submission_id, state=t.state, classification=None, created_at=t.created_at, updated_at=t.updated_at)')
L.append('    if t.classification:')
L.append('        r.classification = ClassificationResult(category=t.classification.category, reason=t.classification.reason, follow_up_action=t.classification.follow_up_action)')
L.append('    return r')
L.append('')
L.append('@app.post("/api/tasks/{task_id}/review", response_model=TaskResponse)')
L.append('def review_task(task_id: int, req: ReviewRequest, db: Session = Depends(get_db)):')
L.append('    t = db.query(Task).filter(Task.id == task_id).first()')
L.append('    if not t: raise HTTPException(status_code=404, detail="not found")')
L.append('    s = t.submission')
L.append('    actor = db.query(User).filter(User.id == req.actor_id).first()')
L.append('    if not actor:')
L.append('        actor = User(id=req.actor_id, username=f"user_{req.actor_id}", role="staff")')
L.append('        db.add(actor); db.flush()')
L.append('    if req.new_category and t.classification:')
L.append('        old = t.classification.category')
L.append('        if old != req.new_category: log_cat(db, t, s, req.actor_id, req.reason, old, req.new_category); t.classification.category = req.new_category')
L.append('    if req.new_state and t.state != req.new_state: log_state(db, t, s, req.actor_id, req.reason, t.state, req.new_state); t.state = req.new_state')
L.append('    if req.field_updates: log_field(db, s, t, req.actor_id, req.reason, req.field_updates)')
L.append('    db.commit(); db.refresh(t)')
L.append('    return get_task(task_id, db)')
L.append('')
p.write_text(chr(10).join(L))
