import pathlib
p = pathlib.Path('app/main.py')
L = p.read_text().splitlines()
L.append('')
L.append('@app.get("/api/tasks/{task_id}/audit", response_model=list[ChangeLogResponse])')
L.append('def get_audit_log(task_id: int, db: Session = Depends(get_db)):')
L.append('    logs = db.query(ChangeLog).filter(ChangeLog.task_id == task_id).order_by(ChangeLog.created_at.desc()).all()')
L.append('    return [ChangeLogResponse(id=log.id, task_id=log.task_id, actor_id=log.actor_id, change_type=log.change_type, reason=log.reason, before_value=log.before_value, after_value=log.after_value, created_at=log.created_at) for log in logs]')
L.append('')
L.append('@app.get("/api/submissions/{submission_id}/trace/{field_name}", response_model=FieldTraceResponse)')
L.append('def trace_field(submission_id: int, field_name: str, db: Session = Depends(get_db)):')
L.append('    s = db.query(Submission).filter(Submission.id == submission_id).first()')
L.append('    if not s: raise HTTPException(status_code=404, detail="not found")')
L.append('    TRACKED = ["student_name", "student_id", "class_name", "meal_days", "subsidy_amount"]')
L.append('    if field_name not in TRACKED: raise HTTPException(status_code=400, detail=f"only track: {TRACKED}")')
L.append('    raw = s.raw_payload.get(field_name)')
L.append('    curr = getattr(s, field_name)')
L.append('    changes = db.query(FieldChange).filter(FieldChange.submission_id == submission_id, FieldChange.field_name == field_name).order_by(FieldChange.created_at).all()')
L.append('    h = [{"change_log_id": c.change_log_id, "before": c.before_value, "after": c.after_value, "at": c.created_at} for c in changes]')
L.append('    return FieldTraceResponse(field_name=field_name, original_value=raw, current_value=curr, change_history=h)')
L.append('')
L.append('@app.post("/api/tasks/{task_id}/export", response_model=ExportReportResponse, status_code=201)')
L.append('def export_report(task_id: int, actor_id: int, db: Session = Depends(get_db)):')
L.append('    t = db.query(Task).filter(Task.id == task_id).first()')
L.append('    if not t: raise HTTPException(status_code=404, detail="not found")')
L.append('    s = t.submission')
L.append('    c = t.classification')
L.append('    rp = {"submission": {"batch_no": s.batch_no, "student_name": s.student_name, "student_id": s.student_id, "class_name": s.class_name, "meal_days": s.meal_days, "subsidy_amount": s.subsidy_amount}, "task": {"state": t.state}, "classification": {"category": c.category if c else None, "reason": c.reason if c else None, "follow_up_action": c.follow_up_action if c else None}, "trace": {"raw_payload": s.raw_payload, "audit_count": db.query(ChangeLog).filter(ChangeLog.task_id == task_id).count()}}')
L.append('    r = ExportReport(submission_id=s.id, task_id=t.id, report_payload=rp, exported_by=actor_id)')
L.append('    db.add(r)')
L.append('    if t.state != "exported":')
L.append('        log_state(db, t, s, actor_id, "export", t.state, "exported")')
L.append('        t.state = "exported"')
L.append('    db.commit(); db.refresh(r)')
L.append('    return ExportReportResponse(report_id=r.id, submission_id=r.submission_id, report_payload=r.report_payload, exported_by=r.exported_by, exported_at=r.exported_at)')
L.append('')
p.write_text(chr(10).join(L))
