import pathlib
p = pathlib.Path("app/main.py")
lines = p.read_text().splitlines()
lines.append("")
lines.append("class SubmissionResponse(BaseModel):")
lines.append("    submission_id: int")
lines.append("    task_id: int")
lines.append("    batch_no: str")
lines.append("    state: str")
lines.append("    message: str")
lines.append("")
lines.append("class ClassificationResult(BaseModel):")
lines.append("    category: str")
lines.append("    reason: str")
lines.append("    follow_up_action: str")
lines.append("")
lines.append("class TaskResponse(BaseModel):")
lines.append("    task_id: int")
lines.append("    submission_id: int")
lines.append("    state: str")
lines.append("    classification: Optional[ClassificationResult]")
lines.append("    created_at: datetime")
lines.append("    updated_at: datetime")
lines.append("")
lines.append("class ReviewRequest(BaseModel):")
lines.append("    actor_id: int")
lines.append("    reason: str")
lines.append("    new_category: Optional[str] = None")
lines.append("    new_state: Optional[str] = None")
lines.append("    field_updates: Optional[dict] = None")
lines.append("")
lines.append("class ChangeLogResponse(BaseModel):")
lines.append("    id: int")
lines.append("    task_id: int")
lines.append("    actor_id: int")
lines.append("    change_type: str")
lines.append("    reason: str")
lines.append("    before_value: Any")
lines.append("    after_value: Any")
lines.append("    created_at: datetime")
lines.append("")
lines.append("class FieldTraceResponse(BaseModel):")
lines.append("    field_name: str")
lines.append("    original_value: Any")
lines.append("    current_value: Any")
lines.append("    change_history: list")
lines.append("")
lines.append("class ExportReportResponse(BaseModel):")
lines.append("    report_id: int")
lines.append("    submission_id: int")
lines.append("    report_payload: dict")
lines.append("    exported_by: int")
lines.append("    exported_at: datetime")
p.write_text(chr(10).join(lines))
