import pathlib
p = pathlib.Path("app/main.py")
lines = p.read_text().splitlines()
lines.append("")
lines.append("def classify_submission(db, submission, task):")
lines.append(\"    apd = submission.subsidy_amount / submission.meal_days if submission.meal_days > 0 else 0\")
lines.append(\"    if not submission.student_id or not submission.class_name:\")
lines.append(\"        return (\"pending_supplement\", \"field missing\", \"please fill\")\")
lines.append(\"    if len(submission.student_id) < 6:\")
lines.append(\"        return (\"pending_supplement\", \"bad student_id\", \"check id\")\")
lines.append(\"    if submission.meal_days > 31:\")
lines.append(\"        return (\"intercepted\", \"days > 31\", \"verify days\")\")
lines.append(\"    if apd < 300:\")
lines.append(\"        return (\"intercepted\", \"amount too low\", \"verify amount\")\")
lines.append(\"    if apd > 5000:\")
lines.append(\"        return (\"intercepted\", \"amount too high\", \"verify amount\")\")
lines.append(\"    return (\"normal\", \"ok\", \"proceed\")\")
lines.append(\"\")
