import type { AudioMaterial } from '../types';

const generateId = () => Math.random().toString(36).substring(2, 11);

const now = new Date();
const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
const lastWeek = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
const expiredDate = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
const futureDate = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

const formatDate = (d: Date) => d.toISOString();

export const mockMaterials: AudioMaterial[] = [
  {
    id: generateId(),
    fileName: 'TRK_001_OpeningTheme.wav',
    trackName: '开场主题曲',
    emotionTag: '激昂',
    remark: '与排练群2024-05-10截图一致，确认可用',
    source: '曲目表',
    processedAt: formatDate(yesterday),
    processedBy: '小温',
    status: 'reviewed',
    exceptions: [],
    originalSource: '曲目表第3行，合同截图A区第2条',
    authorizationDate: formatDate(futureDate),
    timecode: '00:00:00 - 00:02:30',
  },
  {
    id: generateId(),
    fileName: 'BGM_LoveScene.mp3',
    trackName: '爱情场景配乐',
    emotionTag: '温馨',
    remark: '',
    source: '音频文件',
    processedAt: formatDate(now),
    processedBy: '小温',
    status: 'pending',
    exceptions: [],
    originalSource: '音频文件夹-爱情场景分类',
    authorizationDate: formatDate(futureDate),
    timecode: '00:00:00 - 00:01:45',
  },
  {
    id: generateId(),
    fileName: 'SFX_Suspense_01.aiff',
    trackName: '悬疑音效',
    emotionTag: '紧张',
    remark: '群里老张说这个音量要调小一点',
    source: '群聊批注',
    processedAt: formatDate(lastWeek),
    processedBy: '小温',
    status: 'reviewed',
    exceptions: [],
    originalSource: '排练群2024-05-08 14:32 消息',
    timecode: '00:00:05 - 00:00:15',
  },
  {
    id: generateId(),
    fileName: 'AUD_Expired_Track.wav',
    trackName: '过渡段落音乐',
    emotionTag: '',
    remark: '',
    source: '合同截图',
    processedAt: formatDate(now),
    processedBy: '',
    status: 'exception',
    exceptions: [
      {
        type: 'auth_expired',
        description: '授权日期已过期，需要重新申请',
        detectedAt: formatDate(now),
        resolved: false,
      },
    ],
    originalSource: '合同截图B区，授权已过期',
    authorizationDate: formatDate(expiredDate),
    timecode: '00:00:00 - 00:03:20',
  },
  {
    id: generateId(),
    fileName: 'TRK_005_Climax.wav',
    trackName: '高潮片段',
    emotionTag: '激昂',
    remark: '',
    source: '曲目表',
    processedAt: formatDate(yesterday),
    processedBy: '小温',
    status: 'exception',
    exceptions: [
      {
        type: 'timecode_mismatch',
        description: '时码格式异常，音频文件显示时长与曲目表不符',
        detectedAt: formatDate(yesterday),
        resolved: false,
      },
    ],
    originalSource: '曲目表第8行，时长标注不一致',
    timecode: 'invalid_format',
  },
  {
    id: generateId(),
    fileName: 'BGM_Duplicate_01.mp3',
    trackName: '森林背景音',
    emotionTag: '舒缓',
    remark: '与TRK_007重复，建议合并',
    source: '音频文件',
    processedAt: formatDate(lastWeek),
    processedBy: '小温',
    status: 'exception',
    exceptions: [
      {
        type: 'duplicate_track',
        description: '与"森林氛围音效"内容重复',
        detectedAt: formatDate(lastWeek),
        resolved: false,
      },
    ],
    originalSource: '音频文件夹-自然音效分类',
  },
  {
    id: generateId(),
    fileName: 'BGM_Duplicate_02.mp3',
    trackName: '森林氛围音效',
    emotionTag: '舒缓',
    remark: '',
    source: '曲目表',
    processedAt: formatDate(lastWeek),
    processedBy: '小温',
    status: 'exception',
    exceptions: [
      {
        type: 'duplicate_track',
        description: '与"森林背景音"内容重复',
        detectedAt: formatDate(lastWeek),
        resolved: false,
      },
    ],
    originalSource: '曲目表第12行',
  },
  {
    id: generateId(),
    fileName: 'VOC_Narration_01.wav',
    trackName: '旁白录音',
    emotionTag: '',
    remark: '空值测试用例，情绪标签待确定',
    source: '群聊批注',
    processedAt: formatDate(now),
    processedBy: '',
    status: 'pending',
    exceptions: [],
    originalSource: '排练群私发文件',
  },
  {
    id: generateId(),
    fileName: 'SFX_Silent_Edge.wav',
    trackName: '静音边界测试',
    emotionTag: '其他',
    remark: '边界记录：接近静音，情绪标签难以归类',
    source: '合同截图',
    processedAt: formatDate(yesterday),
    processedBy: '小温',
    status: 'reviewed',
    exceptions: [],
    originalSource: '合同附录-特殊音效清单',
    timecode: '00:00:00 - 00:00:01',
  },
  {
    id: generateId(),
    fileName: 'TRK_010_Ending.wav',
    trackName: '结尾曲',
    emotionTag: '欢快',
    remark: '多异常叠加：授权过期+时码错位',
    source: '曲目表',
    processedAt: formatDate(now),
    processedBy: '',
    status: 'exception',
    exceptions: [
      {
        type: 'auth_expired',
        description: '授权已过期15天',
        detectedAt: formatDate(now),
        resolved: false,
      },
      {
        type: 'timecode_mismatch',
        description: '开始时间大于结束时间',
        detectedAt: formatDate(now),
        resolved: false,
      },
    ],
    originalSource: '曲目表最后一行，有疑问',
    authorizationDate: formatDate(expiredDate),
    timecode: '00:05:00 - 00:03:00',
  },
  {
    id: generateId(),
    fileName: 'BGM_Sad_Scene.mp3',
    trackName: '悲伤场景',
    emotionTag: '悲伤',
    remark: '',
    source: '音频文件',
    processedAt: formatDate(lastWeek),
    processedBy: '小温',
    status: 'reviewed',
    exceptions: [],
    originalSource: '音频文件夹-情感分类',
    timecode: '00:00:00 - 00:02:15',
  },
  {
    id: generateId(),
    fileName: 'SFX_Mystery_Box.aiff',
    trackName: '神秘盒子音效',
    emotionTag: '神秘',
    remark: '老张说这个效果很好，保留',
    source: '群聊批注',
    processedAt: formatDate(yesterday),
    processedBy: '小温',
    status: 'resolved',
    exceptions: [
      {
        type: 'timecode_mismatch',
        description: '原时码格式错误，已手动修正',
        detectedAt: formatDate(lastWeek),
        resolved: true,
      },
    ],
    originalSource: '排练群2024-05-12 老张',
    timecode: '00:00:03 - 00:00:08',
  },
];
