import { Router, type Request, type Response } from 'express'
import db from '../db.js'
import { recordChange } from '../lib/auditEngine.js'
import type { SafetyZone } from '../../shared/types.js'

const router = Router()

router.get('/stats', async (req: Request, res: Response): Promise<void> => {
  try {
    const totalStmt = db.prepare('SELECT COUNT(*) as cnt FROM safety_zone')
    const totalZones = (totalStmt.get() as { cnt: number }).cnt

    const pendingStmt = db.prepare('SELECT COUNT(*) as cnt FROM safety_zone WHERE review_status = ?')
    const pendingReview = (pendingStmt.get('pending') as { cnt: number }).cnt

    const approvedStmt = db.prepare('SELECT COUNT(*) as cnt FROM safety_zone WHERE review_status = ?')
    const approved = (approvedStmt.get('approved') as { cnt: number }).cnt

    const rollbackStmt = db.prepare('SELECT COUNT(*) as cnt FROM safety_zone WHERE review_status = ?')
    const rollback = (rollbackStmt.get('rollback') as { cnt: number }).cnt

    const autoStmt = db.prepare('SELECT COUNT(*) as cnt FROM safety_zone WHERE coefficient_source = ?')
    const autoGenerated = (autoStmt.get('auto') as { cnt: number }).cnt

    const manualStmt = db.prepare('SELECT COUNT(*) as cnt FROM safety_zone WHERE coefficient_source = ?')
    const manualModified = (manualStmt.get('manual') as { cnt: number }).cnt

    res.status(200).json({
      success: true,
      data: {
        totalZones,
        pendingReview,
        approved,
        rollback,
        autoGenerated,
        manualModified,
      },
    })
  } catch (error) {
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Failed to fetch stats',
    })
  }
})

router.get('/pending-review', async (req: Request, res: Response): Promise<void> => {
  try {
    const page = parseInt(req.query.page as string) || 1
    const pageSize = parseInt(req.query.pageSize as string) || 20
    const offset = (page - 1) * pageSize

    const whereClause = 'WHERE sz.review_status = ? AND sz.coefficient_source = ? AND sz.coefficient_reason IS NULL'
    const params = ['pending', 'manual']

    const countStmt = db.prepare(`SELECT COUNT(*) as cnt FROM safety_zone sz ${whereClause}`)
    const total = (countStmt.get(...params) as { cnt: number }).cnt

    const query = `
      SELECT sz.*, s.sensor_code, s.material_type
      FROM safety_zone sz
      LEFT JOIN sensor_data s ON sz.sensor_id = s.id
      ${whereClause}
      ORDER BY sz.created_at DESC
      LIMIT ? OFFSET ?
    `
    const zones = db.prepare(query).all(...params, pageSize, offset)

    res.status(200).json({
      success: true,
      data: {
        list: zones,
        total,
        page,
        pageSize,
      },
    })
  } catch (error) {
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Failed to fetch pending review zones',
    })
  }
})

router.get('/', async (req: Request, res: Response): Promise<void> => {
  try {
    const reviewStatus = req.query.review_status as string | undefined
    const page = parseInt(req.query.page as string) || 1
    const pageSize = parseInt(req.query.pageSize as string) || 20
    const offset = (page - 1) * pageSize

    let whereClause = ''
    const params: unknown[] = []

    if (reviewStatus) {
      whereClause = 'WHERE sz.review_status = ?'
      params.push(reviewStatus)
    }

    const countStmt = db.prepare(`SELECT COUNT(*) as cnt FROM safety_zone sz ${whereClause}`)
    const total = (countStmt.get(...params) as { cnt: number }).cnt

    const query = `
      SELECT sz.*, s.sensor_code
      FROM safety_zone sz
      LEFT JOIN sensor_data s ON sz.sensor_id = s.id
      ${whereClause}
      ORDER BY sz.created_at DESC
      LIMIT ? OFFSET ?
    `
    const zones = db.prepare(query).all(...params, pageSize, offset) as Array<SafetyZone & { sensor_code: string }>

    res.status(200).json({
      success: true,
      data: {
        list: zones,
        total,
        page,
        pageSize,
      },
    })
  } catch (error) {
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Failed to fetch safety zones',
    })
  }
})

router.get('/:id', async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params

    const zone = db
      .prepare(
        `
      SELECT sz.*, s.sensor_code, s.material_type, s.rpm_min as sensor_rpm_min, s.rpm_max as sensor_rpm_max
      FROM safety_zone sz
      LEFT JOIN sensor_data s ON sz.sensor_id = s.id
      WHERE sz.id = ?
    `
      )
      .get(id) as (SafetyZone & { sensor_code: string; material_type: string; sensor_rpm_min: number; sensor_rpm_max: number }) | undefined

    if (!zone) {
      res.status(404).json({ success: false, error: 'Safety zone not found' })
      return
    }

    const photos = db.prepare('SELECT * FROM photo_meta WHERE sensor_id = ? ORDER BY uploaded_at DESC').all(zone.sensor_id)

    res.status(200).json({
      success: true,
      data: {
        ...zone,
        photos,
      },
    })
  } catch (error) {
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Failed to fetch safety zone',
    })
  }
})

router.post('/:id/review', async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params
    const { action, comment, reviewer = 'system', reason } = req.body

    if (!action || !['approve', 'rollback'].includes(action)) {
      res.status(400).json({ success: false, error: 'Valid action is required (approve/rollback)' })
      return
    }

    if (!comment || typeof comment !== 'string' || comment.trim() === '') {
      res.status(400).json({ success: false, error: 'Comment is required' })
      return
    }

    const zone = db.prepare('SELECT * FROM safety_zone WHERE id = ?').get(id) as SafetyZone | undefined

    if (!zone) {
      res.status(404).json({ success: false, error: 'Safety zone not found' })
      return
    }

    const oldStatus = zone.review_status
    const oldComment = zone.review_comment
    const oldReviewer = zone.reviewer
    const oldReviewedAt = zone.reviewed_at
    const oldVersion = zone.version

    const newStatus = action === 'approve' ? 'approved' : 'rollback'
    const newVersion = oldVersion + 1
    const now = new Date().toISOString().replace('T', ' ').replace(/\.\d+Z$/, '')

    const tx = db.transaction(() => {
      db.prepare(
        'UPDATE safety_zone SET review_status = ?, reviewer = ?, review_comment = ?, reviewed_at = ?, version = ?, updated_at = ? WHERE id = ?'
      ).run(newStatus, reviewer, comment, now, newVersion, now, id)

      recordChange({
        targetType: 'safety_zone',
        targetId: id,
        field: 'review_status',
        oldValue: oldStatus,
        newValue: newStatus,
        operator: reviewer,
        reason: reason || comment,
      })

      recordChange({
        targetType: 'safety_zone',
        targetId: id,
        field: 'review_comment',
        oldValue: oldComment || '',
        newValue: comment,
        operator: reviewer,
        reason: reason || comment,
      })

      recordChange({
        targetType: 'safety_zone',
        targetId: id,
        field: 'version',
        oldValue: oldVersion,
        newValue: newVersion,
        operator: reviewer,
        reason: reason || comment,
      })
    })

    tx()

    const updatedZone = db
      .prepare(
        `
      SELECT sz.*, s.sensor_code
      FROM safety_zone sz
      LEFT JOIN sensor_data s ON sz.sensor_id = s.id
      WHERE sz.id = ?
    `
      )
      .get(id)

    res.status(200).json({
      success: true,
      data: updatedZone,
    })
  } catch (error) {
    res.status(500).json({
      success: false,
      error: error instanceof Error ? error.message : 'Failed to review safety zone',
    })
  }
})

export default router
