const fs = require('fs');
const path = require('path');

const srcDir = path.join(__dirname, 'src');

function createMatrixBuilder() {
  const lines = [
    "class MatrixBuilder {",
    "  constructor() {",
    "    this.retryCategories = {",
    "      TRANSIENT: { name: 'Transient Errors', description: '可重试的临时错误', retryable: true },",
    "      PERMANENT: { name: 'Permanent Errors', description: '不可重试的永久错误', retryable: false },",
    "      CLIENT_ERROR: { name: 'Client Errors', description: '客户端错误', retryable: false },",
    "      SERVER_ERROR: { name: 'Server Errors', description: '服务端错误', retryable: true }",
    "    };",
    "  }",
    "",
    "  buildMatrix(protoErrorCodes, sdkDefinitions) {",
    "    sdkDefinitions = sdkDefinitions || {};",
    "    const matrix = {",
    "      timestamp: new Date().toISOString(),",
    "      summary: { totalCodes: 0, withRetryStrategy: 0, withoutRetryStrategy: 0, categories: {} },",
    "      errorCodes: [],",
    "      categories: this.initializeCategories(),",
    "      conflicts: []",
    "    };",
    "    const allCodes = this.mergeCodes(protoErrorCodes, sdkDefinitions);",
    "    for (const codeData of allCodes) {",
    "      const category = this.categorizeError(codeData);",
    "      const matrixEntry = this.createMatrixEntry(codeData, category);",
    "      matrix.errorCodes.push(matrixEntry);",
    "      matrix.categories[category.key].codes.push(matrixEntry);",
    "    }",
    "    this.calculateSummary(matrix);",
    "    return matrix;",
    "  }",
    "",
    "  initializeCategories() {",
    "    const categories = {};",
    "    for (const [key, value] of Object.entries(this.retryCategories)) {",
    "      categories[key] = { ...value, key: key, codes: [], count: 0 };",
    "    }",
    "    return categories;",
    "  }",
    "",
    "  mergeCodes(protoCodes, sdkDefinitions) {",
    "    const codeMap = new Map();",
    "    for (const pc of protoCodes) {",
    "      const key = pc.code.toString();",
    "      if (!codeMap.has(key)) {",
    "        codeMap.set(key, { code: pc.code, name: pc.name, proto: { enumName: pc.enumName, fullName: pc.fullName, package: pc.package }, sdks: {} });",
    "      }",
    "    }",
    "    if (sdkDefinitions.sdks) {",
    "      for (const [sdkName, sdkData] of Object.entries(sdkDefinitions.sdks)) {",
    "        if (sdkData.errorCodes) {",
    "          for (const [codeName, codeValue] of Object.entries(sdkData.errorCodes)) {",
    "            const key = codeValue.toString();",
    "            if (!codeMap.has(key)) {",
    "              codeMap.set(key, { code: codeValue, name: codeName, proto: null, sdks: {} });",
    "            }",
    "            codeMap.get(key).sdks[sdkName] = { name: codeName, value: codeValue };",
    "          }",
    "        }",
    "      }",
    "    }",
    "    return Array.from(codeMap.values());",
    "  }",
    "",
    "  categorizeError(codeData) {",
    "    const code = codeData.code;",
    "    const name = codeData.name.toLowerCase();",
    "    if (name.includes('not_found') || name.includes('notfound')) return { key: 'PERMANENT', ...this.retryCategories.PERMANENT };",
    "    if (name.includes('invalid') || name.includes('bad_request')) return { key: 'CLIENT_ERROR', ...this.retryCategories.CLIENT_ERROR };",
    "    if (name.includes('unavailable') || name.includes('timeout') || name.includes('internal') || name.includes('deadline')) return { key: 'TRANSIENT', ...this.retryCategories.TRANSIENT };",
    "    if (code >= 50000 && code < 60000) return { key: 'SERVER_ERROR', ...this.retryCategories.SERVER_ERROR };",
    "    if (code >= 40000 && code < 50000) return { key: 'CLIENT_ERROR', ...this.retryCategories.CLIENT_ERROR };",
    "    return { key: 'PERMANENT', ...this.retryCategories.PERMANENT };",
    "  }",
    "",
    "  createMatrixEntry(codeData, category) {",
    "    return {",
    "      code: codeData.code, name: codeData.name, category: category.key, retryable: category.retryable,",
    "      retryStrategy: this.getRetryStrategy(category.key, codeData),",
    "      proto: codeData.proto, sdks: codeData.sdks, sdkConsistency: this.checkSdkConsistency(codeData)",
    "    };",
    "  }",
    "",
    "  getRetryStrategy(category, codeData) {",
    "    const strategies = {",
    "      TRANSIENT: { maxRetries: 3, backoff: 'exponential', initialDelay: 100, maxDelay: 5000 },",
    "      SERVER_ERROR: { maxRetries: 2, backoff: 'linear', initialDelay: 500, maxDelay: 2000 },",
    "      CLIENT_ERROR: { maxRetries: 0, backoff: 'none' },",
    "      PERMANENT: { maxRetries: 0, backoff: 'none' }",
    "    };",
    "    return strategies[category] || strategies.PERMANENT;",
    "  }",
    "",
    "  checkSdkConsistency(codeData) {",
    "    const sdkNames = Object.keys(codeData.sdks);",
    "    if (sdkNames.length <= 1) return { consistent: true, issues: [] };",
    "    const issues = [];",
    "    const referenceName = codeData.sdks[sdkNames[0]].name;",
    "    for (let i = 1; i < sdkNames.length; i++) {",
    "      if (codeData.sdks[sdkNames[i]].name !== referenceName) {",
    "        issues.push({ sdk1: sdkNames[0], sdk2: sdkNames[i], message: 'Naming mismatch' });",
    "      }",
    "    }",
    "    return { consistent: issues.length === 0, issues: issues };",
    "  }",
    "",
    "  calculateSummary(matrix) {",
    "    matrix.summary.totalCodes = matrix.errorCodes.length;",
    "    matrix.summary.withRetryStrategy = matrix.errorCodes.filter(e => e.retryStrategy.maxRetries > 0).length;",
    "    matrix.summary.withoutRetryStrategy = matrix.errorCodes.filter(e => e.retryStrategy.maxRetries === 0).length;",
    "    for (const [key, category] of Object.entries(matrix.categories)) {",
    "      category.count = category.codes.length;",
    "      matrix.summary.categories[key] = category.count;",
    "    }",
    "  }",
    "",
    "  getRetryableCodes(matrix) { return matrix.errorCodes.filter(e => e.retryable); }",
    "  getNonRetryableCodes(matrix) { return matrix.errorCodes.filter(e => !e.retryable); }",
    "}",
    "",
    "module.exports = MatrixBuilder;"
  ];
  return lines.join('\n');
}

function createReportGenerator() {
  const lines = [
    "const fs = require('fs');",
    "const path = require('path');",
    "const chalk = require('chalk');",
    "const { table } = require('table');",
    "",
    "class ReportGenerator {",
    "  constructor(options) {",
    "    this.options = options || {};",
    "    this.chalk = new chalk.Instance({ level: 3 });",
    "  }",
    "",
    "  generateConsoleReport(matrix) {",
    "    let output = '';",
    "    output += this.generateSummarySection(matrix);",
    "    output += this.generateCategorySection(matrix);",
    "    output += this.generateErrorCodesTable(matrix);",
    "    return output;",
    "  }",
    "",
    "  generateSummarySection(matrix) {",
    "    let output = '';",
    "    output += this.chalk.bold.yellow('Summary\\n');",
    "    const summary = matrix.summary;",
    "    const summaryData = [",
    "      ['Total', summary.totalCodes.toString()],",
    "      ['With retry', summary.withRetryStrategy.toString()],",
    "      ['Without retry', summary.withoutRetryStrategy.toString()]",
    "    ];",
    "    output += table(summaryData);",
    "    output += '\\n';",
    "    return output;",
    "  }",
    "",
    "  generateCategorySection(matrix) {",
    "    let output = '';",
    "    output += this.chalk.bold.yellow('Categories\\n\\n');",
    "    for (const [key, category] of Object.entries(matrix.categories)) {",
    "      output += category.name + ' (' + category.count + ')\\n';",
    "      output += '  ' + category.description + '\\n';",
    "      output += '  Retryable: ' + (category.retryable ? 'YES' : 'NO') + '\\n\\n';",
    "    }",
    "    return output;",
    "  }",
    "",
    "  generateErrorCodesTable(matrix) {",
    "    let output = '';",
    "    output += this.chalk.bold.yellow('Error Codes\\n\\n');",
    "    const tableData = [['Code', 'Name', 'Category', 'Retryable', 'Max Retries']];",
    "    for (const ec of matrix.errorCodes) {",
    "      tableData.push([",
    "        ec.code.toString(), ec.name, ec.category,",
    "        ec.retryable ? 'YES' : 'NO', ec.retryStrategy.maxRetries.toString()",
    "      ]);",
    "    }",
    "    output += table(tableData);",
    "    return output;",
    "  }",
    "",
    "  generateJsonReport(matrix, outputPath) {",
    "    const jsonContent = JSON.stringify(matrix, null, 2);",
    "    if (outputPath) {",
    "      const dir = path.dirname(outputPath);",
    "      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });",
    "      fs.writeFileSync(outputPath, jsonContent, 'utf8');",
    "    }",
    "    return jsonContent;",
    "  }",
    "",
    "  generateMarkdownReport(matrix, outputPath) {",
    "    let md = '# gRPC Error Code Matrix Report\\n\\n';",
    "    md += '*Generated: ' + new Date(matrix.timestamp).toLocaleString() + '*\\n\\n';",
    "    md += '## Summary\\n\\n';",
    "    md += 'Total error codes: ' + matrix.summary.totalCodes + '\\n\\n';",
    "    md += '## Error Codes\\n\\n';",
    "    md += '| Code | Name | Category | Retryable | Max Retries |\\n';",
    "    md += '|------|------|----------|-----------|-------------|\\n';",
    "    for (const ec of matrix.errorCodes) {",
    "      md += '| ' + ec.code + ' | ' + ec.name + ' | ' + ec.category + ' | ' + (ec.retryable ? 'YES' : 'NO') + ' | ' + ec.retryStrategy.maxRetries + ' |\\n';",
    "    }",
    "    md += '\\n';",
    "    if (outputPath) {",
    "      const dir = path.dirname(outputPath);",
    "      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });",
    "      fs.writeFileSync(outputPath, md, 'utf8');",
    "    }",
    "    return md;",
    "  }",
    "",
    "  generateAllReports(matrix, outputDir) {",
    "    const reports = {};",
    "    reports.console = this.generateConsoleReport(matrix);",
    "    if (outputDir) {",
    "      if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });",
    "      reports.jsonPath = path.join(outputDir, 'error-matrix.json');",
    "      reports.json = this.generateJsonReport(matrix, reports.jsonPath);",
    "      reports.markdownPath = path.join(outputDir, 'error-matrix.md');",
    "      reports.markdown = this.generateMarkdownReport(matrix, reports.markdownPath);",
    "    }",
    "    return reports;",
    "  }",
    "}",
    "",
    "module.exports = ReportGenerator;"
  ];
  return lines.join('\n');
}

function createCli() {
  const lines = [
    "#!/usr/bin/env node",
    "",
    "const { Command } = require('commander');",
    "const fs = require('fs');",
    "const path = require('path');",
    "",
    "const ProtoParser = require('./proto-parser');",
    "const MatrixBuilder = require('./matrix-builder');",
    "const ReportGenerator = require('./report-generator');",
    "",
    "const program = new Command();",
    "",
    "program",
    "  .name('grpc-error-matrix')",
    "  .description('gRPC Error Code Matrix Tool')",
    "  .version('1.0.0');",
    "",
    "program",
    "  .command('parse')",
    "  .description('Parse proto file and extract error codes')",
    "  .requiredOption('-p, --proto <path>', 'proto file path')",
    "  .action((options) => {",
    "    const parser = new ProtoParser();",
    "    const result = parser.parse(options.proto);",
    "    console.log('Parsed:', result.file);",
    "    console.log('Packages:', result.packages.join(', '));",
    "    console.log('Error codes:', result.errorCodes.length);",
    "    console.log(result.errorCodes);",
    "  });",
    "",
    "program",
    "  .command('analyze')",
    "  .description('Analyze error codes and build matrix')",
    "  .requiredOption('-p, --proto <path>', 'proto file path')",
    "  .option('-s, --sdk <path>', 'SDK definitions JSON file')",
    "  .option('-o, --output <dir>', 'output directory', 'reports')",
    "  .action((options) => {",
    "    const parser = new ProtoParser();",
    "    const parseResult = parser.parse(options.proto);",
    "    let sdkDefinitions = {};",
    "    if (options.sdk && fs.existsSync(options.sdk)) {",
    "      sdkDefinitions = JSON.parse(fs.readFileSync(options.sdk, 'utf8'));",
    "    }",
    "    const builder = new MatrixBuilder();",
    "    const matrix = builder.buildMatrix(parseResult.errorCodes, sdkDefinitions);",
    "    const generator = new ReportGenerator();",
    "    console.log(generator.generateConsoleReport(matrix));",
    "    if (options.output) {",
    "      generator.generateAllReports(matrix, options.output);",
    "      console.log('Reports saved to:', options.output);",
    "    }",
    "  });",
    "",
    "program",
    "  .command('self-test')",
    "  .description('Self test all modules')",
    "  .action(() => {",
    "    try {",
    "      require('./proto-parser');",
    "      require('./matrix-builder');",
    "      require('./report-generator');",
    "      console.log('All modules loaded successfully!');",
    "    } catch (err) {",
    "      console.error('Self test failed:', err.message);",
    "      process.exit(1);",
    "    }",
    "  });",
    "",
    "program.parse(process.argv);"
  ];
 return lines.join('\n');
}

fs.writeFileSync(path.join(srcDir, 'matrix-builder.js'), createMatrixBuilder(), 'utf8');
fs.writeFileSync(path.join(srcDir, 'report-generator.js'), createReportGenerator(), 'utf8');
fs.writeFileSync(path.join(srcDir, 'cli.js'), createCli(), 'utf8');
console.log('All modules created!');
