import type { Plan, BoothObject, FloorSettings, AisleSettings } from './types';
import { generateId } from './objectLibrary';

export const EXAMPLE_PLANS: Plan[] = [
  {
    id: 'example_basic_booth',
    name: '基础标准摊位 (3m x 6m)',
    description: '适合小型展会的标准摊位布置示例',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    floor: {
      width: 6,
      depth: 3,
      gridSize: 0.5,
      showGrid: true,
      showAxes: true,
    } as FloorSettings,
    mainAisle: {
      minWidth: 1.2,
      color: { r: 255, g: 165, b: 0 },
    } as AisleSettings,
    featureWall: {
      position: { x: 0, y: 1.25, z: -1.45 },
      width: 5,
    },
    objects: [
      {
        id: generateId(),
        type: 'feature_wall',
        name: '主视觉墙',
        position: { x: 0, y: 1.25, z: -1.45 },
        rotation: 0,
        dimensions: { x: 5, y: 2.5, z: 0.1 },
        color: { r: 100, g: 149, b: 237 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'entrance',
        name: '入口',
        position: { x: -2, y: 0.05, z: 1.3 },
        rotation: 0,
        dimensions: { x: 1.5, y: 0.1, z: 0.5 },
        color: { r: 34, g: 139, b: 34 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'exit',
        name: '出口',
        position: { x: 2, y: 0.05, z: 1.3 },
        rotation: 0,
        dimensions: { x: 1.5, y: 0.1, z: 0.5 },
        color: { r: 178, g: 34, b: 34 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'table',
        name: '接待桌',
        position: { x: 0, y: 0.375, z: 0.8 },
        rotation: 90,
        dimensions: { x: 1.8, y: 0.75, z: 0.6 },
        color: { r: 139, g: 90, b: 43 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'display_rack',
        name: '左侧展架',
        position: { x: -2, y: 0.9, z: 0 },
        rotation: 90,
        dimensions: { x: 1.5, y: 1.8, z: 0.4 },
        color: { r: 200, g: 200, b: 200 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'display_rack',
        name: '右侧展架',
        position: { x: 2, y: 0.9, z: 0 },
        rotation: 90,
        dimensions: { x: 1.5, y: 1.8, z: 0.4 },
        color: { r: 200, g: 200, b: 200 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'cashier_desk',
        name: '收银台',
        position: { x: 1.5, y: 0.45, z: -0.5 },
        rotation: 90,
        dimensions: { x: 1.2, y: 0.9, z: 0.6 },
        color: { r: 60, g: 60, b: 60 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'safety_aisle',
        name: '主安全通道',
        position: { x: 0, y: 0.025, z: 0 },
        rotation: 0,
        dimensions: { x: 6, y: 0.05, z: 1.2 },
        color: { r: 255, g: 165, b: 0 },
      } as BoothObject,
    ],
  } as Plan,
  {
    id: 'example_corner_booth',
    name: '转角展位 (6m x 6m)',
    description: 'L型转角位置的展位布置示例，两侧开敞',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    floor: {
      width: 6,
      depth: 6,
      gridSize: 0.5,
      showGrid: true,
      showAxes: true,
    } as FloorSettings,
    mainAisle: {
      minWidth: 1.5,
      color: { r: 255, g: 165, b: 0 },
    } as AisleSettings,
    featureWall: {
      position: { x: -2.5, y: 1.5, z: -2.5 },
      width: 4,
    },
    objects: [
      {
        id: generateId(),
        type: 'feature_wall',
        name: '背景墙',
        position: { x: -2.5, y: 1.5, z: -2.5 },
        rotation: 45,
        dimensions: { x: 4, y: 3, z: 0.15 },
        color: { r: 70, g: 130, b: 180 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'entrance',
        name: '主入口',
        position: { x: 0, y: 0.05, z: 2.8 },
        rotation: 0,
        dimensions: { x: 2, y: 0.1, z: 0.4 },
        color: { r: 34, g: 139, b: 34 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'entrance',
        name: '侧入口',
        position: { x: 2.8, y: 0.05, z: 0 },
        rotation: 90,
        dimensions: { x: 2, y: 0.1, z: 0.4 },
        color: { r: 34, g: 139, b: 34 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'table',
        name: '中心展示桌A',
        position: { x: -1, y: 0.4, z: 0 },
        rotation: 0,
        dimensions: { x: 1.5, y: 0.8, z: 0.8 },
        color: { r: 139, g: 90, b: 43 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'table',
        name: '中心展示桌B',
        position: { x: 1, y: 0.4, z: 0 },
        rotation: 0,
        dimensions: { x: 1.5, y: 0.8, z: 0.8 },
        color: { r: 139, g: 90, b: 43 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'display_rack',
        name: '背景展架',
        position: { x: -2, y: 1, z: -1.5 },
        rotation: 0,
        dimensions: { x: 2, y: 2, z: 0.35 },
        color: { r: 180, g: 180, b: 180 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'cashier_desk',
        name: '收银台',
        position: { x: 1.5, y: 0.45, z: -1.5 },
        rotation: 90,
        dimensions: { x: 1.5, y: 0.9, z: 0.6 },
        color: { r: 80, g: 80, b: 80 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'power_outlet',
        name: '电源插座 A',
        position: { x: -2.5, y: 0.05, z: 2.5 },
        rotation: 0,
        dimensions: { x: 0.1, y: 0.1, z: 0.1 },
        color: { r: 255, g: 200, b: 0 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'power_outlet',
        name: '电源插座 B',
        position: { x: 2.5, y: 0.05, z: -2.5 },
        rotation: 0,
        dimensions: { x: 0.1, y: 0.1, z: 0.1 },
        color: { r: 255, g: 200, b: 0 },
      } as BoothObject,
    ],
  } as Plan,
  {
    id: 'example_problematic',
    name: '问题布置示例（用于测试检查功能）',
    description: '这个方案包含多个违规布置，用于演示规则检查功能',
    createdAt: Date.now(),
    updatedAt: Date.now(),
    floor: {
      width: 5,
      depth: 5,
      gridSize: 0.5,
      showGrid: true,
      showAxes: true,
    } as FloorSettings,
    mainAisle: {
      minWidth: 1.2,
      color: { r: 255, g: 165, b: 0 },
    } as AisleSettings,
    featureWall: {
      position: { x: 0, y: 1.25, z: -2.45 },
      width: 4,
    },
    objects: [
      {
        id: generateId(),
        type: 'feature_wall',
        name: '主视觉墙',
        position: { x: 0, y: 1.25, z: -2.45 },
        rotation: 0,
        dimensions: { x: 4, y: 2.5, z: 0.1 },
        color: { r: 100, g: 149, b: 237 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'entrance',
        name: '入口',
        position: { x: 0, y: 0.05, z: 2.3 },
        rotation: 0,
        dimensions: { x: 1.5, y: 0.1, z: 0.5 },
        color: { r: 34, g: 139, b: 34 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'exit',
        name: '出口',
        position: { x: -2, y: 0.05, z: 0 },
        rotation: 90,
        dimensions: { x: 1.5, y: 0.1, z: 0.5 },
        color: { r: 178, g: 34, b: 34 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'table',
        name: '桌子 A',
        position: { x: 0, y: 0.375, z: 0 },
        rotation: 0,
        dimensions: { x: 3, y: 0.75, z: 1 },
        color: { r: 139, g: 90, b: 43 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'table',
        name: '桌子 B (穿模)',
        position: { x: 0.5, y: 0.375, z: 0.3 },
        rotation: 45,
        dimensions: { x: 1.8, y: 0.75, z: 0.6 },
        color: { r: 139, g: 90, b: 43 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'display_rack',
        name: '遮挡视线的展架',
        position: { x: 0, y: 1, z: 1 },
        rotation: 0,
        dimensions: { x: 2, y: 2.2, z: 0.4 },
        color: { r: 200, g: 200, b: 200 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'cashier_desk',
        name: '收银台 (被堵)',
        position: { x: 1.5, y: 0.45, z: -1 },
        rotation: 90,
        dimensions: { x: 1.2, y: 0.9, z: 0.6 },
        color: { r: 60, g: 60, b: 60 },
      } as BoothObject,
      {
        id: generateId(),
        type: 'table',
        name: '超出边界的桌子',
        position: { x: 2.5, y: 0.375, z: 2 },
        rotation: 0,
        dimensions: { x: 2, y: 0.75, z: 0.8 },
        color: { r: 139, g: 90, b: 43 },
      } as BoothObject,
    ],
  } as Plan,
];

export function getExamplePlanById(id: string): Plan | undefined {
  return EXAMPLE_PLANS.find(p => p.id === id);
}

export function createDefaultPlan(): Plan {
  const now = Date.now();
  return {
    id: `plan_${now}`,
    name: '新方案',
    description: '',
    createdAt: now,
    updatedAt: now,
    floor: {
      width: 6,
      depth: 4,
      gridSize: 0.5,
      showGrid: true,
      showAxes: true,
    } as FloorSettings,
    mainAisle: {
      minWidth: 1.2,
      color: { r: 255, g: 165, b: 0 },
    } as AisleSettings,
    featureWall: {
      position: { x: 0, y: 1.25, z: -1.95 },
      width: 4,
    },
    objects: [],
  } as Plan;
}
