from typing import Dict, Set
from .models import TopologyData


class DiagramGenerator:
    def __init__(self, topology: TopologyData):
        self.topology = topology
        self.exchange_colors = {
            "direct": "#3498db",
            "topic": "#9b59b6",
            "fanout": "#2ecc71",
            "headers": "#e74c3c",
            "x-consistent-hash": "#f39c12"
        }

    def generate_mermaid(self) -> str:
        lines = [
            "%%{init: {'theme': 'neutral', 'themeVariables': {"
            "'fontSize': '14px'"
            "}} }%%",
            "graph TD",
            "    %% 样式定义",
            "    classDef exchange fill:#e3f2fd,stroke:#2196f3,stroke-width:2px,rounded;",
            "    classDef queue fill:#f3e5f5,stroke:#9c27b0,stroke-width:2px,rounded;",
            "    classDef binding fill:#fff,stroke:#ccc,stroke-width:1px;",
            "    classDef orphan fill:#ffebee,stroke:#f44336,stroke-width:2px,rounded,stroke-dasharray: 5 5;",
            ""
        ]
        
        lines.extend(self._generate_vhost_subgraphs())
        lines.extend(self._generate_connections())
        
        return '\n'.join(lines)

    def _generate_vhost_subgraphs(self) -> list:
        lines = []
        vhosts = self._get_all_vhosts()
        
        orphan_queues = set()
        orphan_exchanges = set()
        if hasattr(self, 'validation_result') and self.validation_result:
            orphan_queues = set(self.validation_result.orphan_queues)
            orphan_exchanges = set(self.validation_result.orphan_exchanges)
        
        for vhost in vhosts:
            vhost_safe = vhost.replace('/', '_').replace('-', '_')
            lines.append(f"    subgraph {vhost_safe} [\"Vhost: {vhost}\"]")
            lines.append(f"        direction TB")
            lines.append("")
            
            exchanges = [ex for ex in self.topology.exchanges if ex.vhost == vhost]
            for ex in exchanges:
                ex_id = self._safe_id(f"{vhost}_{ex.name}")
                ex_full_name = f"{vhost}/{ex.name}"
                is_orphan = ex_full_name in orphan_exchanges
                color = self.exchange_colors.get(ex.type.value, "#95a5a6")
                orphan_style = "orphan" if is_orphan else ""
                lines.append(
                    f"        {ex_id}[\"<b>{ex.name}</b><br/><i>{ex.type.value}</i>\"]"
                    f":::exchange{orphan_style}"
                )
            
            lines.append("")
            
            queues = [q for q in self.topology.queues if q.vhost == vhost]
            for q in queues:
                q_id = self._safe_id(f"{vhost}_{q.name}")
                q_full_name = f"{vhost}/{q.name}"
                is_orphan = q_full_name in orphan_queues
                orphan_style = "orphan" if is_orphan else ""
                lines.append(
                    f"        {q_id}[\"<b>{q.name}</b><br/><i>queue</i>\"]"
                    f":::queue{orphan_style}"
                )
            
            lines.append("    end")
            lines.append("")
        
        return lines

    def _generate_connections(self) -> list:
        lines = []
        
        for binding in self.topology.bindings:
            source_id = self._safe_id(f"{binding.vhost}_{binding.source}")
            
            if binding.destination_type == "exchange":
                dest_id = self._safe_id(f"{binding.vhost}_{binding.destination}")
            else:
                dest_id = self._safe_id(f"{binding.vhost}_{binding.destination}")
            
            if binding.routing_key:
                label = f"|{binding.routing_key}|"
            else:
                label = "|fanout|"
            
            lines.append(f"    {source_id} --> {label} {dest_id}")
        
        return lines

    def _get_all_vhosts(self) -> Set[str]:
        vhosts = set()
        for ex in self.topology.exchanges:
            vhosts.add(ex.vhost)
        for q in self.topology.queues:
            vhosts.add(q.vhost)
        for b in self.topology.bindings:
            vhosts.add(b.vhost)
        return sorted(vhosts)

    def _safe_id(self, name: str) -> str:
        safe = name.replace('/', '_').replace('-', '_').replace('.', '_')
        return safe.replace(' ', '_').replace(':', '_')

    def generate_vhost_diagram(self, vhost: str) -> str:
        lines = [
            f"%% RabbitMQ Topology Diagram - Vhost: {vhost}",
            "%% Generated by rabbitmq-topology-cli",
            "",
            "graph LR",
            ""
        ]
        
        vhost_exchanges = [ex for ex in self.topology.exchanges if ex.vhost == vhost]
        vhost_queues = [q for q in self.topology.queues if q.vhost == vhost]
        vhost_bindings = [b for b in self.topology.bindings if b.vhost == vhost]
        
        for ex in vhost_exchanges:
            color = self.exchange_colors.get(ex.type.value, "#95a5a6")
            ex_id = self._safe_id(ex.name)
            lines.append(f'    {ex_id}["{ex.name}<br/><font color="{color}">{ex.type.value}</font>"]')
        
        for q in vhost_queues:
            q_id = self._safe_id(q.name)
            lines.append(f'    {q_id}(("{q.name}"))')
        
        for binding in vhost_bindings:
            source_id = self._safe_id(binding.source)
            if binding.destination_type == "exchange":
                dest_id = self._safe_id(binding.destination)
            else:
                dest_id = self._safe_id(binding.destination)
            
            if binding.routing_key:
                lines.append(f'    {source_id} -- "{binding.routing_key}" --> {dest_id}')
            else:
                lines.append(f'    {source_id} --> {dest_id}')
        
        return '\n'.join(lines)
