import type { CounterExample, QuestionnaireRow, RunRecord } from "../types"

const now = new Date().toISOString()

export const normalMaterials: CounterExample[] = [
  {
    id: "ce-n-001",
    source: "normal",
    originalValue: 0.3,
    threshold: 1.0,
    deviation: -0.7,
    status: "normal",
    questionnaireRowId: "qr-001",
    conflictResolution: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ce-n-002",
    source: "normal",
    originalValue: 0.5,
    threshold: 1.5,
    deviation: -1.0,
    status: "normal",
    questionnaireRowId: "qr-002",
    conflictResolution: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ce-n-003",
    source: "normal",
    originalValue: 0.8,
    threshold: 2.0,
    deviation: -1.2,
    status: "normal",
    questionnaireRowId: "qr-003",
    conflictResolution: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ce-n-004",
    source: "normal",
    originalValue: 0.1,
    threshold: 0.7,
    deviation: -0.6,
    status: "normal",
    questionnaireRowId: "qr-004",
    conflictResolution: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ce-n-005",
    source: "normal",
    originalValue: 0.6,
    threshold: 1.8,
    deviation: -1.2,
    status: "normal",
    questionnaireRowId: "qr-005",
    conflictResolution: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ce-n-006",
    source: "normal",
    originalValue: 1.2,
    threshold: 1.2,
    deviation: 0,
    status: "boundary",
    questionnaireRowId: "qr-006",
    conflictResolution: null,
    createdAt: now,
    updatedAt: now,
  },
]

export const mismatchMaterials: CounterExample[] = [
  {
    id: "ce-m-001",
    source: "mismatch",
    originalValue: 1.5,
    threshold: 0.8,
    deviation: 0.7,
    status: "conflict",
    questionnaireRowId: "qr-007",
    conflictResolution: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ce-m-002",
    source: "mismatch",
    originalValue: 0.9,
    threshold: 1.4,
    deviation: -0.5,
    status: "normal",
    questionnaireRowId: "qr-008",
    conflictResolution: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ce-m-003",
    source: "mismatch",
    originalValue: 2.0,
    threshold: 0.5,
    deviation: 1.5,
    status: "conflict",
    questionnaireRowId: "qr-009",
    conflictResolution: "confirmed",
    createdAt: now,
    updatedAt: now,
  },
]

export const supplementaryMaterials: CounterExample[] = [
  {
    id: "ce-s-001",
    source: "supplementary",
    originalValue: 0.4,
    threshold: 1.0,
    deviation: -0.6,
    status: "normal",
    questionnaireRowId: "qr-010",
    conflictResolution: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ce-s-002",
    source: "supplementary",
    originalValue: 1.6,
    threshold: 1.6,
    deviation: 0,
    status: "boundary",
    questionnaireRowId: "qr-011",
    conflictResolution: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ce-s-003",
    source: "supplementary",
    originalValue: 0.7,
    threshold: 0.9,
    deviation: -0.2,
    status: "normal",
    questionnaireRowId: "qr-012",
    conflictResolution: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "ce-s-004",
    source: "supplementary",
    originalValue: 1.1,
    threshold: 0.6,
    deviation: 0.5,
    status: "pending_review",
    questionnaireRowId: null,
    conflictResolution: null,
    createdAt: now,
    updatedAt: now,
  },
]

export function createSampleQuestionnaireRows(): QuestionnaireRow[] {
  return [
    {
      id: "qr-001",
      rowIndex: 0,
      fields: { originalValue: 0.3, threshold: 1.0, label: "样本A" },
      matchedCounterExampleId: "ce-n-001",
    },
    {
      id: "qr-002",
      rowIndex: 1,
      fields: { originalValue: 0.5, threshold: 1.5, label: "样本B" },
      matchedCounterExampleId: "ce-n-002",
    },
    {
      id: "qr-003",
      rowIndex: 2,
      fields: { originalValue: 0.8, threshold: 2.0, label: "样本C" },
      matchedCounterExampleId: "ce-n-003",
    },
    {
      id: "qr-004",
      rowIndex: 3,
      fields: { originalValue: 0.1, threshold: 0.7, label: "样本D" },
      matchedCounterExampleId: "ce-n-004",
    },
    {
      id: "qr-005",
      rowIndex: 4,
      fields: { originalValue: 0.6, threshold: 1.8, label: "样本E" },
      matchedCounterExampleId: "ce-n-005",
    },
    {
      id: "qr-006",
      rowIndex: 5,
      fields: { originalValue: 1.2, threshold: 1.2, label: "边界样本F" },
      matchedCounterExampleId: "ce-n-006",
    },
    {
      id: "qr-007",
      rowIndex: 6,
      fields: { originalValue: 0.8, threshold: 0.8, label: "冲突样本G" },
      matchedCounterExampleId: "ce-m-001",
    },
    {
      id: "qr-008",
      rowIndex: 7,
      fields: { originalValue: 0.9, threshold: 1.4, label: "匹配样本H" },
      matchedCounterExampleId: "ce-m-002",
    },
    {
      id: "qr-009",
      rowIndex: 8,
      fields: { originalValue: 1.0, threshold: 0.5, label: "冲突样本I" },
      matchedCounterExampleId: "ce-m-003",
    },
    {
      id: "qr-010",
      rowIndex: 9,
      fields: { originalValue: 0.4, threshold: 1.0, label: "补充样本J" },
      matchedCounterExampleId: "ce-s-001",
    },
    {
      id: "qr-011",
      rowIndex: 10,
      fields: { originalValue: 1.6, threshold: 1.6, label: "补充边界K" },
      matchedCounterExampleId: "ce-s-002",
    },
    {
      id: "qr-012",
      rowIndex: 11,
      fields: { originalValue: 0.7, threshold: 0.9, label: "补充样本L" },
      matchedCounterExampleId: "ce-s-003",
    },
  ]
}

export function createSampleRunRecords(): RunRecord[] {
  return [
    {
      id: "run-001",
      mode: "normal",
      timestamp: now,
      counterExampleIds: normalMaterials.map(c => c.id),
      summary: {
        totalCounterExamples: normalMaterials.length,
        normalCount: normalMaterials.filter(c => c.status === "normal").length,
        boundaryCount: normalMaterials.filter(c => c.status === "boundary").length,
        conflictCount: normalMaterials.filter(c => c.status === "conflict").length,
        pendingReviewCount: normalMaterials.filter(c => c.status === "pending_review").length,
      },
    },
    {
      id: "run-002",
      mode: "mismatch",
      timestamp: now,
      counterExampleIds: mismatchMaterials.map(c => c.id),
      summary: {
        totalCounterExamples: mismatchMaterials.length,
        normalCount: mismatchMaterials.filter(c => c.status === "normal").length,
        boundaryCount: mismatchMaterials.filter(c => c.status === "boundary").length,
        conflictCount: mismatchMaterials.filter(c => c.status === "conflict").length,
        pendingReviewCount: mismatchMaterials.filter(c => c.status === "pending_review").length,
      },
    },
    {
      id: "run-003",
      mode: "supplementary",
      timestamp: now,
      counterExampleIds: supplementaryMaterials.map(c => c.id),
      summary: {
        totalCounterExamples: supplementaryMaterials.length,
        normalCount: supplementaryMaterials.filter(c => c.status === "normal").length,
        boundaryCount: supplementaryMaterials.filter(c => c.status === "boundary").length,
        conflictCount: supplementaryMaterials.filter(c => c.status === "conflict").length,
        pendingReviewCount: supplementaryMaterials.filter(c => c.status === "pending_review").length,
      },
    },
  ]
}
