spring:
  application:
    name: object-lifecycle-rule-api
  datasource:
    url: jdbc:h2:mem:lifecycle_db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.object.lifecycle: DEBUG
    org.springframework.web: INFO
