import * as fs from 'fs';
import * as path from 'path';
import { AuditResult } from './types';

export function writeAuditReport(auditResult: AuditResult, outputDir: string): void {
  writeMarkdownReport(auditResult, outputDir);
  writeViolationsCSV(auditResult, outputDir);
  writeProvenanceGraph(auditResult, outputDir);
}

function writeMarkdownReport(auditResult: AuditResult, outputDir: string): void {
  const filePath = path.join(outputDir, 'release_audit.md');
  const { summary, artifacts, provenances, violations, policy } = auditResult;
  
  const content = `# Release Audit Report

Generated on: ${new Date().toISOString()}

## Summary

| Metric | Value |
|--------|-------|
| Total Artifacts | ${summary.totalArtifacts} |
| Passed Checks | ${summary.passedChecks} |
| Failed Checks | ${summary.failedChecks} |
| Warnings | ${summary.warnings} |

## Policy

- Allowed Builders: ${policy.allowedBuilders.join(', ')}
- Allowed Licenses: ${policy.allowedLicenses.join(', ')}
- Signature Window: ${policy.signatureWindowHours} hours
- Strict Mode: ${policy.strict ? 'Yes' : 'No'}

## Artifacts

${artifacts.map(a => `### ${a.name}
- Type: ${a.type}
- Digest: \`${a.digest}\`
- Tags: ${a.tags ? a.tags.join(', ') : 'None'}
`).join('\n')}

## Violations

### Errors (${violations.filter(v => v.severity === 'error').length})

${violations.filter(v => v.severity === 'error').length > 0 
  ? violations.filter(v => v.severity === 'error').map(v => `- **${v.rule}**${v.artifactName ? ` (${v.artifactName})` : ''}: ${v.message}`).join('\n')
  : 'None'}

### Warnings (${violations.filter(v => v.severity === 'warning').length})

${violations.filter(v => v.severity === 'warning').length > 0 
  ? violations.filter(v => v.severity === 'warning').map(v => `- **${v.rule}**${v.artifactName ? ` (${v.artifactName})` : ''}: ${v.message}`).join('\n')
  : 'None'}

## Provenance Attestations

${provenances.map((p, idx) => `### Attestation ${idx + 1}
- Builder: ${p.predicate.builder.id}
- Build Type: ${p.predicate.buildType}
- Subjects: ${p.subject.map(s => s.name || s.digest).join(', ')}
- Started: ${p.predicate.metadata?.buildStartedOn || 'Unknown'}
- Finished: ${p.predicate.metadata?.buildFinishedOn || 'Unknown'}
`).join('\n')}

---
*Report generated by release-audit-cli*
`;

  fs.writeFileSync(filePath, content);
}

function writeViolationsCSV(auditResult: AuditResult, outputDir: string): void {
  const filePath = path.join(outputDir, 'violations.csv');
  const { violations } = auditResult;

  const headers = ['artifact_name', 'rule', 'severity', 'message'];
  const rows = violations.map(v => [
    v.artifactName || '',
    v.rule,
    v.severity,
    v.message
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell.replace(/"/g, '""')}"`).join(','))
  ].join('\n');

  fs.writeFileSync(filePath, csvContent);
}

function writeProvenanceGraph(auditResult: AuditResult, outputDir: string): void {
  const filePath = path.join(outputDir, 'provenance_graph.html');
  const { artifacts, provenances, violations } = auditResult;

  const nodes = [];
  const links = [];
  
  artifacts.forEach((a, i) => {
    nodes.push({
      id: `artifact-${i}`,
      label: a.name,
      group: 'artifact',
      digest: a.digest
    });
  });

  provenances.forEach((p, i) => {
    nodes.push({
      id: `provenance-${i}`,
      label: `Builder: ${p.predicate.builder.id.split('/').pop()}`,
      group: 'builder',
      builderId: p.predicate.builder.id
    });
    
    p.subject.forEach(subj => {
      const digest = Object.values(subj.digest)[0];
      const artifactIdx = artifacts.findIndex(a => a.digest === digest);
      if (artifactIdx !== -1) {
        links.push({
          source: `provenance-${i}`,
          target: `artifact-${artifactIdx}`
        });
      }
    });

    if (p.predicate.materials) {
      p.predicate.materials.forEach((mat, j) => {
        const matId = `material-${i}-${j}`;
        nodes.push({
          id: matId,
          label: mat.uri?.split('/').pop() || 'material',
          group: 'material'
        });
        links.push({
          source: matId,
          target: `provenance-${i}`
        });
      });
    }
  });

  const content = `<!DOCTYPE html>
<html>
<head>
  <title>Provenance Graph</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 20px; background: #f5f5f5; }
    .container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
    h1 { color: #333; margin-bottom: 20px; }
    .legend { margin-bottom: 20px; display: flex; gap: 20px; }
    .legend-item { display: flex; align-items: center; gap: 8px; }
    .legend-color { width: 16px; height: 16px; border-radius: 50%; }
    .artifact { background: #4CAF50; }
    .builder { background: #2196F3; }
    .material { background: #FF9800; }
    canvas { border: 1px solid #ddd; border-radius: 4px; width: 100%; height: 600px; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Provenance Graph</h1>
    <div class="legend">
      <div class="legend-item"><div class="legend-color artifact"></div> Artifact</div>
      <div class="legend-item"><div class="legend-color builder"></div> Builder</div>
      <div class="legend-item"><div class="legend-color material"></div> Material</div>
    </div>
    <canvas id="graph"></canvas>
  </div>
  
  <script>
    const nodes = ${JSON.stringify(nodes)};
    const links = ${JSON.stringify(links)};
    
    const canvas = document.getElementById('graph');
    const ctx = canvas.getContext('2d');
    
    function resize() {
      canvas.width = canvas.offsetWidth;
      canvas.height = 600;
    }
    resize();
    window.addEventListener('resize', resize);
    
    const colors = {
      artifact: '#4CAF50',
      builder: '#2196F3',
      material: '#FF9800'
    };
    
    let pos = {};
    nodes.forEach((n, i) => {
      pos[n.id] = {
        x: 100 + Math.random() * (canvas.width - 200),
        y: 100 + Math.random() * (canvas.height - 200),
        vx: 0,
        vy: 0
      };
    });
    
    function simulate() {
      const dt = 0.5;
      const damping = 0.9;
      const repel = 5000;
      const attract = 0.01;
      
      nodes.forEach(ni => {
        const pi = pos[ni.id];
        nodes.forEach(nj => {
          if (ni.id === nj.id) return;
          const pj = pos[nj.id];
          const dx = pi.x - pj.x;
          const dy = pi.y - pj.y;
          const dist = Math.sqrt(dx * dx + dy * dy) || 1;
          const force = repel / (dist * dist);
          pi.vx += (dx / dist) * force;
          pi.vy += (dy / dist) * force;
        });
      });
      
      links.forEach(link => {
        const ps = pos[link.source];
        const pt = pos[link.target];
        const dx = pt.x - ps.x;
        const dy = pt.y - ps.y;
        const dist = Math.sqrt(dx * dx + dy * dy) || 1;
        const force = dist * attract;
        ps.vx += (dx / dist) * force;
        ps.vy += (dy / dist) * force;
        pt.vx -= (dx / dist) * force;
        pt.vy -= (dy / dist) * force;
      });
      
      nodes.forEach(n => {
        const p = pos[n.id];
        p.vx *= damping;
        p.vy *= damping;
        p.x += p.vx * dt;
        p.y += p.vy * dt;
        p.x = Math.max(30, Math.min(canvas.width - 30, p.x));
        p.y = Math.max(30, Math.min(canvas.height - 30, p.y));
      });
    }
    
    function draw() {
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      
      ctx.strokeStyle = '#999';
      ctx.lineWidth = 2;
      links.forEach(link => {
        const ps = pos[link.source];
        const pt = pos[link.target];
        ctx.beginPath();
        ctx.moveTo(ps.x, ps.y);
        ctx.lineTo(pt.x, pt.y);
        ctx.stroke();
      });
      
      nodes.forEach(n => {
        const p = pos[n.id];
        ctx.beginPath();
        ctx.arc(p.x, p.y, 20, 0, 2 * Math.PI);
        ctx.fillStyle = colors[n.group];
        ctx.fill();
        ctx.strokeStyle = '#333';
        ctx.lineWidth = 2;
        ctx.stroke();
        
        ctx.fillStyle = '#333';
        ctx.font = '12px sans-serif';
        ctx.textAlign = 'center';
        ctx.fillText(n.label, p.x, p.y + 40);
      });
    }
    
    function animate() {
      for (let i = 0; i < 10; i++) simulate();
      draw();
      requestAnimationFrame(animate);
    }
    animate();
  </script>
</body>
</html>`;

  fs.writeFileSync(filePath, content);
}
