const ApplicationStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  IN_PROGRESS: 'IN_PROGRESS',
  EXTENSION_PENDING: 'EXTENSION_PENDING',
  EXTENSION_APPROVED: 'EXTENSION_APPROVED',
  EXTENSION_REJECTED: 'EXTENSION_REJECTED',
  WITHDRAWAL_PENDING: 'WITHDRAWAL_PENDING',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED'
};

const ExtensionStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

const WithdrawalStatus = {
  PENDING: 'PENDING',
  INSPECTING: 'INSPECTING',
  PASSED: 'PASSED',
  FAILED: 'FAILED',
  REINSPECTION_PENDING: 'REINSPECTION_PENDING'
};

const FineStatus = {
  PENDING: 'PENDING',
  ISSUED: 'ISSUED',
  PAID: 'PAID',
  WAIVED: 'WAIVED',
  DISPUTED: 'DISPUTED'
};

const RoadSectionStatus = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  PARTIALLY_OCCUPIED: 'PARTIALLY_OCCUPIED',
  MAINTENANCE: 'MAINTENANCE'
};

const TaskStatus = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  RETRYABLE: 'RETRYABLE'
};

const TaskType = {
  APPROVE_EXTENSION: 'APPROVE_EXTENSION',
  ISSUE_FINE: 'ISSUE_FINE',
  SEND_NOTIFICATION: 'SEND_NOTIFICATION',
  GENERATE_REPORT: 'GENERATE_REPORT',
  RECALCULATE_STATUS: 'RECALCULATE_STATUS'
};

const FineRuleType = {
  OVERTIME: 'OVERTIME',
  DAMAGE: 'DAMAGE',
  SAFETY_VIOLATION: 'SAFETY_VIOLATION',
  DOCUMENTATION: 'DOCUMENTATION'
};

module.exports = {
  ApplicationStatus,
  ExtensionStatus,
  WithdrawalStatus,
  FineStatus,
  RoadSectionStatus,
  TaskStatus,
  TaskType,
  FineRuleType
};
