package com.example.readonlywindow.entity;

public enum EventType {
    WINDOW_CREATED,
    WINDOW_ACTIVATED,
    WINDOW_SUSPENDED,
    WINDOW_CANCELLED,
    WINDOW_COMPLETED,
    WRITE_REQUESTED,
    EXCEPTION_APPROVED,
    EXCEPTION_REJECTED,
    CONFLICT_DETECTED,
    CREDENTIAL_ISSUED,
    CREDENTIAL_USED,
    STATUS_CHANGED
}
