import os
import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from jinja2 import Template
from .yaml_loader import YamlLoaderWithLineInfo, LoadedValues, ValueSource, deep_merge


SENSITIVE_KEYS = {'password', 'secret', 'token', 'api_key', 'apikey', 'private_key'}


def mask_sensitive_value(key: str, value: Any) -> Any:
    if isinstance(value, dict):
        return {k: mask_sensitive_value(k, v) for k, v in value.items()}
    if isinstance(value, list):
        return [mask_sensitive_value(str(i), v) for i, v in enumerate(value)]
    key_lower = key.lower()
    for s in SENSITIVE_KEYS:
        if s in key_lower:
            return '********'
    return value


@dataclass
class ValueOverrideChain:
    key: str
    sources: List[ValueSource] = field(default_factory=list)
    
    def add_source(self, source: ValueSource):
        self.sources.append(source)
    
    @property
    def current_value(self) -> Any:
        if self.sources:
            return self.sources[-1].value
        return None
    
    @property
    def is_overridden(self) -> bool:
        return len(self.sources) > 1


HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Helm Values Audit Report</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }
        h1 { color: #333; border-bottom: 2px solid #eee; padding-bottom: 10px; }
        .file-list { background: #f8f9fa; padding: 15px; border-radius: 8px; margin: 20px 0; }
        .file-ok { color: #28a745; }
        .file-error { color: #dc3545; }
        .override-chain { background: #fff; border: 1px solid #dee2e6; border-radius: 8px; margin: 10px 0; padding: 15px; }
        .key-name { font-weight: bold; font-size: 1.1em; color: #007bff; }
        .source-item { padding: 5px 10px; margin: 3px 0; border-left: 3px solid #6c757d; }
        .source-final { border-left-color: #28a745; font-weight: bold; }
        .file-label { color: #6c757d; font-size: 0.9em; }
        .sensitive-badge { background: #ffc107; color: #333; padding: 2px 8px; border-radius: 12px; font-size: 0.8em; margin-left: 10px; }
        .errors-section { background: #f8d7da; border: 1px solid #f5c6cb; border-radius: 8px; padding: 15px; margin: 20px 0; }
        .error-item { font-family: monospace; padding: 8px; background: #fff; margin: 5px 0; border-radius: 4px; }
    </style>
</head>
<body>
    <h1>&#128270; Helm Values 覆盖审计报告</h1>
    
    <h2>&#128193; 加载的文件</h2>
    <div class="file-list">
        {% for file in files %}
        <div>
            {% if file.is_valid %}
            <span class="file-ok">&#10004;</span>
            {% else %}
            <span class="file-error">&#10008;</span>
            {% endif %}
            {{ file.path }}
        </div>
        {% endfor %}
    </div>
    
    {% if errors %}
    <div class="errors-section">
        <h2>&#9888; 解析错误</h2>
        {% for err in errors %}
        <div class="error-item">
            <strong>{{ err.file_path }}</strong>
            {% if err.line_number %}:{{ err.line_number }}{% endif %}
            <br>{{ err.message }}
            {% if err.raw_content %}<br><code>{{ err.raw_content }}</code>{% endif %}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    
    <h2>&#128279; 值覆盖链 (共 {{ chains|length }} 个键)</h2>
    {% for chain in chains %}
    <div class="override-chain">
        <div class="key-name">
            {{ chain.key }}
            {% if chain.is_sensitive %}<span class="sensitive-badge">敏感值</span>{% endif %}
        </div>
        {% for src in chain.sources %}
        <div class="source-item {% if loop.last %}source-final{% endif %}">
            {{ src.value }}
            <span class="file-label">@ {{ src.file_path }} {% if src.line_number %}#L{{ src.line_number }}{% endif %}</span>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
    
    <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; color: #6c757d; font-size: 0.9em;">
        Generated by helm-value-auditor
    </footer>
</body>
</html>
"""


class HelmValuesAuditor:
    def __init__(self):
        self.loader = YamlLoaderWithLineInfo()
        self.loaded_files: List[LoadedValues] = []
        self.override_chains: Dict[str, ValueOverrideChain] = {}
        self.merged_values: Dict[str, Any] = {}
    
    def load_files(self, file_paths: List[str]):
        for path in file_paths:
            result = self.loader.load_with_source_tracking(path)
            self.loaded_files.append(result)
            
            if result.is_valid:
                for key, source in result.sources.items():
                    if key not in self.override_chains:
                        self.override_chains[key] = ValueOverrideChain(key=key)
                    self.override_chains[key].add_source(source)
                
                self.merged_values = deep_merge(self.merged_values, result.values)
    
    def load_values_files(self, file_paths: List[str]):
        self.load_files(file_paths)
    
    def get_sensitive_keys(self) -> List[str]:
        sensitive = []
        for key in self.override_chains:
            key_lower = key.lower()
            for s in SENSITIVE_KEYS:
                if s in key_lower and key not in sensitive:
                    sensitive.append(key)
        return sensitive
    
    def get_overridden_keys(self) -> List[ValueOverrideChain]:
        return [c for c in self.override_chains.values() if c.is_overridden]
    
    def get_errors(self) -> List:
        errors = []
        for f in self.loaded_files:
            errors.extend(f.errors)
        return errors
    
    def generate_terminal_summary(self) -> str:
        lines = []
        lines.append('=' * 80)
        lines.append('HELM VALUES AUDIT SUMMARY')
        lines.append('=' * 80)
        lines.append('')
        
        lines.append(f'Files loaded: {len(self.loaded_files)}')
        for f in self.loaded_files:
            status = '[OK]' if f.is_valid else '[ERROR]'
            lines.append(f'  {status} {f.file_path}')
        lines.append('')
        
        overridden = self.get_overridden_keys()
        lines.append(f'Overridden keys: {len(overridden)}')
        for chain in overridden:
            lines.append(f'  {chain.key}:')
            for i, src in enumerate(chain.sources):
                prefix = '->' if i == len(chain.sources) - 1 else '  '
                val = mask_sensitive_value(chain.key, src.value)
                lines.append(f'       {prefix} {val} @ {os.path.basename(src.file_path)}')
        lines.append('')
        
        sensitive = self.get_sensitive_keys()
        lines.append(f'Sensitive keys found: {len(sensitive)}')
        for k in sensitive:
            lines.append(f'  {k}')
        lines.append('')
        
        errors = self.get_errors()
        if errors:
            lines.append(f'Parse errors: {len(errors)}')
            for e in errors:
                lines.append(f'  {e.file_path}:{e.line_number or "?"}:{e.column or "?"}')
                lines.append(f'    {e.message}')
                if e.raw_content:
                    lines.append(f'    {e.raw_content}')
            lines.append('')
        
        lines.append('=' * 80)
        return '\n'.join(lines)
    
    def print_terminal_summary(self):
        print(self.generate_terminal_summary())
    
    def generate_json_report(self) -> str:
        report = {
            'files_loaded': [f.file_path for f in self.loaded_files],
            'merged_values': mask_sensitive_value('root', self.merged_values),
            'override_chains': [
                {
                    'key': c.key,
                    'is_sensitive': any(s in c.key.lower() for s in SENSITIVE_KEYS),
                    'sources': [
                        {
                            'file_path': s.file_path,
                            'line_number': s.line_number,
                            'value': mask_sensitive_value(c.key, s.value)
                        } for s in c.sources
                    ]
                } for c in self.override_chains.values()
            ],
            'errors': [
                {
                    'file_path': e.file_path,
                    'line_number': e.line_number,
                    'column': e.column,
                    'message': e.message,
                    'raw_content': e.raw_content
                } for e in self.get_errors()
            ]
        }
        return json.dumps(report, indent=2, ensure_ascii=False)
    
    def generate_html_report(self) -> str:
        template = Template(HTML_TEMPLATE)
        chains_data = []
        for c in self.override_chains.values():
            is_sensitive = any(s in c.key.lower() for s in SENSITIVE_KEYS)
            chains_data.append({
                'key': c.key,
                'is_sensitive': is_sensitive,
                'sources': [
                    {
                        'file_path': os.path.basename(s.file_path),
                        'line_number': s.line_number,
                        'value': mask_sensitive_value(c.key, s.value)
                    } for s in c.sources
                ]
            })
        
        files_data = [
            {'path': f.file_path, 'is_valid': f.is_valid}
            for f in self.loaded_files
        ]
        
        errors_data = self.get_errors()
        
        return template.render(
            files=files_data,
            chains=chains_data,
            errors=errors_data
        )
