"""配置模块"""
import os
from datetime import datetime

DB_FILENAME = "allocation.db"

NEAR_EXPIRY_DAYS = 90
CRITICAL_EXPIRY_DAYS = 30

WAREHOUSE_STORAGE_COST_PER_DAY = 0.01

STORAGE_TYPE_NORMAL = "normal"
STORAGE_TYPE_COLD = "cold"
STORAGE_TYPE_FROZEN = "frozen"

STATUS_PENDING = "pending"
STATUS_APPROVED = "approved"
STATUS_COMPLETED = "completed"
STATUS_REJECTED = "rejected"
STATUS_CANCELLED = "cancelled"
STATUS_FAILED = "failed"

ALLOWED_STATUS_TRANSITIONS = {
    STATUS_PENDING: [STATUS_APPROVED, STATUS_REJECTED, STATUS_CANCELLED],
    STATUS_APPROVED: [STATUS_COMPLETED, STATUS_CANCELLED, STATUS_FAILED],
}
